### ISSUE TITLE
Sound and vibration when showing the notification

### ISSUE THREAD

**Issue by samapraku** [MaikuB/flutter_local_notifications#1]
Hello,

Is there a way to configure sound and or vibrations in android when displaying the notification?

I see the IOS initial settings allow to pass a sound and badge values on initial settings but the android part only takes default icon.

Thanks

**Comment by MaikuB** [comment]
Not at the moment. I may look into adding that in as for iOS I haven't actually allowed it to configure the sound either or even play the default

**Comment by MaikuB** [comment]
@samapraku I've released a new version that hopefully should be what you're after.  Check it out

**Comment by samapraku** [comment]
Yeah great! I've seen the example. I'll implement it in my app and see.

Thanks for you efforts

**Comment by rishab2890** [comment]
not able to play custom sound from notification
