### ISSUE TITLE
Is there a way to put notification to the background (hide it) while the app is in foreground?

### ISSUE THREAD

**Issue by sooxt98** [MaikuB/flutter_local_notifications#1001]
I have search thru every possible settings like `IOSNotificationDetails` , and cant find a way to hide it

**Comment by MaikuB** [comment]
No as what you've described is application logic. Whether or not a notification appears is based on the `presentAlert` setting so you'd need if you can make use of that, though to do what you're after may possibly even require you to write all of the code to handle this on the iOS side in Objective C or Swift
