### ISSUE TITLE
zonedSchedule triggered early than expected even if given future time with repeat interval set

### ISSUE THREAD

**Issue by LunaticXJ** [MaikuB/flutter_local_notifications#1007]
zonedSchedule will validate the scheduleDate and make sure it's future time，but when i want repeat daily from tomorrow and set scheduleDate time at tomorrow, it just triggered today！

**Comment by JayDev43** [comment]
I've noticed this too. 

My scenarios are:
- Set for daily, but start tomorrow (But it still runs today). Example below
```dart
Future<void> applyNotification(final Notification notification) {
  final nextInstance = _nextInstanceOfTime(DateTime.now().add(const Duration(seconds: 30)), true);
  
  await _localNotificationsPlugin.zonedSchedule(
        notification.id,
        notification.title,
        notification.message,
        nextInstance,
        const NotificationDetails(android: androidPlatformChannelSpecifics),
        androidAllowWhileIdle: true,
        uiLocalNotificationDateInterpretation:
            UILocalNotificationDateInterpretation.absoluteTime,
        matchDateTimeComponents: DateTimeComponents.time
  
  );
}

tz.TZDateTime _nextInstanceOfTime(
      final DateTime startDateTime, final bool ignoreToday) {
    final tz.TZDateTime now = tz.TZDateTime.now(tz.local);
    tz.TZDateTime scheduledDate = tz.TZDateTime(tz.local, now.year, now.month,
        now.day, startDateTime.hour, startDateTime.minute);
    if (scheduledDate.isBefore(now) ||
        (ignoreToday && _isSameDay(now, scheduledDate))) {
      scheduledDate = scheduledDate.add(const Duration(days: 1));
    }
    return scheduledDate;
  }

bool _isSameDay(final tz.TZDateTime now, final tz.TZDateTime date) {
    return now.year == date.year &&
        now.month == date.month &&
        now.day == now.day;
  }
```

- Set for weekly, but start next week (But it still runs today). The code is similar to the daily example except the nextInstance is calculated different and matchDateTimeComponents is DateTimeComponents.dayOfWeekAndTime.

What I'm not sure of though, is whether this is a bug in the Flutter library, or if this is just how the underlying iOS and Android libraries work and what I'm attempting to do is just not possible?

**Comment by MaikuB** [comment]
This is working as expected as it's not a repeat interval and this is reflected in the naming. the name of the argument is around matching parts of the date and time, which means it only uses those components to have a recurring notification. This is why the 4.0 prerelease has a change to allow a date in the past to be used. There isn't a native notification API that allows one to schedule a notification on a particular date and have it repeat on a specified interval. See https://developer.apple.com/documentation/usernotifications/uncalendarnotificationtrigger that's used for iOS, which is all about matching components of a date. A one-off notification is actually one that makes use of this class that matches on all components

**Comment by JayDev43** [comment]
Understood. I'd looked into the AlarmManager API for Android and it seemed feasible, but I hadn't got time to look into the iOS implementation, hence the question of whether this was a native library issue.
