### ISSUE TITLE
App crash on build with error faild to find plaform sdk 30

### ISSUE THREAD

**Issue by AdelKanso** [MaikuB/flutter_local_notifications#1009]
I'm running the app on emulator with android API 29 and Huawei android 10, the app crash producing this error:
Could not determine the dependencies of task :flutter_local_notifications: compileDebugAidl
Faild to find platform SDK with path: platforms;android-30
Exception: Gradle task assembleDebug failed

Note: App build and work perfectly on emulator with android API 30 and Tecno Camon 16 android 10

**Comment by MaikuB** [comment]
Build issues aren't app crashes. Crashes are for when the app is running then stops. If you do a search for your error (i.e.. Faild to find platform SDK with path: platforms;android-30) then this is to do with your dev environment missing a SDK and is implied by the error as well so it isn't to do with the plugin.

For future reference, any bug reports must use the bug report template and provide the details mentioned it or I will be closing the issue.
