### ISSUE TITLE
flutter SDK  NOT FOUND

### ISSUE THREAD

**Issue by DipenBhagat** [MaikuB/flutter_local_notifications#101]
In android,i got flutter sdk not found
how can i implement this plugin successfully in android studio?

**Comment by MaikuB** [comment]
First time I've heard of this error and sounds like an issue with your environment. Are you about to get a basic app to run and have you checked for similar issues on the Flutter repository e.g. https://github.com/flutter/flutter/issues/13860

**Comment by MaikuB** [comment]
Closing this due having but had a response for a long time. Feel free to reopen if you still have problems
