### ISSUE TITLE
onSelectNotification doesn't work in the background

### ISSUE THREAD

**Issue by OmarYehiaDev** [MaikuB/flutter_local_notifications#1012]
Hello there. I wanna launch specific screen when the user clicks on the notification so my code became like this :-
```
onSelectNotification: (String payload) async {
      if (payload != null) {
        debugPrint(
          "Notification Payload:- $payload",
        );
        if (payload == "New Offer") {
          Navigator.of(_key.currentContext).push(
            MaterialPageRoute(
              builder: (context) => HotOffers(),
            ),
          );
        }
      }
    },
```
This code works good when in the foreground but when I click on the notification and the app is in the background, nothing happens except opening on the home screen and I don't want this to happen. So is there any way to make specific calls when the user clicks on the notification or not??
***I'm using FCM with the pacakge***

**Comment by OmarYehiaDev** [comment]
> Hello there. I wanna launch specific screen when the user clicks on the notification so my code became like this :-
> 
> ```
> onSelectNotification: (String payload) async {
>       if (payload != null) {
>         debugPrint(
>           "Notification Payload:- $payload",
>         );
>         if (payload == "New Offer") {
>           Navigator.of(_key.currentContext).push(
>             MaterialPageRoute(
>               builder: (context) => HotOffers(),
>             ),
>           );
>         }
>       }
>     },
> ```
> 
> This code works good when in the foreground but when I click on the notification and the app is in the background, nothing happens except opening on the home screen and I don't want this to happen. So is there any way to make specific calls when the user clicks on the notification or not??
> **_I'm using FCM with the package_**

**Comment by OmarYehiaDev** [comment]
I've solved it.

**Comment by jonbhanson** [comment]
@OmarYehiaDev can you describe your solution?  I'm having this same problem.

**Comment by OmarYehiaDev** [comment]
> @OmarYehiaDev can you describe your solution?  I'm having this same problem.

All i'd done is depending on the callbacks of FCM package then defining a payload from the firebase console. Also i've made a custom method channel for my notifications. That's all i'd done

**Comment by jonbhanson** [comment]
Thanks for your response @OmarYehiaDev but unfortunately I don't understand.  If the user clicks on a message that was generated by the flutter_local_notifications package, how will the FCM callback be triggered?  Can you give some code samples?  Thanks!

**Comment by OmarYehiaDev** [comment]
> Thanks for your response @OmarYehiaDev but unfortunately I don't understand.  If the user clicks on a message that was generated by the flutter_local_notifications package, how will the FCM callback be triggered?  Can you give some code samples?  Thanks!

Unfortunately my laptop is being repaired so i can't provide u any code snippets. I'm using flutter_local_notifications as a package to display the notifications i receive from firebase. So i'm triggering the notifications in the "onMessage" and "onResume" and "onLaunch" then i display them through the plugin and I'm not using "onSelectNotification" callback
