### ISSUE TITLE
Timeot cannot be set less than 4 seconds

### ISSUE THREAD

**Issue by bambinoua** [MaikuB/flutter_local_notifications#1014]
If set `timeoutAfter` to value less than 4000 ms it does not respect it.

**Comment by MaikuB** [comment]
For issues like this, please use the bug report template and provide everything that's requested in there. The example app has code that specifies 3 seconds and from what I've seen works as expected. The native APIs don't document any restrictions on this either and if you happen to have run into a device-specific issue then there's nothing that the plugin can do about this as this is up to the native notification APIs to handle
