### ISSUE TITLE
Scheduled notifications that have been presented still show as pending

### ISSUE THREAD

**Issue by nicknma** [MaikuB/flutter_local_notifications#1015]
>     final d= _nextInstanceOfSelectedTime(hour, minute);
    final days = List<int>.generate(2, (int index) => index);
    Future.forEach(days, (day) async{
      final dd = d.add(Duration(days: day));
      await _notificationsPlugin.zonedSchedule(
        day,
        '$dd',
        '$dd',
        dd,
        notificationDetails,
        payload: '$dd',
        androidAllowWhileIdle: true,
        uiLocalNotificationDateInterpretation:UILocalNotificationDateInterpretation.absoluteTime,
        matchDateTimeComponents: DateTimeComponents.dayOfWeekAndTime,
      );
    });

1-Create two scheduled notifications for two consecutive days (I set the first one to be presented in a minute so I can test).
2-Call pendingNotificationRequests() and you'll get two notifications.
3-After the first notification is presented.
4-Call pendingNotificationRequests() again and you still see two pending notifications although the one that was presented shows at the bottom.

Is there a way to clear the notifications that were presented?

**Comment by MaikuB** [comment]
By specifying ` matchDateTimeComponents: DateTimeComponents.dayOfWeekAndTime`, you have configured recurring notifications so what you're seeing is expected. They're going to repeat so there will always be pending notifications. This is how the native APIs work and as far as I know, the native APIs don't have anyway of doing what you're after

**Comment by phamquoctrongnta** [comment]
@MaikuB 
I scheduled 50 next days start from 26/06/2024.
I mock set current day on device to 03/07/2024.
Then I call `pendingNotificationRequests` still return 50 pending schedule? Why?
p/s: Sorry my bad English
