### ISSUE TITLE
Notifications are not comming on Android 5 and 6 when the app is in background or closed

### ISSUE THREAD

**Issue by xjerryg** [MaikuB/flutter_local_notifications#1016]
Hi, I'm using the package in my project and notifications are not working on Android 5 and 6. I tested also the official example with the same results. I know that the operating system and modifications of manufacturers may cause it because of the battery saving, but anyway I want to be sure. So:

- I have two phones: Xiaomi Mi-4c with Android 5.1.1 and Honor PLK-L01 with Android 6
- On both phones I went through the settings and turn off all power saving modes and give the app rights to run on background
- I'm testing with your example project
- When I "schedule notification to appear in 5 seconds" and let the app on foreground, the notification it is displayed
- When I "schedule notification to appear in 5 seconds" and put the app to background, the notification it is displayed
- When I "schedule notification to appear in 5 seconds" and close the app, the notification it is not displayed

My questions are:
- Is it standard behaviour? Do you think that I may do anything to make it work even when the app is closed? E.g. give the phone user some advice what to set in the settings? (something what I'm still missing)
- I tested it also on several phones with Android 9 and 10 where it works perfectly. What may I expect on Android 7 and 8? I do not have these and I'm thinking to stop support of my app for Android 6 and lower. But will it work on 7 and 8?

Thank you.
Jaromir

**Comment by MaikuB** [comment]
> Is it standard behaviour? Do you think that I may do anything to make it work even when the app is closed? E.g. give the phone user some advice what to set in the settings? (something what I'm still missing)

As you already mentioned, this is to do with the manufacturers and I don't have phones from these companies. So any issue you have is to do with how their phones work. The restrictions will mean it will be standard behaviour. As I don't have these phones, I don't know if there will be settings you can turn on that you may have missed. Even if there were, it could vary from one manufacturer to another. You'd best ask elsewhere when it comes to how apps handle these settings as being a maintainer of a notifications plugin doesn't necessarily mean I'm expert on that subject, especially when manufacturers can customise Android to suit their needs. Chances are that users of these phones are already used to this behaviour as I've even seen tutorials on turning on certain settings e.g. https://threema.ch/en/faq/notification_channels_xiaomi

> I tested it also on several phones with Android 9 and 10 where it works perfectly. What may I expect on Android 7 and 8? I do not have these and I'm thinking to stop support of my app for Android 6 and lower. But will it work on 7 and 8?

In general, this all depends on the manufacturers and the restrictions they've put on. So if they haven't put restrictions then it'll work. It's not to do with Android version and Android SDK allows you to create emulators for different versions of the stock Android OS that you can use to check
