### ISSUE TITLE
App Icon in notification is empty : shown as grey square

### ISSUE THREAD

**Issue by abaturyna** [MaikuB/flutter_local_notifications#1017]
Hi, 

Problem is : app_icon is under android/app/main/res/drawable/app_icon.png and when notification triggers - image is empty in it! 

STEPS TO REPRODUCE : 
1. Add icon on path android/app/main/res/drawable/app_icon.png
2. Trigger notification on Android
3. App icon is not shown, grey square instead of it

**Comment by MaikuB** [comment]
If you have an issue with the icon then either you haven't changed it correctly the way Android expects it (you'll need to check their docs on this e.g. if all of is non-transparent then I believe you may have issues) or hadn't follow all the steps in the readme as I explicitly warned that not setting it up properly may mean the icon won't appear as expected [here](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#release-build-configuration). There's no issue with the plugin when it comes to the icon as the steps you describe are the same as what's done in the example app https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications/example

**Comment by hanyska** [comment]
Go to: https://jgilfelt.github.io/AndroidAssetStudio/icons-notification.html#source.space.trim=1&source.space.pad=0&name=ic_notification

Create icon. Make sure that you get TRANSPARENT background!

**Comment by FeleConvo** [comment]
@MaikuB I had the same issue, the icon was correct but not showing. It only worked once I added this to `AndroidManifest.xml` : 

`<meta-data
            android:name="com.google.firebase.messaging.default_notification_icon"
            android:resource="@mipmap/ic_launcher_round_notifs" />`

I got this from this response in SO: https://stackoverflow.com/questions/57362439/notification-icon-donest-show-in-flutter-andriod-app-local-notification-flutter/63746521#63746521

Not sure why but probably worth mentioning in the docs.

**Comment by MaikuB** [comment]
That is for the firebase messaging plugin not this plugin

**Comment by dleurs** [comment]
This solved my problem :

https://stackoverflow.com/questions/61301786/flutter-android-notification-icon-grey-square

**Comment by Programmerflash** [comment]
> If you have an issue with the icon then either you haven't changed it correctly the way Android expects it (you'll need to check their docs on this e.g. if all of is non-transparent then I believe you may have issues) or hadn't follow all the steps in the readme as I explicitly warned that not setting it up properly may mean the icon won't appear as expected [here](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#release-build-configuration). There's no issue with the plugin when it comes to the icon as the steps you describe are the same as what's done in the example app https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications/example

I have followed all instructions but still it is neither displaying icon nor playing custom sound on release build. It is working fine or debug build.
[stackoverflow](https://stackoverflow.com/questions/61301786/flutter-android-notification-icon-grey-square) 
many people also facing same issue in this StackOverflow issue, check comment section of answer

**Comment by IshitaPathak** [comment]
Adding `<meta-data 
                  android:name="com.google.firebase.messaging.default_notification_icon" 
                  android:resource="@drawable/logoName" 
                 />` in `AndroidManifest.xml` and again building apk works.

**Comment by ahakDot** [comment]
I am also having this issue, but it is only on google pixel android phones. The icon looks fine on Samsung phones and iOS.

**Comment by ahakDot** [comment]
> > I am also having this issue, but it is only on google pixel android phones. The icon looks fine on Samsung phones and iOS.
> 
> Me too. Any solution?

@burekas7 yes, for Google phones u need to use a black and white icons. The phone will then color the white part of the icon according to the device's color theme that the user selected.

**Comment by Abolfazl-MI** [comment]
> Go to: https://jgilfelt.github.io/AndroidAssetStudio/icons-notification.html#source.space.trim=1&source.space.pad=0&name=ic_notification
> 
> Create icon. Make sure that you get TRANSPARENT background!

where should i place the site out put? when i extract it in res folder could not run and give me following error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:generateReleaseBuildConfig'.
> java.io.FileNotFoundException: C:\Users\Abolfazl\Desktop\amata-projects\dialy_motivation\build\app\generated\source\buildConfig\release\com\daily_motivation \BuildConfig.java (The system 
cannot find the path specified)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org
