### ISSUE TITLE
Feature to send notifications on specified days of week

### ISSUE THREAD

**Issue by abaturyna** [MaikuB/flutter_local_notifications#1019]
Dear @FlutterLocalNotifications team! 

Could you please realize a feature to send notificatons on specified days of week (for example, so that it was possible to schedule on Monday, Wednesday and Friday). 

Thank You!

**Comment by AbdullahChauhan** [comment]
Hey @abaturyna 
You can check the [/example](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications/example) directory for this. There's a clear example of how to schedule a notification only for day i.e. Monday. You can further extend this to your specific days.

**Comment by MaikuB** [comment]
Thanks @AbdullahChauhan for answering :)
