### ISSUE TITLE
didReceiveLocalNotification click not working for iOS 10+ 

### ISSUE THREAD

**Issue by deepashree-ballodi** [MaikuB/flutter_local_notifications#1021]
// Local notification set up
  localNotificationSetUp() {
    tz.initializeTimeZones();
    WidgetsFlutterBinding.ensureInitialized();
    const AndroidInitializationSettings initializationSettingsAndroid =
        AndroidInitializationSettings('@mipmap/ic_launcher');
    final IOSInitializationSettings initializationSettingsIOS =
        IOSInitializationSettings(
            requestAlertPermission: false,
            requestBadgePermission: false,
            requestSoundPermission: false,
            onDidReceiveLocalNotification:onDidReceiveLocalNotification
            );
    const MacOSInitializationSettings initializationSettingsMacOS =
        MacOSInitializationSettings(
            requestAlertPermission: false,
            requestBadgePermission: false,
            requestSoundPermission: false);
    final InitializationSettings initializationSettings =
        InitializationSettings(
            android: initializationSettingsAndroid,
            iOS: initializationSettingsIOS,
            macOS: initializationSettingsMacOS);
    flutterLocalNotificationsPlugin.initialize(initializationSettings,
        onSelectNotification: notificationSelected);
  }

Future onDidReceiveLocalNotification(
    int id, String title, String body, String payload) async {
 
  showDialog(
    context: context,
    builder: (BuildContext context) => CupertinoAlertDialog(
      title: Text(title),
      content: Text(body),
      actions: [
        CupertinoDialogAction(
          isDefaultAction: true,
          child: Text('Ok'),
          onPressed: () async {
            Navigator.of(context, rootNavigator: true).pop();
            await Navigator.push(
               context,
               MaterialPageRoute(
                builder: (context) => SecondScreen(payload),
               ),
            );
          },
        )
      ],
    ),
  );
}

**Comment by MaikuB** [comment]
This isn't a bug and if you check the docs (e.g. https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/IOSInitializationSettings/onDidReceiveLocalNotification.html) it's specific to iOS versions **older** than 10. This is because on such devices, if the app is in the foreground then a notification won't appear (not an issue with the plugin, just how iOS works) and applications need to use the callback to show information if needed
