### ISSUE TITLE
Missing notification icon in OneUI

### ISSUE THREAD

**Issue by Akeel1994** [MaikuB/flutter_local_notifications#1022]
Hey, 

i created a notification Icon with Android Studio Image Asset Editor. Everything is fine on stock android. 
But on Samsung devices I can't see the icon. 
Any ideas?

**Comment by MaikuB** [comment]
Are you running on release mode? If so, please make sure to do the [release build configuration](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#release-build-configuration). Generally icon issues are to do with not having done this. I haven't seen any reports of icon issues specific to Samsung and I know there have been other devs who have used this plugin on Samsung devices

**Comment by Akeel1994** [comment]
> Are you running on release mode? If so, please make sure to do the [release build configuration](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#release-build-configuration). Generally icon issues are to do with not having done this. I haven't seen any reports of icon issues specific to Samsung and I know there have been other devs who have used this plugin on Samsung devices
Hey, 
thanks for the fast answer. Year, we created a proguard file. 
Is this correct: 

## Flutter wrapper
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }
-dontwarn io.flutter.embedding.**

## Gson rules
# Gson uses generic type information stored in a class file when working with fields. Proguard
# removes such information by default, so configure it to keep all of it.
-keepattributes Signature

# For using GSON @Expose annotation
-keepattributes *Annotation*

# Gson specific classes
-dontwarn sun.misc.**
#-keep class com.google.gson.stream.** { *; }

# Prevent proguard from stripping interface information from TypeAdapter, TypeAdapterFactory,
# JsonSerializer, JsonDeserializer instances (so they can be used in @JsonAdapter)
-keep class * extends com.google.gson.TypeAdapter
-keep class * implements com.google.gson.TypeAdapterFactory
-keep class * implements com.google.gson.JsonSerializer
-keep class * implements com.google.gson.JsonDeserializer

# Prevent R8 from leaving Data object members always null
-keepclassmembers,allowobfuscation class * {
  @com.google.gson.annotations.SerializedName <fields>;
}

I also edited the build.gradle now, so I guess that was the mistake.

**Comment by MaikuB** [comment]
You'll need to read the entire section as there are really two paragraphs. The Proguard rules part is not the one that affects the icon. As it looks like you've missed these, I would suggest giving the readme a proper read in case you've missed other things as well e.g. the setup needed for the plugin to work on iOS.

**Comment by Akeel1994** [comment]
Okay, I guess you mean the keep.xml file, right? 

Thank you for your help!

**Comment by MaikuB** [comment]
> Okay, I guess you mean the keep.xml file, right?

Yep
