### ISSUE TITLE
Prevent show notification

### ISSUE THREAD

**Issue by xmavara** [MaikuB/flutter_local_notifications#1023]
Hello,
I use both flutter_local_notifications and firebase_messaging 8.0 and everything is okay except background message.
My code is :

```
FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async { 
  await Firebase.initializeApp();
  var notification = message.notification;
  flutterLocalNotificationsPlugin.show(
            notification.hashCode,
            notification.title,
            notification.body,
            NotificationDetails(
              android: AndroidNotificationDetails(
                channel.id,
                channel.name,
                channel.description
              ),
            ));
}
```

When my app is in background or closed two notification is shown.
I want to show only flutter_local_notifications notif.
Is there any way to prevent second notification?
thanks

**Comment by MaikuB** [comment]
If you want to keep the local notification but ignore the push notification from Firebase then that relates to Firebase functionality. Based on my limited understanding, you may need to use data messages but this is something you should be checking the Firebase docs for and/or ask on their repo as it's not to do with this plugin's functionality
