### ISSUE TITLE
How can i use this package in below metioned class ?

### ISSUE THREAD

**Issue by muhammednazil** [MaikuB/flutter_local_notifications#1026]
import 'dart:io';

import 'package:firebase_messaging/firebase_messaging.dart';

import 'notification_manager.dart';

class PushNotificationService {
  final FirebaseMessaging _fcm = FirebaseMessaging();

  Future initialise() async {
    if (Platform.isIOS) {
      _fcm.requestNotificationPermissions(IosNotificationSettings());
    }

    _fcm.configure(
      onMessage: (Map<String, dynamic> message) async {
        print("onMessage: $message");
      },
      onLaunch: (Map<String, dynamic> message) async {
        print("onLaunch: $message");
      },
      onResume: (Map<String, dynamic> message) async {
        print("onResume: $message");
      },

    );
  }
}

**Comment by MaikuB** [comment]
You need to fill in the blanks if you need to display a local notification and this all depends on what you're after. There's already documentation and an example for this plugin that you can make use of to plug in the gaps. There's also documentation for the firebase_messaging plugin at https://firebase.flutter.dev/docs/messaging/notifications#foreground-notifications and their repo has an example app as well. All of these should provide the info you need but if you need more in-depth help then I suggest jumping to the Flutter communities on Discord, Slack etc
