### ISSUE TITLE
How can I use this package with starting time (aka scheduling) in periodicallyShow method with end time? 

### ISSUE THREAD

**Issue by nurassylive** [MaikuB/flutter_local_notifications#1027]
I have no idea how to use this package? I need perioducallyShow method with starting (schedualing) time with limited amount. For example: 
-RepeatInterval is daily
-Starting time is after one hour
-End time is after five days  

I have to get notification after one hour, then next notification should be tomorrow at the same time. Repeating daily notification should end after five days, so the last notification I have to get after five days in the same time. Is this possible to implement such behaviour using this package? 

I have tried this: 
`for (int i = 0; i < 5; i++) {
      final dateTime = DateTime.now().add(Duration(seconds: 3600 * i + 1 + (86400 * i)));
      final time = tz.TZDateTime.from(dateTime, tz.local);
      fnPlugin.zonedSchedule(
        i,
        title,
        body,
        time,
        generalNotificationDetails,
        uiLocalNotificationDateInterpretation:
            UILocalNotificationDateInterpretation.absoluteTime,
        androidAllowWhileIdle: true,
      );
    }
`

**Comment by MaikuB** [comment]
No it isn't as the native notification APIs (especially on iOS and macOS) don't allow for this. You potentially need to at writing your own code for this or look at using https://pub.dev/packages/background_fetch as I've heard of others using this but it's not something I've personally used before
