### ISSUE TITLE
Progress notifications

### ISSUE THREAD

**Issue by MartinHlavna** [MaikuB/flutter_local_notifications#103]
Hello,
first of all, great job for making this plugin. However I am struggling with one use case I am trying to implement. I would like to create "progress notification". As I am coming from android enviroment, I know that android implementation is pretty straightforward.

https://medium.com/@britt.barak/notifications-part-2-progress-indicator-2aa4cdea24c6

I have not found a way how to achieve something like this in flutter using your plugin.

According to this SO question (and answers), it should be possible to do also on iOS using UIProgressBar, although I have very limited knowledge of iOS development and it may be off topic.

https://stackoverflow.com/questions/31672003/could-i-show-a-progress-bar-at-notification-bar-in-ios-8

**Comment by MaikuB** [comment]
It's not currently supported but should be easy to add. Will happily take a PR if you want to submit one too

**Comment by ram231** [comment]
Wouldn't be easy if you show numbers as "percentage" like "56%" in notification? Just some hacks for your project to have a progress indicator.

**Comment by MaikuB** [comment]
If that was directed to me, i'm just referring to exposing what's in the Android notification APIs.

**Comment by ram231** [comment]
I was referring Martin.

**Comment by MaikuB** [comment]
This should now be in 0.3.9. Closing the issue now since you should be able to show progress notifications once you get that release. Feel free to reopen if you encounter issues.

**Comment by Jeancr123** [comment]
Has there been any developments for this on iOS?
