### ISSUE TITLE
About RepeatIInterval.hourly

### ISSUE THREAD

**Issue by basemind** [MaikuB/flutter_local_notifications#1031]
Is there a problem with RepeatInterval.hourly ? My app works fine with RepeatInterval.everyMinute but RepeatInterval.hourly doesnt send notifications. I am using periodicallyShow function. Thanks

**Comment by MaikuB** [comment]
No and I just tested this again as well. The method has been in the plugin for a very long time without changes beyond refactoring so if there were issues then there should've been other reports on this. What device are you using to test this on?

**Comment by basemind** [comment]
It doesn't work in the first hour but second hour it works. And so on. Android(not physical device)
