### ISSUE TITLE
No Such Method Error

### ISSUE THREAD

**Issue by zilvinas-t** [MaikuB/flutter_local_notifications#1032]
Hello,

I've received this error while trying to create `_zonedScheduleNotification()` :

`E/flutter ( 5105): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The method 'timeZone' was called on null.
E/flutter ( 5105): Receiver: null
E/flutter ( 5105): Tried calling: timeZone(1612787878762)`

My line of code that caused the error: 
`var now = tz.TZDateTime.now(tz.local);`

**Comment by MaikuB** [comment]
The line of code you mention isn't from this plugin though so if that's where you're getting the error then make sure you've read their docs, especially around using `tz.local`.

**Comment by alaaKholi** [comment]
I think you should Initialise the time zone database
 `tz.initializeTimeZones();`

**Comment by MaikuB** [comment]
Thanks @alaaKholi for providing more info. Closing this as it's not an issue relating to this plugin and is around initialisation of the `timezone` package
