### ISSUE TITLE
periodicallyShow with starting time 

### ISSUE THREAD

**Issue by akshaybhange** [MaikuB/flutter_local_notifications#1033]
I want to show a notification to the user every day at 9 but I'm setting this up at some different time.

Is there any method where I can schedule notifications periodically but not from now?

Also, Is there any way to stop notifications for some time? (want to show notification hourly but between 9-6 only)

**Comment by MaikuB** [comment]
You should be using zonedSchedule for daily notifications. This was covered in the example app as well so please make sure to take a closer look. It starts at the next instance of the specified time. There is no way to stop notifications for some time. To do this potentially requires you write your own code on the Android/iOS to display notifications or use a fork of the plugin to add your own custom logic specific to your app

**Comment by micimize** [comment]
This is done with `matchDateTimeComponents `. Relevant section from the docs:

> If a value for `matchDateTimeComponents` parameter is given, this tells
the plugin to schedule a recurring notification that matches the
specified date and time components. Specifying
`DateTimeComponents.time` would result in a daily notification at the
same time whilst `DateTimeComponents.dayOfWeekAndTime` would result
in a weekly notification that occurs on the same day of the week and time.
