### ISSUE TITLE
Show a notification every day, at a specific time.

### ISSUE THREAD

**Issue by Jadiel-Santana** [MaikuB/flutter_local_notifications#1039]
Hello.

It would be great if there was a method for submitting a notification every day, at a specific time.

For example: I would set the 18:00 time in my SharedPreferences and every day at that time (18:00) my app would present a notification.

**Comment by MaikuB** [comment]
This is already available. Please take a closer look at the APIs and example app (https://github.com/MaikuB/flutter_local_notifications/blob/e4d42abe88d925e7c43850a073f49c10b41a6f25/flutter_local_notifications/example/lib/main.dart#L320)
