### ISSUE TITLE
[Feature Request] Option to have scheduled notification from future

### ISSUE THREAD

**Issue by techpool** [MaikuB/flutter_local_notifications#1042]
Currently the documentation explicitly states that it is not possible to start a periodic zonedScheduled notification from a future date, but is the limitation from the OS APIs? Is it not possible to consider the starting date of the scheduled notifications?

**Comment by MaikuB** [comment]
Yes this is a limitation of the native APIs and was mentioned in other threads. As an example, scheduled notifications on iOS use https://developer.apple.com/documentation/usernotifications/uncalendarnotificationtrigger. You specify a date and which components of the date and time it should match on. There's no concept of starting date
