### ISSUE TITLE
onSelectNotification not working if app closed , even when initialized at the main function 

### ISSUE THREAD

**Issue by quanghuuxx** [MaikuB/flutter_local_notifications#1047]
My app can't call the onSelectNotification function when click on notification at moment app is closed, even though I initialized it at main . Help me ! 

My code :
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  var android = AndroidInitializationSettings('@mipmap/ic_launcher');
  var iOS = new IOSInitializationSettings();
  var initSetttings = InitializationSettings(android: android, iOS: iOS);
  await flutterLocalNotificationsPlugin.initialize(initSetttings,
      onSelectNotification: (payload) async {
    if (payload != null) {
      //call action to an available phone number
      AcctionSystem.call(phoneNumber: '03xxxxxxx');
    }
  });
  runApp(MyApp());
}

**Comment by MaikuB** [comment]
Since 4.0, the callback cannot be used when the notification launches the app. This has been noted in the readme (note: fixed a typo there a moment ago) and changelog. You should use the `getNotificationAppLaunchDetails` method. The example app in the readme shows this as well

**Comment by quanghuuxx** [comment]
can you give me a few examples of usage 'getNotificationAppLaunchDetails '


Vào Th 2, 22 thg 2, 2021 vào lúc 16:04 Michael Bui <
notifications@github.com> đã viết:

**Comment by MaikuB** [comment]
See the example app in the repo

**Comment by quanghuuxx** [comment]
Sorry, does flutter_local_notifications already have a show notification
function with action buttons?

Vào Th 2, 22 thg 2, 2021 vào lúc 16:41 Michael Bui <
notifications@github.com> đã viết:
