### ISSUE TITLE
[Feature Request] add criticalAlert permission for iOS > 12.0

### ISSUE THREAD

**Issue by StalderT** [MaikuB/flutter_local_notifications#1049]
It would be nice to be able to add the possibility to ask permission for the "criticalAlert" attribute :

https://developer.apple.com/documentation/usernotifications/unauthorizationoptions/2963120-criticalalert

Thanks for the great job.

**Comment by StalderT** [comment]
Something like that : https://github.com/StalderT/flutter_local_notifications/commit/09097bf430afed071259607ca071513ac60894f1

I have nothing to test the modifications.

**Comment by MaikuB** [comment]
As you have a fork for this, could you please submit a PR for it? Though if you can't test this yourself, I'm not sure how you planned to leverage this feature

**Comment by MaikuB** [comment]
Closing since PR has issues and hasn't been updated for a while
