### ISSUE TITLE
Icons Not Showing at Status Bar

### ISSUE THREAD

**Issue by Seedorf161** [MaikuB/flutter_local_notifications#105]
I've integrated the local notification and everything is perfect but when the notification shows, no Icon is shown at the Status Bar.

Does this require additional steps? How do i go about it?

**Comment by MaikuB** [comment]
There shouldn't be any additional steps required. Which platform are you running this on and can you provide a sample app to reproduce this? Does the example app exhibit the same problem for you?

**Comment by Seedorf161** [comment]
I'm running it on Android. I have the same Experience with replacing my app main.dart with your example's main.dart.

**Comment by MaikuB** [comment]
Please run the example app as a whole not just replacing the main.dart. Although I said there's no additional steps, you mentioned you had integrated the plugin so I'm assuming you actually followed what was documented with regards to integrating on each platform. There's a comment about this in the example main.dart too. I suspect you haven't gone through the Android integration section so I'd suggest you go over it

**Comment by Seedorf161** [comment]
I appreciate your Swift response.

I've initialize the notification on Android platform. I get notification at the scheduled time but the only issue is the icon not showing at the Status Bar. And if i may ask, what actually defines the Status Bar icon? Is it the icon specified during initialization or the icon specified on scheduling notification?

**Comment by MaikuB** [comment]
Initialising is to specify the default icon but it's possible to override this on a per notification basis. As mentioned in my previous post, please read the Android integration section as I believe you haven't actually followed what's mentioned there to ensure the icons are rendered. You can look at the example app and the associated Android project to see how it's been setup

**Comment by MaikuB** [comment]
Also if you plan to target iOS then you should read the iOS integration section as well

**Comment by MaikuB** [comment]
Just wanted to follow up on this, were you able to sort out the issue?

**Comment by Seedorf161** [comment]
I noticed that it didn't show icon at status bar for ongoing notification.

**Comment by MaikuB** [comment]
Closing this due having but had a response for a long time. Feel free to reopen if you still have problems
