### ISSUE TITLE
Ui Thread blocked when scheduling 60+ zonedSchedule

### ISSUE THREAD

**Issue by armandojimenez** [MaikuB/flutter_local_notifications#1051]
Hi, question,
In my app, users are able to choose a time range (for example 9 am to 8 am), the days in the week they want to receive notifications, and how many in a day. Based on this info, I generate a list of future dates.

The problem is that i need to do a zonedSchedule for each date. For example, I will do a loop, foreach date. In iOS, I can schedule as many as I want and it does not block the UI, but I know I have to limit it to 60. But for Android, when I try to schedule more than 60+ in a loop, the UI will lock until the loop finish. I have tried with execute(), but when I do that, timezone does not work and the plugin can't invoke the method channel.

Is there any way to handle this without blocking the ui? I can't even show a loading since it freezes too.

Any help would be appreciated and thanks for this awesome plugin.

`
// I call it here
 onTap: () async {
                await EasyLoading.show(status: 'loading...');
                await getDatesForNotifications();
                await EasyLoading.dismiss();

                print("done");
              },

`

`
Future<void> getDatesForNotifications() async {
    final now = tz.TZDateTime.now(tz.local);
    print(now);

    int pushLimit = 450;
    //if (Device.get().isAndroid) pushLimit = 499;

    int dailyPush = 30;
    DateFormat dateFormat = DateFormat.Hm();

    String startTime = "9:30";
    String endTime = "22:00";

    tz.TZDateTime open =
        tz.TZDateTime.from(dateFormat.parse(startTime), tz.local);
    open = tz.TZDateTime(
        tz.local, now.year, now.month, now.day, open.hour, open.minute);
    tz.TZDateTime close =
        tz.TZDateTime.from(dateFormat.parse(endTime), tz.local);
    close = tz.TZDateTime(
        tz.local, now.year, now.month, now.day, close.hour, close.minute);

    if (close.isBefore(open)) {
      close = close.add(Duration(days: 1));
    }
    print('open is $open and close is $close');

    print('diferences in minutes: ${close.difference(open).inMinutes}');

    int checkDailyInLoop = (close.difference(open).inMinutes) ~/ dailyPush;

    print('check daily in loop every $checkDailyInLoop minutes');

    List<int> daysIwant = [
      DateTime.monday,
      DateTime.tuesday,
      DateTime.wednesday,
      DateTime.thursday,
      DateTime.sunday
    ];

    List<tz.TZDateTime> pushTimes = [];

    var dateForLoop = tz.TZDateTime(
      tz.local,
      now.year,
      now.month,
      now.day,
      open.hour,
      open.minute,
    );

    for (int i = 1; i <= pushLimit; i++) {
      bool foundADate = false;

      while (!foundADate) {
        dateForLoop = dateForLoop.add(Duration(minutes: checkDailyInLoop));

        if (!daysIwant.contains(dateForLoop.weekday)) {
          dateForLoop = tz.TZDateTime(tz.local, dateForLoop.year,
              dateForLoop.month, dateForLoop.day + 1, open.hour);
          print('not in the desired date, jumping to $dateForLoop');
        }
        tz.TZDateTime currentOpen =
            tz.TZDateTime.from(dateFormat.parse(startTime), tz.local);
        currentOpen = tz.TZDateTime(tz.local, dateForLoop.year,
                dateForLoop.month, dateForLoop.day, open.hour, open.minute)
            .subtract(Duration(seconds: 1));
        tz.TZDateTime currentClose =
            tz.TZDateTime.from(dateFormat.parse(endTime), tz.local);
        currentClose = tz.TZDateTime(tz.local, dateForLoop.year,
            dateForLoop.month, dateForLoop.day, close.hour, close.minute);

        if (currentClose.isBefore(currentOpen)) {
          currentClose = currentClose.add(Duration(days: 1));
        }

        if ((dateForLoop.isAfter(currentOpen) &&
                dateForLoop.isBefore(currentClose)) &&
            !dateForLoop.isBefore(now)) {
          print('found a date! $dateForLoop');
          foundADate = true;
          pushTimes.add(dateForLoop);
        }
      }
    }

    print('resulting dates for push: $pushTimes');
    print('push dates lenght: ${pushTimes.length}');

    if (pushTimes.isNotEmpty) {
      await flutterLocalNotificationsPlugin.cancelAll();
      await pushTimes.asMap().forEach((pushId, time) async {
        List<String> affirmations =
            context.read<AppProvider>().todayAffirmations;
        String message =
            affirmations[Random().nextInt(affirmations.length)].tr();

        final BigTextStyleInformation bigTextStyleInformation =
            BigTextStyleInformation(
          message,
        );
        final AndroidNotificationDetails androidPlatformChannelSpecifics =
            AndroidNotificationDetails(
          'believe_id',
          'Affirmation Reminders',
          'Affirmations for a positive mind.',
          styleInformation: bigTextStyleInformation,
          importance: Importance.max,
          ledColor: const Color(0xFFFFA291),
          color: const Color(0xFFFFA291),
          largeIcon: DrawableResourceAndroidBitmap('large_notification_icon'),
          ledOffMs: 300,
          ledOnMs: 1000,
          priority: Priority.high,
          enableLights: true,
          enableVibration: true,
          visibility: NotificationVisibility.public,
          showWhen: true,
        );
        final NotificationDetails platformChannelSpecifics =
            NotificationDetails(android: androidPlatformChannelSpecifics);

        await flutterLocalNotificationsPlugin.zonedSchedule(
          pushId,
          null,
          message,
          time,
          platformChannelSpecifics,
          androidAllowWhileIdle: true,
          uiLocalNotificationDateInterpretation:
              UILocalNotificationDateInterpretation.absoluteTime,
        );
        print('a message was scheduled to show on $time');
        print('push id: ${time.hashCode}');
      });
      BotToast.showSimpleNotification(
          title: 'Push Scheduled',
          enableKeyboardSafeArea: true,
          titleStyle: TextStyle(fontSize: 18),
          align: Alignment.bottomCenter);

      print('done with message!');
    }
  }

`

**Comment by MaikuB** [comment]
What version of the plugin are you using? There were already changes done to save notification information to shared preferences in the background in https://github.com/MaikuB/flutter_local_notifications/pull/980 so I'm wondering if your issue is to do with using an older version that didn't have the changes as the PR was from another member of the community that had similar problems

**Comment by armandojimenez** [comment]
Hi,
flutter_local_notifications: ^4.0.1+1

I tried in a S10+, LG G7 and a S5, The UI will lock, and at the end it shows the error about skipping 900+ frames,

I even tried the Flutter Isolate example I saw in another issue here

**Comment by armandojimenez** [comment]
Any way to deal with this? I need to also need to update the notifications again on each app start, and this will block the UI for 2 or 3 seconds if I only schedule 60

**Comment by MaikuB** [comment]
From what I've been trying, there isn't much else for the plugin to do. If you're scheduling a lot, you may need to consider having your fork to bulk schedule all your notifications via one method to avoid making platform channel calls and saving to shared preferences multiple. There was a PR on this before but was not merged in as it's an extension rather than a core notifications API since the plugin's purpose to is to provide a wrapper for the standard native notification APIs

**Comment by BrandCooper** [comment]
> 

hello,  could you post link of the PR, thanks

**Comment by BrandCooper** [comment]
https://github.com/MaikuB/flutter_local_notifications/pull/1351

The same problem occurs when multiple cancel(id)
