### ISSUE TITLE
stop sound notification onPressed

### ISSUE THREAD

**Issue by prozaklob** [MaikuB/flutter_local_notifications#1052]
hi.
Thx for plugin.

1) Can I somehow stop playing notif.sound by pressing a button in the app (onPressed) and if i press hardware button volume down?
2) I saw in closed topics a question about looping sound playback. Has there been a solution?

**Comment by MaikuB** [comment]
> 1. Can I somehow stop playing notif.sound by pressing a button in the app (onPressed) and if i press hardware button volume down?

No

> 2. I saw in closed topics a question about looping sound playback. Has there been a solution?

The only on Android has already been covered in the example app https://github.com/MaikuB/flutter_local_notifications/blob/c21506bcae63f84813aa01e09330006cd4d138d2/flutter_local_notifications/example/lib/main.dart#L819. It's not something that is supported on other platforms
