### ISSUE TITLE
Turn on and turn off notification 

### ISSUE THREAD

**Issue by soanpr123** [MaikuB/flutter_local_notifications#1053]
I have a toggle that notifies. how I can turn off local notifications in my project.

**Comment by MaikuB** [comment]
There are no APIs to manage this. It's something you need to handle in your own app so your app doesn't run code to show notifications

**Comment by hamra** [comment]
hey @MaikuB . Can you be more precise to how to achieve this ? I want to do the same thing (turn on and off the notification through a toggle in Settings).
If I do CancellAll(), it cancels all the scheduled notifications. My app has scheduled notifications that work as reminders. Please help me where and how should I do something to start/stop showing the notification based on a bool value coming from settings?
