### ISSUE TITLE
显示通知

### ISSUE THREAD

**Issue by BurkeDeng** [MaikuB/flutter_local_notifications#1056]
notification 在通知框显示通知时如何像wechat新消息提醒般弹出通知详情；
How to pop up notification content details

**Comment by MaikuB** [comment]
I'm not Chinese nor can I read/write it so please write all of your message in English. If you cannot do so, you should look for a message board/chat community with those that speak the same language to help you out. How to show notifications is already documented and there's an example app in the repository

**Comment by boukyuan** [comment]
How to implement the overall notification of Android phones in China, and explain the details of the notification when a floating window notification appears

**Comment by MaikuB** [comment]
Your question is very vague and how to show notifications is already documented and covered in the example app. Please go through the docs and example app.

Please note that this repository is for _local_ notifications. Your original post mentions WeChat that would rely more on push notifications. That's a different thing and you would need to look up how to implement those. Most Flutter developers use Firebase but again, that is for push notifications and a different thing to local notifications. So if you're after something like WeChat and specific to China then you'd need to ask that question elsewhere as it relates to a different topic and I'm not familiar with how companies in China deal with push notifications

**Comment by BurkeDeng** [comment]
> 您的问题非常模糊，示例应用程序中已记录并涵盖了如何显示通知。请仔细阅读文档和示例应用程序。
> 
> 请注意，该存储库用于_本地_通知。您的原始帖子提到微信，该微信将更多地依赖于推送通知。那是另一回事，您将需要查找如何实现它们。大多数Flutter开发人员都使用Firebase，但同样，这是用于推送通知的，与本地通知不同。因此，如果您关注的是微信之类的东西并且特定于中国，那么您需要在其他地方问这个问题，因为它与另一个主题相关，而且我不熟悉中国的公司如何处理推送通知

**Comment by BurkeDeng** [comment]
I get it, thank




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MaikuB/flutter_local_notifications"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月26日(星期五) 下午2:49
收件人:&nbsp;"MaikuB/flutter_local_notifications"<flutter_local_notifications@noreply.github.com&gt;;
抄送:&nbsp;"╮柏拉图、親"<boukyuan@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [MaikuB/flutter_local_notifications] 显示通知 (#1056)





 
Your question is very vague and how to show notifications is already documented and covered in the example app. Please go through the docs and example app.
 
Please note that this repository is for local notifications. Your original post mentions WeChat that would rely more on push notifications. That's a different thing and you would need to look up how to implement those. Most Flutter developers use Firebase but again, that is for push notifications and a different thing to local notifications. So if you're after something like WeChat and specific to China then you'd need to ask that question elsewhere as it relates to a different topic and I'm not familiar with how companies in China deal with push notifications
