### ISSUE TITLE
White screen on my Android Phone

### ISSUE THREAD

**Issue by eyabmohero** [MaikuB/flutter_local_notifications#1058]
**Describe the bug**

Hello 
I used exact same  code you have in main.dart 
run it on my Android Phone and just got  white screen , with nothing in it just blank 

**To Reproduce**

**Expected behavior**

**Sample code to reproduce the problem**

**Comment by MaikuB** [comment]
It looks like you had missed the comments that were put in the main.dart file [here](https://github.com/MaikuB/flutter_local_notifications/blob/c21506bcae63f84813aa01e09330006cd4d138d2/flutter_local_notifications/example/lib/main.dart#L47). For convenience. what was written that copying just the Dart code won't work. If you would like to run the example app then you should either download/clone the entire repository or copying the remaining parts from the native side, which includes things like the custom resources for the icon and code specific to each platform (e.g. https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/example/ios/Runner/AppDelegate.swift)
