### ISSUE TITLE
Not documented where to put custom sounds files

### ISSUE THREAD

**Issue by kondasoft** [MaikuB/flutter_local_notifications#106]
I have managed to find the path for Android 
`android/app/src/res/raw`

but where is for iOS?

**Comment by MaikuB** [comment]
I refer to Apple's documentation for more info on that in the READM https://developer.apple.com/documentation/usernotifications/unnotificationsound?language=objc

There's also an example app where you can see where it ends up once you've added the sound via XCode

https://github.com/MaikuB/flutter_local_notifications/tree/master/example/ios

**Comment by kondasoft** [comment]
HI, thanks for the reply. so where to drag the sound file on xcode? Sorry but most of the developers including me, dont have pririor experience with iOS

**Comment by MaikuB** [comment]
I can't check until much later (getting late here now) but if you open the example app in Xcode then you should see where it needs to go as a reference

**Comment by MaikuB** [comment]
were you able to find out where to put the file?

**Comment by kondasoft** [comment]
Hi,
I try to add on the runner folder but without success. This is the variable as well. On Android is working fine by the way.

`var iOSPlatformChannelSpecifics = IOSNotificationDetails( presentSound: true, sound: "custom_sound.aiff");`

**Comment by MaikuB** [comment]
Do you see an error and can you include a screenshot of the project structure in xcode?

**Comment by MaikuB** [comment]
Am closing due to lack of follow up response

**Comment by kondasoft** [comment]
Hi, Sorry for the delays. I decided to not use custom sound at this time, but otherwise the docs should be more easy to follow. Anyway the plugin is very good.
