### ISSUE TITLE
[macOS] The plugin requests permissions on initialization even if none requested from an application

### ISSUE THREAD

**Issue by badver** [MaikuB/flutter_local_notifications#1062]
**Describe the bug**
The plugin requests permissions on initialization even if none requested from an application.
The problem is that `requestPermissionsImpl` calls system's methods like "requestAuthorization" even if I set initialization options to none:
```dart
const MacOSInitializationSettings initializationSettingsMacOS = MacOSInitializationSettings(
      requestSoundPermission: false,
      requestBadgePermission: false,
      requestAlertPermission: false,
    );
```
This behavior leads to app freeze or blank screen on start if the plugin initialized in main.dart

**Expected behavior**
Don't call system methods to request permissions if none requested from an application.

**Comment by badver** [comment]
Fix prepared: https://github.com/MaikuB/flutter_local_notifications/pull/1063

**Comment by MaikuB** [comment]
Thanks, will try to look at the PR as soon as I can
