### ISSUE TITLE
Amount of time the notification stays on screen

### ISSUE THREAD

**Issue by rekonvald** [MaikuB/flutter_local_notifications#1064]
Hi there! 

First of all, I really want to thank you for this plugin!

But unfortunately there is no possibility to specify the amount of time the notification stays on screen, is it? Could you please tell either we can hope that such functionality will be added

**Comment by MaikuB** [comment]
Only on Android and is demonstrated in the example app. Other platforms don't support this. See https://github.com/MaikuB/flutter_local_notifications/blob/c21506bcae63f84813aa01e09330006cd4d138d2/flutter_local_notifications/example/lib/main.dart#L415. I suggest exploring the example app as it covers all of the functionality available with the plugin

**Comment by rekonvald** [comment]
Thank you

**Comment by talwarabhimanyu** [comment]
Thank you for this suggestion and thanks for your work on this package. If I may ask, is there a max limit for `timeoutAfter`? I noticed the notification stays visible for 4-5 seconds, even if `timeoutAfter` is set to say `10000`. Is there a way to prolong the visibility duration? (My use case is that I'm showing the notification to inform the user of an incoming call. Hence I want to show it for longer.) Thank you
