### ISSUE TITLE
Flutter Local notifications with sounds saved in local directory

### ISSUE THREAD

**Issue by mhmhassan** [MaikuB/flutter_local_notifications#1065]
I am creating an app that is to push local notifications of custom sounds pulled with an http request saved in local directory.  Does UriAndroidNotificationSound support that?.. I tried passing mp3 file path to it and notifications play with no sound.

Thanks for your time

**Comment by MaikuB** [comment]
Only Android URIs are supported.  As such, the scheme is very specific such that a URI may look something like `android.resource://...`. I'm not sure if it's possible to get such a URI for a file that has been saved. This would be something you would need to look up as it involves more knowledge on the Android development side of things

**Comment by mhmhassan** [comment]
Thank you
