### ISSUE TITLE
Scheduling notifications

### ISSUE THREAD

**Issue by kostyanchikoff** [MaikuB/flutter_local_notifications#1066]
Is it possible to schedule only the time, for example, every day only at 09:00 and 18:00  a notification will come, regardless of the date and year. Thank you in advance!

**Comment by iqfareez** [comment]
Of course it is possible

**Comment by kostyanchikoff** [comment]
Tell me how to do this please?)

**Comment by iqfareez** [comment]
i'm afraid i dont have time for that, Try asking at StackOverflow, (post the link here later)

**Comment by MaikuB** [comment]
@kostyanchikoff did you check out the example app? it has already covered how to have daily notifications but you are required to still specify a date and time

**Comment by kostyanchikoff** [comment]
@MaikuB I need to receive reports every day at 9: 00, 15: 00 and 19:00, no matter what date

**Comment by MaikuB** [comment]
Please take a closer at the examples around daily notifications that I've mentioned and the API involved as that can be used to do what you're after. When the `matchDateTimeComponents` parameter is specified and given the name of the argument, it means you schedule a notification to occur based on the conditions that match the specified date/time components. The date doesn't indicate a start date anymore
