### ISSUE TITLE
How to cancel notification by groupkey?

### ISSUE THREAD

**Issue by skripsimu** [MaikuB/flutter_local_notifications#1067]
**I want to cancel my app notifications with the group key, only notifications with the same key will be canceled. is that possible? because now can only cancel with ID or cancel all**

**Comment by skripsimu** [comment]
or can I group messages with the group key automatically?

**Comment by skripsimu** [comment]
and can I group notifications with the group key automatically?

**Comment by MaikuB** [comment]
The notification APIs don't support cancelling by group key. You need to manage this on your own. With regards to automatic grouping, I thought this already happens. Have you tried running the example app?

**Comment by skripsimu** [comment]
Thanks for your response, I've successfully canceled the notification by recording the notification id which has the same group key. and for grouping, I have successfully implemented it, thanks again
