### ISSUE TITLE
Specify custom interval for Periodically show a notification with a specified interval

### ISSUE THREAD

**Issue by rekonvald** [MaikuB/flutter_local_notifications#1068]
Hi!

Can we specify custom time interval for Periodically show a notification functionality?

For now it can be specified via repeat interval enum, and the smallest interval is every minute, what if I want to specify 5 sec for example?

Thank you

**Comment by MaikuB** [comment]
No. Also, thhere's already an open issue on this https://github.com/MaikuB/flutter_local_notifications/issues/92
