### ISSUE TITLE
Flutter local notifications in the background issues

### ISSUE THREAD

**Issue by fdarsot** [MaikuB/flutter_local_notifications#1069]
hi there, We have an app that probes an api endpoint periodically (every 60 seconds) and provides data to a user.

Currently we are using a Timer function and Observing the state of the app (whether its in foreground, background etc) and if it's in the background, we are calling the timer function every 60 seconds, probing the api endpoint, filtering through the results of that api call to find any **_new_** events and then if **_new_** events are found, sending a flutter local notification using your plugin.

However currently even though new events are found, the local notifications are not being sent through consistently in a release version (but they are in debug version).

We were wondering what the issue would be or if there was a simpler way to just use the flutter local notification plugin somehow in the background when a new event is found.

**Comment by wangxinnong** [comment]
Same issue here, can anyone help resolve it?

**Comment by fdarsot** [comment]
@MaikuB

**Comment by MaikuB** [comment]
> However currently even though new events are found, the local notifications are not being sent through consistently in a release version (but they are in debug version).

Issues like this would suggest that not all of the release build configuration has been done  Please check the readme and cross reference your app with the example app in the repository

**Comment by mrdc** [comment]
@MaikuB 
Hi! Thanks for the plugin — I’m having the same issue on iOS: no notifications when an app in background. On Simulator everything works fine, but not on my phone.
I’ve checked plugin docs and api, plugin example, googled and found nothing about any special config for release app building options. Also there is no special compatibility options set in plugin example (iOS Xcode project).
Will you be so kind to guide us where to look?

**Comment by fdarsot** [comment]
hi @MaikuB  i will check the release build configuration. However, if it isn't the configuration, any idea what it might be?

Do you see any issues with the process that we are currently doing? (checking if app is in background, if it is, probe every 60 seconds using Timer function and then if new item is found in api response, show a local notification)

**Comment by fdarsot** [comment]
@mrdc  how are you running the notifications when your app is in the background? same way as we are?

**Comment by MaikuB** [comment]
@mrdc https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#release-build-configuration

> Do you see any issues with the process that we are currently doing? (checking if app is in background, if it is, probe every 60 seconds using Timer function and then if new item is found in api response, show a local notification)

@fdarsot the other thing you should be aware of is that applications don't necessarily remain running in the background. The OS may release the resources used by your app so that's another likely cause for what you're seeing. This is one of the reasons why Flutter has restoration APIs (see https://api.flutter.dev/flutter/services/RestorationManager-class.html). I'm guessing when you say that debug version works fine that you have a debug session. I would imagine that the framework has a way to keep the app and debug session remaining. Nothing from what you've described points to a problem with this plugin either nor I do see how there could be a bug specific to it. Given the OS may effectively stop your app from continuing to run when it's in the background, I would say you likely need to do some research to come up with a different approach to work within the constraints of the native platforms you're dealing with

**Comment by fdarsot** [comment]
@MaikuB I see, yes i have had that suspicion as well, but then that makes me wonder how is it that these apps such as google maps or Waze maps, how do they run in the background without the OS stopping them from running?

The debug version is indeed running a debug session, and everything works fine on that.

**Comment by MaikuB** [comment]
@fdarsot those are very different use cases so you'll need to dwelve more into the native APIs if you want to know more. Those apps make use of location APIs so would've been built with the intent that they can run in the background and request permission to do so. Note that your timer would've been stopped too so it's not as though the problem you've originally is that the part that fails has to do with plugin (e.g.  https://stackoverflow.com/questions/59480124/how-to-run-clock-timer-in-background-on-flutter, which shows up as the first Google result when I look for `flutter timer background`). 

In light of what I've mentioned, I'll be closing this as it's not an issue specific to the plugin

**Comment by mrdc** [comment]
> @mrdc https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#release-build-configuration

@MaikuB 
Unfortunately, it’s for Android, but not for iOS in my case.

**Comment by MaikuB** [comment]
@mrdc please read the rest of the conversation in the thread, there isn't an issue here with the plugin

**Comment by mrdc** [comment]
> how are you running the notifications when your app is in the background? same way as we are?

Looks like it's the same - my app receives info while in background and then shows local notification.

@MaikuB you are right: the issue on iOS is not plugin related, but plugin's example related: xcode settings are not set for the iOS app to be able to send local push notifications :)
