### ISSUE TITLE
Nothing working in an Oreo emulated Android device (API 27).

### ISSUE THREAD

**Issue by xufab** [MaikuB/flutter_local_notifications#107]
I have an emulated Android device in Android studio which runs Oreo API 27. I tried the example app but nothing is working, not even a simple notification.
Is it only me?

**Comment by MaikuB** [comment]
I suspect something's wrong with your environment so a few questions about that

1. What's the output of running `flutter doctor -v`?
2. Are you able to run a basic Flutter app?
3. Does the example run for you at all?

**Comment by xufab** [comment]
1.
```
C:\Users\Xufab>flutter doctor -v
[√] Flutter (Channel dev, v0.9.2, on Microsoft Windows [version 10.0.14393], locale fr-FR)
    • Flutter version 0.9.2 at C:\Users\Xufab\flutter
    • Framework revision 85b4670b2a (13 days ago), 2018-09-19 14:59:23 -0700
    • Engine revision 2e8e96fad1
    • Dart version 2.1.0-dev.4.0.flutter-4eb879133a

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\Xufab\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 28.0.2
    • Dart plugin version 181.5616
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!
```

2. Yes, without any problems.

3. It runs but without any notifications.

**Comment by MaikuB** [comment]
When you run the example app are you just copying what's in main.dart across to the project you created? If so, this won't work and there's about in the code about this too. There's setup involved for each platform that needs to be done if you do it that way or you can clone the repo where the platform-specific setup has been done

**Comment by xufab** [comment]
I will check another time. Thanks.
