### ISSUE TITLE
How to clear the notifications?

### ISSUE THREAD

**Issue by bdlukaa** [MaikuB/flutter_local_notifications#1070]
Hey, thank you for this awesome plugin :)

Is there any way to clear the notifications from the notifications bar?

On android, it can be done this way:

```java
NotificationManager notificationManager = (NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE);
notificationManager.cancelAll();
```

Thanks :)

**Comment by MaikuB** [comment]
Yes, please try take a closer look at the documentation and examples as this was already covered and the method has the exact same name https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#cancellingdeleting-all-notifications
