### ISSUE TITLE
How to turn on the screen when there is a notification on Android

### ISSUE THREAD

**Issue by pavane90** [MaikuB/flutter_local_notifications#1077]
Hello
I implemented push notification using flutter local notifications 4.0.1 and it works well.

However, in case of Android, when push notification occurs when the screen is turned off, the screen does not turn on and only sounds and vibrations occur.

If use fullScreenIntent= true, the screen will turn on and the app will start. But I want to implement the lockscreen turn on.
I'm sorry for the rudimentary question.

**Comment by MaikuB** [comment]
As far as I know, the native Android notification APIs don't provide this functionality and that there are separate Android APIs for waking up the screen. You may need to look at writing your own native Android code to add the functionality in
