### ISSUE TITLE
Version solving failed with some packages

### ISSUE THREAD

**Issue by dyhwang** [MaikuB/flutter_local_notifications#1078]
**Describe the bug**

Because flutter_local_notifications_platform_interface 2.0.0+1 depends on plugin_platform_interface ^1.0.2 and no versions of flutter_local_notifications_platform_inter
face match >2.0.0+1 <3.0.0, flutter_local_notifications_platform_interface ^2.0.0+1 requires plugin_platform_interface ^1.0.2.
And because file_picker >=3.0.0-nullsafety.3 depends on plugin_platform_interface ^2.0.0 and flutter_local_notifications >=3.0.1+4 <5.0.0-nullsafety.0 depends on flutte
r_local_notifications_platform_interface ^2.0.0+1, file_picker >=3.0.0-nullsafety.3 is incompatible with flutter_local_notifications >=3.0.1+4 <5.0.0-nullsafety.0.
So, because MyAppName depends on both flutter_local_notifications ^4.0.1+2 and file_picker ^3.0.0, version solving failed.

Thanks for the great package.

**Comment by hschk** [comment]
It's the same problem with firebase_messaging version 9.0.0

```
Because flutter_local_notifications >=3.0.1+4 <5.0.0-nullsafety.0 depends on flutter_local_notifications_platform_interface ^2.0.0+1 which depends on plugin_platform_interface ^1.0.2, flutter_local_notifications >=3.0.1+4 <5.0.0-nullsafety.0 requires plugin_platform_interface ^1.0.2.
Because firebase_messaging_platform_interface 2.0.0 depends on plugin_platform_interface ^2.0.0 and no versions of firebase_messaging_platform_interface match >2.0.0 <3.0.0, firebase_messaging_platform_interface ^2.0.0 requires plugin_platform_interface ^2.0.0.
Thus, flutter_local_notifications >=3.0.1+4 <5.0.0-nullsafety.0 is incompatible with firebase_messaging_platform_interface ^2.0.0.
And because firebase_messaging 9.0.0 depends on firebase_messaging_platform_interface ^2.0.0 and no versions of firebase_messaging match >9.0.0 <10.0.0, flutter_local_notifications >=3.0.1+4 <5.0.0-nullsafety.0 is incompatible with firebase_messaging ^9.0.0.
So, because playground depends on both firebase_messaging ^9.0.0 and flutter_local_notifications ^4.0.1+2, version solving failed.
pub get failed (1; So, because playground depends on both firebase_messaging ^9.0.0 and flutter_local_notifications ^4.0.1+2, version solving failed.)
```

**Comment by fredecodes** [comment]
I'm having the same issue, incompatible with firebase_messaging version 9.0.0.

**Comment by vipinnegi90** [comment]
Ever since upgraded to Flutter v2.0.1 I started to have these problems. Trying to fix one package version produces many more package incompatibility issues. The only solution at the moment I see is to downgrade the flutter version.

**Comment by fredecodes** [comment]
Actually, it looks like there is a dev version with null safety.  If you run the following command:
`dart pub outdated --mode=null-safety`
You'll see that it recommends using this version:
`flutter_local_notifications: 5.0.0-nullsafety.1`

**Comment by MaikuB** [comment]
Please read https://github.com/MaikuB/flutter_local_notifications/issues/1087
