### ISSUE TITLE
Schedule notification dosen't work when app is killed or closed (Oneplus 6)

### ISSUE THREAD

**Issue by Ronaldonizuka** [MaikuB/flutter_local_notifications#1079]
Hello, 
First of all I would like to thank you for your work.
I coded an application, which displays a notification at a fixed time every day, it all works except when the application is closed or killed. 
Is it due to the brand of my phone (Oneplus 6) ? on the android studio emulator, it works perfectly.
In this case, is there anything to do ? 
Thanks in advance. 
Best regards

**Comment by saivarunr** [comment]
@Ronaldonizuka For one plus, disable optimise battery for the app.

**Comment by MaikuB** [comment]
@Ronaldonizuka yes it would be to do with the brand of your phone. You'll need to check your phone settings to see what can be changed to allow it to work. This is outside the control of the plugin
