### ISSUE TITLE
Why is the notification id not passed to user?

### ISSUE THREAD

**Issue by ristiisa** [MaikuB/flutter_local_notifications#1082]
Currently only the payload is passed back to user when clicked on presented notification.

Is there a good reason why not to pass the notification id back to the user?

**Comment by MaikuB** [comment]
If you were to deal with the native Android APIs, when you tap on a notification, this triggers an intent. What is associated with the intent is essentially custom data, which is currently the payload. This is like an opt-in option so if you wanted to include the ID then that would be something you can opt into. The payload is a string so this allows for JSON to be used

**Comment by ristiisa** [comment]
If the ID is present then why not pass it to user?

**Comment by MaikuB** [comment]
I didn't say the ID is present. Only custom data i.e. the payload is. As per my previous post, this has to do with how the native APIs work. Hence why I said if you want the ID there, you'd need to include it in the payload, which you can do since it's a string.

**Comment by ristiisa** [comment]
On IOS the ID is present. I have not looked at Android but I don't see a reason why it should not be there.

**Comment by MaikuB** [comment]
As I explained in my previous post, you don't get a notification object on Android. Your don't even a get notification-specific event when tapping on a notification with details on the notification. Just a intent, which is a generic concept that can trigger any action that can hold data (needs to be serialisable). Given this a cross-platform plugin, lowest common demonstrator approach was used and not everyone needs data. For example, for some apps it's enough to navigate to a specific page on tapping on a notification without needing to inspect the notification. Therefore, it is up developers to define what data they need. Given the data needs to be serialisable, this has been exposed as a string from the plugin side so you can pass it JSON that holds the data you need
