### ISSUE TITLE
Cannot find symbol - getNotificationChannels()

### ISSUE THREAD

**Issue by edjostenes** [MaikuB/flutter_local_notifications#1084]
Hi, I'm using the latest prerelease version (5.0.0-nullsafety.1) and the method getNotificationChannels isn't found when I'm building my project. This only happens when building for Android. I've tried to repair the pub-cache, to changing to beta channel but the error persists. Bellow follows more details:

```
../.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-5.0.0-nullsafety.1/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java:1260: error: cannot find symbol
[  +11 ms]             List<NotificationChannel> channels = notificationManagerCompat.getNotificationChannels();
[        ]                                                                           ^
[        ]   symbol:   method getNotificationChannels()
[        ]   location: variable notificationManagerCompat of type NotificationManagerCompat
```

the output of flutter doctor -v:

```
[✓] Flutter (Channel beta, 2.0.1, on macOS 11.2.2 20D80 darwin-x64, locale pt-BR)
    • Flutter version 2.0.1 at /Users/edjosteneslimapoderoso/development/flutter
    • Framework revision c5a4b4029c (6 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/edjosteneslimapoderoso/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1
```

**Comment by MaikuB** [comment]
Do you have a link to a minimal app that can reproduce the issue? There was an issue on at https://github.com/MaikuB/flutter_local_notifications/issues/1059 but was closed as no one had provided one

**Comment by odam1** [comment]
Open your projects android level build.gradle and locate the code below

```
subprojects {
    project.evaluationDependsOn(':app')

    project.configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'androidx.core' &&
                    !details.requested.name.contains('androidx')) {
                details.useVersion "1.0.1"
            }
        }
    }
}
```

then delete **project.configurations.all** and all its content 

the new code now looks like this

```
subprojects {
    project.evaluationDependsOn(':app')
}
```

**Comment by edjostenes** [comment]
> Open your projects android level build.gradle and locate the code below
> 
> ```
> subprojects {
>     project.evaluationDependsOn(':app')
> 
>     project.configurations.all {
>         resolutionStrategy.eachDependency { details ->
>             if (details.requested.group == 'androidx.core' &&
>                     !details.requested.name.contains('androidx')) {
>                 details.useVersion "1.0.1"
>             }
>         }
>     }
> }
> ```
> 
> then delete **project.configurations.all** and all its content
> 
> the new code now looks like this
> 
> ```
> subprojects {
>     project.evaluationDependsOn(':app')
> }
> ```
> 
> After this run the following commands and rebuild your project
> 
> 1. flutter clean
> 2. flutter pub get

Thank you, it worked!

I'm closing this issue.
