### ISSUE TITLE
fullScreenIntent not working as intended

### ISSUE THREAD

**Issue by jenniestrongbow** [MaikuB/flutter_local_notifications#1085]
**Describe the bug**
I thought that fullScreenIntent:true was supposed to display my app in fullscreen when a background notification is received? The notification shows a normal notification, but NOT the app in fullscreen.

**To Reproduce**
See the code below

**Expected behavior**
The app is brought to the foreground when the notification is received in the background.

**Sample code to reproduce the problem**
I just added 

`fullScreenIntent: true`

to the example provided in a FCM myBackgroundMessageHandler function.

**Comment by sebstr1** [comment]
Just ran into the same issue. After I swipe away the "lock screen" the app opens as it should have from having the screen turned off.

**To Reproduce**
1. Created new project
2. Copied the entire example from [pub.dev](https://pub.dev/packages/flutter_local_notifications/examplel)
3. added the missing dependencies to pubspec.yaml
4. add attributes to Androidmanifest.xml as per description `<activity
    android:showWhenLocked="true"
    android:turnScreenOn="true">`
5. run the app in devmode on my Xiaomi MI 2S (Android 10)
6.. Press the "Show full-screen" notification button and close the screen

**Comment by MaikuB** [comment]
@jenniestrongbow there are more steps needed that were covered in the readme [here](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#full-screen-intent-notifications)

@sebstr1 what if you clone the entire repo and just run the example app? Also had you tried to run without having a debug session active. May be possible that having it on treats it as having the device active. You could try to create a release mode APK and sideload it onto the device

Note that if you still don't see it, there isn't anything more the plugin can do. The plugin is already calling the appropriate APIs and requesting the required permissions. The official docs [here](https://developer.android.com/training/notify-user/time-sensitive) also has the following note


> The system UI may choose to display a heads-up notification, instead of launching your full-screen intent, while the user is using the device.

I don't know have knowledge on all of the devices to know if there are quirks around this like on what amount of time is considered to be able to show the full-screen intent

**Comment by MaikuB** [comment]
Closing due to lack of response and plugin is calling the appropriate APIs so there's nothing further it can do
