### ISSUE TITLE
Gettin version issue with flutter_local_notifications

### ISSUE THREAD

**Issue by devappbirds** [MaikuB/flutter_local_notifications#1086]
**Describe the bug**
Because flutter_local_notifications >=3.0.1+4 <5.0.0-nullsafety.0 depends on flutter_local_notifications_platform_interface ^2.0.0+1 which depends on plugin_platform_interface ^1.0.2, flutter_local_notifications >=3.0.1+4 <5.0.0-nullsafety.0 requires plugin_platform_interface ^1.0.2.
And because firebase_storage >=8.0.0 depends on firebase_core_platform_interface ^4.0.0 which depends on plugin_platform_interface ^2.0.0, flutter_local_notifications >=3.0.1+4 <5.0.0-nullsafety.0 is incompatible with firebase_storage >=8.0.0.
So, because vr depends on both firebase_storage ^8.0.0 and flutter_local_notifications ^4.0.1+2, version solving failed.
pub get failed (1; So, because vr depends on both firebase_storage ^8.0.0 and flutter_local_notifications ^4.0.1+2, version solving failed.)

**To Reproduce**

**Expected behavior**

**Sample code to reproduce the problem**

**Comment by WaheedHussainHaans** [comment]
Having the exact same problem any solution or workaround for it would be appreciated thanks in advance

**Comment by MaikuB** [comment]
Please read https://github.com/MaikuB/flutter_local_notifications/issues/1087
