### ISSUE TITLE
How can i add custom repeat interval?

### ISSUE THREAD

**Issue by Prateek-Vortex** [MaikuB/flutter_local_notifications#1088]
### Question

`const AndroidNotificationDetails androidPlatformChannelSpecifics =
        AndroidNotificationDetails(
            'channel id', 'channel name', 'channel des');
    const NotificationDetails platformChannelSpecifics =
        NotificationDetails(android: androidPlatformChannelSpecifics);
    await flutterLocalNotificationsPlugin.periodicallyShow(0, 'repeating title',
        'repeating body', RepeatInterval.hourly, platformChannelSpecifics,
        androidAllowWhileIdle: true);
  }`

Here I want my notification to be repeated every 2 hours 30 mins. How to achieve this?

**Comment by MaikuB** [comment]
Not supported by the plugin and there's already an open issue on this https://github.com/MaikuB/flutter_local_notifications/issues/92. You'd need to come up with your own solution for it
