### ISSUE TITLE
Is there a method to handle when a notification is received?

### ISSUE THREAD

**Issue by AdelKanso** [MaikuB/flutter_local_notifications#1089]
I have a flutter screen to show all received notifications.
There is a method to handle when a notification is clicked, called onSelectNotification

```
 await flutterLocalNotificationsPlugin.initialize(
      initializationSettings,
      onSelectNotification: (payload) =>
          onNotificationClicked(payload),
    );
```
so in onSelectNotification, I added the payload to notifications and show it in notifications screen.

but what if the user didn't click the notification, how to handle this event. is there a method to handle all received notifications(if user clicked on it and if he didn't)?

package version:
flutter_local_notifications: ^4.0.1+2

flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.18363.1379], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.52.1)
[√] Connected device (1 available)

! Doctor found issues in 1 category.

**Comment by MaikuB** [comment]
No there isn't one and is a similar issue to https://github.com/MaikuB/flutter_local_notifications/issues/74. If you only care about receiving this info when the app is running then you could look at forking to implement your own solution that's suitable for your app
