### ISSUE TITLE
Custom intervals for show notification

### ISSUE THREAD

**Issue by anhtu0101** [MaikuB/flutter_local_notifications#109]
Hi MaikuB,

Functions can be made to fire a notification once EveryMinute, Hourly, Daily, Weekly
I want to show notification custom: 
Ex: show on the monday, Tuesday, Thursday for week
Please help me.

**Comment by anhtu0101** [comment]
I would like to display the notice on the days I choose for a week. 
showWeeklyAtDayAndTime function show notice all day of week.

**Comment by MaikuB** [comment]
What you said is incorrect. The function does exactly what you're after

**Comment by MaikuB** [comment]
See https://github.com/MaikuB/flutter_local_notifications/issues/53

**Comment by anhtu0101** [comment]
thank you

**Comment by AbdulBasitSaleem** [comment]
Hi @MaikuB
