### ISSUE TITLE
Failed to handle method call

### ISSUE THREAD

**Issue by bobykurniawan11** [MaikuB/flutter_local_notifications#1091]
So, i'm trying to use local notification. Here is what i do

  Future showNotification(RemoteMessage payload) async {
    FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
        FlutterLocalNotificationsPlugin();
    var initializationSettingsAndroid = AndroidInitializationSettings(
        'launcher_icon.png');
    var initializationSettings = InitializationSettings(android: initializationSettingsAndroid);

    AndroidNotificationDetails androidPlatformChannelSpecifics = AndroidNotificationDetails(
        'your channel id', 'your channel name', 'your channel description',
        importance: Importance.max, showWhen: false);

    NotificationDetails platformChannelSpecifics =
        NotificationDetails(android: androidPlatformChannelSpecifics);

    await flutterLocalNotificationsPlugin.show(
        0, payload.notification.title, payload.notification.body, platformChannelSpecifics,
        payload: json.encode(payload.data));

    flutterLocalNotificationsPlugin.initialize(initializationSettings,
        onSelectNotification: onSelectNotification);
  }

**Describe the bug**
E/MethodChannel#dexterous.com/flutter/local_notifications(25165): Failed to handle method call
E/MethodChannel#dexterous.com/flutter/local_notifications(25165): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
E/MethodChannel#dexterous.com/flutter/local_notifications(25165):   at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.setSmallIcon(FlutterLocalNotificationsPlugin.java:237)
E/MethodChannel#dexterous.com/flutter/local_notifications(25165):   at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification(FlutterLocalNotificationsPlugin.java:179)
E/MethodChannel#dexterous.com/flutter/local_notifications(25165):   at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification(FlutterLocalNotificationsPlugin.java:791)
E/MethodChannel#dexterous.com/flutter/local_notifications(25165):   at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.show(FlutterLocalNotificationsPlugin.java:1054)
E/MethodChannel#dexterous.com/flutter/local_notifications(25165):   at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(FlutterLocalNotificationsPlugin.java:947)
E/MethodChannel#dexterous.com/flutter/local_notifications(25165):   at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#dexterous.com/flutter/local_notifications(25165):   at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#dexterous.com/flutter/local_notifications(25165):   at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/MethodChannel#dexterous.com/flutter/local_notifications(25165):   at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#dexterous.com/flutter/local_notifications(25165):   at android.os.MessageQueue.next(MessageQueue.java:325)
E/MethodChannel#dexterous.com/flutter/local_notifications(25165):   at android.os.Looper.loop(Looper.java:142)
E/MethodChannel#dexterous.com/flutter/local_notifications(25165):   at android.app.ActivityThread.main(ActivityThread.java:6494)
E/MethodChannel#dexterous.com/flutter/local_notifications(25165):   at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#dexterous.com/flutter/local_notifications(25165):   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/MethodChannel#dexterous.com/flutter/local_notifications(25165):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
E/flutter (25165): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference

so, the launcher_icon.png is my icon that i put inside drawable, i already try to remove the extenstion and still not working.

Then i'm trying to use flutter_launcher_icons, here is my set up

```
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/app.png"
```

then i change my

```
var initializationSettingsAndroid = AndroidInitializationSettings(
            'launcher_icon.png')

```
to

```
var initializationSettingsAndroid = AndroidInitializationSettings(
            'launcher_icon')
```

It is still throwing same error

**Comment by yukitoto** [comment]
I have same issue, too.
