### ISSUE TITLE
No custom sound in release mode even after adding keep.xml

### ISSUE THREAD

**Issue by shivanshPurple** [MaikuB/flutter_local_notifications#1092]
No custom sound neither in my app nor in the example app in release mode. But notification is showing. I have created the keep.xml as described in the doc.

my `keep.xml`

`<?xml version="1.0" encoding="utf-8"?>
<resources xmlns:tools="http://schemas.android.com/tools"
    tools:keep="@drawable/*,@raw/*" />`

**Expected behaviour**
Notification sound should be there in release mode!

**Device being tested on**
Xiaomi note 5 Pro
Android 9
In release mode

I haven't tested on any other devices yet. It can be a device-related bug.

**Comment by MaikuB** [comment]
If you download/clone the repository and run the example app, do you have the same problem? If you do, then this would be a device-specific issue and you'd need to see if those devices require changing some settings for it to work

**Comment by shivanshPurple** [comment]
Yes! I still have the same problem when I clone the repository and run the example app without changing anything. What can I change for it to get working, I have no idea what I should change and what I shouldn't!

**Comment by MaikuB** [comment]
You'll need to have a fiddle or look it up as I don't have access to all phones to know. Brands like Xiaomi tend to have their own custom settings. I vaguely remember others mention where to go  in reply to other issues so if you search for Xiaomi here or online then you might find an answer

**Comment by shivanshPurple** [comment]
Ok, something made it right in the same device that I was using!

My flutter initial code looked something like this

`
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  prefs = await SharedPreferences.getInstance();

  platform.invokeMethod("setAlarm", {"hour": "7", "minutes": "00"});

  runApp(App());
}

class App extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _App();
}

class _App extends State<App> {
  @override
  void initState() {
    super.initState();
    intitializeApp();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Sample App',
      theme: ThemeData(
          primaryColor: Colors.deepPurple[700],
          accentColor: Colors.deepPurple[700]),
      home: SetupLists(),
    );
  }
void intitializeApp() async {
    //some async things
    }
}
`

I was fixing a bug related to my app (with the shared preferences plugin) and I removed the initState() function in the _App class. So my code looks like this

`Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  prefs = await SharedPreferences.getInstance();

  platform.invokeMethod("setAlarm", {"hour": "7", "minutes": "00"});
  await intitializeApp();
  runApp(App());
}

class App extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _App();
}

class _App extends State<App> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Sample App',
      theme: ThemeData(
          primaryColor: Colors.deepPurple[700],
          accentColor: Colors.deepPurple[700]),
      home: SetupLists(),
    );
  }
}`

I don't know how by only removing the initState() function from the _App class fixed the notification sound problem but it fixed it!
