### ISSUE TITLE
onSelectNotification callback is not called

### ISSUE THREAD

**Issue by rekonvald** [MaikuB/flutter_local_notifications#1094]
Hi!

I use **4.0.1+2** version of you plugin. It worked great but unfortunately onSelectNotification is not triggered any more(
The code I use

` var initializationSettingsAndroid = fln.AndroidInitializationSettings('ic_local_notification');
    var initializationSettingsIOs = fln.IOSInitializationSettings();
    var initSettings = fln.InitializationSettings(
      android: initializationSettingsAndroid,
      iOS: initializationSettingsIOs,
    );

    flutterLocalNotificationsPlugin.initialize(initSettings,
        onSelectNotification: (String payload) async {
          if (payload != null) {
            debugPrint('notification payload: ' + payload);
          }

          final NotificationAppLaunchDetails details =
          await flutterLocalNotificationsPlugin.getNotificationAppLaunchDetails();

          print("test me !-> ${details.payload}");
        });`
On tapping on notification app just launches

**Comment by dalisc** [comment]
Running into the same problem

**Comment by MaikuB** [comment]
This was covered in the changelog and readme. Copying it here for convenience

> calling initialize will no longer trigger the onSelectNotification if a notification was tapped on prior to calling initialize. This was done as the getNotificationAppLaunchDetails method already provided a way to handle when an application was launched by a notification. Furthermore, calling initialize multiple times (e.g. on different pages) would have previously caused the onSelectNotification callback multiples times as well. This potentially results in the same notification being processed again

You'll need to switch to use the `getNotificationAppLaunchDetails` method

**Comment by rekonvald** [comment]
But I need event when user taps on notification, how getNotificationAppLaunchDetails replaces it? When should it be called?

**Comment by MaikuB** [comment]
`getNotificationAppLaunchDetails` is what you should be using when the app needs to handle being launched from a notification. `onSelectNotification` is only for when the user had tapped on notification whilst the app is already running

**Comment by rekonvald** [comment]
I am sorry, but as far as I understood getNotificationAppLaunchDetails returns details when I call it, right?
How can I handle that tap, or should I add WidgetsBindingObserver and on resume get that details?
Could you provide an example, please

**Comment by MaikuB** [comment]
Please refer to the example app that I mentioned before in https://github.com/MaikuB/flutter_local_notifications/issues/1064. You can download/clone the repo and explore the example that is located at https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications/example.

I only work on OSS projects in my limited, spare time so focus on bugs etc. If you need more detailed help for your app, please make use of places like Slack, Discord etc listed at https://flutter.dev/community.

**Comment by rekonvald** [comment]
Thanks, I looked at example, my app is already running, I use it for background msgs, when app is in background or with lock screen, and in this case there is a problem( sorry

**Comment by rekonvald** [comment]
I downgraded to ^3.0.1+2 and still having issue

**Comment by MaikuB** [comment]
Sorry but I'm not sure what it is you're trying to report here anymore. Your original post seems to imply you had functionality that use to work but now you're saying downgrading still has the same behaviour.

If you're trying to report a bug, then this should use the bug report template.  Before doing so, you should check to see if you can reproduce the issue with the example app. If you can, then include detailed steps on how the issue could be reproduced. If you can't then this typically means you have an issue with your own app/scenarios. This would be where you should reach out to the wider community via Slack etc for more detailed help

**Comment by rekonvald** [comment]
I've found what caused this issue! onSelection stopped working when I added flutter_ios_voip_kit plugin.
But I need both of them and it would be good if they could works together

**Comment by MaikuB** [comment]
That's not an issue for this plugin to resolve as code already exists to prevent it from causing conflicts with other plugins when comes to processing notifications. This is why it can work with the `firebase_messaging` plugin. If you need this plugin working other plugins you're using then you may need to looking at modifying the other plugin to get it work or come up with a different approach for what you're trying to do with your app

**Comment by kururu-abdo** [comment]
from the official doc



Note: from version 4.0 of the plugin, calling initialize will not trigger the onSelectNotification callback when the application was started by tapping on a notification to trigger. Use the getNotificationAppLaunchDetails method that is available in the plugin if you need to handle a notification triggering the launch for an app e.g. change the home route of the app for deep-linking.
