### ISSUE TITLE
Scheduling Local notification is reseting to 12:00 AM midnight for iOS devices after some days. [It was scheduled to 7:00 AM every morning]

### ISSUE THREAD

**Issue by rameshASI** [MaikuB/flutter_local_notifications#1095]
1. I am using version 4.0.1+1 for scheduling local notification 
2. App should get local notification every morning 7:00 AM in the morning
3. It works well for few days [3-4]. Now, App is getting local notification at 12:00 AM [in midnight].
4. App user is in US-region. They have not changed region and clock time in phone device setting 

I am unable to resolve this issue. Can u please guide me ASAP because lot of app users is facing this issue.

Right now, I have uploaded app to App Store for iOS devices only. Android app is ready but due to this issue . I haven't uploaded yet.

**Comment by MaikuB** [comment]
The only guidance I can give you is to debug your app. There are no known issues with this functionality that would cause a shift like you've described that would cause notifications to be rescheduled at a different time. If there was an issue with the plugin itself then I would've expected a lot more others in the community to have reported this

**Comment by MaikuB** [comment]
Closing as there are known issues in the plugin on this. If you've come across a bug then feel free to reopen provided you can also add a link to a minimal app that can reproduce the problem
