### ISSUE TITLE
Location exists but I get Unhandled Exception: Location with the name "Asia/Saigon" doesn't exist

### ISSUE THREAD

**Issue by anonyran** [MaikuB/flutter_local_notifications#1096]
I use below code to print out all supported positions and I have found the Asia / Saigon location but I still get "Unhandled Exception: Location with the name" Asia / Saigon "doesn't exist". Please help!

```
Future<void> configureLocalTimeZone() async {
    tz.initializeTimeZones();
    final List<String> timeZoneList = await FlutterNativeTimezone.getAvailableTimezones();
    for(int i = 0; i < timeZoneList.length; i++) {
      var timeZoneName = timeZoneList[i];
      print(timeZoneName);
    }
    tz.setLocalLocation(tz.getLocation('Asia/Saigon'));
  }
```

![Chưa có tên](https://user-images.githubusercontent.com/75026244/111862885-b5970e80-898a-11eb-95b3-0f176164f47a.png)
![Chưa có tên2](https://user-images.githubusercontent.com/75026244/111862889-ba5bc280-898a-11eb-8266-98107321757a.png)

**Comment by MaikuB** [comment]
Whilst specifying the timezones helps with using functionality from this plugin, the issue you're seeing is to do with an API from the `timezone` plugin so should be posted on the corresponding repository. As such I'll be closing this.

At a guess from what's documented [here](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones), `Asia/Saigon` is deprecated and `Asia/Ho_Chi_Minh` is what should be used instead.
