### ISSUE TITLE
Custom sound doesn't work on Android with release only

### ISSUE THREAD

**Issue by anonyran** [MaikuB/flutter_local_notifications#1098]
I'm trying to play my own custom sound for my notifications on android. 
It works fine with the debug on my android emulator and my personal devices, but when I run the release or build an apk file and install it, there isn't any sound coming out.
I then updated to the latest version, including switching to null-safety, but nothing changed, it still didn't work.

```
var androidDetails = new AndroidNotificationDetails(
      "1", "Channel 1 Name", "Channel 1 Description",
      playSound: soundSetting.value!,
      enableLights: ledSetting.value!,
      enableVibration: vibrationSetting.value!,
      subText: subTextNotification.value,
      usesChronometer: true,
      importance: Importance.max,
      priority: Priority.max,
      icon: '@mipmap/ic_launcher',
      ledOffMs: 500,
      ledOnMs: 250,
      ledColor: const Color.fromARGB(255, 0, 255, 0),
      vibrationPattern: vibrationPattern,
      sound: RawResourceAndroidNotificationSound('slow_spring_board'),
    );
```

**Comment by zumrywahid** [comment]
I noticed the same issue. Looking for a workaround atleast.

**Comment by MaikuB** [comment]
Make sure you've gone through and did the [release build configuration](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#release-build-configuration). Issues like this are indicative that this wasn't done. You can use the example app to cross-reference. If you are certain you have done everything then provide a link to a minimal repo that can reproduce the issue

**Comment by zumrywahid** [comment]
Yes! Its working after i added the produard.  Also I had to mark priority and importance to MAX. It worked in my situation. 

I had a different issue in huawei. I gave up for now. I will update here if i found a solution.

**Comment by MaikuB** [comment]
Closing as the original poster hasn't responded further and there are no known issues around release build with custom sounds provided the configuration has been done properly
