### ISSUE TITLE
Scheduled Notification doesnot fire when App is not running and Phone is locked

### ISSUE THREAD

**Issue by Lone-Wolf17** [MaikuB/flutter_local_notifications#1099]
If a Notification is scheduled for a certain time and at that time the App is not running and the phone is Unlocked the Notification does not show.

**To Reproduce**
1. On the Example App , navigate to the part of the code for "Schedule notification to appear in 5 seconds based on local timezone" . 
2. Change the implementation to schedule to appear in 2 - 5 mins depending on your preference.  you can do this by editing '_zonedSchduleNotification' function
3. Run the App and click on the option.
4. Close the Application and Lock the phone
5. At the Scheduled time, the notification does not fire

**Expected behavior**
The Notification is expected to fire irrespective as long as the Phone is not dead. 

**Sample code to reproduce the problem**
  ` 
 Future<void> _zonedScheduleNotification() async {
    await flutterLocalNotificationsPlugin.zonedSchedule(
        0,
        'scheduled title',
        'scheduled body',
        tz.TZDateTime.now(tz.local).add(const Duration(seconds: 120)),
        const NotificationDetails(
            android: AndroidNotificationDetails('your channel id',
                'your channel name', 'your channel description')),
        androidAllowWhileIdle: true,
        uiLocalNotificationDateInterpretation:
            UILocalNotificationDateInterpretation.absoluteTime);
  }
  `

**Comment by MaikuB** [comment]
What device are you using?

**Comment by Lone-Wolf17** [comment]
Android Tecno LA7 Android 8.1.0

**Comment by MaikuB** [comment]
Whilst I'm not familiar with this brand, with this issue that would mean what you're encountering is a limitation with the imposed by the manufacturer. I mentioned this in the readme [here](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#scheduled-android-notifications). There's nothing this plugin can do to get around it as it's an OS limitation. You'd need to do some research to see that branded version of Android has some mechanism to allow processes to run in the background.
