### ISSUE TITLE
Notification body only shows one line of text and doesn't wrap.

### ISSUE THREAD

**Issue by SuitMonkeyB** [MaikuB/flutter_local_notifications#110]
Hey MaikuB,

It seems that when I pass a block of text to the showNotification, it only displays one line of that text and puts and ellipsis. There seems to be no way to expand the notification or wrap the text. Is there a way this can be achieved?

**Comment by MaikuB** [comment]
I'm assuming this is on Android. You should familiarise yourself more with the Android notification APIs as the plugin acts as a wrapper for them e.g.

https://developer.android.com/training/notify-user/build-notification
https://developer.android.com/training/notify-user/expanded

I suggest you run the example app as well since the scenario has been covered (big text notification)

**Comment by SuitMonkeyB** [comment]
Oh wow, I truly apologize, such a simple oversight. Thanks man.

**Comment by MaikuB** [comment]
No worries :)

**Comment by alvarosantisteban** [comment]
In case it helps someone in the future that dont want to look for it in the example, the code needed is simply the following:

`style: AndroidNotificationStyle.BigText,`

**Comment by ThinkDigitalSoftware** [comment]
> In case it helps someone in the future that dont want to look for it in the example, the code needed is simply the following:
> 
> `style: AndroidNotificationStyle.BigText,`

Thanks. I didn't know what to look for to find this.

**Comment by srihariash999** [comment]
@alvarosantisteban  where do I add this style? The big picture text in the package right now, expects a constant String, I want a different message each time, can you please help?

**Comment by mohammedsalem97** [comment]
Hi,
i have read the discussion above but i cannot understand  what to do?!
where should i put this `style: AndroidNotificationStyle.BigText,` ?

**Comment by mohammedsalem97** [comment]
I finally discovered that is the paramenter and the value to make the job are  `styleInformation: BigTextStyleInformation(''),` 
put it in the `AndroidNotificationDetails()` class

**Comment by flaviodarochalopes** [comment]
use <br>

**Comment by flaviodarochalopes** [comment]
use "<br>"

**Comment by flaviodarochalopes** [comment]
use `<br>`
