### ISSUE TITLE
Remove NotificationAppLaunchDetails

### ISSUE THREAD

**Issue by pepe19000** [MaikuB/flutter_local_notifications#1101]
Hey!

I faced with an issue with getNotificationAppLaunchDetails method. The problem is that i have a login screen in my app. If user log in successfully i checked that is there notification app launch details or not. If yes, the payload always contains a route and redirect to there. 

Problem: If user logout and log in again application redirect to payload route again and again because getNotificationAppLaunchDetails always return with previous value.

How can i remove manually the AppLaunchDetails?

Thank you!

**Comment by MaikuB** [comment]
You can't. It'd be up to your application to manage if it has processed the notification before. It's still correct for the plugin to return info that indicates the fact that it was launched from a notification and so the method should always return the same response when called multiple times.

**Comment by pepe19000** [comment]
> You can't. It'd be up to your application to manage if it has processed the notification before. It's still correct for the plugin to return info that indicates the fact that it was launched from a notification and so the method should always return the same response when called multiple times.

Thank you your response! I think, the solution is that if I store a boolean variable for it in a singleton service. Boolean variable's value depends on i used redirect or not yet.
