### ISSUE TITLE
Large icon

### ISSUE THREAD

**Issue by aoeminh** [MaikuB/flutter_local_notifications#1106]
Can I set large icon is dynamic?

**Comment by MaikuB** [comment]
Could you please elaborate more on what you mean? The only thing supported is what's available via the plugin's API.

**Comment by aoeminh** [comment]
largeIcon: DrawableResourceAndroidBitmap('ic_little_sun'),
I want instead of 'ic_little_sun' by a variable that can change after called API

**Comment by MaikuB** [comment]
No this isn't possible because of how plugins work and Dart does not support passing by reference. For example, if you run the following code, `a` will remain as 2

```
void main() {
  var a = 2;
  foo(a);
  print(a);
}

void foo(int a) {
  a = 5;
}
```
