### ISSUE TITLE
FlutterLocalNotificationsPlugin.initialize is not a NOOP in tests when run on MacOS

### ISSUE THREAD

**Issue by dotdoom** [MaikuB/flutter_local_notifications#1109]
When running widget tests on MacOS computer, initialization fails (NPE).

The documentation in README says:

> If you decide to use the plugin class directly as part of your tests, the methods will be mostly no-op and methods that return data will return default values.
> Part of this is because the plugin detects if you're running on a supported plugin to determine which platform implementation of the plugin should be used. If it's neither Android or iOS, then it defaults to the aforementioned behaviour to reduce friction when writing tests

However, it turns out to be not exactly true on MacOS:

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following NoSuchMethodError was thrown running a test:
The getter 'requestAlertPermission' was called on null.
Receiver: null
Tried calling: requestAlertPermission

When the exception was thrown, this was the stack:
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      MacOSInitializationSettingsMapper.toMap (package:flutter_local_notifications/src/platform_specifics/macos/method_channel_mappers.dart:8:35)
#2      MacOSFlutterLocalNotificationsPlugin.initialize (package:flutter_local_notifications/src/platform_flutter_local_notifications.dart:627:46)
#3      FlutterLocalNotificationsPlugin.initialize (package:flutter_local_notifications/src/flutter_local_notifications_plugin.dart:130:13)
```

**Comment by MaikuB** [comment]
Thanks for finding this. I updated the readme as I forgot to do this for this particular section after macOS support was added. The point was more for what happens on platforms that aren't supported by the plugin so have updated the readme to reflect this
