### ISSUE TITLE
Avatar image

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [MaikuB/flutter_local_notifications#1110]
Hi,

since there is no  option to add feature request i am writing this to bug report.
Is there a way to add avatar image to notification like:
![image](https://user-images.githubusercontent.com/3918999/113548662-380d0880-95f0-11eb-9b90-4a608a54cf8c.png)

**Comment by MaikuB** [comment]
Please take a look at the example app that covers all of the supported features. This includes being able to show a picture so if this isn't suitable for your use case, you most likely need to look into implementing notifications with custom layouts on your own as that would specific to your application

**Comment by vytautas-pranskunas-** [comment]
I have looked example app it supports only big image. It would be great if you can bring easy way to customize layout or support avatar images

**Comment by MaikuB** [comment]
An avatar is still an image so I don't see why you can't specify an avatar as an image. The Android docs have an example of this too where the large icon is a picture of a person (see https://developer.android.com/training/notify-user/expanded).

 If you're in need of custom layouts then that is something you should be implementing as that is specific to your application.

**Comment by vytautas-pranskunas-** [comment]
Yes but faces looks ugly and weird in big image (e. g. Push about John has sent you new chat message) and usually avatar is square and notifications are stretched squares.

**Comment by MaikuB** [comment]
Sounds like you are still describing the big picture style. If you look at the example where they specify an avatar (https://developer.android.com/training/notify-user/expanded#large-style), it does not make use of that style. The avatar is specified as the large icon. If you look at the example [here](https://github.com/MaikuB/flutter_local_notifications/blob/c0087bce1f8fedd04de2c8a3cd1d259315242155/flutter_local_notifications/example/lib/main.dart#L403) and tap on the associated button, you can see the image is a square. On iOS, if you tap on the button associated with [this code](https://github.com/MaikuB/flutter_local_notifications/blob/c0087bce1f8fedd04de2c8a3cd1d259315242155/flutter_local_notifications/example/lib/main.dart#L594), the image is also a square

**Comment by vytautas-pranskunas-** [comment]
The boig image notification looks like this:

![image](https://user-images.githubusercontent.com/3918999/114296247-887ddd80-9aaa-11eb-9224-5b6ec53add82.png)

what I would like to have is ability to set that 'G' avatar in push notification not that big photo.

**Comment by vytautas-pranskunas-** [comment]
unless you support ' .setLargeIcon(emailObject.getSenderAvatar())' from link with description you provided https://developer.android.com/training/notify-user/expanded#large-style:

```
var notification = NotificationCompat.Builder(context, CHANNEL_ID)
        .setSmallIcon(R.drawable.new_mail)
        .setContentTitle(emailObject.getSenderName())
        .setContentText(emailObject.getSubject())
        .setLargeIcon(emailObject.getSenderAvatar())
        .setStyle(NotificationCompat.BigTextStyle()
                .bigText(emailObject.getSubjectAndSnippet()))
        .build()
```

**Comment by vytautas-pranskunas-** [comment]
p.s.

I can see that you support largeIcon (hope that is same largIcon like from google) but only two types:
- DrawableResourceAndroidBitmap 
- FilePathAndroidBitmap

but what i need is to load it from remote like here: https://stackoverflow.com/questions/41479579/how-to-set-a-bigger-icon-in-firebase-app-notification

like this:

```

String name = remoteMessage.getNotification().getIcon();
URL url_value = new URL(name);
Bitmap mIcon1 = BitmapFactory.decodeStream(url_value.openConnection().getInputStream());

AndroidNotificationDetails(
              channel.id,
           ...
.setLargeIcon(mIcon1) <-------------------
....
```
