### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by Polyomino** [MaikuB/flutter_local_notifications#1115]
**Describe the bug**
There's no copy of the BSD license listed at https://pub.dev/packages/flutter_local_notifications/license in this repository. 

**To Reproduce**
1. Go to https://github.com/MaikuB/flutter_local_notifications/
2. Search for 'license' in this repository
3. See no copy of the license in this repository

**Expected behavior**
There is a copy of the license in this repo

**Comment by MaikuB** [comment]
The licenses are in the repo. I would guess you're confused as the repo hosts two packages, one is for the cross-platform facing API, the other is for the platform interface. The specific license you're looking is actually at https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/LICENSE
