### ISSUE TITLE
Repeating notifications with a start date?

### ISSUE THREAD

**Issue by StefanDimov** [MaikuB/flutter_local_notifications#1118]
Hi, I've bumped in to the limitation of `matchDateTimeComponents` not respecting `scheduledDate ` as initial date.

My specific case is as follows:

A repeating notification is set as a reminder for the user to do a particular action in the app. If the user does this action prematurely, the notification is canceled, but should continue repeating in the future. So I basically cancel the notification and create a new one but with the `scheduledDate` for the next iteration (which doesn't work, because of the logic behind `matchDateTimeComponents`).

Is there a workaround for this?

**Comment by MaikuB** [comment]
As the native notification APIs don't support this, the only alternative I know is to make use of APIs provided by a native platform for doing recurring background tasks. However, they won't show up at the precise time for various reasons e.g. takes battery life into account. I believe others in the community are making use of https://pub.dev/packages/background_fetch that interacts with such APIs
