### ISSUE TITLE
Notification duration - Android

### ISSUE THREAD

**Issue by pmagnuson** [MaikuB/flutter_local_notifications#1121]
I am also finding that the timeoutAfter value is not recognized.  I have set to 10000 and the notification displays for about 1.5 seconds.  Setting to 100000 has no different effect.   This is the call to zonedSchedule I am using.  

```dart
void _scheduleBackgroundNotifications(Duration timerLength) async {
    tz.initializeTimeZones();
    await flutterLocalNotificationsPlugin.zonedSchedule(
        0,
        'BuddhaPath',
        'You Have Completed Your Meditation',
        tz.TZDateTime.now(tz.local).add(timerLength),
        NotificationDetails(
            android: AndroidNotificationDetails(
                'BuddhaPath Timer', // channel id
                'BuddhaPath Timer Background', // channel name
                'BuddhaPath Timer Background Notifications', // channel description
                importance: Importance.max,
                priority: Priority.max,
                timeoutAfter: 10000,
                visibility: NotificationVisibility.public,
                enableLights: true,
                enableVibration: true),
            iOS: IOSNotificationDetails(sound: 'slow_spring_board.aiff')),
        androidAllowWhileIdle: true,
        uiLocalNotificationDateInterpretation:
            UILocalNotificationDateInterpretation.absoluteTime);
  }
```

**Comment by MaikuB** [comment]
The plugin is just passing the values for this functionality so if you're seeing an issue then there's nothing further that can be done to resolve this. It most likely means there's some limitation in the Android notification APIs for this that but there's no mention of it in the official docs.

Out of curiosity, what device and Android version are you using?

**Comment by pmagnuson** [comment]
My device is a Google Pixel 3.  Android version 11.

**Comment by MaikuB** [comment]
Ok thanks. Thought it might be an older Android version as I'd seen some comments on people using this functionality on older Android versions when using the APIs directly. 

As mentioned earlier though, there's nothing the plugin do around this so I'll close the issue
