### ISSUE TITLE
Exception has occurred. LocationNotFoundException (Location with the name "GMT" doesn't exist)

### ISSUE THREAD

**Issue by mariamalbarghouti** [MaikuB/flutter_local_notifications#1125]
i have get the git hub local notification repository, when i run it this issues occurs!
i living in Egypt.

```
Exception has occurred.
LocationNotFoundException (Location with the name "GMT" doesn't exist)
```

**Comment by MaikuB** [comment]
As covered [here](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#scheduling-a-notification), neither this plugin or timezone one will know what the device location is. You are required to set it and error occurs as you haven't done so. Refer to the example on how this can be done or make use of the https://pub.dev/packages/flutter_native_timezone mentioned in to do so

**Comment by mariamalbarghouti** [comment]
**i did so :**
```
Future<void> _configureLocalTimeZone() async {
  tz.initializeTimeZones();
  final String? timeZoneName =
      await platform.invokeMethod<String>('getTimeZoneName');
  try {
    tz.setLocalLocation(tz.getLocation(timeZoneName!));
  } catch (e) {
    const String fallback = 'Egypt';
    tz.setLocalLocation(tz.getLocation(fallback));
  }
}
```
but the question is: what if the location is cuba, EET or canada/Yukon and so on!

**Comment by MaikuB** [comment]
I'm not sure what you're trying to ask but generally you either schedule a notification based on a user's timezone obtained via platform channels (which could be via a plugin) or only schedule them for specific locations. If you are referring to the latter case then you may need to find out the format for them. These are generally IANA-based and refers to the values under the "TZ database name" at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

**Comment by mariamalbarghouti** [comment]
i need to enable the user to choose according to his own location but when i use the code without try and catch "Location with the name "GMT" doesn't exist" exception will be thrown.
also flutter_native_timezone return GMT not Egypt for example. @MaikuB

**Comment by MaikuB** [comment]
You would need to look further to see what's going on as I don't go through and debug each person's issues. You cannot make use of the code you've written unless you write the code to return the results on the Android/iOS side as well. If you're not familiar with platform channels then you can read more at https://flutter.dev/docs/development/platform-integration/platform-channels

Having said that, if the plugin is returning GMT as well then chances are the device/simulator has the timezone set to GMT and the error is happening as GMT isn't a recognised timezone by the timezone package. I believe it uses UTC instead but that package isn't one I maintain so if you plan to allow users to pick GMT then you'd need to look further into how to use timezone package to do so.

**Comment by mariamalbarghouti** [comment]
thanks a lot for the responding so fast@MaikuB, your discussion was helpful for me thanks again 💯
