### ISSUE TITLE
Handle notification actions for remote notification

### ISSUE THREAD

**Issue by ngminhduong** [MaikuB/flutter_local_notifications#1126]
I tried to handle event when user click notification actions for remote notification from iOS
But I can not get event from Flutter.
I tried to debug from native iOS from function
```
- (void)userNotificationCenter:(UNUserNotificationCenter *)center
didReceiveNotificationResponse:(UNNotificationResponse *)response
         withCompletionHandler:(void (^)(void))completionHandler NS_AVAILABLE_IOS(10.0)
```

I found center and response always nil.
I don't known if this library can work for remote notifications action?

**Comment by MaikuB** [comment]
No as this library is for local notifications, particularly those generated by this library. If you have remote notifications generated elsewhere then you'll need to work on the logic to do so yourself

**Comment by ngminhduong** [comment]
That mean I can not work with local and remote notification at the same time.
Because `didReceiveNotificationResponse` callback handled by flutter_local_notification.

**Comment by MaikuB** [comment]
Not true as firebase_messaging also works with this plugin and firebase_messaging relies on remote notifications too. What it means is you'd need to find a custom solution for your purposes e.g. fork the repo and make modifications specific to your app or look at how multiple notification plugins can work together.
