### ISSUE TITLE
Android: cancel notifications from app widgets

### ISSUE THREAD

**Issue by alexursul** [MaikuB/flutter_local_notifications#1127]
Hello!
Is it possible to cancel a notification by it's id from a home widget?

**Comment by MaikuB** [comment]
I don't know exactly what you mean but if you need to cancel a notification then you call the `cancel()` method to from the appropriate point in your application.

**Comment by alexursul** [comment]
I'm sorry, I'm a newbie in Android native development. I am unable to use the method `cancel()`  from my home widget because getting notification manager is private: `Cannot access 'getNotificationManager': it is private in 'FlutterLocalNotificationsPlugin'`.

`val notificationManager = FlutterLocalNotificationsPlugin.getNotificationManager(context)
notificationManager.cancel(id)`

**Comment by MaikuB** [comment]
Ok, I think I get what you're asking now. I thought you were referring to Flutter widgets and wanted to do something specific to Android. The purpose of this plugin is to be provide a way to access the native notification APIs from Flutter and a lot of code is written that integrates with Flutter-specific Android APIs so you won't be able to use it. You should be using the Android notification APIs directly as it would. Trying to use the plugin would've added a level of indirection.
