### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method getTimeZoneName on channel dexterx.dev/flutter_local_notifications_example)

### ISSUE THREAD

**Issue by MojtabaTavakkoli** [MaikuB/flutter_local_notifications#1128]
Hello
I'm recently getting this Error when I'm trying to fire a notification:

` Unhandled Exception: MissingPluginException(No implementation found for method getTimeZoneName on channel dexterx.dev/flutter_local_notifications_example)`

It was working fine before and all the setup is done. But after flutter Null-Safety I'm facing it.

This is the method where I try to fire the notification:
`    await flutterLocalNotificationsPlugin.zonedSchedule(

        0,
        'some text',
        'some other text',
        DateTime(xxxx, xx, xx, xx, xx), //The time is generated in app
        const NotificationDetails(
            android: AndroidNotificationDetails(
                'your channel id',
                'your channel name',
                'your channel description'
            )
        ),
        androidAllowWhileIdle: true,
        payload: notificationsJSON,
        uiLocalNotificationDateInterpretation: UILocalNotificationDateInterpretation.absoluteTime
    );`

I also configured the _configureLocalTimeZone() method like so:
`    await _configureLocalTimeZone();

  Future<void> _configureLocalTimeZone() async {
    tz.initializeTimeZones();
    final String timeZoneName =
    await platform.invokeMethod<String>('getTimeZoneName');
    tz.setLocalLocation(tz.getLocation(timeZoneName));
  }`

**Note: ** My project is not yet migrated to null-safety due to some packages I use and they haven't migrated yet.

**Comment by MaikuB** [comment]
This error isn't specific to the plugin as it doesn't implement the method. It was specific to the example app. The error you're seeing happens when you make calls via platform channels but haven't implemented the code on the native side (e.g. on the Android side with Java/Kotlin). I would guess that when you updated, the code on the native side got lost. Perhaps you had recreated the app and so lost the code on the Android/iOS side

**Comment by MojtabaTavakkoli** [comment]
Thanks for responding so fast. I didnt know that in the recent update we have to configure it in the native side because the last version we just set it in manifest.

So, is there any code equivalent code for java? Because my android project is .Java.

**Comment by MaikuB** [comment]
There was but you'd have to search for it, probably via the use of git tags alongside with the change log as the example code use to be in Java on the Android side before. Alternatively, if you only target Android and iOS, then you can use https://pub.dev/packages/flutter_native_timezone

**Comment by MojtabaTavakkoli** [comment]
I'm so sorry. I know its totally off-topic but can you please provide a simple approach for setting up the notifications service for android? I have read the **README** file in the pub but still didn't really get what to do. So if its possible please provide a simple guide to clarify what to do. What I've got so far is that we just need to add some lines of code to the **MainActivity** in android project folder. But its a Kotlin file and as I searched for Java file in open and closed issues but found nothing helpful.

So, I guess all I need to do is to just implement some code in MainActivity.java right? If its so can you please provide a sample code for java? Thanks

**Comment by MaikuB** [comment]
> Thanks for responding so fast. I didnt know that in the recent update we have to configure it in the native side because the last version we just set it in manifest.

I forgot you mentioned this part but there isn't anything specific to null safety migration that would caused your code on this to have been lost.

I'm not adding details specific to the readme as it is off-topic as you say and would just make the readme far longer. It would also duplicate the Flutter docs around using platform channels https://flutter.dev/docs/development/platform-integration/platform-channels. This is crucial to understanding to getting it working. Perhaps that is what you missed.

I also mentioned that if you are only targeting Android and iOS that you don't need such code and could use an existing plugin. Is this the case or are you targeting more platforms? The whole point of the code is to get the timezone from the device so you can schedule from the notification for a specific timezone.

With regards to searching the code, I specifically to look at tags (releases). You seem to be looking at open issues. I should've documented in the changelog for when the example app was updated. You should be able to get the code for the entire repo prior to when that happen. For example, go to https://github.com/MaikuB/flutter_local_notifications/releases to see all of the releases. pub.dev provides similar functionality as well.

Note that you could recreate the Android and iOS side in a different language as well. Running `flutter create .` from the root of the project can do this but you may need to backup some of your code beforehand (e.g. Dart code)

**Comment by MaikuB** [comment]
Oh, looks like the other plugin has added macOS support so I can try to see about updating the example app to make use of it instead

**Comment by MojtabaTavakkoli** [comment]
Thanks for your time.
I finally could make it work using this little steps that you mentioned in this thread. 

You have a great powerful work here but not all of package users are as experienced as you.
So, it would be great if you could add this setup in the readme file so that every one can simply use it. I know you have provided a complete example but yet no one would notice the MainActivity.java or MainActivity.kt in the android root folder etc.

And if you are worry about the readme to get long, it wont. Me personally prefer a full simple step by step guide even if its long to a short and unclear one.


I again thank you for your time.

**Comment by MojtabaTavakkoli** [comment]
And also to prevent any blocks of code to be removed by r8 I use the command `flutter build apk --no-shrink --split-per-abi` to build the release version BUT yet the app stops working after splash screen. It works fine in debug mode but Have that problem only in release version. 

For more info I have this warning:

`    Building without sound null safety
    For more information see https://dart.dev/null-safety/unsound-null-safety

    Note: Some input files use or override a deprecated API.
    Note: Recompile with -Xlint:deprecation for details.
    Note: D:\FlutterSDK\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_local_notifications-5.0.0+1\android\src\main\java\com\dexterous\flutterlocalnotifications\FlutterLocalNotificationsPlugin.java uses or over
    rides a deprecated API.
    Note: Recompile with -Xlint:deprecation for details.
    D:\FlutterSDK\flutter\.pub-cache\hosted\pub.dartlang.org\sqflite_sqlcipher-2.0.0\android\src\main\java\com\davidmartos96\sqflite_sqlcipher\SqfliteSqlCipherPlugin.java:37: warning: [deprecation] Registrar in Plu
    ginRegistry has been deprecated
    import io.flutter.plugin.common.PluginRegistry.Registrar;
                                              ^
    1 warning
`

**Comment by MaikuB** [comment]
Make sure you've gone through and did what's release build configuration section of the readme. Though the issue you're seeing may not necessarily have anything to do with this plugin.

**Comment by MaikuB** [comment]
Example app has been updated to use the flutter_native_timezone plugin now so will close this
