### ISSUE TITLE
Debug vs Release behavior on IOS

### ISSUE THREAD

**Issue by pmagnuson** [MaikuB/flutter_local_notifications#1130]
I am seeing different behavior between `run --debug` vs `run --release`

In this application, a timer is set.  
1. start timer
2. press home button, to send application to background
3. wait for timer to expire

In debug mode, the notification pop-up appears on the home screen.  
In release mode, the notification pop-up does not appear.  When the application is selected for foreground, the notification pop-up then appears.  

The notification callbacks are not implemented as they are not needed for this application.

AppDelegate.swift
```swift
import UIKit
import Flutter

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    if #available(iOS 10.0, *) {
      UNUserNotificationCenter.current().delegate = self as UNUserNotificationCenterDelegate
    }
    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}

```

initialization
```dart
  // local notifications plugin
  final FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
      FlutterLocalNotificationsPlugin();

    // initialize the local notifications plugin
    final IOSInitializationSettings initializationSettingsIOS =
        IOSInitializationSettings(
      requestAlertPermission: true,
      requestBadgePermission: true,
      requestSoundPermission: true,
    );
    const AndroidInitializationSettings initializationSettingsAndroid =
        AndroidInitializationSettings('app_icon');
    final InitializationSettings initializationSettings =
        InitializationSettings(
            android: initializationSettingsAndroid,
            iOS: initializationSettingsIOS);
    flutterLocalNotificationsPlugin.initialize(
      initializationSettings,
    );
```

show notification
```dart
  Future<void> _showNotificationCustomSound() async {
    const AndroidNotificationDetails androidPlatformChannelSpecifics =
        AndroidNotificationDetails(
      'BuddhaPath_channel_0',
      'BuddhaPath Timer Channel',
      'BuddhaPath Meditation Timer Channel',
      sound: RawResourceAndroidNotificationSound('slow_spring_board'),
    );
    const IOSNotificationDetails iOSPlatformChannelSpecifics =
        IOSNotificationDetails(sound: 'slow_spring_board.aiff');
    const NotificationDetails platformChannelSpecifics = NotificationDetails(
      android: androidPlatformChannelSpecifics,
      iOS: iOSPlatformChannelSpecifics,
    );
    await flutterLocalNotificationsPlugin.show(
        0,
        'BuddhaPath',
        'Timer is complete.',
        platformChannelSpecifics);
  }
```

**Comment by MaikuB** [comment]
The issue you're seeing isn't to do with this plugin. When an app is put in the background, the operating system can suspend the app to free up resources. This prevents _any_ running code from continuing to execute. Debug sessions stop the iOS from suspending the app so that would explain the difference in behaviour you're seeing. 

A similar issue was raised in https://github.com/MaikuB/flutter_local_notifications/issues/1093 where I pointed to the official iOS docs on the app lifecycle. As you're targeting iOS, I would suggest reading these docs to understand how the platform works
https://developer.apple.com/documentation/uikit/app_and_environment/managing_your_app_s_life_cycle

I'll be closing this as it's not an issue with the plugin.

**Comment by pmagnuson** [comment]
Thank you for your response.  I appreciate the help.

**Comment by pmagnuson** [comment]
Another note:  your example app provides the behavior I am looking for.  The notification appears even when the app is in background after pushing the Home button.  Does the require more code in `AppDelegate.swift`?
