### ISSUE TITLE
Android: The Lock screen does not wake upon notification

### ISSUE THREAD

**Issue by rohitranjan1991** [MaikuB/flutter_local_notifications#1135]
**Describe the bug**
In Android, The scheduled notification is not waking up the lock screen. I tried adding android:showWhenLocked="true"
    android:turnScreenOn="true" to the AndroidManifest file in the main folder to the activity tag. I am using a Samsung physical phone. Please let me know if. am doing any thing wring here.

Scheduling Code:

await flutterLocalNotificationsPlugin.zonedSchedule(
      0,
      'asdasd',
      'Some Messsage',
      tz.TZDateTime.now(tz.local).add(const Duration(seconds: 5)),
      const NotificationDetails(
        iOS: IOSNotificationDetails(presentAlert: true, presentSound: true, presentBadge: true, sound: "loud-alarm-clock.aiff"),
        android: AndroidNotificationDetails('SOME_REMINDERS', 'Title', 'Message', sound: RawResourceAndroidNotificationSound("loud_alarm_clock")),
      ),
      androidAllowWhileIdle: true,
      payload: jsonEncode({"command": "bt_time_up"}),
      uiLocalNotificationDateInterpretation: UILocalNotificationDateInterpretation.absoluteTime,
    );

**Comment by rohitranjan1991** [comment]
@MaikuB , any update on this ?

**Comment by MaikuB** [comment]
From what I know (e.g. see https://stackoverflow.com/questions/45415774/how-to-make-a-screen-wake-up-when-a-notification-is-received) waking up the lock screen is a separate API so if that is something you need then you'd need to implement that part

**Comment by milindgoel15** [comment]
Could this be added as an optional feature in this plugin?
