### ISSUE TITLE
Scheduling multiple notifications with zonedSchedule results in only the last one working

### ISSUE THREAD

**Issue by sishyanet** [MaikuB/flutter_local_notifications#1136]
I am trying to schedule two notifications each day (e.g. at 8am and 6pm). I'm doing this by calling zonedSchedule twice, something like this:

``` 
  await flutterLocalNotificationsPlugin.zonedSchedule(
      0,
      'My app name',
      message,
      date,
      const NotificationDetails(
        android: AndroidNotificationDetails(
            'ReminderChannel', 'Reminders', 'Daily reminders to practice'),
      ),
      androidAllowWhileIdle: true,
      uiLocalNotificationDateInterpretation:
          UILocalNotificationDateInterpretation.absoluteTime,
      matchDateTimeComponents: DateTimeComponents.time);
```

The `date` I am passing to the above function is calculated like this from an hour (e.g. 8 and 18) and minute (e.g. 0):
```
  final tz.TZDateTime now = tz.TZDateTime.now(tz.local);
  tz.TZDateTime scheduledDate =
      tz.TZDateTime(tz.local, now.year, now.month, now.day, hour, minute);
```

Expected behavior: notifications fire twice a day.
Actual behavior: only the notification scheduled by the last call to zonedSchedule fires. In this example, only the 6pm notification fires. 
If I swap the order of setting the notifications, the other notification fires.

**Comment by MaikuB** [comment]
This is happening as you used the same notification id (0) instead of specifying a unique I'd for each notification
