### ISSUE TITLE
Scheduled notifications don't work if the app is not open at the time the notification is scheduled for

### ISSUE THREAD

**Issue by 4amVim** [MaikuB/flutter_local_notifications#1137]
**Describe the bug**
Scheduled Notifications are not shown if the app is closed

**To Reproduce**

1. Install the example app
2. Open it and click on the button that says 'schedule daily 10:00:00 am notification in your local time zone'
3. Kill the app and wait for the time when notification should occur

**Expected behavior**
The scheduled notification should display even when the app is closed

**Comment by MaikuB** [comment]
What device are you using? Please sure you've read https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#scheduled-android-notifications. I would guess you're using a device that restricts services/apps running in the background

**Comment by 4amVim** [comment]
I've tested on OnePlus 7T and Nord with Andoid 10

**Comment by MaikuB** [comment]
This isn't an issue with the plugin then and the link to the caveat I mentioned applies here. If you run the example on a stock Android device/emulator, it'll behave as expected. Doing some research online (e.g. search for "oneplus background restriction", which is what I did just then) should lead you to find info on how OnePlus devices has battery optimisations in place that can restrict apps from doing stuff when in the background/not running

**Comment by ajaypunekar1** [comment]
Hey @MaikuB,
In my case schedule notification was working fine in background without any settings. But recent days I have found that on same device it is not working.
