### ISSUE TITLE
Ability to change custom android sound without changing channelID

### ISSUE THREAD

**Issue by odonc** [MaikuB/flutter_local_notifications#1140]
**Describe the bug**
On Android, can't change custom notification sound after it has been set. Unless you change the channelID, which as you know creates another notification category in notifications settings. 

**To Reproduce**
Set a custom mp3 with:
`sound: RawResourceAndroidNotificationSound('sound_in_raw_folder'),`
Next time set a different mp3, the original mp3 will play. 

I wan't the user to be able to change the notification sound in settings, picking from a list. But after the first time it can't be changed.

Is this a flutter_local_notifications thing or an android thing? The workaround I can think of is randomly generating a different string each time for the channelID, but they they will keep adding to the list in android notification categories.

**Comment by odonc** [comment]
To stop the android notification categories growing, I could also delete the channel and create a new one each time the user changes the sound, but then in the Android notification settings it will say the number of categories deleted, which isn't ideal. Showing the number of categories is apparently a "spam prevention mechanism".

**Comment by MaikuB** [comment]
The behaviour is how notification channels work on Android (see https://developer.android.com/training/notify-user/channels) so your only option would be to recreate them
