### ISSUE TITLE
does not sound when releasing the apk

### ISSUE THREAD

**Issue by LuisDeLaValie** [MaikuB/flutter_local_notifications#1141]
When I try to generate the apk, for some reason the sound that I specify does not play, it only vibrates, but when it is in debug mode it plays the sound that I specify.

I have only tested this for android, for ios I have not tested it

**Comment by MaikuB** [comment]
This issue arises when the [release build configuration](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#release-build-configuration) steps haven't been done. Please check and make sure you've followed everything there.
