### ISSUE TITLE
Notification sound does not work after updating app version

### ISSUE THREAD

**Issue by venkateshironman** [MaikuB/flutter_local_notifications#1142]
I have several notification channels in my app. For each channel, I assigned a sound Uri to a file stored in my app res/raw folder.

This worked great in several versions, however, in the last version of my app, we noticed that notifications are not playing sound anymore.

Digging and debugging, and I found that the res ID for the sound file has changed. So, if for example in version 1.2 of my app R.raw.tone1 was 12345678, now that same R.raw.tone1 is 123456799. Which results in that the system can't find the file anymore.

Now I'm not sure what should I do? Recreate the channel each version?

Thank you for your help

**Comment by MaikuB** [comment]
From what I've read in https://stackoverflow.com/questions/54796492/android-notification-channel-sounds-stop-working-when-using-sound-uris-that-refe, sounds like the plugin will need a fix to have the sound URI be based on the name of the resource as opposed to an id. After that lands, you would need to recreate the notification channels once for the fix to stick. If you can help submit a PR to fix this then that would be great as I won't be able to get to fixing this immediately

**Comment by venkateshironman** [comment]
I have tried this solution but it doesn't work

**Comment by MaikuB** [comment]
Please be more specific on what you tried

**Comment by venkateshironman** [comment]
I have fixed it.
The solution is 

In root build.gradle of android folder

downgrading androidx.core version from 1.1.0  to 1.0.1 made it work
