### ISSUE TITLE
General question about scheduling.

### ISSUE THREAD

**Issue by Wizzel1** [MaikuB/flutter_local_notifications#1146]
I am creating a Habit tracker and I want to enable the user to choose up to 7 Notificationtimes per day.  This habit can be scheduled up to 7 days per week. That would make a total of 49 scheduled notifications for a single habit. 

My question is: How should this get handled? Do I schedule all those notifications from the start or is there/ should I find a way to schedule only the next notification?(Though I am afraid that won't be possible)

I am mainly asking because of the pending notification limit on ios.

**Comment by MaikuB** [comment]
If you're never going to run into problems with the limits then I would think the approach you mentioned would be fine. However, if it will be an issue then you would need to do more research on this as it's a general question that is more to do with iOS APIs than what the plugin has to offer. This relies on having knowledge of the native APIs so would also suggest you look into what native APIs exist and ask the question on places with more iOS devs that use these APIs directly.

I'll be closing this as I can't offer much advice on this beyond what I mentioned above. Hope you manage to find a solution
