### ISSUE TITLE
FlutterLocalNotificationsPlugin.java uses or overrides a deprecated API

### ISSUE THREAD

**Issue by BringTheChill** [MaikuB/flutter_local_notifications#1148]
I guess title is pretty much explanatory. This java file uses or overrides a deprecated API.

**Comment by MaikuB** [comment]
I'll be closing this as it's more of a warning than an issue. You'll see this occur for a majority of the plugins. If you recompile it with the options mentioned in the warning, you should find it that it has to Flutter's Android APIs. This is so plugins can continue support apps that were built with [Android v1 embedding](https://flutter.dev/docs/release/breaking-changes/android-v1-embedding-create-deprecation)

**Comment by alpeshvasani** [comment]
Do we have any temporary solution to this? This is causing the build to fail.

**Comment by MaikuB** [comment]
6.0 has been released that fixes the warnings though warnings don't cause build errors unless you have a setting to treat warnings as errors. As such, I would say your issue is more likely to do with another issue
