### ISSUE TITLE
Example project Full Screen Notifications not showing

### ISSUE THREAD

**Issue by baconcheese113** [MaikuB/flutter_local_notifications#1151]
**Describe the bug**
The example app full screen notifications don't show full screen on my S20, they go straight to the notification bar like all other notifications and don't wake the screen or show full screen when unlocking my phone

**To Reproduce**
1. Run example project
2. Click on `Show full-screen notification`
3. Press Ok, and turn off screen
4. See that the device isn't woken or showing a full screen notification

**Expected behavior**
Screen wakes and shows full screen notification

**Comment by baconcheese113** [comment]
This might be related to removing
```xml
android:showWhenLocked="true"
android:turnScreenOn="true"
```
from `AndroidManifest.xml`
https://github.com/MaikuB/flutter_local_notifications/commit/41ae0b1f7af9e32301c5b2a831ad91046d4ee18b#diff-5c59805868c48917c45c4f813981c4e142f26fbfab2c6ca045fe4e83d9a84891L26

**Comment by MaikuB** [comment]
Thanks for spotting this. Got accidentally removed when recreating the example app. Did re-adding that back in solve your issue?

**Comment by MaikuB** [comment]
I have a PR for this at https://github.com/MaikuB/flutter_local_notifications/pull/1154. I've tested it on my phone but  If you're able to help test it out and confirm it works for you as well then that would be much appreciated

**Comment by baconcheese113** [comment]
With those 2 lines added back, it works great on my phone as well!

**Comment by IbneUmmah** [comment]
But this line
android:showWhenLocked="true"
keeps the app open when mobile is locked.
I mean when you lock the android it app should not be accessible but app stays accessible due to this line.
