### ISSUE TITLE
timeoutAfter - working ? 

### ISSUE THREAD

**Issue by meridorkobi** [MaikuB/flutter_local_notifications#1153]
Is timeoutAfter suppose to work?
I define 50,000 and it didn't affect 
Is there other option?

**Comment by MaikuB** [comment]
Yes it works and is one of the features covered in the example. All the plugin does is call an Android API for this so if it's not work then there's some other issue going that isn't to do with the plugin itself. Not sure what that could be but perhaps to do with the device you're using. Running on a device/emulator with stock Android should show it working. If it's not working for then not sure what options there are for you. You may need to ask in a community/forum where there are more Android developers.

Closing this as there's nothing else that can be done from the plugin side.
