### ISSUE TITLE
How to display notification while app in background state?

### ISSUE THREAD

**Issue by meridorkobi** [MaikuB/flutter_local_notifications#1155]
Do I have to handle the state or  flutter_local_notification can handle it?

**Comment by MaikuB** [comment]
The only way a notification can appear if the app is in the background is if there was one scheduled using *native* APIs belonging to the target platform. The plugin provides functionality that schedules notification using such APIs. Please make sure you read up on the application lifecycle on the platforms you're targeting as in general, apps may be suspended when in the background. This means application won't be running at all and logic that was scheduled using native APIs may run. Dart APIs on other, such as `Future.delayed(...)`, would not work in these scenarios

**Comment by meridorkobi** [comment]
Thanks, 
I found the way to notify from the  background,  after reading many examples.
Now it's working on Android but not on IOS.
I think It's because I'm using Timer.periodic in foreground and background to check interfaces and notify about problems.
In IOS the timer working in foreground and  stops in the background.
Do you have any idea how to force the timer to work in IOS background?

**Comment by sanchaykasturey** [comment]
hello, can you please help me with the same as well, how did you find the solution?

**Comment by MaikuB** [comment]
@meridorkobi I think you'll need to spend more time digesting what I had written in my response as I had already mentioned why and when using Dart APIs will not work
I had mentioned earlier that apps in the background may be suspended so your application would not be running at all. This is why you're seeing those issues on iOS. That you have it working on Android is more of a coincidence and you could run into the same problem on other Android devices.
