### ISSUE TITLE
[Android] Fullscreen Notification - Background

### ISSUE THREAD

**Issue by ilhamchp** [MaikuB/flutter_local_notifications#1157]
Is there any way to show fullscreen notification when app closed (run in background)?
I already follow all the step and set `fullScreenIntent: true` on `FirebaseMessaging.onBackgroundMessage();`call,  but it doesn't wake up the screen, just show normal notification. Thanks

**Comment by MaikuB** [comment]
There are no known issues within the plugin itself around this and has been tested to appear even the app is closed. As such, if this isn't working for you either there's still an issue with your application or the conditions to show a full-screen intent haven't been met as covered in the Android docs [here](https://developer.android.com/guide/topics/ui/notifiers/notifications#Heads-up).
