### ISSUE TITLE
zonedSchedule not working for periodic notifications on iOS 14.5

### ISSUE THREAD

**Issue by ilievangel1** [MaikuB/flutter_local_notifications#1159]
**Describe the bug**

Single notifications work with no issues however, periodic notifications are not showing using the zonedSchedule method. They are not showing at all. I followed all the steps in the setup guide and enabled foreground notifications for iOS. I also, successfully request notification permissions for iOS.

Everything works just as intended on Android without any issues for single and periodic notifications.
Has anybody else encountered a similar issue like this? 

**Sample code to reproduce the problem**

Future<void> scheduleNotificationDailyAtTime(
    FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin,
    String id,
    String title,
    String body,
    RepeatInterval interval,
    Time notificationTime,
    NotificationPayload payload,
    DateTime scheduledDate) async {
  var androidPlatformChannelSpecifics = AndroidNotificationDetails(
    id,
    'Reminder notifications',
    'Remember about it',
    icon: 'ic_stat_rocket',
  );
  var iOSPlatformChannelSpecifics = IOSNotificationDetails();
  var platformChannelSpecifics = NotificationDetails(
      android: androidPlatformChannelSpecifics,
      iOS: iOSPlatformChannelSpecifics);
  print('NOTIFICATION TYPE: $interval, ID: $id');

  tz.initializeTimeZones();
  var location = tz.getLocation('Europe/Belgrade');
  tz.TZDateTime tzDateTime = tz.TZDateTime(
      location,
      scheduledDate.year,
      scheduledDate.month,
      scheduledDate.day,
      scheduledDate.hour,
      scheduledDate.minute);
  await flutterLocalNotificationsPlugin.zonedSchedule(
      int.parse(id), title, body, tzDateTime, platformChannelSpecifics,
      uiLocalNotificationDateInterpretation: null,
      androidAllowWhileIdle: true,
      matchDateTimeComponents: DateTimeComponents.time,
      payload: json.encode(payload.toJson()));
}

**Comment by PO15ON** [comment]
I'm having the same issue, I have asked on Stackoverflow but no one helped me.
https://stackoverflow.com/questions/67360776/scheduled-notifications-not-working-on-ios-flutter

**Comment by MaikuB** [comment]
Have you tried reproducing the issue with the example app?

**Comment by shreyansh2211** [comment]
try using 
 uiLocalNotificationDateInterpretation:
              UILocalNotificationDateInterpretation.wallClockTime
              
and removing

**Comment by MaikuB** [comment]
Closing as there's been no response from OP
