### ISSUE TITLE
Seperate the receiver for scheduled notifications, and the receiver for retaining notifications after a reboot in the readme

### ISSUE THREAD

**Issue by MichaelPriebe** [MaikuB/flutter_local_notifications#116]
I was wracking my brain why my scheduled notifications weren't showing up, but its because you NEED `<receiver android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver" />` in the AndroidManifest.xml. I skipped over this part because I didn't require notification schedules to be retained after a reboot. (I only needed to delay notifications up to a minute, they would be irrelevant after a reboot.) So separating the two cases would be helpful.

**Comment by MaikuB** [comment]
Can do

**Comment by MaikuB** [comment]
Updated the README in 0.4.1 now. Thanks for the feedback
