### ISSUE TITLE
createNotificationChannel function not working

### ISSUE THREAD

**Issue by appoodeh** [MaikuB/flutter_local_notifications#1160]
### **Describe the bug**

I am trying to create an android notification channel with `flutter_local_notifications: ^5.0.0+4` Put it looks like it does not work as should be.

I wrote a code using `getNotificationChannels `to verify if the channel was created successfully

As you can see in the code below I am using `createNotificationChannel `to create a notifications channel then I am using `getNotificationChannels `to see if the channel was created successfully.

I am getting always **"No notification channels"** as a result in the dialog. I do not know what is wrong with my code,

Has anybody else encountered a similar issue like this?

### **Sample code to reproduce the problem**

```
Future<void> _getNotificationChannels() async {

    await flutterLocalNotificationsPlugin.resolvePlatformSpecificImplementation<
            AndroidFlutterLocalNotificationsPlugin>()?.createNotificationChannel(AndroidNotificationChannel(
      'high_importance_channel', // id
      'High Importance Notifications', // title
      'This channel is used for important notifications', // description
      importance: Importance.max,
    ));

    final Widget notificationChannelsDialogContent =
        await _getNotificationChannelsDialogContent();
    await showDialog<void>(
      context: context,
      builder: (BuildContext context) => AlertDialog(
        content: notificationChannelsDialogContent,
        actions: <Widget>[
          TextButton(
            onPressed: () {
              Navigator.of(context).pop();
            },
            child: const Text('OK'),
          ),
        ],
      ),
    );
  }

  Future<Widget> _getNotificationChannelsDialogContent() async {
    try {
      final List<AndroidNotificationChannel>? channels =
          await flutterLocalNotificationsPlugin
              .resolvePlatformSpecificImplementation<
                  AndroidFlutterLocalNotificationsPlugin>()!
              .getNotificationChannels();

      return Container(
        width: double.maxFinite,
        child: ListView(
          children: <Widget>[
            const Text(
              'Notifications Channels',
              style: TextStyle(fontWeight: FontWeight.bold),
            ),
            const Divider(color: Colors.black),
            if (channels?.isEmpty ?? true)
              const Text('No notification channels')
            else
              for (AndroidNotificationChannel channel in channels!)
                Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    Text('id: ${channel.id}\n'
                        'name: ${channel.name}\n'
                        'description: ${channel.description}\n'
                        'groupId: ${channel.groupId}\n'
                        'importance: ${channel.importance.value}\n'
                        'playSound: ${channel.playSound}\n'
                        'sound: ${channel.sound?.sound}\n'
                        'enableVibration: ${channel.enableVibration}\n'
                        'vibrationPattern: ${channel.vibrationPattern}\n'
                        'showBadge: ${channel.showBadge}\n'
                        'enableLights: ${channel.enableLights}\n'
                        'ledColor: ${channel.ledColor}\n'),
                    const Divider(color: Colors.black),
                  ],
                ),
          ],
        ),
      );
    } on PlatformException catch (error) {
      return Text(
        'Error calling "getNotificationChannels"\n'
        'code: ${error.code}\n'
        'message: ${error.message}',
      );
    }
  }
```

**Comment by MaikuB** [comment]
Please confirm what version of Android your device is on. Notification channels is a concept that is specific Android 8 or newer, which is why the API docs state that the method to create channels is only for those versions of Android

**Comment by appoodeh** [comment]
Thanks for your reply, I was testing on Android 6
It is my mistake.
I am using `createNotificationChannel `to create a channel for FCM to show heads up notifications on background
As alternative solution I used the Local Notifications Plugin to show the notification on `FirebaseMessaging.onBackgroundMessage` so I get the Heads up notification, but the original notification that sent by FCM is still in the notification tray. I tried the `cancel ` method and `cancelAll ` to dismiss it but it does not go a way
I appreciate any help

**Comment by MaikuB** [comment]
If you don't want the notification from FCM to be visible then you'll need to read their docs https://firebase.google.com/docs/cloud-messaging/concept-options

Closing this since the reported issue with the plugin was due to running on a lower Android version
