### ISSUE TITLE
[Android] Get Payload of Active Notification

### ISSUE THREAD

**Issue by robert-virkus** [MaikuB/flutter_local_notifications#1162]
**Describe the bug**

ActiveNotification objects do not contain the payload, which is necessary to handle them correctly.

**To Reproduce**

1. Have at least one active notification
2. Query the active notifications
3. ID, channelID, title and body are available 
4. But no payload

**Expected behavior**

I can retrieve the payload for an active notification.

**Sample code to reproduce the problem**

You can query the active notifications by calling 
```dart
final activeNotifications = await _flutterLocalNotificationsPlugin
        .resolvePlatformSpecificImplementation<
            AndroidFlutterLocalNotificationsPlugin>()
        .getActiveNotifications();
```
just fine, but these notifications do not contain any payload.

In `FlutterLocalNotificationsPlugin.java` there is the following code in the method `getActiveNotifications()`:
```java
 for (StatusBarNotification activeNotification : activeNotifications) {
    HashMap<String, Object> activeNotificationPayload = new HashMap<>();
    activeNotificationPayload.put("id", activeNotification.getId());
    Notification notification = activeNotification.getNotification();
    if (VERSION.SDK_INT >= VERSION_CODES.O) {
        activeNotificationPayload.put("channelId", notification.getChannelId());
    }
    activeNotificationPayload.put("title", notification.extras.getString("android.title"));
    activeNotificationPayload.put("body", notification.extras.getString("android.text"));
    activeNotificationsPayload.add(activeNotificationPayload);
}
```

I assume there should be an additional data item like:
```java
    activeNotificationPayload.put("body", notification.extras.getString("android.payload"));
````

**Comment by QuentinSc** [comment]
🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏

**Comment by MaikuB** [comment]
This isn't possible, which is why it's not there. Sounds like you thought Android notification APIs supports adding custom data/payload directly to the notification but it actually doesn't.

Sidenote: this is more of a feature request since it's to add something that is missing as opposed to a bug. The latter would be an issue with functionality that has been implemented

**Comment by robert-virkus** [comment]
Thanks for the feedback and too bad that this is not possible. The only issue template here is a "bug", otherwise I would have posted this as a feature request.

Thanks again and keep up the good work!

**Comment by MaikuB** [comment]
> The only issue template here is a "bug", otherwise I would have posted this as a feature request.

Only that was defined so that the community knows what is expected when they file a bug report and how they can use the example app to try to reproduce the issue first. If it's not a bug report, there should be an option to file a general issue :)

> Thanks again and keep up the good work!

Thanks :)

**Comment by EmanuelDavid** [comment]
But this is possible in iOS. Why android has not a simple thing like this :(
