### ISSUE TITLE
Class referenced in the manifest, com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver, was not found in the project or the libraries Unresolved package 'dexterous' 

### ISSUE THREAD

**Issue by sanchaykasturey** [MaikuB/flutter_local_notifications#1163]
I am getting this error while writing the following code in AndroidManifest
`        <receiver android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
                <action android:name="android.intent.action.MY_PACKAGE_REPLACED" />
            </intent-filter>
        </receiver>
        <receiver android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver" />
`
Please help me.

**Comment by MaikuB** [comment]
The only assistance I can provide is to point out that you can use the example app found [here](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications/example) to use as a reference with what you have in your own app. Having said that, I'm not sure why you are adding that code into your own app now as if you're using recent versions of the plugin, you don't need to add those lines in manually

**Comment by MaikuB** [comment]
Closing since this was answered and the plugin has not needed changes in the manifest file for a while now
