### ISSUE TITLE
app icon

### ISSUE THREAD

**Issue by dmrcierhn** [MaikuB/flutter_local_notifications#1164]
The application icon is displayed fine in debug mode, but in release mode it appears as a dot or as a empty. any solution? Thank you!

**Comment by otopba** [comment]
Same issue. 
```dart
   const initializationSettingsAndroid = AndroidInitializationSettings(
      'ic_notification',
    );
```
Doesn't work in release

**Comment by otopba** [comment]
@dmrcierhn Until today I had the same issue. Check [this](https://developer.android.com/studio/build/shrink-code#keep-resources) link. It will help you 
![image](https://user-images.githubusercontent.com/4225279/118395738-a368e200-b654-11eb-8470-4884dbccff01.png)

**Comment by dmrcierhn** [comment]
@otopba, it worked for me. Thank you so much for your help. I will close this as the problem is solved
