### ISSUE TITLE
Two "How do I do this?" questions

### ISSUE THREAD

**Issue by jonahgreenthal** [MaikuB/flutter_local_notifications#117]
Thanks for this plugin, and I'm really sorry if this isn't the right place to ask usage questions—please point me to the right place if this isn't it.

Is there a way to determine, given an ID, whether a notification with that ID has been scheduled?

Is there a way to determine whether the user has given permission for notifications to be scheduled?

**Comment by MaikuB** [comment]
Hi asking those kinds of questions here is fine since they are more general questions :)

Answer is no to both. There's a a similar in #75. Only iOS required permissions for showing notifications in general (i.e. not specific to scheduled ones). I'm trying to avoid having platform specific code as much as possible, I'd suggest checking to see if there are plugins for permissions that handle what you need or add the checks you need in your app. The initialise function on iOS returns a Boolean depending on if permissions were granted

**Comment by jonahgreenthal** [comment]
Thanks. On Android, does `FlutterLocalNotificationsPlugin.initialize()` always return `true`? What happens on iOS if `initialize()` is called after permissions are already granted (so they're not getting re-approved, but it will work to send notifications) or already denied (so they're not getting re-denied, but it won't work)?

**Comment by MaikuB** [comment]
I'm not at near a PC to double but I'm pretty sure what you described for Android is how it works. On iOS it always returns true on iOS < 10. On >=10, the intent is to show the permissions prompt and return if the user granted permissions. This isn't shown again and should return true if granted before. If it was denied, calling it the next time should show the permissions prompt again.

There's an example app that you can run and code is available there for you to inspect further.

**Comment by jonahgreenthal** [comment]
Okay, thanks. It would be nice if there were a way (on iOS) for the developer to know that permission had already been denied so they can avoid asking again (and avoid showing UI elements that let users set notifications).

**Comment by MaikuB** [comment]
Managed to get around to checking on iOS and it returns false and won't show the prompt again if it was denied before and initialise is called again. I'd still suggest you run the example to see if it works the way you want it to for your app. Sounds like it does based on your last reply.

Note though as I mentioned above and in the readme, I'm not looking to implement platform-specific methods (see https://medium.com/flutter-io/writing-a-good-flutter-plugin-1a561b986c9c?linkId=57996885 for guidelines in writing plugins)

**Comment by jonahgreenthal** [comment]
For what it's worth (leaving this here in case other people have the same question), I think I can used the SharedPreferences plugin to set/save a `bool` indicating whether a given notification has been set. Obviously you need to have a `String` key; you can just use `id.toString()` or (probably wiser) something like `com.myapp.notifications/####` where `####` is the ID.
