### ISSUE TITLE
Android 12 Manifest issue

### ISSUE THREAD

**Issue by Faiyyazauxy** [MaikuB/flutter_local_notifications#1171]
**Describe the bug**
Since android 12 we need to add `android:exported` value in the manifest for activities & services & receiver having intent filters.

**To Reproduce**
Just make your project target android 12

**Expected behavior**
Should have built without errors

Logs for the same

`[INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl1137663400.tmp/base.apk (at Binary XML file line #150): com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver: Targeting S+ (version 10000 and above) requires that an explicit value for android:exported be defined when intent filters are present]`

**Comment by MaikuB** [comment]
Published a pre-release with changes made to support Android 12

**Comment by MaikuB** [comment]
@Faiyyazauxy did you get to try the prerelease and see if it solved the issue? Note that this will remain a prerelease for now as Android 12 isn't available for general/stable release yet

**Comment by MaikuB** [comment]
Closing now as 9.0.0 now has a stable release with changes for Android 12 release. Should you find other problems, please open a new issue and try to use the bug report template
