### ISSUE TITLE
Default sound not playing when receiving notification - (Even in playSound: true)

### ISSUE THREAD

**Issue by anburocky3** [MaikuB/flutter_local_notifications#1176]
Looks odd, it was working till yesterday, and today when I checked, the sound is not playing  (in Emulator, Physical Android device too). What might be the problem?

**For debugging,** 
I downloaded the flutter_local_notifications example app and tried there, in that also, the sound is not playing..

**What I did:**
1. Deleted the emulator and created a fresh one. Not working.
2. Tried it on a different physical device, not working.

**These are my codes:**
1. For testing, I call it like this: 
  ```dart
  ElevatedButton(
    onPressed: () => showNotification(),
    child: Text("Test Notification"),
  )
  ```

2. These are the exact method, I have used.
  ```dart
  Future<void> showNotification() async {
    flutterLocalNotificationsPlugin.show(
        1,
        "Testing REMOTE",
        "It works!",
        NotificationDetails(
          android: AndroidNotificationDetails(channel.id, channel.name, channel.description,
              importance: Importance.max, priority: Priority.high, playSound: true, icon: '@mipmap/ic_notification'),
        ),
        payload: 'item x');
  }
  ```

3. Since in some android devices (physical) it was not displaying icons and i have to make some tweaks in `AndroidManifest.xml` like these.
```xml
   <application>
        ...
       <meta-data
           android:name="com.google.firebase.messaging.default_notification_icon"
           android:resource="@mipmap/ic_notification" />

       <meta-data
           android:name="com.google.firebase.messaging.default_notification_color"
           android:resource="@color/notification"/>

   </application>
```

**Some Clarifications from my side:**
1. It happens in both (foreground & background)

What might be the problem?

**Comment by MaikuB** [comment]
So you tried the example app on emulators and actual devices as well? If you did so without making any changes to it and sound doesn't work then I would think you have an issue with your development environment. You may need to delete and reinstall your SDKs and/or try using a third party build service.

There's nothing further I can look into here as there aren't any known issues with the plugin on this as it just delegates the logic to the native Android APIs and no one has had such issues either. I have heard there are some phones where sounds won't play unless you change the settings of the device. I suggest you take a look at that more closely as in case that is the issue as Android does separate the settings for playing media and system sounds as well

**Comment by anburocky3** [comment]
Do i have to enable any kind of settings inorder to make it work?

**Comment by MaikuB** [comment]
Depends on the phone (e.g  see https://github.com/MaikuB/flutter_local_notifications/issues/958#issuecomment-759472185) you have and something you would need to look into further yourself. Stock Android devices don't require this but as I mentioned before another thing to be careful of Android does also separate the settings for playing media and system sounds. Some mistakenly think there's a problem when they have actually muted the volume setting that affects the playing of ringtones and notification sounds.

Closing this as there isn't an issue with the plugin on playing sounds and something you would need to look into that may even turn out be an issue with your development environment
