### ISSUE TITLE
Replace / cancel old scheduled notifications

### ISSUE THREAD

**Issue by nielsvanberkel** [MaikuB/flutter_local_notifications#1177]
**Describe the bug**
In order to prevent notifications from stacking up, I would like to cancel any ongoing notifications when a new notification comes up. This can be achieved by configuring all notifications to have the same id. However, the zonedSchedule function seems to require unique id's or will overwrite all scheduled notifications and only display the final notification.

**To Reproduce**
1. Create a zonedSchedule in which each notification has its unique ID
2. Wait for two or more notifications to arrive
3. Notifications do not replace each other but instead stack up.

**Expected behavior**
Offer the possibility to cancel / delete / replace any ongoing notifications. I tried to call 'await flutterLocalNotificationsPlugin.cancel(id - 1);' in the scheduleNotification async function, but I suppose this is called only when scheduling the notification and not when the notification is actually triggered.

Many many thanks for your work on this super useful plugin. This is the missing piece I need :-) Previously discussed (by someone else) [on StackOverflow](https://stackoverflow.com/questions/63762098/flutter-how-to-a-schedule-a-notification-that-replaces-the-last-scheduled-notif), but never received a reply.

**Comment by MaikuB** [comment]
This a feature request as opposed to a bug and what you're after isn't possible either as, assuming you're using Flutter to target multiple platforms, the notification APIs for iOS/macOS don't have callbacks for when a notification is about to be shown when the app isn't running.  If you're only after this behaviour for Android then this is something you would need to fork and customise for your own app
