### ISSUE TITLE
Weekly scheduled repeating notification not working as expected

### ISSUE THREAD

**Issue by arashAndroid** [MaikuB/flutter_local_notifications#1178]
**The App**
  I am developing a reminder application where user can set local notifications to be displayed every week at selected days of week with repeating every X hours. The notification can have start and end time. For example, setting notification to be displayed every SAT,SUN,WED starting at 08:30, ending at 15:30 and repeat every 2 hours between these times (8:30, 10:30, 12:30, 14:30). For simplification, I will set the notification for every day of week. 
  **The Bug**
  The problem is, sometimes it does and sometimes it does not show the notifications. The first notification always displays (8:30 in example above) but the other ones does not show, sometimes. I do set all the notifications.
  **My specs**
  I am using the latest version of plugin (6.0.0). My phone is LG V20 with Android 8.0. Flutter version is 2.2.0 (flutter doctor at the end of this issue). 
  **Code Sample**
  My code is a little complicated. I can provide the full code but it is hard to understand it. I will provide the part that I think is needed. I commented the code so it is understandable and used the example above as the data given to this function:
```dart
  void showNotificationWeekly(
      int id, String title, String body, Reminder reminder) async {
        // Initialize Timezone
    tz.initializeTimeZones();
    final String currentTimeZone =
        await FlutterNativeTimezone.getLocalTimezone();
    print("timezone = $currentTimeZone");
    tz.setLocalLocation(tz.getLocation(currentTimeZone));
    // Initialize Timezone done
    int _notificationId = 0;
    List<int> _notificationIdList = []; // I want to set the IDs in the shared Pref, Thats what this list is for
    /// [weekValues] is an array of 7 bools,  0 to 6 representing each day of week
    /// is this loop, I set all the notification for the days of week that user has selected
    /// in our example we have selected all the days of week, so [weekValues] is array of 7 true booleans.
    for (var i = 0; i < reminder.weekValues.length; i++) { 
      tz.TZDateTime _weekDateTime =
          _getNextDateTime(i + 1, reminder.timeValues);
      tz.TZDateTime _timeEnd = tz.TZDateTime(
        tz.local,
        _weekDateTime.year,
        _weekDateTime.month,
        _weekDateTime.day,
        reminder.timeValues[1][0],
        reminder.timeValues[1][1],
      );
      /// since [weekValues] is all true, the else of this if statement is useless here
      if (reminder.weekValues[i]) {
        /// [timeValues[2][0]] is my repeating hour, this part is complicated but in this example
        /// [timeValues[2][0]] is 2 so the if is true
        if (reminder.timeValues[2][0] > 0) {
          while (_weekDateTime.isBefore(_timeEnd)) {
            /// The output of this print is important and will be provided after this code
            print(
                'if Notification with Id= $_notificationId Succesfully Scheduled at $_weekDateTime');
            await flutterLocalNotificationsPlugin.zonedSchedule(
                _notificationId,
                title,
                body,
                // _temp,
                _weekDateTime.add(Duration(seconds: 1)),
                getPlatformChannelSpecfics(),
                androidAllowWhileIdle: true,
                uiLocalNotificationDateInterpretation:
                    UILocalNotificationDateInterpretation.absoluteTime,
                matchDateTimeComponents: DateTimeComponents.dayOfWeekAndTime);
                /// some incrementall stuff
            _notificationIdList.add(_notificationId);
            _notificationId++;
            /// Adding to the times base of the repeating time
            /// in this example and if the first loop we add 2 hours to 8:30, so the result is 10:30
            _weekDateTime = _weekDateTime.add(
              Duration(
                hours: reminder.timeValues[2][0],
              ),
            );
          }
        } else { // This else can be ignored since we selected all the week days
          tz.TZDateTime _temp = tz.TZDateTime(
            tz.local,
            _weekDateTime.year,
            _weekDateTime.month,
            _weekDateTime.day,
            _weekDateTime.hour,
            _weekDateTime.minute,
            _weekDateTime.second,
            _weekDateTime.millisecond,
            _weekDateTime.microsecond,
          );
          print(
              'else Notification with Id= $_notificationId Scheduled at $_temp');
          _notificationIdList.add(_notificationId);
          await flutterLocalNotificationsPlugin.zonedSchedule(
              _notificationId,
              title,
              body,
              // _temp,
              _temp,
              getPlatformChannelSpecfics(),
              androidAllowWhileIdle: true,
              uiLocalNotificationDateInterpretation:
                  UILocalNotificationDateInterpretation.absoluteTime,
              matchDateTimeComponents: DateTimeComponents.dayOfWeekAndTime);
        }
        _notificationId++;
      }
    }
    await setNotificationIds(_notificationIdList);
  }
```
The output of print:
```

I/flutter ( 7643): Notification with Id= 0 Succesfuly Scheduled at 2021-05-24 08:30:00.000+0430
I/flutter ( 7643): Notification with Id= 1 Succesfuly Scheduled at 2021-05-24 10:30:00.000+0430
I/flutter ( 7643): Notification with Id= 2 Succesfuly Scheduled at 2021-05-24 12:30:00.000+0430
I/flutter ( 7643): Notification with Id= 3 Succesfuly Scheduled at 2021-05-24 14:30:00.000+0430
I/flutter ( 7643): Notification with Id= 5 Succesfuly Scheduled at 2021-05-25 08:30:00.000+0430
I/flutter ( 7643): Notification with Id= 6 Succesfuly Scheduled at 2021-05-25 10:30:00.000+0430
I/flutter ( 7643): Notification with Id= 7 Succesfuly Scheduled at 2021-05-25 12:30:00.000+0430
I/flutter ( 7643): Notification with Id= 8 Succesfuly Scheduled at 2021-05-25 14:30:00.000+0430
I/flutter ( 7643): Notification with Id= 10 Succesfuly Scheduled at 2021-05-26 08:30:00.000+0430
I/flutter ( 7643): Notification with Id= 11 Succesfuly Scheduled at 2021-05-26 10:30:00.000+0430
I/flutter ( 7643): Notification with Id= 12 Succesfuly Scheduled at 2021-05-26 12:30:00.000+0430
I/flutter ( 7643): Notification with Id= 13 Succesfuly Scheduled at 2021-05-26 14:30:00.000+0430
I/flutter ( 7643): Notification with Id= 15 Succesfuly Scheduled at 2021-05-27 08:30:00.000+0430
I/flutter ( 7643): Notification with Id= 16 Succesfuly Scheduled at 2021-05-27 10:30:00.000+0430
I/flutter ( 7643): Notification with Id= 17 Succesfuly Scheduled at 2021-05-27 12:30:00.000+0430
I/flutter ( 7643): Notification with Id= 18 Succesfuly Scheduled at 2021-05-27 14:30:00.000+0430
I/flutter ( 7643): Notification with Id= 20 Succesfuly Scheduled at 2021-05-28 08:30:00.000+0430
I/flutter ( 7643): Notification with Id= 21 Succesfuly Scheduled at 2021-05-28 10:30:00.000+0430
I/flutter ( 7643): Notification with Id= 22 Succesfuly Scheduled at 2021-05-28 12:30:00.000+0430
I/flutter ( 7643): Notification with Id= 23 Succesfuly Scheduled at 2021-05-28 14:30:00.000+0430
I/flutter ( 7643): Notification with Id= 25 Succesfuly Scheduled at 2021-05-29 08:30:00.000+0430
I/flutter ( 7643): Notification with Id= 26 Succesfuly Scheduled at 2021-05-29 10:30:00.000+0430
I/flutter ( 7643): Notification with Id= 27 Succesfuly Scheduled at 2021-05-29 12:30:00.000+0430
I/flutter ( 7643): Notification with Id= 28 Succesfuly Scheduled at 2021-05-29 14:30:00.000+0430
I/flutter ( 7643): Notification with Id= 30 Succesfuly Scheduled at 2021-05-30 08:30:00.000+0430
I/flutter ( 7643): Notification with Id= 31 Succesfuly Scheduled at 2021-05-30 10:30:00.000+0430
I/flutter ( 7643): Notification with Id= 32 Succesfuly Scheduled at 2021-05-30 12:30:00.000+0430
I/flutter ( 7643): Notification with Id= 33 Succesfuly Scheduled at 2021-05-30 14:30:00.000+0430

```
**Flutter doctor**
```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.0, on Microsoft Windows [Version 10.0.19042.985], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[!] Android Studio (not installed)
[√] VS Code (version 1.56.2)
[√] Connected device (3 available)

! Doctor found issues in 1 category.
```
Please help me solve this. Any help would be appreciated.

**Comment by arashAndroid** [comment]
**Update:** 
The `zonedSchedule `seems buggy. I used `showWeeklyAtDayAndTime `function instead of `zonedSchedule `and it has been giving notification every hour in the last 3 days. 
The `showWeeklyAtDayAndTime` is deprecated but it works fine. I read the docs and it said the reason for deprecation is the local time problem. And yes there was a problem but I easily solved it by calling `toLocal()` functionon my my datetime. 
`_weekDateTime = _weekDateTime.toLocal();`
I will give you updates on how it goes in 4 days.

**Comment by MaikuB** [comment]
As mentioned in the bug template, I'd need a link to a repo with a minimal app that can reproduce the issue. There's still a fair bit of code in the snippet you have there and It looks like if the method was called multiple times, you would have notifications you had scheduled before being replaced as your notification id starts from zero again. Don't know if this intentional for your application but may explain the issue you saw if the method was being called multiple times.

You can fork the repo and update the example app as a way of providing a minimal app that can reproduce the issue and this would be the ideal approach.

The reason the old APIs were deprecated was to do with handling daylight savings, it wasn't about converting to local time

**Comment by arashAndroid** [comment]
Thanks for the response. I'll try to do the fork thing and get back to you asap. it might take a week or two.

**Comment by arashAndroid** [comment]
There is a delay on showing the notification. The delay is from 1sec to 3 minutes. For example, if the notification is set at 15:45, it will show on 15:47. Can this be at the exact time?

**Comment by MaikuB** [comment]
Showing with the exact time only works with the `zonedSchedule` method so if you are still use the deprecated method then that would be why

**Comment by iandis** [comment]
@arashAndroid Hi I just noticed this issue too with my app. For me the line that caused it was 

```dart
uiLocalNotificationDateInterpretation: UILocalNotificationDateInterpretation.absoluteTime
```

This caused either delayed multiple scheduled notifications or no notifications at all.
So I set this line to

```dart
uiLocalNotificationDateInterpretation: UILocalNotificationDateInterpretation.wallClockTime
```

I'm not sure whether this is a bug or not, but changing to **wallClockTime** solved the issue for me.

@MaikuB I think you should explain it more on the docs regarding the usage of **UILocalNotificationDateInterpretation**. Let me know what you think🙂

**Comment by MaikuB** [comment]
There is much more explanation I can offer as this comes from the iOS docs. Doesn't sound right that changing between the modes would've fixed an issue for you as it's supposed to only be relevant when changing timezones and when on olders iOS versions i.e. < 10

**Comment by arashAndroid** [comment]
Hello again. I fixed my issue, I don't exactly know where I did wrong, but I have some guesses.
I rebuilt my app using the example code. I copied everything from example app to my main.dart then removed the extra stuff ( I only kept the weekly part). Then I used the weekly notification into my loop instead of my own code, they were the same tho. But the app worked well. It gives notification at the exact time. 
The difference was that I initialized everything in main.dart. I used to init everything in my NotificationManager class. This maybe the reason for the fix.

**Comment by thisispratik01** [comment]
> **The App** I am developing a reminder application where user can set local notifications to be displayed every week at selected days of week with repeating every X hours. The notification can have start and end time. For example, setting notification to be displayed every SAT,SUN,WED starting at 08:30, ending at 15:30 and repeat every 2 hours between these times (8:30, 10:30, 12:30, 14:30). For simplification, I will set the notification for every day of week. **The Bug** The problem is, sometimes it does and sometimes it does not show the notifications. The first notification always displays (8:30 in example above) but the other ones does not show, sometimes. I do set all the notifications. **My specs** I am using the latest version of plugin (6.0.0). My phone is LG V20 with Android 8.0. Flutter version is 2.2.0 (flutter doctor at the end of this issue). **Code Sample** My code is a little complicated. I can provide the full code but it is hard to understand it. I will provide the part that I think is needed. I commented the code so it is understandable and used the example above as the data given to this function:
> 
> ```dart
>   void showNotificationWeekly(
>       int id, String title, String body, Reminder reminder) async {
>         // Initialize Timezone
>     tz.initializeTimeZones();
>     final String currentTimeZone =
>         await FlutterNativeTimezone.getLocalTimezone();
>     print("timezone = $currentTimeZone");
>     tz.setLocalLocation(tz.getLocation(currentTimeZone));
>     // Initialize Timezone done
>     int _notificationId = 0;
>     List<int> _notificationIdList = []; // I want to set the IDs in the shared Pref, Thats what this list is for
>     /// [weekValues] is an array of 7 bools,  0 to 6 representing each day of week
>     /// is this loop, I set all the notification for the days of week that user has selected
>     /// in our example we have selected all the days of week, so [weekValues] is array of 7 true booleans.
>     for (var i = 0; i < reminder.weekValues.length; i++) { 
>       tz.TZDateTime _weekDateTime =
>           _getNextDateTime(i + 1, reminder.timeValues);
>       tz.TZDateTime _timeEnd = tz.TZDateTime(
>         tz.local,
>         _weekDateTime.year,
>         _weekDateTime.month,
>         _weekDateTime.day,
>         reminder.timeValues[1][0],
>         reminder.timeValues[1][1],
>       );
>       /// since [weekValues] is all true, the else of this if statement is useless here
>       if (reminder.weekValues[i]) {
>         /// [timeValues[2][0]] is my repeating hour, this part is complicated but in this example
>         /// [timeValues[2][0]] is 2 so the if is true
>         if (reminder.timeValues[2][0] > 0) {
>           while (_weekDateTime.isBefore(_timeEnd)) {
>             /// The output of this print is important and will be provided after this code
>             print(
>                 'if Notification with Id= $_notificationId Succesfully Scheduled at $_weekDateTime');
>             await flutterLocalNotificationsPlugin.zonedSchedule(
>                 _notificationId,
>                 title,
>                 body,
>                 // _temp,
>                 _weekDateTime.add(Duration(seconds: 1)),
>                 getPlatformChannelSpecfics(),
>                 androidAllowWhileIdle: true,
>                 uiLocalNotificationDateInterpretation:
>                     UILocalNotificationDateInterpretation.absoluteTime,
>                 matchDateTimeComponents: DateTimeComponents.dayOfWeekAndTime);
>                 /// some incrementall stuff
>             _notificationIdList.add(_notificationId);
>             _notificationId++;
>             /// Adding to the times base of the repeating time
>             /// in this example and if the first loop we add 2 hours to 8:30, so the result is 10:30
>             _weekDateTime = _weekDateTime.add(
>               Duration(
>                 hours: reminder.timeValues[2][0],
>               ),
>             );
>           }
>         } else { // This else can be ignored since we selected all the week days
>           tz.TZDateTime _temp = tz.TZDateTime(
>             tz.local,
>             _weekDateTime.year,
>             _weekDateTime.month,
>             _weekDateTime.day,
>             _weekDateTime.hour,
>             _weekDateTime.minute,
>             _weekDateTime.second,
>             _weekDateTime.millisecond,
>             _weekDateTime.microsecond,
>           );
>           print(
>               'else Notification with Id= $_notificationId Scheduled at $_temp');
>           _notificationIdList.add(_notificationId);
>           await flutterLocalNotificationsPlugin.zonedSchedule(
>               _notificationId,
>               title,
>               body,
>               // _temp,
>               _temp,
>               getPlatformChannelSpecfics(),
>               androidAllowWhileIdle: true,
>               uiLocalNotificationDateInterpretation:
>                   UILocalNotificationDateInterpretation.absoluteTime,
>               matchDateTimeComponents: DateTimeComponents.dayOfWeekAndTime);
>         }
>         _notificationId++;
>       }
>     }
>     await setNotificationIds(_notificationIdList);
>   }
> ```
> 
> The output of print:
> 
> ```
> 
> I/flutter ( 7643): Notification with Id= 0 Succesfuly Scheduled at 2021-05-24 08:30:00.000+0430
> I/flutter ( 7643): Notification with Id= 1 Succesfuly Scheduled at 2021-05-24 10:30:00.000+0430
> I/flutter ( 7643): Notification with Id= 2 Succesfuly Scheduled at 2021-05-24 12:30:00.000+0430
> I/flutter ( 7643): Notification with Id= 3 Succesfuly Scheduled at 2021-05-24 14:30:00.000+0430
> I/flutter ( 7643): Notification with Id= 5 Succesfuly Scheduled at 2021-05-25 08:30:00.000+0430
> I/flutter ( 7643): Notification with Id= 6 Succesfuly Scheduled at 2021-05-25 10:30:00.000+0430
> I/flutter ( 7643): Notification with Id= 7 Succesfuly Scheduled at 2021-05-25 12:30:00.000+0430
> I/flutter ( 7643): Notification with Id= 8 Succesfuly Scheduled at 2021-05-25 14:30:00.000+0430
> I/flutter ( 7643): Notification with Id= 10 Succesfuly Scheduled at 2021-05-26 08:30:00.000+0430
> I/flutter ( 7643): Notification with Id= 11 Succesfuly Scheduled at 2021-05-26 10:30:00.000+0430
> I/flutter ( 7643): Notification with Id= 12 Succesfuly Scheduled at 2021-05-26 12:30:00.000+0430
> I/flutter ( 7643): Notification with Id= 13 Succesfuly Scheduled at 2021-05-26 14:30:00.000+0430
> I/flutter ( 7643): Notification with Id= 15 Succesfuly Scheduled at 2021-05-27 08:30:00.000+0430
> I/flutter ( 7643): Notification with Id= 16 Succesfuly Scheduled at 2021-05-27 10:30:00.000+0430
> I/flutter ( 7643): Notification with Id= 17 Succesfuly Scheduled at 2021-05-27 12:30:00.000+0430
> I/flutter ( 7643): Notification with Id= 18 Succesfuly Scheduled at 2021-05-27 14:30:00.000+0430
> I/flutter ( 7643): Notification with Id= 20 Succesfuly Scheduled at 2021-05-28 08:30:00.000+0430
> I/flutter ( 7643): Notification with Id= 21 Succesfuly Scheduled at 2021-05-28 10:30:00.000+0430
> I/flutter ( 7643): Notification with Id= 22 Succesfuly Scheduled at 2021-05-28 12:30:00.000+0430
> I/flutter ( 7643): Notification with Id= 23 Succesfuly Scheduled at 2021-05-28 14:30:00.000+0430
> I/flutter ( 7643): Notification with Id= 25 Succesfuly Scheduled at 2021-05-29 08:30:00.000+0430
> I/flutter ( 7643): Notification with Id= 26 Succesfuly Scheduled at 2021-05-29 10:30:00.000+0430
> I/flutter ( 7643): Notification with Id= 27 Succesfuly Scheduled at 2021-05-29 12:30:00.000+0430
> I/flutter ( 7643): Notification with Id= 28 Succesfuly Scheduled at 2021-05-29 14:30:00.000+0430
> I/flutter ( 7643): Notification with Id= 30 Succesfuly Scheduled at 2021-05-30 08:30:00.000+0430
> I/flutter ( 7643): Notification with Id= 31 Succesfuly Scheduled at 2021-05-30 10:30:00.000+0430
> I/flutter ( 7643): Notification with Id= 32 Succesfuly Scheduled at 2021-05-30 12:30:00.000+0430
> I/flutter ( 7643): Notification with Id= 33 Succesfuly Scheduled at 2021-05-30 14:30:00.000+0430
> ```
> 
> **Flutter doctor**
> 
> ```
> flutter doctor
> Doctor summary (to see all details, run flutter doctor -v):
> [√] Flutter (Channel stable, 2.2.0, on Microsoft Windows [Version 10.0.19042.985], locale en-US)
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
> [√] Chrome - develop for the web
> [!] Android Studio (not installed)
> [√] VS Code (version 1.56.2)
> [√] Connected device (3 available)
> 
> ! Doctor found issues in 1 category.
> ```
> 
> Please help me solve this. Any help would be appreciated.

To show  notifications for particular day in a week at specific time use Zonedschedule() method from flutter_local_notification library .  old one showWeeklyatdaytime() is deprecated .    i also faced issue while using zoned schedule() for weekly notification but finally i sorted it out . everything working fine . code is as below  ..

  weeklyScheduledNotification(DateTime dateTime, int hour, int minutes) async {
    await flutterLocalNotificationsPlugin.zonedSchedule(
      2000, //you can specify any id in int format
      "weekly",  //any string
      "weekly", //any string
      tz.TZDateTime(tz.local, dateTime.year, dateTime.month, dateTime.day, hour,
          minutes, dateTime.weekday),
      

      
      const NotificationDetails(
          android: AndroidNotificationDetails(
              'your channel id', 'your channel name',
              channelDescription: "your channel desc")),
      androidAllowWhileIdle: true,
      uiLocalNotificationDateInterpretation:
          UILocalNotificationDateInterpretation.wallClockTime,
      matchDateTimeComponents: DateTimeComponents.dayOfWeekAndTime,

      payload: "weekly", // any string
    );
  }

im getting datetime from calendar  as below :

  _getDateFromUser() async {
    DateTime? _pickerDate = await showDatePicker(
        context: context,
        initialDate: DateTime.now(),
        firstDate: DateTime(2000),
        lastDate: DateTime(2321));

    if (_pickerDate != null) {
      setState(() {
        _selectedDate = _pickerDate;
      });
    } else {
      print("please select date");
    }
  }

then i called my  weeklyScheduledNotification(_selectedDate ,10,20);   and scheduled day and time of week to show notification .  
 you can pass hour and minutes dynamically .

hope it will help you 😊

**Comment by taherhamdy** [comment]
اكتب شعر حزين عن فقدان ابنتي صفا و ان كل الآماكن اللي كنا نزورها 
مشتاقة لها
