### ISSUE TITLE
How to reschedule a notification for different time when that particular notification receives.  

### ISSUE THREAD

**Issue by HamadBangash353** [MaikuB/flutter_local_notifications#1179]
How to reschedule a notification  for different time when that particular notification receives.  I mean if i have scheduled a notification for a prayer but as you know that prayer time changes day by day so how can i reschedule it for correct time again when notification of previous time receives without opening app.

**Comment by MaikuB** [comment]
Trying to reschedule a notification right after it's been triggered cannot be done
