### ISSUE TITLE
How to disable notifications when the app is in the foreground (Android)

### ISSUE THREAD

**Issue by racloubon** [MaikuB/flutter_local_notifications#1181]
I have scheduled notifications, but if the user is using the app (i.e. the app is in the foreground), I don't want the notifications to be displayed. This is default behaviour for iOS, but it would be useful to be able to specify it for Android as well. Is this currently possible?

As reference, something similar was done for React Native here: https://github.com/zo0r/react-native-push-notification/pull/1183/files

**Comment by danny2585** [comment]
usually the app has 4 states try the following


@override
  void didChangeAppLifecycleState(AppLifecycleState state) async {
    super.didChangeAppLifecycleState(state);
    if (state == AppLifecycleState.resumed) {
      await _notificationManagerState.cancelAllNotifications();
    } else if (state == AppLifecycleState.inactive) {
      
    } else if (state == AppLifecycleState.paused) {
      
    } else if (state == AppLifecycleState.detached) {
      
    }
    print('state = $state');
  }

**Comment by danny2585** [comment]
usually the app has 4 states try the following:

```
@override
void didChangeAppLifecycleState (estado de AppLifecycleState) async {
super.didChangeAppLifecycleState (estado);
if (estado == AppLifecycleState.resumed) {
await _notificationManagerState.cancelAllNotifications ();
} else if (estado == AppLifecycleState.inactive) {

} else if (state == AppLifecycleState.paused) {
  
} else if (state == AppLifecycleState.detached) {
  
}
print('state = $state');
}
```

**Comment by danny2585** [comment]
usually the app has 4 states try the following:



```
@override
  void didChangeAppLifecycleState(AppLifecycleState state) async {
    super.didChangeAppLifecycleState(state);
    if (state == AppLifecycleState.resumed) {
      await _notificationManagerState.cancelAllNotifications();
    } else if (state == AppLifecycleState.inactive) {

    } else if (state == AppLifecycleState.paused) {
      
    } else if (state == AppLifecycleState.detached) {

    }
    print('state = $state');
  }
```

**Comment by racloubon** [comment]
@danny2585 I'm not sure this works - certainly we'd stop all of the notifications when the app is in the foreground, but (assuming it's the right way to do it) how would we then re-schedule all the cancelled notifications when the user leaves the app?

**Comment by danny2585** [comment]
`else if (state == AppLifecycleState.paused) { }`

This part will be in charge of identifying when the user is outside the app. you can program, activate or call any notification from here

**Comment by racloubon** [comment]
Thanks for responding, but I'm not sure this solves the problem: for example, you can - and often do - go from the foreground to killing the app without passing through the background ('paused' state). Aside from that, it seems quite error-prone and expensive to capture, then cancel all pending notifications every time you pause the app, only to look them up and reschedule all of them every time you resume.

I've actually since found a similar suggestion of doing periodic updates while the app is running to clear any notifications that are just about to fire. Again, it's not perfect, but less error-prone.

I guess at this moment, there's no way to configure Android - through this library or otherwise - to match iOS and just not send notifications when the app is open.

**Comment by MaikuB** [comment]
There isn't currently isn't way via the plugin. I'm not familiar with the APIs mentioned in that PR but apparently it uses APIs that one of the developers that works on Android itself says not to use (see https://groups.google.com/g/android-developers/c/zH-2bovZSLg/m/L2YM8Z1N-HwJ?pli=1). As such, I would see if there is an approach that would require contribution from the community and it should be one that doesn't use same Androids APIs as referenced in that PR
