### ISSUE TITLE
Any plan to support windows local notification?

### ISSUE THREAD

**Issue by jinfagang** [MaikuB/flutter_local_notifications#1183]
Any plan to support windows local notification? this is really needed.

**Comment by MaikuB** [comment]
There's an open issue on desktop support already. Please see https://github.com/MaikuB/flutter_local_notifications/issues/746. If you need support for Windows then you'll need to submit a PR. Closing as a duplicate of https://github.com/MaikuB/flutter_local_notifications/issues/746
