### ISSUE TITLE
Unable to Get Payload Content When Tap On Notification (iOS)

### ISSUE THREAD

**Issue by Jayvd** [MaikuB/flutter_local_notifications#1186]
I am wondering why does this no longer possible? As I recalled 6 months ago, on older version of this plugin, the code below worked. But now it no longer works.

Even if the app is in the background, and I tap the notification. It doesnt trigger the `onSelectNotification` function.. 

Any thoughts please? Thank you

```

    var androidInitSettings = AndroidInitializationSettings("app_notif_icon");
    var iosInitSettings = IOSInitializationSettings(requestAlertPermission: false, requestBadgePermission: false, requestSoundPermission: false);
    var initSettings = InitializationSettings(android: androidInitSettings, iOS: iosInitSettings);

    flutterLocalNotificationsPlugin.initialize(initSettings, onSelectNotification: onSelectNotification);
```

```

  Future<dynamic> onSelectNotification(String? payload) async {
    print("payload content: $payload");
  }
```

**Comment by MaikuB** [comment]
There were breaking changes done in the plugin a while back. Please make sure you check the changelog and updated readme

**Comment by Jayvd** [comment]
@MaikuB I did read the changelog, but `getNotificationAppLaunchDetails` doesnt get it done either

```

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    super.didChangeAppLifecycleState(state);
    isInForeground = state == AppLifecycleState.resumed;

    print("APP IS IN FOREGROUND == $isInForeground");
    if(isInForeground) {
      notificationHelper.getNotificationAppLaunchDetails();
    }
  }
```

```

  void initializePlatformSettings() {

    var androidInitSettings = AndroidInitializationSettings("app_notif_icon");
    var iosInitSettings = IOSInitializationSettings(requestAlertPermission: false, requestBadgePermission: false, requestSoundPermission: false);
    var initSettings = InitializationSettings(android: androidInitSettings, iOS: iosInitSettings);

    flutterLocalNotificationsPlugin.initialize(initSettings, onSelectNotification: onSelectNotification);
  }

  void getNotificationAppLaunchDetails() async {
    notificationAppLaunchDetails = (await flutterLocalNotificationsPlugin.getNotificationAppLaunchDetails())!;

    if(notificationAppLaunchDetails.didNotificationLaunchApp) {
      print("LAUNCHED BY NOTIF");

      print(notificationAppLaunchDetails.payload);
    }
    else {
      print("NOT LAUNCHED BY NOTIF");
    }
  }

```

**Comment by MaikuB** [comment]
I'd say there's an issue somewhere with the way you're dealing with it and would be something you need get help from others to track down if you can't do so yourself. I haven't seen any other reports on this and haven't seen the issue you've described occur with the example app either. Did you try to reproduce the issue with the example app as well?

**Comment by Jayvd** [comment]
@MaikuB Thanks for the reply.  

The example app would work **only** **when the app is TOTALLY CLOSED.** 

When the app is "minimized" in the background and user tap on the notification, nothing will happen since the code in the `main.dart` will not be run

**Comment by MaikuB** [comment]
Well then, I'm not sure how you're running into the issue and how it's possible unless you've got weird issues with your development environment. I don't see how the changes in handling launch notifications would've affected your scenario. Can you fork the repo, download/clone your fork and do a recording from running the example app in release mode (`flutter run --release`) based on the code `log_lifecycle_example_app` branch? This has changes to display the lifecycle changes and as you can see from the recording I've done, it works fine for me

https://user-images.githubusercontent.com/25263378/120866329-06ee8b80-c5d3-11eb-89a7-2e1931799604.mp4

**Comment by MaikuB** [comment]
As this could not be reproduced and there's no updates in providing ways to reproduce the reported issue, this will be closed. Feel free to re-open once you're able to provide a link to a repository with a minimal app that can reproduce the issue
