### ISSUE TITLE
CastError at getNotificationAppLaunchDetails

### ISSUE THREAD

**Issue by bhtri** [MaikuB/flutter_local_notifications#1188]
Hi everyone!
I'm trying to get details on if the app was launched via a notification like [this](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#getting-details-on-if-the-app-was-launched-via-a-notification-created-by-this-plugin) then get the following exception at [here](https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/lib/src/platform_flutter_local_notifications.dart#L48)
```
例外が発生しました
_CastError (Null check operator used on a null value)
```
Here is my error code in main when call `getNotificationAppLaunchDetails`
```
Future<void> main() async {
  String initialRoute = HomePage.routeName;

  final NotificationAppLaunchDetails? notificationAppLaunchDetails =
      await flutterLocalNotificationsPlugin.getNotificationAppLaunchDetails();
  if (notificationAppLaunchDetails?.didNotificationLaunchApp ?? false) {
    selectedNotificationPayload = notificationAppLaunchDetails!.payload!;
    initialRoute = SecondPage.routeName;
  }

  runApp(
    MaterialApp(
      initialRoute: initialRoute,
      routes: <String, WidgetBuilder>{
        HomePage.routeName: (_) => HomePage(title: 'Test Notification'),
        SecondPage.routeName: (_) => SecondPage(selectedNotificationPayload),
      },
    ),
  );
}
```
I also tried referencing the [example](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications/example) but still don't understand, am i missing something?
Thanks for all the comments and sharing

**Comment by MaikuB** [comment]
I'm not sure what's going on and haven't seen anyone else mention this issue so be best if you can provide a link to a repo containing a minimal app that can reproduce the issue

**Comment by bhtri** [comment]
I'm sorry this is my code `WidgetsFlutterBinding.ensureInitialized()` omission.
I have consulted more [here](https://stackoverflow.com/a/63873689/6284714), and thank you @MaikuB very much ^^
