### ISSUE TITLE
Updating from 5.0.0+4 to 6.0.0 causes MissingPluginException

### ISSUE THREAD

**Issue by mattbreeland** [MaikuB/flutter_local_notifications#1192]
**Describe the bug**

When running my app and initializing the FlutterLocalNotificationsPlugin, the following exception is thrown:

```
Exception has occurred.
MissingPluginException (MissingPluginException(No implementation found for method initialize on channel dexterous.com/flutter/local_notifications))
```

No changes were made except switching from 5.0.0+4 to 6.0.0, which in turn updates my pubspec.lock file  as so:
from  flutter: ">=1.26.0-17.6.pre" to  flutter: ">=2.2.0"

Switching flutter versions seems to break this plugin for some reason.

**Expected behavior**

I would expect the plugin to still work without throwing this exception.

Does the flutter 2.2.0 SDK require a new plugin installation process or something? I also did a clean build but it did not resolve the issue.

**Comment by mattbreeland** [comment]
It seems like doing this upgrade in isolation is the problem, but when doing a more complete library upgrade then things work.

> flutter pub upgrade

followed by

> flutter pub upgrade --major-versions

seemed to fix things for me.

These were the original results from 

> flutter pub outdated

> direct dependencies:
> flutter_local_notifications                     *5.0.0+4  *5.0.0+4    6.0.0       6.0.0
> get_it                                          *6.1.1    *6.1.1      7.1.3       7.1.3
> injectable                                      *1.3.0    *1.3.0      1.4.1       1.4.1
> stacked                                         *2.1.6    *2.1.6      2.1.7       2.1.7
> 
> dev_dependencies:
> injectable_generator                            *1.3.0    *1.3.0      1.4.1       1.4.1
> 
> transitive dependencies:
> async                                           *2.6.1    *2.6.1      *2.6.1      2.7.0
> flutter_local_notifications_platform_interface  *3.0.0    *3.0.0      4.0.0       4.0.0
> meta                                            *1.3.0    *1.3.0      *1.3.0      1.4.0
> 
> transitive dev_dependencies:
> args                                            *2.0.0    *2.0.0      *2.0.0      2.1.1
> petitparser                                     *4.1.0    *4.1.0      *4.1.0      4.2.0
> test_api                                        *0.3.0    *0.3.0      *0.3.0      0.4.0


And of course, as soon as I am writing this, after adding the 

> flutter_facebook_auth: ^3.4.1

 dependency to pubspec.yaml, the MissingPluginException strikes again. Very strange. I am not sure what is going on here.

**Comment by layndev** [comment]
Hi! I am facing the same issue too. I have done @mattbreeland sugestiona "flutter pub upgrade --major-versions" but still Plugin Exception.. This happen after upgrade flutter from 2.0.2-pre to 2.2.0. on flutter 2.0 all things worked fine..

**Comment by mattbreeland** [comment]
Hmm now I can reproduce the error simply by importing "flutter_bacebook_auth.dart" and relaunching the app:

> //import 'package:flutter_facebook_auth/flutter_facebook_auth.dart';

This changes pubspec.lock in the following way:

>   flutter_facebook_auth:
>     dependency: "direct main"
>     description:
>       name: flutter_facebook_auth
>       url: "https://pub.dartlang.org"
>     source: hosted
>     version: "3.4.1"
>   flutter_facebook_auth_platform_interface:
>     dependency: transitive
>     description:
>       name: flutter_facebook_auth_platform_interface
>       url: "https://pub.dartlang.org"
>     source: hosted
>     version: "2.6.1"
>   flutter_facebook_auth_web:
>     dependency: transitive
>     description:
>       name: flutter_facebook_auth_web
>       url: "https://pub.dartlang.org"
>     source: hosted
>     version: "2.6.0+1"

And this is with:

> sdks:
>   dart: ">=2.13.0 <3.0.0"
>   flutter: ">=2.2.0"

**Comment by mattbreeland** [comment]
I think that my misconfigured flutter_facebook_auth plugin is the problem, and it is then blocking other plugins from loading correctly. So this might not be an issue with flutter_local_notifications after all!

**Comment by layndev** [comment]
I configure my Flutter Project as Packages. After that, I get that "... Plugin Exception". 
I try to downgrade to Flutter 2.0.x, and the Problem still there. now I am trying to change the grade Version on Android folder. On iOS, all worked fine.

**Comment by MaikuB** [comment]
@mattbreeland that would seen to be the case as per https://github.com/darwin-morocho/flutter-facebook-auth/issues/48

If you're running into issues like this, chances are there's another plugin cause a problem or a corrupt pub cache. If it's the former, you'd need to figure out which one and may need to file an issue with on its associated repo. I've seen reports with https://pub.dev/packages/flutter_facebook_login as well

**Comment by MaikuB** [comment]
Will close this then :)
