### ISSUE TITLE
Notifications message is null when notification uses title_loc_key, body_loc_key in foreground

### ISSUE THREAD

**Issue by Inassdev** [MaikuB/flutter_local_notifications#1195]
This is a bug on Android.

I have an issue when trying to internationalize my notifications messages using the body_loc_key parameter

When the app is in foreground the notification message property is null. In background the notification will display properly and show the value of the resources string.

**Comment by MaikuB** [comment]
Your issue is being logged on the wrong repo as those parameters you mention don't have anything to do with this plugin. They're to do with Firebase Cloud Messaging, which is for remote notifications. This plugin is for local notifications
