### ISSUE TITLE
How To Check Notification id Already Used?

### ISSUE THREAD

**Issue by tonmooy** [MaikuB/flutter_local_notifications#1198]
How To Check Notification id Already Used?

I want to check Notification id exist or not , if not exist , app will  to set a new notification  .

**Comment by rocboronat** [comment]
To do that I think you could just use always the same notification id. So, it will update the notification in case it exists, or create a new one if it doesn't.

**Comment by MaikuB** [comment]
There's no way to do so. Closest thing is to get a list of pending notifications. IDs would've been generated by your app so if you need to track what's been used then you would need to implement that yourself
