### ISSUE TITLE
What does ContentUriAndroidIcon expect?

### ISSUE THREAD

**Issue by rocboronat** [MaikuB/flutter_local_notifications#1200]
According to the documentation, the `ContentUriAndroidIcon` constructor expects `A content URI that refers to the location of the icon`. But should `ContentUriAndroidIcon('https://example.com/image.png')` work?

It smells like it should, but it shows nothing

![image](https://user-images.githubusercontent.com/456499/122532869-3e245a00-d021-11eb-9463-f32ff400354d.png)

By the way, thanks for the plugin, @MaikuB, and contributors! 😄

**Comment by MaikuB** [comment]
No, it won't work. These content URIs are specific to Android. See https://developer.android.com/reference/android/content/ContentUris and https://developer.android.com/guide/topics/providers/content-provider-basics#ContentURIs. You can only use local resources for icons
