### ISSUE TITLE
onNotificationFired callback

### ISSUE THREAD

**Issue by fahidsarker-CC** [MaikuB/flutter_local_notifications#1201]
is there any plan to introduce onNotificationFired callback or something like that for zonedScheduled notification? So that we can do some async work in the background when a notification is fired (like scheduling another notification for some other time).

**Comment by Shashwat2708** [comment]
Yes. Really need that. If making an alarm app, can be really helpful. If such a feature already exists, then please let us know. I want to schedule a notification for a time that is picked by the user from a timepicker but I have no idea of how to do it. Please help

**Comment by MaikuB** [comment]
No plans to at the moment but community contributions are welcome. Even then, it doesn't sound like it would support your case as iOS only supports getting callbacks about when a notification about to shown when the app is in the foreground. It wouldn't work when the app is in the background or not running

**Comment by fahidsarker-CC** [comment]
I see
