### ISSUE TITLE
[feature] Android 12 - Exact alarm permission

### ISSUE THREAD

**Issue by wcoder** [MaikuB/flutter_local_notifications#1202]
Android doc: https://developer.android.com/about/versions/12/behavior-changes-12?hl=cs#exact-alarm-permission

```kt
// Open settings
if (!alarmManager.canScheduleExactAlarms()) {
	startActivityForResult(
		Intent(Settings.ACTION_REQUEST_SCHEDULE_EXACT_ALARM, "package:<package_id>")
	)
}
```

![alarms-and-reminders](https://user-images.githubusercontent.com/766193/122674370-838d8680-d1dd-11eb-8bf9-93e41be5d967.png)

**Comment by MaikuB** [comment]
Although this plugin makes use of exact alarms, that is a much more generic concept and with regards to separate responsibilities of various services/plugins, the requested feature belongs more to plugin that deals with permissions. As such, I'm not looking to implement this. I would suggest you make a feature request to one such as https://pub.dev/packages/permission_handler
