### ISSUE TITLE
[ask] Flutter SDK Version

### ISSUE THREAD

**Issue by lucasribolli** [MaikuB/flutter_local_notifications#1204]
I would like to know the version of Flutter SDK used in example app of the 3.0.2 version released.
Thanks!

**Comment by MaikuB** [comment]
Flutter apps in general are not tied to specific versions of a Flutter SDK and neither is the example app so this isn't something that can be provided. If you're trying to look at what version you can install to run the app, you would need to look at the Dart and Flutter SDK constraints to figure it out. This isn't something I can provide
