### ISSUE TITLE
Can I show big picture image from network? Is that possible?

### ISSUE THREAD

**Issue by shivam-cashify** [MaikuB/flutter_local_notifications#1207]
While sending push we add banner image there and for that we need to show BigTextStyleInformation.
Is it possible?

**Comment by rocboronat** [comment]
Yes, but you have to download it by yourself and then show the notification with the previously downloaded image.

**Comment by shivam-cashify** [comment]
download in which format, as we use :
`FadeInImage.assetNetwork(
    placeholder: placeholder,
    image: url ?? "",
    fit: fit,
  );`

to download and show the image at runtime.
Or download the image in .png format etc.

**Comment by shivam-cashify** [comment]
Solved.

**Comment by kateile** [comment]
> Solved.

How you did it? I need the same thing
