### ISSUE TITLE
CATEGORY_MESSAGE notifications show a Google Maps action

### ISSUE THREAD

**Issue by rocboronat** [MaikuB/flutter_local_notifications#1210]
**Describe the bug**
When showing a group message notification, it also shows an action that opens Google Maps.

<img src="https://user-images.githubusercontent.com/456499/123592894-26ea2700-d7ee-11eb-8479-9231b7bc2dd7.jpg" width=400/>

**To Reproduce**
Launch a notification with `category: "msg"` and a `styleInformation` like
```dart
styleInformation: MessagingStyleInformation(
  chatFakePerson,
  conversationTitle: roomName,
  groupConversation: true,
  messages: messages,
),
```

**Expected behavior**
It doesn't show any action.

**Sample code to reproduce the problem**
```dart
AndroidNotificationDetails androidDetails = AndroidNotificationDetails(
      'mentions',
      'Mentions',
      '',
      importance: Importance.high,
      priority: Priority.high,
      showWhen: true,
      subText: 'English room',
      groupKey: 'englishroom',
      category: 'msg',
      styleInformation: MessagingStyleInformation(
        person,
        conversationTitle: 'English room',
        groupConversation: true,
        messages: messages,
      ),
    );

    NotificationDetails platformChannelSpecifics = NotificationDetails(android: androidDetails);

    await localNotificationsPlugin!.show(
      42,
      author,
      text,
      platformChannelSpecifics,
      payload: payloadJson),
    );
```

**Comment by MaikuB** [comment]
This isn't an issue with the plugin. It doesn't do anything to specify that actions should be shown. You may need to familiarise yourself with Android more as some implementations of the Android OS itself may suggest actions or replies on their own e.g. https://www.samsung.com/us/support/answer/ANS00062618/
