### ISSUE TITLE
Specific Date Time notification is not working

### ISSUE THREAD

**Issue by imdarpn** [MaikuB/flutter_local_notifications#1215]
**Describe the bug**
 I want to set a local notification on specific date & time, but its not getting date it's only getting time, and everyday same time its throws notification 

**Sample code to reproduce the problem**
 
Future<void> _scheduleDailyZone5Notification() async {
    await flutterLocalNotificationsPlugin.zonedSchedule(
        5,
        'zone 5',
        (notificationMessage..shuffle()).first,
        _nextInstanceOfZone5(),
        const NotificationDetails(
          android: AndroidNotificationDetails(
              'daily notification channel id',
              'daily notification channel name',
              'daily notification description'),
        ),
        androidAllowWhileIdle: true,
        uiLocalNotificationDateInterpretation:
            UILocalNotificationDateInterpretation.absoluteTime,
        matchDateTimeComponents: DateTimeComponents.time);
  }

  
  
  **

tz.TZDateTime _nextInstanceOfZone5() {
    final tz.TZDateTime now = tz.TZDateTime(tz.local, now(tz.local);
    tz.TZDateTime scheduledDate =
        tz.TZDateTime(tz.local, now.year, 7,1,13,30);
    print("=====================5th====================$scheduledDate");
    return scheduledDate;
  }

**

**Comment by Shashwat2708** [comment]
What is now(tz.local)?

**Comment by imdarpn** [comment]
@Shashwat2708 its local device timezone

**Comment by MaikuB** [comment]
@imdarpn the behaviour you've described is to be expected as by specifying `matchDateTimeComponents: DateTimeComponents.time` you've requested to have a daily notification. If you look at the readme and example app, having a notification shown on a specific date and time is done by omitting that parameter
