### ISSUE TITLE
Scheduled notifications not working in iOS

### ISSUE THREAD

**Issue by RomanSoviak** [MaikuB/flutter_local_notifications#1216]
Hi there! Thanks for nice lib.
Library doesn't reflect scheduled notifications on my iphone 6s. On the other hand Android works correct.

To reproduce bug:
If you manually change the date on your iOS device, notifications will only be received if the difference between the date you switched and the current date does not exceed 1 day.

Code:

`final currentTimeZone = await FlutterNativeTimezone.getLocalTimezone();` 
` await _flutterLocalNotificationsPlugin.zonedSchedule(` 
  ` weekDay,` 
  ` notification.title,` 
  ` notification.body,` 
  ` tz.TZDateTime.from(date, tz.getLocation(currentTimeZone)),` 
  ` _platformSpecifics,` 
 `  androidAllowWhileIdle: true,` 
`   uiLocalNotificationDateInterpretation:` 
      ` UILocalNotificationDateInterpretation.absoluteTime,` 
` );` 
For example: I schedule notification on 02.07.2021, after that change date to 10.07.2021 but nothing happens. When I schedule for today and change time it works.
I will appreciate your help. Thanks!

**Comment by MaikuB** [comment]
There's no further that can be done with the plugin on this as it calls the appropriate APIs when it comes to scheduling. What you're seeing would therefore be just how it works. That Android works the way you expect when you manually change the time doesn't necessarily mean iOS would behave the same way. If you were to follow a tutorial on how to schedule notifications on iOS to test it out, you should see the same behaviour again.
