### ISSUE TITLE
the icon is not displayed in the background with firebase_messaging

### ISSUE THREAD

**Issue by adeyanovalexey** [MaikuB/flutter_local_notifications#1218]
`static NotificationDetails getPlatformChannelSpecifics(){
    var androidPlatformChannelSpecifics =
    AndroidNotificationDetails('repeatDailyAtTime channel id',
        'repeatDailyAtTime channel name', 'repeatDailyAtTime description', styleInformation: BigTextStyleInformation('', htmlFormatBigText: true));
    var iOSPlatformChannelSpecifics = IOSNotificationDetails();
    var macOSNotificationDetails = MacOSNotificationDetails();

    var platformChannelSpecifics = NotificationDetails(
        android: androidPlatformChannelSpecifics, iOS: iOSPlatformChannelSpecifics, macOS: macOSNotificationDetails);
    return platformChannelSpecifics;
  }`

`FirebaseMessaging.onMessage.listen((RemoteMessage event) {
      flutterLocalNotificationsPlugin.show(24, event.notification.title, event.notification.body, 
      LocalNotification.getPlatformChannelSpecifics());
    });
    FirebaseMessaging.onMessageOpenedApp.listen((message) {
      print('==============Message clicked!');
    });`

I take the standard icon without the android background:icon= "@mipmap/ic_launcher".  it shows up well when using local notifications. but when I catch the firebase_messaging notification in the background. it doesn't pick up the icon. since the application is closed. In what format should I add it to AndroidNotificationDetails (icon: ). Will it also be substituted in size as a standard one.

**Comment by quocviet1996** [comment]
I have the sam issue too, display icon when app in foreground but not in backgrond , but everything was fine before

**Comment by adeyanovalexey** [comment]
I solved the problem. Added to AndroidManifest.xml
`<meta-data
            android:name="com.google.firebase.messaging.default_notification_icon"
            android:resource="@drawable/ic_stat_icon3" />

        <meta-data
            android:name="com.google.firebase.messaging.default_notification_color"
            android:resource="@android:color/holo_purple" />`

Subscribed to a subscription
`FirebaseMessaging messaging = FirebaseMessaging.instance;
await messaging.subscribeToTopic('en');`
