### ISSUE TITLE
Android "Pop on Screen" permission turned off by default

### ISSUE THREAD

**Issue by 4bSolutionsLLP** [MaikuB/flutter_local_notifications#1221]
When installing Android app that uses notifications, the permission for "Pop on Screen" is turned off by default. How can I programatically request this permission/turn it on?

Many thanks.

**Comment by MaikuB** [comment]
I don't know what permission you're referring to here. Can you point out which one you're referring to from the official docs? The plugin doesn't make use of APIs that require permissions to requested at runtime and only needs them in the manifest file and does so as part of the plugin's own manifest file

**Comment by 4bSolutionsLLP** [comment]
![Screenshot_20210703-131751_Settings](https://user-images.githubusercontent.com/67598738/124353899-30fe9200-dc01-11eb-8663-80cf17fa0c55.jpg)
Hi
Many thanks for your response.  I would like the "Show as pop-up" (see screen shot) to default to "on" when app is first installed and was wondering what needs to be set in the Manifest or within code to achieve this. Many thanks.

**Comment by MaikuB** [comment]
If you look at the link I sent earlier that has the list of all Android permissions then you can see that is no such permission. This is either a custom setting from Samsung or is meant to be what they refer to as a [heads-up notification](https://developer.android.com/guide/topics/ui/notifiers/notifications.html#Heads-up). I suggest you read the docs on the latter and see if changing the appropriate notification (channel) settings

**Comment by 4bSolutionsLLP** [comment]
Thanks. Looks like the "Importance.max" parameter is what is needed to show "Heads-up" notifications - which Samsung seem to refer to as "pop-up".
