### ISSUE TITLE
Compatibility with external storage installation on Android

### ISSUE THREAD

**Issue by innovation-elab** [MaikuB/flutter_local_notifications#1222]
Hi,
Is the plugin compatible with an installation on an external storage on Android?
It seems to me it is not as it uses the AlarmManager API, I just wanted to make sure there wasn't any workaround for this.

[Android install location](https://developer.android.com/guide/topics/data/install-location.html)

**Comment by MaikuB** [comment]
You'd run into the same issue described in the docs you linked if you're making use of scheduled notifications. There's no workaround for this as the AlarmManager API is the only one available on Android that allows for scheduling work to occur at an exact time even if the app is in low-power mode
