### ISSUE TITLE
No custom sound on build release

### ISSUE THREAD

**Issue by shpy2001** [MaikuB/flutter_local_notifications#1223]
**Describe the bug**
At same device. Flutter_local_notification 6.0.0

- In debug, every things ok. Sound from flutter_local_notification or form Firebase FCM play exactly sound.mp3 file.

- In release mode. They only play default sound from system. I opened apk file, in res/raw/ there is sound.mp3 with 0 byte size (in debug apk, it have exactly size)
- After research , i found that add keep.xml file in res/raw with content 

`<?xml version="1.0" encoding="utf-8"?>
<resources xmlns:tools="http://schemas.android.com/tools"
    tools:keep="@drawable/*,@raw/sound"
    />`

and then, there is sound.mp3 with exactly size in apk. 

But, sound from flutter_local_notification or from FCM is not sound.mp3 , they play ring_original.wav. I do not add this file. I dont know where it come from. Under android/res/raw dose not have this file, but check in apk file at res/raw , it's there.

For more test, i added an a_sound.mp3 with idea about sort order !! With edit keep.xml
And from flutter_local_notification or from FCM , i call a_sound . But , it do not play a_sound, just play default system sound.

- I had step by step with this link [https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#release-build-configuration](url) . Included proguard.

**Comment by MaikuB** [comment]
Could you include a link to a repository with a minimal app that can reproduce the problem and only uses this plugin?

**Comment by shpy2001** [comment]
@MaikuB 
Thank you. I found where this issue happen and know to fix.

Step by step
- The ring_original.wav come from another native sdk (Zoom sdk).
- When set up custom sound for notification but not include keep.xml, my sound.mp3 still there in the release apk but size = 0 byte. And then, app will play default sound. 
- However, the notification channel had been created and asign to sound.mp3 - but no file to play (so play default).
- Rebuild release with keep.xml and UPDATE on device. Now, sound.mp3 have size. But, app will not play sound.mp3 or default sound, it play original.wav - the only another sound file in res/raw . I dont know why that.
- So, if fresh install or change to difference channel id when update, app will play sound.mp3 .
