### ISSUE TITLE
Android foreground service

### ISSUE THREAD

**Issue by EPNW** [MaikuB/flutter_local_notifications#1225]
This feature was already discussed in #1193 and rejected, but I want to start discussion again with some additional thoughts.

So first of all a small introduction:
If a flutter app starts an Android foreground service, the system will treat the app as "in-foreground", even if it is minimized.
This is useful in flutter for a bunch of different use cases.
There are already serveral packages on pub that allow you to create an Android foreground service.
Since an Android foreground service always needs an Android notification, most of the plugins come with an own (but limited) notification system.

This leads to the following problem:
You don't want to have two API's for notifications: one for the foreground service and one for `flutter_local_notifications`.

Now I thought of two solutions to this problem which I'd like to present and discuss here.
They all aim to use the API already in place with this plugin.

### Approach 1: Create a new plugin that depends on `flutter_local_notifications`
I could create a plugin that provides a method for starting an Android foreground service and takes an [`AndroidNotificationDetails`](https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/AndroidNotificationDetails-class.html) as parameter.
Since this plugin would depend on `flutter_local_notifications` I can import the java classes from there and then use its own notification serialization mechanics.
Concrete, this means using [`NotificationDetails.from`](https://github.com/MaikuB/flutter_local_notifications/blob/fc42fc99547d757086b66f8064e9ab25e3928880/flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/models/NotificationDetails.java#L187) to obtain a `NotificationDetail` object.
While the function that creates the actual `Notification` form these details is luckily already `static`, it is unfortunately also `private`:
https://github.com/MaikuB/flutter_local_notifications/blob/fc42fc99547d757086b66f8064e9ab25e3928880/flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java#L163
The same goes for the dart side of serialization, `AndroidNotificationDetailsMapper` is from [`lib/src/platform_specifics/android/method_channel_mappers.dart`](https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/lib/src/platform_specifics/android/method_channel_mappers.dart), what is not exported from the plugin. This is not as bad as the `private` in java, since (while discouraged) in dart we can import private files of a package, if we are ok with breaking dart conventions.

After giving this quick summary of approach 1, lets discuss it:
Pros:
* Clear separation of concerns: An Android foreground service inherently depends on notifications and can not exist wihtout a notification, but notifications can exist without a foreground service. So it seems natural to create a seperate plugin that *depends* on `flutter_local_notifications`.

Neutral:
* Small API change required: Change `private` of `createNotification` to `public`.

Cons:
* Breaking dart conventions: This separate plugin would need to import a not-exported file to gain access to the dart-side serialization methods.
* **VERSION LOCK**: This is imo the biggest problem. Such a plugin would not only depend on `flutter_local_notifications`, but it would need to depend on one specific version. Dart's versioning system is build in such a way that on breaking API changes, the major version of a package should increase. Dependend packages will notice that there is a change in major version and in most cases (if `^` was used in pubspec.yaml) not use the package and inform the developer to take action. This all makes totally sense BUT is only true for the *public* API of a package. The dependend packages won't notice if the *internal* API changes (as the major version would typically not be increased). And in our specific use case, we not only depend on a not-exported dart file, the whole java side is not considered public API, too. 

A "simple" but effective workaround for the last cons would be to agree that some specific java files and the serialization dart file are per definition part of the public API.

Side note: I've already created an Android foreground service plugin that depends on an other notification system once before (you can see the results [here](https://pub.dev/documentation/android_foreground_service_with_awesome_notifications/latest/android_foreground_service_with_awesome_notifications/AFSWAN/startForeground.html)). But for our current app we will use `flutter_local_notifications`, so we need the functionallity compatible with this plugins API.

### Approach 2: Integrate the functionallity into this plugin
We could intergrate the Android foreground services directly into `flutter_local_notifications`. This could be done in many ways, here are two I came up with:
#### 2.1: Introduce a new library
A package can contain multiple libraries, so an `android_foreground_service` library could be added. This library could contain a class with two methods, one to start and one to stop the service. The start method would take an [`AndroidNotificationDetails`](https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/AndroidNotificationDetails-class.html) as parameter. Both these methods would use the already existing method channel and on the java side, a foreground service would be spawned. On non Android platforms, these methods would be no-ops.
Pros:
* API stability: Since there is only one package, API stability is guaranteed.
* A bit separation of concerns: Puting this in a new library somewhat separates it from the core functionallity of this package (what is notifications, not Android services).

Cons:
* Bloating: Such a new library could be perceived as "bloating", since the added functionallity only targets one platform and is only indirectly related to notifications. One could argue that integrating a *dependend* functionallity into the main package feels unnatural (as opposed to the `Clear separation of concerns` argument above).

#### 2.2: Add a flag to [`AndroidNotificationDetails`](https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/AndroidNotificationDetails-class.html)
Adding a simple flag like `bool useForegroundService` to the Android specific class clould do the trick.
Pros:
* API stability: see above.

Neutral:
* Missable: Such a "tiny" flag could be easily missed by a developer. On the other hand, someone looking for this functionallity will find it, so this is only neutral, not a cons.
* Strange feeling: Adding a flag to enable a functionallity to something that is meant to be a 1:1 map may feel strange (every property of `AndroidNotificationDetails` has an equivalent in Android's `NotificationCompat.Builder`, but the new flag wouldn't). Since this is only a *feeling* it's not really a cons.

Cons:
* Still a bit bloating: While there is no new library, one could still argue that integrating a *dependend* functionallity into the main package feels unnatural.

So this was a lot of text, but I hope you read it and look forward to your thoughts 😄.

**Comment by MaikuB** [comment]
Thanks for the proposal. Some good ideas here and the library one is pretty clever. I'm going to propose another one where the API is added to https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/AndroidFlutterLocalNotificationsPlugin-class.html. This avoids adding another library, having to make sure things are no-op for other platforms and keep it as Android-specific functionality. There is in fact already some Android-specific APIs around notification channel management. The federated plugin spec also talks about keeping platform-specific functionality in platform-specific implementations being more natural and avoids having a bloated monolithic cross-platform facing API.

How does that sound?

**Comment by EPNW** [comment]
Yes, I think you are right and it would make most sense to place it into the Android specific platform implementation.
I will start working on this as soon as I have time, but I think it will take at least 2 weeks until a PR is ready...

**Comment by asterisk37n** [comment]
After implementing a local notification, I found what I needed is a foreground service notification! Looking forward to read updates!

**Comment by yshahak** [comment]
This will be a great addition!

**Comment by MaikuB** [comment]
This is now in the 8.1.0 release. Thanks @EPNW for the PR!
