### ISSUE TITLE
java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by alex9153** [MaikuB/flutter_local_notifications#1226]
com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification

Fatal Exception: java.lang.RuntimeException
Unable to start receiver com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver: java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(channel=voice channel id shortcut=null contentView=null vibrate=null sound=null defaults=0x0 flags=0x10 color=0x00000000 vis=PRIVATE semFlags=0x0 semPriority=0 semMissedCount=0)
android.app.ActivityThread.handleReceiver

**Comment by MaikuB** [comment]
The error is in the exception "Invalid notification (no valid small icon)". You have an issue with how you've configured or specified the icon. This is something you'd need to fix within your app.
