### ISSUE TITLE
MissingPluginException (MissingPluginException(No implementation found for method initialize on channel dexterous.com/flutter/local_notifications))

### ISSUE THREAD

**Issue by mohammadhassan1497** [MaikuB/flutter_local_notifications#1229]
I show notification in the background and I use background_services package for running code in background for android notification work perfectly but for iOS not work, show this error **MissingPluginException (MissingPluginException(No implementation found for method initialize on channel dexterous.com/flutter/local_notifications))**

This is my code https://github.com/mohammadhassan1497/flutter_notification_background

**Comment by Nyancat92** [comment]
Same issue for me, does anyone have a solution for this problem?

**Comment by Nyancat92** [comment]
I´m using flutter workmanager by the way

**Comment by MaikuB** [comment]
This would be an issue with the plugins you're using, which may require more setup required within your app that they can call other plugins. You'd need to see if they have instructions for them and if they even support this scenario

**Comment by varunkamanibosc** [comment]
@Nyancat92 @mohammadhassan1497 Did you find any solution?
