### ISSUE TITLE
Improve explanation on using custom sounds.

### ISSUE THREAD

**Issue by Scott-Tenera** [MaikuB/flutter_local_notifications#1231]
The portions of the getting started guide that relate to custom sounds, do not actually explicitly and clearly explain how to use custom sounds.

It specifies the following rather incomplete information...
`
For Android 8.0+, sounds and vibrations are associated with notification channels and can only be configured when they are first created. Showing/scheduling a notification will create a channel with the specified id if it doesn't exist already. If another notification specifies the same channel id but tries to specify another sound or vibration pattern then nothing occurs.`

and then links to this.

https://developer.apple.com/documentation/usernotifications/unnotificationsound?language=objc

It would be better if it was 

Setting up custom sounds on android:
1...
2...
3...
etc

Setting up custom sounds on iOS

1...
2...
3...
etc

**Comment by MaikuB** [comment]
There's also a link to https://developer.android.com/guide/topics/resources/providing-resources

Noted your feedback. There aren't steps as this relies on knowing about how each platform works given the plugin is still a wrapper for native APIs. IDEs will change and steps can change that will be difficult to stay on top of. Android, for example, could support higher res assets in the future. This is why I've tried to link to the official documentation that I could find. These details and showing screenshots would make the readme a lot bigger than it really needs to be more of a website, which can be time-consuming to maintain, especially if others in the community aren't willing to help out too.

**Comment by MaikuB** [comment]
Closed as no one seems to be willing to help out. Developers will need to continue making sure they understand the native platforms, something which I would say they should being doing to begin with as the plugin's main purpose is to provide a Dart interface to native APIs. Not to say that having instructions won't aid others but even that can be subject to change if the platform changes how things should work
