### ISSUE TITLE
Notifications Click not working while in app

### ISSUE THREAD

**Issue by MojtabaTavakkoli** [MaikuB/flutter_local_notifications#1233]
Hello
I've set the package pre requirements and it's working fine when the app is closed. I mean when trying to open a certain route of the app with notification its fine WHILE the app is closed. But when I'm in app and get the notification and click on it nothing happens and I get the log below:
```
D/ViewRootImpl@eca7c5c[MainActivity](27076): stopped(false) old=false
I/flutter (27076): notification payload: {"examIndex":8,"quizName":"freeQuiz8","categoryIndex":100,"routeFetch":"free","totalExams":24,"categoryName":"رایگان"}
D/ViewRootImpl@eca7c5c[MainActivity](27076): Relayout returned: old=(0,0,720,1560) new=(0,0,720,1560) req=(720,1560)0 dur=12 res=0x1 s={true 513498505216} ch=false
D/ViewRootImpl@eca7c5c[MainActivity](27076): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager(27076): prepareNavigationBarInfo() DecorView@17ebd30[MainActivity]
D/InputMethodManager(27076): getNavigationBarColor() -855310
```

I've been using this from the versions below `5` but now that I'm using version `6` its not.
Thank you

**Comment by MaikuB** [comment]
If this issue exists then it should be reproducible within the example app as well. However, there aren't any known issues on this so I would suggest you debug your app to figure out the issue.

**Comment by MaikuB** [comment]
Closing as there aren't any known issues with this. If you are moving to new versions, you should also check the changelog. One of the changes that may affect your scenario is 4.0 made some changes to the `initialize` method that may have uncovered how you may not have handled the dealing with the callback. See the changelog for more details and  you can also refer to the example  app

**Comment by MojtabaTavakkoli** [comment]
I found this **Note**  in the seam of your coat (docs 😅) referring to my issue.

> Note: from version 4.0 of the plugin, calling initialize will not trigger the onSelectNotification callback when the application was started by tapping on a notification to trigger. Use the getNotificationAppLaunchDetails method that is available in the plugin if you need to handle a notification triggering the launch for an app e.g. change the home route of the app for deep-linking.

So i copied some from the example and BOOM🧨
