### ISSUE TITLE
Does not find icon assets in res folder.

### ISSUE THREAD

**Issue by safield** [MaikuB/flutter_local_notifications#1234]
I have initialised witth the following settings... 

`var initializationSettingsAndroid = AndroidInitializationSettings('ic_launcher');`

I have an instance of ic_launcher.png in...

app/src/main/res/mipmap-hdpi/ic_launcher.png
app/src/main/res/mipmap-mdpi/ic_launcher.png
app/src/main/res/mipmap-xhdpi/ic_launcher.png
app/src/main/res/mipmap-xxhdpi/ic_launcher.png

It finds none of these assets, even though they exist.

PS. The comment and docs about the defaultIcon REALLY need to be improved. Is this string supposed to be a file path? A relative path?

**Comment by zigapovhe** [comment]
@safield If you have your icon saved in res/mipmap folder, you should use "@mipmap/ic_launcher" as relative path for local notifications, but it is recommended that notification icons are saved in drawable folder. Icons saved in drawable folder should display correctly in notifications when specifying "ic_laucncher" as your path.

**Comment by MaikuB** [comment]
@zigapovhe has answered this and the info mentioned was available from the readme, which mentions in a few place that this ideally refer to a drawable resource and what to do if you insist on using the launcher icon. If you haven't picked that up then I suspect have you missed [this link](https://developer.android.com/guide/topics/resources/providing-resources) to information about Android's resource system and that there's a link to the [example](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications/example) app that can be used to a reference.
