### ISSUE TITLE
flutter_local_notifications_platform_interface upgrade causing problem at build time

### ISSUE THREAD

**Issue by Silfalion** [MaikuB/flutter_local_notifications#1243]
**Describe the bug**
after the latest update of the platform plugin this error is returned:
```
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-6.0.0/lib/src/platform_flutter_local_notifications.dart:261:5: Error:
'validateId' is imported from both 'package:flutter_local_notifications_platform_interface/src/helpers.dart' and 'package:flutter_local_notifications/src/helpers.dart'.
    validateId(id);
```

**To Reproduce**
1. Upgrade the plugin so that flutter_local_notifications_platform_interface
2. notice the error message being returned

**Expected behavior**
building app working

**Sample code to reproduce the problem**
the bug is not related to a particular piece of code as it happens at build time

**Comment by engeslamsaad** [comment]
same issue

**Comment by MaikuB** [comment]
@Silfalion sorry looks like you were too quick, about to release new version of plugin that should fix this soon

**Comment by Silfalion** [comment]
temp workaround is to add this to pubspec.yaml:

`  flutter_local_notifications_platform_interface: "<=4.0.0"`

**Comment by Silfalion** [comment]
> @Silfalion sorry looks like you were too quick, about to release new version of plugin that should fix this soon

oh thank you!

**Comment by MaikuB** [comment]
Sorry i didn't realise the issue this would cause before, I think I'll look into do a revert of the changes to the platform interface and get that too

**Comment by MaikuB** [comment]
6.1.0 should be released and fix this issue. Let me know how it goes

**Comment by rkl555** [comment]
When is 6.1.0 expected to be released

**Comment by Silfalion** [comment]
Thank you so much for the very quick fix, it's working great now :ok_hand:

**Comment by Silfalion** [comment]
> When is 6.1.0 expected to be released
it's shown as waiting on pub.dev but its available

**Comment by lucaspal** [comment]
@MaikuB thanks for how fast you reacted 🍾

**Comment by MaikuB** [comment]
Thanks for the feedback, updates and your understanding everyone. I'll leave this open for a bit longer in case others run into this issue so they can see what the solution is
