### ISSUE TITLE
Updating a notification channel seems not possible

### ISSUE THREAD

**Issue by EPNW** [MaikuB/flutter_local_notifications#1246]
Using [`AndroidFlutterLocalNotificationsPlugin.createNotificationChannel`](https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/AndroidFlutterLocalNotificationsPlugin/createNotificationChannel.html) does not update the notification channel.

This suprised me since the behavior of the native Android methods `flutter_local_notifications` is calling is to simply update a channel if a channel with the same key already exists. 

Digging deeper shows that `AndroidNotificationChannelAction` can be used to explicitly update an already existing channel. But unfortunately the [`AndroidNotificationChannel`](https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/AndroidNotificationChannel-class.html) class, which is the parameter for the above mentioned `createNotificationChannel`, does not allow setting such an action, despite already serializing it correctly and passing it correctly to the java side, see this line:
https://github.com/MaikuB/flutter_local_notifications/blob/63e2f27d1d9fea218ebe5122cb3a05d93ee72d8f/flutter_local_notifications/lib/src/platform_specifics/android/method_channel_mappers.dart#L59

I would opt for making this action a parameter in the `AndroidNotificationChannel` class and not forcing it to `AndroidNotificationChannelAction.createIfNotExists` while serializing, so a developer has the control over what happens.

My current workaround is to delete all channels and recreate them.

**Comment by MaikuB** [comment]
What were you trying to change though. Not sure I've missed something from what you've explained but Android itself doesn't allow for changing the majority of the notification channel details once created beyond the name and description as explained in https://developer.android.com/training/notify-user/channels

**Comment by EPNW** [comment]
Oh yes, sorry I didn't mentinon that.

My app is listening for the devices current locale settings (in the "standard flutter way" with a localizations delegate) and localizes the channels name and description, so I need to update them.

**Comment by proninyaroslav** [comment]
@EPNW 
Any channel settings, including the name, can't be changed after they have been created.

**Comment by MaikuB** [comment]
This is likely an oversight from when there was a contribution that added supported for creating notification channels and refactored some existing logic. This could probably be fixed by not bothering with specifying the channel action and some tweaks to the logic on the Android side. However, I've already got a few PRs to review including one from you so not something I could look into soon. If you've got time to look into submitting a PR for this then would happily at this ahead of the foreground service one if needed
