### ISSUE TITLE
flutter_local_notifications 6.1.0 got error when running in flutter web.

### ISSUE THREAD

**Issue by phonghoang2k** [MaikuB/flutter_local_notifications#1247]
**Describe the bug**
When update plugin into version 6.1.0, this error is returned when running in flutter web (I have disabled the related flutter_local_notifications's code using !kIsWeb for only run in mobile device).
```
../../.pub-cache/hosted/pub.dartlang.org/ffi-1.1.2/lib/src/utf16.dart:5:8: Error: Not found: 'dart:ffi'
import 'dart:ffi';
       ^
../../.pub-cache/hosted/pub.dartlang.org/posix-2.1.2/lib/src/unistd/unistd.dart:209:15: Error: Type 'ffi.Int32' not found.
  ffi.Pointer<ffi.Int32> __pipedes,
              ^^^^^^^^^
../../.pub-cache/hosted/pub.dartlang.org/posix-2.1.2/lib/src/unistd/unistd.dart:209:3: Error: Type 'ffi.Pointer' not found.
  ffi.Pointer<ffi.Int32> __pipedes,
  ^^^^^^^^^^^
../../.pub-cache/hosted/pub.dartlang.org/posix-2.1.2/lib/src/unistd/unistd.dart:209:3: Error: Expected 0 type arguments.
  ffi.Pointer<ffi.Int32> __pipedes,
...
```
**To Reproduce**

1. Upgrade the plugin to latest version 6.1.0.
2. Runs app on Flutter web, you will see error return.

**Expected behavior**
the app runs successfully and not encountered error.

**Sample code to reproduce the problem**
The bug only happens at the build time and not related to any particular piece of code. 
Checking the log, maybe there's somethings wrong when using the posix-2.1.2 lib because when i downgraded the plugin to version 5.0.0+4, everything run perfectly with no error.

**Comment by raviganwal** [comment]
Yes I just update to` flutter_local_notifications: ^7.0.0-dev.3 ` and I am facing same error. while my app was working fine with `^6.0.0`.

**Comment by nori-flutter** [comment]
I got the same error. Everything was okay with version 6.0.0 for web build.

**Comment by MaikuB** [comment]
Thanks for the info. Yes it looks like adding Linux support has caused an issue with this.

cc @proninyaroslav so you're across this. I suspect this is to do `posix` being used in the Linux and it is dependent on a very old version of the `ffi` library than what is currently being pulled as a transitive dependency by regular apps. Until `posix` is updated or there's another solution, I think it's better to leave out Linux support for now

**Comment by proninyaroslav** [comment]
@MaikuB 
As the option, I can add some native code (using Dart FFI or Flutter native code), I only use a couple of posix calls in the plugin. What do you say?

**Comment by MaikuB** [comment]
@proninyaroslav if you can then that would be great as it'd be a shame to revert so soon. Do you have a rough idea on when this would be up for review?

**Comment by proninyaroslav** [comment]
@MaikuB 
I will try to make it today.

**Comment by proninyaroslav** [comment]
Which do you think is preferable: Dart FFI or a small piece of native code in `flutter_local_notifixations_linux`? Will FFI problems arise again?

**Comment by MaikuB** [comment]
My understanding is Dart FFI is already baked into the Flutter SDK. A reference to it via pubspec.yaml shouldn't be needed so using FFI should be fine and shouldn't run into the same issues again.

**Comment by MaikuB** [comment]
@proninyaroslav i tried to see to if I could look at some solutions as well but if looks this will be more complicated that it would take more time to be resolved. Even if the ffi issue can get resolved, errors like this also occur

```
../../../../../flutter/.pub-cache/hosted/pub.dartlang.org/dbus-0.5.4/lib/src/dbus_value.dart:252:49: Error: The integer literal 9223372036854775807 can't be represented exactly in JavaScript.
Try changing the literal to something that can be represented in Javascript. In Javascript 9223372036854775808 is the nearest value that can be represented exactly.
    if (value < -9223372036854775808 || value > 9223372036854775807) {
```

I believe this would likely require dealing with conditional imports and creating stubs. Given the above error is from `dbus` that would take more effort to deal with as well. Unless you've got some other ideas, I'm going to look to revert the Linux support by removing references to it from the main plugin. This would help fix the issue for others and the Linux plugin would still stay in the repo to look into a solution.

**Comment by MaikuB** [comment]
Released 7.0.0 that removes referencing the Linux plugin that caused the issue

**Comment by proninyaroslav** [comment]
@MaikuB 
The problem with `dbus` is already familiar https://github.com/canonical/dbus.dart/issues/250. Older version 0.4.0 has no problem.

**Comment by proninyaroslav** [comment]
@MaikuB 
To be honest, I don't know how to solve this. `connectivity_plus` also uses` dbus`, but it doesn't have this problem. The only difference is that the `connectivity_plus` plugin is divided into several packages, and the web, macOS implementations are separated as well as Linux.

**Comment by proninyaroslav** [comment]
@MaikuB 
It seems they did it easier by making a stub for the plugin. I think this is the only correct solution https://github.com/fluttercommunity/plus_plugins/blob/main/packages/connectivity_plus/connectivity_plus_linux/lib/src/connectivity_stub.dart

**Comment by proninyaroslav** [comment]
```
// connectivity_plus_linux depends on dbus which uses FFI internally; export
// a stub for platforms that don't support FFI (e.g., web) to avoid having
// transitive dependencies break web compilation.
```
https://github.com/fluttercommunity/plus_plugins/blob/main/packages/connectivity_plus/connectivity_plus_linux/lib/connectivity_plus_linux.dart

**Comment by MaikuB** [comment]
It's late here now so I'm not going to look into further but I had tried something like that but it didn't work. Possible I missed something though as I had the stub in the main plugin instead of the Linux one and tried to do a conditional export for the stub.

If you manage to get working then happy to look at a PR. Looking at issues around inclusion of Linux support has taken a fair bit of time the past couple days so I'd like to pause on that to look at the other PRs that are open

**Comment by proninyaroslav** [comment]
@MaikuB 
I posted a PR anyway https://github.com/MaikuB/flutter_local_notifications/pull/1249. I hope the support will be returned. You tried to make a runtime stub, while FFI is a compile-time dependency and requires a compile-time stub using the Dart language feature. As it turns out, the Web doesn't support this (generally logical).
