### ISSUE TITLE
Time schedule events in Android

### ISSUE THREAD

**Issue by mbasa** [MaikuB/flutter_local_notifications#125]
For some reason, I can not get the time schedule functions working in Android ( flutterLocalNotificationsPlugin.schedule(), .periodicallyShow(), .showDailyAtTime(), .showWeeklyAtDayAndTime() ) . 

Everything works though in IOS. I am using the example program included in the project for the tests.

Am I missing a Permission or something? Thanks in Advance.

**Comment by mbasa** [comment]
Thanks for the quick reply. This is what I just did to test:

* download the zip file from the master branch
* edit example/pubspec.yaml and changed dependency to http:  (since I was getting errors with the ^0.12.0 version)
* ran flutter packages get
* ran flutter build apk --debug
* ran flutter install 

In the emulator with JellyBean, the Schedule functions still didn't display any notification.

**Comment by MaikuB** [comment]
can you include the output of `flutter doctor -v`

**Comment by mbasa** [comment]
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.13.6 17G3025, locale en-JP)
    • Flutter version 0.9.4 at /Users/mbasa/Development/flutter
    • Framework revision f37c235c32 (8 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/mbasa/Library/Android/sdk
    • Android NDK at /Users/mbasa/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 4.3.1 (API 18) (emulator)

• No issues found!

**Comment by MaikuB** [comment]
I cannot reproduce the problem you're seeing in the API 16 or API 18 emulator. Have you pulled down the notification tray to see if the notification appears there? If the issue still remains then you may have to debug to see what is going on. Also note that Flutter beta is on 0.11.3 now though I doubt upgrading your Flutter SDK will address the issue

**Comment by mbasa** [comment]
I have started using the 0.42 version and the example application as well as my own test application are working correctly. Thank you.
