### ISSUE TITLE
zonedSchedule does not work on real device.

### ISSUE THREAD

**Issue by spacekestrel** [MaikuB/flutter_local_notifications#1251]
When i try to implement zonesSchedule on emulator - it works, But on real device(samsung galaxy s21) it does nothing and system says that no notifications has been send.

Code:
```
Future<void> scheduleNotification(
    {@required int dayOfWeek,
    @required int hour,
    @required int minutes}) async {
  await flutterLocalNotificationsPlugin
      .zonedSchedule(
          dayOfWeek,
          'test app',
          'alarm clock',
          nextInstanceOfDayOfWeek(dayOfWeek, hour, minutes),
          NotificationDetails(
            android: AndroidNotificationDetails(
                dayOfWeek.toString(), 'test app', 'alarm clock',
                importance: Importance.max,
                priority: Priority.max,
                ticker: 'ticker'
                ),
          ),
          androidAllowWhileIdle: true,
          uiLocalNotificationDateInterpretation:
              UILocalNotificationDateInterpretation.wallClockTime,
          matchDateTimeComponents: DateTimeComponents.dayOfWeekAndTime)
      .whenComplete(() {
    print('Notification is settled!');
  });
}

tz.TZDateTime nextInstanceOfDayOfWeek(dayOfWeek, hour, minutes) {
  tz.TZDateTime scheduledDate = nextInstanceOfhours(hour, minutes);
  while (scheduledDate.weekday != dayOfWeek) {
    scheduledDate = scheduledDate.add(const Duration(days: 1));
  }
  return scheduledDate;
}

tz.TZDateTime nextInstanceOfhours(hour, minutes) {
  final tz.TZDateTime now = tz.TZDateTime.now(tz.local);
  tz.TZDateTime scheduledDate =
      tz.TZDateTime(tz.local, now.year, now.month, now.day, hour, minutes);
  if (scheduledDate.isBefore(now)) {
    scheduledDate = scheduledDate.add(const Duration(days: 1));
  }
  return scheduledDate;
}
```

Initialization is pretty standard:
```
final FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
    FlutterLocalNotificationsPlugin();
Future<void> initializeLocalNotification() async {
  final AndroidInitializationSettings initializationSettingsAndroid =
      AndroidInitializationSettings('@mipmap/ic_launcher');

  final MacOSInitializationSettings initializationSettingsMacOS =
      MacOSInitializationSettings();
  final InitializationSettings initializationSettings = InitializationSettings(
      android: initializationSettingsAndroid,
      macOS: initializationSettingsMacOS);
  await flutterLocalNotificationsPlugin.initialize(initializationSettings,
      onSelectNotification: selectNotification);
}

Future selectNotification(String payload) async {
  Get.toNamed('/test_screen');
}
```

**Comment by MaikuB** [comment]
From the snippet, you reference `tz.local` but this requires specifying the local timezone via the `timezone` package. Some sample code of this is in the example app but not mentioned in the initialisation above. Has that actually been done? You may also need to check to see if your phone has some battery optimisations that is preventing it from working. A number of OEMs are applying their own customisations to their implementation of Android that can get in the way

**Comment by spacekestrel** [comment]
> 
> 
> From the snippet, you reference `tz.local` but this requires specifying the local timezone via the `timezone` package. Some sample code of this is in the example app but not mentioned in the initialisation above. Has that actually been done? You may also need to check to see if your phone has some battery optimisations that is preventing it from working. A number of OEMs are applying their own customisations to their implementation of Android that can get in the way

Yes, I forgot to indicate the local location. However, even after I set the it, it did not fix the error. 
What is more strange, those functions work well without errors both on the emulator and on a real device:
```
Future<void> displayNotificationNow() async {
  const AndroidNotificationDetails androidPlatformChannelSpecifics =
      AndroidNotificationDetails(
          '1', 'your channel name', 'your channel description',
          importance: Importance.max, priority: Priority.high, showWhen: false);
  const NotificationDetails platformChannelSpecifics =
      NotificationDetails(android: androidPlatformChannelSpecifics);
  await flutterLocalNotificationsPlugin.show(
      0, 'plain title', 'plain body', platformChannelSpecifics,
      payload: 'item x');
}
```
```
Future<void> displayZonedNotification() async {
  await flutterLocalNotificationsPlugin.zonedSchedule(
      0,
      'scheduled title',
      'scheduled body',
      tz.TZDateTime.now(tz.local).add(const Duration(seconds: 5)),
      const NotificationDetails(
          android: AndroidNotificationDetails('your channel id',
              'your channel name', 'your channel description')),
      androidAllowWhileIdle: true,
      uiLocalNotificationDateInterpretation:
          UILocalNotificationDateInterpretation.absoluteTime);
}
```
So, i'm guessing is has to something with nextInstanceOfDayOfWeek() or nextInstanceOfHours() functions, but i can't put my finger on what exactly is the issue.

**Comment by MaikuB** [comment]
The only guidance i can give is that you'd need to debug further to figure it out. The API itself has been around for quite a while so any issues should've resulted in more reports. There are similar scenarios in the example app that I've tested and haven't seen any issues either.

One thing I've noticed in the original code is you use the day of the week as the notification id. Not sure if that is intentional but could mean you have notifications overriding each other

**Comment by spacekestrel** [comment]
Okay, so i've managed to solve this, and this is really weird. What needed to be done in order to fix this issue is to go to samsung settings - memory usage - excluded apps. There you can add an app, memory usage for whom wouldn't be checked and notifications would start to pop up.

**Comment by MaikuB** [comment]
This goes back to the point I covered earlier 

> You may also need to check to see if your phone has some battery optimisations that is preventing it from working. A number of OEMs are applying their own customisations to their implementation of Android that can get in the way

This was also mentioned in the section in the readme https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#scheduled-android-notifications

Will close this since the issue has been resolved but might be worth if you double check the readme in case you maybe missing other configuration like the release build one as that could cause a lot of issues later

**Comment by spacekestrel** [comment]
Yea, thanks a lot. It just so odd that sertain OEM's prevent you from creating simple alarm clock.
