### ISSUE TITLE
[URGENT] Release 6.1.1 to fix web build failure 

### ISSUE THREAD

**Issue by aliasgarlabs** [MaikuB/flutter_local_notifications#1254]
Most of the users of this plugin will have version `^6.0.0` configured in their `pubspec.yaml` file. Because of this, pub automatically upgrades this plugin to `6.1.0`, which made the web builds to fail. 

A bug fix was released in `7.0.0` but due to the `^6.0.0` configuration, most of the users will be stuck at `6.1.0` and will have to do a post-mortem to find out which plugin broke their builds just like how I did. 

To avoid them having to face this issue and make all web builds pass again without changes from their end, we can release a `6.1.1` patch update that fixes the web build issue. 

The patch can either conditionally import Linux-specific imports or revert Linux support based on a decision taken by the maintainer but I strongly believe `6.1.1` is necessary. 

Thanks for the awesome plugin btw!

**Comment by MaikuB** [comment]
Good point. Will do that soon

**Comment by MaikuB** [comment]
Done now. Thanks for the suggestion!
