### ISSUE TITLE
notification has one hour delay

### ISSUE THREAD

**Issue by mariamalbarghouti** [MaikuB/flutter_local_notifications#1257]
i need to schedule the notification at 10 AM, but the timezone is delayed with one hour.
so if i choose the hour to be 10 AM, the notification will be daily repeated at 9 AM.
**The code is:**
```
 tz.TZDateTime _nextInstanceOfTenAM() {
    final tz.TZDateTime now = tz.TZDateTime.now(tz.local);
    tz.TZDateTime scheduledDate =
        tz.TZDateTime(tz.local, now.year, now.month, now.day, 10);
    print(now.hour);
    if (scheduledDate.isBefore(now)) {
      scheduledDate = scheduledDate.add(const Duration(days: 1));
    }
    return scheduledDate;
  }

```

**Comment by mariamalbarghouti** [comment]
i have used  `DateTime.now();` to get the current time. 
it returned the time accurately, but it does not work!
so if i need to schedule a notification at 7 AM i have to type 6 AM! 
`this is the new way:`
 ```
tz.TZDateTime _nextInstanceOfTenAM({required int hour, required int minute}) {
    final DateTime now =DateTime.now();
    tz.TZDateTime scheduledDate =
        tz.TZDateTime(tz.local, now.year, now.month, now.day,7);
    print("tz.local: ${tz.local}");
    print("now.year ${now.year}");
    print("now.month ${now.month}");
    print("now.day ${now.day}");
    print("now.hour ${now.hour}");
    print("now.minute ${now.minute}");
    if (scheduledDate.isBefore(now)) {
      scheduledDate = scheduledDate.add(const Duration(days: 1));
    }
    return scheduledDate;
  } 
```

**Comment by MaikuB** [comment]
It isn't expected to work properly with regular DateTime objects as `zonedSchedule()` expects a `TZDateTime` object to be passed in to begin. Moreover, `TZDateTime` is not a class from this library so if you are having issues with it, this should be raised at https://github.com/srawlins/timezone.

Closing this as there's nothing to indicate that there's a problem with the `flutter_local_notifications` itself
