### ISSUE TITLE
Suggestion: add more vibration settings on AndroidNotificationDetails

### ISSUE THREAD

**Issue by spacekestrel** [MaikuB/flutter_local_notifications#1259]
Since there is no way to run code at the moment when notification starts, and you can't use vibration package where you can set a lot of settings such as:
```
Future basicCall() async =>
    await Vibration.vibrate(pattern: [500, 5000], repeat: 1, amplitude: 255,intensities: [1,255],duration: 10000);
```
i propose to add some extra functionality to vibration such as repeat, duration and amplitude.

**Comment by MaikuB** [comment]
Vibration APIs are outside the scope of this library as its purpose is to be able invoke a platform's native notification APIs. What is available there right now is what the Android notification APIs themselves support. If you need to combine calling multiple native APIs then that's an application-specific scenario you'd need to look at implementing yourself e.g. via a fork or write all the code natively

**Comment by spacekestrel** [comment]
@MaikuB  Yea, well...the thing is, that i can't even set that Int64List pattern properly, because it just plays vibration on notification without any pauses no matter what list was created.

**Comment by MaikuB** [comment]
Did you try running the example app to run the scenario for applying a custom vibration pattern to see if you run into the same issue?

Also note the following that is in the API docs

> For Android 8.0 or newer, this is tied to the specified channel and cannot be changed after the channel has been created for the first time.

This means that, as an example, if you used a notification channel to send a notification with default behaviour and then try to pass different values for the vibration settings to the same channel again, nothing will change

**Comment by spacekestrel** [comment]
@MaikuB Yes. Such implementation work:
```
   final Int64List vibrationPattern = Int64List(4);
    vibrationPattern[0] = 0;
    vibrationPattern[1] = 1000;
    vibrationPattern[2] = 5000;
    vibrationPattern[3] = 2000;
```
and such implementation  doesn't:
```
 final Int64List vibrationPattern = Int64List.fromList([0, 1000, 5000, 2000]);
```
Also, is there a way to update custom sound and vibration rather then cancel all notifications and set the again with updated  values?
