### ISSUE TITLE
uploaded date issue in local notification package

### ISSUE THREAD

**Issue by weddingstudio007** [MaikuB/flutter_local_notifications#1260]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Sample code to reproduce the problem**

**Comment by weddingstudio007** [comment]
upload date isuue

**Comment by MaikuB** [comment]
You've not filled in what was required for the bug report template. Please do so or this will be closed. Also note that a  notification itself doesn't have an upload date as notifications do upload anything

**Comment by MaikuB** [comment]
Closing to due to lack of information with no minimal app to reproduce the problem
