### ISSUE TITLE
Notification is Delayed on Android with Power Saving Mode ON

### ISSUE THREAD

**Issue by Jayvd** [MaikuB/flutter_local_notifications#1261]
On Android, the notification is delayed randomly when device is in the Low Power Mode or Power Saving Mode is ON.

1. **This is a one-off notification**, **NOT** a repeated notification.

2. I have set `androidAllowWhileIdle` to **true** but the notifications are still delayed..

3. It seems to happen now even after I turned off the low power mode. 

4. This only happen when there are multiple notifications scheduled

Any thoughts on this?

**Comment by MaikuB** [comment]
If you read some of the Android docs (e.g. https://developer.android.com/about/versions/pie/power#battery-saver), you can see that happens will vary per manufacturer. On my Pixel 4 XL, a one-off scheduled notification still appears when battery saver mode is on. This is outside of the control the plugin so there's nothing else it can do.
