### ISSUE TITLE
Is there is any way to toggle notification?

### ISSUE THREAD

**Issue by akashlilhare** [MaikuB/flutter_local_notifications#1270]
I have a boolean value, I want to toggle on/off notification on the basis of the value.

**Comment by Chinmay-KB** [comment]
If you have kept a record of the notification id you have used to send the notification, you can cancel the notification depending on the boolean value.
```dart
// cancel the notification with id value of zero
await flutterLocalNotificationsPlugin.cancel(0);
```

**Comment by MaikuB** [comment]
No there isn't. You would potentially need to write your own native code to do this
