### ISSUE TITLE
A 'canBypassDnd'  equivalent?

### ISSUE THREAD

**Issue by Andrious** [MaikuB/flutter_local_notifications#1279]
Again, great plugin.

I see it utilizes the Android's NotificationManager of course.

Would there be a 'canBypassDnd()' function in the future?

Is it possible to access Android's NotificationManager object now to access that function?

```
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
        NotificationManager manager = (NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE);
        NotificationChannel channel = manager.getNotificationChannel(CHANNEL_ID);
        channel.canBypassDnd();
    }
```

**Comment by MaikuB** [comment]
Please submit a PR if you are in need of this. I had also asked this from a related request https://github.com/MaikuB/flutter_local_notifications/issues/1211

**Comment by Andrious** [comment]
It would seem the app-end is really powerless to override the 'DND' setting on any particular phone. 

In the end, the phone has the final say regardless, and so I won't even bother implementing it.
