### ISSUE TITLE
How do I use HTML in the android notification?

### ISSUE THREAD

**Issue by cherryholme7** [MaikuB/flutter_local_notifications#128]
Hi,

I can't seem to get any HTML markup to render in the Android notifications. I've visited https://developer.android.com/guide/topics/resources/string-resource#StylingWithHTML and used their example markup, but the Android notifications render the HTML tags as strings.

Any idea?

Thanks!

**Comment by MaikuB** [comment]
If you look at the example app then there's code to demonstrate how it's done. Also refer to the API docs. More specifically https://pub.dartlang.org/documentation/flutter_local_notifications/latest/flutter_local_notifications/DefaultStyleInformation-class.html

**Comment by cherryholme7** [comment]
I see! Thank you!

Is it possible to add functional buttons with the HTML that I can listen to?

Or would that require a completely different feature?

**Comment by MaikuB** [comment]
it's not possible
