### ISSUE TITLE
Custom sounds doesn't play on release apk.

### ISSUE THREAD

**Issue by spacekestrel** [MaikuB/flutter_local_notifications#1283]
Steps to reproduse:
proguard rules
```
## Gson rules
# Gson uses generic type information stored in a class file when working with fields. Proguard
# removes such information by default, so configure it to keep all of it.
-keepattributes Signature

# For using GSON @Expose annotation
-keepattributes *Annotation*

# Gson specific classes
-dontwarn sun.misc.**
#-keep class com.google.gson.stream.** { *; }

# Prevent proguard from stripping interface information from TypeAdapter, TypeAdapterFactory,
# JsonSerializer, JsonDeserializer instances (so they can be used in @JsonAdapter)
-keep class * extends com.google.gson.TypeAdapter
-keep class * implements com.google.gson.TypeAdapterFactory
-keep class * implements com.google.gson.JsonSerializer
-keep class * implements com.google.gson.JsonDeserializer

# Prevent R8 from leaving Data object members always null
-keepclassmembers,allowobfuscation class * {
  @com.google.gson.annotations.SerializedName <fields>;
}
```
keep.xml
```
<?xml version="1.0" encoding="utf-8"?>
<resources xmlns:tools="http://schemas.android.com/tools"
    tools:keep="@drawable/*,@raw/*"
     />
```
I build app-release.aab with bundletool and use this command to create apks
```
java -jar bundletool.jar  build-apks --bundle=app-release.aab --output=my_app.apks --mode=universal --ks=upload_keystore.jks --ks-pass=pass:<myPassword> --ks-key-alias=upload_keystore --key-pass=pass:<myPassword> 
```
Then i unpack my_app.apks, extract universal.apk and install it on real android device. Notifications runs, virbrations plays but no sound.
I do not put flutterLocalNotificationsPlugin.show, because it's typical for exaple app and it all notifications run wery vell on debug app.

**Comment by MaikuB** [comment]
If you're looking to report a bug then a minimal app that can reproduce the problem will be needed as asked for in the bug report template.

Have you also tried reproducing the issue with the example app as I haven't heard of issues with this even when using a release APK. There have been some reports of some Android devices (e.g. Xiaomi) ones that need some settings changed for sound to work. This is outside the control of the plugin. I've also seen cases where some don't realise that the volume/sound settings for playing media is separate from the ringer one.

**Comment by adrianprawira** [comment]
@spacekestrel Hey bro, Do you mind to share the solution about this issue? I'm facing similar problem too...

**Comment by Andro-Samurai** [comment]
I have the same issue on some devices (Samsung), @spacekestrel any hints
