### ISSUE TITLE
zonedSchedule does not work on Samsung galaxy xx (e.g. Xcover 5)

### ISSUE THREAD

**Issue by dushon** [MaikuB/flutter_local_notifications#1284]
Implementation of zonesSchedule on samsung galaxy (e.g. Xcover5, Android 11)  does not work correctly. Scheduled notifications not work when the application is in the background. Notifications are triggered only when the application is started. For details, see the code sample below. 

Is there any way to solve this problem?

Thx for reply.

`
```dart
        await flutterLocalNotificationsPlugin.zonedSchedule(
            ticket.id,
            ticket?.name?.replaceAll('_', '\u00A0') ?? '',
            'Platnost vyprší za pár minut.',
            scheduledDate,
            const NotificationDetails(
              android: AndroidNotificationDetails('id', 'Name', 'Description'),
            ),
            androidAllowWhileIdle: true,
            uiLocalNotificationDateInterpretation:
                UILocalNotificationDateInterpretation.absoluteTime);
      }

```
`

**Comment by MaikuB** [comment]
This relates to what was described at https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#scheduled-android-notifications. The only solution is you'd need to check the phone's settings to see what can be enabled to fix the issue
