### ISSUE TITLE
Notification icon is in poor quality

### ISSUE THREAD

**Issue by bigbang489** [MaikuB/flutter_local_notifications#1285]
I successful show the icon, but the problem is it's poor quality (the green icon), no matter how I change the resolution of the image. the quality of icon from other app is in better quality (the blue icon)
Is there any recommendation to export to png file, or any configuration that I missed?
I exported every scale from ldpi to xxxhdpi

Thanks
![unnamed](https://user-images.githubusercontent.com/29498440/129664790-77d6e75e-6565-458c-ac3a-da5f693a254a.png)

**Comment by MaikuB** [comment]
This would be outside of the control of the native notification APIs, let alone the plugin as it just displays what it's provided. The only thing that comes to mind is that your original image is probably not detailed enough. Increasing the resolution of an image doesn't make it look better. If what you had was originally small, increasing the resolution would make it worse. The image itself would need to be high enough quality at higher resolutions e.g. a vector image that you export to different PNG resolutions. If you need more guidance on this then you'd probably need to speak to a designer to get help
