### ISSUE TITLE
The build failed likely due to AndroidX incompatibilities in a plugin.

### ISSUE THREAD

**Issue by aspiiire** [MaikuB/flutter_local_notifications#1286]
After moving the minSdkVersion from 18 to 19 due to the need to implement Google Ads package the package stopped working.

it gives the following problem:

```
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:processDebugResources'.                 
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed                                    
     /home/name/.gradle/caches/transforms-2/files-2.1/ac4fd0c8568c7f89d6212e04e47ffb80/play-services-ads-lite-20.1.0/AndroidManifest.xml:27:5-43:15: AAPT: error: unexpected element <queries> found in <manifest>.
                                                                        
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 15s                                                     
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        15.8s
The build failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetifier to solve the incompatibility.
Building plugin flutter_local_notifications...

Exception: The plugin flutter_local_notifications could not be built due to the issue above.
```

Things that I have tried without success:

- flutter clean
- flutter pub cache repair
- removed all files from .android/build-cache/*
- removed all cache files from .gradle/caches/*
- Upgraded the package to dev version

I have read that some contributor has added the AndroidX support so updated the package to the latest dev, but had the same issues. I'have searched on tons of websites, but I fail to find the solution 😅

**Comment by MaikuB** [comment]
It's quite possible that even though it says this plugin fails to build that your issue lies elsewhere. This plugin has already migrated to AndroidX and no one else has reported issues on this too. If you build the example app then you should find that it works as expected.

If you look at the exception itself it really fails at

```
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed                                    
     /home/name/.gradle/caches/transforms-2/files-2.1/ac4fd0c8568c7f89d6212e04e47ffb80/play-services-ads-lite-20.1.0/AndroidManifest.xml:27:5-43:15: AAPT: error: unexpected element <queries> found in <manifest>.
```

which isn't to do with plugin but to do with the library you use for ads. I suggest you look on the repository for that library as chances are there are open issues to do with it, which aren't to do with this plugin

**Comment by aspiiire** [comment]
> It's quite possible that even though it says this plugin fails to build that your issue lies elsewhere. This plugin has already migrated to AndroidX and no one else has reported issues on this too. If you build the example app then you should find that it works as expected.
> 
> If you look at the exception itself it really fails at
> 
> ```
> > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
>    > Android resource linking failed                                    
>      /home/name/.gradle/caches/transforms-2/files-2.1/ac4fd0c8568c7f89d6212e04e47ffb80/play-services-ads-lite-20.1.0/AndroidManifest.xml:27:5-43:15: AAPT: error: unexpected element <queries> found in <manifest>.
> ```
> 
> which isn't to do with plugin but to do with the library you use for ads. I suggest you look on the repository for that library as chances are there are open issues to do with it, which aren't to do with this plugin

Thank you for your time and clarification
