### ISSUE TITLE
Is there any solution for scheduling notification with starting date?

### ISSUE THREAD

**Issue by sejun2** [MaikuB/flutter_local_notifications#1292]
I can't find any references to start notification with starting date.
Any solution for this? Thanks!

**Comment by MaikuB** [comment]
Please take a closer look at the readme https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#scheduling-a-notification and the [example app](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications/example)

**Comment by sejun2** [comment]
I apologize to incorrect question. 

What I mean was that scheduling weekly or daily notification with starting date.
If I set starting date as '2021-09-01' and daily, I look forward to get daily notification from '2021-09-01'. 
I couldn't find any solutions for this.

**Comment by sejun2** [comment]
> Please take a closer look at the readme https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#scheduling-a-notification and the [example app](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications/example)

I apologize to incorrect question.

What I mean was that scheduling weekly or daily notification with starting date.
If I set starting date as '2021-09-01' and daily, I look forward to get daily notification from '2021-09-01'.
I couldn't find any solutions for this.

**Comment by MaikuB** [comment]
Both cases are covered in the example app

**Comment by sejun2** [comment]
> Both cases are covered in the example app

Ok I got it. Thanks!
