### ISSUE TITLE
What callback can I use when a notification is received in the foreground

### ISSUE THREAD

**Issue by fremfi** [MaikuB/flutter_local_notifications#1302]
I'd like to use the payload to route the user while they are on the foreground, after clicking on the notification, but I'm only aware of the onSelectNotification which only runs when you click in the background

**Comment by MaikuB** [comment]
`onSelectNotification` is for foreground as well. If that isn't working for you then you'd need to check your code and you should be able to see this working in the example app. Closing as there are no known issues on this. Feel free to reopen if you've identified a bug and can fork the example app as a way to provide a minimal app that can reproduce the issue
