### ISSUE TITLE
Test Condition on Scheduled Notifications

### ISSUE THREAD

**Issue by mbasa** [MaikuB/flutter_local_notifications#131]
Will it be possible to pass a function to test if the Notification should be displayed or not first in Scheduled events. Thanks.

**Comment by MaikuB** [comment]
Nope

**Comment by RobertB4** [comment]
@maikuB May I ask why there is no plan to implement this?

My usecase: I am developing  flashcard app. I want to send a daily reminder to users if any of their flashcards are tagged as "needs review".

I'd be happy to implement it if you don't mind.

**Comment by MaikuB** [comment]
None of the native notification APIs expose that kind of functionality and the plugin is intended to like a wrapper of sorts around them. As such, if you were to do what you've described in say, an Android app written in Java, it would a require periodic job to fire to see if a notification should be shown. This is essentially what you're doing now

**Comment by RobertB4** [comment]
Ok, that makes sense! Thanks for the explanation!
