### ISSUE TITLE
[Help] Update progress notification value

### ISSUE THREAD

**Issue by joaobaronisilva** [MaikuB/flutter_local_notifications#1315]
Hi, guys

First of all, i'd like to take this moment to thanks by flutter local notification package. It's important to community.

I'm using flutter local notification package in one of my apps. And, i'm working with a specific usecase that i need update the progress value of the notification channel, to give to user a feedback to the progress of the a task, that are running on the background. How can I do this?

**Comment by joaobaronisilva** [comment]
Guys,
I found a solution to my problem. I run the following command in a **for** loop. _i_ represents current value and _qtdProdutos_ represents max value possible.

```dart
NotificationService().showNotification(1, 'Sincronizando produtos', '', 
                                   NotificationChannels().canalSincronizacao(i, qtdProdutos));
```

Idk if the solution above is the best as possible. So, im accepting suggestions

**Comment by MaikuB** [comment]
Thanks the kudos :)

Could you elaborate more on exactly what you're trying to do? Asking this as progress is not tied to notification channels. If you need to update content for a notification then in general you make use of the same notification id to update its content. There's also an Android specific example for updating a progress bar if you check the example app https://github.com/MaikuB/flutter_local_notifications/blob/276c7bc8c2f1356afc25df7d7b215c17616fe40b/flutter_local_notifications/example/lib/main.dart#L523

**Comment by joaobaronisilva** [comment]
@MaikuB, thanks by ur answer
ur suggestion worked perfeclty! I followed the example avaible on example app, and everthing is like expected
Another question: As far I know, **iOS has no progress notification**, so in this case, how the flutter local notification will show them?

**Comment by MaikuB** [comment]
It should show as a standard notification but this depends on what you specify. This is something you run and confirm. I say that as since you asked the question, I'm hoping that you aren't coding "blindly" so to speak when it comes to iOS
