### ISSUE TITLE
Plugin is not deleting the old reminders from notification panel(android)

### ISSUE THREAD

**Issue by SalishKumar** [MaikuB/flutter_local_notifications#1321]
Android has set limit to 24 notifications per app, app should old notification so user can keep receiving new notifications
**To Reproduce**

1. Set 25 reminders  you will receive 24 reminders 

**Expected behavior**
Old notifications should be removed from notification bar so that user can recieve new one

**Comment by MaikuB** [comment]
This won't be changed as the plugin's responsibility is to provide a more direct interface to the native platform APIs for showing/removing notifications. If there are notifications that need to be removed, it would be the responsibility of your application to do this just as it would do if it was written in Kotlin/Java directly
