### ISSUE TITLE
Android 12 Support

### ISSUE THREAD

**Issue by agungnursatria** [MaikuB/flutter_local_notifications#1322]
**Describe the bug**
android:exported needs to be explicitly specified for <receiver>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.

**To Reproduce**

1. (In my app) Go to android/app/build.gradle
2. Upgrade targetSdkVersion to 31
2. Click on sync now
3. Run the app

**Expected behavior**

Build success. 
Need to add android:exported in android manifest receiver which have intent-filter

**Sample code to reproduce the problem**

**Comment by MaikuB** [comment]
There's already been issues and an open PR on this. I kindly that you don't more issues as this adds more work for maintainers when you've seen the PR too. Furthermore, the changes in that PR are already in a pre-release so if you are in need of those changes, you should use the pre-release as Android 12 is still in beta

**Comment by agungnursatria** [comment]
Thankss!
