### ISSUE TITLE
Targeting S+ (version 31 and above) migration

### ISSUE THREAD

**Issue by hamfatfat** [MaikuB/flutter_local_notifications#1324]
The below exception is handled when android target sdk api is changed to 31,

adb: failed to install D:\recitation-mobile\RecitationFlutter\recitation-flutter\build\app\outputs\flutter-apk\app.apk: Failure [INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl494713769.tmp/base.apk (at Binary XML file line #142): com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present]

**Comment by MaikuB** [comment]
Back when you reported the issue, support Android 12 would've required using the 9.0.0 prerelease. This is now on a stable 9.0.0 release since Android 12 is considered officially released now
