### ISSUE TITLE
Android 12 not showing notification

### ISSUE THREAD

**Issue by JavierConde** [MaikuB/flutter_local_notifications#1328]
Hi folks,

first, i read the other bugs here respect this problem, and see this could be resolve in v.9.0.0.

I updated my application to these versions:

  firebase_core: ^1.7.0
  firebase_messaging: ^10.0.8
  flutter_local_notifications: ^9.0.0

I'm using flutter:
Flutter 2.5.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 3595343e20 (8 days ago) • 2021-09-30 12:58:18 -0700
Engine • revision 6ac856380f
Tools • Dart 2.14.3

In my manifest, i have this:
```
<application
        android:label="GeoTareas"
        android:icon="@mipmap/ic_launcher"
        android:usesCleartextTraffic="true"
        android:exported="true"
        >

        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
          
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />

            <meta-data
                android:name="com.google.firebase.messaging.default_notification_channel_id"
                android:value="logictrack"/>

            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
```

i initialized the plugin in a service and try to display the notification like this:
```

import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';

class LocalNotificationService {
  static final FlutterLocalNotificationsPlugin _futterLocalNotificationsPlugin = FlutterLocalNotificationsPlugin();
  static initialize(BuildContext context) async {
    final InitializationSettings initializationSettings = InitializationSettings(android: AndroidInitializationSettings("@mipmap/ic_launcher"));

    await _futterLocalNotificationsPlugin.initialize(initializationSettings, onSelectNotification: (String? payload) async {
      // Navigator.of(context).pushNamed(payload);
      print('payload: $payload');
    });
  }

  static void display(RemoteMessage message) async {
    try {
      final double dt = DateTime.now().millisecondsSinceEpoch / 1000;
      final int id = dt.toInt();

      final NotificationDetails notificationDetails = NotificationDetails(
        android: AndroidNotificationDetails(
          'logictrack',
          'High Importance Notifications',
          channelDescription: 'High Importance Notifications',
          priority: Priority.max,
          importance: Importance.max,
        ),
      );

      print(message.notification!.title);

      _futterLocalNotificationsPlugin.show(
        id,
        message.notification!.title,
        message.notification!.body,
        notificationDetails,
        // payload: message.data['item']
      );
    } on Exception catch (e) {
      print('Error display $e');
    }
  }
}
```

my gradle is configured:
compileSdkVersion 31
and
minSdkVersion 21
targetSdkVersion 31

before the update, this plugin was working well, popup the notif always, after the update, never more works, the push is received in the phone, i can configure the sound, etc and works fine, but the local notifcation never show ups.

Repeat, i read the other posts about this, search on internet and spend 2 days on this without any solution.

Could you guys try to help me?

thanks!

**Comment by MaikuB** [comment]
Please provide a link to a minimal app that can reproduce the problem. Did you also try to run the example app in the repository to see if it could reproduce the problem. Both of these are mentioned in the bug report template, which is what should've been used for instances like this

**Comment by JavierConde** [comment]
Hello MaikuB, i cloned the repository and install the example in a phone A10 with Android 11. The first option, justo show in the taskbar the icon, but not sound and not show a desplegable windows from the top like before.
I try to do the same on a S21 with android 11 and is the same

**Comment by MaikuB** [comment]
Closing this as there's no been further updates as previous info would indicate a configuration issue. Feel free to re-open if you encounter a bug and can provide a fork that contains minimal steps to reproduce the problem
