### ISSUE TITLE
[Help] how to use ContentUriAndroidIcon() ??

### ISSUE THREAD

**Issue by Joseph-Nathan** [MaikuB/flutter_local_notifications#1332]
in AndroidNotificationDetails() in MessagingStyleInformation() how to use ContentUriAndroidIcon() ?
i have image url that i want to appear as person image , how can i do that ? 

when i use ContentUriAndroidIcon( _url ) 
it take image place but the place was blank .

**Comment by MaikuB** [comment]
This is for Android content URIs (see https://developer.android.com/reference/android/content/ContentUris). Not to be confused with URLs from the web. Please make sure you check the example app as this also nearly all the scenarios that can be implemented with this plugin, including how to make use of an image from the web as an icon
