### ISSUE TITLE
Notification does not come at correct time. 

### ISSUE THREAD

**Issue by BenjaminMahmic** [MaikuB/flutter_local_notifications#1333]
The notification does not come at the correct time. I use ''schedule'' from an older version, and use "zoneSchedule" from the last version, the error is the same. 
Like, if I set the time of notification at 21:00, it comes at 21:02, 03, etc.. sometimes it goes more than 2-3 minutes offset... 

Note: it happened when I restart mobile or turn off / turn on.

**Comment by mike-robinson** [comment]
Nope. I'm afraid the @MaikuB will have to take a look at the issue.

**Comment by MaikuB** [comment]
Make sure you have set the `androidAllowWhileIdle` to true. If you have and still encounter delays then you need to check the settings for your phone as there's nothing further that the plugin can do

**Comment by anggaaryas** [comment]
> `androidAllowWhileIdle`

Thanks, it works

**Comment by MaikuB** [comment]
Closing this due to lack of further response and information to reproduce the issue
