### ISSUE TITLE
How to check if user disabled notifications

### ISSUE THREAD

**Issue by evansherry** [MaikuB/flutter_local_notifications#1339]
The question is around whether app notifications are available, I need to know the following two points.

1. How to check if the user has disabled notifications?
On Android, you can use `NotificationManagerCompat.areNotificationsEnabled` to determine whether notifications are available.

2. How to get NotificationChannel through channel id?
On Android, you can use `NotificationManagerCompat.getNotificationChannel(channelId)`.

Can you provide some solutions, thx.

**Comment by MaikuB** [comment]
Neither of these are capabilities are available. It's possible some permission plugins are available for the first feature. If you need access to those APIs you could look at adding custom code of your own, submit a PR etc
