### ISSUE TITLE
Unchanged example app crashes on startup on real Android device but not emulator

### ISSUE THREAD

**Issue by cdwangco** [MaikuB/flutter_local_notifications#1341]
On my Android emulator the example app works perfectly, but if I try to start it on my Samsung Galaxy Note 5 (Android Version 7.0) then it crashes on initialization with the error, "flutter_local_notifications_example" has stopped. I haven't made any changes to the example app.

************************    This is the error on the actual Samsung Note 5 device: ************************

Launching lib\main.dart on SM N920T in debug mode...
Running Gradle task 'assembleDebug'...
√  Built build\app\outputs\flutter-apk\app-debug.apk.
W/FlutterActivityAndFragmentDelegate(19546): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
Debug service listening on ws://127.0.0.1:49933/8wH26ZocRDY=/ws
Syncing files to device SM N920T...
E/AndroidRuntime(19546): FATAL EXCEPTION: main
E/AndroidRuntime(19546): Process: com.dexterous.flutter_local_notifications_example, PID: 19546
E/AndroidRuntime(19546): java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/ZoneId;
E/AndroidRuntime(19546): 	at com.whelksoft.flutter_native_timezone.FlutterNativeTimezonePlugin.onMethodCall(FlutterNativeTimezonePlugin.kt:37)
E/AndroidRuntime(19546): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/AndroidRuntime(19546): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/AndroidRuntime(19546): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
E/AndroidRuntime(19546): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime(19546): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/AndroidRuntime(19546): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(19546): 	at android.app.ActivityThread.main(ActivityThread.java:6682)
E/AndroidRuntime(19546): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(19546): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1534)
E/AndroidRuntime(19546): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1424)
E/AndroidRuntime(19546): Caused by: java.lang.ClassNotFoundException: Didn't find class "java.time.ZoneId" on path: DexPathList[[zip file "/data/app/com.dexterous.flutter_local_notifications_example-2/base.apk"],nativeLibraryDirectories=[/data/app/com.dexterous.flutter_local_notifications_example-2/lib/arm64, /data/app/com.dexterous.flutter_local_notifications_example-2/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
E/AndroidRuntime(19546): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime(19546): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
E/AndroidRuntime(19546): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(19546): 	... 11 more

************* This is what is expected and is shown on the console when running on an Android emulator: ************

Launching lib\main.dart on sdk gphone x86 arm in debug mode...
Running Gradle task 'assembleDebug'...
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...
W/FlutterActivityAndFragmentDelegate( 6296): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
Debug service listening on ws://127.0.0.1:59950/Itb8DzjTSTo=/ws
Syncing files to device sdk gphone x86 arm...

**Comment by MaikuB** [comment]
Haven't heard of anyone else with this issue before and can't reproduce this myself so not much I can do about this. Could you fork this repo and bump the `flutter_native_timezone` dependency to see if it fixes the issue? There seems to be a similar issue for that plugin that is supposed to have been resolved (see https://github.com/pinkfish/flutter_native_timezone/issues/25). If that fixes the issue, it'd be good if you can confirm and submit a PR back to this repository
