### ISSUE TITLE
iOS when app in foreground I was not receiving any notifications

### ISSUE THREAD

**Issue by JoelSuyati** [MaikuB/flutter_local_notifications#1349]
Actually I was Implementing alert like app but in that for iOS I was not receiving any notifications when app in foreground. But it works fine when app in background or killed state.

`AndroidNotificationDetails androidPlatformChannelSpecifics =
        AndroidNotificationDetails(id.toString(), name,
            importance: Importance.max,
            priority: Priority.high,
            ticker: 'ticker',
            playSound: false);

    IOSNotificationDetails iOSPlatformChannelSpecifics = IOSNotificationDetails(
        presentAlert: true, presentBadge: true, presentSound: false);

    NotificationDetails platformChannelSpecifics = NotificationDetails(
        android: androidPlatformChannelSpecifics,
        iOS: iOSPlatformChannelSpecifics);

      await flutterLocalNotificationsPlugin.zonedSchedule(id, name, desc,
          scheduledNotificationDateTime, platformChannelSpecifics,
          androidAllowWhileIdle: true,
          uiLocalNotificationDateInterpretation:
              UILocalNotificationDateInterpretation.absoluteTime);`

This is my Initialisation code

`var initializationSettingsAndroid =
        AndroidInitializationSettings('name');

    var initializationSettingsIOS = IOSInitializationSettings(
        requestAlertPermission: false,
        requestBadgePermission: false,
        requestSoundPermission: false,
        onDidReceiveLocalNotification:
            (int id, String title, String body, String payload) async {});

    var initializationSettings = InitializationSettings(
        android: initializationSettingsAndroid, iOS: initializationSettingsIOS);

    flutterLocalNotificationsPlugin.initialize(initializationSettings,
        onSelectNotification: (String payload) async {
      if (payload != null) {
        debugPrint('notification payload: ' + payload);
      }
    });`

**Comment by JoelSuyati** [comment]
Actually the reply is not a solution for me the solution is I used Awesome notification along with this package that made me such errors once I removed that everything worked fine

**Comment by lizhuoyuan** [comment]
add this:
```dart
const IOSNotificationDetails iosDetail = IOSNotificationDetails(
  presentAlert: true,
  presentBadge: true,
  presentSound: true,
);
```
