### ISSUE TITLE
Feature Request: Allow setting `defaultActionName` on Linux to null

### ISSUE THREAD

**Issue by karmanyaahm** [MaikuB/flutter_local_notifications#1355]
And consequently return an empty array here if it is null:

https://github.com/MaikuB/flutter_local_notifications/blob/03680366b0c3c232ce74a002fdadaac74168462d/flutter_local_notifications_linux/lib/src/notifications_manager.dart#L206-L214

This would be very helpful for notifications that shouldn't be clickable, since clicking them doesn't do anything. Having notifications that don't trigger an action being clickable just confuses the user.

I can submit a pull request for this if it would be accepted?

**Comment by MaikuB** [comment]
Closing this since the PR was closed and the results differ on different distributions
