### ISSUE TITLE
Notification click event not working When Android app is not running or killed. 

### ISSUE THREAD

**Issue by RahulAlchemy** [MaikuB/flutter_local_notifications#1359]
In android when app is not running or app is killed `onSelectNotification`  it not calling no notification click but it works when app is background or foreground  and this problem is not occurring in IOS.
In IOS all notification click working fine.

      `    await flutterLocalNotificationsPlugin
            .resolvePlatformSpecificImplementation<IOSFlutterLocalNotificationsPlugin>()
             ?.requestPermissions(
                alert: true,
               badge: true,
              sound: true,
              );
            if (settings.authorizationStatus == AuthorizationStatus.authorized) {
           //debugPrint('User granted permission');
            } else if (settings.authorizationStatus == AuthorizationStatus.provisional) {
          //debugPrint('User granted provisional permission');
           } else {
          //debugPrint('User declined or has not accepted permission');
          }
           await FirebaseMessaging.instance.setForegroundNotificationPresentationOptions(
            alert: true, // Required to display a heads up notification
             badge: true,
             sound: true,
           );

      await flutterLocalNotificationsPlugin
          .resolvePlatformSpecificImplementation<AndroidFlutterLocalNotificationsPlugin>()
          ?.createNotificationChannel(channel);

      var initializationSettingsAndroid =
          AndroidInitializationSettings('drawable/ic_notification'); // <- default icon name is @mipmap/ic_launcher
      final IOSInitializationSettings initializationSettingsIOS = IOSInitializationSettings(
          requestSoundPermission: true,
          requestBadgePermission: true,
          requestAlertPermission: true,
          onDidReceiveLocalNotification: onDidReceiveLocalNotification);

      final InitializationSettings initializationSettings =
          InitializationSettings(android: initializationSettingsAndroid, iOS: initializationSettingsIOS);

      await flutterLocalNotificationsPlugin.initialize(initializationSettings,
          onSelectNotification: onNotificationClickHandler);
      listenerNotification();`

   `showNotification(Map<String, dynamic> message) async {
  flutterLocalNotificationsPlugin.show(
      message.hashCode,
      message["title"],
      message["body"],
      NotificationDetails(
        android:
            AndroidNotificationDetails(channel.id, message["title"], message["body"], icon: null // other properties...
                ),
      ),
      payload: json.encode(message));
}`

**Comment by MaikuB** [comment]
It's not meant to work when the app isn't running as there isn't any code left in memory around listening for events. This is mentioned in the readme

```
Note: from version 4.0 of the plugin, calling initialize will not trigger the onSelectNotification callback when the application was started by tapping on a notification to trigger. Use the getNotificationAppLaunchDetails method that is available in the plugin if you need to handle a notification triggering the launch for an app e.g. change the home route of the app for deep-linking.
```

Looks like you may have missed this so I would suggest taking another look at the readme in case there's other key information you may have also missed
