### ISSUE TITLE
When a new notification channel is created, the existing notification sound changes.

### ISSUE THREAD

**Issue by ilsong963** [MaikuB/flutter_local_notifications#1362]
I'm not good at English, so I ask for your understanding of using a translator.

my library version is 
`flutter_local_notifications: 4.0.1+2`

I am using 6 notification channels and I am trying to create 2 notification channels.
However, when two are generated, the notification sound of the existing channel changes.

create chennel part in my code 
`const newOrderNotiChannel = AndroidNotificationChannel(
        'noti_push_NEW_ORDER', // id
        'noti_push_NEW_ORDER', // title
        'neworder', // de
        sound: RawResourceAndroidNotificationSound('new_order'),
        importance: Importance.max);
    await flutterLocalNotificationsPlugin
        .resolvePlatformSpecificImplementation<AndroidFlutterLocalNotificationsPlugin>()
        ?.createNotificationChannel(newOrderNotiChannel);`

send notification on server
`const NOTI_FOR_NEW_ORDER = {
  notification: {
    title: "neworder",
    body: "neworder",
    android_channel_id: "noti_push_NEW_ORDER",
    sound: "NEW_ORDER.wav"
  },
  data: {
    click_action: "FLUTTER_NOTIFICATION_CLICK",
    type: "NEW_ORDER"
  }
};`

when send notification value of android_channel_id as noti_push_NEW_ORDER,
The sound that plays is the basic sound or other custom sound (ex DONE_ORDER) but title body is right.
Ios have no problem. i think.. because it is handed over to the sound of payload.

While searching for this issue, the stackoverflow answer is write keep.xml, so this code is also written down.
`<?xml version="1.0" encoding="utf-8"?>
<resources xmlns:tools="http://schemas.android.com/tools"
    tools:keep="@drawable/*,@raw/new_order,@raw/hurry_order,@raw/checked_order,@raw/new_message,@raw/new_notice,@raw/test_alarm" />`

If i send notification A, iwill hear notification B sound , and if isend notification B, i will hear sound C.

If the notification sound changes after release at google play, users will feel uncomfortable because there is no solution other than reinstalling the application and deleting data.

Is this a version issue? Or is there a solution?

**Comment by ilsong963** [comment]
I found the same case in stackoverflow.
[https://stackoverflow.com/questions/48781986/notificationchannel-playing-wrong-sound-in-oreo](url)

my sound file name is "new_order", "hurry_order" ...
so I named the file I was going to add like "znew_order", "zhurry_order"

There's no more problem....
and i close this issue

**Comment by MaikuB** [comment]
I'm reopening this as from the issue you've described,  it looks like there's a valid problem to be addressed here where if the resource IDs change, a different sound could be played
