### ISSUE TITLE
IOS notification sound not working

### ISSUE THREAD

**Issue by DushanAd** [MaikuB/flutter_local_notifications#1365]
Ios notification sound is not getting.I have implimented similar like in the example code but not working.

**Comment by MaikuB** [comment]
This would be something you'd need to check the code/configuration on your end. There are no known issues with the plugin around playing sound and the example app itself can be run to check

**Comment by expertdev-designer** [comment]
Also for me ..custom sound not working

**Comment by jinfagang** [comment]
@MaikuB the readme part doesn't mentioned anything about iOS custom sound setup. It's just android. Does there any instructions on how to make iOS custom sound? I know the code, but where does sound place?

**Comment by MaikuB** [comment]
@jinfagang it's not tied to how plugin works so the only official resource I could find from Apple is already linked in the readme. The way a sound would be added would be same process normal iOS app development follows so there'll likely be more docs/tutorials on this if you do a general search online.
