### ISSUE TITLE
[Question] How can I prevent user to dismiss a notification? How to dismiss a notification by its id?

### ISSUE THREAD

**Issue by ralphvmo** [MaikuB/flutter_local_notifications#1370]

**Comment by MaikuB** [comment]
Please check the readme and example app for the plugin as these scenarios are covered. However, preventing a notification from being dismissed is only possible on Android. As you've asked this when it's been covered it the aforementioned places, I suspect you may also need to familiarise yourself with the docs available around notifications for the platforms your targeting. If that's the case, please ensure you do so as the purpose of a plugin is to provide an interface to a target platform's native APIs
