### ISSUE TITLE
Programmatically turn off in the middle of notification sounds

### ISSUE THREAD

**Issue by Benife** [MaikuB/flutter_local_notifications#1371]
hello.

I am playing a 60 second mp3 file with the fcm push notification sound.
However, the user wants to arbitrarily stop playing the sound in the middle, what should I do?
I can't find it no matter how much I search.

please help me

**Comment by MaikuB** [comment]
This isn't possible. General note that if you are looking to see what can be done via notifications, the first place to check would be the docs for the platforms you're targeting. If you're dealing with FCM then this isn't place to ask as this library is dealing with local notifications not push notifications as you had stated in your original message
