### ISSUE TITLE
Text direction

### ISSUE THREAD

**Issue by sm2017** [MaikuB/flutter_local_notifications#1373]
How can I set text direction of local notifications?
I want to make `title` and `body` of notification LTR or RTL based on locale

**Comment by MaikuB** [comment]
The native notification APIs don't have any properties for this so I suspect this handled automatically. Not something I'm familiar and can verify though so it's something you'd need to check

**Comment by sajjadjafari76** [comment]
Hi @MaikuB, 

I’ve investigated the RTL text rendering issue on Android notifications. 

I believe this can be solved using either:
- BidiFormatter wrapping (for automatic RTL detection)
- or RemoteViews customization if a more controlled layout is needed.

I can prepare a patch for this and submit a PR if you are interested in merging it.

**Comment by MaikuB** [comment]
Hi @sajjadjafari76, thanks for sharing your findings. The first approach sounds good to me and happy to review on a PR on it. As part of the PR, is it possible to update the example app so there is an additional scenario for RTL text?
