### ISSUE TITLE
[Request] Support for interruption level in iOS

### ISSUE THREAD

**Issue by mgonzalezc** [MaikuB/flutter_local_notifications#1374]
Hello, from iOS 15, it is possible to set the interruption level of the notifications. See [this API reference](https://developer.apple.com/documentation/usernotifications/unnotificationcontent/3747256-interruptionlevel?language=objc).

Could this be added?

Thank you,

Marina

**Comment by MaikuB** [comment]
Any chance you could submit a PR for this?

**Comment by MaikuB** [comment]
Closing as it was added in 10.0 a while back
