### ISSUE TITLE
Error Launching Application after iOS setup

### ISSUE THREAD

**Issue by ZXERSTON** [MaikuB/flutter_local_notifications#1377]
My app is working fine before adding this code for the iOS setup.

```
if #available(iOS 10.0, *) {
  UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate
}
```

My code in AppDelegate.swift:
```
import UIKit
import Flutter

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
  if #available(iOS 10.0, *) {
  UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate
}
}
```

Error:

![image](https://user-images.githubusercontent.com/62199218/140452424-44c32d91-324c-44a2-b5f4-e0cbd2745fcb.png)![image](https://user-images.githubusercontent.com/62199218/140452442-bc9c3c2a-1ee8-4ba4-a6f2-ac3aee128ab1.png)

Hope to get some guidance here.

**Comment by MaikuB** [comment]
Looks like an issue with your code causes it to fail to compile as you added the code outside the scope of the method body itself. There's a link to the [example app](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications/example) where this setup has been done that can be used as a reference for you to compare

**Comment by vanessabin** [comment]
Try to add the missing line with the deployment target in your pod file

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
  end
end
```

**Comment by MaikuB** [comment]
Closing as it's not an issue with the plugin but an issue with the OP's application code
