### ISSUE TITLE
Build fails on Android due to jcenter in build.gradle

### ISSUE THREAD

**Issue by tigertore** [MaikuB/flutter_local_notifications#1380]
Hi,
Your build.gradle file specifies jcenter() as one of the repositories.
Jcenter() is deprecated, and today the certificate to the webserver which hosts jcenter, jcenter.bintray.com, expired.
The certificate states NOT AFTER:  Tue, 09 Nov 2021 12:00:00 GMT. 

This causes all of our CI and release pipelines to fail.

The fix is easy, just replace jcenter() with mavenCentral().

Please fix asap.

**Comment by MaikuB** [comment]
If it's an easy fix, could you look at submitting a PR so I can look at it later. It is past 1am in my timezone

**Comment by tigertore** [comment]
bintray.com has just updated their certificate, and jcenter() is working again.
But I recommend that we replace jcenter() with mavenCentral(). 
I will make a PR tomorrow.

**Comment by tigertore** [comment]
Added PR:
#1381
