### ISSUE TITLE
4973 Error -  Android 

### ISSUE THREAD

**Issue by Promhuadz** [MaikuB/flutter_local_notifications#1383]
I can't show noti from firebase  I don't know how to fix it
<img width="1053" alt="Screen Shot 2564-11-10 at 20 54 55" src="https://user-images.githubusercontent.com/39197776/141126176-fb34c289-cf32-47fa-908b-20b62a7caf14.png">
<img width="681" alt="Screen Shot 2564-11-10 at 20 55 33" src="https://user-images.githubusercontent.com/39197776/141126419-a0eaedc1-445c-4704-80b8-e2b837bbb046.png">

**Comment by MaikuB** [comment]
You haven't set the icon by initialising the plugin. Please check the readme as it's stated as the first step to do. Alternatively, you can specify the icon for the notification directly. You can also make use of the example app available to cross-reference. The FCM plugin example app specifies the icon for each notification

**Comment by Promhuadz** [comment]
@MaikuB  
It work thank you
