### ISSUE TITLE
Loop sound for notification

### ISSUE THREAD

**Issue by anhhh11** [MaikuB/flutter_local_notifications#139]
I think it should have something like customizing FLAG_INSISTENT flag (https://stackoverflow.com/questions/26631651/android-notification-builder-how-to-setsound-so-that-sound-plays-in-a-looper) to support loop notification sound.

**Comment by MaikuB** [comment]
Sorry for the late response. If this is you something need, feel free to submit a PR as it appears you already have a fork

**Comment by kodaizen** [comment]
Hello, 
I am also interested in repeating the sound

**Comment by MaikuB** [comment]
Happy to look at a PR for this

**Comment by MaikuB** [comment]
Closing this as it's not something I'm not looking to work on. As stated above, if someone in the community needs this then submit a PR

**Comment by reshuashish** [comment]
how to get this feature for ios? (https://stackoverflow.com/questions/20063674/sound-notification-in-loop-in-for-alarm-application-in-ios)

**Comment by MaikuB** [comment]
There is no such feature on iOS

**Comment by reshuashish** [comment]
I am working on the alarm application in IOS. Where I want to send the notification when the application is in background mode, the sound notification would be like ALARM. i.e. sound will not stop until the user doesn't perform any interaction.

Is there any way to make it happen, I have seen some Alarm apps on AppStore  which use the same principle for alarm
