### ISSUE TITLE
Full screen intent notification issue in "Foreground" and "Background" if Lock screen is not enabled

### ISSUE THREAD

**Issue by anil-sookshum** [MaikuB/flutter_local_notifications#1395]
**Describe the bug**
I am trying to schedule full screen intent notification and it works fine if "lock screen" is enabled in phone, but a simple notification popup will appear in case if app is in foreground or in background and lock screen is not enabled.

It works fine sometimes in foreground or background and then again starts showing popup/heads up notification. Sometimes if the phone status-bar is expanded over the example app the full screen notification works fine. Take a look into the screen recording.

**Video Recording**
https://drive.google.com/file/d/1fkxRSlttOOZiROIuLMYfpur-t2_3PRuG/view?usp=sharing

**To Reproduce**

1. Clone and Run the plugin example on Android device
2. Scroll down to 'Show full-screen notification' option button 
3. Click on 'Show full-screen notification' button on example app home page
4. It will open an "Turn off your screen pop" confirmation dialog with "OK" and "Cancel" button
5. Click on "Ok" button and "**Do not turn off the screen**"
6. A simple notification popup will trigger instead of pull screen page which is defined on "onSelectNotification" function

**Expected behavior**
A full screen intent screen notification should open instead of a popup/heads up notification when app is in foreground or background.

**Show full-screen notification function in example app **
```
await flutterLocalNotificationsPlugin.zonedSchedule(
        0,
        'scheduled title',
        'scheduled body',
        tz.TZDateTime.now(tz.local).add(const Duration(seconds: 5)),
        const NotificationDetails(
          android: AndroidNotificationDetails(
            'full screen channel id',
            'full screen channel name',
            channelDescription: 'full screen channel description',
            priority: Priority.high,
            importance: Importance.high,
            fullScreenIntent: true,
          ),
        ),
        androidAllowWhileIdle: true,
        uiLocalNotificationDateInterpretation:
            UILocalNotificationDateInterpretation.absoluteTime,
      );
```

     
Platform: Android 
Flutter Version: Latest Stable channel
Plugin version : Latest

**Comment by MaikuB** [comment]
Outside the control of the plugin as it's the system  thatdecides what to do. This was documented in the readme, API docs and Android's own documentation [here](https://developer.android.com/training/notify-user/time-sensitive#display-notification-user) that I've quoted below

> Note: The system UI may choose to display a heads-up notification, instead of launching your full-screen intent, while the user is using the device.
