### ISSUE TITLE
[Android Only Bug] commitAsync Error

### ISSUE THREAD

**Issue by ragokan** [MaikuB/flutter_local_notifications#1397]
**Describe the bug**
Crashes the app on the launch for the old android devices.
You can check the *extra* section to see the screenshots. I have talked with the users, they say that their application crashes on launch. The devices are old ones, none of them has more than 2 GB ram, and all of them released before 2017. While debugging in some of their phones, I tried try catch, catchError etc. Definitely it is not changing anything.

- The error does not occur on newer phones and iOS devices.
- The error does not occur on emulator.
- I am using the latest version of all packages and Flutter.

**To Reproduce**
Just start the application.

**Extra**
![image](https://user-images.githubusercontent.com/63511519/142477508-84648218-7087-446a-8501-61f4563c141c.png)

**Comment by mk-dev-1** [comment]
Chrashlytics is showing crashes also on devices from 2019 with 4 GB (Nokia 6.2) and even S21 Ultra - this does not seem to be related to the device….

**Comment by MaikuB** [comment]
@ragokan what does your app do on startup though?

@mk-dev-1 does your app actually use 9.1.2 though? The reason I'm asking is because I previously mentioned 9.1.1 had changes that attempted to fix https://github.com/MaikuB/flutter_local_notifications/issues/1378

**Comment by MaikuB** [comment]
I'll be rolling back changes that were done but this will mean #1378 will be reopened. Currently this is the lesser of two evils though I had no response in assisting with testing fixes for #1378 so hopefully that situation improves next time

**Comment by mk-dev-1** [comment]
May app is using 9.1.2 yes. I specifically published a new version as I realized the issues described here and in #1387 when I used 9.1.1.

Unfortunately I am unable to recreate the issue myself.

Yesterday this affected about 1.5% of users that had the app version that uses 9.1.2. Looking at user streams, it does not seem to prevent them from using the app, i.e. it looks like the app crashes, but not every time....

**Comment by MaikuB** [comment]
Can either of you (@ragokan  and @mk-dev-1) help with testing changes related to this when it's published then e.g. via beta track of your app? Especially @mk-dev-1 as you had a sample app in https://github.com/MaikuB/flutter_local_notifications/issues/1378 but I wasn't able to reproduce the issue you reported there unless there are steps missing

@davidlepilote not sure if you'll see but FYI I suspect going back to `apply()` per your original PR https://github.com/MaikuB/flutter_local_notifications/pull/980 is the way to go

**Comment by ragokan** [comment]
@MaikuB hello, thank you for your very fast answer. The app starts normally, without any error. 

When this part of the code starts running, the app breaks. Weirdly, the try/catch is not working
![image](https://user-images.githubusercontent.com/63511519/142653429-86f4040b-160b-4848-998d-600624cf6630.png)

I report all the errors to the backend, there are no error about notifications. All I know is some of my users can't log in and when I try to check it on Play Store crashes, there are many instances of the error. 
![image](https://user-images.githubusercontent.com/63511519/142653552-2bbb9e8b-c40e-4a5c-970d-2c842ee1b0ea.png)

I call this method on init/loading screen, they are stuck there and the code stop executing.

**Comment by MaikuB** [comment]
@ragokan 9.1.3 should fix the issue though not sure how your app was running into issues with initialisation

**Comment by ragokan** [comment]
> @ragokan 9.1.3 should fix the issue though not sure how your app was running into issues with initialisation

Ohh, thank you so much, if anything changes I will let you know. Have a great day.

**Comment by mk-dev-1** [comment]
@ragokan: Can you consistenly recreate the issue withe sample code provided above? Does it crash only on real devices or also on the emulator? I am asking since I have not been able to reproduce the issue so far. That is, on an emulator.... will need to try later on a real device.

**Comment by ragokan** [comment]
> @ragokan: Can you consistenly recreate the issue withe sample code provided above? Does it crash only on real devices or also on the emulator? I am asking since I have not been able to reproduce the issue so far. That is, on an emulator.... will need to try later on a real device.

Yeah, I can't also reproduce it on the emulator, if it was, it would be easier. For now, I am closing this issue, let us try the new version with the users and see how it is going. Thank you, again.

**Comment by iqfareez** [comment]
Just released new app update few days ago. Had a similar issue with 9.1.2, will try to upgrade to 9.1.4

Google Play Store crashes report on `java.util.concurrent.RejectedExecutionException`:
![Screenshot 2021-11-23 013121](https://user-images.githubusercontent.com/60868965/142949280-fb427144-a067-49fa-a742-d77ff83ca020.png)

**Comment by ragokan** [comment]
With the latest version of plugin, the errors are now gone, thank you. 
(By the way, some of the users' application was crashing, not because of this bug, but because of bad certificate error on old devices. So the error was just disabling the local notifications for the user.)
