### ISSUE TITLE
Receive double Notification with ZoneSchedule() Function

### ISSUE THREAD

**Issue by habilgur** [MaikuB/flutter_local_notifications#1402]
Hello, I used a notification alarm code structure that worked without any problems before wtih schedule() function.. However, when I use the zoneSchedule() method working with the TZDateTime class, some notifications appear twice and the alarm sound of these notifications sometimes sounds once or twice.

When I examine the Android alarm bacths, there is only one alarm set, so I confirm that there are no more than one alarm set with different id's or channel names.

Steps:
1- Set an alarm with a future date (with Zoneschedule())
2- When the alarm time comes;
2.1 The alarm sounds at the exact time. (Okay)
2.2 Notification appears on the screen sometimes twice. (Expected: one notification)
2.3 Notification Alarm sound sometimes rings once, sometimes twice. (Expected: one alarm sound)

As I said, notifications were working smoothly with the schedule() function in the previous version. When the zoneSchdule() method is used without making any changes to the code, more than one notification appears on the screen.

As an alternative to the ZoneSchedule() method used in the latest version, can it be an option to use the schedule() method, which uses the DateTime class, together?

Thanks.

**Comment by MaikuB** [comment]
> As an alternative to the ZoneSchedule() method used in the latest version, can it be an option to use the schedule() method, which uses the DateTime class, together?

Not sure what you're trying to ask here but `schedule()` is deprecated and will likely be removed in an upcoming release. If you want to continue to use it then that is something for you to decide.

As for the issues you're seeing with `zonedSchedule()`, no one else has reported an issue with this before so I suggest you analyse your code more deeply to see where the issue lies. If there's a bug with the plugin around this then it should be easily reproducible and can be done so by providing a link to a repository with a minimal app. There's already an example app in this repository that doesn't exhibit the behaviour you've described

**Comment by MaikuB** [comment]
> Actually there is similar bug report #1293. 

That issue you mentioned didn't provide evidence of this though so may well have been an issue with their application logic. It should be easy enough to reproduce and I had even attempted to do so.

> I dont want to take your time but is this possible to also use schedule() method for whom choose local purpose beside zoneSchedule() in next release?

Not sure what exactly you're trying to ask here. If this is about the next release of your app then that is up to you. If you this about the next release of the plugin then similar comment applies. If a deprecated API gets removed but you still want to use it that you can look at using a fork. Factors like this are something you're meant to be considering when making use of dependencies. Open source software is typically provided as-is such that maintainers aren't obligated to provide support.

**Comment by habilgur** [comment]
You missunderstood me. Dont want to a support from maintainers of course:)  All i have to say is can it be possible to use both these mentioned methods in upcoming release of this flutter_local_notification package not mine next release:)
I'll close this issue. Thank you for your time again.

**Comment by Aziz-cs** [comment]
I have the same problem and did not find solution..
