### ISSUE TITLE
Cancel method

### ISSUE THREAD

**Issue by xarmatura** [MaikuB/flutter_local_notifications#1404]
@MaikuB Hi! Just want to ask you about local notifications.
cancel() method means that we delete notification and we need to reschedule it or I can cancel cancellation?

**Comment by MaikuB** [comment]
I don't know what you mean by "cancel cancellation" but `cancel()` also applies to notifications that have been scheduled. That is, if it's scheduled to be shown but hasn't yet. Calling `cancel()` would mean that notification will no longer be scheduled.  You can make use of the example app and tweak it to your needs to check the behaviour of the plugin in general

**Comment by xarmatura** [comment]
@MaikuB Sorry, the question was does the `cancel `method mean that the notification needs to be re-created or can it be restored?
