### ISSUE TITLE
Group Notification Android

### ISSUE THREAD

**Issue by yuriekabaguspratama** [MaikuB/flutter_local_notifications#1405]
**Describe the bug**

**To Reproduce**

1. create the first notification and do the group key set
2. make the next notification with the same group key

**Expected behavior**
there are two notification show in same group

**Result**

there are two notification show in separate

btw I am still using 4.0.1+2 version
and I try in android 11 OS

**Comment by MaikuB** [comment]
From what you've described, it sounds like you are missing the summary notification, which is required by Android and may mean you potentially need to look into how notifications work on Android.

Other sidenotes for future reference:
- Bug reports like this need a link to a minimal app that can reproduce the problem
- Please ensure you use recent versions for bug reports in the future. If you stick with an older version of a plugin, then it's up to you "support" it. I put "support" with quotes as open-source software is provided as-is as maintainers aren't required to provided fixes
