### ISSUE TITLE
[Feature request] show badge number

### ISSUE THREAD

**Issue by makstheimba** [MaikuB/flutter_local_notifications#1409]
According to this [guide](https://developer.android.com/training/notify-user/badges) we can call `setNumber` to set a custom number to be displayed for a notification. Is it possible to support this api from flutter side? In this package we already have `channelShowBadge` which is kinda only half of the badge story on Android :)

**Comment by MaikuB** [comment]
Please look at submitting a PR

**Comment by MaikuB** [comment]
Closing as #1637 has been merged
