### ISSUE TITLE
android 8 and above no notification sound

### ISSUE THREAD

**Issue by AhmedMorra1** [MaikuB/flutter_local_notifications#1410]
**Describe the bug**
Android 8 and above no notification sound. 

**To Reproduce**

1. use the following code as the notification service helper

**Expected behavior**
 Notification sound works perfect on iOS (emulator&device) and on android 7 (emulator&device) but not playing any sound on android 8+ (emulator android 11 & Samsung Galaxy A50 android 9 and 11) 

**Sample code to reproduce the problem**

```
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:rxdart/rxdart.dart';
import 'package:timezone/data/latest.dart' as tz;
import 'package:timezone/timezone.dart' as tz;
import 'package:flutter_native_timezone/flutter_native_timezone.dart';


class NotificationsHelper {

  NotificationsHelper._privateConstructor();
  static final NotificationsHelper instance = NotificationsHelper._privateConstructor();

  static final _notifications = FlutterLocalNotificationsPlugin();
  static final onNotifications = BehaviorSubject<String?>();

  static Future _notificationDetails() async {
    const sound = 'pristine.mp3';
    return  NotificationDetails(
      android: AndroidNotificationDetails(
        'c4',
        'channel 4',
        channelDescription: 'channel 4 description',
        importance: Importance.max,
        priority: Priority.high,
        playSound: true,
        enableVibration: true,
        sound: RawResourceAndroidNotificationSound(sound.split('.').first),
      ),
    );
  }

  static Future init({bool initScheduled = false}) async {

    const android = AndroidInitializationSettings('stackly_notification_icon');
    const iOS = IOSInitializationSettings();
    const settings = InitializationSettings(
      android: android,
      iOS: iOS,
    );
    await _notifications.initialize(settings,onSelectNotification: (payload)async{
      onNotifications.add(payload);
    });

    if (initScheduled) {
      tz.initializeTimeZones();
      final locationName = await FlutterNativeTimezone.getLocalTimezone();
      tz.setLocalLocation(tz.getLocation(locationName));
    }
  }

  static Future showNotifications({
    int id = 0,
    String? title,
    String? body,
    String? payload,
  }) async =>
      _notifications.show(
        id,
        title,
        body,
        await _notificationDetails(),
        payload: payload,
      );

  static Future showScheduledNotifications({
    int id = 0,
    String? title,
    String? body,
    String? payload,
    required DateTime servingTime,
  }) async =>
      _notifications.zonedSchedule(
        id,
        title,
        body,
        tz.TZDateTime.from(servingTime, tz.local),
        await _notificationDetails(),
        payload: payload,
        androidAllowWhileIdle: true,
        uiLocalNotificationDateInterpretation: UILocalNotificationDateInterpretation.absoluteTime,
      );

  static Future showDailyScheduledNotifications({
    int? id,
    String? title,
    String? body,
    String? payload,
    required DateTime servingTime,
  }) async =>
      _notifications.zonedSchedule(
        id!,
        title,
        body,
        _scheduleDaily(Time(servingTime.hour,servingTime.minute,servingTime.second)),
        await _notificationDetails(),
        payload: payload,
        androidAllowWhileIdle: true,
        uiLocalNotificationDateInterpretation: UILocalNotificationDateInterpretation.absoluteTime,
        matchDateTimeComponents: DateTimeComponents.time,
      );

  static tz.TZDateTime _scheduleDaily(Time time){
    final now = tz.TZDateTime.now(tz.local);
    final scheduledDate = tz.TZDateTime(
      tz.local,
      now.year,
      now.month,
      now.day,
      time.hour,
      time.minute,
      time.second,
    );

    return scheduledDate.isBefore(now)
        ? scheduledDate.add(Duration(days: 1))
        : scheduledDate;
  }

  static void cancel(int id) => _notifications.cancel(id);
  static void cancelAll() => _notifications.cancelAll();

}

```

Update: I tried using the example app, still no sound on android, iOS working fine

**Comment by MaikuB** [comment]
There are no known issues on this and this is a feature that has been around for a while. 

As you didn't provide a link to a minimal app that can reproduce the issue as requested in the bug report template, I can only guess what the your problem actually is and that is you included the extension of the sound file. If you look at the example app, it doesn't do any when it comes to any Android resources

**Comment by AhmedMorra1** [comment]
> There are no known issues on this and this is a feature that has been around for a while.
> 
> As you didn't provide a link to a minimal app that can reproduce the issue as requested in the bug report template, I can only guess what the your problem actually is and that is you included the extension of the sound file. If you look at the example app, it doesn't do any when it comes to any Android resources

here is an app example for you
https://github.com/AhmedMorra1/local_notifications_test

I hope there is a solution for this.
Thanks

**Comment by MaikuB** [comment]
> Update: I tried using the example app, still no sound on android

If that's the case then you may have an issue with your Android SDK installation or need to check the sound settings of the device you're using. This is something that is working fine for myself and many others so your problem would be environmental

**Comment by MaikuB** [comment]
> So when you use my example app in the emulator it plays sound?

Yes though I ran this in debug mode as you didn't mention anything about the mode you used to run the app

> Because I have a released version of another app with the same implementation on PlayStore and when people download it it doesn't play the sound on actual devices.

Go through the readme and ensure you have done the release build configuration

**Comment by AhmedMorra1** [comment]
I re-installed Android Studio and now it's working on the emulator and the released version on the PlayStore.
Thanks for pointing out that it's a development environment problem.
