### ISSUE TITLE
Linux: Upgrade to latest dbus version

### ISSUE THREAD

**Issue by 12people** [MaikuB/flutter_local_notifications#1411]
Right now, notifications use dbus ^0.5.0 on Linux, which has a different API from the latest ^0.6.0 versions (most recent version is 0.6.6).

That leads to conflicts with other Linux-centric libraries that can't be easily resolved.

It'd be great if the dbus dependency was upgraded to ^0.6.0, along with the minor API changes (using named parameters instead of positional ones) that go with such an upgrade.

**Comment by MaikuB** [comment]
It would be great if you could submit a PR. How about it?

**Comment by 12people** [comment]
Submitted: #1414

**Comment by MaikuB** [comment]
Closing this now as the changes have been published. Thanks for the PR :)
