### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference

### ISSUE THREAD

**Issue by Klingefjord** [MaikuB/flutter_local_notifications#1417]
I'm getting this error even with proguard set up according to the README.md:

android/app/proguard-rules.pro:
```
## Gson rules
# Gson uses generic type information stored in a class file when working with fields. Proguard
# removes such information by default, so configure it to keep all of it.
-keepattributes Signature

# For using GSON @Expose annotation
-keepattributes *Annotation*

# Gson specific classes
-dontwarn sun.misc.**
#-keep class com.google.gson.stream.** { *; }

# Prevent proguard from stripping interface information from TypeAdapter, TypeAdapterFactory,
# JsonSerializer, JsonDeserializer instances (so they can be used in @JsonAdapter)
-keep class * extends com.google.gson.TypeAdapter
-keep class * implements com.google.gson.TypeAdapterFactory
-keep class * implements com.google.gson.JsonSerializer
-keep class * implements com.google.gson.JsonDeserializer

# Prevent R8 from leaving Data object members always null
-keepclassmembers,allowobfuscation class * {
  @com.google.gson.annotations.SerializedName <fields>;
}
```

Specifically, this cast to Integer fails: https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/models/NotificationDetails.java#L234

When I'm debugging, it does seem like the only value not null in `platformChannelSpecifics` is `allowWhileIdle`

**Comment by Klingefjord** [comment]
Also, getting this in `debug` with proguard disabled

**Comment by Klingefjord** [comment]
This was solved by adding a default AndroidNotificationDetails for android: 

  final NotificationDetails _details = const NotificationDetails(
    iOS: IOSNotificationDetails(
      presentAlert: true,
      presentBadge: true,
      presentSound: true,
    ),
    android: AndroidNotificationDetails(
      'channel-potential',
      'channel-potential',
      styleInformation: DefaultStyleInformation(
        false,
        false,
      ),
    ),
  );

without the android property, the above error occurs

**Comment by lizhuoyuan** [comment]
Encountered the same problem, how can I solve it

**Comment by awaisabbasaa11** [comment]
This resolved my issue with the help of @lizhuoyuan answer, please note that the icon name might be different for you guys for me it was '@mipmap/ic_launcher', . To find the correct name please go to your AndroidManifest.xml and look in the application tag

AndroidNotificationDetails(
            channel.id,
            channel.name,
            channelDescription: channel.description,
            priority: Priority.high,
            setAsGroupSummary: group,
            importance: Importance.max,
            icon: '@mipmap/ic_launcher',
          ),

**Comment by lizhuoyuan** [comment]
> @lizhuoyuan where did you add `icon: "app_logo",` ? I added to `AndroidNotificationDetails` - ` icon: "assets/images/app_logo.png",` but throw the error `The resource assets/images/app_logo.png could not be found. Please make sure it has been added as a drawable resource to your Android head project.,`

```
const AndroidInitializationSettings initializationSettingsAndroid =
        AndroidInitializationSettings('@mipmap/ic_launcher');

    const InitializationSettings initializationSettings =
        InitializationSettings(android: initializationSettingsAndroid);
    flutterLocalNotificationsPlugin.initialize(
      initializationSettings,
...
```
