### ISSUE TITLE
[Question] Daily (every day) multiple notifications

### ISSUE THREAD

**Issue by dukaric1991** [MaikuB/flutter_local_notifications#1420]
If I understand correctly... If I want to have multiple notifications on a daily basis, let say every Monday, Tuesday and Wednesday (3 notifications at 1pm, 2pm, 3pm).

I need to call method flutterLocalNotificationsPlugin.zonedSchedule() (3 days x 3 notifications) 9 times everytime with different scheduledDate and different ID and channel ID right? And then I should get this notifications for lets say another year every monday tuesday and wednesday ?

**Comment by MaikuB** [comment]
You are right regarding the number of method calls and IDs. It's up to you if you want them to be associated with different channels. The notifications will continue to fire until your application requests for them to be cancelled
