### ISSUE TITLE
onSelectNotification is not called while app in foreground after closing and opening the app again

### ISSUE THREAD

**Issue by MohamadSobhy** [MaikuB/flutter_local_notifications#1426]
**Describe the bug**
I am using `flutter_local_notifications` plugin in my app to show notifications received from Firebase while app in foreground. Also I'm using `onSelectNotification` to handle clicks on notifications while the app is open and `getNotificationAppLaunchDetails` to handle the clicks of notifications if the app is opened from a notification. The package is working well with all the cases except only one case. 

**To Reproduce**
- Suppose that you received a notification while app in foreground.
- Press back button or remove the app from background.
- Reopen the app again normally from the app icon.
- Now press on the notification.

**Result**
Nothing happens and no logs appear in the **Debug Console** and `onSelectNotification` never be called.

**Expected behavior**
I expect `onSelectNotification` to be called to handle the notification action.

**Platform** 
I tested this on Android and haven't tested it on iOS because I don't have a Physical device so I don't know wether it happens in iOS or not.

**Is there any solution for this??**

**Flutter Doctor**
[flutter_doctor.log](https://github.com/MaikuB/flutter_local_notifications/files/7768564/flutter_doctor.log)

**Comment by MaikuB** [comment]
Can you please clarify more on what you mean by the second step as it sounds like both options can contradict each other.

Also have you tried reproducing this via the example app and if so, can you provide a recording?

**Comment by MohamadSobhy** [comment]
Hi, @MaikuB Thank you for your reply. I couldn't reproduce the issue with the example app so I revised all the steps on my app and found that the issue was that I was initializing the plugin inside the `onMessage` stream listener of Firebase instead of initializing it inside the `initState()`. So I moved the following code to the `initState()` method and the issue is fixed.

```dart
const initializationSettingsAndroid =
        AndroidInitializationSettings('app_icon');

    final initializationSettingsIOS = IOSInitializationSettings(
      onDidReceiveLocalNotification: (_, __, ___, ____) => Future.value(),
    );
    final initializationSettings = InitializationSettings(
      android: initializationSettingsAndroid,
      iOS: initializationSettingsIOS,
    );

    flutterLocalNotificationsPlugin.initialize(initializationSettings,
        onSelectNotification: _onLocalNotificationClicked);
```

Thank you.
