### ISSUE TITLE
Local notification sound not coming on Device like OnePlus 

### ISSUE THREAD

**Issue by parmarravi** [MaikuB/flutter_local_notifications#1427]
The example code works differently in native devices and Chinese devices.

The notification sound does not come in one plus 7T that is Android 30 also the notification UI does not come in front of the screen it directly falls in the notification tray. 
Only  show Grouped notification come above the screen while all other notification falls directly in the system tray  

While on a Device like Nokia 5.1 Plus Android 29 it works perfectly fine.

When  Disabling battery optimization Permission the sound comes. however, this only works for  InboxStyleInformation while for BigPictureStyleInformation the sound does not come, and also notification is not coming above the screen it falls in system tray

**Comment by parmarravi** [comment]
Add Disable battery optimization Permission to enable sound on Chinese android devices

**Comment by brams-9** [comment]
are you using the latest version yet?

**Comment by parmarravi** [comment]
yes

**Comment by MaikuB** [comment]
Differences in device behaviours are expected given various OEMs apply their own customisation. Nokia devices run stock Android so the have the expected default behaviour. If you've got inconsistent behaviours on same device then you'll need to check your code.

In all cases I've described above, these aren't issues to do with the plugin as it calls the appropriate Android APIs that are available. There's nothing the plugin can do with how different Android devices behave differently
