### ISSUE TITLE
Android files not compiling in latest Android Fox 

### ISSUE THREAD

**Issue by parmarravi** [MaikuB/flutter_local_notifications#1429]
In the latest Android studio fox, the lib is not able to compile It works perfectly fine in older android studio 

![image](https://user-images.githubusercontent.com/7616089/147528556-3874ea2a-c012-4a04-9f8c-f4832611bf5a.png)

**Comment by MaikuB** [comment]
This would be an issue you need to check on your environment. I'm running artic fox myself and don't have issues. Furthermore, there are pipelines that can build the example app that references this library. As far as I know, the IDE isn't really what is used to compile anyway It's the Android SDKs and build tools used behind that scenes that matter
