### ISSUE TITLE
Enable / Disable foreground notifications based on condition

### ISSUE THREAD

**Issue by SimonHausdorf** [MaikuB/flutter_local_notifications#1430]
I tried something like this in the on message listener on iOS:

```dart
    FirebaseMessaging.onMessage.listen((RemoteMessage message) async {
      if (message.data["should_show"] == "false") {
        FirebaseMessaging.instance.setForegroundNotificationPresentationOptions(
          alert: false,
          sound: false,
        );
      } else {
        FirebaseMessaging.instance.setForegroundNotificationPresentationOptions(
          alert: true,
          sound: true,
        );
      }
    }
```

But this doesn't seem to work. Is there any way to conditionally show or not show notifications?

**Comment by MaikuB** [comment]
No there isn't for this plugin. Note though that the code you have is not for this plugin but is the firebase_messaging plugin. It's repo is https://github.com/FirebaseExtended/flutterfire
