### ISSUE TITLE
onSelectNotification - problem

### ISSUE THREAD

**Issue by chan27-2** [MaikuB/flutter_local_notifications#1431]
Every notification is triggering the **onSelectNotification** function without even tapping the notification.
``` 
Future<void> showNotification(RemoteMessage message) async {
    
  final androidPlatformChannelSpecifics = AndroidNotificationDetails(
        "1",
        'channel 1',
        channelDescription: 'All notifications',
        importance: Importance.max,
        priority: Priority.high,
        groupAlertBehavior: GroupAlertBehavior.summary,
        largeIcon: const DrawableResourceAndroidBitmap("app_logo"),
      );

    const iOSPlatformChannelSpecifics = IOSNotificationDetails();

    final platformChannelSpecifics = NotificationDetails(
      android: androidPlatformChannelSpecifics,
      iOS: iOSPlatformChannelSpecifics,
    );

    flutterLocalNotificationsPlugin.show(
      "some unique id",
      "title",
      "body",
      platformChannelSpecifics,
      payload: "some payload",
    );
  }
```

**Comment by mehrdad-shokri** [comment]
@chan27-2 how did you solve it?

**Comment by chan27-2** [comment]
> 

check if you have fullScreenIntent: true in android notification detail. for me removing it solved the issue

**Comment by mehrdad-shokri** [comment]
@chan27-2 thanks man, documentation should have noted that but doesn't

**Comment by chan27-2** [comment]
> @chan27-2 thanks man, documentation should have noted that but doesn't

yeah, it should mention it, took a while to debug it

**Comment by MaikuB** [comment]
This behaviour is documented in the last paragraph of this section
https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#full-screen-intent-notifications. It is also mentioned in API docs for that specific flag https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/AndroidNotificationDetails/fullScreenIntent.html

Note that the code snippet in the original post had no mention of full screen intents either. If turning it off solves your issue then you may have potentially tried to enable something you didn't actually need or weren't aware of the consequences of enabling it. If so, in cases like this, you can run the example app to examine the behaviour.
