### ISSUE TITLE
[Feature Request] Getting Icon data in ActiveNotifications

### ISSUE THREAD

**Issue by thecodepapaya** [MaikuB/flutter_local_notifications#1432]
I have a messaging style notification where I need to append messages to a list of messages but I have no context about the messages which have already been shown using `.show()`.

I can get information about the active notifications using `getActiveNotifications()` but there is no information about the icons or other assets which were also used in those notifications. The `ActiveNotification` class does not provide any such information about the notification.

Is it possible to somehow get information about these additional details as well?

**Comment by MaikuB** [comment]
It's not supported. You could either look at using a fork and make modifications for your own purposes (note: potentially could submit a PR back to this repo too) or use the payload property to include custom data that is of interest to your use case. Based on what you described and how many notifications are generally managed, this is done by id. If you're calling `show()` then your own application could track what is shown by id with extra data you need in your own data store. Also should point out that `getActiveNotifications()` is only supported on Android 6.0 onwards so being reliant on that API won't work on older versions of Android

**Comment by kenguyenduc** [comment]
I did the following and it worked for me:

1. Create a transparent and white notification icon (you can use the following tool: AndroidAssetStudio )
Download the zip folder, unzip and you'll see it contains a res folder with different drawable folders. Copy and paste the contents of the res folder in "android\app\src\main\res" path
![image](https://user-images.githubusercontent.com/32872158/167284466-15ae1a45-f05c-452f-98d7-425af448d94d.png)

2. Then open the AndroidManifest.xml file and add the following lines to it:
ic_stat_calendar_today is the name of my notification icon. And each of the drawable folders that have been pasted contain a different size of icon with the same name.
![image](https://user-images.githubusercontent.com/32872158/167284479-dfc8ea5d-3c09-4252-8489-ecfd00107b6e.png)

3. If you want to change the color of the icon then check the above image. Add the metadata tag after the notification icon tag
4. Go to "android\app\src\main\res\values" and add a colors.xml file
![image](https://user-images.githubusercontent.com/32872158/167284498-7d0cf7c6-d7c3-4c5a-8a30-7e2fce6687f6.png)
<color name="colorAccent">#[your color]</color>

+++ AND if you use .show, you can add color in function:
_flutterLocalNotificationsPlugin.show(
        notification.hashCode,
        notification.title,
        notification.body,
        NotificationDetails(
          android: AndroidNotificationDetails(
            _channel.id,
            _channel.name,
            channelDescription: _channel.description,
            icon: 'app_icon',
            importance: Importance.max,
            priority: Priority.max,
            color: Color(0xFFBB2030),
          ),
        ),
        payload: jsonEncode(message.data),
      );

+++ References: https://github.com/flutter/flutter/issues/17941#issuecomment-622268132
