### ISSUE TITLE
Flutter Local Notifications not receiving when device reboots

### ISSUE THREAD

**Issue by Joel7jones** [MaikuB/flutter_local_notifications#1436]
Actually I have scheduled one alert at some custom time the alerts seems to be coming fine but when I restart my mobile alerts are not coming

**Comment by MaikuB** [comment]
Please try to use the example app to see if you can reproduce the issue first. If this behaviour is specific to Android, check that you have applied all of the Android-specific configuration, especially around release builds. You can cross-reference what you've done with the docs and example app

**Comment by MaikuB** [comment]
Closing due to lack of response and sufficient info to reproduce the reported issue
