### ISSUE TITLE
onSelectNotification payload is empty

### ISSUE THREAD

**Issue by yostrokon** [MaikuB/flutter_local_notifications#1439]
flutter_local_notifications: ^9.1.5
firebase_messaging: ^11.2.4

trying to get the payload from tapped notification, but getting empty string in callback
in onMessage listener this payload present.

please advise, what can i do to solve this issue?

**Comment by amrit-citrusleaf** [comment]
@yostrokon - how did you get it working? I am getting empty payload string.

**Comment by yostrokon** [comment]
@amrit-citrusleaf Was missed to pass payload from the message to the flutterLocalNotificationsPlugin.show in the stream listener
