### ISSUE TITLE
Schedule a recurring notification

### ISSUE THREAD

**Issue by Simpler1** [MaikuB/flutter_local_notifications#144]
Is it possible to schedule a notification and then have it repeat daily?

I'd like to specify a date for the initial notification and then repeat daily.
If the date is in the past, then the daily repeated notifications would start tomorrow.

Thanks.

**Comment by MaikuB** [comment]
There are functions like that that are covered in the readme

**Comment by Simpler1** [comment]
Hi Maiku,  I don't see anything in the readme like this.  I looked through the code for the `schedule` function and it doesn't have a way to enter a recurrence interval.

Am I missing something?

Thanks

**Comment by MaikuB** [comment]
Ah my bad, your case is a bit different than the daily example. No it's not possible as from what I recall iOS doesn't support this (note that in trying to support the old and new notification APIs on iOS). Would take a PR if I've missed something and someone is able to get it working on all platforms.

**Comment by hemangjoshi37a** [comment]
> Hi Maiku, I don't see anything in the readme like this. I looked through the code for the `schedule` function and it doesn't have a way to enter a recurrence interval.
> 
> `showDailyAtTime` doesn't allow for specifying a date to start.
> 
> Am I missing something?
> 
> Thanks

Perhaps you can set a timer to trigger first notification which is repeated afterwards.

**Comment by MaikuB** [comment]
Going to close this as this something that can done unless it's possible to get headless execution working to know when a notification has been shown. Alternative is to use platform channels to implement logic that's specific to your app
