### ISSUE TITLE
[Question] canceling background notifications

### ISSUE THREAD

**Issue by marcoberetta96** [MaikuB/flutter_local_notifications#1444]
Hi. I'm using this simple piece of code to retrieve all **active notifications** and to **delete** the ones with "TEST" as title.

```
List<ActiveNotification> activeNotifications = await flutterLocalNotificationsPlugin.resolvePlatformSpecificImplementation<AndroidFlutterLocalNotificationsPlugin>()?.getActiveNotifications() ?? [];
activeNotifications.forEach((notification) {
  if (notification.title == "TEST") flutterLocalNotificationsPlugin.cancel(notification.id);
});
```

This is working fine when the notification are generated with `flutterLocalNotificationsPlugin.show(...)` when the app is active.
When the app is not active, the notifications have 0 as id and they cannot be removed. There's no error, just the `cancel` method is not working.

So, I have 3 questions:

1. the 0 as id is the correct behaviour?
2. there's a way to remove all the notifications with "TEST" as title?
3. this way of canceling notifications can be implemented for iOS too?

Thanks

**Comment by MaikuB** [comment]
>1. the 0 as id is the correct behaviour?

The plugin is reporting the correct IDs. If you don't where the IDs are coming from then I believe you'll need to get deeper understanding of your application.  If you are only using this plugin, then the IDs reported would've been what you provided to the plugin's APIs. I suspect you've left out some key details where you most likely are using Firebase Cloud Messaging

> 2. there's a way to remove all the notifications with "TEST" as title?
> 3. this way of canceling notifications can be implemented for iOS too?

None of the native notification APIs provide a way to manage notifications by content like the title. The ID is the unique identifier so you'd need to track them or query notifications like you're already doing

**Comment by marcoberetta96** [comment]
Hi @MaikuB and thanks for your answer.
I'm using Firebase Cloud Messaging. The notification id is set locally (not from server), so I need to understand why the firebase package set it to 0. Is this right? Thanks again.
