### ISSUE TITLE
Unable to use latest version, getting dbus error inside flutter_local_notifications_linux

### ISSUE THREAD

**Issue by roshan9419** [MaikuB/flutter_local_notifications#1445]
I'm using this latest version:
`flutter_local_notifications: ^9.2.0`

Here is the pubspec.lock file:

> flutter_local_notifications:
    dependency: "direct main"
    description:
      name: flutter_local_notifications
      url: "https://pub.dartlang.org"
    source: hosted
    version: "9.2.0"

> flutter_local_notifications_linux:
    dependency: transitive
    description:
      name: flutter_local_notifications_linux
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.4.1+1"

After running the app, I'm getting the following error:

![image](https://user-images.githubusercontent.com/53408220/148540958-7cec2a0a-7438-4e6f-beda-1f29ccc6d315.png)
![image](https://user-images.githubusercontent.com/53408220/148541139-f5ac64e9-0f20-4949-8fd3-5d1110815788.png)

I'm able to use this package on this specific version:
`flutter_local_notifications: ^9.1.4`
but not on any higher versions.

I have cleared the cache also, but it didn't resolve.

System
> Windows
> Flutter 2.5.3
> Dart 2.14.4

**Comment by MaikuB** [comment]
This looks like it's specific to your dev environment so you would need to look into it further. Not something I've been able to reproduce and it passes CI. Furthermore, there's been no other reports on this

**Comment by roshan9419** [comment]
Yeah, it's working on the latest Flutter 2.8.1. The error is gone after I have upgraded. Thanks!
