### ISSUE TITLE
NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()'

### ISSUE THREAD

**Issue by alexursul** [MaikuB/flutter_local_notifications#1446]
Hi. Got this error from crashylytics, version 10.0.0-dev.2

`Caused by java.lang.NullPointerException
Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification (FlutterLocalNotificationsPlugin.java:327)
com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification (FlutterLocalNotificationsPlugin.java)
com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver.onReceive (ScheduledNotificationReceiver.java:76)
android.app.ActivityThread.handleReceiver (ActivityThread.java:3846)
android.app.ActivityThread.access$1500 (ActivityThread.java:224)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1898)
android.os.Handler.dispatchMessage (Handler.java:107)
android.os.Looper.loop (Looper.java:223)
android.app.ActivityThread.main (ActivityThread.java:7562)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:539)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:950)`

**Comment by MaikuB** [comment]
Would you be able to provide a link to a repository with a minimal app that can reproduce the issue? This looks strange given there's a null check done at https://github.com/MaikuB/flutter_local_notifications/blob/569df7eea26216dd0826aec48d0b7ba55e59e43c/flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java#L325 and is around code that hasn't existed for a long time without changes done to it

**Comment by alexursul** [comment]
I did nothing special, just updated the plugin of my large working app to version 10 (yes, dev version, but I really needed notification actions), and this error fell in. There are a huge number of errors, but not a single user has complained yet, and 100% of errors occur in the background.

![error](https://user-images.githubusercontent.com/1566690/148679247-ec8d12c0-c7ad-4372-ab69-4159755be75c.png)

I can send the plugin initialization code, but there is absolutely nothing unusual about it.

```
    _flutterLocalNotificationsPlugin = FlutterLocalNotificationsPlugin();
    const initializationSettingsAndroid = AndroidInitializationSettings('app_icon');
    final initializationSettingsIOS = DarwinInitializationSettings(
      onDidReceiveLocalNotification: (int id, String? title, String? body, String? payload) =>
          _processClickOnNotification(payload),
      notificationCategories: <DarwinNotificationCategory>[
        DarwinNotificationCategory(
          'plainCategory',
          actions: <DarwinNotificationAction>[
            DarwinNotificationAction.plain('complete', tr('complete')),
            DarwinNotificationAction.plain(
              'hide',
              tr('hide'),
              options: <DarwinNotificationActionOption>{
                DarwinNotificationActionOption.destructive,
              },
            ),
          ],
          options: <DarwinNotificationCategoryOption>{
            DarwinNotificationCategoryOption.hiddenPreviewShowTitle,
          },
        )
      ],
    );
    final initializationSettings = InitializationSettings(
      android: initializationSettingsAndroid,
      iOS: initializationSettingsIOS,
    );
    await _flutterLocalNotificationsPlugin?.initialize(
      initializationSettings,
      onSelectNotification: _processClickOnNotification,
      onSelectNotificationAction: backgroundHandler,
    );
```

**Comment by MaikuB** [comment]
Thanks for the reply, what does the code for your notifications look like and are you scheduling notifications with actions?

**Comment by alexursul** [comment]
I hope it will be understandable from the pieces of code.

```   
NotificationDetails _getNotificationDetails({String? icon, Color? color}) {
  return NotificationDetails(
    android: AndroidNotificationDetails(
      'CHANNEL_NAME (replaced)',
      'APP_NAME (replaced)',
      importance: Importance.max,
      priority: Priority.max,
      showWhen: true,
      enableVibration: true,
      enableLights: true,
      playSound: AdvancedSettings.notificationSound != 'no',
      color: color,
      largeIcon: icon != null ? DrawableResourceAndroidBitmap(icon) : null,
      visibility: NotificationVisibility.public,
      sound: AdvancedSettings.notificationSound != 'no'
          ? RawResourceAndroidNotificationSound(AdvancedSettings.notificationSound)
          : null,
      actions: [
        AndroidNotificationAction(
          'complete',
          tr('complete'),
        ),
        AndroidNotificationAction(
          'hide',
          tr('hide'),
        ),
      ],
    ),
    iOS: const DarwinNotificationDetails(),
  );
}

// ---

final tz.TZDateTime local = tz.TZDateTime.from(showTime.toLocal(), tz.local);
_flutterLocalNotificationsPlugin!.zonedSchedule(
  scheduleId,
  title,
  body,
  local,
  _getNotificationDetails(icon: 'icon_${task.image}'),
  payload: task.id.toString() + '|' + date.toIso8601String(),
  androidAllowWhileIdle: true,
  uiLocalNotificationDateInterpretation: UILocalNotificationDateInterpretation.absoluteTime,
);

// ---

static backgroundHandler(NotificationActionDetails details) async {
  AdvancedSettings.shared = await SharedPreferences.getInstance();
  await AdvancedSettings.loadExtendedSettings();

  try {
    await notificationHelper.init();
    await _flutterLocalNotificationsPlugin!.cancel(details.id);
  } catch (e) {
    DebugHelper.log(e.toString());
  }

  // some code ... 

  return true;
}
```

**Comment by MaikuB** [comment]
I've not been able to reproduce this using similar code via example app.

Have you been able to reproduce this using your own app via debug and/or release build? The latter (release build) is more important. If you have been able to reproduce the issue, can you see if it can be reproduced with a release build of the example app on the same device with tweaks done to the app so that it can schedule a notification with actions?

**Comment by alexursul** [comment]
I will try to catch and reproduce the error and post it here.
