### ISSUE TITLE
Issue when run the application on Android 12 pixel 4a

### ISSUE THREAD

**Issue by jeniscodesmith** [MaikuB/flutter_local_notifications#1447]
**Bug**
when I run app on android 12 version phone its throw an error which I defined below. 

**CONSOLE ERROR**
adb: failed to install D:\CodeSmith\Flutter Projects\home_xp\build\app\outputs\flutter-apk\app.apk: Failure [INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl1863689627.tmp/base.apk (at Binary XML file line #206): **com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver:** Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present]
Error launching application on Pixel 4a. 

**I have defined this in my androidmanifest.XML**
```
  <service
           android:name="com.dexterous.flutterlocalnotifications.ForegroundService"
           android:exported="false"
           android:stopWithTask="false"/>


```

**Comment by MaikuB** [comment]
What version of the plugin are you using? Please make sure you are on recent version of the plugins prior to reporting a bug. 9.0.0 addressed compatibility issues with Android 12 and the error you reported is what happened with older versions of the plugin

**Comment by elenacrst** [comment]
@MaikuB  https://medium.com/tech-takeaways/migrating-my-app-to-android-12-7bafba3ed999 please see this article. There are some changes required in order to support API 31 / Android 12. I have the same issue.
I hope flutter_local_notifications will have an update soon for this

**Comment by MaikuB** [comment]
Closing due to lack of response and the plugin has already done the appropriate changes required for Android 12 a while. Issue is likely due to using an old version of the plugin

**Comment by aminbbb92** [comment]
on android 12 you should change AndroidManifest intent
"You uploaded an APK or Android App Bundle which has an activity, activity alias, service or broadcast receiver with intent filter, but without 'android:exported' property set. This file can't be installed on Android 12 or higher. See: developer.android.com/about/versions/12/behavior-changes-12#exported"


 <application>
      <receiver android:name="com.dexterous.flutterlocalnotifications.ActionBroadcastReceiver" />
        <receiver android:exported="true" android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver" />
        <receiver android:exported="true" android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"/>
                <action android:name="android.intent.action.MY_PACKAGE_REPLACED"/>
                <action android:name="android.intent.action.QUICKBOOT_POWERON" />
                <action android:name="com.htc.intent.action.QUICKBOOT_POWERON"/>
            </intent-filter>
        </receiver>
    </application>

**Comment by aminbbb92** [comment]
` <application>
      <receiver android:name="com.dexterous.flutterlocalnotifications.ActionBroadcastReceiver" />
        <receiver android:exported="false" android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver" />
        <receiver android:exported="false" android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"/>
                <action android:name="android.intent.action.MY_PACKAGE_REPLACED"/>
                <action android:name="android.intent.action.QUICKBOOT_POWERON" />
                <action android:name="com.htc.intent.action.QUICKBOOT_POWERON"/>
            </intent-filter>
        </receiver>
    </application>`
