### ISSUE TITLE
Unresolved package dexterous

### ISSUE THREAD

**Issue by chaitanyabhardwaj** [MaikuB/flutter_local_notifications#145]
### **Android Integration**

The following lines in AndroidManifest.xml file gives the error - _Unresolved package dexterous_

    <receiver android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver">
        <intent-filter>
            <action android:name="android.intent.action.BOOT_COMPLETED"/>
         </intent-filter>
    </receiver>

I've added the dependencies in the pubspec.yaml file
`flutter_local_notifications: ^0.4.2+1`
The flutter notifications plugin is working as expected except the missing `com.dexterous` package which I suppose should have been included in the plugin.

**Comment by icavanaugh95** [comment]
Mine does say the same thing however everything worked even after rebooting so I just ignored it.  I never had any issues with it.

**Comment by anoop4real** [comment]
@chaitanyabhardwaj  did you manage to fix this?

**Comment by Azazel17** [comment]
I have the same exact problem

**Comment by chaitanyabhardwaj** [comment]
Unfortunately it never worked. Plus Flutter has many other ['Gradle Bugs' ](https://github.com/flutter/flutter/issues/25734) so I finally switched back to Java
