### ISSUE TITLE
Notifications not firing under Android 11

### ISSUE THREAD

**Issue by Xango** [MaikuB/flutter_local_notifications#1450]
**Describe the bug**

- I have setup the app as described in the Readme. 
- Under IOS the notifications are firing but under Android 11 they are not. To make sure the error does not lie with me I downloaded the example project and built it.
- I ran it on two separate devices:
    - IPhone SE (IOS 15.2)
    - Android Pixel 4 (Android 11)

Notifications are being fired for IOS but not for the Android device. This is true for my personal code as well as the example app provided in this repo. This is true when the app is in the foreground and background.

I tested both on simulators.

**To Reproduce**

1. Download the example project from this repo
2. Add all packages 
3. Boot two different simulators, one for IOS and one for Android.
4. Build the project
5. Once the project has built on both devices press the following button: "Schedule notification to appear in 5 seconds"

**Expected behavior**
- When pressing the button mentioned above I would expect a notification to appear when the app is in the foreground or background.
- Notifications should appear in both IOS and Android.

**Sample code to reproduce the problem**
https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications/example

**Comment by mohammedsalem97** [comment]
is there any solution found for this problem in Android 11 ? @Xango

**Comment by arslandevcrew** [comment]
I have same issue in android 11,  I want to show downloading progress bar in notification bar flutter
