### ISSUE TITLE
HTML Text is not showing in the samsung devices.

### ISSUE THREAD

**Issue by AhemadAbbasVagh** [MaikuB/flutter_local_notifications#1452]
I tried to add HTML text for title and body with BigTextStyleInformation to display notification and for all the android devices, it's working as expected but when I use same code for the samsung devices then It's showing as a normal text even if I add HTML text in it.

**Comment by MaikuB** [comment]
Each Android OEM applies their own customisations to Android so would most likely the case here where Samsung has applied their own look and feel and the notifications behave as expected on other devices. Furthermore, the plugin is calling the appropriate APIs so there isn't anything else it can do
