### ISSUE TITLE
not able to specify a handler for backgroundHandler when initializing notification.

### ISSUE THREAD

**Issue by Itiode** [MaikuB/flutter_local_notifications#1454]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Sample code to reproduce the problem**

**Comment by MaikuB** [comment]
A bug is to do with an provided functionality not behaving as expected and what you've described doesn't fit this category. If there's a feature missing that you'd fine useful then submit a PR back as this is open-source. It's already documented how you can deal with when a notification has been tapped on when the application is killed
