### ISSUE TITLE
Can i make a http request with periodicallyShow local notification?

### ISSUE THREAD

**Issue by ABmamunHoneybee** [MaikuB/flutter_local_notifications#1458]
import 'dart:convert';

import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:http/http.dart' as http;
import 'package:timezone/timezone.dart' as tz;
import 'package:timezone/data/latest.dart' as tz;

import '../constants.dart';

class NotificationService {
  String lastMessage = "Hi this is last messages.";
  static final NotificationService _notificationService =
      NotificationService._internal();

  factory NotificationService() {
    return _notificationService;
  }

  final FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
      FlutterLocalNotificationsPlugin();

  NotificationService._internal();
  loadJson(int index) async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    var uid = prefs.getString("uid");
    var url = Uri.parse('$serverUrl/notification/notification.php');
    var request = http.MultipartRequest('POST', url);
    request.fields['uid'] = uid;
    var res = await request.send();
    res.stream.transform(utf8.decoder).listen((value) async {
      print(json.decode(value));
      lastMessage = json.decode(value)[index]["message"];
    });
  }

  showScheduledNotification() async {
    await loadJson(0).then((value) {
      print(value);
      return showNotification(0, "Support 365", lastMessage, 1);
    });
    initNotification();
  }

  Future<void> initNotification() async {
    const AndroidInitializationSettings initializationSettingsAndroid =
        AndroidInitializationSettings('@drawable/ic_stat_contact_support');

    const IOSInitializationSettings initializationSettingsIOS =
        IOSInitializationSettings(
      requestAlertPermission: false,
      requestBadgePermission: false,
      requestSoundPermission: false,
    );

    const InitializationSettings initializationSettings =
        InitializationSettings(
            android: initializationSettingsAndroid,
            iOS: initializationSettingsIOS);

    await flutterLocalNotificationsPlugin.initialize(initializationSettings);
  }

  Future<void> showNotification(
      int id, String title, String body, int seconds) async {
    var interval = RepeatInterval.everyMinute;
    await flutterLocalNotificationsPlugin.periodicallyShow(
      id,
      title,
      body,
      interval,
      const NotificationDetails(
        android: AndroidNotificationDetails(
            'main_channel', 'Main Channel', 'Main channel notifications',
            importance: Importance.max,
            priority: Priority.max,
            icon: '@drawable/ic_stat_contact_support'),
        iOS: IOSNotificationDetails(
          sound: 'default.wav',
          presentAlert: true,
          presentBadge: true,
          presentSound: true,
        ),
      ),
      androidAllowWhileIdle: true,
    );
  }

  Future<void> cancelAllNotifications() async {
    await flutterLocalNotificationsPlugin.cancelAll();
  }
}

**Comment by MaikuB** [comment]
Nope
