### ISSUE TITLE
java.lang.NoSuchFieldException: Drawable

### ISSUE THREAD

**Issue by Stnieder** [MaikuB/flutter_local_notifications#146]
I am running my app and it is working just fine. But when I try to create a notification it throws me this error: 

```
[ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(40)] java.lang.AssertionError: java.lang.NoSuchFieldException: Drawable
E/flutter (16179):      at com.c.a.b.a.n$a.<init>(Unknown Source:87)
E/flutter (16179):      at com.c.a.b.a.n$24.a(Unknown Source:29)
E/flutter (16179):      at com.c.a.f.a(Unknown Source:74)
E/flutter (16179):      at com.c.a.b.a.i.a(Unknown Source:42)
E/flutter (16179):      at com.c.a.b.a.i.a(Unknown Source:125)
E/flutter (16179):      at com.c.a.b.a.i.a(Unknown Source:22)
E/flutter (16179):      at com.c.a.f.a(Unknown Source:74)
E/flutter (16179):      at com.c.a.f.a(Unknown Source:4)
E/flutter (16179):      at com.c.a.f.a(Unknown Source:8)
E/flutter (16179):      at com.c.a.f.a(Unknown Source:5)
E/flutter (16179):      at com.c.a.f.a(Unknown Source:13)
E/flutter (16179):      at com.dexterous.flutterlocalnotifications.b.a(Unknown Source:4)
E/flutter (16179):      at com.dexterous.flutterlocalnotifications.b.c(Unknown Source:23)
E/flutter (16179):      at com.dexterous.flutterlocalnotifications.b.onMethodCall(Unknown Source:121)
E/flutter (16179):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(Unknown Source:17)
E/flutter (16179):      at io.flutter.view.FlutterNativeView$PlatformMessageHandlerImpl.handlePlatformMessage(Unknown Source:32)
E/flutter (16179):      at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:6)
E/flutter (16179):      at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (16179):      at android.os.MessageQueue.next(MessageQueue.java:325)
E/flutter (16179):      at android.os.Looper.loop(Looper.java:142)
E/flutter (16179):      at android.app.ActivityThread.main(ActivityThread.java:6494)
E/flutter (16179):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter (16179):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/flutter (16179):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
E/flutter (16179): Caused by: java.lang.NoSuchFieldException: Drawable
E/flutter (16179):      at java.lang.Class.getField(Class.java:1601)
E/flutter (16179):      at com.c.a.b.a.n$a.<init>(Unknown Source:34)
E/flutter (16179):      ... 23 more
```

**EDIT**: 
I've found out that error is throwing at the initialization of the notifications, that look like this:
```
var initializeAndroid = new AndroidInitializationSettings('@drawable/logo_transparent');
      var initializeIOS = new IOSInitializationSettings();
      var initializeSettings = new InitializationSettings(initializeAndroid, initializeIOS);
      flutterLocalNotifications.initialize(
        initializeSettings,
        onSelectNotification: onSelectNotification
      );
```
and the drawable folder where I store the image called logo_transparent looks like this:
![bildschirmfoto von 2018-12-27 17-11-54](https://user-images.githubusercontent.com/33837785/50486576-e8940700-09fa-11e9-877f-37132fbc11e9.png)

**FURTHER EDIT**:
I have changed `@drawable/logo_transparent` to `@drawable/logo_transparent.png` and only then it throws me an error, that the image was not found.

**Comment by MaikuB** [comment]
You shouldn't be passing in @drawable as part of specifying the icon to use. There's an example app that you should probably use to take a closer look if you haven't done so already

**Comment by Stnieder** [comment]
Thanks that worked for me

**Comment by anoop4real** [comment]
I am getting "The resource ic_launcher could not be found. Please make sure it has been added as a drawable resource to your Android head project." I am uasing the default value 

`  FlutterLocalNotificationsPlugin initializeNotifications() {

    var initializationSettingsAndroid = AndroidInitializationSettings('ic_launcher');
    var initializationSettingsIOS = IOSInitializationSettings();
    var initializationSettings = InitializationSettings(
        initializationSettingsAndroid, initializationSettingsIOS);
    _flutterLocalNotificationsPlugin = FlutterLocalNotificationsPlugin();
    _flutterLocalNotificationsPlugin.initialize(initializationSettings).then((value) => _showDailyAtTime());

    return _flutterLocalNotificationsPlugin;
  }`

I tried this `var initializationSettingsAndroid = AndroidInitializationSettings('@mipmap/ic_launcher');` didnt work

**Comment by MaikuB** [comment]
@anoop4real 

1. does the file exist for your app?
2. can you reproduce this using the example app? You'll need to clone/download the repository and run it on the same device

**Comment by anoop4real** [comment]
@MaikuB Thanks for quick reply, 

1. Yes the file exists in my app
2. I will check

I am confused with one step, I am wondering whether it has to do with progruard config.... I am not quite good at this, I couldnt even find that file...do I need to create this manually?
In iOS, its working super smooth, I just need to fix this in ANdroid so that I can release my app :)

**Comment by MaikuB** [comment]
You may need to create it manually if it doesn't exist. Newer versions of the Flutter SDK generate one now. A reminder though that using an Android drawable resource is the official recommendation. That using the launcher icon works is something reported by the community though I did also check the example app. There are direct links to the configuration files for the example app in the readme itself in case you have missed that

**Comment by anoop4real** [comment]
Ok... after some trials finally managed to fix it... the main issue was that I had the minifiedEnabled in debug also as cloudstore plugin demanded it and I was adding the proguard config only in release.... after adding proguard to both release and debug... the issue gone

**Comment by jamesdixon** [comment]
In case anyone else runs into this, for me it was not including the proguard rules as shown here: https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/example/android/app/proguard-rules.pro
