### ISSUE TITLE
IOS NotificationAppLaunchDetails when app is terminated

### ISSUE THREAD

**Issue by dimitristoz** [MaikuB/flutter_local_notifications#1461]
Hello, I am trying to redirect a user to a specific flutter page when opens the application, which is terminated, from a scheduled notification but I am not able to do it.

This notification has been scheduled in the background while the application was terminated via firebaseMessaging at the background messages handler. Is this viable to be done, or I am missing something?

**Comment by MaikuB** [comment]
This had been demonstrated in the example app so I would think that if you're having trouble with this that you'll need to look further into it too see what's going on
