### ISSUE TITLE
Notification are scheduled successfully but not showing up.

### ISSUE THREAD

**Issue by SalishKumar** [MaikuB/flutter_local_notifications#1462]
I am using zoned schedule, when I am scheduling the notification for multiple days , like today is Monday and scheduled notification for Monday and Tuesday. Notification work perfectly on Monday but on Tuesday they don't show up.

 await flutterLocalNotificationsPlugin
              .zonedSchedule(
                  count,
             "Reminder ${reminderClass.id}",
                  reminderClass.sendTextMessage
                      ? reminderClass.setupSounds[iteratorForSOund]
                      : "",
                  scheduledDate,
                  platform,
                  androidAllowWhileIdle: true,
                  uiLocalNotificationDateInterpretation:
                      UILocalNotificationDateInterpretation.absoluteTime,
                  matchDateTimeComponents: DateTimeComponents.dayOfWeekAndTime)
              .then((value) => print(
                  "sucess ${scheduledDate.hour} ${scheduledDate.minute} ${scheduledDate.second} day =  ${scheduledDate.day} ${count} ${reminderClass.setupSounds[iteratorForSOund]}"))
              .onError((error, stackTrace) =>
                  print("**error : " + error.toString()));

**Comment by MaikuB** [comment]
Your description and code snippet doesn't indicate much. If you have issues with your app then you'll need to make use of community sites to get assistance in debugging your app etc. If there's an issue with the plugin itself that you'd like to report then please use the bug report template and provide a link to a minimal app that can reproduce the issue. This could be by including a link to a fork of this repo where the example app has been modified to demonstrate the issue. This should also include details of the platforms the bug occurs on and the details of the timezone

**Comment by SalishKumar** [comment]
@MaikuB  i produced the issue on the sample app 

steps
1. Change the date to Sunday 9:59 am
2. set notification for "weekly Monday at 10:00:00 am my time zone"
3. Change date to Monday 9:59:50 am
4. wait for 10 seconds 
5. Notification will not show up

Refer video for better understanding 
https://drive.google.com/file/d/1YySQrH4SpblIH77lqz_LO4y4yCZSvsz8/view?usp=sharing

**Comment by MaikuB** [comment]
Changing the time manually isn't the same way as the scenarioa you're talking about and if that how you had tested then that would explain why you would've run into the issue. You need to wait for the actual time to pass as it is not meant to deal with manual time changes

**Comment by SalishKumar** [comment]
@MaikuB manual time change was for a quick demo, I have tested my own app properly will check the demo app too and let you know

**Comment by MaikuB** [comment]
Closing this due to lack of response. If you run into a problem please open a new issue using the bug report template and provide all of these details mentioned there

**Comment by WahdanZ** [comment]
@MaikuB  i have the same issue event and notification never fired 
```dart 
await flutterLocalNotificationsPlugin.zonedSchedule(
Random().nextInt(10000),
'scheduled title',
'scheduled body',
tz.TZDateTime.now(tz.local).add(const Duration(seconds: 5)),
const NotificationDetails(
    android: AndroidNotificationDetails(
        'your channel id', 'your channel name',
        channelDescription: 'your channel description')),
androidAllowWhileIdle: true,
uiLocalNotificationDateInterpretation:
    UILocalNotificationDateInterpretation.absoluteTime);
```
