### ISSUE TITLE
Big Image in Notification not showing in some devices like Vivo

### ISSUE THREAD

**Issue by ibrahimrehman1** [MaikuB/flutter_local_notifications#1466]
I have implemented **local notifications** in my app using this plugin. The problem is that in most devices the **big picture** in the notification is displaying properly but in some devices, it is not displaying at all. Only the **title and body** are displayed.

Does anyone have any fix for this?

![WhatsApp Image 2022-02-04 at 2 59 37 PM](https://user-images.githubusercontent.com/63722045/152524122-2cb9c149-d0b0-46d7-9ee3-5416207cf6de.jpeg)

**Comment by MaikuB** [comment]
The plugin calls the appropriate APIs so there's no fix for this. Various manufacturers implement their own version of Android so you'll get different behaviour amongst the various Android devices.  Not familiar with Vivo but you might want to see if those devices have setting that controls this. If there is, note that such settings are specific to those devices as they have customised Android so won't be part of the standard Android OS that there are APIs to access them
