### ISSUE TITLE
Schedule notifications on Android with Cron

### ISSUE THREAD

**Issue by Th2y** [MaikuB/flutter_local_notifications#1467]
Notifications scheduled for times when the app is closed do not work

```
Cron().schedule(Schedule.parse('1 1 * * *'), () async {
      await fltrNotification.show(
          0,
          "exemple",
          generalNotificationDetails,
          payload: "Task");
});
```

When the app is open, it works perfectly, but if it closes, no notification arrives (tests on Android)

**Comment by MaikuB** [comment]
This isn't an issue with this plugin. You'll need to look into what you're using for cron jobs
