### ISSUE TITLE
Can't set null payload

### ISSUE THREAD

**Issue by sanekyy** [MaikuB/flutter_local_notifications#1469]
**Describe the bug**
You can't show null payload and then receive null payload in `NotificationAppLaunchDetails`.

**To Reproduce**
1. Show notification with null payload
2. Close app and click on notification
3. call `getNotificationAppLaunchDetails`
4. `NotificationAppLaunchDetails.payload` will be not null but empty string. (Notification `payload` and `NotificationAppLaunchDetails.payload` marked as nullable)

**Expected behavior**
write null, read null

**Comment:**
I think that this bug due to this line of code: 

https://github.com/MaikuB/flutter_local_notifications/blob/8aae2df48e6cae601cb712d1f9d18b9191cd5116/flutter_local_notifications/lib/src/platform_flutter_local_notifications.dart#L322

**Comment by MaikuB** [comment]
Thanks for the reminder. This is something that should be documented. A null payload can't be set because it would actually cause a crash on older versions of iOS
