### ISSUE TITLE
Just a question: custom scheduling 

### ISSUE THREAD

**Issue by SlimenTN** [MaikuB/flutter_local_notifications#147]
I'm working on an app that works like a reminder for some events, those events are repetitive each one for a specific time.
ex: event that happens every 10th of each month, or event that happens every year
so I wanted to know how to schedule such events, I just set the start date and reiteration times (2 months, 6 months, 2 years, etc..) and then schedule notifications for them.

**Comment by MaikuB** [comment]
It's not possible. Not sure if what you're after is the same as https://github.com/MaikuB/flutter_local_notifications/issues/92. Your scenario seems very app specific and probably better if you looked at using platform channels https://flutter.io/docs/development/platform-integration/platform-channels

**Comment by SlimenTN** [comment]
Thanks for your quick answer.
just wondering even if I use platform channel and build a java code for this one, wouldn't be a pain for the phone to schdule all theses notifications infinitely ? not to mention that we can have hundreds of events.

**Comment by SlimenTN** [comment]
or maybe adding `onSwipeToDissmiss` feature :) so I can set a callback that schedule a new notification for this event, because I can use `onSelectNotification` but the user can swipe it without pressing it.

**Comment by MaikuB** [comment]
I'm not sure where you're getting at with your question as this plugin uses platform channels too

**Comment by MaikuB** [comment]
Regarding swipe to dismiss, there's already an existing issue that has been raised 
https://github.com/MaikuB/flutter_local_notifications/issues/74

Unless I'm mistaken sounds like both things you're asking about are duplicates

**Comment by SlimenTN** [comment]
yes I know and I hope you add it soon.
Thanks again for your help 😄
