### ISSUE TITLE
Does the IANA time zone database need to be constantly updated?

### ISSUE THREAD

**Issue by eczkgn** [MaikuB/flutter_local_notifications#1470]
If IANA time zone database is old, does it cause false notification? Do you need to follow the updates constantly? And I could not find detailed information about the update.

**Comment by MaikuB** [comment]
This plugin passes the timezone apps specify to the underlying platform so updates to said timezones would be managed by the platform.  Therefore, there shouldn't be any need for the plugin or apps to maintain an updated database. This is why you won't find any mention about updating the timezone information. If your question is based on how you found that the plugin depends on https://pub.dev/packages/timezone as a dependency, then that's only so it can leverage the [TZDateTime](https://pub.dev/documentation/timezone/latest/timezone.standalone/TZDateTime-class.html) class. This reduces the need for the plugin to have it's own version. As it's maintained by someone who appears to work at Google, chances are those who need to build apps that need to take timezones into account would more likely use it too
