### ISSUE TITLE
The notification icon is not output together.

### ISSUE THREAD

**Issue by donghakIpixel** [MaikuB/flutter_local_notifications#1474]
**Bug Description**
I downloaded the example and ran it as it is, but even if I press all the buttons, the app icon with title and body is not displayed.

**To duplicate**
1. Download the sample, build it, and run it.
2. Click the illustrative buttons to check the operation.

**Expected movement**
When receiving a local notification from Android, the icon specified by the user is displayed in a certain space on the left along with the content of Title and Body.

**Sample code to reproduce the question*
You have used the sample folder in your current storage as it is.

// current
![Screenshot_20220209-183045](https://user-images.githubusercontent.com/86765016/153315762-872246b8-126b-4c90-a2b6-3e9aef06ff45.jpg)

// want
![스크린샷 2022-02-10 오전 9 52 46](https://user-images.githubusercontent.com/86765016/153315949-717bd30e-7a64-4b09-99b9-0b538022e2dc.png)

------------------------------------------------------------------------------------------
 [✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-x64, locale ko-KR)
    • Flutter version 2.8.1 at /Users/donghak/fvm/versions/2.8.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (8week ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/donghak/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/donghak/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.64.1)
    • VS Code at /Applications/Visual Studio

**Comment by MaikuB** [comment]
What device did you use? Have you tried other devices and emulators, especially those with stock Android OS? I don't have this issue myself and this is the first time someone has mentioned this. I would this is a limitation of your device as different Android manufacturers will customise their version of Android will behave

**Comment by donghakIpixel** [comment]
Thank you for your answer.

The device I used is the Galaxy S9+. As you said, I changed the model and tested it, and I think Title and Body are printed well with the icon (Galaxy Note 20 Ultra).

It's strange that it comes out like this depending on the year or model of release, but is there any way for the user to set it up separately?

**Comment by MaikuB** [comment]
That would be something you would need to research on as Android devices will vary and that's something not related to the notification APIs or this plugin. I may be the maintainer of this plugin, it doesn't mean I have access to all devices and know about how a lot the devices work. With this in mind, closing this as there's no issue with the plugin

**Comment by donghakIpixel** [comment]
Yes, thank you for answering!
