### ISSUE TITLE
Not found: 'dart:ffi'

### ISSUE THREAD

**Issue by sergeyxo** [MaikuB/flutter_local_notifications#1479]
Target dart2js failed: Exception:
/c:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-9.3.0/lib/src/platform_specifics/android/notification_details.dart:1:8:
Error: Not found: 'dart:ffi'
import 'dart:ffi';

Flutter (Channel beta, 2.10.0-0.3.pre, on Microsoft Windows [Version 10.0.19043.1526], locale ru-RU)
    • Flutter version 2.10.0-0.3.pre at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fdd0af78bb (2 weeks ago), 2022-01-25 22:01:33 -0600
    • Engine revision 5ac30ef0c7
    • Dart version 2.16.0 (build 2.16.0-134.5.beta)
    • DevTools version 2.9.2

and  also in stable channel

How to fix?

**Comment by MaikuB** [comment]
That import isn't used so  whilst it can be removed from the plugin. Curious though, what platform were you target when you tried to build the app that ran into this issue?

**Comment by sergeyxo** [comment]
build for web
debug and stable
flutter_local_notifications - not used in project

**Comment by MaikuB** [comment]
Yep noticed the dart2js reference after I posted. This should now be fixed in 9.3.1. Thanks for reporting this

**Comment by sergeyxo** [comment]
Thank you!
