### ISSUE TITLE
Timer in notification

### ISSUE THREAD

**Issue by Tichz** [MaikuB/flutter_local_notifications#1486]
Can I with this package leave a timer running on the notification like the android's native timer?
And when accessing the notification, open the app at the time set in the notification timer?

**Comment by MaikuB** [comment]
I don't know what exactly what you mean but if you want to see what the plugin can do then please clone the repo and run the example app as it covers all the functionality that the plugin has to offer

**Comment by mubasshir** [comment]
@Tichz were able to achieve it?
