### ISSUE TITLE
pass array of strings instead of single payload string

### ISSUE THREAD

**Issue by mohamed6996** [MaikuB/flutter_local_notifications#149]
when onSelectNotification is triggered, i wanna go to a new page using Navigator.push and i wanna pass multiple arguments through the constructor of the new page.
for example 
```
Future onSelectNotification(String payload) async {
    await Navigator.push(
        context,
        new MaterialPageRoute(
            builder: (context) => CommitmentPage(
                biteName,
                biteId,
                skillID,
                commitmentId,
                userId,
                )));
  }
```

how can i do that?

**Comment by MaikuB** [comment]
you could pass JSON as the payload instead of a simple string then deserialise it to get what you need

**Comment by mohamed6996** [comment]
Great, i was thinking of that (: 
I have another question. in the first page i initialize the plugin and set the timer ...etc 
but i need an instance of the plugin in the second page also. i have a button in the second page so that the user can cancel the notification. what will happen if i create a new instance of it in the second page and call cancel(id)? is it different from the one i created in the first page and the notification wont be canceled ?

**Comment by MaikuB** [comment]
an id is a unique identifier for a notification so the fact that you called it from another page shouldn't change its behaviour. you may need to consider just creating the plugin once as well in some way e.g. a global variable. i've not tried creating another instance but if it works it should still behave as expected and is something that you should be able to confirm in your own app
