### ISSUE TITLE
flutter_local_notifications_linux debus version 0.6.0 is incompatible with 0.7.0 pacakges

### ISSUE THREAD

**Issue by guyluz11** [MaikuB/flutter_local_notifications#1491]
Currently our `dbus` version on flutter_local_notifications_linux is `^0.6.0` and the last available is `0.7.1`.

I am getting `incompatible` errors when updating another package named `connectivity_plus` since it uses newer version of dbus `0.7.0`

```
Because no versions of flutter_local_notifications match >9.3.2 <10.0.0 and flutter_local_notifications 9.3.2 depends on flutter_local_notifications_linux ^0.4.1, flutter_local_notifications ^9.3.2 requires flutter_local_notifications_linux ^0.4.1.
And because flutter_local_notifications_linux >=0.4.0 depends on dbus ^0.6.0 and nm >=0.5.0 depends on dbus ^0.7.0, flutter_local_notifications ^9.3.2 is incompatible with nm >=0.5.0.
And because connectivity_plus >=2.2.1 depends on connectivity_plus_linux ^1.3.0 which depends on nm ^0.5.0, flutter_local_notifications ^9.3.2 is incompatible with connectivity_plus >=2.2.1.
So, because cybear_jinni depends on both connectivity_plus ^2.2.1 and flutter_local_notifications ^9.3.2, version solving failed.
pub get failed (1; So, because cybear_jinni depends on both connectivity_plus ^2.2.1 and flutter_local_notifications ^9.3.2, version solving failed.)
```

Let's update dbus version to the last available one.

**Comment by dpedrinha** [comment]
I'm having the same problem. Need to update nm to the latest version for compatibility with connectivity_plus.

**Comment by MaikuB** [comment]
Thanks for reporting and for PR. FYI this will likely keep happening until dbus reaches 1.0+. Similar issue can occur with other packages like rxdart that haven't gone to 1.0. In cases like this and in case you're not aware, [dependency overrides](https://dart.dev/tools/pub/dependencies#dependency-overrides) can be used so you can specify the version to use in your own app. Provided there aren't breaking changes then that can will get around the version conflict issue

**Comment by MaikuB** [comment]
This has been merged and released now as a minor change to the linux plugin. This should mean that due to how caret versioning works that running `flutter pub upgrade` should pick up the new version
