### ISSUE TITLE
Scheduling notification - dynamically change body and title

### ISSUE THREAD

**Issue by ChrisZi** [MaikuB/flutter_local_notifications#1493]
Is there a way for the scheduling notification to contain changing content e.g.  taken from the database?

Currently, in the zonedSchedule method, the body and title are set immediately, and whether it would be possible to set them right before the notification is displayed, which would allow the display of different content. Or is it possible to set a schedule for calling a method that will trigger notifications with contents that will be set dynamically?

**Comment by MaikuB** [comment]
No it isn't possible. This isn't something that native notification APIs provide

**Comment by ChrisZi** [comment]
Thank you for your response.
