### ISSUE TITLE
Notifications on Harmony OS not reliable

### ISSUE THREAD

**Issue by rubenaster** [MaikuB/flutter_local_notifications#1494]
**Describe the bug**
A user with a Huawei device and Harmony OS 2 most of the time doesn't get scheduled notifications in the background. Often times she gets all notifications at once when she opens the app.

Did anybody encountered similar problems?

**To Reproduce**
1. Schedule several notifications on app start
2. Close app and wait until all notifications should have been triggered
3. Open the app again and see that all notifications are triggered at once

**Expected behavior**
Notifications should be triggered at the specific, scheduled time.

**Comment by MaikuB** [comment]
This isn't to do with the plugin and has been documented in the readme. See https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#scheduled-android-notifications. If you've missed this then may want to take a closer look at the readme to see if there's anything else important that you've been missed.

Will close this as it's to do with the OS
