### ISSUE TITLE
Support for UNNotificationContent.interruptionLevel on iOS

### ISSUE THREAD

**Issue by maprohu** [MaikuB/flutter_local_notifications#1495]
Hello,

I was trying to see if I could send "time sensitive" and "critical" notifications on iOS using this plugin, but I did not find a way.

I understand that this should be controlled by `UNNotificationContent.interruptionLevel` as described here: https://developer.apple.com/documentation/usernotifications/unnotificationinterruptionlevel

And here:
https://developer.apple.com/design/human-interface-guidelines/ios/system-capabilities/notifications#helping-people-manage-notifications

Can you please confirm that this feature is indeed not implemented? If so, could I help with implementing it?

Great job on the plugin by the way, thank you! 

Cheers,
Marton

**Comment by MaikuB** [comment]
It's not implemented and was requested before in https://github.com/MaikuB/flutter_local_notifications/issues/1374 with no response when I asked about submitting a PR. So yes you can help implement it and I can see you've opened a PR already :)

Will check it out when I get the chance to
