### ISSUE TITLE
Playstore Crashes & ANRs ( ANR details Broadcast of Intent { act=android.intent.action.MY_PACKAGE_REPLACED } )

### ISSUE THREAD

**Issue by siraj-logicvalley** [MaikuB/flutter_local_notifications#1503]
Broadcast of Intent { act=android.intent.action.MY_PACKAGE_REPLACED flg=0x4000010 pkg=com.xxx.yyy cmp=com.xxx.yyy/com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver (has extras) }, InvisibleToUser

**Comment by MaikuB** [comment]
Please use the bug report template and provide the information mentioned in that template. What you've provided is insufficient
