### ISSUE TITLE
[Feature request] A callback when the app is not launch and user receive a schedule notification

### ISSUE THREAD

**Issue by EArminjon** [MaikuB/flutter_local_notifications#1505]
**Describe the bug**

**FEATURE REQUEST**

**To Reproduce**

We would create an alarm. With your plugin we well schedule notification and when user click on it, it well open our app and launch a musique / web radio.
Is it possible to automatise this process and run a callback when user receive a scheduled notification and app is closed ?

**Expected behavior**

We would produce a classic alarm system, working even phone is shutdown or app closed.

**Sample code to reproduce the problem**

**Comment by MaikuB** [comment]
If you need to handle doing something when the app is launched then you need to use the mechanisms that already are provided by the plugin to do this that is shown in the example app as well. As far as I know, there is no other way to do this and the FCM plugin doesn't support this either and has a similar mechanism for dealing with notifications that launch the app
