### ISSUE TITLE
[version 10.*] Bug when tapping on notification

### ISSUE THREAD

**Issue by marcoberetta96** [MaikuB/flutter_local_notifications#1506]
**Describe the bug**
App crashes when tapping on a notification generated from Firebase.
Everything worked fine with version 9.* of this package.

**To Reproduce**
Just click on an app notification.

**Expected behaviour**
Just do not crash.

**Log**
```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[3]'
*** First throw call stack:
(0x18208f05c 0x19a5a9f54 0x182198538 0x1821a36b4 0x18204c474 0x18206ae1c 0x103fd53fc 0...)
libc++abi: terminating with uncaught exception of type NSException
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00000001b897d9c4 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`__pthread_kill:
->  0x1b897d9c4 <+8>:  b.lo   0x1b897d9e4               ; <+40>
    0x1b897d9c8 <+12>: pacibsp
    0x1b897d9cc <+16>: stp    x29, x30, [sp, #-0x10]!
    0x1b897d9d0 <+20>: mov    x29, sp
Target 0: (Runner) stopped.
```

  
Problem was highlighted here.

<img width="1164" alt="image" src="https://user-images.githubusercontent.com/11749393/155846627-90c996be-98ed-4436-9db7-44f0e6368b12.png">

Then, I noticed that `response.notification.request.content.userInfo[@"payload"]` was null (which is fine when my notification comes from Firebase) so I replaced it with an empty string.

Then, an other problem did arise because of `callback information could not be retrieved` and the `abort()` call, so I commented the abort line and now everything works fine (as in v9.* versioni of this package).

Finally, my 2 questions:

- can you add a null check on `response.notification.request.content.userInfo[@"payload"]` to avoid an app crash?
- can you remove the `abort()` call and just do nothing if a callback is not provided?

Thanks

**Comment by MaikuB** [comment]
Thanks for reporting this, actually the issue lies elsewhere and the plugin shouldn't have allowed executing the logic you mentioned. I have a branch with a fix for this at https://github.com/MaikuB/flutter_local_notifications/tree/didReceiveResponseFix. Would you be able to help test to confirm the fix works by updating your app to use a [Git dependency](https://dart.dev/tools/pub/dependencies#git-packages)? Your pubspec.yaml file should look like

```yaml
flutter_local_notifications:
    git:
        url: https://github.com/MaikuB/flutter_local_notifications.git
        path: flutter_local_notifications
        ref: didReceiveResponseFix
```

**Comment by marcoberetta96** [comment]
Tested.
I confirm the branch works fine.
Thanks!

**Comment by MaikuB** [comment]
Thanks for confirming, will merge it in and release an update soon
