### ISSUE TITLE
Canceling notifications

### ISSUE THREAD

**Issue by marcoberetta96** [MaikuB/flutter_local_notifications#1508]
**Describe the bug**
Canceling notifications works only for notifications generated from this package.
If the notification comes from Firebase, this package correctly reports it in the active notifications list with its id, but when using the `cancel` method the notification is not canceled. No error is shown.

**To Reproduce**
Send an FCM notification using a custom server and set a specific NotificationId.
Use the `getActiveNotifications` and `cancel` method of this package to find and cancel the notification.
Notification is reported with its id but it is not going to be canceled.

**Expected behaviour**
The notification should be canceled.
Since it is correctly found by this package I think it should be canceled without problem.

Am I missing something or there's something I can debug more to investigate the problem?
Thanks

**Comment by MaikuB** [comment]
A couple of questions on this

- What did you see be reported?
- What platform(s) did you try to cancel notifications on

You may need to check how the FCM plugin creates the notifications. Last I remember, on Android it was creating notifications using a combination of ID and tag, both of which are used to uniquely identify notifications but FCM used `0` as the id value. To cancel these, you need to specify both the id and tag

**Comment by marcoberetta96** [comment]
> * What did you see be reported?

Nothing. This plugin seems to correctly cancel the notification, but the notification remains visible.

> * What platform(s) did you try to cancel notifications on

On iOS. Not tested (yet) on Android.

> You may need to check how the FCM plugin creates the notifications.

From my backend, an FCM is sent. I set a field `NotificationId` which is used from the firebase plugin to set the notification ID on the App. Your plugin finds the notification (among the active notifications) with the id I set from my backend, but when I try to cancel it the notification remains visible and no error is triggered.

The only thing I noticed is that when the notification is from FCM, the id used is a String (not int as when generated from this package), so I added a cast in the active notifications method. I also tried to use both the id and String id in the native code of this package to cancel the notification, but nothing happens.

I would like to debug more the situation, but I don't know where/what to look further.

**Comment by MaikuB** [comment]
> The only thing I noticed is that when the notification is from FCM, the id used is a String (not int as when generated from this package), so I added a cast in the active notifications method. I also tried to use both the id and String id in the native code of this package to cancel the notification, but nothing happens.

In that case you most likely need to have your own code to handle this situation then. The plugin isn't necessarily going to solve all scenarios and is working as intended with how it was designed. It uses an integer to make the plugin more easier to use from a cross-platform perspective given the main id on Android is an integer. You'd also find a lot of other libraries outside of Flutter ecosystem that follow a similar approach

**Comment by marcoberetta96** [comment]
I agree. The id was a string because of a constraint on my server side.
For testing purpose, I tried to send an FCM notification from another server using an int value as notification ID.
Unfortunately the issue is still the same: the notification is found in the active notifications list with the id I set from server side, but when I try to cancel it the notification does not disappear and no error is triggered.
Is something more I can debug?

**Comment by MaikuB** [comment]
Not something I can help you further on and this may be something you need to dig into further on your own for your particular use case The code this plugin and FCM are open-source for you to use to debug too. In case it wasn't clear what I meant in my previous response too, what I meant is you may need to have your own code using platform channels that will invoke Swift/Objective-C code to cancel notifications.
