### ISSUE TITLE
flutter_local_notifications/README.md is not in alignment with official Dart coding standards

### ISSUE THREAD

**Issue by banderberg** [MaikuB/flutter_local_notifications#1511]
In particular, the section "Scheduling a notification" claims that one need not take a direct dependency on the 'timezone' package.  This however does not agree with the "depend_on_referenced_packages" standard set by the Dart Team.

https://dart-lang.github.io/linter/lints/depend_on_referenced_packages.html

Following the README, a developer using the Dart linter will get a warning that won't go away unless they take a direct dependency on the 'timezone' package.

I'm happy to submit a PR with an update to the README.

**Comment by MaikuB** [comment]
Thanks for raising this and would be happy to take a PR.
