### ISSUE TITLE
android: add tag to getActiveNotifications

### ISSUE THREAD

**Issue by emersion** [MaikuB/flutter_local_notifications#1512]
It would be handy to get back the notification tag in `getActiveNotifications`. Is this something Android APIs would be able to support?

Related: https://github.com/MaikuB/flutter_local_notifications/issues/1162

**Comment by emersion** [comment]
Sounds like it's possible: https://developer.android.com/reference/android/service/notification/StatusBarNotification#getTag()

Would that be a welcome contribution?

**Comment by MaikuB** [comment]
Yep PRs are welcome. If this isn't a breaking change then the PR can be based on master. If however, it is a breaking change please use the 10.0.0 as the target as there's currently a prerelease
