### ISSUE TITLE
Show Notification on Boot Completed 

### ISSUE THREAD

**Issue by zogol** [MaikuB/flutter_local_notifications#1514]
Thanks first of all for the great package. You have already thought of very many cases.
A useful extension would be to display a notification right after the device starts.
Preferably with the possibility to execute code. Which should be no problem with the startForeground feature

**Comment by MaikuB** [comment]
Thanks for the compliments. Regarding your use case and viewing it from a general perspective, what you're describing relates more to application lifecycle on wanting to run some logic upon a reboot. This is different from what the purpose of this plugin is about and that is to be able to have an interface written in Dart that can invoke native notification APIs. As such your use case is much more narrow and more specific to your app that you should be prepared to include your custom logic and libraries such as these. Furthermore, I believe what you're after is only possible on Android that you would require you to implement this logic yourself via Java/Kotlin. As such I'll be closing this issue
