### ISSUE TITLE
[Feature Request] Is it possible to know which occurrence of a recurring notification was selected?

### ISSUE THREAD

**Issue by jjoelson** [MaikuB/flutter_local_notifications#1515]
Both `NotificationAppLaunchDetails` and the `onSelectNotification` callback only provide the payload that is given to `zonedSchedule`. That means if it is a recurring notification (i.e. uses `matchDateTimeComponents`) then it seems there is no way to determine which occurrence was selected. 

On iOS, `UNNotification` has a [`date`](https://developer.apple.com/documentation/usernotifications/unnotification/1649326-date) property that represents the delivery date of the notification; this is easily accessible in `UNUserNotificationCenterDelegate`'s `didReceiveNotificationResponse` method.

I am not an Android developer, but from looking through the code it seems it should be possible to record the time at which each notification is delivered.

Is there a reason that the notification delivery date could not be included in the `onSelectNotification` callback and in `NotificationAppLaunchDetails`? Would a PR for such an enhancement be welcome?

**Comment by MaikuB** [comment]
It wasn't implemented as back when this plugin targeted Android and iOS, only iOS had this. I didn't see a use case for it either and plugin has been available for quite a long time that from memory, you're the first to raise this.  In your case, what would an app do upon knowing the date? PRs would be welcome but note that the plugin also supports macOS and Linux and what you mentioned with iOS is using the user notifications framework that is applicable to iOS 10+ and this plugin currently supports iOS version older than 10

**Comment by jjoelson** [comment]
Hi Michael! Thanks for the background info. The basic use case is that I have a reminder app that supports recurring reminders, and if a user wants to complete an occurrence of that reminder by tapping on a notification then I would need to know _which_ notification they tapped on.

But even with the delivery date, there would need to be some fuzzy date math to determine which notification corresponds to which reminder occurrence, so maybe it doesn't make sense as a general feature for this package, especially if it's never been requested before.
