### ISSUE TITLE
Change AudioAttributes to the notifications in android 

### ISSUE THREAD

**Issue by bornold** [MaikuB/flutter_local_notifications#1519]
Hello @MaikuB 👋 
First of all, thank you so much for the plugin! Huge fan!

Have a use case where we would like to change [AudioAttributes](https://developer.android.com/reference/android/media/AudioAttributes) for the notifications here: https://github.com/MaikuB/flutter_local_notifications/blob/2c0b2db29fef939f1355cd708f8c5fee73deed22/flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java#L953

Specifically to `AudioAttributes.USAGE_ALARM`

We are maintaining a fork so there is no problem for us just change the attribute, but I was wondering if there would be any interest in adding this to [AndroidNotificationDetails](https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/lib/src/platform_specifics/android/notification_details.dart)?

If so, I would be happy to write a PR

**Comment by MaikuB** [comment]
A PR would be welcome but would like know what the thought would be on how users of the plugin specify the attribute? If you're looking to expand this then I suspect it makes  sense to allow any of the allowed attribute values to be specified then for backwards compatibility, assume the default value is `AudioAttributes.USAGE_NOTIFICATION`

**Comment by bornold** [comment]
Cool!
Yes, the user will specify the attribute in [AndroidNotificationDetails](https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/lib/src/platform_specifics/android/notification_details.dart)
as a [enum](https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/lib/src/platform_specifics/android/enums.dart) that defaults to `AudioAttributes.USAGE_NOTIFICATION`.

Even though it does not really make any sense to specify some of the attributes available in [`AudioAttributes.Builder.setUsage` ](https://developer.android.com/reference/android/media/AudioAttributes.Builder#setUsage(int)) for a notification I believe it's best to include them all.


Guess I'll start working on a PR that in the coming weeks branching of [10.0.0](https://github.com/MaikuB/flutter_local_notifications/tree/10.0.0)?

**Comment by MaikuB** [comment]
This sounds like something that wouldn't be a breaking change so if that's the case, it could use master as the target branch so that this goes out in a 9.x release
