### ISSUE TITLE
Installing dev v 10 build 11

### ISSUE THREAD

**Issue by webuijorgeGL** [MaikuB/flutter_local_notifications#1520]
Because flutter_local_notifications >=10.0.0-dev.11 depends on flutter_local_notifications_platform_interface ^6.0.0-dev.3 which doesn't match any versions, flutter_local_notifications >=10.0.0-dev.11 is forbidden.
So, because pine depends on flutter_local_notifications ^10.0.0-dev.11, version solving failed.

The target does not exist.

**Comment by MaikuB** [comment]
Hmm could've sworn I published it but anyway it should be fixed now. Thanks!

**Comment by webuijorgeGL** [comment]
Ty
