### ISSUE TITLE
MissingPluginException in action callback on android

### ISSUE THREAD

**Issue by FallenRiteMonk** [MaikuB/flutter_local_notifications#1523]
**Describe the bug**
Accessing shared_preferences in action callback (onSelectNotificationAction) results in `MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)` on android. [I have not tested on any other platform]

**To Reproduce**
In the example app of the 10.0.0 branch, add `await SharedPreferences.getInstance();` in the 'notificationTapBackground' method (also make it async) before the 'IsolateNameServer.lookupPortByName' call. [Sample code can be found bellow]

Launch the app (debug mode) on an android device or emulator. Tab the button 'Show notification with plain actions' and click any of the three actions in the notification, which will throw the error `MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)`

**Expected behavior**
According to the readme 
```
...
Accessing plugins will work; however in particular on Android there is no access to the Activity context which means some plugins (like url_launcher) will require additional flags to start the main Activity again.
...
```
it should be possible to use possible to access plugins.

Is this some kind of special case or am I doing something wrong?

**Sample code to reproduce the problem**
```
void notificationTapBackground(NotificationActionDetails details) async {
  // ignore: avoid_print
  print('notification(${details.id}) action tapped: ${details.actionId} with'
      ' payload: ${details.payload}');
  if (details.input?.isNotEmpty ?? false) {
    // ignore: avoid_print
    print('notification action tapped with input: ${details.input}');
  }

  await SharedPreferences.getInstance();

  final SendPort? send = IsolateNameServer.lookupPortByName(portName);
  send?.send(details);
}
```

**Comment by MaikuB** [comment]
The issue you've linked to indicates it's an issue with another plugin not this one so will close this

**Comment by FallenRiteMonk** [comment]
Thanks for the feedback
