### ISSUE TITLE
QQ: Release date for version 10

### ISSUE THREAD

**Issue by webuijorgeGL** [MaikuB/flutter_local_notifications#1531]
Hi. Do you have planning a release date for the new version 10?

**Comment by MaikuB** [comment]
There is none as this is more of a community project, not a vendor offering. It was mentioned at https://github.com/MaikuB/flutter_local_notifications/issues/17#issuecomment-1061502547 that there's remaining work to be fine and asked community to help. Only one person had answered the call but they have had a change in priorities so won't come back it assist until later.
