### ISSUE TITLE
Attempt to invoke virtual method 'java.io.Serializable android.content.Intent.getSerializableExtra(java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by seonwoonam** [MaikuB/flutter_local_notifications#1533]
Hello, My firebase crashlytics dashboard shows the below error on some devices. I tried to create a situation where the error occurs, but I couldn't. Do you know why this error occurs or does anyone else get same error?

error log : 

Fatal Exception: java.lang.RuntimeException
Unable to start service com.dexterous.flutterlocalnotifications.ForegroundService@97c1e8a with null: java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.Serializable android.content.Intent.getSerializableExtra(java.lang.String)' on a null object reference

Caused by java.lang.NullPointerException
Attempt to invoke virtual method 'java.io.Serializable android.content.Intent.getSerializableExtra(java.lang.String)' on a null object reference

code : 
```
@Override
  public int onStartCommand(Intent intent, int flags, int startId) {
    ForegroundServiceStartParameter parameter =
        (ForegroundServiceStartParameter)
            intent.getSerializableExtra(ForegroundServiceStartParameter.EXTRA);
    Notification notification =
        FlutterLocalNotificationsPlugin.createNotification(this, parameter.notificationData);
    if (parameter.foregroundServiceTypes != null
        && Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
      startForeground(
          parameter.notificationData.id,
          notification,
          orCombineFlags(parameter.foregroundServiceTypes));
    } else {
      startForeground(parameter.notificationData.id, notification);
    }
    return parameter.startMode;
  }
```

**Comment by MaikuB** [comment]
Have you done all of this? https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#release-build-configuration

My guess is it's because you haven't and this is release build specific. If that's the case and you've been trying with a debug build then that would be why you can't reproduce it

**Comment by seonwoonam** [comment]
I found the solution of this issue.
This issue was caused by START_STICKY option.
https://developer.android.com/reference/android/app/Service#START_STICKY

So I changed this option to START_NOT_STICKY or START_REDELIVER_INTENT
