### ISSUE TITLE
Property to open app when press an action in notification

### ISSUE THREAD

**Issue by webuijorgeGL** [MaikuB/flutter_local_notifications#1538]
When the notification has actions for iOS exist a property to open the app to the foreground

`DarwinNotificationActionOption.foreground,`

But Android does not have a property to do this in a specific action.

**Comment by MaikuB** [comment]
Aware of this one already. This was covered in https://github.com/MaikuB/flutter_local_notifications/issues/17#issue-316443725 so i'll be closing it as there's an open issue to do with actions. Should note that PRs are welcome
