### ISSUE TITLE
Notification Icon color differences in different devices android

### ISSUE THREAD

**Issue by Nishtha-Iwebservices** [MaikuB/flutter_local_notifications#1540]
**To Reproduce**
The issue is If we put Notification white Icon with transparent background under Androidmanifest.xml and also in AndroidNotificationDetails with color property Getting different Icon behaviour on android 11 and 12.

**Expected behavior**
It is expected to be same on different devices.

**Sample code to reproduce the problem**
In AndroidManifest.xml
    
 meta-data
           android:name="com.google.firebase.messaging.default_notification_icon" 
            android:resource="@drawable/ic_stat_jobpool" 

In FirebasePushNotification Class
AndroidNotificationDetails(
        androidNotificationChannel.id ,
        androidNotificationChannel.name,
        icon: '@drawable/ic_stat_jobpool',
      color: HexColor('#00C7EE'),
    );

![android11](https://user-images.githubusercontent.com/88364538/160088238-2ff80513-2a6a-464d-b27b-d1299549958d.png)
On android11 it is giving forground color to icon 

![android12](https://user-images.githubusercontent.com/88364538/160088505-ad6a6255-273b-447e-8645-cbeab820a539.png)
on android 12 Background color with white icon.

Please help me to out.
Tried almost everything from stackOverflow and github but nothing works.

      <meta-data-->
                       android:name="com.google.firebase.messaging.default_notification_color"
                       android:resource="@color/colorPrimary" />
                     
Even the above default notification color is not working.

**Comment by MaikuB** [comment]
This isn't an issue to do with the plugin and you've not provided any evidence that it is to do with the plugin so will be closing the issue. Furthermore part of what you provided is to do with firebase, not this plugin. If you're going to open a bug report, then the template has specified that you should provide a minimum app that can reproduce the issue and this should be isolated to the plugin to prove that it is to do with this plugin. This is to help ensure that a maintainer's time and the time of others in the community looking into issues is widely spent. I should also point out that devices behaving differently can be expected
