### ISSUE TITLE
Heads-up notifications not working on Android 7

### ISSUE THREAD

**Issue by davebound** [MaikuB/flutter_local_notifications#1542]
I'm using the following to produce a heads-up notif upon receipt of a Firebase FCM message.
This works on Android 8, but on Android 7 I just get a sound, but no popup

Notif channels were introduced in Android 8 and on Android 8 it is essential to create a channel because the default channel does not allow heads up notifs. 

My question is, what should I do in android 7 to enabkle heads up notifs given that there is no support for notif channels?

Many thanks

```
Future<void> _createAndroidNotifChannel() async {
  if (glog) gl.i('$runtimeType._createAndroidNotifChannel()');
  final plugin = _flnPlugin.resolvePlatformSpecificImplementation<AndroidFlutterLocalNotificationsPlugin>();
  await plugin?.createNotificationChannel(_mychan);
  if (glog) gl.o();
}

const AndroidNotificationChannel _mychan = AndroidNotificationChannel(
  //
  // id - must match value in AndroidManifest.xml: see DCB_NOTE_NOTIF_CHAN
  'mychan',

  // title
  'High Importance Notifications',

  // others
  description: 'This channel is used for important notifications.',
  importance: Importance.max /*high*/ /*max*/,
  playSound: true,
);

void _showLocalNotif(RemoteNotification notification, AndroidNotification android) {
  if (glog) gl.i('_showLocalNotif()');
  _flnPlugin.show(
    notification.hashCode, // id
    notification.title,
    notification.body,
    NotificationDetails(
      android: AndroidNotificationDetails(
        _mychan.id,
        _mychan.name,
        channelDescription: _mychan.description,
        color: Colors.blue,
        playSound: true,
        icon: '@mipmap/ic_launcher',
        importance: Importance.max,
        priority: Priority.high,
      ),
    ),
  );
  if (glog) gl.o();
}
```

**Comment by MaikuB** [comment]
Please refer to the Android docs https://developer.android.com/guide/topics/ui/notifiers/notifications#Heads-up. You can also use the example app in the repository and I've seen heads-up notifications appear on emulators for older devices using the app

**Comment by MaikuB** [comment]
Closing as this has been answered. If you believe there's a bug, please use the bug report template and provide all of the requested information
