### ISSUE TITLE
flutter local notification not works properly when the app is terminated

### ISSUE THREAD

**Issue by Saikiran24** [MaikuB/flutter_local_notifications#1545]
**Describe the bug**
[flutter local notification not works properly when the app is terminated](https://stackoverflow.com/questions/70747915/flutter-local-notification-not-works-properly-when-the-app-is-terminated)
**To Reproduce**

**Expected behavior**

**Sample code to reproduce the problem**

**Comment by MaikuB** [comment]
This isn't a bug and you haven't filled in the bug report template properly. Please take a closer look at the docs that mention how to handle this

https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#initialisation
https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#getting-details-on-if-the-app-was-launched-via-a-notification-created-by-this-plugin

There's an example app too and this is mentioned in the bug report template to try to minimise "invalid" bug reports from being filed. Closing as this is to do with a gap in your implementation
