### ISSUE TITLE
NotificationAppLaunchDetails payload is always Null

### ISSUE THREAD

**Issue by abbiyuarsyah** [MaikuB/flutter_local_notifications#1546]
I have a problem with NotificationAppLaunchDetails payload, every time I tap the notification, the payload is always null.

I show the notification like this
  ```    
await flutterLocalNotificationsPlugin?.show(
      notificationModel.id,
      notificationModel.title,
      notificationModel.message,
      platformChannelSpecifics,
      payload: 'chat');
  ```    
    
 and get the payload like this:
```
final NotificationAppLaunchDetails? notificationAppLaunchDetails =
        await flutterLocalNotificationsPlugin.getNotificationAppLaunchDetails();
```
```
String? payload = notificationAppLaunchDetails!.payload;
```

    
  And payload is always null

**Comment by MaikuB** [comment]
You are only meant to call `getNotificationAppLaunchDetails()` if you want to deal with when a notification launched the app. A reminder that there's an example app that can be referred. Closing as this issue is due to misunderstanding in how to use the plugin
