### ISSUE TITLE
Not working on Android Release when minified and obfuscated

### ISSUE THREAD

**Issue by brunodmn** [MaikuB/flutter_local_notifications#1552]
**Describe the bug**
I am trying to run notification from another isolate (with [Workmanager](https://pub.dev/packages/workmanager) plugin). It works fine when I run on my physical Android device locally, but when I build an appbundle obfuscating the code, it won't work nor throw errors. 

**To Reproduce**
I've created a fresh application with implementation of packages  [Workmanager](https://pub.dev/packages/workmanager) and [Flutter Local Notifications](https://pub.dev/packages/flutter_local_notifications). Added keep.xml and progruard-rules.pro as per documentation
1. Clone [this sample](https://github.com/brunodmn/localNotificationsAndWorkmanagerMinimL);
2. Add key.porperties to sign the bundle;
3. Run `flutter build appbundle --obfuscate --split-debug-info={$FOLDER}` to create a bundle (replace $FOLDER with existing location)
4. Install it on your Android device (You can use [Internal App Sharing](https://support.google.com/googleplay/android-developer/answer/9844679))

**Expected behavior**
Local notification should be shown on app initialization

**Sample code to reproduce the problem**
[Sample Code](https://github.com/brunodmn/localNotificationsAndWorkmanagerMinimL)

<details>
  <summary>flutter doctor -v</summary>
  
[✓] Flutter (Channel stable, 2.10.4, on Linux Mint 20.3 5.4.0-107-generic,
    locale en_US.UTF-8)
    • Flutter version 2.10.4 at /home/bruno/_development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (11 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/bruno/Android/Sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /snap/android-studio/current/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio
    • Android Studio at /snap/android-studio/current/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /snap/android-studio/current/android-studio
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.66.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.38.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux Mint 20.3
      5.4.0-107-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 100.0.4896.60

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

</details>

**Comment by MaikuB** [comment]
Thanks for including a minimal app but your scenario refers to another plugin. If there's an issue specific to this plugin then you'll need to isolate the example to only refer to this plugin. Given how long the plugin has been out, I doubt the issue you're referring to is to do with this plugin as it should've been reported by now

**Comment by brunodmn** [comment]
> Thanks for including a minimal app but your scenario refers to another plugin. If there's an issue specific to this plugin then you'll need to isolate the example to only refer to this plugin. Given how long the plugin has been out, I doubt the issue you're referring to is to do with this plugin as it should've been reported by now

Hi @MaikuB, thanks for your reply. I did additional tests, I can confirm the plugin works even obfuscated if I run from code and not from workmanager. I've also tested awesome_notifications with same issue running from isolate. All suggests the problem is with workmanager and I posted a report there.
 I will close this issue by now and follow up there..thank you
