### ISSUE TITLE
Add ability to show big picture on iOS without the need to download and pass in the file path.

### ISSUE THREAD

**Issue by Kashishm273** [MaikuB/flutter_local_notifications#1553]
Right now, in order to show a big picture along with notification in iOS, given that we need to download the image from web, we need to download it and give the file path like - 

`IOSNotificationAttachment(bigPicturePath)`

Can we have the capability wherein we can directly pass the image URL, and rest of the things like download, etc can be handled internally?

**Comment by MaikuB** [comment]
No plans for this as developers will have their own way of handling downloads, whether it be where files get saved, how to handle errors (e.g. retry logic) or even what library gets used to do download as everyone has different preferences. Furthermore the plugin is wrapper to the native APIs so without the wrapper, the onus would still be on developers to download and decide where the file resides as it is now

**Comment by AnhDTN** [comment]
I got bug not load image when kill app, and not load image in iPhone 11
