### ISSUE TITLE
Call a long running function on startForegroundService()

### ISSUE THREAD

**Issue by razfazz** [MaikuB/flutter_local_notifications#1554]
if would be handy if it would be possible to call a long running background function (dart function) on startForegroundService()

**Comment by MaikuB** [comment]
Not sure what you mean by that and how and why that should tie into that particular API.

Regardless, this would be something you'd need to look at submitting a PR. Note that even the current implementation was a contribution but another developer in the community

**Comment by MaikuB** [comment]
Closing as there's not been any further explanation and won't be something I'd be looking to look at
