### ISSUE TITLE
Manually count badge count.

### ISSUE THREAD

**Issue by Najaf-Rai** [MaikuB/flutter_local_notifications#1557]
Hi, I want to count unread notifications count manually to set badge count on the icon inside the app? kindly let me know how can I handle it also how do I get to know when the notification arrived on my App, for example, is there any listener which called?

**Comment by wahyu-handayani** [comment]
Hi @MaikuB I would like to ask.. is there a way to show dot badge instead of number when notification is active on status bar? I also open my question in https://stackoverflow.com/questions/73046034/how-to-show-dot-badge-on-app-icon-flutter would you like to take a look
