### ISSUE TITLE
[idea] How about merge zonedSchedule & periodicallyShow into an uniform 'cron syntax'

### ISSUE THREAD

**Issue by ash0080** [MaikuB/flutter_local_notifications#1560]
First of all, thanks for this awesome package,  I have a little idea here that I hope will help make it even better

```dart
_lnp.schedule(
      id,
      title,
      body,
      '5 4 * * *',  // <-- cron string.   At 04:05 daily
      timezone: "Europe/London", // <--optional, default device local  
      notificationDetails,
      // matchDateTimeComponents @Deprecated 
    )
```
more cron styles
```dart
'0 8 * * 1', // <-- At 08:00 on Monday weekly
'0 16 * * 6,7' // <-- At 16:00 on Saturday and Sunday.
'* * * * *' // <-- At every minute
```

Motivation:

From the developer's perspective:
Currently .zonedSchedule(), .periodicallyShow() seems to be functionally indistinguishable, 
zonedSchedule() essentially produces a 'repeat notification' effect by adding the matchDateTimeComponents parameter, using a uniform cron syntax that makes things clear.

From an internal code perspective:
For example, let's look at the swift code, You'll notice that both methods, in essence, repeat by adding the notification.repeatInterval parameter. so maybe it's feasible to actually merge the two methods and make the code clearer and easier to maintain.

https://github.com/MaikuB/flutter_local_notifications/blob/2558b2ee8f40dfead9027d088af33528530cdedd/flutter_local_notifications/ios/Classes/FlutterLocalNotificationsPlugin.m#L448
https://github.com/MaikuB/flutter_local_notifications/blob/2558b2ee8f40dfead9027d088af33528530cdedd/flutter_local_notifications/ios/Classes/FlutterLocalNotificationsPlugin.m#L512

OK, this is my little immature ideas, wish to help and welcome your correction.

**Comment by MaikuB** [comment]
> From the developer's perspective:
Currently .zonedSchedule(), .periodicallyShow() seems to be functionally indistinguishable,
zonedSchedule() essentially produces a 'repeat notification' effect by adding the matchDateTimeComponents parameter, using a uniform cron syntax that makes things clear.

IMO that is subjective. I personally find the cron syntax hard to understand and I wouldn't be surprised if most developers would struggle with this when it comes to readability. Even the notification APIs for each platform don't support cron syntax

If you want to look at cron syntax then you'll need to do some research on seeing if it's technically feasible so with the available APIs provided by each platform and should it even be possible then you'd need to submit a PR yourself this as this isn't something I have time to do so. However, I do want to point out that the code referenced (note: that is Objective-C not Swift) is for code using Apple's old notification APIs. On iOS 10+, the APIs used behind the scenes for both methods are different so this is another reason why there are two separate methods so I would suggest you look further into those. If I'm not mistaken, cron syntax also allows you to craft expressions with multiple values for the same component. This isn't supported by the native APIs

**Comment by ash0080** [comment]
Okay, so back to the two methods themselves, 
```dart
enum RepeatInterval {
  everyMinute,
  hourly,
  daily,
  weekly
}
```
```dart
enum DateTimeComponents {
  time,   // equals daily.
  dayOfWeekAndTime, // equals weekly
  dayOfMonthAndTime,   // equals monthly
  dateAndTime,   // equals yearly.
}
```
Don't you think you can use zonedScheduleNotification instead of periodicallyShow method except for per minute, just use DateTime.now(), so can't these two methods be combined into one? at least for flutter interface.
You mentioned awesome_notifications, and it has only one. At least it would be much clearer in terms of usage, the current naming and splitting is confusing.

**Comment by MaikuB** [comment]
> Don't you think you can use zonedScheduleNotification instead of periodicallyShow method except for per minute, just use DateTime.now(), so can't these two methods be combined into one? at least for flutter interface.
You mentioned awesome_notifications, and it has only one. At least it would be much clearer in terms of usage, the current naming and splitting is confusing.

How would you suggest doing so? The fact that one plugin takes a certain approach doesn't mean this one needs to either. Furthermore, there's not been an explanation on where the confusion is. From what I can recall you're the first to bring it up or if you're not, there's not been much feedback to warrant the change. Given what you said, perhaps the confusion is that you haven't realised there's also a fundamental difference in what each method does. One is to periodically show a notification based on a predefined interval (hence the name of the method). The other method allows a notification to be scheduled appear in the future based on a given date/time relative to a timezone with the *option* to have it repeat based on components of the date/time. This has a dependence on a date/time value but the other method doesn't. Based on that explanation, you should hopefully see why the methods are named the way they are though `schedule` still seemed to be used by some of the community so kept in the interface

I assume you brought up `DateTime.now()` to cover the use case of `periodicallyShow`. If so, note isn't possible to have a notification repeat and give it a start date at the same time. If you'd like to make suggestions then my own suggestion is you look at the native APIs first

**Comment by ash0080** [comment]
Very clear

**Comment by lukepighetti** [comment]
@MaikuB @ash0080 hey guys i'm trying to schedule "remind me of my workout every day at 6am" and the quote above from @MaikuB makes it sound like this is possible but I'm having troubling finding a method that performs this task. thank you!

**Comment by MaikuB** [comment]
@lukepighetti clone the repo and run the example app. It covers every scenario supported and based on what you said (daily notification), yours is one of them
