### ISSUE TITLE
[question] Can the current plugin implement channel name localization?

### ISSUE THREAD

**Issue by ash0080** [MaikuB/flutter_local_notifications#1563]
ref: 
https://stackoverflow.com/questions/46317545/android-o-notification-channel-localization

**Comment by MaikuB** [comment]
Not sure what the relevance of the link is. Localisation on Android is done differently than Flutter to begin with. If you're using the plugin then it's the responsibility of your application to provide the content of the notification to display so it'll display what your app tells it display. This is also what would happen if you used the native APIs directly. It's up to you to determine what your application needs to support, the scenarios it needs to cover etc and then see if using the plugin is sufficient or if you need to implement your custom solution.

**Comment by ash0080** [comment]
For example, for scheduled notification, I'm not sure how an already scheduled notification would respond to a language switch

**Comment by MaikuB** [comment]
This isn't supported by the plugin as it will display what's it told to display. You would need to do research into if it's even possible to handle the scenarios you're looking to support to begin with as explained earlier. This means you should be look into understanding how the native APIs work prior as part of this and this is something you should be doing before even considering using this plugin as part of the analysis of developing your app
