### ISSUE TITLE
AssetsLinuxIcon doesn't quite work as named

### ISSUE THREAD

**Issue by dballard** [MaikuB/flutter_local_notifications#1565]
Flutter does not have access to the asset_path in the dart runtime. The rootBundle uses a binaryMessage system to fetch assets because as to it's mobile origins, native code was required to load them. This was kept up and as best I can tell, on desktop it's implemented probably in the autogenerated or included C code.

if the application is installed in a non standard way, this AssetsLinuxIcon doesn't work. We hacked my_application.cc for linux to support more natural linux installations of `assets` to /usr/share/appname/assets or ~/.local/share/appname/assets. While in app any user of AssetImage works in our app, using your AssetsLinuxIcon doesn't because it only gets a local relative path and only works when the assets dir is right in the executing directory hence the relative path happens to resolve.

I'm not sure what the proper solution is since we are doing slightly non standard behaviour but at a minimum you might want to rename the class from AssetsLinuxIcon since it isn't access flutter assets properly but just acting as a normal straight relative path, so it was a confusing error for a while until I understood what was happening.

On my end I'll prolly have to write my own detection code in dart so it can find the assets in one of the 3 or 4 locations we would install them and construct and absolute path to give to "AssetsLinuxIcon".

thanks! and sorry :D

**Comment by dballard** [comment]
oh, it seems in platform_info.dart you have a 
`LinuxPlatformInfo` which has 
`final String assetPath = path.join(appPath, 'data', 'flutter_assets');`
and then in `notification_manager.dart` you have
`
case LinuxIconType.assets:
        if (_platformData.assetsPath == null) {
          return null;
        } else {
          final String relativePath = icon.content as String;
          return path.join(_platformData.assetsPath!, relativePath);
        }
`

which means even if I do my own detection and supply an absolute path to the installed icon, your plugin cannot use it.

**Comment by dballard** [comment]
so yeah I guess my request is a way to either update FlutterLocalNotificationsPlugin with an assets_path or AssetsLinuxIcon

**Comment by MaikuB** [comment]
I'm not particularly familiar with Linux so note that what I say here may incorrect and the Linux support came from a  PR from @proninyaroslav. With the implementation it is in some ways correct in the sense of the path it uses is within `flutter_assets`. If I understood you correctly, it's that the use of the term asset here isn't assigned with how Flutter assets with work e.g. https://docs.flutter.dev/development/ui/assets-and-images#sharing-assets-with-the-underlying-platform. If so, I understand what you mean though I'm not sure if a better name for it or if this could just explained via documentation as a caveat. From what I understood, to support your own use case doesn't require changing how things currently work. You could submit a PR to add another icon type so to speak as the icon property expects an instance of the `AssetsLinuxIcon` class. `LinuxNotificationIcon` derives from this so the new type could do the same. Given you mentioned trying to change the latter, have you looked at the other subclasses and considered using those?

**Comment by proninyaroslav** [comment]
Unfortunately, Flutter is not adapted to the classic FHS (Filesystem Hierarchy Standard) model for Linux and is oriented towards containers such as Flatpak, Snap, AppImage. As a default behavior, to access resources, the app uses `data` folder, which is located next to the executable file. The `data/flutter_assets` directory contains all assets. You can see that this access method is even in `package_info_plus`:

https://github.com/fluttercommunity/plus_plugins/blob/89993a6339cf74594e88bc48f861d0c95e8b21ea/packages/package_info_plus/package_info_plus_linux/lib/src/package_info.dart#L29-L39

Therefore, this method was chosen to access assets. Flutter for Linux still doesn't have an idiomatic way to access resources like Android does, nor to customize it at build time with the standard Flutter tools. I think that developers should be given more options to customize the asset path. Maybe allow this at the plugin initialization stage, or create a class derived from `LinuxNotificationIcon` that allows to specify the absolute path to the icon. @MaikuB how do you think?

**Comment by MaikuB** [comment]
@proninyaroslav makes sense and your last suggestion is aligns with what I mentioned earlier around deriving from `AssetsLinuxIcon`. I would think that would be better than the first option as it sounds like the first option on customising the path may involve a breaking change. There may also be possibility for the name of the new subclass and/or its constructor signature to provide more clarity on what its usage is for as well

**Comment by MaikuB** [comment]
@dballard there's a PR that @proninyaroslav has put up. Are you able to see if this would work for your scenarios? From what I could see it should work but would be good if you could confirm. To test, you could change your app to reference that PR/fork by following the docs that cover how to use git dependencies at https://dart.dev/tools/pub/dependencies#git-packages

**Comment by dballard** [comment]
Sorry just moved and have a busy week but I'll try and schedule some time this week to confirm! thanks!
