### ISSUE TITLE
Excuse me, I wonder if this plugin supports changing the channel of sound ?

### ISSUE THREAD

**Issue by DioboKN** [MaikuB/flutter_local_notifications#1567]
Since I wanted to make an alarm clock app, I wanted to know if I could make the sound play in the alarm clock volume
![7e97f6f23fbc4f7c9265c2a3ffdc410](https://user-images.githubusercontent.com/52503667/163902855-6fab268e-ce1d-404a-99c0-683121bd061c.jpg)
.

**Comment by MaikuB** [comment]
No it doesn't and I don't believe the native Android APIs even support this as it IMO would defeat the purpose of having a separate volume setting specifically for notifications and system sound. If you know of a way to do so then submit a PR for it
