### ISSUE TITLE
Is there a way to define end date?

### ISSUE THREAD

**Issue by mydwa** [MaikuB/flutter_local_notifications#157]
First, many thanks for this work. 
Just two questions, 
is there a way to define end date for showDailyAtTime?
How to show to user all pending notifications?
again great work!

**Comment by MaikuB** [comment]
there's no way to specify the end date and none of the APIs exposed natively let you do that from memory and i'm trying to mirror what's available in the APIs as much as possible. once better background execution support is available in Flutter, I would envisage that you could cancel scheduled notifications on receiving a callback when a notification is shown by inspecting the payload/custom data associated with the notification.

there's no way to get a list of pending notifications (yet) either. there's an open issue on that already #75

**Comment by mydwa** [comment]
Hi there,
Many thanks for your answer.
On EndDate topic, actually I am trying to do this (but still on test phase):
“await Future.delayed(Duration(days: (EndDate - StartDate), () async
	{await stopNotification(notification_ref);}
);”
I will tell if that works.

To get Pending notifications, I still working on it. For the time being, I’m trying to store them in a List and use callback to update that List.

Again great work !!
