### ISSUE TITLE
 onSelectNotification is not called on iOS

### ISSUE THREAD

**Issue by kodol73** [MaikuB/flutter_local_notifications#1570]
Hi, 
It works ok on Android,
however, onSelectNotification is not called when I press the notification on iPhone.

It seems that there should be some code to call the callback, onSelectNotification for flutter_local_notifications in completionHandler() of userNotificationCenter() didReceive of AppDelegate.swift

Please help me to solve this issue.
Thanks in advance

swift version : 5.6

in pubspec.yaml
flutter_local_notifications: ^8.1.1+2

```
import UIKit
import Flutter

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
   if #available(iOS 10.0, *) {
      UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate
    } else { 
      UIApplication.shared.registerForRemoteNotifications()
    }
    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }

  @available(iOS 10.0, *)
  override public func userNotificationCenter(
    _ center: UNUserNotificationCenter, 
    willPresent notification: UNNotification, 
    withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Swift.Void) {
    print("Notification on Foreground")
    completionHandler([.alert, .badge, .sound])
  }

  @available(iOS 10.0, *)
  override public func userNotificationCenter(
    _ center: UNUserNotificationCenter, 
    didReceive response: UNNotificationResponse, 
    withCompletionHandler completionHandler: @escaping () -> Swift.Void) {
      
      let notification = response.notification
      let userInfo = notification.request.content.userInfo

      if response.actionIdentifier == UNNotificationDismissActionIdentifier {
          print ("Message Closed")
      } else if response.actionIdentifier == UNNotificationDefaultActionIdentifier {
          print ("push notification is clcked")
          print("====userInfo====")
          print(userInfo)
      } 

      completionHandler()
  }
}
```

**Comment by jaskiratAtNexG** [comment]
encountering the same problem any solution?

**Comment by eyesoffish** [comment]
in FlutterLocalNotificationsPlugin.m at line 840 then add center.delegate = self; it is work to me
```obcj
- (void)addNotificationRequest:(NSString *)identifier
                       content:(UNMutableNotificationContent *)content
                        result:(FlutterResult _Nonnull)result
                       trigger:(UNNotificationTrigger *)trigger
    API_AVAILABLE(ios(10.0)) {
  UNNotificationRequest *notificationRequest =
      [UNNotificationRequest requestWithIdentifier:identifier
                                           content:content
                                           trigger:trigger];
  UNUserNotificationCenter *center =
      [UNUserNotificationCenter currentNotificationCenter];
// add the code
  center.delegate = self;
  [center addNotificationRequest:notificationRequest
           withCompletionHandler:^(NSError *_Nullable error) {
             if (error == nil) {
               result(nil);
               return;
             }
             result(getFlutterError(error));
           }];
}
```

**Comment by kodol73** [comment]
> addNotificationRequest:notificationRequest

It works well
Thanks a lot

**Comment by ram231** [comment]
@eyesoffish  it looks like on the latest release, it doesn't have the fix yet. Can you make a PR on this? I'm having the same problem.

**Comment by MaikuB** [comment]
I suspect the issues mentioned here are from not doing this setup https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#general-setup

If this isn't correct then please open a new issue using the bug report template and include a link to a minimal app using only this plugin the can also reproduce the issue

**Comment by kodol73** [comment]
> 

I don't think that this issue is related to any setting on your link
If you think so, please pick up the exact one

**Comment by MaikuB** [comment]
The link goes to the exact section and key part of the code logic is same as what was shared by @eyesoffish earlier around assigning the delegate. Would be up to community to provide the evidence of issues provided the steps have been followed

**Comment by kodol73** [comment]
> The link goes to the exact section and key part of the code logic is same as what was shared by @eyesoffish earlier around assigning the delegate. Would be up to community to provide the evidence of issues provided the steps have been followed

There are too much settings on your link,
then which setting on the link do you think is related to this issue?

**Comment by MaikuB** [comment]
It goes the exact section as mentioned earlier so it would be general setup. Opening the link should have taken you straight to it

![Screenshot_20220505-150648](https://user-images.githubusercontent.com/25263378/166866371-0f6ab69d-edb7-41a8-9611-160fe1d0f3eb.png)

**Comment by kodol73** [comment]
> https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#general-setup

The setting you just mentioned is what I already wrote in the beginning
See what I wrote in the beginning
Moreover, this setting is for notification while the app is in the foreground
My issue is different from this

**Comment by MaikuB** [comment]
Apologies missed that as I was going through based on the proposed solution, which relates to this. Actually the setting is required to deal with notification events so not foreground specific.. What sticks out is that you have implemented `didReceive`. Based on this it looks your own app would be handling what would happen when a notification is tapped on. If so, then that would be why the plugin's callback isn't triggered as it's being overwritten. Similarly, you shouldn't have to implement `willPresent` either. If you look at the example app, neither of these methods are present https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/example/ios/Runner/AppDelegate.swift. Have you tried removing your implementations?

**Comment by youssefali424** [comment]
suddenly this started happening, and I didn't notice it until the client reported it, I followed every setup guide for ios, and it was actually working before not even that long ago, but I can't be sure which version ruined the expected behavior. but I can tell that the fork above actually solved the issue, and probably this isn't a setup issue at all.

**Comment by MaikuB** [comment]
@youssefali424 there's not been any changes in the plugin around this so ideally it would be good if you can provide a minimal app that can reproduce the issue. At the least, can you provide info on the version of Flutter being used, the version of this plugin used by the app and version information of other notification plugins being used. Perhaps other plugins have changed how they do things and have affected this plugin that requires changes then

**Comment by youssefali424** [comment]
After adding [one signal](https://pub.dev/packages/onesignal_flutter) to the [example](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications/example)
flutter_local_notifications suddenly started behaving weird sometimes not even showing notifications on ios, so if you think it isn't a bug with flutter_local_notifications at least tell us how to use both or what is the issue that broke the package with one_signal 
@MaikuB
