### ISSUE TITLE
unable to execute code after app starts when it is terminated

### ISSUE THREAD

**Issue by nicknma** [MaikuB/flutter_local_notifications#1572]
My app executes code after a user taps a notification. This works just fine when the app is running in the background, but the code is not executed if the app is terminated before the user taps the notification. 
1-Set a notification.
2-Close the app.
3-Tap notification when it pops.
4-App opens but the code that executes on notification selection does not execute.

**Comment by MaikuB** [comment]
The callback isn't meant to work when the app is terminated. It's covered in the docs that if you want to handle this i.e. when an app is launched from a notification that you should call method to determine if that is the case https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#getting-details-on-if-the-app-was-launched-via-a-notification-created-by-this-plugin
