### ISSUE TITLE
only single payload data can be added to onclick 

### ISSUE THREAD

**Issue by suhail600** [MaikuB/flutter_local_notifications#1573]
only single payload data can be added to onclick , if we needed to check another message data in on click , there is no method , if anyone knows please tell

**Comment by Asquare17** [comment]
Encode all the fcm data and pass it to the payload
FirebaseMessaging.onMessage.listen((RemoteMessage message) {

Map<String, dynamic> data = message.data;

  _flutterLocalNotificationsPlugin.show(
          notification.hashCode,
          notification.title,
          notification.body,
          notificatioDetails,
 payload: jsonEncode(data));

});

**Comment by MaikuB** [comment]
as @Asquare17 mentioned you can serialise your data as JSON and the deserialise it when you need to read the info
