### ISSUE TITLE
Attachment in iOS is not showing just notification with title and body is coming when app is the background or closed . When the app is in the open state it is working as expected

### ISSUE THREAD

**Issue by Vishanth-vn** [MaikuB/flutter_local_notifications#1576]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Sample code to reproduce the problem**

**Comment by MaikuB** [comment]
Please make sure to include a minimal example app that can reproduce the issue that **only** uses this plugin. This is to ensure due diligence has been done on ensuring there's a legitimate bug here. Unless it's done this will be closed. Furthermore, I've seen a lot of issues reported that aren't valid when developers useFCM with this plugin and don't understand when a notification comes from FCM or is from this plugin

**Comment by MaikuB** [comment]
Closing due to lack of response with the requested information. Feel free to re-open the new issue if you're able to provide it
