### ISSUE TITLE
[FEATURE REQUEST] beforeShown, afterShown callbacks on notifications

### ISSUE THREAD

**Issue by adummy832** [MaikuB/flutter_local_notifications#1579]
Hi! First of all, Thanks for this very wonderful package 🎉

I just wondering if you can support this feature? This would be 
a very beneficial feature especially on scheduled notifs eg. daily notifs, etc.

Imagine having this on our code.

```dart
static Future<void> scheduleNotification({
  required String title,
  required String body,
  String? payload,
}) async {
  return await _notification.zonedSchedule(
    0,
    title,
    body,
    tzDateTime,
    _notificationDetails(),
    payload: payload,
    androidAllowWhileIdle: true,
    uiLocalNotificationDateInterpretation:
        UILocalNotificationDateInterpretation.absoluteTime,
    matchDateTimeComponents: DateTimeComponents.time,
    
    beforeShown: (NotificationInfo info) async {
      // We could do wonders here. 
      // 1. Reinitialize attributes
      // 2. DB checks updating the title, body, etc.
      info.title = 'New title';
      info.body = 'New body';
      info.payload = 'New payload';
    }, 
    afterShown: (NotificationInfo info) async {
      // Edit something.
    },
  );
}
```

I also referenced this issue https://github.com/MaikuB/flutter_local_notifications/issues/1493

**Comment by MaikuB** [comment]
Your request isn't much different to the one you referenced where I had answered there that it's not possible. Consequently the answer here is the same in that it's not possible. If you need to do something this then you need think about your problem a a higher level as you're not scheduling a notification but scheduling general computational work, which isn't what notification APIs do
