### ISSUE TITLE
Custom sound not working

### ISSUE THREAD

**Issue by appledev-67** [MaikuB/flutter_local_notifications#1582]
We have noticed that the Alert Tone is not working for Alcatel devices - it's playing the regular android notification tone

**Comment by Gkemon** [comment]
I also worked with like that - 

```
 NotificationDetails(
            android: AndroidNotificationDetails(
              channel.id,
              channel.name,
              channelDescription: channel.description,
              playSound: true,
              sound: RawResourceAndroidNotificationSound("inactive_notification_sound")
            ),
            iOS: IOSNotificationDetails(
              presentAlert: true, // Required to display a heads up notification
              presentBadge: false,
              presentSound: true,
              sound: "inactive_notification_sound.wav"
            )),
```

And my keep.xml is - 

```
<?xml version="1.0" encoding="utf-8"?>
<resources xmlns:tools="http://schemas.android.com/tools"
    tools:keep="@drawable/*,@raw/inactive_notification_sound"
    />
```

and my resource is in -  **res/raw/inactive_notification_sound.wav** . 

But it is not working

**Comment by GkEmonGON** [comment]
Exception

> I also worked with like that -
> 
> ```
>  NotificationDetails(
>             android: AndroidNotificationDetails(
>               channel.id,
>               channel.name,
>               channelDescription: channel.description,
>               playSound: true,
>               sound: RawResourceAndroidNotificationSound("inactive_notification_sound")
>             ),
>             iOS: IOSNotificationDetails(
>               presentAlert: true, // Required to display a heads up notification
>               presentBadge: false,
>               presentSound: true,
>               sound: "inactive_notification_sound.wav"
>             )),
> ```
> 
> And my keep.xml is -
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <resources xmlns:tools="http://schemas.android.com/tools"
>     tools:keep="@drawable/*,@raw/inactive_notification_sound"
>     />
> ```
> 
> and my resource is in - **res/raw/inactive_notification_sound.wav** .
> 
> But it is not working

Exception is - 
`I/flutter (26614): PlatformException(INVALID_SOUND, The resource inactive_notification_sound.wav could not be found. Please make sure it has been added as a raw resource to your Android head project., null, null)`

**Comment by MaikuB** [comment]
Closing as there's further lack of response from original poster. If it's a device-specific issue then that's outside of the control of the plugin and Android APIs themselves.

As for your issue @Gkemon, I've not seen anyone else have such issues and haven't had issues with this myself. If you believe there's a bug then please file a new issue via the bug report template and include a link to a repository that has a minimal app that can reproduce the issue
