### ISSUE TITLE
[macOS] flutter_local_notifications/FlutterLocalNotificationsPlugin.swift:87: Fatal error: Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by deimantasa** [MaikuB/flutter_local_notifications#1585]
**Describe the bug**
App crashes when it's in foreground and receives a push notification.

**To Reproduce**
Trigger `push notification` on macOS.

**Expected behavior**
App should not crash and `push notification` badge should be shown on the right top corner of the screen with push notification payload.

**Sample code to reproduce the problem**
N/A.

**Additional Information**
Stable and Dev versions has different crash location. However - they both do crash at the same scenario. While receiving `push notification` well, if app is in the background.

Version `9.5.1`
```
flutter_local_notifications/FlutterLocalNotificationsPlugin.swift:87: Fatal error: Unexpectedly found nil while unwrapping an Optional value
```
Which is at
```swift
// FlutterLocalNotificationsPlugin.swift

    @available(OSX 10.14, *)
    public func userNotificationCenter(_ center: UNUserNotificationCenter, willPresent notification: UNNotification, withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void) {
        var options: UNNotificationPresentationOptions = []
        let presentAlert = notification.request.content.userInfo[MethodCallArguments.presentAlert] as! Bool // line 87 is here
        let presentSound = notification.request.content.userInfo[MethodCallArguments.presentSound] as! Bool
        let presentBadge = notification.request.content.userInfo[MethodCallArguments.presentBadge] as! Bool
        if presentAlert {
            options.insert(.alert)
        }
        if presentSound {
            options.insert(.sound)
        }
        if presentBadge {
            options.insert(.badge)
        }
        completionHandler(options)
    }
```

Version `10.0.0-dev.13`.
```
flutter_local_notifications/FlutterLocalNotificationsPlugin.swift:642: Fatal error: Unexpectedly found nil while unwrapping an Optional value
```

Which is at
```swift
// FlutterLocalNotificationsPlugin.swift

   @available(macOS 10.14, *)
    func extractNotificationResponseDict(response: UNNotificationResponse) -> [String: Any?] {
        var notificationResponseDict: [String: Any?] = [:]
        notificationResponseDict["notificationId"] = Int(response.notification.request.identifier)! // l642 is here
        if response.actionIdentifier == UNNotificationDefaultActionIdentifier {
            notificationResponseDict[MethodCallArguments.notificationResponseType] = 0
        } else if response.actionIdentifier != UNNotificationDismissActionIdentifier {
            notificationResponseDict[MethodCallArguments.actionId] = response.actionIdentifier
            notificationResponseDict[MethodCallArguments.notificationResponseType] = 1
        }
        notificationResponseDict["input"] = (response as? UNTextInputNotificationResponse)?.userText
        notificationResponseDict[MethodCallArguments.payload] = response.notification.request.content.userInfo[MethodCallArguments.payload]
        return notificationResponseDict
    }
```

Any suggestions on how to fix it and/or solve this issue are welcome!

**Comment by deimantasa** [comment]
Apologies - it's `remote push notification` sent from Firebase. Our codebase at this point is very big, but I'm certain that the issue should be reproducible anywhere - will create some small project for it.

**Comment by MaikuB** [comment]
Are you able to use this branch of the plugin with your application to confirm it fixes the issue https://github.com/MaikuB/flutter_local_notifications/tree/macOSNotificationUnwrap? I don't have access to a project with FCM on macOS but the fix is the same done for iOS so I'd expect it to work

**Comment by deimantasa** [comment]
I was about to submit PR. Woah.

Wonderful. It does work! Thank you for prompt fix. I guess yours is much better than mine at this point https://github.com/deimantasa/flutter_local_notifications/commit/8732716b7662baa72512da828e479e8bef158a54 .  Can I expect this fix be included in upcoming version bump? If yes - when should it happen?

**Comment by deimantasa** [comment]
No problem. Thank you very much for your quick response and a fix! Have a great rest of the Friday!
