### ISSUE TITLE
App crash when clicking on action button within notification

### ISSUE THREAD

**Issue by IronHeartDan** [MaikuB/flutter_local_notifications#1589]
### This is my channel initialization code :

NotificationDetails(
          android: AndroidNotificationDetails(
            'CALL_CHANNEL',
            'Call',
            channelDescription: 'Required to show incoming calls',
            importance: Importance.max,
            priority: Priority.max,
            category: "CATEGORY_CALL",
            playSound: true,
            sound: const RawResourceAndroidNotificationSound("incoming_call"),
            enableVibration: true,
            vibrationPattern: Int64List.fromList([1111,1111]),
            ongoing: true,
            autoCancel: false,
            fullScreenIntent: true,
            actions: const [
              AndroidNotificationAction("ACCEPT", "Accept"),
              AndroidNotificationAction("DECLINE", "Decline"),
            ]
          )

### Error after clicking on the action button

Shutting down VM
E/AndroidRuntime(10036): FATAL EXCEPTION: main
E/AndroidRuntime(10036): Process: com.zdimension.sharebits, PID: 10036
E/AndroidRuntime(10036): java.lang.RuntimeException: Unable to start receiver com.dexterous.flutterlocalnotifications.ActionBroadcastReceiver: java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.view.FlutterCallbackInformation.callbackLibraryPath' on a null object reference
E/AndroidRuntime(10036): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4041)
E/AndroidRuntime(10036): 	at android.app.ActivityThread.access$1400(ActivityThread.java:237)
E/AndroidRuntime(10036): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1924)
E/AndroidRuntime(10036): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(10036): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(10036): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime(10036): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10036): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(10036): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/AndroidRuntime(10036): Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.view.FlutterCallbackInformation.callbackLibraryPath' on a null object reference
E/AndroidRuntime(10036): 	at io.flutter.embedding.engine.dart.DartExecutor$DartCallback.toString(DartExecutor.java:423)
E/AndroidRuntime(10036): 	at java.lang.String.valueOf(String.java:2924)
E/AndroidRuntime(10036): 	at java.lang.StringBuilder.append(StringBuilder.java:132)
E/AndroidRuntime(10036): 	at io.flutter.embedding.engine.dart.DartExecutor.executeDartCallback(DartExecutor.java:175)
E/AndroidRuntime(10036): 	at com.dexterous.flutterlocalnotifications.ActionBroadcastReceiver.startEngine(ActionBroadcastReceiver.java:87)
E/AndroidRuntime(10036): 	at com.dexterous.flutterlocalnotifications.ActionBroadcastReceiver.onReceive(ActionBroadcastReceiver.java:65)
E/AndroidRuntime(10036): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4032)
E/AndroidRuntime(10036): 	... 8 more

**Comment by strmchsr** [comment]
@IronHeartDan facing the same issue , what is the resolution?

**Comment by IronHeartDan** [comment]
> @IronHeartDan facing the same issue , what is the resolution?

Yes I solved it by providing both methods that needs to handle the click while initialisation.

**Comment by MaikuB** [comment]
@IronHeartDan which one was the callback you originally handled that led to the crash then?

**Comment by IronHeartDan** [comment]
> @IronHeartDan which one was the callback you originally handled that led to the crash then?

**FlutterLocalNotificationsPlugin.java**
**Line 1466 to 1470**
`    Long dispatcherHandle = call.argument(DISPATCHER_HANDLE);
    Long callbackHandle = call.argument(CALLBACK_HANDLE);
    if (dispatcherHandle != null && callbackHandle != null) {
      new IsolatePreferences(applicationContext).saveCallbackKeys(dispatcherHandle, callbackHandle);
    }`

The callbacks are only saved when we provide both the methods so using only one will always crash.

### Also after solving this 

When using "onDidReceiveBackgroundNotificationResponse" the method is not behaving properly,

I am trying to decline a call but as the app could be in background of not alive I have to use "onDidReceiveBackgroundNotificationResponse" so that when a decline action is clicked it handles it in background but as their a different flutter engine, I need to connect a socket from there and send server the response for call decline and then close the socket. It works perfectly for the first notification but for all the new ones the socket never gets connected as if the code is not running again.



void onDidReceiveBackgroundNotificationResponse(response) async {
  var notificationResponse = response as NotificationResponse;

  log("Background CLick");

  var action = notificationResponse.actionId;
  var payload = jsonDecode(notificationResponse.payload!);

  if (action == "DECLINE") {
    var socket = io(
        socketServer,
        OptionBuilder().setTransports(['websocket']).setExtraHeaders(
            {"type": 0}).build());

    socket.onConnect((_) {
      log("Background Socket Connected");
      socket.emit("callDeclined", payload["from"]);
      log("Sent CallDeclined In BG");
      socket.disconnect();
      log("Background Socket Disconnected");
    });
  }
  log("ENDED");
}


Surprisingly the logs are working but the socket only gets connected once.
Anything I am doing wrong or is there any better way for it ?
