### ISSUE TITLE
Targeting S+ (version 31 and above) - Prerelease: 10.0.0-dev.13 on Android 

### ISSUE THREAD

**Issue by Onheil13** [MaikuB/flutter_local_notifications#1591]
For those who are facing.

`Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent. Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.`

Try to add this on your build.gradle(app)

`implementation 'androidx.work:work-runtime:2.7.1'`

**Comment by MaikuB** [comment]
This looks odd as all these issues should've been resolved and adding a library isn't what should fix this as these issues require a code change. I've not seen show up in the example app since changes were made around this either. You able to provide a link to a repo with a minimal app that can reproduce the problem?

**Comment by maximiliannocker** [comment]
@MaikuB do you know when Version 10 will be released as stable version?

**Comment by MaikuB** [comment]
@maximiliannocker is your question somehow related the issue reported here as Android 12 support? This should already be there in the current 9.x release.

As for the answer to your question, a shortened version is that there's no timeline and if you want to see if released sooner then help test it out and provide feedback. When I say feedback, this doesn't just mean reporting issues but also includes reporting on if it has worked for your scenarios and what those scenarios were. I originally this mentioned in https://github.com/MaikuB/flutter_local_notifications/issues/17#issuecomment-1093747889. This is a plugin I developed in my spare time as there was gap the plugin space and don't actually use so I need the community to help as well. In the past, I had already come across problems where I added features/fixes that the community requested in a prerelease yet it became apparent that the community didn't assist to test things out after as issues were reported when a prerelease was promoted to a stable version. These were issues that should've been caught during the prerelease phase too.. Right now, it looks as though it could be happening again as I'm not seeing much in the way of feedback either besides a report about Android 12 compatibility issues with the 10 prerelease that was then fixed and one comment from a single person at https://github.com/MaikuB/flutter_local_notifications/issues/17#issuecomment-1123737372 that the changes are working well on Android.

**Comment by Onheil13** [comment]
Sorry for the late response. I was kind a out in the wild for some time. After testing on a new project and some investigation made, this error appears non-existent and only occurs in the old project, and the issue was resolved by importing the whole project again and updating all dependencies before running `flutter pub get`. Will be closing this issue since it cannot be reproduced anymore.
