### ISSUE TITLE
IOS Deprecated Code in FlutterLocalNotificationsPlugin.m

### ISSUE THREAD

**Issue by mrr358** [MaikuB/flutter_local_notifications#1592]
**Describe the bug**
Using Xcode to build my Flutter app I am generating no less than 34 Deprecation messages for Flutter_Local_Notifications of which this is one example

/usr/local/Caskroom/flutter/2.8.1/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-9.5.2/ios/Classes/FlutterLocalNotificationsPlugin.m:935:34: 'UILocalNotification' is deprecated: first deprecated in iOS 10.0 - Use UserNotifications Framework's UNNotificationRequest
FlutterLocalNotificationsPlugin.m

Clicking on the module it displays the following code within the xcode editor:

#import "FlutterLocalNotificationsPlugin.h"

@implementation FlutterLocalNotificationsPlugin {
  FlutterMethodChannel *_channel;
  bool _displayAlert;
  bool _playSound;
  bool _updateBadge;
  bool _initialized;
  bool _launchingAppFromNotification;
  NSUserDefaults *_persistentState;
  NSObject<FlutterPluginRegistrar> *_registrar;
  NSString *_launchPayload;
  UILocalNotification *_launchNotification;
}
...

With the final line of the code indicated as deprecated

I have cleared and re-installed cocoapods on several occasions
I note it references 9.5.2 in the error message which I believe references the latest release or else is a remarkable coincidence
My pubspec.yaml file has:
  flutter_local_notifications: ^9.4.1
but I believe this means it will grab the latest release

**To Reproduce**
1. From Android Studio right click IOS, select Flutter, open /IOS module in xcode
2. On top menu - Click on Product > Archive  - to build a release
3. Deprecated messages appear in build window

**Expected behaviour**
This deprecation dates back to IOS 10 so not expecting to see any deprecation messages
I'm concerned it will prevent me from publishing my app on the app store

**Sample code to reproduce the problem**
It's not in my code but in the plugin code shown above.
My app works fine and notifications are generated as expected in Android and IOS

My first issue - so apologies in advance if I haven't complied with all conventions

**Comment by MaikuB** [comment]
This warning has been there since the beginning and as it's warning, shouldn't cause rejections. No one else has reported rejections either since the time this plugin has been around. If you're that concerned about this, note that this has been addressed in the 10.0.0 pre-release

**Comment by mrr358** [comment]
Thanks for the swift response - I was taken back by the number of warnings - but sounds like a resolution is in hand so all good and will close this now.

**Comment by MaikuB** [comment]
Are you able to share all the warnings you were setting? Besides this issue, others should be have version checks around them unless Apple requires some changes to suppress them that would require investigation into. PRs on other warnings would be welcome

**Comment by mrr358** [comment]
Is this what you need?
[errorlog.pdf](https://github.com/MaikuB/flutter_local_notifications/files/8782424/errorlog.pdf)
