### ISSUE TITLE
Not getting payload in onSelectNotification method when app is terminated

### ISSUE THREAD

**Issue by hiashutoshsingh** [MaikuB/flutter_local_notifications#1594]
**Describe the bug**

**To Reproduce**

1. Set Notification with payload
2. Click on notification when app is in terminated state
3. Observe

**Expected behavior**
Ideally when tapping the notification payload should get retrieved this is working for foreground state but not when app is terminated(removed from app stack), I verified by storing the last payload value in sharedpreferences. I am trying to redirect to a particular screen on the basis of payload which is working for foreground but not in terminated state of app.

```
Flutter version: 2.10.0
flutter_local_notifications: 9.3.2
```

**Sample code to reproduce the problem**
```
  var initializationSettingsAndroid = AndroidInitializationSettings('@mipmap/ic_launcher');
  var initializationSettingsIOS = IOSInitializationSettings(
      requestAlertPermission: true,
      requestBadgePermission: false,
      requestSoundPermission: false,
      onDidReceiveLocalNotification: (id, title, body, payload) async {});
  var initializationSettings = InitializationSettings(iOS: initializationSettingsIOS, android: initializationSettingsAndroid);


  /// listing onClick event of notification
  await flutterLocalNotificationsPlugin.initialize(initializationSettings, onSelectNotification: (String payload) async {
    debugPrint('payload $payload');
    if (payload.contains('keyword')) {
        /// navigate to screen
    }
    
  });
```

I have written the above code in main.dart before the runApp.
Anyhelp and guidance would be appreciated.

Thanks!

**Comment by DhrumilBhayani** [comment]
I had Same Problem i did  following steps :
1. Initialize notificationAppLaunchDetails in main() function like this :
```
NotificationAppLaunchDetails? notificationAppLaunchDetails =
      await flutterLocalNotificationsPlugin.getNotificationAppLaunchDetails();
```

2.  check if app is opened by NotificationTap :
```
  if (notificationAppLaunchDetails?.didNotificationLaunchApp ?? false) {

   // String?  selectedNotificationPayload = notificationAppLaunchDetails!.payload;
   // use notificationAppLaunchDetails!.payload for getting Notification Payload
  }
```

**Comment by MaikuB** [comment]
This is behaving as expected and the docs cover how you're meant to deal with this scenario and this is the same as the answer @DhrumilBhayani provided
