### ISSUE TITLE
How to create notification with custom xml layout

### ISSUE THREAD

**Issue by DhrumilBhayani** [MaikuB/flutter_local_notifications#1599]
Hii I want to show notification with custom xml layout(shown below) is it possible ?

Just like this :
![IMG-20220505-WA0002](https://user-images.githubusercontent.com/47532256/168606916-3736d90a-9091-47eb-83f0-3cc4da7537f6.jpg)

i want to show logo and title like this.

Thanks in advance

**Comment by MaikuB** [comment]
No is isn't. This would be something you'd need to code for in your own app
