### ISSUE TITLE
小米手机，本地通知。不能策划删除

### ISSUE THREAD

**Issue by Aaronwk** [MaikuB/flutter_local_notifications#1605]
小米手机。应用在后台的时候。收到本地通知。然后这条通知只能在点击的时候才可以消失。 侧滑的时候不能删除这条通知

**Comment by MaikuB** [comment]
If you have an issue to report, please do so using English. If you can't do so then I'd advise you find a community speaks the same language you use so they can help you out

**Comment by MaikuB** [comment]
Closing due to lack of response (in English).
