### ISSUE TITLE
notifications when the app is in Terminated state

### ISSUE THREAD

**Issue by Jules369-ZM** [MaikuB/flutter_local_notifications#1608]
I am not able to get notifications when the app is in terminated state. please i need your help.
you can clone my project here  https://github.com/Jules369-ZM/notify.git

**Comment by Jules369-ZM** [comment]
@MaikuB thank you, for my repository you can check the master branch.

**Comment by MaikuB** [comment]
As mentioned in previous post, I can't help on a per individual basis and have mentioned where to go for this. Moreover, your app doesn't use this plugin. General comment here to help other maintainers, if you're going to raise an issue on a repository/library, please ensure it is to do with said repository/library
