### ISSUE TITLE
Introducing ios chat layout

### ISSUE THREAD

**Issue by iosephmagno** [MaikuB/flutter_local_notifications#1615]
Hello @MaikuB, is it possible to introduce the latest ios chat layout with avatar and app icon on the left? Pic below

![2599E12D-71F2-46FD-9830-58B4D452A595](https://user-images.githubusercontent.com/83366073/171165156-ffd1f0bf-a05a-4b2d-8fd7-e791ee9d6ab3.jpeg)

**Comment by MaikuB** [comment]
Please see https://github.com/MaikuB/flutter_local_notifications/issues/1525

Closing as a duplicate

**Comment by iosephmagno** [comment]
Hello @MaikuB, I looked at #1525 and I think that we can maybe implement a work around.

As for that Apple link, didReceive is intended to update received content on the fly before showing notification. In their doc, they mention that that could be useful to for example decrypt an encrypted payload.

By using FCM, we already have access to notification payload and can do whatever we want with it before displaying notification via flutter_local_notification. For example, in our app we decrypt all messages from payload (we are an e2ee messenger) and then show local notification with a decrypted text.

What we would need is a notification's theme where we pass two images (app_logo and user_avatar) and that will display these two images in notification badge as in below example. Since UI of local notification badge has nothing to do with native code, I think this might be doable. Did I miss something?

![171165156-ffd1f0bf-a05a-4b2d-8fd7-e791ee9d6ab3](https://user-images.githubusercontent.com/83366073/174559995-3fbda324-85ff-4085-9ace-b1218f664a7b.jpeg)

**Comment by iosephmagno** [comment]
Just noticed this is wrong - "Since UI of local notification badge has nothing to do with native code, I think this might be doable on both ios and android".

But since required layout is available on both ios/android platforms, above rationale still makes sense (plugin could just provide the theme).
