### ISSUE TITLE
How to mute Flutter Notifcation for certain Time?

### ISSUE THREAD

**Issue by Programmerflash** [MaikuB/flutter_local_notifications#1616]
I have feature in app in which user can mute notifications for like 2 hours, 5 hours and 12 hours.
I have 5 notification that displays on certain time DAILY.
So if user has mute the notification Let say for 5 Hours. The notification that has time to display in next 5 hours. It will be cancel automatically(only for that day).
Right now I am using [workmanager](https://pub.dev/packages/workmanager) to achieve this but nothing right is happening

  `Here is my code

       void callbackDispatcher() {
       Workmanager().executeTask((String taskName, dynamic inputData) {
       String path = '/data/user/0/com.salamgram.salamgram/app_flutter';
       File file = File('$path/mute.txt');
       file.writeAsString('0');
       return Future<bool>.value(true);
      });
      }`

`And For muting Notification

       Workmanager().registerOneOffTask('mute', 'notification',
          initialDelay: Duration(hours: muteNotificationTime),);

`
But nothing is happening right. Is there any feature in plugin to do this? Or what else is the correct way of achieving it. Like whatsapp mute notification feature.

**Comment by MaikuB** [comment]
No there isn't such functionality and isn't the responsibility for a plugin to provide such capabilities. What you described is the responsibility of your app to manage and as explained in https://github.com/MaikuB/flutter_local_notifications/issues/1613#issuecomment-1153481245, if you need with your specific app then this isn't the forum for it. It also looks like you're trying to use plugins without understanding the native APIs that you're working with. This is actually a prerequisite so please ensure you spend the time to understand what you're working with on each platform
