### ISSUE TITLE
Custom sound is not working after build apk, works only when i debug over usb

### ISSUE THREAD

**Issue by santamayengb** [MaikuB/flutter_local_notifications#1617]

**Comment by MaikuB** [comment]
Sounds as though you may not have followed the instructions for release builds as described at https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#release-build-configuration. Please check and cross-reference with your app and the example app can used as a reference too

If you believe there's a bug with the plugin, please use the bug report template if you believe there's a bug, read the info mentioned in the template and provide the information that it requests.
