### ISSUE TITLE
Silent notifications not working on ios release build

### ISSUE THREAD

**Issue by iosephmagno** [MaikuB/flutter_local_notifications#1620]
Hello @MaikuB, we are debugging this strange issue at #8277
https://github.com/firebase/flutterfire/issues/8277#issuecomment-1147316656
https://github.com/firebase/flutterfire/issues/8277#issuecomment-1148715908

Basically, silent notifs:
- dont show in background mode in release build
- may or may not show in foreground mode in release build

We are taking official firebase messaging example as reference.
https://github.com/firebase/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example

We think that the issue might be related to firebase messaging, but we are wondering if it might also be an issue with flutter local notification.

Can you please have a look? The entire flutter community is stalled because of this crowd issue.

**Comment by iosephmagno** [comment]
The doubt is because the silent notifications arrive on the device as shown in vid 2 from this comment https://github.com/firebase/flutterfire/issues/8277#issuecomment-1148715908

What is missing is showing the badge.

**Comment by iosephmagno** [comment]
@MaikuB We edited the firebase messaging official demo. https://github.com/firebase/flutterfire/issues/8277#issuecomment-1149028107

Results is strange: Silent notification works in foreground and don't work in background.
Can you please have a look? We tend to think this is a firebase messaging but maybe you see something.
If you can make time, thx for any help you can provide.

**Comment by iosephmagno** [comment]
Apologies, just forgot to close this. Yes it was FCM issue

**Comment by Kiruel** [comment]
@iosephmagno How you fix it ? Got the same problem works on debug/profile mode but not in release mode.
