### ISSUE TITLE
Xiaomi notification settings

### ISSUE THREAD

**Issue by gdet** [MaikuB/flutter_local_notifications#1626]
Hello,
I have created successfully the notifications for other devices except xiaomi. I know that this is an issue that is already mentioned but I was wondering how can I fix it by changing app settings. I have already enabled notifications, sound etc from inside application's settings but they are still not working when you delete the application from running in the background. Have I done something wrong or there is no solution to enable the notifications manually?  

    var androidChannel = AndroidNotificationDetails(
        'PROMPTED_1', 'PROMPTED',
        importance: Importance.max,
        priority: Priority.high,
        playSound: true,
        fullScreenIntent: true,
        showWhen: true,
        timeoutAfter: 4000);

    var dateTime900 = DateTime(DateTime.now().year, DateTime.now().month,
        DateTime.now().day, startHour, startMinute, 0);
    var platformChannel900 = NotificationDetails(android: androidChannel);

    await flutterLocalNotificationsPlugin.zonedSchedule(
      0,
      'Hello!',
      'Press to answer the questionnaire',
      tz.TZDateTime.from(dateTime900, tz.local),
      //RepeatInterval.everyMinute,
      platformChannel900,
      payload: 'New payload',
      androidAllowWhileIdle: true,
      uiLocalNotificationDateInterpretation:
          UILocalNotificationDateInterpretation.absoluteTime,
      matchDateTimeComponents: DateTimeComponents.time,
    );

Thank you

**Comment by RokasUrb** [comment]
You should probably prompt the user to enable autostart and open the settings page of your app on xiaomi phones

**Comment by PoeMcMoe** [comment]
https://stackoverflow.com/questions/34149198/how-to-enable-auto-start-for-my-app-in-xiaomi-programmatically

**Comment by gdet** [comment]
Two people have answered my question but for some reason the comments were erased. The solution is to enable autostart and also they added this link https://stackoverflow.com/questions/34149198/how-to-enable-auto-start-for-my-app-in-xiaomi-programmatically

thank you

**Comment by iqfareez** [comment]
Hi. Yes correct, the Autostart settings is one of the culprits for these notification issues, some Chinese OEMs (Xiaomi, Vivo etc.) put restriction to "save battery life". You can read [this article](https://www.howtogeek.com/805157/google-explains-your-android-phones-broken-notifications/). They basically explain how these OEMs frustrates the developer

While there is no way to enable the **Autostart**, you can ask user to enable it. Here what you gonna do:
-  Detect if the phone supports Autostart settings, you can use package like [auto_start_flutter](https://pub.dev/packages/auto_start_flutter), [disable_battery_optimization](https://pub.dev/packages/disable_battery_optimization) or [android_autostart](https://pub.dev/packages/android_autostart).
- Show prompts/dialog etc to ask user to go to settings and enable Autostart, example:
![image](https://user-images.githubusercontent.com/60868965/174574438-49286245-6b61-48bc-be15-5a30ea1add68.png)
