### ISSUE TITLE
String identifier of notifications on iOS

### ISSUE THREAD

**Issue by devxpy** [MaikuB/flutter_local_notifications#1629]
Thanks @MaikuB, for such amazing  work on this plugin!

This issue is somewhat related to https://github.com/MaikuB/flutter_local_notifications/issues/1353. 

- iOS has an API that supports a String [identifier](https://developer.apple.com/documentation/usernotifications/unnotificationrequest/1649634-identifier). 
- APNs supports providing a String `collapse-key`, and then removing notifications using [removeDeliveredNotifications](https://developer.apple.com/documentation/usernotifications/unusernotificationcenter/1649500-removedeliverednotifications). However `FlutterLocalNotificationsPlugin.cancel()` only takes an `int` value. 

I was wondering if these native APIs can be accessed via this plugin?

Background - integer ids for notifications can be a bit limiting -- for e.g. our backend messages are identified via a UUID which can't be represented easily as a 32-bit integer.

On android this problem can be circumvented using tags, not sure how to do this on iOS.

**Comment by MaikuB** [comment]
No they're not so you'll need to look at submitting PRs or roll your own solution. An integer id was used for covering how the primary ID on Android is an integer and this is how majority of notification libraries on other platforms tackle this too. For either feature
