### ISSUE TITLE
Find which notification is clicked when app is terminated.

### ISSUE THREAD

**Issue by gdet** [MaikuB/flutter_local_notifications#1633]
Hello,
I have multiple notifications with different payloads but I want only one to redirect to a page. Everything works fine if the app is running but when it is terminated I cannot differentiate the notifications. I used  flutterLocalNotificationsPlugin.getNotificationAppLaunchDetails() as you suggest and also used your example in https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/example/lib/main.dart .
But in your example if I understand correctly you just see if a notification is pressed. I tried to differentiate them with payload but it seems to be null (I cannot see it's value since the app is terminated). Is there a way to differentiate the notifications and find which one is clicked when the app is terminated?
Thank you

**Comment by MaikuB** [comment]
> But in your example if I understand correctly you just see if a notification is pressed.

No, the payload is shown and using the payload should work. If you've got an issue with this you got an issue elsewhere that you'll need to look into. Given what you written, it could well be that you've misunderstood what is going on in your own code even. Note that I only have spare time to work on the plugin so if you need help with your app, which seems to be the scenario here, then you'll need to reach out to the wider community to get help. I would suggest checking something like the Flutter slack community where there may those who may be actively help with debugging your app, check the code etc
