### ISSUE TITLE
Scheduled android notifications doesn't  work when using "firebase_messaging 11.4.2"

### ISSUE THREAD

**Issue by hm21** [MaikuB/flutter_local_notifications#1634]
Scheduled android notifications doesn't work correctly when using firebase_messaging and close the app completly. The notifications will be sent but too late which have mostley a delay from 30-60min.

I testet it with a samsung galaxy s10 with the default [example app](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications/example) and just add the packages [firebase_messaging ^11.4.2](https://pub.dev/packages/firebase_messaging) / [firebase_core ^1.7.0](https://pub.dev/packages/firebase_core) and use the package version from flutter_local_notifications: ^9.6.1. The delay which i used was 10min.

I tried it also on iOS but it seems like the bug exist only on android.

**Comment by MaikuB** [comment]
Closing due to lack of further response
