### ISSUE TITLE
Flutter local notification not installing in my project.

### ISSUE THREAD

**Issue by yangsh91** [MaikuB/flutter_local_notifications#1639]
I tried Executed the command "flutter pub add flutter_local_notifications"
It's not installing my toy project and the error message is "Because flutter_local_notifications depends on flutter_local_notifications, version solving failed"

How to installing this plugin?  My flutter version is 3.0.4

**Comment by zzzhhhhh001** [comment]
Reduce your flutter version. At present, the plug-in should only support version 2.0

**Comment by MaikuB** [comment]
If you believe it's a bug to do with the plugin then please provide a minimal app with steps to reproduce this. As for the comment around Flutter version support, everytime changes are done to the repo, this triggers builds on the latest stable release of Flutter and 3.0 has been out for some time now. There have been no issues I've seen with CI builds etc. If it was to do with the version of Flutter then I'd expect to see more widespread reports on this. Furtherrmore, I was able to create a brand new app and add in the plugin as a dependency. This was on version 3.0.4. I was also able to run the example on said version. Based on what you said, you likely have other version constraint issue to look into to resolve.
