### ISSUE TITLE
ref in console on cancel notification

### ISSUE THREAD

**Issue by mydwa** [MaikuB/flutter_local_notifications#164]
Hi there,
Actually it is not a issue...
When I cancel one notification, one "reference" (String like "17E8-9C35") is displayed in the debug console. Could you please explain what it is?
And why on creation there is not such ref printed?

I think, this ref is the local mobile notification reference, if so it would be great to have same info on creation. (if you remember my first raised issue ;-) )

**Comment by MaikuB** [comment]
there's no code in the library to print any of these statements so I don't know what that is or where that is coming from at the moment. Could be from Flutter or the native platform's debugger output

**Comment by jonahgreenthal** [comment]
I've seen this too, for what it's worth—let me know if I can help track it down.

**Comment by MaikuB** [comment]
Should clarify there is some code to print out errors (you can search the repository for "print" and "NSLog"). So it's outside of the library

@jonahgreenthal you're more than welcome to help track it down but would seem to be "outside" of the library

**Comment by MaikuB** [comment]
Closing this as it's not something I've coded to have to printed out so it's coming outside of the plugin
