### ISSUE TITLE
Real time control whether the prompt tone is effective

### ISSUE THREAD

**Issue by zzzhhhhh001** [MaikuB/flutter_local_notifications#1640]
The initial setting of Android system only has the function of setting icons. Is there any way to control whether the prompt tone takes effect after I push the notice

**Comment by zzzhhhhh001** [comment]
After I create a notification, how can I make it display normally without playing the prompt tone

**Comment by zzzhhhhh001** [comment]
If this plug-in does not support this function, please close this issue. Thank you for your patience

**Comment by MaikuB** [comment]
Looks like you're talking about having a notification without sound. This is supported with API docs available for you to check on how to do this and already covered in the example app too
