### ISSUE TITLE
[flutter_local_notifications] [Android] can we specify the color of the icon only?

### ISSUE THREAD

**Issue by zopagaduanjr** [MaikuB/flutter_local_notifications#1642]
Can we achieve the colored icons below? (chat icon blue, gmail icon red)

![image](https://user-images.githubusercontent.com/38291023/177333352-243e8276-44ee-46af-86cc-6227e4ae3c68.png)

currently when AndroidNotificationDetails' color property is set, it sets both the icon & app name's color

![image](https://user-images.githubusercontent.com/38291023/177334047-555e19cb-709e-448c-b2f3-fb8e71a1c2b9.png)

https://github.com/MaikuB/flutter_local_notifications/blob/870b8a4714a222a92de688e135d8a91fb0fac1d7/flutter_local_notifications/lib/src/platform_specifics/android/method_channel_mappers.dart#L191-L194

**Comment by zopagaduanjr** [comment]
seems like not possible since notification UI behaves differently depending on android version

Behavior when [color](https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/AndroidNotificationDetails/color.html) is set to `Colors.red` on Android versions 5 to 12:

![different_notif_ui](https://i.imgur.com/PbQuczf.png)

**Comment by MaikuB** [comment]
Closing since you've already found it's not possible and this isn't to with plugin functionality but to do with Android itself

**Comment by NabinGrz** [comment]
Can anyone tell me that which "StyleInformation" is used in the top picture?
