### ISSUE TITLE
Need a help About Saving notifications.

### ISSUE THREAD

**Issue by tonmooy** [MaikuB/flutter_local_notifications#1643]
Hello Sir,

I setup local notification on my apps and its work well.

But I have also e notification page like facebook where I store my firebase push. notification offline   when it's appear.

but I don't know how can I save local notification  data offline after notification appear on notification bar.

I want to save notification on hive db,  when my app is on background or closed state but if notification appear I want to save it offline

how can I listen local notification background like firebase push notification.

**Comment by MaikuB** [comment]
No such capability is available. This is something you'd need to submit a PR for
