### ISSUE TITLE
Set Edge Lighting Color is it possible?

### ISSUE THREAD

**Issue by manylittlestorms** [MaikuB/flutter_local_notifications#1646]
Hello,
Is it possible to set edge lighting color with this package?
As you can see [here](https://play.google.com/store/apps/details?id=com.edgeround.lightingcolors.rgb&hl=it&gl=US) there are many apps that can do it natively. Can we do it on Flutter?

**Comment by MaikuB** [comment]
Edge lighting is specific to some devices and there isn't any functionality in the notification APIs for it. There's one for LED colour and it's demonstrated in the example app. It's possible that it will leverage a device's edge lighting but this would be something you need to verify
