### ISSUE TITLE
No didReceiveNotification functionality. (such as Firebase Cloud Messaging)

### ISSUE THREAD

**Issue by TomasWard1** [MaikuB/flutter_local_notifications#1648]
**Describe the bug**
I am scheduling a notification and need to update things in the app when the notification arrives (at a later date). How can I manage this? Currently, the only functionality available is onSelectedNotification()

**To Reproduce**
1. Schedule a notification
2. Receive it
3. Try to automatically update something (like a notification count in the DB)
4. You will see it is impossible (maybe not?)

**Comment by MaikuB** [comment]
What you've described isn't a bug but to do with an unsupported feature. If you're after something like this then you'll need to look at submitting a PR
