### ISSUE TITLE
Scheduling a daily notifications with today's date as its body

### ISSUE THREAD

**Issue by sergiuiacob1** [MaikuB/flutter_local_notifications#165]
Hello! My "issue" is more of a question. I'm not sure what's the best way to solve my problem, so I'll explain it below, maybe somebody can give me an idea.

My app sends a daily notification. The body of the notification is today's date (For example: February 7, 2019). The problem is that every following notification will have the same body, so on February 8 I'll receive this body: February 7, 2019.

What's the easiest way to solve this for both Android/iOS?

I thought I could schedule the next notifications for a month, let's say, and have like 30 individual notifications. Each individual notification would have its own date. But I'm not sure how the schedule function works, if there is a thread kept in memory. If so, I think having 30 threads running in the background might be a little too much.

Thanks a lot in advance. I really appreciate any thoughts on this. Great job with the plugin, @MaikuB!

**Comment by MaikuB** [comment]
Thanks for the compliments. You could schedule a bunch of them but would suggest as a best practice to await the call to schedule a single notification before scheduling the next one.  My understanding is that Flutter is single-threaded to begin with. 

Alternative that would've probably would've been better is if a callback is provided for when a notification is shown. This requires headless execution from Flutter as that  allows Dart code to be invoked even when the app is terminated but there are issues with that at the moment.

Another alternative that is more difficult is you would have to dive into the native iOS APIs and Android APIs code to do this as you can hook into when a notification is shown and then write code in Objective-C/Swift and Java/Kotlin to schedule the next one with a different body

**Comment by sergiuiacob1** [comment]
Thank you a lot for your response! So, from my understanding, the second practice is the best one. That can't be implemented yet until some Flutter issues are solved. I'll go with the first method for now, it is a good idea to await for the current notification, that will surely decrease the background resources being utilized. 

Thank you!

**Comment by MaikuB** [comment]
Closing since this has been answered
