### ISSUE TITLE
Xcode error need help

### ISSUE THREAD

**Issue by notufure** [MaikuB/flutter_local_notifications#1651]
error message
Uncategorized (Xcode): Command CompileSwiftSources failed with a nonzero exit code

Parse Issue (Xcode): Expected identifier or '('
/Users/notufure/Documents/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-9.7.0/ios/Classes/FlutterLocalNotificationsPlugin.m:16:0

Semantic Issue (Xcode): Use of undeclared identifier 'SHOW_METHOD'
/Users/notufure/Documents/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-9.7.0/ios/Classes/FlutterLocalNotificationsPlugin.m:134:14
2

Could not build the application for the simulator.
Error launching application on iPhone 13 Pro.
Exited

**Comment by MaikuB** [comment]
Unable to help you there as this looks like it's an issue specific to your machine. The error would suggest a compilation error but there's no reports of this happening by anyone else or on build servers being used by the repository. The issues reported don't make much sense either. You may need to reach other to wider community to get an issue like this sorted out
