### ISSUE TITLE
How to catch "clear" action on status bar

### ISSUE THREAD

**Issue by wahyu-handayani** [MaikuB/flutter_local_notifications#1652]
Hi, as we know that ```flutter_local_notifications``` package has property ```onSelectNotification``` to catch the action when user click notification from status bar. In android, when I clear notification from status bar, the badge icon on app will automatically be removed. For now I am doing it in iOS, while in iOS.. I am using ```flutter_app_badger``` to show badge icon app. The case that I would like to ask is... is there a property like ```onSelectNotification``` that catch user action when user click ```clear``` or ```clear notification``` from status bar of iOS device so I can trigger the function to remove badge icon app

**Comment by MaikuB** [comment]
No there isn't. This is something you'd need to submit a PR for
