### ISSUE TITLE
[flutter_local_notifications_linux] path package version conflict 

### ISSUE THREAD

**Issue by amirazizi4861** [MaikuB/flutter_local_notifications#1656]
**Describe the bug**
Flutter 2.10 (Dart 2.16) or below still uses path version 1.8.0 but flutter_local_notifications_linux is using path 1.8.1. This causes version conflicts for both flutter_test and flutter_local_notifications_linux dependencies.

**To Reproduce**
1. Use flutter version 2.10 or below with the latest flutter_local_notifications (9.7.0)
2. The below error will be displayed
3. Current workaround is to use dependency_override on path package or use version 9.5.3

`Because flutter_local_notifications_linux 0.5.0+1 depends on path ^1.8.1 and no versions of flutter_local_notifications_linux match >0.5.0+1 <0.6.0, flutter_local_notifications_linux ^0.5.0+1 requires path ^1.8.1.
And because every version of flutter_test from sdk depends on path 1.8.0, flutter_test from sdk is incompatible with flutter_local_notifications_linux ^0.5.0+1.
And because flutter_local_notifications 9.7.0 depends on flutter_local_notifications_linux ^0.5.0+1 and no versions of flutter_local_notifications match >9.7.0 <10.0.0, flutter_test from sdk is incompatible with flutter_local_notifications ^9.7.0.
So, because flutter_tourplus depends on both flutter_local_notifications ^9.7.0 and flutter_test from sdk, version solving failed.
pub get failed (1; So, because flutter_tourplus depends on both flutter_local_notifications ^9.7.0 and flutter_test from sdk, version solving failed.)`

**Expected behavior**
There should not be a conflict in dependencies for the latest package if the sdk used is correct (Dart 2.12)

**Comment by MaikuB** [comment]
Thanks for pointing this out. I believe the issue took place as a result of https://github.com/MaikuB/flutter_local_notifications/pull/1602

@proninyaroslav if I'm not mistaken, it should be ok to downgrade the dependencies that were bumped in that PR. Is that correct or was there another reason why they were bumped?

**Comment by proninyaroslav** [comment]
@MaikuB 
You're right, it's a minor update of the `path` package, that I updated along with other dependencies. Here is the changelog for version 1.8.1:
```
Don't crash when an empty string is passed to toUri().
```
