### ISSUE TITLE
[flutter_local_notifications] [Android] Use Java 8+ APIs available through desugaring instead of ThreeTenABP

### ISSUE THREAD

**Issue by mirland** [MaikuB/flutter_local_notifications#1661]
[ThreeTenABP](https://github.com/JakeWharton/ThreeTenABP) has not been used in the community for a while. I[nstead of that, we should use just Java 8 features through desugaring](https://developer.android.com/studio/write/java8-support
). 
Furthermore, the ThreeTenABP readme says:

```
Attention: Development on this library is winding down. Please consider switching to Android Gradle plugin 4.0, java.time.*, and its [core library desugaring](https://developer.android.com/studio/write/java8-support#library-desugaring) feature in the coming months.
```

**Comment by MaikuB** [comment]
This has already been done in the 10.0 prerelease so will close this issue

**Comment by mirland** [comment]
Cool! Thanks!
