### ISSUE TITLE
Scheduled notifications that have been presented still show as pending

### ISSUE THREAD

**Issue by 826327700** [MaikuB/flutter_local_notifications#1665]
```dart
np.zonedSchedule(
			pendingNotificationRequests.length+1,
			title,
			body,
			scheduledDate,
			details,
			uiLocalNotificationDateInterpretation: UILocalNotificationDateInterpretation.absoluteTime,
			androidAllowWhileIdle: true,
			matchDateTimeComponents:DateTimeComponents.time,
			payload:payload
		);
```
I'm sure I used DateTimeComponents.time for matchDateTimeComponents property, I hope that scheduled notification only working once.

**Comment by MaikuB** [comment]
Your code didn't align with your intention. You've scheduled a daily notification so that's why there's still pending notifications. Please take a closer look at the docs and example app
