### ISSUE TITLE
onSelectNotification is not called when the app in background

### ISSUE THREAD

**Issue by mkassir95** [MaikuB/flutter_local_notifications#1666]
I am trying to click on the notification when the app is in the background, the onSelectNotification is not being called

**Comment by MaikuB** [comment]
Please provide a recording of you reproducing the issue using the example app

**Comment by lucasgsa** [comment]
`onSelectNotification` is called only when app is already open.
Probably when you click in notification when is closed, it opens the app, so, when app is opened you can add a verify if is opened by the notification click using 
```
NotificationAppLaunchDetails? details = await _flutterLocalNotificationsPlugin?.getNotificationAppLaunchDetails()
if (details != null && details.didNotificationLaunchApp) {
  notificationManager.onSelectNotification(details.payload);
}
```
and it maybe works

**Comment by jahid-hasan-polash** [comment]
@lucasgsa It doesn't in iOS. It doesn't call any of the handlers if the app is in the background.

**Comment by MaikuB** [comment]
Closing this as original poster hasn't provided further information. If any others have an issue then open a separate issue using the bug report template with a link to a repository hosting a minimal app that can reproduce the issue
