### ISSUE TITLE
Android Notification Channel Management

### ISSUE THREAD

**Issue by mrmikezhang** [MaikuB/flutter_local_notifications#167]
Hi, first of all, thanks for a great plugin. I have got everything to work perfectly, however I do have one question/request, is it possible to modify a channel once it's created? If not, do you plan on adding this feature in the near future?

Thank you very much

**Comment by MaikuB** [comment]
No it's possible at the moment. What kind of modifications are you looking to do? Android restricts the ability to change most details once a channel has been created. Note that I'm trying to avoid having platform-specific methods exposed by the plugin as well, so may have to look at using flags

**Comment by mrmikezhang** [comment]
Thanks for the quick response. That's great to hear, maybe I am doing it wrong then.

So basically I want to change the channel name and maybe the description as well, so that it is synced with the name a user has defined in the app. Now, it seems once a notification "category/channel" is created, it won't let you update it, even though the same channel id is used, but with a different channel name.

This is a code snippet I am currently using.
`var androidPlatformChannelSpecifics = AndroidNotificationDetails(
      'id1', 'General', 'General Notifications',
      icon: '@drawable/notification_icon',
      largeIconBitmapSource: BitmapSource.Drawable,
      largeIcon: '@drawable/notification_icon_large',
      color: Colors.blue.shade800,
      ongoing: true,
      style: AndroidNotificationStyle.BigText,
      importance: Importance.Max, 
      priority: Priority.High);`

If I later want to change the name to "Generic" using the same channel id, it won't update the actual name of the channel, but notification still works fine.
`var androidPlatformChannelSpecifics = AndroidNotificationDetails(
      'id1', 'Generic', 'General Notifications',
      icon: '@drawable/notification_icon',
      largeIconBitmapSource: BitmapSource.Drawable,
      largeIcon: '@drawable/notification_icon_large',
      color: Colors.blue.shade800,
      ongoing: true,
      style: AndroidNotificationStyle.BigText,
      importance: Importance.Max, 
      priority: Priority.High);`

Unless there's a specific way to do it?

**Comment by MaikuB** [comment]
Right now, you'd have to uninstall the app and run it again with the updated code/name. There's a guard in the plugin code at the moment to not call the method that creates the channel (which is also used to update the name) so that's why it's not working. This was done to avoid calling the notification channel APIs on trying to send every notification.  I'll see about adding flags as mentioned in my previous response

**Comment by mrmikezhang** [comment]
Alright mate, thank you very much. :)

**Comment by MaikuB** [comment]
The option for updating a channel should now be available in v0.5.2

**Comment by mrmikezhang** [comment]
Wonderful! Thanks for letting me know mate, I will test it asap.

**Comment by MaikuB** [comment]
Closing this. Feel free to reopen if you run into issues or create a new one
