### ISSUE TITLE
How to show updated data in repeat Notification 

### ISSUE THREAD

**Issue by neelayak** [MaikuB/flutter_local_notifications#1670]
So I tried to save data in hive and try to see when the notification gets called again wether the data can be updated or not and I was getting the same data

`
    Future<void> _repeatNotification() async {

    const AndroidNotificationDetails androidPlatformChannelSpecifics =
        AndroidNotificationDetails(
            'repeating channel id', 'repeating channel name',
            channelDescription: 'repeating description');
    const NotificationDetails platformChannelSpecifics =
        NotificationDetails(android: androidPlatformChannelSpecifics);
    var box= await Hive.openBox('bodybook');
    var data= box.get('key');
    var no=box.get('no');
    no++;
    await flutterLocalNotificationsPlugin.periodicallyShow(0, 'repeating title$no',
        'repeating body', RepeatInterval.everyMinute, platformChannelSpecifics,
        androidAllowWhileIdle: true);
 }
`

I tried this but the value was not getting updated is there any way to achieve this?

**Comment by MaikuB** [comment]
There aren't any notification APIs to do this. You have to look at this from a different approach e.g. native APIs that periodically run a job that happens to be to show a notification with updated information. The API you're calling is meant for showing the same notification over and over
