### ISSUE TITLE
No implementation found for method getNotificationAppLaunchDetails on iOS

### ISSUE THREAD

**Issue by HamedMP** [MaikuB/flutter_local_notifications#1671]
I'm getting the following error when I want to run the project from Xcode. It causes the app to freeze on the Splash screen (both on the device and in the simulator). 

The Android app works well. I wanted to check what iOS-specific changes might have happened in the last version. There is a published versioned of the app which uses version `^8.1.1+1` of the library with no problems 🙌 

I also tried commenting to check for notifications in the startup, but then I got an issue similar to #238. None of the suggestions there worked. I've been doing full clean and `pod install` many times before the build but no help. 

```swift
2022-08-13 20:53:29.142372+0200 Runner[1748:3520328] Metal API Validation Enabled
2022-08-13 20:53:35.414722+0200 Runner[1748:3520606] flutter: The Dart VM service is listening on http://127.0.0.1:64724/oA-rdAnFg-4=/
2022-08-13 20:53:42.252745+0200 Runner[1748:3520563] [VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: MissingPluginException(No implementation found for method getNotificationAppLaunchDetails on channel dexterous.com/flutter/local_notifications)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
<asynchronous suspension>
#1      MethodChannelFlutterLocalNotificationsPlugin.getNotificationAppLaunchDetails (package:flutter_local_notifications/src/platform_flutter_local_notifications.dart:53:9)
<asynchronous suspension>
#2      FlutterLocalNotificationsPlugin.getNotificationAppLaunchDetails (package:flutter_local_notifications/src/flutter_local_notifications_plugin.dart:188:14)
<asynchronous suspension>
#3      main (package:****/main.dart:59:9)
<asynchronous suspension>
```

`flutter doctor` output (on the machine for iOS build only):
```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.70.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

! Doctor found issues in 2 categories.
```

During build time I get the following warnings (probably not related, but maybe good to fix in upcoming versions?) 
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/3755031/184507712-841f62ac-5e05-4193-b806-450030e15608.png">

And the pod info:
<img width="946" alt="image" src="https://user-images.githubusercontent.com/3755031/184507610-afbe323f-dcf0-4696-b939-55938a7a81dc.png">

**Comment by MaikuB** [comment]
There's been no changes in this regard to cause such an issue so I don't know what the cause is here. Might be something you'll need others to help with as if it's an issue with the plugin itself then I'd expect more widespread reports. The code is open-source too you're welcome to use it track down what's going on yourself.

As for the warnings you've mentioned, they aren't related and is to do with code for supporting older iOS versions. I'd need to see how those could be suppressed as they have been raised before but PRs are welcome
