### ISSUE TITLE
Please give me idea of set biweekly or 2 weekly/fortnightly reminder .

### ISSUE THREAD

**Issue by testd2496** [MaikuB/flutter_local_notifications#1678]
### Please give me suggestion.

```
Future<void> setNotificationWeeklyNew(
    String timerTitle, String timerBody, int id, DateTime dateTime) async {
  print("click");
  tz.initializeTimeZones();
  await flutterLocalNotificationsPlugin.zonedSchedule(
      id,
      timerTitle,
      timerBody,
      tz.TZDateTime.from(dateTime, tz.local),

      NotificationDetails(
          android: _androidNotificationDetails, iOS: _iosNotificationDetails),
      androidAllowWhileIdle: true,
      matchDateTimeComponents: DateTimeComponents.dayOfWeekAndTime,
      uiLocalNotificationDateInterpretation:
          UILocalNotificationDateInterpretation.absoluteTime);

  await checkPendingNotificationRequest();
}
```

**Comment by didnteven** [comment]
I have put comments where I have changed code to add another week to now be fortnightly

You will just need to edit the method of _nextInstanceOfMondayTenAM to the time/day you would like ?

Editing their example code below: 

 Future<void> _scheduleMonthlyMondayTenAMNotification() async {
    await flutterLocalNotificationsPlugin.zonedSchedule(
        0,
        'monthly scheduled notification title',
        'monthly scheduled notification body',
        _nextInstanceOfMondayTenAM(),
        const NotificationDetails(
          android: AndroidNotificationDetails('monthly notification channel id',
              'monthly notification channel name',
              channelDescription: 'monthly notificationdescription'),
        ),
        androidAllowWhileIdle: true,
        uiLocalNotificationDateInterpretation:
            UILocalNotificationDateInterpretation.absoluteTime,
        matchDateTimeComponents: DateTimeComponents.dayOfMonthAndTime);
  }

  tz.TZDateTime _nextInstanceOfTenAM() {
    final tz.TZDateTime now = tz.TZDateTime.now(tz.local);
    tz.TZDateTime scheduledDate =
        tz.TZDateTime(tz.local, now.year, now.month, now.day, 10);
    if (scheduledDate.isBefore(now)) {
      scheduledDate = scheduledDate.add(const Duration(days: 1));
    }
    return scheduledDate;
  }
 
  //this has been updated till next Monday fortnight
  tz.TZDateTime _nextInstanceOfMondayTenAM() {
    tz.TZDateTime scheduledDate = _nextInstanceOfTenAM();

 
    while (scheduledDate.weekday != DateTime.monday )  {
      
      scheduledDate = scheduledDate.add(const Duration(days: 1));
    }
      //add extra week(s) here   ------------------------------------------------  >>>>
    int weeks = 1;
    scheduledDate = scheduledDate.add(Duration(days: 7 * weeks));


    return scheduledDate;
  }

**Comment by MaikuB** [comment]
None of the native APIs support this so you'll need to do research into how to achieve what you're after. It could be you need to look into using the native calendar APIs instead

**Comment by markst** [comment]
https://stackoverflow.com/questions/41441124/ios-notification-trigger-fortnightly-and-or-quarterly
