### ISSUE TITLE
Not enter to Calling page when the IOS app is closed by pressing the notification

### ISSUE THREAD

**Issue by A-Eric-J** [MaikuB/flutter_local_notifications#1679]
Hello,
I have a video chat application. everything is fine with android but when the IOS app is closed and a notification comes(a person called me) if i press the notif, it goes to the main page instead of going to the calling page but in android(even when the app is closed) is going to calling page.
here is part of my code:

`const AndroidInitializationSettings initializationSettingsAndroid =  AndroidInitializationSettings('logo');

       IOSInitializationSettings initializationSettingsIos =  IOSInitializationSettings();

      final InitializationSettings initializationSettings = InitializationSettings(
          android: initializationSettingsAndroid,iOS: initializationSettingsIos);

      flutterLocalNotificationsPlugin.initialize(initializationSettings);

      if(Platform.isAndroid){
        await flutterLocalNotificationsPlugin
            .resolvePlatformSpecificImplementation<
            AndroidFlutterLocalNotificationsPlugin>()
            ?.createNotificationChannel(channel);
      }
      else if(Platform.isIOS){
        await flutterLocalNotificationsPlugin
            .resolvePlatformSpecificImplementation<
            IOSFlutterLocalNotificationsPlugin>()
            .requestPermissions(
          alert: true,
          badge: true,
          sound: true,
        );
      }
      
      flutterLocalNotificationsPlugin.initialize(initializationSettings);

      await FirebaseMessaging.instance
          .setForegroundNotificationPresentationOptions(
        alert: true,
        badge: true,
        sound: true,
      );

      await FirebaseMessaging.instance.requestPermission(
        alert: true,
        announcement: false,
        badge: true,
        carPlay: false,
        criticalAlert: false,
        provisional: false,
        sound: true,
      );
    String payload = (await flutterLocalNotificationsPlugin.getNotificationAppLaunchDetails())?.payload;
    MyNotificationObj myNotificationObj;
    if(payload != null){
      myNotificationObj = MyNotificationObj.fromJson(jsonDecode(payload));
    }
    bool goToCall = false;
    var user;
    if(payload != null){
      if(myNotificationObj.type == "call"){
        goToCall = true;
        user = myNotificationObj.user;
        debugPrint(user.toString());
      }
    }
    runApp(
      MyApp(
          goToCall: goToCall,
          user: user),
    );`

if you see i have a var named goToCall and if it's true it goes to calling page if it's false it goes to the main page.
this problem is just in IOS but in Android everything works fine.

**Comment by MaikuB** [comment]
If you believe there's a bug then this will need a link to a repo hosting minimal app that can reproduce the issue

**Comment by MaikuB** [comment]
Closing as further information hasn't been provided. Feel free to reopen if you can do so

**Comment by pistolcaffe** [comment]
@A-Eric-J I also faced the same issue but I found that the ios configuration is missing and the following code solved the problem. Make sure there is nothing missing in your ios configuration.

### AppDelegate.swfit
`if #available(iOS 10.0, *) {
  UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate
}`

You can refer to this link for more details.
https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#general-setup

**Comment by A-Eric-J** [comment]
@pistolcaffe Hey Buddy, you're right, we have to add that line to the AppDelegate.swift , but i don't know why i had problem again in ios. 
because of that i thought to use a trick. and goToCall variable helped me in this way and change its data in ios. and it worked for me.
here is my code:

`bool goToCall = false;
var user;
void main() async {
  HttpOverrides.global = MyHttpOverrides();
  WidgetsFlutterBinding.ensureInitialized();
  SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp])
      .then((value) async {
    await Firebase.initializeApp();
    FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);
    if (!kIsWeb) {
      const AndroidInitializationSettings initializationSettingsAndroid =
      AndroidInitializationSettings('logo');
       IOSInitializationSettings initializationSettingsIos =  IOSInitializationSettings(
       );
      final InitializationSettings initializationSettings = InitializationSettings(
          android: initializationSettingsAndroid,iOS: initializationSettingsIos);
      flutterLocalNotificationsPlugin.initialize(initializationSettings);

      if(Platform.isAndroid){
        await flutterLocalNotificationsPlugin
            .resolvePlatformSpecificImplementation<
            AndroidFlutterLocalNotificationsPlugin>()
            ?.createNotificationChannel(channel);
      }
      else if(Platform.isIOS){
        await flutterLocalNotificationsPlugin
            .resolvePlatformSpecificImplementation<
            IOSFlutterLocalNotificationsPlugin>()
            .requestPermissions(
          alert: true,
          badge: true,
          sound: true,
        );
      }

      await flutterLocalNotificationsPlugin.initialize(initializationSettings
          ,onSelectNotification: selectNotification
      );


      /// Update the iOS foreground notification presentation options to allow
      /// heads up notifications.
      await FirebaseMessaging.instance
          .setForegroundNotificationPresentationOptions(
        alert: true,
        badge: true,
        sound: true,
      );

      await FirebaseMessaging.instance.requestPermission(
        alert: true,
        announcement: false,
        badge: true,
        carPlay: false,
        criticalAlert: false,
        provisional: false,
        sound: true,
      );
    }

    var notificationAppLaunchDetail = (await flutterLocalNotificationsPlugin.getNotificationAppLaunchDetails());
    if(Platform.isAndroid){
      String payload = notificationAppLaunchDetail?.payload;
      MyNotificationObj myNotificationObj;
      if(payload != null){
        myNotificationObj = MyNotificationObj.fromJson(jsonDecode(payload));
      }
      if(payload != null){
        if(myNotificationObj.type == "call"){
          goToCall = true;
          user = myNotificationObj.user;
          debugPrint(user.toString());
          debugPrint("user.toString()");
        }
      }
      runApp(
        MyApp(
          goToCall: goToCall,
          user: user,),
      );
    }
    else if(Platform.isIOS){
      if(!notificationAppLaunchDetail.didNotificationLaunchApp)
        runApp(
          MyApp(
            goToCall: goToCall,
            user: user,),
        );
    }
  });
}

void selectNotification(String payload) async {
// this is where i handle the ios notification when the app is closed.
  if(Platform.isIOS){
    if (payload != null) {
      MyNotificationObj myNotificationObj = MyNotificationObj.fromJson(
          jsonDecode(payload));
      if (myNotificationObj.type == "call") {
        goToCall = true;
        user = myNotificationObj.user;
        runApp(
          MyApp(
            goToCall: goToCall,
            user: user,),
        );
      }
    }
  }
}
`
