### ISSUE TITLE
Execution failed for task ':flutter_local_notifications:compileDebugJavaWithJavac'.

### ISSUE THREAD

**Issue by harshd110** [MaikuB/flutter_local_notifications#1680]
/Users/imac/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-9.8.0+1/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java:1550: error: cannot find symbol
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
                                                    ^
  symbol:   variable TIRAMISU
  location: class VERSION_CODES
/Users/imac/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-9.8.0+1/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java:1551: error: cannot find symbol
      String permission = Manifest.permission.POST_NOTIFICATIONS;
                                             ^
  symbol:   variable POST_NOTIFICATIONS
  location: class permission
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_local_notifications:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 24s

**Comment by MaikuB** [comment]
Please read the 9.8.0 changelog https://pub.dev/packages/flutter_local_notifications/changelog#980. It was explained that changes need to be made that also require the Android 13 SDK installed

**Comment by rafibr** [comment]
I was able to solve the problem by changing the compileSdkVersion from 31 to 33

**Comment by WaheedHussainHaans** [comment]
> I was able to solve the problem by changing the compileSdkVersion from 31 to 33

Is there any other workaround actually my other plugins need compile SDK version to be 31 TIA
