### ISSUE TITLE
[Question:Android] How to detect notification dismiss?

### ISSUE THREAD

**Issue by SotnikAP** [MaikuB/flutter_local_notifications#1681]
I want to detect if notification was dismissed by user. Is there such functionality? Or some workaround, didn't find anything about this in readme and code.

**Comment by MaikuB** [comment]
No this functionality isn't available.

**Comment by Imdavyking** [comment]
Please can it be added

**Comment by MaikuB** [comment]
Please look at submitting a PR and this is a duplicate of #74 so will be closing this one
