### ISSUE TITLE
requires Android SDK version 33

### ISSUE THREAD

**Issue by dmrcierhn** [MaikuB/flutter_local_notifications#1682]
**Describe the bug**
Hello, I'm trying to use 9.4.0 but I'm getting this error "Warning: The plugin flutter_local_notifications requires Android SDK version 33."

**To Reproduce**
1. Add the version 9.4.0 to pubspec.yaml
2. Just run the app

**Expected behavior**
Run the app without any problem

**Comment by guilhermeg2k** [comment]
If on your pubspec.yaml you have something like flutter_local_notifications: ^9.4.0, drop the "^" caret symbol, this makes pub get try to get latest 9 version wich is 9.8 that requires sdk 33

**Comment by dmrcierhn** [comment]
okay I will try thank you!

**Comment by MaikuB** [comment]
You could also install the Android 13 (API level 33) SDK as explained by the message. This is also mentioned in the changelog and readme

**Comment by dmrcierhn** [comment]
Thanks for your answer but I don't want to use API level 33 right now. I solved my issue in another way. I edited pubspec.lock and .packages files and then I ran pub get. Finally it worked when I run the app.

**Comment by MaikuB** [comment]
In case you're not familiar with Android development, you're not really using the SDK unless you change the targetSdkVersion to 33. That is one that affects the behaviour, compileSdkVersion as the name implies is purely for compilation and no behavioural changes

**Comment by dmrcierhn** [comment]
Thanks for letting me know. I will keep this in my mind. To be honest I didn't know this so I learned something new from you I really appreciate
