### ISSUE TITLE
Proposal to change the iOS general setup document

### ISSUE THREAD

**Issue by SungHyun22** [MaikuB/flutter_local_notifications#1684]
The documentation says to put the following code(IOS general setup) in didFinishLaunchingWithOptions method

```
if #available(iOS 10.0, *) {
  UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate
}
```

But in reality,  that code is in the application method.

```
@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    if #available(iOS 10.0, *) {
      UNUserNotificationCenter.current().delegate = self as UNUserNotificationCenterDelegate
    }

    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}
```

I think this may confuse the readers of the document. How about explicitly mentioning where to put the iOS general setup code in the documentation? 

this part.

![image](https://user-images.githubusercontent.com/26302580/187019960-83532512-37a0-4f6a-a389-e2a0c1c4e498.png)

By the way, thanks for the good library 😁😁

**Comment by MaikuB** [comment]
Thanks for picking up on that. Could you please submit a PR?

**Comment by SungHyun22** [comment]
Okay!!

**Comment by MaikuB** [comment]
Forgot to close this since PR had been merged. Thanks again for the submission
