### ISSUE TITLE
Local notifications error

### ISSUE THREAD

**Issue by Liliana99** [MaikuB/flutter_local_notifications#169]
AAPT: error: resource android:attr/fontVariationSettings not found.

This is the error that flutter shows at the moment to try run my project where I have implemented the plugin   flutter_local_notifications: ^0.5.1.

Could you help me please?

**Comment by MaikuB** [comment]
Starting from version 0.5.0, the plugin no longer uses the deprecated Android support libraries and uses the AndroidX libraries. Have you migrated your app to AndroidX following this [guide](https://developer.android.com/jetpack/androidx/migrate)? It was mentioned in the changelog for 0.5.0 release but I've now added a note on this in the readme

**Comment by Liliana99** [comment]
No, I haven't , because I have my project on VSCode . I solved the issue putting this line on Android/Manifest.xml 
<receiver android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver">
                <intent-filter>
                    <action android:name="android.intent.action.BOOT_COMPLETED"></action>
                </intent-filter>
            </receiver>
Now its works.
Thanks so much.

**Comment by MaikuB** [comment]
Np. Closing this then
