### ISSUE TITLE
Banner Image in IOS terminated not work

### ISSUE THREAD

**Issue by AnhDTN** [MaikuB/flutter_local_notifications#1691]
**Banner Image in IOS terminated not work**

Hello, When I using IOSNotificationAttachment, it work fine with foreground and background, but when I swipe to kill app, it not working, I will receiver default notification
This is method handle download image banner in notification
![Screen Shot 2022-09-05 at 10 42 49](https://user-images.githubusercontent.com/43284656/188356544-c56a5496-ea14-47d8-a52e-13a5e04425c8.png)

This method handle background message
![Screen Shot 2022-09-05 at 10 54 39](https://user-images.githubusercontent.com/43284656/188357660-a24ac1eb-3e7b-4b45-b626-f12ac074e4cf.png)

This method call on onBackgroundMessage of FirebaseMessaging

![Screen Shot 2022-09-05 at 10 54 29](https://user-images.githubusercontent.com/43284656/188357808-aa71a650-2e76-4f87-a582-5432c272d70a.png)

**Comment by MaikuB** [comment]
Nothing you've mentioned so far points to an issue with this plugin. The fact that when the app is terminated that you even get notification without an image would mean it's not going through the logic you've shared as a failure to download the image would mean an exception gets thrown that would prevent the logic to show the local notification from being executed. What you're describing be behaviour from using Firebase Cloud Messaging and looks like you need to do more research into understanding it more as there are different kinds of messages and they behave differently
