### ISSUE TITLE
build ipa failed after update to flutter 3.3.1

### ISSUE THREAD

**Issue by abdelrahman-abied** [MaikuB/flutter_local_notifications#1695]
flutter/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-9.9.1/ios/Classes/FlutterLocalNotificationsPlugin.h: Operation not permitted (in target 'flutter_local_notifications' from project 'Pods')

**Comment by MaikuB** [comment]
You're going to need dig further into this shouldn't be an issue with the plugin itself and I've been able to build an IPA myself. This issue would be more of a development environment issue so I suggest you look up online for similar issues to see how to resolve in. A quick search would seem to indicate this is Xcode related. I'll be closing this based on what I said but f you believe it's to with the plugin then feel free to re-open the issue provided you can give a link to a repository with a minimal app that can reproduce the issue
