### ISSUE TITLE
On restart, all previous notifications reschedule themselves

### ISSUE THREAD

**Issue by Yasminehassan26** [MaikuB/flutter_local_notifications#1696]
Hello, in my application when I schedule like some notifications during the day and then I turn off my phone the whole day by example and open it later, I receive all the scheduled notifications which their due date was during the time where my phone was off ,it is like that all the missed notifications come at once as a stream  which I don't want to happen, so is there a way to prevent ,any scheduled notifications that its due date was while the phone was off , from getting rescheduled again after the boot event.
Thank you in advance!

**Comment by MaikuB** [comment]
No as this is how it is expected to behave to begin with. If you were to write the iOS to schedule a notification yourself with Objective-C or Swift without the plugin, you'll find it'll behave the way you described. This is similar to setting up a reminder/event, which should take place irrespective of if the device is on or not
