### ISSUE TITLE
Android 13 notification permissions not running on android 13

### ISSUE THREAD

**Issue by BrianMwas** [MaikuB/flutter_local_notifications#1697]
**Describe the bug**
Requesting for notification permissions on a device running android 13 software does not trigger am using the latest plugin version. Any help would be grateful

**To Reproduce**
1. Add flutter local notifications plugin to your flutter app
2. request for permissions within the initState of a view
3. Reload the app/Restart the application a fresh to take in the plugin
4. The notification request dialog does not show up.5. 
The following is being printed on the console D/RequestPermissionHandler( 7762): onRequestPermissionsResult - false

**Expected behavior**
The notification dialog should show up instead I get the log that request notification permission - false on the terminal

**Sample code to reproduce the problem**
Here's the code that I am using 
`
final androidImpl =
            _localNotification.resolvePlatformSpecificImplementation<
                AndroidFlutterLocalNotificationsPlugin>();
        await androidImpl?.requestPermission();
`

**Comment by MaikuB** [comment]
Note that in the changelog and readme that there are steps required to enable this. In the readme, it's mentioned at https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#requesting-permissions-on-android-13-or-higher where you need to change the target SDK version of your app. Did you read and follow these steps? This isn't mention in what you mentioned either so I assume that hasn't been done

**Comment by BrianMwas** [comment]
Thanks, I realised I needed to change the target sdk to 33
