### ISSUE TITLE
payload is null in flutterLocalNotificationsPlugin.getActiveNotifications

### ISSUE THREAD

**Issue by androidwoman** [MaikuB/flutter_local_notifications#1700]
hey

i try to use payload in flutterLocalNotificationsPlugin.getActiveNotifications but it always returns null 

I even ran the example, but the payload is still null
![image](https://user-images.githubusercontent.com/76970164/189723260-d146dd13-429f-4fc8-9226-0ab353097e5a.png)

**Comment by MaikuB** [comment]
Thanks for picking up on this. Looks like this was a gap in the documentation when iOS support for active notifications were added (https://github.com/MaikuB/flutter_local_notifications/pull/1391) as the payload can only be returned on iOS and macOS
