### ISSUE TITLE
Add Android NotificationServiceListener functionality

### ISSUE THREAD

**Issue by Turburlar** [MaikuB/flutter_local_notifications#1701]
It would be helpful if this plugin exposed Android NotificationListenerService functionality to improve notification cancelling behaviour.

For example, notifications that arrive using FCM are not able to be cancelled using the cancel(id , {tag}) method exposed by this library, as FCM notifications arrive with an ID of zero.

The only successful way to cancel FCM notifications is to implement a NotificationListenerService class at the Android level, and implement the [cancelNotification(key) method](https://developer.android.com/reference/android/service/notification/NotificationListenerService#cancelNotification(java.lang.String)).

**Comment by MaikuB** [comment]
> For example, notifications that arrive using FCM are not able to be cancelled using the cancel(id , {tag}) method exposed by this library, as FCM notifications arrive with an ID of zero.

Although these have an ID of zero, from what I know, notifications from FCM would have tags. This plugin also exposes an API to return active notifications this would include the tag. With this is mind, I believe this should allow for a way for cancelling FCM notifications. If not, then what would you say is missing? Note that this is open source so if you have need for functionality then you can submit a PR

**Comment by MaikuB** [comment]
Closing due to lack of response to explain further and PRs can be submitted
