### ISSUE TITLE
intent SerializableExtra Deprecation on SDK 33

### ISSUE THREAD

**Issue by lawrencemauku** [MaikuB/flutter_local_notifications#1702]
I started getting this errors after upgrading to SDK 33.

warning: [deprecation] getSerializableExtra(String) in Intent has been deprecated
intent.getSerializableExtra(ForegroundServiceStartParameter.EXTRA);

warning: [deprecation] <T>getParcelableExtra(String) in Intent has been deprecated
      Notification notification = intent.getParcelableExtra("notification");
                                        ^
  where T is a type-variable:
    T extends Parcelable declared in method <T>getParcelableExtra(String)

**Comment by MaikuB** [comment]
This will be fixed in the 10.0 release but note these are warnings not errors

**Comment by MaikuB** [comment]
Just noticed one that I've missed suppressing so will do another update to address this soon

**Comment by lawrencemauku** [comment]
Thank you for this.
