### ISSUE TITLE
false positive when using `didNotificationLaunchApp` when performing a hot restart after showing scheduled notif

### ISSUE THREAD

**Issue by imedboumalek** [MaikuB/flutter_local_notifications#1703]
**Describe the bug**
When creating a scheduled notif with a payload, showing that notification, then doing a hot restart, the handler for notification tapped gets executed because `didNotificationLaunchApp`is `true`
my code:
 ```dart
class _HomeScreenState extends State<HomeScreen> {
  @override
  void initState() {
    super.initState();
    final notifPlugin = locator<FlutterLocalNotificationsPlugin>();
    notifPlugin.getNotificationAppLaunchDetails().then((value) {
      if (value?.didNotificationLaunchApp ?? false) {
        notificationTapped(value?.payload);
      }
    });
  }
```
**To Reproduce**
Tested on Android with scheduled notifications
1. create a notification for 10s from now
2. show notification (but don't tap it, you could even delete it and it'll still happen)
3. hot restart

**Comment by MaikuB** [comment]
I tried these steps on the example app but can't reproduce the issue you're reporting. Are you able to reproduce in the example app yourself? If not, can you fork the repository and update the example app to demonstrate how this can be reproduced?

**Comment by MaikuB** [comment]
Closing due to lack of response to provide a way to reproduce this when it can't be reproduced with the example app
