### ISSUE TITLE
example without other plugins

### ISSUE THREAD

**Issue by Goddard** [MaikuB/flutter_local_notifications#1704]
Your example uses additional plugins we may not be using so it makes it a little confusing since I have not learned those plugins.  If at all possible, creating an example just using standard Flutter libraries that would be really useful.

**Comment by MaikuB** [comment]
Can you be more specific on the plugins you're referring to. Note that this is open-source so you can contribute back

**Comment by Goddard** [comment]
Well normally in example code people do not use any additional plugins.  So using a state management plugin, or any third party plugin just makes it confusing since some people may not be using it.

**Comment by MaikuB** [comment]
That some other examples do this doesn't mean it's applicable for all scenarios so you'll need to be more specific. Can you point out where it's not appropriate or is this purely based on your experience with examples you've seen? This plugin is meant to deal with native APIs, as such there will be scenarios that require interacting with other native APIs that using a plugin is the simplest way to do so.

**Comment by Goddard** [comment]
https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/example/lib/main.dart

You are using plugins in your example code that has nothing to do with your plugin development.  It doesn't help people use your plugin.  It just confuses them because they are probably not using RXDart.

**Comment by MaikuB** [comment]
Point taken on rxDart though the syntax should be similar to others who have dealt with streams. So is your point specifically on rxDart or other plugins too? Note the example app is meant to cover a wide variety of scenarios, some of which may not be applicable to everyone's use case. Each button is use case on its own so developers can look at the code related to that button and work backwards. If your point is also on other plugins, I'd be interested know on how it could be done without them without having developers having to look at even more lower level details e.g. native APIs. Even better, please look at submitting a pull request

**Comment by MaikuB** [comment]
Closing as rxDart has been removed from example app now. If your comment also applies to other plugins then a more detailed explanation would be needed given some are needed depending on the problem the various scenarios in the example app are trying to demonstrate
