### ISSUE TITLE
onDidReceiveNotificationResponse callback is not getting called when clicking on notification from notification shade.

### ISSUE THREAD

**Issue by pintusingh28** [MaikuB/flutter_local_notifications#1707]
> Here is my notification handing code:

```dart
Future<void> initialize() async {
  const androidSettings = AndroidInitializationSettings(_androidNotificationIcon);
  const iosSettings = DarwinInitializationSettings(
    notificationCategories: [
      DarwinNotificationCategory(_categoryGeneralNotification, options: {DarwinNotificationCategoryOption.allowAnnouncement}),      
    ],
  );
  const settings = InitializationSettings(android: androidSettings, iOS: iosSettings);
  await _notificationsPlugin.initialize(
    settings,
    onDidReceiveNotificationResponse: onDidReceiveNotificationResponse,
    onDidReceiveBackgroundNotificationResponse: onDidReceiveBackgroundNotificationResponse,
  );
}

Future<void> showGeneralNotification(String title, String body) async {
  const androidDetails = AndroidNotificationDetails(_categoryGeneralNotification, "General Notifications", icon: _androidNotificationIcon);
  const iosDetails = DarwinNotificationDetails(categoryIdentifier: _categoryGeneralNotification);
  const notificationDetails = NotificationDetails(android: androidDetails, iOS: iosDetails);
  return _notificationsPlugin.show(title.hashCode, title, body, notificationDetails);
}

void onDidReceiveNotificationResponse(NotificationResponse details) {
  "onDidReceiveNotificationResponse".debug();
  details.debug();
}

@pragma('vm:entry-point')
void onDidReceiveBackgroundNotificationResponse(NotificationResponse details) {
  "onDidReceiveBackgroundNotificationResponse".debug();
  details.debug();
}
```

> Device Info:

Model: Pixel 4
Android Version: 13

**Comment by MaikuB** [comment]
Can you provide a link to a repository with a minimal app that can reproduce the issue?

**Comment by azharmaqbool** [comment]
How this issue was fixed, I am still getting the same problem.

**Comment by itsdani121** [comment]
same here 

                 ` 
@pragma('vm:entry-point')
Future<void> navigateNotification(mId) async {
  AndroidInitializationSettings initializationSettingsAndroid = AndroidInitializationSettings('ic_launcher');
  final InitializationSettings initializationSettings = InitializationSettings(android: initializationSettingsAndroid);

  await flutterLocalNotificationsPlugin.initialize(
    initializationSettings,
    onDidReceiveNotificationResponse: (details) {
      print('nav id $mId');
      navigatorKey.currentState?.push(MaterialPageRoute(
        builder: (context) => MeetingViewPage(meetingId: int.parse(mId)),
      ));
    },
    onDidReceiveBackgroundNotificationResponse: notificationTapBackground,
  );
}


        
@pragma('vm:entry-point')
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  if (message.data.isNotEmpty) {
    box.write('nMeetingId', message.data['meeting_id']!);
    RemoteNotification? notification = message.notification;
    AndroidNotification? androidz = message.notification?.android;
    if (message.notification != null && androidz != null) {
      flutterLocalNotificationsPlugin.show(
        notification.hashCode,
        notification?.title,
        notification?.body,
        NotificationDetails(
          android: AndroidNotificationDetails(
            'your channel id',
            'your channel name',
            channelDescription: 'your channel description',
            priority: Priority.high,
            importance: Importance.max,
            // Assigning vibration pattern to notification
            // Assigning custom sound to notification
            icon: '@mipmap/ic_launcher',
            // Assigning large icon to notification
            largeIcon: DrawableResourceAndroidBitmap('@mipmap/ic_launcher'),
          ),
        ),
      );
  
      await navigateNotification(message.data['meeting_id']);
    }
  }


}

`
here is my code when i use it iniside background call it did not working   @MaikuB  kindly complete guide me if i am doing wrong
