### ISSUE TITLE
Crash exception after update from 9.9.1 into 11.0.0

### ISSUE THREAD

**Issue by marcellocamara** [MaikuB/flutter_local_notifications#1708]
After upgrading the plugin dependencie from 9.9.1 into 11.0.0, this exception occurs:

```stacktrace
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter_local_notifications/src/platform_flutter_local_notifications.dart': Failed assertion: line 1018 pos 12: 'callback != null': 
    The backgroundHandler needs to be either a static function or a top level function to be accessible as a Flutter entry point.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      _evaluateBackgroundNotificationCallback (package:flutter_local_notifications/src/platform_flutter_local_notifications.dart:1018:12)
#3      IOSFlutterLocalNotificationsPlugin.initialize (package:flutter_local_notifications/src/platform_flutter_local_notifications.dart:648:5)
#4      FlutterLocalNotificationsPlugin.initialize (package:flutter_local_notifications/src/flutter_local_notifications_plugin.dart:151:13)
```

**Sample code to reproduce the problem**
```dart
final _notificationsPlugin = FlutterLocalNotificationsPlugin();

@override
Future<void> initialize() async {
   var settings = const InitializationSettings(
     android: AndroidInitializationSettings('@mipmap/ic_launcher'),
     iOS: DarwinInitializationSettings(),
   );
   await _notificationsPlugin.initialize(
     settings,
     onDidReceiveNotificationResponse: (details) async {
       print('\n\nNotification clicked => Details: details\n\n');
     },
     onDidReceiveBackgroundNotificationResponse: (details) async {
       print('\n\nNotification clicked => Details: details\n\n');
     },
   );
   tz.initializeTimeZones();
}
```

**Comment by MaikuB** [comment]
The docs and error explains the problem as an anonymous function like you have is not a static or top level function

**Comment by HatsuneMikuV** [comment]
@marcellocamara How did you solve it?

**Comment by marcellocamara** [comment]
@HatsuneMikuV 
> How did you solve it?

I didn't bumped the version for now, because it breaks my "clean code and clean arch". 
I've implemented the notifications configuration at one of the repository/external layers of my project.
The resolution that I saw that works is cut that code and implement it on the top level of a function. However, it makes the code uglier

**Comment by mohantyagii** [comment]
@HatsuneMikuV - I have tried this with the latest version (flutter_local_notifications: ^14.1.1)of this plugin 

Please try with this piece of code.

static void _onLocalNotificationTap(NotificationResponse payload) {
    print('notification(${payload.id}) action tapped: '
        '${payload.actionId} with'
        ' payload: ${payload.payload}');
    if (payload.input?.isNotEmpty ?? false) {
    print(
    'notification action tapped with input: ${payload.input}');
    } 
  }
  
  and assign this to the callback like this
  
  await flutterLocalNotificationsPlugin.initialize(initializationSettings,
      onDidReceiveNotificationResponse:
          (NotificationResponse notificationResponse) {
     
      },
      onDidReceiveBackgroundNotificationResponse: _onLocalNotificationTap,
       );
