### ISSUE TITLE
Users can remove/dismiss a notification if it contains an action

### ISSUE THREAD

**Issue by hawarhekmat** [MaikuB/flutter_local_notifications#1710]
User can remove/dismiss a notification if it contains an action, an action should be performed in order to remove/dismiss a notification

**Comment by MaikuB** [comment]
Which platform(s) are you seeing this issue on. If it's Android, have you made sure that [this](https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/AndroidNotificationAction/cancelNotification.html) is set to `true`? Note that this is the default value and will dismiss the notification if an action is tapped on. Tweaking the example app will also show this too

**Comment by MaikuB** [comment]
I'm not sure what you're trying to report here. First of all, are you trying to report a bug or a request a feature? If it's a bug can you please mention the steps to reproduce and fork the repository and update the code to demonstrate the problem

**Comment by MaikuB** [comment]
Closing due to lack of response. Feel free to re-open provided you can be elaborate more
