### ISSUE TITLE
Actions cause the crash of the entire app

### ISSUE THREAD

**Issue by EnricoTirri** [MaikuB/flutter_local_notifications#1721]
**Describe the bug**
When I show a notification with actions and I try to press one of them the application crash, the warning are referencing to the unability of the system to reach a receiver

**To Reproduce**
Just show a notification with action and try to press one of the action button, it does not depend whether the application is running or not, it also does not depend on the callback function referenced on onDidReceiveNotificationResponse args.

[bug.txt](https://github.com/MaikuB/flutter_local_notifications/files/9640853/bug.txt)

**Comment by MaikuB** [comment]
Can you provide a link to a repository hosting a minimal app that can reproduce the problem?

**Comment by fewling** [comment]
I just ran into the same problem, the android JAVA part seems to have a null callback function to handle the action.

Base on the documentation: when initializing the plugin, we can prepare two callbacks: 
- `onDidReceiveNotificationResponse`
- `onDidReceiveBackgroundNotificationResponse`


After setting both callbacks, pressing the actions does not crash anymore.

Caution❗: As the documentation mentioned, `onDidReceiveBackgroundNotificationResponse` needs to be either static or annotated with the `@pragma('vm:entry-point')`, but I have to add both to make it stop crashing 🤷‍♂️.

```dart
import 'package:flutter_local_notifications/flutter_local_notifications.dart';

main() async {

  /// Initialization part:
  FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
      FlutterLocalNotificationsPlugin();

  const AndroidInitializationSettings initializationSettingsAndroid =
      AndroidInitializationSettings('@mipmap/ic_launcher');

  const InitializationSettings initializationSettings =
      InitializationSettings(android: initializationSettingsAndroid);



  /// ⚠⚠⚠ Preparing TWO callbacks here:
  await flutterLocalNotificationsPlugin.initialize(
    initializationSettings,
    onDidReceiveNotificationResponse: onReceiveResponse,                        //  callback A 🅰
    onDidReceiveBackgroundNotificationResponse: onReceiveBackgroundResponse,    //  callback B 🅱
  );
}

  ///  🅰 callback A:
  void onReceiveResponse(
      NotificationResponse notificationResponse) async {
    final payload = notificationResponse.payload;
    log('notification payload: $payload');
  }

  /// 🅱 callback B:
  /// Functions passed to the [onDidReceiveBackgroundNotificationResponse] callback need to be
  /// annotated with the @pragma('vm:entry-point') annotation to ensure they are not stripped out by the Dart compiler.
  @pragma('vm:entry-point')
  static void onReceiveBackgroundResponse(
      NotificationResponse notificationResponse) async {
    final payload = notificationResponse.payload;
    log('Background Notification payload: $payload');
  }
```

**Comment by MaikuB** [comment]
Thanks @fewling, will see if I can reproduce this one though not sure if it's the same problem @EnricoTirri is having

**Comment by MaikuB** [comment]
I was able to reproduce in the example app by not listening to the `onDidReceiveBackgroundNotificationResponse` stream. The crash is actually indicative of trying to setup a notification action that but hasn't been handled. Will fix the crash given that trying to handle the action is optional
