### ISSUE TITLE
iOS setup

### ISSUE THREAD

**Issue by erperejildo** [MaikuB/flutter_local_notifications#1723]
I was reading this comment:
```
/// Please download the complete example app from the GitHub repository where
/// all the setup has been done
```
here:
https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/example/lib/main.dart#L82

Where am I supposed to download this example from? I am missing the iOS setup, getting right now:
`iOS settings must be set when targeting iOS platform`

**Comment by MaikuB** [comment]
GitHub should have ways for you to clone/download the entire repository for you to get the entire example app. If you were debugging then the stack trace should've pointed out the issue where you need to pass initialisation settings. The plugin makes parameters nullable even if it they're actually required (like this scenario) because not every app will want to target all platforms supported by the plugin

**Comment by erperejildo** [comment]
I know how to clone the repository, but can you point me out to the iOS file where we have its setup?

**Comment by MaikuB** [comment]
There is no iOS file that you're suppose to modify when it comes to the issue you're encountering. This is why I was referring to looking at the stack trace and how you need to pass initialisation settings despite how the parameters are nullable (explained why in previous post). The stack trace should've pointed you to how this is to do with calling `initialize()` and what it's looking for here https://github.com/MaikuB/flutter_local_notifications/blob/0144fa622a9c7ec0ff6d33628b1254cb74c67b30/flutter_local_notifications/lib/src/flutter_local_notifications_plugin.dart#L145 i.e. it requires you pass initialisation settings for iOS

**Comment by erperejildo** [comment]
I'm passing the initialisation created here:
```
final IOSInitializationSettings initializationSettingsIOS =
        IOSInitializationSettings(
      requestSoundPermission: true,
      requestBadgePermission: true,
      requestAlertPermission: true,
      onDidReceiveLocalNotification: onDidReceiveLocalNotification,
    );
```
but I'm getting:
`'IOSInitializationSettings' isn't a type.`

If I try to remove the type I get this instead:
`'IOSInitializationSettings' isn't defined for the class 'NotificationService'.`

**Comment by MaikuB** [comment]
Which version of the plugin are you using?

**Comment by erperejildo** [comment]
`flutter_local_notifications: ^12.0.0`

**Comment by MaikuB** [comment]
Is there a reason why you tried to specify `IOSInitializationSettings`? That class doesn't exist anymore so that would explain the issue you're seeing . The API docs are on pub https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/InitializationSettings-class.html. There would've also been example code on calling `initialize` in the readme and example app too

**Comment by erperejildo** [comment]
I was just following these instructions: https://blog.codemagic.io/flutter-local-notifications/

I'm totally lost with the steps here: I copied the whole `darwin` folder but I see some other types defs here and const create in main there. I see tutorials with different features (like downloading images or so). I just need a simple text notification the user. Do you know of any updated tutorial like the one I shared I could look at?

**Comment by MaikuB** [comment]
No but solving your issue should be straightforward. If you're struggling then are you by chance new to programming? The API docs, readme, example app and your IDE etc should already point out the exact class you need. The changelog would've also highlighted the breaking changes between releases. If you're still struggling then I suggest you hop onto communities like Slack or discord to get help

**Comment by erperejildo** [comment]
> No but solving your issue should be straightforward. If you're struggling then are you by chance new to programming? The API docs, readme, example app and your IDE etc should already point out the exact class you need. The changelog would've also highlighted the breaking changes between releases. If you're still struggling then I suggest you hop onto communities like Slack or discord to get help

No, and I'm not new to Flutter either. I know code and how to clone repos if that answers your question. Github also has a contribution activity page that you could check.

The documentation I have been following is not updated but you mentioned that solving my issue should be straightforward. Ok, as mentioned, what I need is pretty simple and I didn't find it in the example I downloaded. I'll share what I currently have working on Android:

I have Firebase, where I detect when an user creates a document in one collection to send him a notification like this:
```
export const sendToDevice = functions.firestore
    .document("orders/{orderId}")
    .onCreate(async (snapshot) => {
      const order = snapshot.data();

      const querySnapshot = await db
          .collection("users")
          .doc(order.seller)
          .get();

      const token = querySnapshot.data()!.token;

      const payload: admin.messaging.MessagingPayload = {
        notification: {
          title: "New Order!",
          body: `you sold a ${order.product} for ${order.total}`,
          icon: "your-icon-url",
          click_action: "FLUTTER_NOTIFICATION_CLICK",
        },
      };

      return fcm.sendToDevice(token, payload);
    });
```

This is my service, which will be listen for it:
```
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
// import 'package:firebase_crashlytics/firebase_crashlytics.dart';
import 'package:flutter/material.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';

const AndroidNotificationChannel channel = AndroidNotificationChannel(
  'high_importance_channel', // id
  'High Importance Notifications', // title
  importance: Importance.high,
);

Future<void> firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  // If you're going to use other Firebase services in the background, such as Firestore,
  // make sure you call `initializeApp` before using other Firebase services.
  print('Handling a background message ${message.messageId}');
}

class NotificationsService {
  final FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
      FlutterLocalNotificationsPlugin();
  String token = '';
  final AndroidNotificationChannel channel = const AndroidNotificationChannel(
    'high_importance_channel', // id
    'High Importance Notifications', // title
    importance: Importance.high,
  );

  initializeNotifications() async {
    // notifications
    FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);
    await flutterLocalNotificationsPlugin
        .resolvePlatformSpecificImplementation<
            AndroidFlutterLocalNotificationsPlugin>()
        ?.createNotificationChannel(channel);

    await FirebaseMessaging.instance
        .setForegroundNotificationPresentationOptions(
      alert: true,
      badge: true,
      sound: true,
    );

    final initialzationSettingsAndroid =
        AndroidInitializationSettings('@mipmap/ic_launcher');

    // final DarwinInitializationSettings initializationSettingsDarwin =
    //     DarwinInitializationSettings(
    //   requestAlertPermission: false,
    //   requestBadgePermission: false,
    //   requestSoundPermission: false,
    //   onDidReceiveLocalNotification:
    //       (int id, String? title, String? body, String? payload) async {
    //     didReceiveLocalNotificationStream.add(
    //       ReceivedNotification(
    //         id: id,
    //         title: title,
    //         body: body,
    //         payload: payload,
    //       ),
    //     );
    //   },
    //   notificationCategories: darwinNotificationCategories,
    // );

    final initializationSettings = InitializationSettings(
      android: initialzationSettingsAndroid,
      // iOS: initializationSettingsDarwin,
    );
    flutterLocalNotificationsPlugin.initialize(initializationSettings);

    FirebaseMessaging.onMessage.listen((RemoteMessage message) {
      RemoteNotification? notification = message.notification;
      AndroidNotification? android = message.notification?.android;
      if (notification != null && android != null) {
        flutterLocalNotificationsPlugin.show(
          notification.hashCode,
          notification.title,
          notification.body,
          NotificationDetails(
            android: AndroidNotificationDetails(
              channel.id,
              channel.name,
              // channel.description,
              color: Colors.blue,
              // TODO add a proper drawable resource to android, for now using
              //      one that already exists in example app.
              icon: "@mipmap/ic_launcher",
            ),
          ),
        );
      }
    });

    getToken();
  }

  // void onDidReceiveLocalNotification(
  //     int id, String? title, String? body, String? payload) {
  //   print('id $id');
  // }

  Future<void> _firebaseMessagingBackgroundHandler(
      RemoteMessage message) async {
    // If you're going to use other Firebase services in the background, such as Firestore,
    // make sure you call `initializeApp` before using other Firebase services.
    await Firebase.initializeApp();
    print('Handling a background message ${message.messageId}');
  }

  getToken() async {
    token = (await FirebaseMessaging.instance.getToken())!;
  }
}
```

I don't want to add extra configuration I don't need, just listen for this as well on iOS, and from the example I'm not sure if I need that all (because for Android seems to be pretty straight forward for real)

**Comment by MaikuB** [comment]
The example for both this plugin and the blog post you speak to both specify the `ios` property of the `InitializationSettings` class. In the example for this plugin it's at https://github.com/MaikuB/flutter_local_notifications/blob/b4ec7d7fc1064ebae1a30cef40d24f760c45691e/flutter_local_notifications/example/lib/main.dart#L175. I mentioned why it's nullable before and this is also captured in the [API docs](https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/InitializationSettings/iOS.html) that would've highlighted the type expected object is an instance of the [DarwinInitializationSettings](https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/DarwinInitializationSettings-class.html) class. This should also be highlighted via the IDE and the changelog for version 10 calls out the change in the class to use (see https://github.com/MaikuB/flutter_local_notifications/blob/b4ec7d7fc1064ebae1a30cef40d24f760c45691e/flutter_local_notifications/CHANGELOG.md?plain=1#L36). In other words, if you were trying to following the blog post but use a more recent version of the plugin, this should be a matter of copying the code that was there and replace `IOSInitializationSettings` with `DarwinInitializationSettings` as called out by the changelog entry. In the code snippet you've shared above, you've still kept the code to specify the initialisations for iOS commented out so this is why you're getting an `ArgumentError` as it's to do with invalid arguments being passed to the `initialize()` method call and the error message is calling out that you need to specify it when you're targeting iOS

**Comment by erperejildo** [comment]
Nothing... it may be related to some missing Firebase configuration on the iOS part. I removed what I had working for Android and copied it from those files. Worked again on Android but not on iOS.

```
notificationsInit();

runApp(
    LocalizedApp(
      delegate,
      const MyApp(),
    ),
  );
}

Future<void> notificationsInit() async {
  notificationsFirebase();

  const AndroidInitializationSettings initializationSettingsAndroid =
      AndroidInitializationSettings('@mipmap/ic_launcher');

  final List<DarwinNotificationCategory> darwinNotificationCategories =
      <DarwinNotificationCategory>[
    DarwinNotificationCategory(
      darwinNotificationCategoryText,
      actions: <DarwinNotificationAction>[
        DarwinNotificationAction.text(
          'text_1',
          'Action 1',
          buttonTitle: 'Send',
          placeholder: 'Placeholder',
        ),
      ],
    ),
    DarwinNotificationCategory(
      darwinNotificationCategoryPlain,
      actions: <DarwinNotificationAction>[
        DarwinNotificationAction.plain('id_1', 'Action 1'),
        DarwinNotificationAction.plain(
          'id_2',
          'Action 2 (destructive)',
          options: <DarwinNotificationActionOption>{
            DarwinNotificationActionOption.destructive,
          },
        ),
        DarwinNotificationAction.plain(
          navigationActionId,
          'Action 3 (foreground)',
          options: <DarwinNotificationActionOption>{
            DarwinNotificationActionOption.foreground,
          },
        ),
        DarwinNotificationAction.plain(
          'id_4',
          'Action 4 (auth required)',
          options: <DarwinNotificationActionOption>{
            DarwinNotificationActionOption.authenticationRequired,
          },
        ),
      ],
      options: <DarwinNotificationCategoryOption>{
        DarwinNotificationCategoryOption.hiddenPreviewShowTitle,
      },
    )
  ];

  /// Note: permissions aren't requested here just to demonstrate that can be
  /// done later
  final DarwinInitializationSettings initializationSettingsDarwin =
      DarwinInitializationSettings(
    requestAlertPermission: false,
    requestBadgePermission: false,
    requestSoundPermission: false,
    onDidReceiveLocalNotification:
        (int id, String? title, String? body, String? payload) async {
      didReceiveLocalNotificationStream.add(
        ReceivedNotification(
          id: id,
          title: title,
          body: body,
          payload: payload,
        ),
      );
    },
    notificationCategories: darwinNotificationCategories,
  );
  final InitializationSettings initializationSettings = InitializationSettings(
    android: initializationSettingsAndroid,
    iOS: initializationSettingsDarwin,
  );
  await flutterLocalNotificationsPlugin.initialize(
    initializationSettings,
    onDidReceiveNotificationResponse:
        (NotificationResponse notificationResponse) {
      switch (notificationResponse.notificationResponseType) {
        case NotificationResponseType.selectedNotification:
          selectNotificationStream.add(notificationResponse.payload);
          break;
        case NotificationResponseType.selectedNotificationAction:
          if (notificationResponse.actionId == navigationActionId) {
            selectNotificationStream.add(notificationResponse.payload);
          }
          break;
      }
    },
    onDidReceiveBackgroundNotificationResponse: notificationTapBackground,
  );
}

Future<void> notificationsFirebase() async {
  FirebaseMessaging.onBackgroundMessage(firebaseMessagingBackgroundHandler);
  await flutterLocalNotificationsPlugin
      .resolvePlatformSpecificImplementation<
          AndroidFlutterLocalNotificationsPlugin>()
      ?.createNotificationChannel(channel);

  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);
  await flutterLocalNotificationsPlugin
      .resolvePlatformSpecificImplementation<
          AndroidFlutterLocalNotificationsPlugin>()
      ?.createNotificationChannel(channel);

  await FirebaseMessaging.instance.setForegroundNotificationPresentationOptions(
    alert: true,
    badge: true,
    sound: true,
  );

  FirebaseMessaging.onMessage.listen((RemoteMessage message) {
    RemoteNotification? notification = message.notification;
    AndroidNotification? android = message.notification?.android;
    if (notification != null && android != null) {
      flutterLocalNotificationsPlugin.show(
        notification.hashCode,
        notification.title,
        notification.body,
        NotificationDetails(
          android: AndroidNotificationDetails(
            channel.id,
            channel.name,
            // channel.description,
            color: Colors.blue,
            // TODO add a proper drawable resource to android, for now using
            //      one that already exists in example app.
            icon: "@mipmap/ic_launcher",
          ),
        ),
      );
    }
  });

  getToken();
}

Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  // If you're going to use other Firebase services in the background, such as Firestore,
  // make sure you call `initializeApp` before using other Firebase services.
  await Firebase.initializeApp();
  print('Handling a background message ${message.messageId}');
}

final FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
    FlutterLocalNotificationsPlugin();
String token = '';
final AndroidNotificationChannel channel = const AndroidNotificationChannel(
  'high_importance_channel', // id
  'High Importance Notifications', // title
  importance: Importance.high,
);
getToken() async {
  token = (await FirebaseMessaging.instance.getToken())!;
}

```

I didn't mention it but I'm testing on simulator 11 pro max iOS 16

**Comment by MaikuB** [comment]
You're likely going to need to get help elsewhere then if FCM is involved here. From what I remember FCM example app leverages this plugin too though I don't know how well they've maintained. Could you clarify what you mean by same behaviour s the original issue you reported is to this with an `ArgumentError` due to missing values from passed to the `initialize()` method call via this plugin but I can see now you've specified it so would think you're having a different issue altogether

**Comment by erperejildo** [comment]
with same behaviour I mean comparing after copying those new methods I was missing before: it doesn't throw any error but doesn't show any notification from Firebase. I'll check on Firebase repo then.
Thanks

**Comment by MaikuB** [comment]
Yep ok that's a different issue then. I noticed the tutorial you referenced doesn't talk about [this step](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#general-setup) so if you haven't done so yet then you'll need to do so. If you have done so and still have issues then could you provide a link to a repository that can reproduce this problem? Seen a similar issue reported but no one has been able to provide a way to reproduce it (see https://github.com/MaikuB/flutter_local_notifications/issues/1606) and I've not been able to reproduce it myself either

**Comment by erperejildo** [comment]
Not easy to reproduce since this would need a Firebase project and the user being able to create these documents from the UI (right now it's a manual process directly in the DB).

I have created a question here: https://stackoverflow.com/questions/74006564/flutter-show-local-notifications-from-firebase-on-ios
