### ISSUE TITLE
How to retrieve `scheduledDate` from pending notification requests

### ISSUE THREAD

**Issue by atmikeguo** [MaikuB/flutter_local_notifications#1724]
I tried to parse `pendingNotificationRequest.payload` but it's `""`.

**Comment by MaikuB** [comment]
The native APIs don't provide a way to fetch this for the plugin to do the same thing. The closest thing you can do is to include these details as part of the payload when you create the notification. If you mean you provided some payload and it's not coming back then please provide a link to a repository hosting a minimal app that can reproduce the issue. You can fork this repository and update the example app to demonstrate this too.
