### ISSUE TITLE
Is there way to show notification with no sound on iOS?

### ISSUE THREAD

**Issue by songyiYu** [MaikuB/flutter_local_notifications#1725]
I wonder if show notification with no sound on iOS
I want to show only badge without sound or vibration.
If yes, how can I do?

**Comment by songyiYu** [comment]
I've found the solution. For showing only badge without notification, better to use another plugin named 'flutter_app_badger'

**Comment by MaikuB** [comment]
The example app has a specific scenario on how to show a notification without a sound
