### ISSUE TITLE
Bump dbus,xml and ffi dependency files 

### ISSUE THREAD

**Issue by erickgon92** [MaikuB/flutter_local_notifications#1726]
Hi, while updating my project packages came across this error on version solving. 
All other packages are using ffi ^2.0.1 so basically after a pub get I come across this error of version solving.

Because dbus >=0.7.4 depends on xml ^6.1.0 and dbus >=0.5.5 <0.7.5 depends on ffi ^1.1.2, dbus >=0.5.5 requires xml ^6.1.0 or ffi ^1.1.2.
And because open_filex >=4.0.0 depends on ffi ^2.0.1, if open_filex >=4.0.0 and dbus >=0.5.5 then xml ^6.1.0.
And because flutter_local_notifications >=9.6.0 <10.0.0-dev.1 depends on flutter_local_notifications_linux ^0.5.0+1 which depends on dbus ^0.7.1, if open_filex >=4.0.0 and flutter_local_notifications >=9.6.0 <10.0.0-dev.1 then xml ^6.1.0.
And because flutter_html 2.2.1 depends on flutter_svg >=0.22.0 <1.0.0 which depends on xml ^5.0.0, one of open_filex >=4.0.0 or flutter_local_notifications >=9.6.0 <10.0.0-dev.1 or flutter_html 2.2.1 must be false.
And because no versions of flutter_html match >2.2.1 <3.0.0 and minerva depends on flutter_html ^2.2.1, open_filex >=4.0.0 is incompatible with flutter_local_notifications >=9.6.0 <10.0.0-dev.1.
So, because "x" depends on both open_filex ^4.1.1 and flutter_local_notifications ^9.6.0, version solving failed.

pub get failed (1; So, because "x" depends on both open_filex ^4.1.1 and flutter_local_notifications ^9.6.0, version solving failed.)

Thanks in advance!

**Comment by MaikuB** [comment]
dbus dependency has been bumped now but will require that you update the version of the plugin used
