### ISSUE TITLE
Implement FCM token management best pratices (deleting stale tokens etc)

### ISSUE THREAD

**Issue by giorgio79** [MaikuB/flutter_local_notifications#1731]
Any plans to provide cloud functions, firestore storage models for FCM tokens? https://firebase.google.com/docs/cloud-messaging/manage-tokens

**Comment by MaikuB** [comment]
No as this plugin is to do with local notifications while FCM is to do with remote/push notifications so they're really different things. The plugin provides the functionality by being a wrapper for native APIs to trigger a notification locally on the device i.e. there's no dependency on a network connection let alone FCM. I believe you should be asking on https://github.com/firebase/flutterfire, which is the official repo of the Flutter FCM plugin
