### ISSUE TITLE
onDidReceiveBackgroundNotificationResponse callback is not getting called when tapped on notification

### ISSUE THREAD

**Issue by hosseinkhojany** [MaikuB/flutter_local_notifications#1732]
VERSION: flutter_local_notifications: ^11.0.0

It doesn't work when the application is closed. Is there anything needed to work?
It works when the app is open

-------------------------------------------CODE-----------------------------
 flutterLocalNotificationsPlugin.initialize(
        initializationSettings,
        onDidReceiveBackgroundNotificationResponse: _onOpenedNotificationBackground,
        onDidReceiveNotificationResponse: _onOpenedNotificationBackground,
      );

 @pragma('vm:entry-point')
  static void _onOpenedNotificationBackground(NotificationResponse message) async {
    print("NOTIFICATION TAPPED");
  }
-------------------------------------------CODE-----------------------------

/home/khoujani/Documents/flutter/3.0.3/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, 3.0.2, on Ubuntu 20.04.3 LTS 5.4.0-050400-generic, locale en_US.UTF-8)
    • Flutter version 3.0.2 at /home/khoujani/Documents/flutter/3.0.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (4 months ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /usr/lib/android-sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.1)
    • Android Studio at /home/khoujani/ANDROID/android-2021.1.1
    • Flutter plugin version 64.0.2
    • Dart plugin version 211.7798
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • M2010J19CG (mobile) • c0b33e21120 • android-arm64  • Android 10 (API 29)
    • Linux (desktop)     • linux       • linux-x64      • Ubuntu 20.04.3 LTS 5.4.0-050400-generic
    • Chrome (web)        • chrome      • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
Process finished with exit code 0

**Comment by MaikuB** [comment]
Could you provide a link to a repository to a minimal app that can reproduce the issue?

**Comment by hosseinkhojany** [comment]
I do mistake, I Fix that

**Comment by MrunalrajRedij** [comment]
@hosseinkhojany What did you fix? I am facing a similar issue.

**Comment by hosseinkhojany** [comment]
Use this way when the app is terminated
_--------------------------------------------------------------------------------------------
@pragma('vm:entry-point')
void notificationTapBackground(NotificationResponse notificationResponse) {
}

Future<void> main() async {
  // needed if you intend to initialize in the `main` function
  WidgetsFlutterBinding.ensureInitialized();

  await _configureLocalTimeZone();

  final NotificationAppLaunchDetails? notificationAppLaunchDetails = !kIsWeb &&
          Platform.isLinux
      ? null
      : await flutterLocalNotificationsPlugin.getNotificationAppLaunchDetails();
  String initialRoute = HomePage.routeName;
  if (notificationAppLaunchDetails?.didNotificationLaunchApp ?? false) {
    payload = notificationAppLaunchDetails!.notificationResponse?.payload;
  }
}
-----------------------------------------------------------------------------------------------------------

**Comment by mutasimNuman** [comment]
which package are you talking about?

**Comment by azharmaqbool** [comment]
@hosseinkhojany I am facing the same issue, can you please share some details how you fixed this?
