### ISSUE TITLE
Hii Guys Please help me to fix this problem. Attention: I am using Awesome Notification package in flutter

### ISSUE THREAD

**Issue by Boburbek6010** [MaikuB/flutter_local_notifications#1737]
E/Android: [Awesome Notifications](25254): Invalid notification (no valid small icon): Notification(channel=basic_channel shortcut=null contentView=null vibrate=null sound=null tick defaults=0x0 flags=0x11 color=0xff009688 vis=PRIVATE) (NotificationThread:58)
W/System.err(25254): me.carda.awesome_notifications.core.exceptions.AwesomeNotificationsException: Invalid notification (no valid small icon): Notification(channel=basic_channel shortcut=null contentView=null vibrate=null sound=null tick defaults=0x0 flags=0x11 color=0xff009688 vis=PRIVATE)
W/System.err(25254): 	at android.app.NotificationManager.fixNotification(NotificationManager.java:606)
W/System.err(25254): 	at android.app.NotificationManager.notifyAsUser(NotificationManager.java:585)
W/System.err(25254): 	at android.app.NotificationManager.notify(NotificationManager.java:534)
W/System.err(25254): 	at android.app.NotificationManager.notify(NotificationManager.java:510)
W/System.err(25254): 	at me.carda.awesome_notifications.core.managers.StatusBarManager.showNotificationOnStatusBar(StatusBarManager.java:86)
W/System.err(25254): 	at me.carda.awesome_notifications.core.threads.NotificationSender.showNotification(NotificationSender.java:260)
W/System.err(25254): 	at me.carda.awesome_notifications.core.threads.NotificationSender.doInBackground(NotificationSender.java:147)
W/System.err(25254): 	at me.carda.awesome_notifications.core.threads.NotificationSender.doInBackground(NotificationSender.java:32)
W/System.err(25254): 	at me.carda.awesome_notifications.core.threads.NotificationThread.runOnForegroundThread(NotificationThread.java:106)
W/System.err(25254): 	at me.carda.awesome_notifications.core.threads.NotificationThread.execute(NotificationThread.java:34)
W/System.err(25254): 	at me.carda.awesome_notifications.core.threads.NotificationSender.send(NotificationSender.java:101)
W/System.err(25254): 	at me.carda.awesome_notifications.core.AwesomeNotifications.createNotification(AwesomeNotifications.java:569)
W/System.err(25254): 	at me.carda.awesome_notifications.AwesomeNotificationsPlugin.channelMethodCreateNotification(AwesomeNotificationsPlugin.java:1274)

**Comment by MeetSolguruz** [comment]
Can you share your code please ?
For more info.

**Comment by MaikuB** [comment]
The issue you're reporting is to do with another plugin not this one so should be posted on the repo for that plugin
