### ISSUE TITLE
Cannot detect callback on Android, I am trying code from example to my projects but it does not work. I can detect callback when user click banner notification on iOS, but Android I can not find it. Author could help this ? #Tag script code work on Android

### ISSUE THREAD

**Issue by Jayden0907** [MaikuB/flutter_local_notifications#1738]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Sample code to reproduce the problem**

**Comment by MaikuB** [comment]
I've not seen anyone else report this issue either as an issue like this affects critical functionality of the plugin so lends more credence to this being an issue to your own app. Please clone the entire repository and run the example from there to confirm the functionality works as the first thing before trying to submit a bug report as this is also mentioned in the template.

If this is indeed an issue with your own app then note you'll need to reach out to the wider community to get help and this may involve going to places like Slack, Discord etc as I don't have the capacity to be helping everyone that has issues using the plugin by checking their app

**Comment by Jayden0907** [comment]
Thanks for your email. Please check this video, on Android it happened when
i tapped notification on top.

**Comment by MaikuB** [comment]
You've not provided anything and my response wasn't via an email. If you intend to share something then ensure you do via GitHub. Note also what I mentioned earlier on actually trying out the example app. You should also cross-reference with what is there. Simply showing a video isn't evidence of a bug of this plugin. You need ensure you do your due diligence in trying to demonstrate a bug and provide a link to repository with a minimal app that can reproduce the issue

**Comment by MaikuB** [comment]
Closing due to lack of response and lack of evidence that was requested to prove there's an issue with the plugin
