### ISSUE TITLE
Help on notification buttons

### ISSUE THREAD

**Issue by asterd** [MaikuB/flutter_local_notifications#1748]
Hi, I need some help because I didn't understand, reading documentation and example, how to use notification action button in android and iOS using FCM push notification.
My need is:
1. The server send a push notification through FCM with some data payload
2. The app (even if in background or closed) receive the notification, read data and if data contains some parameter, the notification shows one or more action buttons (and obviously do something on click), otherwise displays other buttons or no button at all.

Is this possible? I admit (but probably is my limit) that I don't understand how to achieve it through documentation.
If you can help me, I can format a readme section to add to docs.. 
Thank you very much.

**Comment by MaikuB** [comment]
I've not done this myself but I don't see why not. Note that this isn't matter of documentation for the plugin but more where it's on you to translate your scenarios and understanding how of the problem/solution to code. This is similar how you don't see FCM's official documentation having specific docs for this either. FCM should have info on how you send data messages and the plugin has examples to generate notifications with actions. From there you should be trying to combine the knowledge together. I'd suggest you spend more time investigating/experimenting by tackling each thing that needs be done, one at a time. You may be able to reach out to others in the Flutter community on Slack, Discord etc as those that typically go to GitHub do so to report an issue as opposed to treating it as a forum to provide answers
