### ISSUE TITLE
How to disabled auto start request? 

### ISSUE THREAD

**Issue by lanistor** [MaikuB/flutter_local_notifications#1749]
It will request auto start automaticlly, before user allow our privacy agreement. How to disable it and allow it later?

**Comment by lanistor** [comment]
Yeah, it's Xiaomi, the report indicates the `ScheduledNotificationBootReceiver` listening the `android.content.Intent.ACTION_BOOT_COMPLETED` broadcast and maybe do something, this violated the privacy agreement.

**Comment by lanistor** [comment]
Is it possible to add a switch of `ACTION_BOOT_COMPLETED` broadcast reaction?

**Comment by MaikuB** [comment]
I don't know what you mean by a switch on then. This plugin needs it to handle rescheduling notifications after a phone is rebooted. Given this plugin is library for general use, if you need to do tweaks for your own purposes, it may be that you need to keep a fork specific to yourself

**Comment by lanistor** [comment]
Got it, thanks.
