### ISSUE TITLE
Failed to transform FakeDependency.jar

### ISSUE THREAD

**Issue by VasuBhav** [MaikuB/flutter_local_notifications#1753]
**Failed to transform FakeDependency.jar**

```
Could not resolve all files for configuration ':flutter_local_notifications:detachedConfiguration6'.
Failed to transform FakeDependency.jar to match attributes {artifactType=_internal-d8-desugar-methods, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
Execution failed for D8BackportedMethodsGenerator: path\FakeDependency.jar.
```

Get around the issue by including coreLibraryDesugaring in dependencies How do we solve the issue?

**Comment by MaikuB** [comment]
Please elaborate on where this an issue specific to the plugin as
1. FakeDependency.jar is not something from this plugin
2. You mention you are able to solve issue by enabling/including desugaring. This implies that you originally didn't do it but it's mentioned in the readme that it is needed. See https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#gradle-setup

**Comment by MaikuB** [comment]
Close due to lack of response
