### ISSUE TITLE
How to skip one scheduled recurring weekly notification?

### ISSUE THREAD

**Issue by iasiu** [MaikuB/flutter_local_notifications#1755]
I am using `zonedSchedule` to schedule weekly notifications on each of selected by the user weekdays, like this:
```dart
zonedSchedule(
   dateTime.weekday,
   'title',
   'body',
   dateTime,
   NotificationDetails(...),
   matchDateTimeComponents: DateTimeComponents.dayOfWeekAndTime,
   uiLocalNotificationDateInterpretation: UILocalNotificationDateInterpretation.absoluteTime,
 );
``` 
Is it possible to cancel today's notification before the scheduled time but not cancelling next week's Monday notification?

I tried with cancelling all notifications and rescheduling but for Monday using dateTime for next week's Monday but then I read [this](https://github.com/MaikuB/flutter_local_notifications/blob/341fa5875f274ece04c1e3d54a77ac51e20b8765/flutter_local_notifications/lib/src/flutter_local_notifications_plugin.dart#L348):
```
Note that when a value is given, the [scheduledDate] may not represent the 
first time the notification will be shown. An example would be if the date
and time is currently 2020-10-19 11:00 (i.e. 19th October 2020 11:00AM) and 
[scheduledDate] is 2020-10-21 10:00 and the value of the 
[matchDateTimeComponents] is [DateTimeComponents.time], then the next time a
notification will appear is 2020-10-20 10:00.
```
With this unfortunately there is also no way to set the first day on which a weekly notification is sent which could be a pretty handy feature.

**Comment by MaikuB** [comment]
There isn't a way to do this. This has to do with how the native notification APIs work and the semantics infer this how it's meant to work given they're all associated with the same notification. I'd suggest looking more into how these APIs work as the plugin is wrapper for them so understanding how these work is really a prerequisite. If you need something like this then you may need to investigate how it can be done via other means. For example, this may involve using a platform's API for running scheduling a job to run a job in the background
