### ISSUE TITLE
Zone schedule with matchDateTimeComponents: DateTimeComponents.dateAndTime does not use schedule year as first firedate

### ISSUE THREAD

**Issue by wanpaya** [MaikuB/flutter_local_notifications#1761]
Lib version : ^12.0.0
Method **zonedSchedule** with matchDateTimeComponents: DateTimeComponents.dateAndTime does not use schedule's year as initial fireDate.

To reproduce:
Call zonedSchedule with scheduleDate as 2099-03-01 it will fire on nowYear-03-01 instead.
I've found this on android but did not test on iOS yet.

It seems getNextFireDateMatchingDateTimeComponents in FlutterLocalNotificationPlugin.java
use now.getYear() as nextFireDate.

**Comment by MaikuB** [comment]
This is working as intended and was never meant to work the way you thought it would. This is why the property is named around matching certain date/time components of the given date/time and is explained in the [API docs for this method](https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/FlutterLocalNotificationsPlugin/zonedSchedule.html), specifically the part where it says

```
If a value for [matchDateTimeComponents] parameter is given, this tells
the plugin to schedule a recurring notification that matches the
specified date and time components.
```

This aligns with the APIs available on iOS as Apple's own APIs are focused around matching date/time components. There's no API to specify an initial date and then have it recurring based on certain date/time components
