### ISSUE TITLE
"Every 5 seconds", "every minute" (at least) don’t work in background if one close application before first launching notification in foreground mode

### ISSUE THREAD

**Issue by ValeriusGC** [MaikuB/flutter_local_notifications#1766]
Hi!

Steps to reproduce:

- Install from scratch
- Push buttons ‘every minutes’ or ‘every 5 seconds’
- Close application (remove from memory)
- Result – no notifications 

But if one gets first notification in foreground and then closes application then after that everything works fine.

**Device:** Realme XT, Android 11

**Comment by ValeriusGC** [comment]
Flutter 3.3.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 18a827f393 (3 weeks ago) • 2022-09-28 10:03:14 -0700
Engine • revision 5c984c26eb
Tools • Dart 2.18.2 • DevTools 2.15.0

**Comment by MaikuB** [comment]
This isn't to do with this plugin and outside its control. There's a caveat documented that relates to what you're seeing at  https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#scheduled-android-notifications so please read closely. If you run on a stock Android device like a Pixel or Android emulator then you'll find that it works as expected

**Comment by atretiakMobidev** [comment]
Newarly similar behavior. But I can't receive notifications for closed app after first launch. Relaunching and rescheduling and after it closing app from recents solves problem for all future schedulings. The same behavior on example app.

Was tested on Pixel 6 Android 13
