### ISSUE TITLE
Update Documentation to include import FlutterLocalNotificationsPlugin in AppDelegate.swift

### ISSUE THREAD

**Issue by som-R91** [MaikuB/flutter_local_notifications#1769]
Could any contributor update the documentation under Notification Actions to include the import statement?[https://pub.dev/packages/flutter_local_notifications#notification-actions](url)

** For Swift, open the AppDelegate.swift and update the didFinishLaunchingWithOptions as follows where the commented code indicates the code to add in and why.

**
`
import UIKit
import Flutter
import flutter_local_notifications
.......
.......
override func application(
  _ application: UIApplication,
  didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
  // This is required to make any communication available in the action isolate.
  FlutterLocalNotificationsPlugin.setPluginRegistrantCallback { (registry) in
    GeneratedPluginRegistrant.register(with: registry)
  }

  ...
  return super.application(application, didFinishLaunchingWithOptions: launchOptions)
}
`

**Comment by MaikuB** [comment]
This is open-source so this means you can submit a pull request yourself. There is no limitation on who can submit a pull request. Can you submit one through?
