### ISSUE TITLE
"example" app uses unreliable images

### ISSUE THREAD

**Issue by noinskit** [MaikuB/flutter_local_notifications#1772]
**Describe the bug**
The "example" app uses https://via.placeholder.com for "large icons" and "big pictures", which as it turns out can be randomly unreliable. I spent quite some time wondering why my phone does not display images in notifications until I learned that I was getting blocked by Cloudflare from my work IP from certain http clients (my Chrome opened these URLs just fine; maybe via.placeholder.com is not meant for programmatic access?)

To make things worse, this was a silent error, i.e. the "example" app ignored `http.Response` code and used the HTML source code of the "Attention Required! | Cloudflare" page as image data, which was passed all the way to OpenGLRenderer which judged that it's not a valid image ("Failed to create image decoder").

**To Reproduce**
I don't know what one must do to upset Cloudflare in this specific way.

**Expected behavior**
The "example" app should ideally use its own assets (except for demonstrating using URL images, I guess).

**Sample code to reproduce the problem**
N/A

**Comment by MaikuB** [comment]
The example app made use of these placeholder images to demonstrate that if one wants to make use of a remotely hosted image that they need to download it. This might seem obvious to some developers but was using the example app to try to make this clearer. As the example has used these images for a couple of years ago, I suspect the issue you saw was something intermittent and/or the owner of placeholder.com inadvertently changed some rules. I did notice the issue a week or two ago even when I opened the site in Chrome so doubt it was to do with IP addresses. From what I could gather, this is a popular site to get placeholder images (stats available at https://placeholder.com/about/) that it's rare that it goes down that picking another option would be more risky

**Comment by noinskit** [comment]
Are you sure using these outside of a browser, from a programmatic HTTP client is supported by via.placeholder.com?

My doubt on this and why I think IPs are involved in the decision to block request is based on the fact that over multiple days:
1) Placeholders did NOT load okay for me from within this "example app", from my work network.
2) Placeholders loaded okay for me from my work network, from a regular browser.
3) Placeholders loaded okay for me from within this "example app", using mobile data (i.e. cellular internet provider).

**Comment by MaikuB** [comment]
Given you've already mentioned the same app works on other networks then that already answers your question. You'll need to contact the owner of the site as if sounds like [WAF](https://www.cloudflare.com/waf/) has flagged your network and http client than this being a reliability issue. It would look at details IP address and the user agent so that's why it's with a browser from work network but not via a http client in the app. Perhaps you've done a lot of  requests via your work network that has triggered this. If you want them to look into it then check the response body for a ray ID that a Cloudflare admin can use to investigate

**Comment by MaikuB** [comment]
I've started getting the issues again and even tried to use the contact form to ask those running the site to see if there were intentional changes done. Unfortunately there's been a lack of response and found a site that seems to work.
