### ISSUE TITLE
On AndroidNotificationAction tap in foreground onDidReceiveBackgroundNotificationResponse is called

### ISSUE THREAD

**Issue by krupikivan** [MaikuB/flutter_local_notifications#1773]
**Describe the bug**
Being on foreground, after receiving the notification with 2 action buttons, after tapping 1 of those buttons onDidReceiveBackgroundNotificationResponse is being called instead of onDidReceiveNotificationResponse and because onDidReceiveBackgroundNotificationResponse is being executed in different isolate I could not handle navigation page

**To Reproduce**
Always on foreground
1. Display notification including 2 action buttons inside AndroidNotificationDetails (for example Answer or reject)
2. Click on any of those buttons
3. onDidReceiveBackgroundNotificationResponse is called instead of onDidReceiveNotificationResponse
4. If onDidReceiveBackgroundNotificationResponse is called in different thread I could not manage the routing to certain page

**Expected behavior**
The expected behaviour is to execute onDidReceiveNotificationResponse instead of onDidReceiveBackgroundNotificationResponse

**Sample code to reproduce the problem**

static FlutterLocalNotificationsPlugin get _notificationService =>
      FlutterLocalNotificationsPlugin();

await _notificationService.initialize(
      InitializationSettings(
        android: androidInitializationSettings,
        iOS: iosInitializationSettings,
      ),
      onDidReceiveNotificationResponse: onDidReceiveNotificationResponse,
      onDidReceiveBackgroundNotificationResponse: notificationTapBackground,

Main page

@pragma('vm:entry-point')
void notificationTapBackground(NotificationResponse notificationResponse) {
  selectNotificationStream.add(notificationResponse);
}

final StreamController<NotificationResponse?> selectNotificationStream =
    StreamController<NotificationResponse?>.broadcast();

**Comment by krupikivan** [comment]
This method (onDidReceiveNotificationResponse) is never being called at all

**Comment by ebelevics** [comment]
Yes, I noticed that yesterday too. As I want to update UI on notification button press, I can't as it runs in separate isolate. My expectation onDidReceiveNotificationResponse it should be possible but it's never called. 
onDidReceiveBackgroundNotificationResponse I would handle UI with WidgetsBindingObserver, but that's not the case as app actions are pressed when app is in foreground, but onDidReceiveBackgroundNotificationResponse is called for reason instead.

**Comment by MaikuB** [comment]
The callback invoked doesn't depend on the application lifecycle and it's not documented to based on that either.  `onDidReceiveBackgroundNotificationResponse` is called as such because of involving a background isolate. Please read the documentation more closely as it's mentioned at https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#notification-actions that this based on how you configuration your notification action. The example app is there for you to cross-reference and should be checked before raising an issue

**Comment by ebelevics** [comment]
While I tried to enable `showsUserInterface` I've noticed first that when app is killed I don't get notification anymore, before that everything worked on Android.

**Comment by ebelevics** [comment]
Yes, I'll try to reproduce minimal example.
