### ISSUE TITLE
Adding button to Notification

### ISSUE THREAD

**Issue by KallepalliTirumalesh** [MaikuB/flutter_local_notifications#1775]
Hi ,

Thank you for the plugin 

I am looking to add a button or text to foreground service notification(Ex: Stop Service) where i can add some functionality to it once user taps on it can you please tell how can i add and Does it supports for both Android and iOS.

Many Thanks

**Comment by ebelevics** [comment]
It's all stated in documentation https://pub.dev/packages/flutter_local_notifications#notification-actions

**Comment by MaikuB** [comment]
Thanks for answering @ebelevics. Will close this. On that note, a reminder to check the documentation as it would've also mentioned there's an example app for the plugin that can be checked
