### ISSUE TITLE
Return whole NotificationDetails object for debug purpose

### ISSUE THREAD

**Issue by KayLeung** [MaikuB/flutter_local_notifications#1782]
Currently when you called `flutterLocalNotificationsPlugin.pendingNotificationRequests()` only returned a few info.  Extra info, e.g. `scheduledDateTime` would help for debugging.

https://github.com/MaikuB/flutter_local_notifications/blob/af5fbe28bdf26159f3d57bcf48e36b32923e9bbb/flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java#L1364

**Comment by MaikuB** [comment]
Not looking to this. It involves a lot of manual work for little gain when this isn't even supported by the OS. If you're looking for this for your own debugging purpose then you can temporarily fork to add this in
