### ISSUE TITLE
cant play sound other default ringtone when push notification on ios

### ISSUE THREAD

**Issue by HaAnhHung** [MaikuB/flutter_local_notifications#1783]
When I push local notification, I use default ringtone ios file it's ok but other sound not working.
<img width="397" alt="Screen Shot 2022-11-14 at 15 00 19" src="https://user-images.githubusercontent.com/39230351/201607296-fb357d7a-73a6-4c50-bfe5-aed412fe2549.png">
<img width="448" alt="Screen Shot 2022-11-14 at 15 00 43" src="https://user-images.githubusercontent.com/39230351/201607346-bbea703c-04fe-4ee1-983d-bfea6c8f467d.png">

**Comment by mfarooqone** [comment]
Any Update?

**Comment by MaikuB** [comment]
This would indicate that you have not added the files to the project via XCode properly. This is something you would need to look up how to do properly as it's specific to how iOS development works as opposed to this being an issue with the plugin. As this is generic on how it works via iOS then there should fair bit of tutorials online for this. I don't recall the steps myself but the example app demonstrates that it works
