### ISSUE TITLE
unable to change custom sound 

### ISSUE THREAD

**Issue by harryandroiddev** [MaikuB/flutter_local_notifications#1784]
i am using it for showing notification at schedule timing just making like alarm app, where user will be able to select the custom sound , but when i change the sound it plays the previous sound . how to make it happen to play the new sound selected by the user .Getting this issue only on android on ios it is working fine .

**Comment by MaikuB** [comment]
Please read the docs more closely as it's stated that on Android, the sound is tied to a notification channel. This how the native platform works and it's up to you to determine how you achieve your requirements based on what is supported by the platform
