### ISSUE TITLE
Infinite INVALID_ICON errors being thrown.

### ISSUE THREAD

**Issue by iamchetangg** [MaikuB/flutter_local_notifications#1787]
**_Description_**

When the application is being run, this error ...

<img width="1440" alt="Screenshot 2022-11-14 at 5 57 11 PM" src="https://user-images.githubusercontent.com/46570522/201660170-6334cfcb-aaf1-42ae-a2e6-2b66f8df1b50.png">

is being thrown infinitely and the application never runs. 

This error usually prevents building the application, when there is a mention of an invalid or non-existent icon resource. But in my case, the icon exists, also the icon property is not being passed when initialising the plugin in flutter.

There are no mentions of this error anywhere. 

**_To Reproduce_**

1. Go to FlutterLocalNotifications package's example project.
2. Run the application
3. See error

_**Expected behavior**_

No error should appear and the application should run flawlessly.

**Comment by iamchetangg** [comment]
@MaikuB

**Comment by MaikuB** [comment]
Not sure what you're talking about given the example app actually works. It never attempts to the use the launcher icon, that would've been something you tried to do and likely did so incorrectly. The docs explicitly state to provide a drawable resource and the example has one that it uses called `app_icon`. The errors shown in your screenshot would have been from you trying to deviate from that, change the code and specify to use the launcher icon (`ic_launcher`), which isn't even in the drawable folder so the steps you tried to describe isn't accurate and the error is to be expected
