### ISSUE TITLE
Cannot find 'FlutterLocalNotificationsPlugin' in scope

### ISSUE THREAD

**Issue by theappideasankit** [MaikuB/flutter_local_notifications#1788]
FlutterLocalNotificationsPlugin.setPluginRegistrantCallback { (registry) in
        GeneratedPluginRegistrant.register(withRegistry: registry)
    }

**Comment by MaikuB** [comment]
You need to add import statements in. Admittedly this was missing the readme before but has been added in. See https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#notification-actions. Xcode may have suggested a fix it too
