### ISSUE TITLE
Calling specific method on actions

### ISSUE THREAD

**Issue by KallepalliTirumalesh** [MaikuB/flutter_local_notifications#1797]
Hi ,

I have referred the example but couldn't able to find how can we call a specific method while clicking on action button on notification like Stop activity is the action and when user clicks on it calling a specific method  and show an alert dialog.

I want to differentiate actions between notification tap and actions tap on notification

Can you please let me know how can i achieve that.

```
const AndroidNotificationDetails androidNotificationDetails =
        AndroidNotificationDetails(
      'your channel id',
      'your channel name',
      channelDescription: 'your channel description',
      importance: Importance.max,
      priority: Priority.high,
      ticker: 'ticker',
      actions: <AndroidNotificationAction>[
       
        AndroidNotificationAction(
          'id_2',
          'Action 2',
          titleColor: Color.fromARGB(255, 255, 0, 0),
          icon: DrawableResourceAndroidBitmap('secondary_icon'),
        ),
   
      ],
    )
```

**Comment by MaikuB** [comment]
The example app would've shown how this works if you had run it. The details are mentioned in https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#notification-actions
