### ISSUE TITLE
push notification will disappear when opening notification center on ios

### ISSUE THREAD

**Issue by ahmadvicky** [MaikuB/flutter_local_notifications#1799]
please help why push notification will gone if open Notification Center while foreground?
<img width="561" alt="Screenshot 2022-11-21 at 16 30 38" src="https://user-images.githubusercontent.com/25771147/203015025-6346dd19-525a-40a0-9ebd-c9c75ab56d9b.png">
![Screenshot 2022-11-21 at 16 31 02](https://user-images.githubusercontent.com/25771147/203015118-4caa2b30-f569-4bcd-adc2-8d7f47d318cb.png)

**Comment by MaikuB** [comment]
Do you have to say that it is this plugin doing it? If it was due to this plugin then this would happen in the example app that you can run it and provide a recording to show this

**Comment by MaikuB** [comment]
Closing due to lack of further response with evidence that it is only to due with this plugin. There's been no reported issues on this either that is specifically to do with this plugin either given how long it's been out

**Comment by Bungeefan** [comment]
I stumbled upon this issue while researching for a very similar problem of vanishing notifications when using this package, in my case it seems to be triggered by using `flutter_local_notifications` and `push` together, and `push` overriding it.

For the convenience of future users encountering a similar problem, I am dropping the link to the corresponding [issue](https://github.com/ben-xD/push/issues/29) in the `push` repository.
