### ISSUE TITLE
0.5.2 not build in flutter stable 1.0

### ISSUE THREAD

**Issue by welldone217** [MaikuB/flutter_local_notifications#180]
it show me:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'androidx.core:core' has different version for the compile (1.0.0) and runtime (1.0.1) classpath. You should manually set the same version via DependencyResolution

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by welldone217** [comment]
i try to 1.2.1    .sorry about that.

**Comment by welldone217** [comment]
i try to 1.2.1 .it is the same error

**Comment by MaikuB** [comment]
I believe you need to look at what's described here
https://flutter.dev/docs/development/packages-and-plugins/developing-packages#conflict-resolution
