### ISSUE TITLE
Heads up notifications do not show after open drawer

### ISSUE THREAD

**Issue by hungbu** [MaikuB/flutter_local_notifications#1800]
I test with bellow code :

```
_showLocalNotification() async {
    int i = 0;
    do {
      await Future.delayed(Duration(seconds: 5), () {
        _localNotificationService.showLocalNotification(); // show a heads up notification
        i++;
      });
    } while (i < 5);

  }
```

heads up notifications show  normal

but after open drawer, it only show on notifications center.

**Comment by MaikuB** [comment]
This has nothing to do with plugin as all it does is call the native APIs so what you are seeing would be expected behaviour on how the platform behaves
