### ISSUE TITLE
README: Recommend android.window as Android dependencies

### ISSUE THREAD

**Issue by 12people** [MaikuB/flutter_local_notifications#1801]
There is a desugaring-related bug on Android 12L and Android 13, where an app with desugaring enabled crashes on startup — see [this StackOverflow thread](https://stackoverflow.com/questions/74163927/flutter-chrash-in-android-12l-with-no-interface-method-addwindowlayoutinfoliste).

The fix for this desugaring bug is to add these two dependencies:
```
implementation 'androidx.window:window:1.0.0'
implementation 'androidx.window:window-java:1.0.0'
```

It'd be great if `flutter_local_notifications` recommended these two dependencies in the [guidelines on pubdev](https://pub.dev/packages/flutter_local_notifications#gradle-setup) alongside other necessary desugaring-related Gradle changes.

**Comment by MaikuB** [comment]
Thanks for raising this. As this is open-sourced, would you be up for submitting a PR to add this information to the readme?

**Comment by 12people** [comment]
@MaikuB Submitted here: https://github.com/MaikuB/flutter_local_notifications/pull/1803

**Comment by MaikuB** [comment]
Closing as the PR has been merged now :)
