### ISSUE TITLE
UNUserNotificationCenterDelegate conflict

### ISSUE THREAD

**Issue by Yi-cherish** [MaikuB/flutter_local_notifications#1802]
FlutterLocalNotificationsPlugin and iOS appDelegate's UNUserNotificationCenterDelegate methods conflict。
If the UNUserNotificationCenterDelegate method is implemented in iOS appDelegate, the UNUserNotificationCenterDelegate method in FlutterLocalNotificationsPlugin will not be called。
Call methods such as：
 - (void) userNotificationCenter: (UNUserNotificationCenter *) center  didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void (^)(void))completionHandler；

**Comment by MaikuB** [comment]
Given only one delegate can be registered then this is to be expected as only one can handle an event. In saying that, add code to `FlutterAppDelegate` should work given this exposes an override that you can call the original implementation.

For example, I added the following to the example app 

```
    override func userNotificationCenter(_ center: UNUserNotificationCenter, didReceive response: UNNotificationResponse, withCompletionHandler completionHandler: @escaping () -> Void) {
        NSLog("hello");
        super.userNotificationCenter(center, didReceive: response, withCompletionHandler: completionHandler)
        return;
    }
```

I then ran the app in XCode and upon tapping on a notification, this navigated to another page as expected and "hello" was logged. I would hazard a guess that you want to call the super method. Either that or called the completionHandler that is only meant to be called when done and this would be done by the plugin

**Comment by Yi-cherish** [comment]
Yes, thank you
