### ISSUE TITLE
Navigation through notification actions, cant get context or global navigatorKey

### ISSUE THREAD

**Issue by vaartatechnologies** [MaikuB/flutter_local_notifications#1805]
Navigation through notification actions not working, can't get context or global navigatorKey without being null. Below is the code:

	@pragma('vm:entry-point')
	static void notificationTapBackground(NotificationResponse notificationResponse) {
		if(notificationResponse.actionId == 'reject'){
			_removeForegroundServiceNotification();
		} else if(notificationResponse.actionId == 'accept'){
			if(notificationResponse.payload == null || notificationResponse.payload == '') {
				_removeForegroundServiceNotification();
				Functions.showToast('Error Occurred', 'Short');
			} else {
				Map<String, dynamic> data = jsonDecode(notificationResponse.payload!);
				_removeForegroundServiceNotification();
				if(NavigationService.navigatorKey.currentState == null){
					debugPrint('debug: Null'); // Always null & no option to get context
				} else {
					debugPrint('debug: Not Null');
				}
				//NavigationService.navigatorKey.currentState!.pushNamed('/call-ui', arguments: data);
			}
		}
	}

Is it an issue or something that I am not able to figure out?

**Comment by chubzchoc** [comment]
I encounter this issue also, my navigation Key always null when app state is terminated

**Comment by MaikuB** [comment]
This is expected behaviour. I suggest you read the section on notification actions more closely (https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#notification-actions) as it's stated that depending on how they're configured as you have done here, they will run in background isolate
