### ISSUE TITLE
custom sound doesnt work.

### ISSUE THREAD

**Issue by faisalmushtaq007** [MaikuB/flutter_local_notifications#1808]
i even tried your example but it just vibrates and there's no sound. 
Can you tell me why is that?
i also tried on multiple devices.

**Comment by faisalmushtaq007** [comment]
@MaikuB i got the issue. The problem is that when we run the app and check the notification settings of app sound and lcd settings are disabled. Can u tell me how to enable those settings programatically??

**Comment by MaikuB** [comment]
There is no such thing so nothing further that can be done. If you have this setting that needs to be turned on like this then it sounds like you're using devices with non-stock version of Android where manufacturers have customised their version of Android. As an example, there's no need to tweak these settings for Pixel devices and it will all work out of the box
