### ISSUE TITLE
No notification working after turning off

### ISSUE THREAD

**Issue by dmorillas** [MaikuB/flutter_local_notifications#181]
This is my AndroidManifest:

`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="PACKAGE">

    
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />

    
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="LABEL"
        android:icon="@mipmap/ic_launcher">

        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>

        <receiver android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver" />
        <receiver android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"></action>
            </intent-filter>
        </receiver>
    </application>
</manifest>
`
and I guess I have in it everything is needed. But, if I schedule a daily notification, it stops showing up once I turn the device off.

**Comment by MaikuB** [comment]
So you never see it ever again? Have you tried the sample app and do you run into the same problem with it?

**Comment by dmorillas** [comment]
Yes, that's true, I never see it again. As long as I keep the device on, everything works perfect and smooth. But, once I shut it down and turn it on again the notification is never triggered until I get into the app and schedule it again.

I have also tried with the sample app and I get the same error. I schedule the "5 seconds notification", although I have changed to 3 minutes, (to have time to reboot the device) and same error.

While testing, I have been checking the logcat and didn't see this log:
https://github.com/MaikuB/flutter_local_notifications/blob/835d73b315baef3a88ed61718972e36e027a8a5f/android/src/main/java/com/dexterous/flutterlocalnotifications/ScheduledNotificationBootReceiver.java#L12

Not sure if I should have seen it.

As an information, I have a Huawei Mate 20 (model HMA-L29) with Android version 9 (the latest)

**Comment by dmorillas** [comment]
I have just tried with another Android device I have. A LG K10 with Android 6 and worked fine.
After rebooting the device I saw the "rebooted" log and after a few seconds the notification popped up.

Maybe an incompatibility in the latest version of Android?

**Comment by MaikuB** [comment]
That shouldn't be the issue as I have a pixel 2 xl so that is running the latest

**Comment by dmorillas** [comment]
ok, then the problem might be in the device, somehow the Huawei prevents the BroadcastReceiver to work as expected :confused:
I'll investigate if that is the problem. At least, I'm happy that the notifications seem to work as expected in most of the devices.

**Comment by MaikuB** [comment]
closing due to lack of further response and possibly to due with the OEM's implementation of Android

**Comment by hakanyusufoglu** [comment]
Has this problem been solved? i have huawei p20 pro too and i can't see notifications when i turn the phone off and on. 

Thanks

**Comment by hakanyusufoglu** [comment]
Hello, the notifications do not appear when the device is restarted, as you said, it is due to the operating system. My device is huawei p20 pro. I solved this problem as follows;

(These process steps may not be the same for all phone brands.)
1. Go to the settings section of your device.
2. Click "Apps" section
3. Enter the "App launch" section. Here, manually change the management style of your application and let it run in the background. Thus, your notifications will be made whenever you reboot your device.

version of "flutter_local_notification" I used: 3.0.1+4

Thanks. Best Regards.

**Comment by kinton** [comment]
Hello!
I have a slightly similar problem: the application sends morning and evening notifications, and if **the device is turned off** during the morning notification, then during the evening one **I receive both morning and evening notifications**.
