### ISSUE TITLE
Notifications after restart device not works

### ISSUE THREAD

**Issue by diego871016** [MaikuB/flutter_local_notifications#1810]
Hi friend thanks for you work
I have the following situation.
1.	download the repository (OK)
2.	I go to the next file(flutter_local_notifications-master\flutter_local_notifications\example\lib\Main.dart)(OK).
3.	Change the “Future<void> _repeatNotification()” (OK)
4.	Changed the example for every minute for every hour( RepeatInterval.minute for Repeatinterval.hourly) in Main.dart.
Compiles and deploys to the test device.
Execute the modified function to have the execution test every hour.
First execution without incident, the application closes and works without incident but if I restart my device it does not continue with the notifications.
But if I enter and validate pending notifications, one registers me, but its execution never takes place.
Thanks for your help

**Comment by MaikuB** [comment]
Is this on an Android device? If so, which one? There are some devices that don't use the stock Android OS as manufacturers have customised it for their own purposes. In this case, you need to check the settings to see if there's something that needs to be changed. This relates to the caveat mentioned at https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#scheduled-android-notifications and is outside the control of the plugin

**Comment by MaikuB** [comment]
FYI I retested this on Pixel 6 and saw that it worked as expected

**Comment by diego871016** [comment]
Thanks
