### ISSUE TITLE
Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.

### ISSUE THREAD

**Issue by Unevenn** [MaikuB/flutter_local_notifications#1814]

**Comment by Unevenn** [comment]
When i creating schedule notification i am getting this error.
My android app/build.gradle

      dependencies {
          implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
          implementation platform('com.google.firebase:firebase-bom:31.0.1')
          implementation 'com.google.firebase:firebase-analytics'
          implementation 'androidx.multidex:multidex:2.0.1'
          implementation 'com.google.android.gms:play-services-appset:16.0.2'
          implementation 'com.google.android.gms:play-services-ads-identifier:18.0.1'
          implementation 'com.google.android.gms:play-services-basement:18.1.0'
          implementation 'androidx.work:work-runtime-ktx:2.8.0-alpha01'
          implementation 'com.onesignal:OneSignal:4.6.3'
          implementation 'com.google.android.gms:play-services-ads:20.4.0'
      }
       compileSdkVersion 33
       defaultConfig {
              // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
              applicationId "xxx"
              minSdkVersion 23
              targetSdkVersion 32
              versionCode 4
              versionName '1.0.3'
              multiDexEnabled true
          }

and I added in the my manifest.xml

      <receiver tools:replace="android:exported" android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver" android:exported="true" />
        <receiver tools:replace="android:exported" android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver" android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"></action>
            </intent-filter>
      </receiver>

and my function

           Future<void> _zonedScheduleNotification(text, Duration duration, id) async {
              if (!duration.isNegative) {
                await flutterLocalNotificationsPlugin.zonedSchedule(
                    id,
                    text,
                    null,
                    tz.TZDateTime.now(tz.local).add(duration),
                    NotificationDetails(
                        android: AndroidNotificationDetails(
                      'Ezan Kanalı',
                      'Ezan',
                      importance: Importance.max,
                      priority: Priority.high,
                      playSound: true,
                      sound: RawResourceAndroidNotificationSound('ezan'),
                    )),
                    androidAllowWhileIdle: true,
                    uiLocalNotificationDateInterpretation:
                        UILocalNotificationDateInterpretation.absoluteTime);
              }
            }

problem not solved. Anybody help?

**Comment by FlaviusBanc** [comment]
same thing happening to me, works tho on versions below 31

**Comment by FlaviusBanc** [comment]
also adding `implementation 'androidx.work:work-runtime:2.7.1'` inside app\build.gradle did not work

**Comment by FlaviusBanc** [comment]
**Solution:** check inside the pubsec.yaml folder if the flutter_local_notification dependency is upgraded to `flutter_local_notifications: ^12.0.4`

**Comment by Unevenn** [comment]
> **Solution:** check inside the pubsec.yaml folder if the flutter_local_notification dependency is upgraded to `flutter_local_notifications: ^12.0.4`

Not worked all solutions. I do not now why? In my other projects working.

**Comment by MaikuB** [comment]
You'll need to provide a link to a minimal app that can reproduce the issue and only uses this plugin. As implied by @FlaviusBanc, this should've been to do with the version of the plugin used and this issue was reported in https://github.com/MaikuB/flutter_local_notifications/issues/1476 and resolved in version 10 before

**Comment by vienhp1996** [comment]
> You'll need to provide a link to a minimal app that can reproduce the issue and only uses this plugin. As implied by @FlaviusBanc, this should've been to do with the version of the plugin used and this issue was reported in #1476 and resolved in version 10 before

I am using version 4.0.1, do you have a fix? thank

**Comment by MaikuB** [comment]
@vienhp1996 already mentioned earlier the version that had the fix. You'll need to update your dependencies as part of maintaining an application. If you don't want to update then you need to fork and implement your own fix based on the version you're using

**Comment by MaikuB** [comment]
Closing as @Unevenn has yet to reply to provide the requested information. I suggest you check the other dependencies you have in your application as you may have confused things to think that it's a problem with this plugin.
