### ISSUE TITLE
Only use for Android foreground notifications?

### ISSUE THREAD

**Issue by rivella50** [MaikuB/flutter_local_notifications#1816]
Hi there,

we use firebase_messaging for all the notifications our app has to handle, which works fine.
Now we were asked to also support displaying foreground messages the app receives.
For iOS this works fine by just calling
```
await FirebaseMessaging.instance.setForegroundNotificationPresentationOptions(
   alert: true,
   badge: false,
   sound: true,
);
```
Regarding Android using `flutter_local_notifications` seems to be the best solution.
Now my question: Can we configure and use this plugin just for the Android foreground notifications and leave everything else as it works fine now? Or does enabling the plugin for Android automatically contains "the whole package"?

**Comment by MaikuB** [comment]
I'm not exactly sure what your concern is but I assume it's on if your app would include other code in the plugin. If so,  my understanding is the Dart compiler will do tree shaking for release builds. Meaning it's not to with how the plugin works. FYI you could also use this directly on Android as this is what gets used behind the scenes on Android
https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/AndroidFlutterLocalNotificationsPlugin-class.html
