### ISSUE TITLE
How to change background color of notification flutter_local_notification?

### ISSUE THREAD

**Issue by Sania-Developer** [MaikuB/flutter_local_notifications#1817]
I am using the **flutter_local_notification** package for showing the notification. For example, I want to change the background color of notifications to blue, but using the color property in notification detail changes the text color of the App name only.

**_Code:_**

_AndroidNotificationDetails(
      'CHANNEL_ID',
      'CHANNEL_NAME',
      channelDescription: 'CHANNEL_DESCRIPTION',
      importance: Importance.max,
      priority: Priority.high,
        icon: 'logo',
        sound: RawResourceAndroidNotificationSound('notification_sound'),
      styleInformation: DefaultStyleInformation(true, true),
      playSound: true,
        color: light_blue_color,
        largeIcon: const DrawableResourceAndroidBitmap('logo'),
        colorized: true,
    );_

**Comment by MaikuB** [comment]
Please try to check API docs more closely. In this case the doc https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/AndroidNotificationDetails/colorized.html would have said the following

```
For most styles, the coloring will only be applied if the notification is or a foreground service notification.
```

Note the plugin acts as bridge to native notification APIs so you still need to ensure you spend time understanding what your target platform supports and APIs that are available
