### ISSUE TITLE
AndroidNotificationAction titleColor not working in dark mode

### ISSUE THREAD

**Issue by letrungdo** [MaikuB/flutter_local_notifications#1819]
**Describe the bug**
AndroidNotificationAction titleColor light mode ok but not working in dark mode.

**To Reproduce**
Setting device to Dark mode

**Comment by MaikuB** [comment]
This working as intended and not a bug. There's no documented behaviour to say the colour would change. Furthermore, it doesn't make sense that you specify a colour and it ends up changing based on the theme as this would negate the reason why you specify a colour to begin with. If you want this kind of behaviour then you need to look into your own solution for this
