### ISSUE TITLE
Notifications that are scheduled don't fire correctly

### ISSUE THREAD

**Issue by RAHUL-KALLAZHI** [MaikuB/flutter_local_notifications#1824]
Hi
In my project, I use this package to create reminders for intervals of 30 minutes, an hour, and two hours. Occasionally, though, the notice is not sent at the specified time, and other times it is delivered twice at the scheduled time.

First create List of DateTime of scheduled times and pass it to scheduleJournalNotification(), Using a for loop assign the values from scheduled time list to zonedSchedule(), 

  Future<void> scheduleJournalNotification(
      List<DateTime> notificationTimes) async {
    final details = await journalNotificationDetails();
    for (int i = 0; i < notificationTimes.length; i++) {
      journalNotificationService.zonedSchedule(
          i,
          "Journal Alarm",
          "Journal Alaram Body",
          tz.TZDateTime.from(notificationTimes[i], tz.local),
          details,
          uiLocalNotificationDateInterpretation:
              UILocalNotificationDateInterpretation.absoluteTime,
          androidAllowWhileIdle: true);
    }
  }

**Comment by litov74** [comment]
Hello! Getting same issue with zonedSchedule. In my project I added 4 notifications for each celebration date (f.ex. 1st Jan), but my app "congratulate" me with new year in the beginnig of december. Also, notifications that are scheduled for next year, fires now. This issue is on the Android and iOS. May be it's an issue with NotificationManager, but I don't have any ideas.

**Comment by litov74** [comment]
Solved Successfully!))) the devil is in the details) let me show you my code snippet.

`await flutterLocalNotificationsPlugin.zonedSchedule(
        int.parse("${notificationId}3"),
        'congrats!',
        'happy new year!',
        _nextInstanceOfNineMay(),
        const NotificationDetails(
          android: AndroidNotificationDetails('channel with congrats',
              'channel with congrats',
              channelDescription: 'channel with congrats'),
        ),
        androidAllowWhileIdle: true,
        uiLocalNotificationDateInterpretation:
        UILocalNotificationDateInterpretation.absoluteTime,
        matchDateTimeComponents: DateTimeComponents.dateAndTime);`

here you should be **VERY** careful with notification ID and matchDateTimeComponents.

I defined notificationId with the following way (code is from author's repo, thanks;)))
`int notificationId = Random().nextInt(1000000);`

AND

`matchDateTimeComponents: DateTimeComponents.dateAndTime` <-- here we need dateAndTime to fire notification only on specific day (ad not to fire it if we just change date/time).

Good Luck;)

**Comment by MaikuB** [comment]
@RAHUL-KALLAZHI if you are having issues with timing then either there's an issue with your code or you need to check the devices you're using. If you're running on Android then you check the timings on device/emulator with stock Android. Other manufacturers may have settings relating to battery optimisations that affect the timing and is outside the control of the plugin
