### ISSUE TITLE
onDidReceiveLocalNotification method is not working in foreground (IOS devices)

### ISSUE THREAD

**Issue by flutterDevs-2010** [MaikuB/flutter_local_notifications#1825]
The latest **flutter_local_notification: ^12.0.4** plugin  is perfectly working in android devices both in foreground as well as background but in the case of **IOS devices** we are getting notification in foreground but **onDidReceiveLocalNotification** method is not triggering. 

My Code snippet:

**// Init Ios Notification Settings**

      final DarwinInitializationSettings initializationSettingsIOS =
        DarwinInitializationSettings(
      requestSoundPermission: true,
      requestBadgePermission: true,
      requestAlertPermission: true,
          onDidReceiveLocalNotification:
              (int id, String? title, String? body, String? payload) async {
                debugPrint("stream: receivedNotification");
            didReceiveLocalNotificationStream.add(
              ReceivedNotification(
                id: id,
                title: title,
                body: body,
                payload: payload,
              ),
            );
          },
      notificationCategories: [
        DarwinNotificationCategory(
          'IOS_Channel',
          actions: <DarwinNotificationAction>[
            DarwinNotificationAction.text(
              'snooze_button',
              'Snooze',
              buttonTitle: "Snooze",
              placeholder: "Snooze",
              options: <DarwinNotificationActionOption>{
                DarwinNotificationActionOption.foreground,
              },
            ),
            DarwinNotificationAction.plain(
              'dismiss_button',
              'Dismiss',
              options: <DarwinNotificationActionOption>{
                DarwinNotificationActionOption.foreground,
              },
            ),
          ],
          options: <DarwinNotificationCategoryOption>{
            DarwinNotificationCategoryOption.customDismissAction,
          },
        )
      ],
    );
     final InitializationSettings initializationSettings =
        InitializationSettings(
            android: initializationSettingsAndroid,
            iOS: initializationSettingsIOS,
            macOS: null);

    await flutterLocalNotificationsPlugin.initialize(
      initializationSettings,
      onDidReceiveNotificationResponse: onDidReceiveTapNotificationResponse,
      onDidReceiveBackgroundNotificationResponse: onDidReceiveTapNotificationResponse,
    );

**Kindly help to get override this issue. We will be thankful to you.**

**Comment by MaikuB** [comment]
Please ensure you read the documentation properly as it has been stated that this callback is on older versions of iOS where a notification won't be shown when the app is in the foreground. The fact that you get a notification in the foreground would indicate you're running on an iOS version >= 10 and hadn't checked the docs on this callback i.e. https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#handling-notifications-whilst-the-app-is-in-the-foreground and https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/DarwinInitializationSettings/onDidReceiveLocalNotification.html

**Comment by amit-flutter-dev** [comment]
Having any method which handle this in 10+ version onDidReceiveLocalNotification: onDidReceiveLocalNotification
