### ISSUE TITLE
onDidReceiveBackgroundNotificationResponse callback not being triggered on iOS

### ISSUE THREAD

**Issue by kjwong** [MaikuB/flutter_local_notifications#1828]
On flutter_local_notifications 12.0.4, the `onDidReceiveBackgroundNotificationResponse` callback is not working for iOS devices (testing on an iOS 16.0 simulator and a physical iphone on iOS 15.6.1) when the app is open in the background.

Side note: `flutterLocalNotificationsPlugin.initialize()` returns `false` when passing in `requestAlertPermission`, `requestBadgePermission`, `requestSoundPermission` as `false` but returns `true` when passing those values as `true`. However, this observation seems independent from why the callback isn't working -- in both cases, the notifications show up fine but the on-tap callback doesn't get triggered.

Saw another issue (https://github.com/MaikuB/flutter_local_notifications/issues/1631) where there was a potential incompatibility with firebase_messaging, but our app doesn't use that package.

**Code snippet in `main.dart`**
```
@pragma('vm:entry-point')
void notificationTapBackground(NotificationResponse notificationResponse) {
  // ignore: avoid_print
  print('notification(${notificationResponse.id}) action tapped: '
      '${notificationResponse.actionId} with'
      ' payload: ${notificationResponse.payload}');
  if (notificationResponse.input?.isNotEmpty ?? false) {
    // ignore: avoid_print
    print(
        'notification action tapped with input: ${notificationResponse.input}');
  }
}

final FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
      FlutterLocalNotificationsPlugin();

  final DarwinInitializationSettings initializationSettingsDarwin =
      DarwinInitializationSettings(
    requestAlertPermission: false,
    requestBadgePermission: false,
    requestSoundPermission: false,
  );
  final InitializationSettings initializationSettings = InitializationSettings(
    iOS: initializationSettingsDarwin,
    macOS: initializationSettingsDarwin,
  );
  bool? initialized = await flutterLocalNotificationsPlugin.initialize(
    initializationSettings,
    onDidReceiveNotificationResponse:
        (NotificationResponse notificationResponse) {
      print(notificationResponse);
    },
    onDidReceiveBackgroundNotificationResponse: notificationTapBackground,
  );
  print("Notifications: $initialized");
  await flutterLocalNotificationsPlugin.zonedSchedule(
      0,
      "testing",
      'testing',
      datetime,
      const NotificationDetails(iOS: DarwinNotificationDetails()),
      androidAllowWhileIdle: true,
      uiLocalNotificationDateInterpretation:
          UILocalNotificationDateInterpretation.wallClockTime,
      matchDateTimeComponents: DateTimeComponents.time);
```

**Comment by RajLogistic** [comment]
I have also facing this but on android onDidReceiveBackgroundNotificationResponse not triggered

**Comment by vaibhavjoshi247** [comment]
Did anyone find the solution?
I am stuck here.

**Comment by MaikuB** [comment]
This is happening as the callback only works for notification actions if they're configured to used background isolates

**Comment by kjwong** [comment]
@MaikuB how would you configure that (using v12.0.4)? Apologies if that info's readily available, but it's not immediately clear to me from the docs/glossing over the `DarwinNotificationAction` implementation.

**Comment by MaikuB** [comment]
@kjwong please see https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#notification-actions. Will close as this was a misunderstanding and not an actual bug
