### ISSUE TITLE
Why would my onSelectNotification event keep firing?

### ISSUE THREAD

**Issue by FineTillYouCameAlong** [MaikuB/flutter_local_notifications#183]
I'm just playing around and testing and I'm having the notification being set by a button on my setting screen. When the notification shows up and I select it, the `onSelectNotification` does what it's supposed to do. However when I go to my settings screen again, it fires the `onSelectNotification` again.
How can I stop `onSelectNotification` from firing every time? Can I somehow "consume" the notification?

**Comment by MaikuB** [comment]
The example app is configured similar to what you've described and doesn't have the same problem so hard to say unless you're able to provide steps to reproduce or an example app that reproduces the problem (e.g. by forking this repo). At this stage I can only say you'd have to debug to find out.

**Comment by MaikuB** [comment]
Closing this. If you're able to provide a sample app to reproduce this then feel free to reopen the issue then

**Comment by javadkt** [comment]
> I'm just playing around and testing and I'm having the notification being set by a button on my setting screen. When the notification shows up and I select it, the `onSelectNotification` does what it's supposed to do. However when I go to my settings screen again, it fires the `onSelectNotification` again.
> How can I stop `onSelectNotification` from firing every time? Can I somehow "consume" the notification?

Facing same issue. Could you please explain how to fix this if you already did.
