### ISSUE TITLE
its not working on where app is in background or killed 

### ISSUE THREAD

**Issue by viadots** [MaikuB/flutter_local_notifications#1830]
When the app is in background or killed , flutter full screen notification is not working

**Comment by MaikuB** [comment]
You're going to need to provide more details than this. This includes details like the devices you're testing with and if you have tried to confirm this using the example app on a device/emulator running stock Android. The latter is important as I had put the following section that is likely the issue you're encountering https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#scheduled-android-notifications and this is outside the control of the plugin

**Comment by igornast** [comment]
I have the same problem after the version bump. The problem exists also with a clean new setup (checked on a new project). The app is not calling the handler after it was killed. Notification handlers are invoked if an app is in the background (wasn't killed).

**Comment by igornast** [comment]
@viadots at the end I just made use of the messaging function:
```dart
// If the application has been opened from a terminated state...
    FirebaseMessaging.instance
        .getInitialMessage()
        .then((RemoteMessage? message) {});
```

**Comment by MaikuB** [comment]
@igornast please check the docs more closely as there's mention that since version 4.0.0 that handling when a notification launches an app should be done via the `getNotificationAppLaunchDetails()` method

**Comment by igornast** [comment]
Yeah, I saw that. But it doesn't behave as I expected. When an app is opened from termination via notification clicking the method returns null :) Either I don't know how to use it or something is not ok in this case.
The background behavior is fine.

**Comment by MaikuB** [comment]
If it's returning null but using the method from FCM plugin works for you then it sounds like you are likely confusing dealing with notifications from this plugin vs those from FCM. This plugin will not be aware of dealing with notifications coming from FCM

**Comment by igornast** [comment]
Ok, so the plugin is only taking care of showing notifications, right? But a developer has to implement receiving notification logic on his own. Is it correct?

**Comment by MaikuB** [comment]
@igornast yes. This will always be the case regardless of the plugin you use. Plugins are responsible for providing a way to access the platform's native APIs. It's your responsibility to handle the logic. A similar thing could likely be said for the majority of libraries you will ever use that you will still need to handle implementing the logic you need.

Going to close this since the OP (@viadots) hasn't responded and would also need evidence of an actual issue.
