### ISSUE TITLE
onDidReceiveBackgroundNotificationResponse not called on notification tap

### ISSUE THREAD

**Issue by RajLogistic** [MaikuB/flutter_local_notifications#1831]
onDidReceiveBackgroundNotificationResponse not called when i taped on notification when my app is on backgroundState , does anyOne faced same issue or something i missed for local notification setup.

Its work fine in forGround state.

from onDidReceiveBackgroundNotificationResponse method i want payload from notification tap so that accordingly i can navigate to particular screen.

**Comment by MaikuB** [comment]
Have you reproduced this with the example app yet? If not please try to provide ways of reproducing this via the example app first. You can fork the repository and make changes if needed to reproduce the issue and then provide a link here. Note that the callback has nothing to do with if the app is on the background

**Comment by MaikuB** [comment]
Closing due to lack of response. Feel free to re-open if you believe there is an issue that you can reproduce with the example app and provide evidence of this
