### ISSUE TITLE
Custom Notification Sound Not Working After Android App Update

### ISSUE THREAD

**Issue by Juuuub** [MaikuB/flutter_local_notifications#1833]
**Describe the bug**
I have noticed that our notifications are not playing any sounds after users download a new version of our app from the play store. Similar issue in this [link](https://github.com/invertase/react-native-notifee/issues/341#issue-949453601).

**To Reproduce**
1. Create a new build release with a custom notification channel and sound, install the app.
2. Test custom sound notification works by sending to channel.
3. Create a new release, do not uninstall the older version, update from the current version. 
4. Custom sound missing when sending to the same channel.

**Expected behavior**
Only remedy is for the user to uninstall the application and install the new application. Running from flutter automatically uninstalls the existing version and installs the new version, cannot be tested that way.

**Sample code to reproduce the problem**
When our app boots we create the notification channels as follows:
```
AndroidNotificationChannel channel = AndroidNotificationChannel("trip_request", "Trip Request Notifications",
      description: "This channel is used for trip notifications",
      importance: Importance.max,
      sound: RawResourceAndroidNotificationSound('tripnotification'),
      enableVibration: true,
      playSound: true);
flutterLocalNotificationsPlugin
          .resolvePlatformSpecificImplementation<AndroidFlutterLocalNotificationsPlugin>()
          ?.createNotificationChannel(channel)
```

**Comment by MaikuB** [comment]
Similar code changes to like those done in the notifee library had already been done a while back in https://github.com/MaikuB/flutter_local_notifications/pull/1379. If you're having this issue then sounds like you are using an older version of the plugin and the fix isn't something that can be retroactively applied

**Comment by MaikuB** [comment]
Closing this as this change was done a long time ago. If you believe the issue still exists feel free to re-open but please provide a link to a repo with a minimal app that can reproduce the issue and that it uses the latest version of the plugin
