### ISSUE TITLE
The set notification icon color appears with a different shade on Android

### ISSUE THREAD

**Issue by Ashhas** [MaikuB/flutter_local_notifications#1836]
Hi!

I ran into the issue where the color that I set for the app icon, appears in a different shade. When adding this icon to my own app, I realised that that the app icon seems to be a bit darker than it should be. That's why I tested in the example app and saw the same behavior. I tested on my emulator and also multiple physical devices and saw the same. 

Did I forget to configure something? Or is this just the expected behavior on Android?

Thanks in advance!

**To Reproduce**

1. Run the example app on a device/emulator
2. Go to the `_showNotificationCustomVibrationIconLed` method (Or any method that adds an icon to the notification)
3. Change `AndroidNotificationDetails.color` to a different color (I used: `#00E487`/`rgb(0, 228, 135)` to test)
4. Call `_showNotificationCustomVibrationIconLed` and inspect the app icon

**Sample of the `AndroidNotificationDetails` object used to setup the notification**
```dart
    const AndroidNotificationDetails androidNotificationDetails =
        AndroidNotificationDetails(
      'other custom channel id',
      'other custom channel name',
      channelDescription: 'other custom channel description',
      icon: 'app_icon', // Changed the icon since it has a bigger surface to inspect, however the clock shows the same thing
      color: Color.fromARGB(255, 0, 228, 135), // Or Color(0xFF00E487)
    );
```

**Comment by MaikuB** [comment]
What you see is what you get. FYI that what this plugin exposes functionality of the native platform so you still need to do understand how the platform works
