### ISSUE TITLE
[Android] foreground notification causes a null pointer exception

### ISSUE THREAD

**Issue by seungku** [MaikuB/flutter_local_notifications#1837]
A null pointer exception occurs when flutterLocalNotificationsPlugin.show() is executed for Android foreground notification. The exception does not occur if intent-filter related to dynamic link is deleted in AndroidManifest.xml. Is there any solution?

### [Log]
E/MethodChannel#dexterous.com/flutter/local_notifications( 9476): Failed to handle method call
E/MethodChannel#dexterous.com/flutter/local_notifications( 9476): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Intent android.content.Intent.setAction(java.lang.String)' on a null object reference
E/MethodChannel#dexterous.com/flutter/local_notifications( 9476): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification(FlutterLocalNotificationsPlugin.java:217)
E/MethodChannel#dexterous.com/flutter/local_notifications( 9476): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification(FlutterLocalNotificationsPlugin.java:1140)
E/MethodChannel#dexterous.com/flutter/local_notifications( 9476): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.show(FlutterLocalNotificationsPlugin.java:1456)
E/MethodChannel#dexterous.com/flutter/local_notifications( 9476): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(FlutterLocalNotificationsPlugin.java:1293)
E/MethodChannel#dexterous.com/flutter/local_notifications( 9476): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#dexterous.com/flutter/local_notifications( 9476): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#dexterous.com/flutter/local_notifications( 9476): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#dexterous.com/flutter/local_notifications( 9476): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#dexterous.com/flutter/local_notifications( 9476): 	at android.os.Handler.handleCallback(Handler.java:873)
E/MethodChannel#dexterous.com/flutter/local_notifications( 9476): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#dexterous.com/flutter/local_notifications( 9476): 	at android.os.Looper.loop(Looper.java:214)
E/MethodChannel#dexterous.com/flutter/local_notifications( 9476): 	at android.app.ActivityThread.main(ActivityThread.java:7073)

**Comment by EloWeld** [comment]
I get this error too. Have you found the answer?

**Comment by seungku** [comment]
@EloWeld Not yet. If you find the answer, would you share me?

**Comment by seungku** [comment]
I separated intent-filter as follows:

             <intent-filter>
                 <action android:name="android.intent.action.MAIN"/>
+                <category android:name="android.intent.category.LAUNCHER"/>
+            </intent-filter>
+            <intent-filter>
                 <action android:name="android.intent.action.VIEW"/>
                 <category android:name="android.intent.category.DEFAULT"/>
                 <category android:name="android.intent.category.BROWSABLE"/>

It works for me.
