### ISSUE TITLE
ios app icon badge never disappear after clicking on the notification 

### ISSUE THREAD

**Issue by nbourdin** [MaikuB/flutter_local_notifications#1842]
**Describe the bug**
I run to example package on my ios device and ios simulator.
When i launch notification it shows a count badge on the app icon. But even if i open the notification and swipe it never remove the badge icon.

**To Reproduce**

- Run the /example package
- Launch a notification
- Remove or open the notification

**Comment by nbourdin** [comment]
Ok after upgrading to the latest version of flutter i never see the badge icon again...

**Comment by MaikuB** [comment]
This isn't a bug as plugin only exposes APIs for dealing with notifications and on Apple's platforms, there happens to be properties to specify the badge **along** with the notification. This is why I had documented this in the readme that you'll need to look into further https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#updating-application-badge
