### ISSUE TITLE
[Android] notification block doesn't appear after I swipe up the notification.

### ISSUE THREAD

**Issue by EunyoungY** [MaikuB/flutter_local_notifications#1844]
**Describe the bug**
Hello!
I'm testing on Android device. when I click a button that calls showNotification() function, I can see notifications are coming. However, When I swipe up the notification to the upper side of the screen and click the button again, it doesn't show the notification anymore. Still, I can hear the sound without the notification. The same problem happens on all the functions from the example code only in Android.

=> I found that if I change 
**'channel id', 'channel name',  'channel description'**  from   **AndroidNotificationDetails('channel id', 'channel name',
            channelDescription: 'channel description',)**  
every time time I click the button(call showNotification function), It works well. 
However, the field has to be const.

**Sample code to reproduce the problem**
  int id = 0;
  Future<void> showNotification() async {
    const AndroidNotificationDetails androidNotificationDetails =
        AndroidNotificationDetails('channel id', 'channel name',
            channelDescription: 'channel description',
            importance: Importance.max, 
            priority: Priority.high, 
            playSound: true,
            sound: RawResourceAndroidNotificationSound('see_u_again'),
            ticker: 'ticker');
    const NotificationDetails notificationDetails =
        NotificationDetails(android: androidNotificationDetails);
    await flutterLocalNotificationsPlugin.show(
        id++, 'plain title', 'plain body', notificationDetails,
        payload: 'item x');
  }

**Comment by MaikuB** [comment]
I don't understand what you mean with the wording you've used. Are you able to provide a video? Regardless of what the video shows I'll say that as this plugin's purpose is to provide access to native APIs, what you see is what you get based on the code you specified so wouldn't be a bug.

**Comment by MaikuB** [comment]
Closing due to lack of further response
