### ISSUE TITLE
The notification is not hidden

### ISSUE THREAD

**Issue by damir-dev-21** [MaikuB/flutter_local_notifications#1845]
Hi!, I have a problem, the notification is not hidden when you swipe left or right, in general, it is not hidden at all. I check important, priority and other parameters, but it didn't help with solving the problem.

**Comment by MaikuB** [comment]
I don't know what you mean. Can you provide a video and also explain why you expect it to work the way you think it should as well

**Comment by okbye123** [comment]
This will help https://www.youtube.com/watch?v=aQTvI8L-mZs

**Comment by giederloreto** [comment]
I think this can help you. 

AndroidNotificationDetails(
                    _androidChannel.id,
                    _androidChannel.name,
                    channelDescription: _androidChannel.description,
                    icon: android.smallIcon ?? '',
                    ongoing: false,
                    fullScreenIntent: false,
                ),

**Comment by MaikuB** [comment]
Closing due to lack of further response
