### ISSUE TITLE
Notification custom sound works in foreground but not in background or terminated state on ios

### ISSUE THREAD

**Issue by AbanobAtef42** [MaikuB/flutter_local_notifications#1846]
Hi Maikub
i want to thank you for your package since it helped me alot
i have an issue with playing custom sound on ios its working fine in foreground 
but if the app is receiving fcm from background **notification alert appears but with no sound either default or custom**
so please let me know what can be the cause either of plugin incorrect use **( but it works perfectly in foreground )** or ios device specific settings **( other apps on the tested ios physical device can play custom sound in background )**

if you need any other details to help me please let me know

thanks in advance

**Comment by sawan07** [comment]
I am facing the same issue. Also, when app in background, attached image does not show. I have noticed, when app is in background, the app looks for title/subtitle inside **notification** rather than in **data** of the main payload.

**Comment by ziqq** [comment]
Yes, I am facing the same issue. Any news about this?

**Comment by MaikuB** [comment]
When using local notifications like via this plugin there is no difference in the behaviour in this regard if the app is in foreground or background. You need to look into understanding how FCM works instead. I often see others come on with issues like this as they don't understand how FCM deals with notifications. This is something you will need to look into further so you're not confusing notifications from this plugin vs those from FCM as they are different things and need to be configured separately and differently
