### ISSUE TITLE
Only the last notification is shown

### ISSUE THREAD

**Issue by mkassir95** [MaikuB/flutter_local_notifications#1847]
I am sending multiple notifications, the last notification replaces the previous sent notification. Not all the notifications appear even I do not remove any notification

**Comment by albus25** [comment]
@mkassir95 How did you solve this issue?

**Comment by mkassir95** [comment]
In the show notifiation function you need to add unique ID for each notification(the first paramter of the function)
`      flutterLocalNotificationsPlugin.show(
        int.parse(messageId.substring(12,messageId.length)),
        senderName,
        messageBody,
        NotificationDetails(
          android: AndroidNotificationDetails(
            channel.id,
            channel.name,
            color: Colors.blue,
            playSound: true,
            icon: 'ic_notification',
          ),
        ),
      payload: messageBody,);
`

**Comment by albus25** [comment]
Do you have an idea, of how to set the due date of notification?
