### ISSUE TITLE
Showing notification badge on App Icon even there is no notification every time when reinstall the Application [iOS].

### ISSUE THREAD

**Issue by raviiparmar** [MaikuB/flutter_local_notifications#1849]
I have implemented the push notification in my system and it's works fine for me if I install it for the first time.

When I reinstall an app after removing it from my device, the notification badge always has a count of 1. I only experienced this problem on an iOS device.

**Comment by MaikuB** [comment]
Similar to what I mentioned in https://github.com/MaikuB/flutter_local_notifications/issues/1842#issuecomment-1368186520, this is outside the scope of the plugin and you need to manage the badge count via other means e.g. other plugins
