### ISSUE TITLE
Inconsistent notification 

### ISSUE THREAD

**Issue by Somtobro** [MaikuB/flutter_local_notifications#1851]
Hello 
Awesome package by the way before I start.
I just have some Few questions.
Why is it that the notifications are not consistent.
I've tested on Vivo and Infinix.
I'm trying to set daily 10 am notifications
But like the notifications don't always come in
Sometimes they come it at the wrong time and stuff like that..some days they don't come at all, other days they do
I followed the example code in the project just to make sure I did it perfectly and Im not doing any background task or any stuff like that
Is it the fault of the os?
What permissions are needed for basic 10 am daily notifications?
Does it need foreground permission?

**Comment by MaikuB** [comment]
Not going to be possible for me to know all the available Android devices outside but this is generally due to the OS. If you want to properly check the expected behaviour then you should run things on a stock Android device/emulator. Other manufacturers apply customisations that can relate to battery optimisations that can affect this. They have settings to disable this but you would be need to do your own research to find out what those are, assuming they even exist

**Comment by Somtobro** [comment]
No, this is different.
This is very very inconsistent.
I'm so sure that this is different and it can be better.
Every brand I've tested on is inconsistent except Samsung meanwhile
firebase notifications doesn't work that way.

**Comment by Somtobro** [comment]
Please reply to this 🙏🏾 so I don't have to open an issue; it pains me to
open issues in great packages like this.
It may be permission issues....Im using only schedule notification. Does it
need any of the permissions the example app came with in the manifest File?
Such as foreground service?
I'm asking cos I removed those permissions as my app is just doing basic
notifications.
I feel like the functions of all the notifications should have been
commented above each one of them in the manifest File.
I really do need your help...this notification package is improving traffic
to my app dramatically and I appreciate it.

**Comment by MaikuB** [comment]
The permission that is required by this plugin to schedule notifications with exact timings can be found at https://github.com/MaikuB/flutter_local_notifications/blob/4b723e750d1371206520b10a122a444c4bba7475/flutter_local_notifications/android/src/main/AndroidManifest.xml#L6. There aren't any more permissions needed. 

A few other things to note
- even if you had checked a number of devices and had made sure that everything had been configured correctly, you still may have run on non-stock Android devices. Do you even if know if those devices were running on a stock Android OS? If you want to test on an actual device then a device like a Pixel is your best bet
- you mention following the example code but don't mention if you had cloned the example app and run it. If you see the same problem on said devices then it's the same problem I mentioned earlier
- you asked if it's an OS issue to which I explained that it is essentially that. The fact that you talked about how it's inconsistent across brands except one proves my point even further
- FCM and scheduled notifications work differently so not appropriate to compare the two
- Note that even if you open another issue, I try to keep the issues board to actual issues with the plugin i.e. bugs. This means that if you open an issue without providing a link to a repo that hosts a minimal app that can consistently reproduce the issue then it will be closed. This plugin is maintained in my spare time so looking at actual bugs is my main focus. On that note, if there was an issue around consistency then I would've expected a lot more reports on this given how long this plugin has been out. All the issues I've seen have been from developers not understanding that different manufacturers will have customisations that can affect this and this was documented in the readme https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#scheduled-android-notifications

**Comment by Somtobro** [comment]
Thank you for the clarification.
I want to thank you once again for this beautiful plug in.
May God Bless your efforts 🙏🏾

**Comment by Somtobro** [comment]
After around version 3.
Adding the permissions manually were not longer part of the set up.
Does that mean the package adds the required permissions and receivers for me automatically or something because this is really confusing to be fair
I don't think the permissions are in the necessary build because I'm not getting the notifications
I just went through the version 3 it says to add them
Am I meant to?
Is it something I'm meant to know already is that why it wasn't added
🙏🏾I'd appreciate your help please I'm confused
And I think the inconsistent notifications might be my own mistake
