### ISSUE TITLE
the best way to have multiple notifications

### ISSUE THREAD

**Issue by ZuxxLo** [MaikuB/flutter_local_notifications#1852]
im working on a reminder app 
and lets say the user add 100 reminders which means 100 notifications , whats the best way to implement that ?
is it okey to have 100 notifications id's
i was thinking maybe when a notification appears it triggers the next one ? 
is there a way to know when a notification appeared?

**Comment by MaikuB** [comment]
If you need help with implementing your scenario then you'll need to reach out to community on other locations to get ideas. What I can say is that there's no way to know if a notification has appeared
