### ISSUE TITLE
Docs : custom buttons, services ?

### ISSUE THREAD

**Issue by TheCarpetMerchant** [MaikuB/flutter_local_notifications#1854]
There is nothing within the README concerning custom buttons or services (except for the mention "[Android] Start a foreground service").
After reading #17 , I'm still not even sure if those are actual functionalities provided by the plugin. If this is the case, the README is in urgent need of updating.

Thus my question : is it possible to creation a notification with Previous/Play/Pause/Next buttons as a foreground service ?

**Comment by MaikuB** [comment]
Please see https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#notification-actions. That issue you pointed to also refers to this as notification actions and the last post there had mentioned which version of the plugin started containing support for this. Example app would also show this too
