### ISSUE TITLE
Update readme to point to new timezone package

### ISSUE THREAD

**Issue by EnduringBeta** [MaikuB/flutter_local_notifications#1855]
[`flutter_native_timezone`](https://pub.dev/packages/flutter_native_timezone) seems abandoned, so @tjarvstrand created [`flutter_timezone`](https://pub.dev/packages/flutter_timezone) and applied recent PRs. I suggest the readme be updated to point to it.

Readme location: https://pub.dev/packages/flutter_local_notifications#scheduling-a-notification

I know it's a simple change and I could do it myself if I had more time. Making this issue is what I can do right now.

**Comment by MaikuB** [comment]
Thanks for the callout. Won't get to this myself until later on as I'm not well at the moment. If you happen to find time for a PR then that would be appreciated. If not then I'll add the info later on

**Comment by EnduringBeta** [comment]
@MaikuB PR up. No rush.

**Comment by MaikuB** [comment]
Thanks for the PR. Merged now so will close this
