### ISSUE TITLE
Heads-up notification never show up and version upgrade failed

### ISSUE THREAD

**Issue by tunlinnaung** [MaikuB/flutter_local_notifications#186]
Hi,

I want to show heads-up notification with this plugins.
Here is the code I used but failed to show heads-up notification.

var android = new AndroidNotificationDetails(
        'My_Id', 'My App', 'Grant this app the ability to show notifications for this app feature',
        importance: Importance.Max, priority: Priority.High);
    var ios = new IOSNotificationDetails();
    var platformChannelSpecifics = new NotificationDetails(android, ios);
    await notificationPlugIn.show(
      0,
      'body',
      'title',
      platformChannelSpecifics,
      payload: """{
        'title': '${message['data']['title']}',
        'body': '${message['data']['body']}',
        'type': '${message['data']['type']}',
        'approval_id': '${message['data']['approval_id']}'
      }""",
    );

As per your documentation, I adjusted importance and priority. But still fail.
May I know who I can show heads-up notification with your library?

FYI: When I check your code and google it, I think if it include this attribute in notification builder, then it will be fine.

.setDefaults(Notification.DEFAULT_ALL)

Full Code:

NotificationCompat.Builder mBuilder =
                    new NotificationCompat.Builder(context)
                            .setSmallIcon(R.drawable.ic_media_play)
                            .setContentTitle("My notification")
                            .setContentText("Hello World!")
                            .setDefaults(Notification.DEFAULT_ALL)
                            .setPriority(Notification.PRIORITY_HIGH);

URL:

https://stackoverflow.com/questions/33510861/how-to-show-heads-up-notifications-android/34713274

And another issue is that I upgraded the version to 0.5.2 from 0.4.2. I got compilation error and can't run.

D8: Program type already present: android.support.v4.app.INotificationSideChannel
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
> com.android.build.api.transform.TransformException: Error while generating the main dex list:
  Error while merging dex archives: 
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: android.support.v4.app.INotificationSideChannel
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 10s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Gradle task assembleDebug failed with exit code 1

Thanks,
Tun

**Comment by MaikuB** [comment]
First, I suggest you run the example app for the plugin as I'm guessing you haven't done so and have only looked at the code. See if the code there performs the way you want it too. You also should be familiarising yourself on how the Android notification APIs work. If you've changed the importance and priority but still keep using the same channel id then those changes won't apply. It'll use the priority and importance you had used when sending (see https://developer.android.com/training/notify-user/channels). What version of Android are you running on?

Also please ensure you have followed the README and looked at the changelog. There were documented breaking changes that required consumers to migrate to AndroidX with a link that had information on how to do so

**Comment by MaikuB** [comment]
I should also point out that the gradle error message included that had more information that you could've taken a look

**Comment by tunlinnaung** [comment]
Hi, I already tried with example app. And still couldn't show heads-up notification.

What version of Android are you running on?
>> Version 7.1.2
      Build number: Flyme 7.1.1.0G
      Device: MEIZU M6 Note

**Comment by MaikuB** [comment]
When you say you tried it with the example app, did you clone the repo or did you just copy and paste the code? Also do you see any notifications show in the status bar?

**Comment by MaikuB** [comment]
I've just run this on an Android 7.1.1 emulator and see the notifications fine. I don't believe that calling `setDefaults()` should be required. If you look at the basic Android tutorials then you'll see it's not called either

**Comment by tunlinnaung** [comment]
My device 'MeiZu' couldn't show up heads-up notification.. Just receive notification with sound.
But never show up heads-up notification..

https://developer.android.com/guide/topics/ui/notifiers/notifications#Heads-up

I tested with Android P device and Android O device. It was working fine and can see "heads-up notification"..

**Comment by MaikuB** [comment]
Not much else I can do to help you on this problem, perhaps there's a setting on that particular device you need to change. I assume you've tried an Android 7.x emulator?

**Comment by MaikuB** [comment]
Whilst push notifications are a bit different, a quick Google seems to show that notifications behave differently or don't even work as per [this link](https://austinmarton.wordpress.com/2017/01/08/meizu-flyme-notifications-fix/). I see a pop-up option in this screen, perhaps it needs to be switched to see the heads-up notification on those phones

**Comment by tunlinnaung** [comment]
I can do settings on those phones. But asking phone users to enable "heads-up notification" option on their phone settings manually might not be okay.

**Comment by MaikuB** [comment]
Understood but this problem would look be because of how Meizu customised Android, which is why this works fine on stock Android (e.g. on the emulator and other devices). In short, this is out of my control
