### ISSUE TITLE
ios: `getActiveNotifications` method is throwing an exception for notification that was shown by the `firebase_messaging`

### ISSUE THREAD

**Issue by Maksimka101** [MaikuB/flutter_local_notifications#1869]
Hello

I'm working with notifications that were sent by either this package or the `firebase_messaging`. When I'm trying to get active notifications, I face an exception because your package is expecting notification id in the notification request content (in the `UNNotificationRequest.content.userInfo`). That's happening because firebase is not setting notification id in this field.

My suggestion is to get notification id from the `UNNotificationRequest.identifier`. 

However in this case we will have another problem because this identifier is a String while you are using int for id. And to fix this problem we will probably need to do something with identifiers. Or we can just try to parse this string into int and maybe it will work.

This is a tricky bug but I'll try to help you to fix it. I can try to make a pr with fix by myself if we will decide what to do :)

**Comment by MaikuB** [comment]
The plugin's focus is on provide a cross-platform interface to show local notifications, in which case the lowest common denominator if you will is to use a numeric identifier as Android itself primarily uses an integer identifier. Whilst there's an option to provide a string tag, it's optional. Furthermore, a notification on Linux only has a numeric identifier. As such, it's difficult a cross-platform plugin to solve for all scenarios and this is where open-source enables developers to fork the plugin to make customisations specific to their application. Sometimes the situation may call for writing the code to access native APIs from scratch even. So to summarise, not looking to make this change in the plugin and you'll need to have custom logic specific to your scenarios. Hope that makes sense

**Comment by Maksimka101** [comment]
Thanks for answering

I think I'll write a package that will cover my scenario: load notifications with their real ids and close notification by id. And will use this package as an addition to this plugin

**Comment by MaikuB** [comment]
Ok though if so publish it then you'll need to be thorough in making sure that you comply with terms of this plugin's license as it would be more noticeable if you don't. This may involve seeking legal advice in case you're not sure on what to do

**Comment by MaikuB** [comment]
Closing since this has been answered

**Comment by nvnk3** [comment]
Why did you close this? getActiveNotifications is throwing an exception for notifications that was shown by the firebase_messaging, I cannot even get local notifications when there is push notifications combined with local notifications. It works fine when we have only local notifications.

**Comment by frankvollebregt** [comment]
Hi! I just created a PR that adds a default value of -1 for the ID. In my testing, this ensures that I can retrieve the active notifications as expected, and interact with the local notifications as desired (while disregarding or ignoring the firebase notifications).

@nvnk3 it should work with my branch, so if it gets merged you can try it (or override your dependency for now to test it for yourself)
```yaml
dependency_overrides:
  flutter_local_notifications:
    git:
      url: git@github.com:frankvollebregt/flutter_local_notifications.git
      path: flutter_local_notifications
      ref: fix-ios-active-firebase-notification
```
Once again, this doesn't allow the user to close Firebase notifications by `id` as would be possible for local notifications or Android notifications, but it does allow you to interact with these other notifications if any Firebase notifications are present.

**Comment by MaikuB** [comment]
@nvnk3 please read the previous conversations
