### ISSUE TITLE
IOS set custom icon for notification

### ISSUE THREAD

**Issue by TetrixGauss** [MaikuB/flutter_local_notifications#1870]
Hello there! I am new here and i am trying to add a specific icon to notification from assets! Every notification may have different icons! 

Like androidSettings has the largeIcon, what i need is something like that for iosSettings. I think what i need is the badgeNumber but i really dont understand how to use it!

Please help a newbie here!!!

**Comment by TetrixGauss** [comment]
never mind!!! i found it! it's all about attachments!!

**Comment by TetrixGauss** [comment]
Although i think i found it, i dont know how to retrieve the icon that i want to show to the notification! 

Can someone help me please?

**Comment by thaliachitziou99** [comment]
I have the same issue!! Can anyone help us??

**Comment by Pavel401** [comment]
@TetrixGauss @thaliachitziou99 Did you find any solutions?

**Comment by TetrixGauss** [comment]
@Pavel401 sorry to say that but I changed library due to that issue because I had to deliver the project!

**Comment by Pavel401** [comment]
> @Pavel401 sorry to say that but I changed library due to that issue because I had to deliver the project!

I found the solution.

Go to this website https://www.appicon.co/#app-icon and generate the ios icons and then put the "AppIcon.appiconset" into ios->Runner->Assets.xcassets.
Then compile the app and then it will work.

<img width="1470" alt="Screenshot 2023-01-21 at 3 21 38 PM" src="https://user-images.githubusercontent.com/47685150/213861587-1d412076-0ff5-4d5b-a6e5-4710e78a08e2.png">

**Comment by TetrixGauss** [comment]
@Pavel401 I think this is the way to just change the main icon in the notification. What I am looking for is to do something LinkedIn..I need the notification to have the application's icon and another icon which will be custom for every each one of the notifications..so it will change dynamically.

**Comment by freakmaxi** [comment]
I'm also looking for the same capability that is looked at by @TetrixGauss Anyway to do that? LinkedIn and WhatsApp are able to show the contact profile photo as the notification icon...

**Comment by MaikuB** [comment]
A reminder that documented in the readme (https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#example-app)  is there's an example app. This shows basically every feature of the plugin including attachments on iOS/macOS. There isn't an ability to provide a different icon for each notification though you can associate a different, additional image. You can check this out through said app.

General note that you should have an understanding of how the APIs work on your target platform and how these platforms work. Once you start from there then you look at what the plugin exposes as the plugin's purpose is to provide access to the native APIs. Anything outside of that is something you need to look into yourself. For example, Apple's documentation talks about how it's possible to have custom UI for a notification. Potentially this is what you can use for having a custom icon for each notification but isn't something supported by the plugin and an area that you would need to do further research on
