### ISSUE TITLE
Question: Is it possible to force the sound even if the phone is on silent mode

### ISSUE THREAD

**Issue by 0xecute** [MaikuB/flutter_local_notifications#1874]
Hello,
Thank you for this great lib, it is very useful !
I didn't find any documentation or question about this so I'm asking :)

I want the user to be able to choose to have sound of my app notification, even through the phone is on silent or vibrate mode.
On Ios and Android.
Is that something possible technically but not implemented in this package ?
Thank you in advance for your help,
Best regards,

**Comment by MaikuB** [comment]
No, silent/vibrate are "global" device settings and is outside the scope of this plugin hence the lack of documentation. This is where you should be looking to understand how each platform and their APIs work and is actually the prerequisite to using the plugin as its purpose is to expose the native APIs
