### ISSUE TITLE
How to access the full original message (title and body) in onDidReceiveNotificationResponse?

### ISSUE THREAD

**Issue by giorgio79** [MaikuB/flutter_local_notifications#1878]
Tried accessing the full message in onDidReceiveNotification but no candy. None of the properties in notificationResponse contain the original full message only the payload. Any tips please?

```
 /// Sets up Local Notifications and its Listeners
  Future<void> _localNotificationsSetup(
      BuildContext context, CashticUser currentUser) async {
    _flutterLocalNotificationsPlugin.initialize(
        const InitializationSettings(
          android: AndroidInitializationSettings(
              '@drawable/ic_notification'),
          iOS: DarwinInitializationSettings(),
        ), onDidReceiveNotificationResponse:
            (NotificationResponse notificationResponse) async {
      {
        log.d(notificationResponse.notificationResponseType);
        log.d(notificationResponse.actionId);
        log.d(notificationResponse.input);
        log.d(notificationResponse.id);
        log.d(notificationResponse.payload);
```

Also posted on stack at https://stackoverflow.com/questions/75270501/flutter-fcm-local-notifications-how-to-access-the-full-original-message

**Comment by MaikuB** [comment]
This isn't available. If there's other information you need then this is where you can use the payload to include the information specific to your use case beyond what is provided.

**Comment by giorgio79** [comment]
Thx I ended up using a global object to have access to the initial message 🙂
