### ISSUE TITLE
Notifications lost after app update on Android?

### ISSUE THREAD

**Issue by eggenstein** [MaikuB/flutter_local_notifications#188]
Is anybody else having the issue that scheduled (repeating) notifications are lost after an app update on Android?
I can't reproduce it on my dev device (Nexus4) but on my main device (S9) I did see this.

Probable repro steps:
- schedule several repeating events
- install an update of your app (without uninstalling in-between of course, release version)
- notice some or all notification don't get triggered

I have a fix for this using a MY_PACKAGE_REPLACED listener, but if nobody else experiences this problem I guess it won't make sense to add it. [(Fix here)](https://github.com/eggenstein/flutter_local_notifications/commit/f39e001015cba4433f11d13644c3eb6f22a424df)

**Comment by richie-south** [comment]
I'm having this issue to! Android and Google pixel (first one). Would be great if you could submit a pr so this might get fixed in the main package 😃

**Comment by MaikuB** [comment]
@richie-south i think the actual issue you're encountering is the one @eggenstein  referenced (#178). You can check that for more details and it should be fixed now. However per the comment I've left there and in the changelog, it will only retroactively apply to notifications that were scheduled don't use the default icon specified via the `initialize` method call

**Comment by richie-south** [comment]
@MaikuB I don't fully understand that conversation, but i for me and my users notifications only disappear when i update the app :( 

using version **0.6.1** does updating fix this? :)

**Comment by MaikuB** [comment]
Yes but note what I said above (also in the changelog)

**Comment by MaikuB** [comment]
Also even without fully understanding the conversation, you could check to see if you have error the same mentioned in that issue

**Comment by MaikuB** [comment]
@eggenstein do you feel that this issue is needed anymore? based on the conversation in the other thread, looks like the cause was around the resource ids being changed

**Comment by eggenstein** [comment]
> @eggenstein do you feel that this issue is needed anymore? based on the conversation in the other thread, looks like the cause was around the resource ids being changed

I didn't get any reports from users anyway (I'm afraid they didn't get the notifications and then forgot about the app) and I haven't seen it happening again. I am not sure if it really is connected to the other other issue or not but sounds possible. We can close it for now and reopen if someone encounters it again. Maybe then we have repro steps.
