### ISSUE TITLE
Notification that 'times out after 3 seconds' in the example does not time out.

### ISSUE THREAD

**Issue by jeevan900929** [MaikuB/flutter_local_notifications#1882]
The timeOutAfter parameter for AndroidNotificationDetails does not seem to close the notification even after the given time lapses.

**To Reproduce**
1. Run the Example App
2. Click on 'Show notification that times out after 3 seconds'
3. Wait for the notification to pop up.
4. Observe that the notification remains open, even after 3 seconds have lapsed.

**Expected behavior**
The notification should close after timing out.
![Screenshot_20230201-105033 2023-02-01 11 10 41](https://user-images.githubusercontent.com/2005277/215936434-005993d5-a054-48bb-a79b-c6c436c54f63.png)

**Sample code to reproduce the problem**
Please run the example app in this repo to reproduce this bug.

**Comment by MaikuB** [comment]
This would a limitation of your device and outside the control of this plugin as it's responsibility is to call the native APIs available. Below is a recording on my Pixel 6

https://user-images.githubusercontent.com/25263378/218751402-be531dd3-f34a-4294-970c-cf1a8e016742.mp4
