### ISSUE TITLE
payload max string length

### ISSUE THREAD

**Issue by iulian0512** [MaikuB/flutter_local_notifications#1886]
What is the maximum string length for payload parameter ? on all platforms, imho if there is a limit it should be included in the docs. i have some objects that i want to serialize in payload.

**Comment by ASE55471** [comment]
Same question on this, I am thinking to use payload parameter from this plugin or save data by my self is better solution.

**Comment by MaikuB** [comment]
As this plugin is a wrapper for native APIs, there's no documented limit as none of the API docs for each platform's native notification API mention there being a limit. With this in mind, I would assume there's none.
