### ISSUE TITLE
How to check notification is shown in notification tray or not?

### ISSUE THREAD

**Issue by pranavo72bex** [MaikuB/flutter_local_notifications#1888]
I want to check whether or not users are getting notification. Want I to send firebase log to check whether notification is show in notification tray or not. 
`flutter_local_notifications: ^9.4.0`

**Comment by MaikuB** [comment]
There's an API to get active notifications. Please try to check the API docs and example app in future before asking as this would've covered there and you doing this helps maintainers better focus on how we use our spare time to maintain plugins e.g. focus on addressing bugs, adding new features etc

**Comment by pranavo72bex** [comment]
Active notifications is only available for android. can we do similar with iOS ?

**Comment by MaikuB** [comment]
It is available for other platforms. The readme needs updating on this but you should be able to look at the API docs and check the example app that I mentioned earlier
