### ISSUE TITLE
Add ability to check if the user has allowed local push notifications?

### ISSUE THREAD

**Issue by zxl777** [MaikuB/flutter_local_notifications#189]
Sometimes we need to know if the user has allowed local push. 
Because sometimes users do not allow local push, it will not be able to use an important function of the entire app.
We hope to detect this flag and alert the user once if it finds that the push notification is not allowed.

Thanks for this plugin, good job.

**Comment by MaikuB** [comment]
Only iOS (particularly 10+) requires permissions to be enabled and I don't plan to add platform-specific methods so if you need to a check like that then I would suggest to use platform channels to add that functionality in your own app. Note that on iOS 10+, that value returned by the initialize method should indicate if permissions have been granted

**Comment by zxl777** [comment]
Thank you,
Share some pages for platform-channels,
https://flutter.dev/docs/development/platform-integration/platform-channels
https://medium.com/flutter-io/flutter-platform-channels-ce7f540a104e

**Comment by ZacharyEilers** [comment]
Hi MaikuB,

It would certainly be of massive help if you added a method to check if notifications are allowed and added a method to show the prompt to allow notifications. Even if this is platform-specific, it would be of massive help to the flutter community as a whole.

**Comment by MaikuB** [comment]
There are already other packages that can do this and one was mentioned in the above conversation

**Comment by anoop4real** [comment]
I would say its really relavant to add this feature rather than getting one more  package in... anyways great plugin

**Comment by niypoo** [comment]
I think it's important feature !!
