### ISSUE TITLE
android:exported needs to be explicitly specified for element <receiver#com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver>

### ISSUE THREAD

**Issue by vinaykharayat** [MaikuB/flutter_local_notifications#1893]
**Describe the bug**
Getting error on compiling
android:exported needs to be explicitly specified for element <receiver#com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver>

**To Reproduce**
Just install plugin with 
compileSdkVersion 33 

**Expected behavior**
I think now we need to define android:exported="true" in AndroidManifest.xml 
Since we are no longer adding <receiver> manually this is causing issue.

**Sample code to reproduce the problem**
No code required.

**Comment by vinaykharayat** [comment]
I just checked, if I am using
`flutter pub add flutter_local_notifications`
it is adding `flutter_local_notifications: ^8.2.0` instead of `flutter_local_notifications: ^13.0.0`

**Comment by MaikuB** [comment]
@vinaykharayat this isn't an issue with the plugin and you'll need to look further into understand how dependencies are resolved as this is based on what your app supports.

These issues are from using an old version of the plugin. This plugin added support for Android 13 (API level 33) a while back so you need to move to a more recent version of the plugin. I suggest staying on top of releases of your dependencies and GitHub provides a way to watch for new releases. If you can't move to a newer version of the plugin then you'll need to fork based on the version you're using and make the appropriate changes to resolve the issue yourself

**Comment by vinaykharayat** [comment]
> @vinaykharayat this isn't an issue with the plugin and you'll need to look further into understand how dependencies are resolved as this is based on what your app supports.
> 
> These issues are from using an old version of the plugin. This plugin solved this issue to add support for Android 12 (API level 31) a while back so you need to move to a more recent version of the plugin. I suggest staying on top of releases of your dependencies and GitHub provides a way to watch for new releases. If you can't move to a newer version of the plugin then you'll need to fork based on the version you're using and make the appropriate changes to resolve the issue yourself

When I am adding `flutter_local_notifications` using `flutter pub add flutter_local_notifications`, it is adding `flutter_local_notifications: ^8.2.0` instead of `flutter_local_notifications: ^13.0.0`

**Comment by MaikuB** [comment]
Read what I wrote in the first paragraph. You need to understand more about how dependencies work

**Comment by YSDC** [comment]
I think the issue is not in the plugin but in its dependencies. As for @vinaykharayat and @sanjay-023 when I add the plugin using pub add, it set the version to an old one as it finds a conflict with other dependencies. I wasn't able yet to identify which one on my side, and honestly, I don't know how to find it... But I will try to manually set it to version 13.

**Comment by YSDC** [comment]
I found out that in my case the issue is this dependency:
`  path_provider: ^2.0.12
`
if I remove it, it. includes version 13, otherwise version 8.2

**Comment by vinaykharayat** [comment]
But if I manually add 13 and run pub get, I get no conflits.

**Comment by YSDC** [comment]
me too, no conflict and it might certainly work. 

I don't know exactly how flutter determined what is the supported version. My guess (and maybe the owner of the flutter_local_notification lib can confirm) is that this library must say the minimum version they support for some libs (like path_provider). I guess after version 8.2.0 they changed to a version higher than mine (either directly or through a transitive dependency) and therefore it cannot automatically confirm that it will be supported.

**Comment by MaikuB** [comment]
Been able to reproduce this but it's not something I can answer as this seems to be more to do with how `flutter pub add` works and the pubspec of both plugins declare details that would be compatible with each other. It sounds like there may be an issue with the command given it's possible to specify the latest versions of both plugins manually and there are no version conflicts raised. This would mean they are compatible yet the docs for `flutter pub add` says the version constraint would be set to the newest compatible version but hasn't done so.  Another possibility is  that a transitive dependency is not declaring the correct details for the command to work properly either. I don't use this command myself as I've always used IDE extensions.
