### ISSUE TITLE
open_file depends on ffi conflict

### ISSUE THREAD

**Issue by CatEatFishs** [MaikuB/flutter_local_notifications#1897]
**Describe the bug**
ffi conflict;
depends on  open_file: ^3.2.1 and  depends on flutter_local_notifications: ^13.0.0
error:
Because no versions of open_file match >3.2.1 <4.0.0 and open_file 3.2.1 depends on ffi ^1.0.0, open_file ^3.2.1 requires ffi ^1.0.0.
And because flutter_local_notifications >=13.0.0 depends on flutter_local_notifications_linux ^3.0.0 which depends on ffi ^2.0.1, open_file ^3.2.1 is incompatible with flutter_local_notifications >=13.0.0.
So, because lk_capital depends on both open_file ^3.2.1 and flutter_local_notifications ^13.0.0, version solving failed.
pub get failed (1; So, because lk_capital depends on both open_file ^3.2.1 and flutter_local_notifications ^13.0.0, version solving failed.)

doctor -v
 Flutter (Channel stable, 3.3.9, on macOS 13.0.1 22A400 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.3.9 on channel stable at /Users/admin/develop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (3 months ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/admin/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/admin/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.66.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • CLT AL01 (mobile)  • AKC7N18408004453                     • android-arm64  • Android 10 (API 29)
    • iPhone 14 (mobile) • 8082E465-AFED-44DE-9091-08BECE866B54 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-1 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by CatEatFishs** [comment]
this error on APP

**Comment by MaikuB** [comment]
Please take a closer look at your dependencies and error messages as this isn't an issue with this plugin and this may be something you need to look at putting a fix in yourself. This plugin requires a more recent version of ffi but one of your dependencies (open_file) appears to not be maintained and depend on an outdated version of ffi
