### ISSUE TITLE
AndroidX incompatibilities issue

### ISSUE THREAD

**Issue by maheshbhattaraai** [MaikuB/flutter_local_notifications#190]
> After installing flutter 0.5.2 version flutter application debug shows androidx incompatible issue.

**Comment by MaikuB** [comment]
Please ensure you have migrated your app to AndroidX as mentioned in the readme and change log if you haven't done so already

**Comment by maheshbhattaraai** [comment]
After migration scheduling not working.

**Comment by MaikuB** [comment]
please provide more details (e.g. steps to reproduce) and at ideally a sample to reproduce the problem. there's a sample app for this plugin that you can find in this repo and scheduling works fine. perhaps you haven't completed all of the migration steps e.g. you haven't updated the gradle.properties file as mentioned in the guide

**Comment by maheshbhattaraai** [comment]
Works perfect right now.
Anyway thank you
