### ISSUE TITLE
How dimissible the startForegroundService()

### ISSUE THREAD

**Issue by lcarielo** [MaikuB/flutter_local_notifications#1902]
On a Xiaomi 10a with Android 11 it does not allow me to dismiss the startForegroundService() notification. How do I dismiss the notification?

I am implementing startForegroundService() because on Android 11+ devices, scheduled notifications are not received when the app is closed.

My purpose is to receive scheduled notifications when the app is closed.

Greetings.

**My implemented code:**

<img width="1230" alt="image" src="https://user-images.githubusercontent.com/119357145/219817664-63046045-3f6a-4b0b-99f2-dcc200245813.png">

**Comment by MaikuB** [comment]
The behaviour you're seeing is the expected behaviour and is documented in the official Android docs. The exception as according to their docs is on Android 13+. See https://developer.android.com/guide/components/foreground-services. Closing as this isn't an issue with the plugin
