### ISSUE TITLE
Android 12+: splash screen icon not shown

### ISSUE THREAD

**Issue by Stoisss** [MaikuB/flutter_local_notifications#1903]
When the app is opened from notification on Android 12+, no splash screen icon is shown. That is caused by a behavior which the google team described as expected. More information about this 'issue' could be found [here](https://stackoverflow.com/questions/73919563/android-12-splash-screen-icon-not-showing-from-notification).

[Android team suggested solution](https://issuetracker.google.com/issues/205021357#comment14) that creates bundle with option and passes it to the startActivity method.

So I will be very thankful if you can add the Bundle the specified values in it and add it to all of the PendingIntent.getActivity calls and create a new release.

https://github.com/MaikuB/flutter_local_notifications/blob/f6d3fe1cd7b0da7d15cbc1f8aa462e0cae927a6e/flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java#L251

**Comment by MaikuB** [comment]
Given this is mentioned to be the expected behaviour what is being proposed here is not the norm that it's not suitable to force this in everyone and should be opted in. This won't be something I'll be looking to do myself so given you are interested in this, please look into submitting a PR

**Comment by okbye123** [comment]
This will help https://www.youtube.com/watch?v=aQTvI8L-mZs
