### ISSUE TITLE
Scheduled notifications are not working in release mode ?

### ISSUE THREAD

**Issue by harryandroiddev** [MaikuB/flutter_local_notifications#1907]
Scheduled notifications are working in debug mode but in release mode on android it is not working .This is only happening in my redmi note 8 android device , while in samsung device it is working fine .

It is showing very  wierd behaviour:

1. when the app the is foreground , it shows notification .
2. when the app is background , it is also working fine .
3. but when the app is terminated it does not show the notification if the screen is unlocked but when i lock the screen it automatically shows the notification.

**Comment by MaikuB** [comment]
This is outside the control of the plugin. Please read https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#scheduled-android-notifications
