### ISSUE TITLE
[iOS] flutter_local_notification unable to display Notification when App is terminated and Background App Refresh is disabled

### ISSUE THREAD

**Issue by shungz89** [MaikuB/flutter_local_notifications#1908]
![image](https://user-images.githubusercontent.com/29431101/222045476-1988209e-b045-4ac7-9c00-d94d715d0db3.png)

I was testing out Firebase Cloud Message, whenever I receive a notification from FCM, I would like to trigger notification bar using flutter local notification. However I notice, when iOS Background App Refresh is set to disabled. I can't trigger .show() in flutter_local_notification

iOS Version is 16.3.1

**Comment by MaikuB** [comment]
If you believe this is that setting affects specifically this plugin then please provide a link to a repository hosting a minimal app using this only this plugin. The reason I'm saying that it should be only using this plugin to ensure you've actually isolated the issue to be relevant to this plugin when what you've mentioned is you depend on FCM as the main dependency and what you've described is more relevant to FCM than this plugin

**Comment by MaikuB** [comment]
Closing to due lack of further response with requested info/evidence
