### ISSUE TITLE
Pub.dev Link Send you to 404

### ISSUE THREAD

**Issue by acuba001** [MaikuB/flutter_local_notifications#1909]
**Describe the bug**

**To Reproduce**

1. Go to https://pub.dev/packages/flutter_local_notifications#custom-notification-icons-and-sounds. This should send you to the pub.dev page under "Android Setup"->"Custom notification icons and sounds".
2. Click on [Icon design status bar](https://android-doc.github.io/guide/practices/ui_guidelines/icon_design_status_bar.html) in the bullet point list.
4. See error 404 page

**Expected behavior**
The link should send you to a page that describes how Android icon design should be done.

**Sample code to reproduce the problem**
N/A

**Comment by MaikuB** [comment]
Thanks for raising this. As this link is an external one, I can't control its availability etc. If you find another official link then please submit a PR but AFAIK, there's no other **official** resource that can replace this that I'll likely have to remove this link. The only thing I can think of adding that is closest to what was there is to direct developers to using Image Asset Studio for their notification icon
