### ISSUE TITLE
[iOS] NotificationAppLaunchDetails payload is always Null when Notification is called after App is terminated for the first time

### ISSUE THREAD

**Issue by shungz89** [MaikuB/flutter_local_notifications#1910]
This bug still exist

NotificationAppLaunchDetails payload is always Null #1546

It is still not working on iOS.

Whenever user trigger closes the App by swiping up, and then later on the flutter local notification wakes up the app for the first time, the event.notificationResponse will be null

`flutterLocalNotificationsPlugin
      .getNotificationAppLaunchDetails()
      .asStream()
      .listen((event) async {
    if (event.didNotificationLaunchApp) {
      Future.delayed(Duration(seconds: 1), () {
        _onNotificationBarClicked(event.notificationResponse);
      });
    } else {
      if (event.notificationResponse != null) {
        //do something.
        //but it will never trigger here
      }
    }
  });`

**Comment by MaikuB** [comment]
Have you used the example app to validate this claim that there is an issue? If not, please do so. I've tried this with the example app and didn't run into this issue. If the issue actually exists then I'd expect a lot more reports on this too as handling what should happen when a notification launches an app is a standard use case.

**Comment by MaikuB** [comment]
Closing due to lack of response with evidence on this issue

**Comment by harshmittal2810** [comment]
I am also facing same issue, while selecting notification from killed state or while app foreground. I am not getting payload only app navigating to main page and if app is open it again opens main page.

**Comment by ilyasdirin** [comment]
Same issue in version ^15.1.0+1
