### ISSUE TITLE
Show Daily Notification which starting from (x Date)

### ISSUE THREAD

**Issue by nawaf11** [MaikuB/flutter_local_notifications#1913]
First thanks for this Handy library.

I want to create Daily Notification that starting from x Date,

In the example of this package:.

`Future<void> _scheduleDailyTenAMNotification() async {
    await flutterLocalNotificationsPlugin.zonedSchedule(
        0,
        'daily scheduled notification title',
        'daily scheduled notification body',
        _nextInstanceOfTenAM(),
        const NotificationDetails(
          android: AndroidNotificationDetails('daily notification channel id',
              'daily notification channel name',
              channelDescription: 'daily notification description'),
        ),
        androidAllowWhileIdle: true,
        uiLocalNotificationDateInterpretation:
            UILocalNotificationDateInterpretation.absoluteTime,
        matchDateTimeComponents: DateTimeComponents.time);
  }
`

This code is Showing the Notification Daily at 10 AM..

I want samething but (Making the notification start showing after x Days..)

**Comment by MaikuB** [comment]
This isn't possible and the notification APIs of the native platforms don't support this, you can only specify it be recurring by matching certain components of the date/time like the example app showed

**Comment by phamquoctrongnta** [comment]
@MaikuB 
I see `DateTimeComponents.dayOfWeekAndTime` and `DateTimeComponents.dayOfMonthAndTime` start displaying after the specified date but `DateTimeComponents.time` does not, why?
Sorry for my bad English.
