### ISSUE TITLE
flutter_local_notifications latest version can't be used with path_provider package

### ISSUE THREAD

**Issue by EDeLeon9** [MaikuB/flutter_local_notifications#1925]
I'm using path_provider package, but I can't get the latest version of flutter_local_notifications using **flutter pub add** (I just get **^8.2.0** version) if I have path_provider.  If I remove path_provider package I do get the latest version (currently **13.0.0**).

Currently I have to use instead path_provider_android, path_provider_foundation, path_provider_windows and path_provider_linux packages individually in order to get the application documents directory path per platform.

I posted that issue in path_provider package and they say it looks like a flutter_local_notifications issue: [](https://github.com/flutter/flutter/issues/122577)

**Comment by MaikuB** [comment]
They are compatible with each other. If you specified the versions yourself then it'll work fine. For whatever reason, the `flutter pub add` command cannot add the latest version but others (e.g. see https://github.com/MaikuB/flutter_local_notifications/issues/1893#issuecomment-1471485739) including myself have found that manually specifying the version works fine
