### ISSUE TITLE
NullPointerException on long android.app.Notification.when

### ISSUE THREAD

**Issue by Fasust** [MaikuB/flutter_local_notifications#1929]
**Describe the bug**
I've noticed an exception coming up through our android crash monitoring. We are running plugin version `12.0.4` with flutter `3.3.10`.
The issue seems to happen primarily while the app is in the background state. This seems to happen on all versions of android & with no specific device models being effected more than others.

````
Exception java.lang.RuntimeException: Unable to start receiver com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver: java.lang.NullPointerException: Attempt to write to field 'long android.app.Notification.when' on a null object reference in method 'void com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver.onReceive(android.content.Context, android.content.Intent)'
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:4561)
  at android.app.ActivityThread.-$$Nest$mhandleReceiver
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2308)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:240)
  at android.os.Looper.loop (Looper.java:351)
  at android.app.ActivityThread.main (ActivityThread.java:8364)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:584)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1013)
Caused by java.lang.NullPointerException: Attempt to write to field 'long android.app.Notification.when' on a null object reference in method 'void com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver.onReceive(android.content.Context, android.content.Intent)'
  at com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver.onReceive (ScheduledNotificationReceiver.java:35)
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:4545)
````

**Comment by MaikuB** [comment]
You would need to provide a link to minimal repo that can reproduce the issue. A stack trace like this doesn't provide sufficient information to look into the problem and looks more strange given the trace would indicate it's gone through a pathway in the code that was for apps that would have used old versions of the plugin and should've handled those scenarios fine. On that note, what's the earliest version of the plugin that your app has used? An important thing to check if the [release build configuration](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#release-build-configuration) in the readme has been done in full for your app as well

**Comment by Fasust** [comment]
Yes, I am referring to the release build configuration.
Thank you for the pointer. I'll change the keys for the shared prefs in our fork

**Comment by okbye123** [comment]
This will help https://www.youtube.com/watch?v=aQTvI8L-mZs

**Comment by MaikuB** [comment]
@Fasust out of interest have you been able to reproduce this issue yourself? I would imagine it should've shown up from testing a release build prior to release and reason I'm asking is I'm curious what the data looks like in your scenario. This might help provide a way for the plugin to catch this and log a better error message to guide developers to check their release build setup again

**Comment by Fasust** [comment]
@MaikuB I was not able to reproduce the issue myself. I was able to resolve the issue however by adding a null check on the android native level & discarding any broken notifications: 
https://github.com/brancedev/flutter_local_notifications/commit/40b277a2dcffeeb32ad3c71755542fcd042cb084

Would this be useful for the plugin in general?

**Comment by MaikuB** [comment]
As the issue may be a recurring one with a scheduled notification not being discarded and a device being rebooted that can cause this issue to happen again, I would be inclined to say yes but at the same time there should be a way for developers to know that there's an issue. Perhaps following what has recently been done to deal with when exact alarm permissions being revoked can be done here where an error log message can be sent like here https://github.com/MaikuB/flutter_local_notifications/blob/ac69878576fd7dd3133064db58aa61349614491e/flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java#L212?
