### ISSUE TITLE
Adding  flutter_local_notifications: ^0.6.0 in pubspec.yaml produces error

### ISSUE THREAD

**Issue by gitboss** [MaikuB/flutter_local_notifications#193]
I added flutter_local_notifications: ^0.6.0 in pubspec.yaml of an existing project and hit F5 to run the code in emulator. It produces the following error - 

============
Launching lib\main.dart on Android SDK built for x86 in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  Output:  D:\fluttercode\flutter-bloc-library-tutorial-master\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:86: error: resource android:attr/fontVariationSettings not found.
  D:\fluttercode\flutter-bloc-library-tutorial-master\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:87: error: resource android:attr/ttcIndex not found.
  error: failed linking references.

  Command: C:\Users\Admin\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\0c2f9118388f1515cc6007d6a4a14204\aapt2-3.2.1-4818971-windows\aapt2.exe link -I\
          C:\Users\Admin\AppData\Local\Android\sdk\platforms\android-27\android.jar\
          --manifest\
          D:\fluttercode\flutter-bloc-library-tutorial-master\build\app\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml\
          -o\
          D:\fluttercode\flutter-bloc-library-tutorial-master\build\app\intermediates\processed_res\debug\processDebugResources\out\resources-debug.ap_\
          -R\
          @D:\fluttercode\flutter-bloc-library-tutorial-master\build\app\intermediates\incremental\processDebugResources\resources-list-for-resources-debug.ap_.txt\
          --auto-add-overlay\
          --java\
          D:\fluttercode\flutter-bloc-library-tutorial-master\build\app\generated\not_namespaced_r_class_sources\debug\processDebugResources\r\
          --custom-package\
          com.example.bloclibrarytut\
          -0\
          apk\
          --output-text-symbols\
          D:\fluttercode\flutter-bloc-library-tutorial-master\build\app\intermediates\symbols\debug\R.txt\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0
  Output:  C:\Users\Admin\.gradle\caches\transforms-1\files-1.1\core-1.0.1.aar\5bb598a62c4dc59ebc0727ba60eec22a\res\values\values.xml:89:5-125:25: AAPT: error: resource android:attr/fontVariationSettings not found.

  C:\Users\Admin\.gradle\caches\transforms-1\files-1.1\core-1.0.1.aar\5bb598a62c4dc59ebc0727ba60eec22a\res\values\values.xml:89:5-125:25: AAPT: error: resource android:attr/ttcIndex not found.

  error: failed linking references.
  Command: C:\Users\Admin\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\0c2f9118388f1515cc6007d6a4a14204\aapt2-3.2.1-4818971-windows\aapt2.exe link -I\
          C:\Users\Admin\AppData\Local\Android\sdk\platforms\android-27\android.jar\
          --manifest\
          D:\fluttercode\flutter-bloc-library-tutorial-master\build\app\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml\
          -o\
          D:\fluttercode\flutter-bloc-library-tutorial-master\build\app\intermediates\processed_res\debug\processDebugResources\out\resources-debug.ap_\
          -R\
          @D:\fluttercode\flutter-bloc-library-tutorial-master\build\app\intermediates\incremental\processDebugResources\resources-list-for-resources-debug.ap_.txt\
          --auto-add-overlay\
          --java\
          D:\fluttercode\flutter-bloc-library-tutorial-master\build\app\generated\not_namespaced_r_class_sources\debug\processDebugResources\r\
          --custom-package\
          com.example.bloclibrarytut\
          -0\
          apk\
          --output-text-symbols\
          D:\fluttercode\flutter-bloc-library-tutorial-master\build\app\intermediates\symbols\debug\R.txt\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

[error.txt](https://github.com/MaikuB/flutter_local_notifications/files/3025950/error.txt)

**Comment by MaikuB** [comment]
If you at the error you'll see there's more information for you to look at

> The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.

**Comment by gitboss** [comment]
Thanks for your answer, I appreciate your time. I solved the error by recreating the project in a new folder and under new name. So, I'm not sure but the error was probably due to some older incompatible dependencies. I had tried to update the dependencies but it too did not work, so I just recreated the project and it worked. Your package is awesome and works like a charm,

**Comment by ened** [comment]
@gitboss please close the issue if you have resolved it
