### ISSUE TITLE
zonedSchedule and GC freed 0% free

### ISSUE THREAD

**Issue by Geparder** [MaikuB/flutter_local_notifications#1931]
Each call to zonedSchedule produces the following message in the console.

`Background young concurrent copying GC freed 1092821(22MB) AllocSpace objects, 0(0B) LOS objects, 0% free, 179MB/179MB, paused 6.289ms,14us total 22.824ms`

As long as I remove the code from the zonedSchedule, the message stops appearing.
Package version 13.0.0

**Comment by MaikuB** [comment]
What is the issue you're trying to report and what is the expectation you have? The message isn't one generated by the plugin so if the OS decides to log messages then that is outside of the control of this plugin. Furthermore, doesn't sound like there's an issue affecting functionality either

**Comment by MaikuB** [comment]
Closing due to lack of response to answer questions raised in previous message
