### ISSUE TITLE
Possible option for improved Xiaomi support

### ISSUE THREAD

**Issue by guyluz11** [MaikuB/flutter_local_notifications#1934]
I found this package [FlutterXiaoMiPushPlugin](https://pub.dev/packages/xiao_mi_push_plugin) which supposed to enable xiaomi push notification support.

Right out of the bats (even though I don't know Chinese XD) I saw that they are importing more Android permissions that are specific to xiaomi

```
    <permission android:name="你的包名.permission.MIPUSH_RECEIVE"
                android:protectionLevel="signature"/>
    <uses-permission android:name="你的包名.permission.MIPUSH_RECEIVE"/>

```

So first of all we can (maybe) get an idea off how to do push notifications to xiaomi devices by looking at the code of the package.

Maybe by adding the permissions they have wrote our current package can support wider range of xiaomi devices.

Edit: He saw my issue about translating the readme to English and it's now in English 👍.

Same for Hawaii

[hua_wei_push_plugin](https://pub.dev/packages/hua_wei_push_plugin)

**Comment by okbye123** [comment]
This will help https://www.youtube.com/watch?v=aQTvI8L-mZs

**Comment by MaikuB** [comment]
@guyluz11 good point by suggest ignoring that poster as this appears to be an effort by the poster promote their in YouTube video that isn't even relevant as they've posted on multiple issues with the same link

As for what you posted about, that's to do with Xiaomi's push notification service. Push notifications aren't the same as local notifications. This is an OS thing that has been a long standing restriction that from what I've seen has no code solution around getting permissions etc. If you google say, "Xiaomi alarm manager", you'll find a lot of comments on this e.g. https://xiaomi.eu/community/threads/alarmmanager-_wakeup-problem.21430/ and https://issuetracker.google.com/issues/113676489

**Comment by guyluz11** [comment]
I meant local notification, anyway this package will not help us with that 

Will close now
