### ISSUE TITLE
an enum switch case label must be the unqualified name of an enumeration constant

### ISSUE THREAD

**Issue by arsios** [MaikuB/flutter_local_notifications#1935]
/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java:534: error: an enum switch case label must be the unqualified name of an enumeration constant
      case RepeatInterval.EveryMinute:
                         ^

/Users/withashish/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-9.5.3+1/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java:534: error: an enum switch case label must be the unqualified name of an enumeration constant
      case RepeatInterval.EveryMinute:
                         ^
/Users/withashish/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-9.5.3+1/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java:537: error: an enum switch case label must be the unqualified name of an enumeration constant
      case RepeatInterval.Hourly:
                         ^
/Users/withashish/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-9.5.3+1/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java:540: error: an enum switch case label must be the unqualified name of an enumeration constant
      case RepeatInterval.Daily:
                         ^
/Users/withashish/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-9.5.3+1/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java:543: error: an enum switch case label must be the unqualified name of an enumeration constant
      case RepeatInterval.Weekly:
                         ^
/Users/withashish/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-9.5.3+1/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java:749: error: an enum switch case label must be the unqualified name of an enumeration constant
      case NotificationStyle.BigPicture:
                            ^
/Users/withashish/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-9.5.3+1/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java:752: error: an enum switch case label must be the unqualified name of an enumeration constant
      case NotificationStyle.BigText:
                            ^
/Users/withashish/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-9.5.3+1/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java:755: error: an enum switch case label must be the unqualified name of an enumeration constant
      case NotificationStyle.Inbox:
                            ^
/Users/withashish/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-9.5.3+1/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java:758: error: an enum switch case label must be the unqualified name of an enumeration constant
      case NotificationStyle.Messaging:
                            ^
/Users/withashish/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-9.5.3+1/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java:761: error: an enum switch case label must be the unqualified name of an enumeration constant
      case NotificationStyle.Media:
                            ^
9 errors

**Comment by bartekpacia** [comment]
Try doing `dart pub cache clean` and then `flutter pub get`. I sometimes get strange errors, similar to yours, and cleaning the pub cache always helps in these cases.

**Comment by MaikuB** [comment]
Thanks @bartekpacia for answering. Agreed should be more an issue with your development environment and would suggest doing the same and check your Android SDK setup. Don't recall seeing others report this and would be more of a widespread issue if it's a legitimate problem. Can also see that when you go to the tagged release for version 9.5.3+1 that it built successfully  https://github.com/MaikuB/flutter_local_notifications/tree/flutter_local_notifications-v9.5.3+1
