### ISSUE TITLE
Programmatically delete Schedule Notifications from Notification Centre

### ISSUE THREAD

**Issue by burhanaksendir** [MaikuB/flutter_local_notifications#1936]
How can we pragmatically remove some pending scheduled notifications sent for my app from notification centre.

**Comment by MaikuB** [comment]
Isn't this covered by the [`cancel()` method](https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/FlutterLocalNotificationsPlugin/cancel.html) or is there something else you're referring to? Note you can check the example app to see how the plugin's APIs work as well

**Comment by burhanaksendir** [comment]
@MaikuB  Thanks for your help.  I am getting this error on real device with iOS 16.3. 

**type 'Null' is not a subtype of type 'int'**

```
 final List<ActiveNotification>? activeNotifications =
          await flutterLocalNotificationsPlugin.getActiveNotifications();

      if (activeNotifications.isNotEmpty) {
        for (ActiveNotification notification in activeNotifications) {
          if (notification.id == 919123) {
            await flutterLocalNotificationsPlugin.cancel(notification.id);
          }
        }
      }
      
```

**Comment by burhanaksendir** [comment]
I deleted the app and reinstalled it. Problem solved.
