### ISSUE TITLE
Notifications not working on iOS

### ISSUE THREAD

**Issue by giovanni256** [MaikuB/flutter_local_notifications#1937]
**Describe the bug**
Notifications are working properly on Android but not working at all on iOS (tried on emulator).
I have the code in the main page and the notification doesn't show.
Please note that I already made changes on AppDelegate.swift file.

**Sample code to reproduce the problem**
```
FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin = FlutterLocalNotificationsPlugin();

flutterLocalNotificationsPlugin
        .resolvePlatformSpecificImplementation<
            AndroidFlutterLocalNotificationsPlugin>()!
        .requestPermission();

    const AndroidInitializationSettings initializationSettingsAndroid = AndroidInitializationSettings('icon');

    final DarwinInitializationSettings initializationSettingsDarwin =
        DarwinInitializationSettings(
            requestSoundPermission: true,
            requestBadgePermission: true,
            requestAlertPermission: true,
            onDidReceiveLocalNotification: onDidReceiveLocalNotification);

    final InitializationSettings initializationSettings =
        InitializationSettings(
            android: initializationSettingsAndroid,
            iOS: initializationSettingsDarwin,
            macOS: initializationSettingsDarwin);

    await flutterLocalNotificationsPlugin.initialize(initializationSettings, onDidReceiveNotificationResponse:  onDidReceiveNotificationResponse);

    const AndroidNotificationDetails androidNotificationDetails =
        AndroidNotificationDetails('can1', 'Channel 1',
            channelDescription: "Desc here",
            importance: Importance.max,
            priority: Priority.high,
            ticker: 'ticker');

    const NotificationDetails notificationDetails =
        NotificationDetails(android: androidNotificationDetails);

    await flutterLocalNotificationsPlugin.show(
        0, 'Notification is working!', 'Hello world', notificationDetails, payload: 'item x');

```

**Comment by adar2378** [comment]
Push notifications do not work on iOS simulator. You need to test it on physical device

**Comment by SagarKeshurtechno** [comment]
did you added APN in firebase ?

**Comment by bartekpacia** [comment]
Notifications have worked on iOS Simulator for a long time, and recently [support for push notifications](https://stackoverflow.com/questions/1080556/how-can-i-test-apple-push-notification-service-without-an-iphone/73829063#73829063) has been added as well.

**Comment by MaikuB** [comment]
You're going to need to check what you're missing as notifications on iOS have worked for a long time and an issue like this would have more widespread reports. It should be mentioned in the issue template that you can cross reference with the example app and you should also be able to use the same app to see if you can reproduce the problem

**Comment by empathictech** [comment]
Any update on this @giovanni256 ? I am having the same issue. I had cross platform notifications working on an earlier build (I believe 9) following a bdestech video, but when I updated to 13 iOS hasn't been working. I have always been using the same hardware device and Apple Developer account. I've tried rebuilding everything (repo, Flutter project, Firebase project, etc) from scratch and none of it has worked. I know I'm just missing one small thing but I don't know what... it's like a remembrall. Here's my [code](https://github.com/Empathetech-LLC/empathetech_flutter_ui/blob/main/lib/src/notifications.dart) (it's very similar to what's posted)

**Comment by giovanni256** [comment]
> Any update on this @giovanni256 ? I am having the same issue. I had cross platform notifications working on an earlier build (I believe 9) following a bdestech video, but when I updated to 13 iOS hasn't been working. I have always been using the same hardware device and Apple Developer account. I've tried rebuilding everything (repo, Flutter project, Firebase project, etc) from scratch and none of it has worked. I know I'm just missing one small thing but I don't know what... it's like a remembrall. Here's my [code](https://github.com/Empathetech-LLC/empathetech_flutter_ui/blob/main/lib/src/notifications.dart) (it's very similar to what's posted)

Hi there!
Sorry for the delay, I was waiting for a test.

Notifications are working a real device so I'm gonna closing the issue.
