### ISSUE TITLE
NSUserNotificationCenter Deprecation Warnings Despite Minimum macOS Target

### ISSUE THREAD

**Issue by cliftonlabrum** [MaikuB/flutter_local_notifications#1939]
Thanks for an awesome package! I have a minor bug to report.

The README for this package [states](https://pub.dev/packages/flutter_local_notifications#-supported-platforms):
> macOS 10.11+. On macOS versions older than 10.14, the plugin will use the [NSUserNotification APIs](https://developer.apple.com/documentation/foundation/nsusernotification). The [UserNotification APIs](https://developer.apple.com/documentation/usernotifications) (aka the User Notifications Framework) is used on macOS 10.14 or newer. Notification actions only work on macOS 10.14 or newer

I have a Flutter app for macOS with the minimum deployment set to `macOS 11.0`. Likewise my `Podfile` is also set for the same version:
```
//Podfile
platform :osx, '11.0'
```
Nevertheless, every macOS build of my app shows deprecation warnings:
```
1 warning generated.
#import "Headers/flutter_local_notifications-Swift.h"
        ^
.../build/macos/Build/Products/Debug/flutter_local_notifications/flutter_local_notifications.framework/Headers/flutter_local_notifications-Swift.h:270:33: warning: 'NSUserNotificationCenter' is deprecated: first deprecated in macOS 11.0 - All NSUserNotifications API should be replaced with UserNotifications.frameworks API
- (void)userNotificationCenter:(NSUserNotificationCenter * _Nonnull)center didActivateNotification:(NSUserNotification * _Nonnull)notification;
                                ^
@interface NSUserNotificationCenter : NSObject {
           ^
#import "Headers/flutter_local_notifications-Swift.h"
        ^
```
```
.../build/macos/Build/Products/Debug/flutter_local_notifications/flutter_local_notifications.framework/Headers/flutter_local_notifications-Swift.h:270:101: warning: 'NSUserNotification' is deprecated: first deprecated in macOS 11.0 - All NSUserNotifications API should be replaced with UserNotifications.frameworks API
- (void)userNotificationCenter:(NSUserNotificationCenter * _Nonnull)center didActivateNotification:(NSUserNotification * _Nonnull)notification;
                                                                                          ^
@interface NSUserNotification : NSObject <NSCopying> {
           ^
#import "Headers/flutter_local_notifications-Swift.h"
        ^
```
```
.../build/macos/Build/Products/Debug/flutter_local_notifications/flutter_local_notifications.framework/Headers/flutter_local_notifications-Swift.h:271:33: warning: 'NSUserNotificationCenter' is deprecated: first deprecated in macOS 11.0 - All NSUserNotifications API should be replaced with UserNotifications.frameworks API
- (BOOL)userNotificationCenter:(NSUserNotificationCenter * _Nonnull)center shouldPresentNotification:(NSUserNotification * _Nonnull)notification SWIFT_WARN_UNUSED_RESULT;
                                ^
@interface NSUserNotificationCenter : NSObject {
           ^
#import "Headers/flutter_local_notifications-Swift.h"
        ^
```
```
.../build/macos/Build/Products/Debug/flutter_local_notifications/flutter_local_notifications.framework/Headers/flutter_local_notifications-Swift.h:271:103: warning: 'NSUserNotification' is deprecated: first deprecated in macOS 11.0 - All NSUserNotifications API should be replaced with UserNotifications.frameworks API
- (BOOL)userNotificationCenter:(NSUserNotificationCenter * _Nonnull)center shouldPresentNotification:(NSUserNotification * _Nonnull)notification SWIFT_WARN_UNUSED_RESULT;
```
My assumption is that the `NSUserNotificationCenter` would get skipped entirely for those of us with a more modern build target, but perhaps its mere presence in the `flutter_local_notifications` codebase triggers the warnings.

In any case, it would be great to not get these. 😊 Thanks again for your stellar work on this package!

**Comment by bartekpacia** [comment]
I think you're getting these warnings because [the plugin has a minimum macOS version set to 10.11](https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/macos/flutter_local_notifications.podspec#L19). So the code using the deprecated APIs is compiled anyway (because it has no `#ifdef`s, I guess).

**Comment by MaikuB** [comment]
Yes the warnings are there as old APIs are used for the lower macOS versions and they aren't used on higher versions. This has been raised before so will be closing as a duplicate https://github.com/MaikuB/flutter_local_notifications/issues/1858. Note that in there I've asked for community to help submit a PR to resolve this. Be great if you could help do so
