### ISSUE TITLE
i have a problem with zonedSchedule when app is closed

### ISSUE THREAD

**Issue by mahdiqdi** [MaikuB/flutter_local_notifications#1944]
i implemented flutter local notification and i receive notification when app is running in foreground or minimized but when app is closed or terminated no notification receive
please help me with my problem.how should i solve it?
i know it is possible to use firebase messaging but i need this feature locally without firebase messaging.
my phone is xiaomi

**Comment by MaikuB** [comment]
Please read https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#scheduled-android-notifications
