### ISSUE TITLE
How can I show a media notification ?

### ISSUE THREAD

**Issue by TheCarpetMerchant** [MaikuB/flutter_local_notifications#1945]
How can I show a notification that looks like this (not exactly, I just need the Play/Pause/Navigation buttons) ?
Notification actions do not appear when they have no text.
![image](https://user-images.githubusercontent.com/5080204/228277897-a2933da4-d307-4b79-9a1a-f06ddeb263ba.png)

**Comment by MaikuB** [comment]
Not something that can be done via the plugin. This is something you'd need to do research on to understand what's available by the native APIs as that's a prerequisite to working on your app, let alone using this plugin. It'll likely require your own custom solution or you can see if anyone else in the Flutter community has built a package to support this. It is my understanding that Android has [this](https://developer.android.com/guide/topics/media/media-controls) and is something you'd need to look into further, especially if you're going to do something custom
