### ISSUE TITLE
How do I create an Android notification with runtime actions?

### ISSUE THREAD

**Issue by moonlitknight** [MaikuB/flutter_local_notifications#1946]
I'm trying to create an Android notification with two actions. 
The actions are only available at runtime as they are fetched from a server API.

The actions param (https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/AndroidNotificationDetails/actions.html ) is defined as final so I can only pass a constant array to it.

**Comment by MaikuB** [comment]
The use of `final` there is meant to represent the list is immutable in the context of this plugin, more specifically as an immutable property of [this class](https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/AndroidNotificationDetails/AndroidNotificationDetails.html). In other words, what you've stated is a misinterpretation and this doesn't stop you from building a list of actions at runtime nor does it doesn't require a constant array.
