### ISSUE TITLE
Can't build apk in release mode after adding this package

### ISSUE THREAD

**Issue by zeljko94** [MaikuB/flutter_local_notifications#1948]
When i try to build my app with this package using: flutter build apk --release

I get the following error:

 Building with sound null safety 

Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':flutter_local_notifications:debugUnitTestRuntimeClasspath'.
   > Failed to transform bcprov-jdk15on-1.68.jar (org.bouncycastle:bcprov-jdk15on:1.68) to match attributes {artifactType=processed-jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for JetifyTransform: C:\Users\zeljk\.gradle\caches\modules-2\files-2.1\org.bouncycastle\bcprov-jdk15on\1.68\46a080368d38b428d237a59458f9bc915222894d\bcprov-jdk15on-1.68.jar.
         > Failed to transform 'C:\Users\zeljk\.gradle\caches\modules-2\files-2.1\org.bouncycastle\bcprov-jdk15on\1.68\46a080368d38b428d237a59458f9bc915222894d\bcprov-jdk15on-1.68.jar' using Jetifier. Reason: IllegalArgumentException, message: Unsupported class file major version 59. (Run with --stacktrace for more details.)
           Suggestions:
            - Check out existing issues at https://issuetracker.google.com/issues?q=componentid:460323&s=modified_time:desc, it's possible that this issue has already been filed there.
            - If this issue has not been filed, please report it at https://issuetracker.google.com/issues/new?component=460323 (run with --stacktrace and provide a stack trace if possible).

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 35s
Running Gradle task 'assembleRelease'...                           96.2s
Gradle task assembleRelease failed with exit code 1

Anyone has any clue on what went wrong?

**Comment by MaikuB** [comment]
Last time a similar issue was reported was in https://github.com/MaikuB/flutter_local_notifications/issues/1771 and this wasn't an issue with this plugin with Android Gradle Plugin. A few things for you to look into to try out are 

- update Flutter version
- update version of the plugin used
- update Gradle version used in your app

You may need to a combination of this steps but it's not an issue with the plugin itself will be closing this
