### ISSUE TITLE
On Huawei Hongmeng 3.0.0, the createNotificationChannel does not take effect and the created notification classification is not visible in the settings. It is possible on other mobile phones and emulators

### ISSUE THREAD

**Issue by panhuiAipami** [MaikuB/flutter_local_notifications#1952]
On Huawei Hongmeng 3.0.0, the createNotificationChannel does not take effect and the created notification classification is not visible in the settings. It is possible on other mobile phones and emulators

I found that others have also encountered this problem
Please take a look：https://developer.huawei.com/consumer/cn/forum/topic/0202102892544497015

**Comment by MaikuB** [comment]
I'm not Chinese nor can I read it so don't know what is said there. Regardless, this would be a device-specific issue and is outside the control of the plugin as it leverages the APIs provided by Android. If it doesn't work as expected then this would indicative of the manufacturer putting in restrictions or there's an issue with the OS. Not something this plugin can solve and you would need to see if the manufacturer has a solution for it, similar to how scheduled notifications may not work on such devices unless settings are changed
