### ISSUE TITLE
BUG: Error on initialize FlutterLocalNotificationsPlugin inside Isolate.spawn. Binding has not yet been initialized.

### ISSUE THREAD

**Issue by vfiruz97** [MaikuB/flutter_local_notifications#1955]
**Describe the bug**
I want to display local notification from the the spawned Isolate. And cancel when before Isolate will be killed.
Throws Unhandled exception: when execute `await flutterLocalNotificationsPlugin.initialize..`

<details><summary>Details</summary>
<p>

flutter doctor   
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.10, on macOS 13.2.1 22D68 darwin-x64, locale en-TJ)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.77.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

</p>
</details> 

**code**
```dart
void main(List<String> args) async {
  WidgetsFlutterBinding.ensureInitialized();
  RootIsolateToken rootIsolateToken = RootIsolateToken.instance!;
  Isolate.spawn(_isolateMain, rootIsolateToken, debugName: 'Isolate');

  runApp(
    MaterialApp(home: MapSample(...)),
  );
}

void _isolateMain(RootIsolateToken rootIsolateToken) async {
  DartPluginRegistrant.ensureInitialized();
  BackgroundIsolateBinaryMessenger.ensureInitialized(rootIsolateToken);

  // code
  print('object');

  void _requestPermissions() async {
    print('object1');
    final flutterLocalNotificationsPlugin = FlutterLocalNotificationsPlugin();
    const AndroidInitializationSettings initializationSettingsAndroid = AndroidInitializationSettings('app_icon');
    final initializationSettingsDarwin = DarwinInitializationSettings(
      requestSoundPermission: false,
      requestBadgePermission: false,
      requestAlertPermission: false,
      notificationCategories: [
        DarwinNotificationCategory(
          'demoCategory',
          actions: <DarwinNotificationAction>[
            DarwinNotificationAction.plain(
              'id_3',
              'Action 3',
              options: <DarwinNotificationActionOption>{
                DarwinNotificationActionOption.destructive,
              },
            ),
            DarwinNotificationAction.text(
              'id_4',
              'Action 4',
              buttonTitle: 'Stop',
              placeholder: 'running',
              options: <DarwinNotificationActionOption>{
                DarwinNotificationActionOption.foreground,
              },
            )
          ],
        )
      ],
    );
    print('object2');
    final InitializationSettings initializationSettings = InitializationSettings(
      android: initializationSettingsAndroid,
      iOS: initializationSettingsDarwin,
    );
    print('object3');
    await flutterLocalNotificationsPlugin.initialize(
      initializationSettings,
      onDidReceiveNotificationResponse: null,
      onDidReceiveBackgroundNotificationResponse: null,
    );
    print('object4');
    final result = await flutterLocalNotificationsPlugin
        .resolvePlatformSpecificImplementation<IOSFlutterLocalNotificationsPlugin>()
        ?.requestPermissions(
          alert: true,
          badge: true,
          sound: true,
        );
    print('requestPermissions result: $result');
    if (result == null || result == false) return;
    // Displaying a notification
    const AndroidNotificationDetails androidNotificationDetails = AndroidNotificationDetails(
        'your channel id', 'your channel name',
        channelDescription: 'your channel description',
        importance: Importance.max,
        priority: Priority.max,
        ongoing: true,
        ticker: 'ticker');
    const iOSNotificationDetails = DarwinNotificationDetails(
      categoryIdentifier: 'demoCategory',
      presentAlert: false,
      // presentSound: false,
      interruptionLevel: InterruptionLevel.active,
    );
    const notificationDetails = NotificationDetails(
      android: androidNotificationDetails,
      iOS: iOSNotificationDetails,
    );
    await flutterLocalNotificationsPlugin.show(
      0,
      'plain title',
      'plain body',
      notificationDetails,
      payload: 'item x',
    );

    Future.delayed(const Duration(seconds: 15), () async {
      // await flutterLocalNotificationsPlugin.cancelAll();
    });
  }

  _requestPermissions();
}
``` 

**Output: Exception **
```
Restarted application in 722ms.
flutter: object
flutter: object1
flutter: object2
flutter: object3
[VERBOSE-2:dart_isolate.cc(1098)] Unhandled exception:
Binding has not yet been initialized.
The "instance" getter on the ServicesBinding binding mixin is only available once that binding has been initialized.
Typically, this is done by calling "WidgetsFlutterBinding.ensureInitialized()" or "runApp()" (the latter calls the former). Typically this call is done in the "void main()" method. The "ensureInitialized" method is idempotent; calling it multiple times is not harmful. After calling that method, the "instance" getter will return the binding.
In a test, one can call "TestWidgetsFlutterBinding.ensureInitialized()" as the first line in the test's "main()" method to initialize the binding.
If ServicesBinding is a custom binding mixin, there must also be a custom binding class, like WidgetsFlutterBinding, but that mixes in the selected binding, and that is the class that must be constructed before using the "instance" getter.
#0      BindingBase.checkInstance.<anonymous closure> (package:flutter/src/<…>
```

**Comment by MaikuB** [comment]
This isn't an exception from the plugin. Furthermore, doesn't the exception message tell you what you need to do?

**Comment by vfiruz97** [comment]
@MaikuB it tells me what to do but it does not help. You never tried to initialize your plugin in spawned Isolate? 
for ex. sharedpreferences which using PlatformChannel  is working fine in new Isolate. It throws exception when it gets to the line where initializing your plugin. Can you replicate my example?

**Comment by MaikuB** [comment]
> it tells me what to do but it does not help. 

What exactly did you do then? Do you have a code snippet to show how you followed it? Note that the code snippet you have above doesn't actually follow what the exception message is above. If you actually followed its advice, you would be getting a different error message.

> You never tried to initialize your plugin in spawned Isolate? for ex. sharedpreferences which using PlatformChannel is working fine in new Isolate. 

Honestly no and this is because I developed the plugin to fill in a gap needed by the community as opposed to it being something I needed. This means other such as yourself are using the plugin more than me. The shared preferences plugin isn't actually a good example as each plugin serves a different purpose and this one requires interacting with the UI. The shared preferences plugin doesn't.

> It throws exception when it gets to the line where initializing your plugin. Can you replicate my example?

Yes, which is why I asked earlier to share a code snippet. I don't believe you should be initialising or requesting permissions in the spawned isolate to begin with as this can trigger UI actions that are meant to take place on the root/main isolate. Hence my point earlier on shared preferences not being a good example

**Comment by vfiruz97** [comment]
@MaikuB thank you for all your hard work for community and also for fast feedback in this issue. 

> The shared preferences plugin isn't actually a good example as each plugin serves a different purpose and **this one requires interacting with the UI**.

you mentioned good point. I strongly believe that if we initiate and ask permission for local notification in the main isolate then send instance to spawned isolate we'd be able to create notification in the spawned isolate. 
I will close this issue.
