### ISSUE TITLE
Update problem

### ISSUE THREAD

**Issue by DDETS-PROJET** [MaikuB/flutter_local_notifications#1956]
Hello, I would like to report a problem. when i update dependencies with this command
 dart pub upgrade --null-safety
 
Versions go back to this
  flutter_local_notifications 8.2.0 (13.0.0 available)
  flutter_local_notifications_platform_interface 4.0.1 (6.0.0 available)
  
 I'm losing class bindings in my project
But if I manually change the notification version to 13.0.0 in my pubspec.yaml file, everything goes back to normal
 
![screen problème 02](https://user-images.githubusercontent.com/72910714/231225237-4d28ff0f-9da0-40fd-ba5d-e40ed07c678e.png)
![screen problème 01](https://user-images.githubusercontent.com/72910714/231225241-addf01e5-b78b-405f-8b17-3c43ac86c1f4.png)

I am using the stable version of flutter

[√] Flutter (Channel stable, 3.7.10, on Microsoft Windows [version 10.0.22621.1485], locale fr-FR)
    • Flutter version 3.7.10 on channel stable at C:\Dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4b12645012 (8 days ago), 2023-04-03 17:46:48 -0700
    • Engine revision ec975089ac
    • Dart version 2.19.6
    • DevTools version 2.20.1

[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Dev\Android\android-sdk\
    • Platform android-33-ext5, build-tools 33.0.2
    • Java binary at: C:\Program Files\Microsoft\jdk-11.0.16.101-hotspot\bin\java.exe
    • Java version OpenJDK Runtime Environment Microsoft-40648 (build 11.0.16.1+1-LTS)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.3)
    • Visual Studio at C:\Dev\VS2022
    • Visual Studio Community 2022 version 17.5.33516.290
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Dev\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] VS Code, 64-bit edition (version 1.77.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.62.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 32) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [version 10.0.22621.1485]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 111.0.5563.147
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 111.0.1661.62

[√] HTTP Host Availability
    • All required HTTP hosts are available
  
  dependencies list :
 
    _flutterfire_internals 1.1.0
  archive 3.3.7
  args 2.4.0
  async 2.10.0 (2.11.0 available)
  boolean_selector 2.1.1
  characters 1.2.1 (1.3.0 available)
  clock 1.1.1
  collection 1.17.0 (1.17.1 available)
  connectivity_plus 3.0.4
  connectivity_plus_platform_interface 1.2.4
  convert 3.1.1
  crypto 3.0.2
  cupertino_icons 1.0.5
  dbus 0.7.8
  device_info_plus 8.2.0
  device_info_plus_platform_interface 7.0.0
  eva_icons_flutter 3.1.0
  fake_async 1.3.1
  ffi 2.0.1
  file 6.1.4
  firebase_app_installations 0.2.2
  firebase_app_installations_platform_interface 0.1.2
  firebase_app_installations_web 0.1.2
  firebase_core 2.9.0
  firebase_core_platform_interface 4.6.0
  firebase_core_web 2.3.0
  firebase_messaging 14.4.0
  firebase_messaging_platform_interface 4.3.0
  firebase_messaging_web 3.3.0
  flutter 0.0.0 from sdk flutter
  flutter_lints 2.0.1
  flutter_local_notifications 8.2.0 (13.0.0 available)
  flutter_local_notifications_platform_interface 4.0.1 (6.0.0 available)
  flutter_svg 2.0.5
  flutter_test 0.0.0 from sdk flutter
  flutter_timezone 1.0.4
  flutter_web_plugins 0.0.0 from sdk flutter
  get 4.6.5
  http 0.13.5
  http_parser 4.0.2
  image 4.0.15
  intl 0.18.0
  js 0.6.5 (0.6.7 available)
  lints 2.0.1
  matcher 0.12.13 (0.12.15 available)
  material_color_utilities 0.2.0 (0.3.0 available)
  meta 1.8.0 (1.9.1 available)
  nm 0.5.0
  path 1.8.2 (1.8.3 available)
  path_parsing 1.0.1
  path_provider 2.0.14
  path_provider_android 2.0.24
  path_provider_foundation 2.2.2
  path_provider_linux 2.1.10
  path_provider_platform_interface 2.0.6
  path_provider_windows 2.1.5
  percent_indicator 4.2.3
  petitparser 5.1.0 (5.3.0 available)
  platform 3.1.0
  plugin_platform_interface 2.1.4
  pointycastle 3.7.2
  process 4.2.4
  sky_engine 0.0.99 from sdk flutter
  source_span 1.9.1 (1.10.0 available)
  stack_trace 1.11.0
  stream_channel 2.1.1
  string_scanner 1.2.0
  term_glyph 1.2.1
  test_api 0.4.16 (0.5.1 available)
  timezone 0.8.0 (0.9.1 available)
  typed_data 1.3.1
  vector_graphics 1.1.4
  vector_graphics_codec 1.1.4
  vector_graphics_compiler 1.1.4
  vector_math 2.1.4
  win32 3.1.4 (4.1.2 available)
  xdg_directories 1.0.0
  xml 6.2.2
  
Do not hesitate if you need other detail the problem.
If you can give me more details on this dependency problem, it would be very useful for me for the future.
Thanking you, Best regards :)

PS : My English is a bit rusty, sorry

**Comment by MaikuB** [comment]
I've seen a similar issue raised when others used `flutter pub add ...` before but unfortunately I don't know how to resolve the issue. If you or others know if how to fix this then welcome to submit a PR on this. This assumes though that it's an issue with this plugin though I would've thought the appropriate version constraints etc are already applied/specified by this plugin. Other potential cases of the problem are due to the use of other dependencies (which I wouldn't have control over) or that the Flutter tooling isn't resolving the appropriate version properly
