### ISSUE TITLE
It's currently not possible to specify the intent (AudioAttributeUsage) when creating an AndroidNotificationChannel

### ISSUE THREAD

**Issue by jordyvanvorselen** [MaikuB/flutter_local_notifications#1964]
**Describe the bug**
It's not possible to specify the intent (AudioAttributeUsage) when creating a notification channel.

It however is possible to pass the intent when triggering a notification.

**To Reproduce**
1. Instantiate a new `AndroidNotificationChannel`
2. There is no way to specify the intent / `AudioAttributeUsage`

**Expected behavior**
There is the possibility to specify the intent / `AudioAttributeUsage`.

**Sample code to reproduce the problem**
 
        // Without a way of specifying the intent, we can not play the sound over the android alarm channel.
        // We need to create the notification channels explicitly, because in our usecase it should also be working
        // when the notification is received when the application is in the background.
        AndroidNotificationChannel(
          'alarm_notification_channel',
          'Alarm Notifications',
          description: 'This channel is used for alarm notifications.',
          importance: Importance.high,
          playSound: true,
          sound: RawResourceAndroidNotificationSound('alarm'),
          enableVibration: true,
          audioAttributesUsage: AudioAttributesUsage.alarm,  // This is currently not possible.
        ),

**Comment by MaikuB** [comment]
Could you help submit a PR on this? Support for audio attributes originally came in via a community contribution (see https://github.com/MaikuB/flutter_local_notifications/pull/1649). Note that whilst it's not possible to specify it via the channel if it's created separately, as far as I know, it is possible to specify the usage/intent via `NotificationDetails` that if the channel was created as part of the process to trigger a notification, the channel will be created with the specified intent

**Comment by jordyvanvorselen** [comment]
> Could you help submit a PR on this? Support for audio attributes originally came in via a community contribution (see https://github.com/MaikuB/flutter_local_notifications/pull/1649). Note that whilst it's not possible to specify it via the channel if it's created separately, as far as I know, it is possible to specify the usage/intent via `NotificationDetails` that if the channel was created as part of the process to trigger a notification, the channel will be created with the specified intent

Thanks for clarifying. Sure, I'll try to submit a PR for this soon.

**Comment by MaikuB** [comment]
As it's been a very long time since this issue has been opened, I assume there's still no plan to submit a PR on this so will close

**Comment by ditheshthegreat** [comment]
I have created a PR related this issue.
