### ISSUE TITLE
Verify if -keep class * implements com.google.gson.JsonSerializer is relevant to add in proguard-rules.pro

### ISSUE THREAD

**Issue by Dolar1** [MaikuB/flutter_local_notifications#1966]
**Describe the bug**
We can see rules defined in proguard-rules.pro on line no 17 as 
`-keep class * implements com.google.gson.JsonSerializer`
But no instance of the same is being used in the whole repo, can we remove it.

**To Reproduce**
simply search `JsonSerializer` in the whole repo of `flutter_local_notifications`.
<img width="1107" alt="Screenshot 2023-04-18 at 3 05 21 PM" src="https://user-images.githubusercontent.com/33690796/232736358-46f6e5c9-95d2-414c-82b6-696e6b03907e.png">

**Expected behavior**
It should not have thrown any error/warning in dexguard report but it's generating a warning as 
`Your denylist for Name Obfuscation does not match any entities. Please verify that it is effective.`

**Sample code to reproduce the problem**
simply search `JsonSerializer` in the whole repo of `flutter_local_notifications`.
as above in SS.

**Comment by MaikuB** [comment]
If you look more closely at the docs and related links around [release build configuration](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#release-build-configuration), as well as the namespace involved, these are rules required by Gson that is used as a transitive dependency. Not seeing it in the plugin's codebase is therefore somewhat expected. If you have doubts on if it's needed then best place would be to ask is on the https://github.com/google/gson repository and these rules were originally sourced from https://github.com/google/gson/tree/master/examples/android-proguard-example where it's purposed is to show how to configure Proguard with Gson. Furthermore, if you have a strong belief that it's not needed then it could be something you can verify this by removing it as well but bear in mind that it's possible this may result in issues in your app. Personally I'd prefer to err on the side on caution given these rules came from those working on Gson even if there are warnings.
