### ISSUE TITLE
Does not work with Timezone.

### ISSUE THREAD

**Issue by prifyDevelopers** [MaikuB/flutter_local_notifications#1967]
anytime i click on schedule notification for 1 day , or even next 5 seconds it crashes app and display this error

FATAL EXCEPTION: main
E/AndroidRuntime( 3514): Process: com.example.word, PID: 3514
E/AndroidRuntime( 3514): java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/LocalDateTime;
E/AndroidRuntime( 3514): at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.zonedScheduleNotification(FlutterLocalNotificationsPlugin.java:540)
E/AndroidRuntime( 3514): at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.zonedSchedule(FlutterLocalNotificationsPlugin.java:1453)
E/AndroidRuntime( 3514): at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(FlutterLocalNotificationsPlugin.java:1305)
E/AndroidRuntime( 3514): at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/AndroidRuntime( 3514): at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/AndroidRuntime( 3514): at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:322)
E/AndroidRuntime( 3514): at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$2j2MERcK825A5j1fv5sZ7xB2Iuo.run(lambda)
E/AndroidRuntime( 3514): at android.os.Handler.handleCallback(Handler.java:751)
E/AndroidRuntime( 3514): at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 3514): at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime( 3514): at android.app.ActivityThread.main(ActivityThread.java:6190)
E/AndroidRuntime( 3514): at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 3514): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:892)
E/AndroidRuntime( 3514): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
E/AndroidRuntime( 3514): Caused by: java.lang.ClassNotFoundException: Didn't find class "java.time.LocalDateTime" on path: DexPathList[[zip file "/data/app/com.example.word-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.word-1/lib/x86, /data/app/com.example.word-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]
E/AndroidRuntime( 3514): at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime( 3514): at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
E/AndroidRuntime( 3514): at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime( 3514): ... 14 more

**Comment by MaikuB** [comment]
For future reference, please try to check if this issue has been reported before as there's been a number of issues mentioned on this. See https://github.com/MaikuB/flutter_local_notifications/search?q=Ljava%2Ftime%2FLocalDateTime&type=issues. The issue you're seeing is because you hadn't configured the app properly as per https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#-android-setup. If you're having this issue then chances are there are other parts of the readme that you hadn't gone through properly so please ensure you do so
