### ISSUE TITLE
Deprecated iOS notification code silently still compiles

### ISSUE THREAD

**Issue by stevekohls** [MaikuB/flutter_local_notifications#1969]
**Describe the bug**
PR #1740 addressed issue #1592.

That PR suppressed warning notifications for deprecated API related to `UILocalNotification`.
The warnings are no longer issued, but the deprecated code is still compiled.

It is ok for deprecated code to be compiled, but only if the API is still available in the SDK version.

Like in PR #1965, the deprecated code should we wrapped in an appropriate `#available` statement that only compiles the code if it exists in the SDK. This should make sure the warnings are silenced on build time, and that if a future SDK _removes_ that old API, the compile will not fail.

I recently pushed PR #1965 which addressed warnings which remained in the macOS code.

**To Reproduce**
Review the code and see that warnings and silenced, and the code in question is not guarded by conditional compilation.

**Expected behavior**
Deprecated code should not be compiled if does not exist in the SDK used for the build. By conditionally compiling the deprecated code, warnings will never be issued when building with an SDK version introduced after the deprecated API is removed.

**Sample code to reproduce the problem**
See **flutter_local_notifications/ios/Classes/FlutterLocalNotificationsPlugin.m** and search for:
```objective-c
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
```

**Comment by stevekohls** [comment]
@MaikuB I'm going to take this one on now, since I wrapped up the macOS fixes.

**Comment by MaikuB** [comment]
Sure, thanks for helping out.

**Comment by MaikuB** [comment]
Heads up I intend to publish 14.0.0 as a stable release soon. This likely means that when you get around to doing the PR for that it 'll be as a patch against a stable 14.x.x version
