### ISSUE TITLE
Add compatibility with AGP 8 (Android Gradle Plugin)

### ISSUE THREAD

**Issue by biklas7** [MaikuB/flutter_local_notifications#1973]
Android Flutter plugins should add `namespace` under `android` inside the build configuration for the app.
Something like [this](https://github.com/fluttercommunity/plus_plugins/pull/1704/files).

Also check official android documentation [here](https://developer.android.com/build/publish-library/prep-lib-release#choose-namespace).

**Comment by MaikuB** [comment]
A PR on this has already been merged in https://github.com/MaikuB/flutter_local_notifications/pull/1970 so will close this issue
