### ISSUE TITLE
Can plugins send notifications when the app is not running

### ISSUE THREAD

**Issue by cooliangzhu** [MaikuB/flutter_local_notifications#1974]
I used version 14.0.0 on an Android device, set to send notifications after 5 seconds, and then killed the app.
I can receive notifications on the emulator, but they cannot be received on Xiaomi's real machine

Would you like to confirm if this plugin can only send notifications while the app is still running?

**Comment by MaikuB** [comment]
This isn't to do with the situations the plugin will work. Please read https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#scheduled-android-notifications
