### ISSUE TITLE
custom interval reminders,not just every day, every week, every month

### ISSUE THREAD

**Issue by mlf2020** [MaikuB/flutter_local_notifications#1978]
Whether to support custom interval reminders, such as every n days, every n weeks, every n months, etc

**Comment by MaikuB** [comment]
There's an existing issue on this at https://github.com/MaikuB/flutter_local_notifications/issues/92. If this something you want then you'll do to do a PR for it consider using a fork for your own purposes. Bear in mind that there are limitations imposed by native APIs that can restrict what you can do to begin with. This is what knowledge of said APIs is prerequisite to using the plugin as it's purpose is to act as a wrapper for them. Closing this as an there's an existing issue
