### ISSUE TITLE
Can we make play sound to false or true according to condition.

### ISSUE THREAD

**Issue by pranavo72bex** [MaikuB/flutter_local_notifications#1979]
I want to play sound for specific case and not in another case. But if `playSound: true` then it work as expected but in another case when `playSound: false` even though it is producing sound.

**Comment by MaikuB** [comment]
No, please read the API docs for it (see https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/AndroidNotificationDetails/playSound.html) and around how notifications work on Android as this would've explained the behaviour
