### ISSUE TITLE
UI is crashing upon receiving push notifications when app is in foreground in flutter-Android

### ISSUE THREAD

**Issue by hiral6882** [MaikuB/flutter_local_notifications#198]
I am using FCM. I am trying to show notification when my app is in foreground. I am recieving notification successfully but app is crashing upon receiving it

void initState() {

//TODO: Local notifications configuration.
var initializationSettingsAndroid = AndroidInitializationSettings('notification_icon');
var initializationSettingsIOS = IOSInitializationSettings();
var initializationSettings = InitializationSettings(initializationSettingsAndroid,initializationSettingsIOS);

Future selectNotification(String payload) async {
  print('Showing alert');
  showDialog(context: context,builder: (_)=>AlertDialog(title: Text("Title"),));
}

FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin = FlutterLocalNotificationsPlugin();

flutterLocalNotificationsPlugin.initialize(initializationSettings,onSelectNotification: selectNotification);

Future showNotifications() async {
  print('show');
  var androidPlatformSpecifics = AndroidNotificationDetails('123','Channel Name','Description about the channel',importance: Importance.Max,priority: Priority.Default);
  var iOSPlatformSpecifics = IOSNotificationDetails();
  var platformChannelSpecifics = NotificationDetails(androidPlatformSpecifics,iOSPlatformSpecifics);
  await flutterLocalNotificationsPlugin.show(0, 'New Post', 'Notification', platformChannelSpecifics);
  print('show');

}

//TODO:Configuration of firebase
_firebaseMessaging.configure(
  onMessage: (Map<String,dynamic> message){
    debugPrint('on');
    showNotifications();
    print(message);
  },
  onResume: (Map<String,dynamic> message){
    debugPrint('resume');
    print(message);
  },
  onLaunch: (Map<String,dynamic> message){
    debugPrint('Launch');
    print(message);
  },

);

_firebaseMessaging.getToken().then((token){
  print(token);
});

After push notification I keep getting "System UI has stopped"

**Comment by MaikuB** [comment]
Any chance you complete code that could be used to reproduce the problem? The layout of your code looks a bit confusing. Other question I've got have you tested to see if you can actually show a notification via this plugin without any problems whilst ensuring the code to initialise the plugin and show the notification is the same as what you have above?

**Comment by MaikuB** [comment]
closing to lack of further response
