### ISSUE TITLE
Know when notification fires in Foreground state

### ISSUE THREAD

**Issue by AAverin** [MaikuB/flutter_local_notifications#1980]
Is there any way to know when local notification fires in the Foreground state of the app?

I have lots of local notifications (calendar-like app), so I need to reschedule future notifications often.
I plan to do it:
- when app starts (for any reason, including tap on notification)
- when notification is received while app is running

I have checked Android code and `sendNotificationPayloadMessage` is triggered from `onNewIntent()`, that is when user clicks on notification. Is there also some callback when notification fires? 
I didn't find anything in `ScheduledNotificationReceiver`, it only attempts to re-schedule notifications if frequency/interval were configured. I would like to reschedule manually.

**Comment by MaikuB** [comment]
There's no such capability and a similar issue has been raised before #1699 so will close this. You would need to look into submitting a PR for this
