### ISSUE TITLE
Is it possible to simply send a local notification when user presses a button?

### ISSUE THREAD

**Issue by simplenotezy** [MaikuB/flutter_local_notifications#1981]
I am looking to send a local notification N seconds after a user have pressed a button and left the app. So the notification needs not to be shown if the app is open, and needs to be sent/scheduled from within flutter locally.

I have read through the whole documentation but it's still unclear to me whether that is possible using this library.

Documentation doesn't seem to write anything about how to send a local push notification on iOS only how to show incoming notifications in the app, which is not something I am looking to do. Most examples seem to include Android config, but no specific iOS config

**Comment by simplenotezy** [comment]
Although the documentation can be a bit overwhelming and seem like very tedious work to get local notifications working, it turned out to be as simple as:

```dart
    final FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin = FlutterLocalNotificationsPlugin();
    const AndroidNotificationDetails androidNotificationDetails = AndroidNotificationDetails(
      'local_push',
      'local push notification',
      channelDescription: 'currently used to aid in copying the invite link',
      importance: Importance.max,
      priority: Priority.high,
      ticker: 'ticker',
    );
    const NotificationDetails notificationDetails = NotificationDetails(android: androidNotificationDetails);
    await flutterLocalNotificationsPlugin.show(
      0,
      'some title',
      'some text',
      notificationDetails,
    );

**Comment by MaikuB** [comment]
Glad you sorted it out though FYI I noted that there's an example app located at https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications/example. If you clone the repository then you would be able to run it. It covers the majority of scenarios that can by the implemented by plugin is covered and each scenario is has a corresponding button. This allows tracing the code related to pressing on the button to use as a reference for your own application

**Comment by simplenotezy** [comment]
Thanks @MaikuB!

**Comment by simplenotezy** [comment]
@MaikuB By the way, how do I handle Android notifications? On iOS we got `onDidReceiveLocalNotification`, but what about android?

https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/example/lib/main.dart#L152
