### ISSUE TITLE
I cannot cancel notification using flutterLocalNotificationsPlugin.cancel() function

### ISSUE THREAD

**Issue by FullStack1106** [MaikuB/flutter_local_notifications#1988]
Hi,.
I am developing a flutter app and used this package.
When user A send request to user B, user B receive push notification and display local notification.
After 20 seconds, if user B did not take action for this notification, I have to remove this notification from notification bar.
Here is my code but does not work.
```dart
      String messageCategory = message.data['category'].toString();
      int notificatonUniqueId = notification.hashCode;
      await flutterLocalNotificationsPlugin.show(
          notificatonUniqueId,
          newTitle,
          newBody,
          notificationDetails,
          payload: payload).then((value) {
        if(messageCategory == "cash_request"){
          Timer(Duration(seconds: 20), ()async {
            print("Cancel Notification:${notificatonUniqueId}");
            await flutterLocalNotificationsPlugin.cancel(notificatonUniqueId);
          });
        }
      });
```

**Comment by FullStack1106** [comment]
After 20 seconds, I get this log correctly.
```
I/flutter (12456): Cancel Notification:429297137
```

**Comment by FullStack1106** [comment]
Thanks @MaikuB 
It was my issue. and I want to discuss some details for firebase_messaging.
As I described in first comment, I need to cancel notification after 20 seconds if user did not take any actions.
But when I receive push notfication using firebase_messaging package, app display notification even I did not call flutterLocalNotificationPlugin.show() function.
So I checked active notifications and notification id.
Notifications that has published from push notification has 0 for notification_id.
I cannot cancel specific notification.
Can you please set notification id using notification.hashcode?
I think it would be solve my problem.
Thank you.

**Comment by MaikuB** [comment]
That is to do with FCM not this plugin. This is something you need to familiarise yourself with on how to work with FCM. Not something I can you help you with
