### ISSUE TITLE
Clicking on notification action button does not dismiss notification on android terminated state

### ISSUE THREAD

**Issue by Cha195** [MaikuB/flutter_local_notifications#1991]
Hi team. Thanks for the plugin. I'm facing an issue with notification actions.

When a user clicks on the notification action, while the app is in terminated state (cleared from recent apps), the notification is not dismissed and it stays.
The notification sent is a data message so we don't get an FCM notification as well (which does not show the action buttons). 
Refer to the recording below.

Uploading Screen_Recording_20230512_112839_Pocketpills (Stg).mp4…

**Comment by MaikuB** [comment]
I can't see the video and if you'd like to report a bug, then this should be done via the bug report and include a link to a repo of a minimal app that can reproduce the issue. This is best done via a fork of the repo and modify the example app to demonstrate this. In saying that, the example app shows that this is possible so I suggest you take a closer look at it and cross-reference it with what you've done. My guess is you've set [https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/AndroidNotificationAction/cancelNotification.html] to false. Here's a recording I took of the example app where you can see the notification is dismissed/cancelled after tapping on an action

https://github.com/MaikuB/flutter_local_notifications/assets/25263378/7a01aa9b-fa57-4c89-80e3-59e2fe379d0a

**Comment by Cha195** [comment]
Hi @MaikuB thank you for the response. But the notification that you show in the recording is a foreground notification which you click after terminating the app. The scenario I mentioned in the issue was receiving the notification when the app is terminated.

**Comment by MaikuB** [comment]
The state of the app when the notification appears has no impact on this. I could change the example to schedule notification with actions so that it appears after the app is terminated and the result is the same. 


https://github.com/MaikuB/flutter_local_notifications/assets/25263378/7ef42a3b-07fe-4a39-b644-c59e845b7359

Note that you still need to provide a evidence of the issue with a link to repo hosting a minimal app that can reproduce this. Unless you're going to do this then this won't be looked into further and the issue will be closed.

**Comment by Cha195** [comment]
Hi @MaikuB, as requested I have forked the repo made changes to reproduce the issue. 
Link: https://github.com/Cha195/flutter_local_notifications

The change was to set `showUserInterface` parameter to true in the `AndroidNotificationAction` as shown below. This opens the app when the user clicks on the Notification Action Button but does not dismiss the notification when it is received in the terminated state in android.

<img width="463" alt="image" src="https://github.com/MaikuB/flutter_local_notifications/assets/60818157/382f5b58-d397-40e3-ad8c-3304f9b21f06">

https://github.com/MaikuB/flutter_local_notifications/assets/60818157/20215e98-6acd-4a89-b977-51ad4567bc9c

**Comment by MaikuB** [comment]
Thanks for providing this as this helped reproduce the issue. I have a fix in https://github.com/MaikuB/flutter_local_notifications/tree/fix-notification-action-terminated. Could you help verify that this solves the issue? You could also try using that branch with your app temporarily as well by following steps mentioned in https://dart.dev/tools/pub/dependencies#git-packages. Once you've confirmed this solves the issue, I'll have this merged in and released as a patch update

**Comment by Cha195** [comment]
Hi @MaikuB thanks for the swift action! I tested the code in two my own app and the example app and yes the changes work. Thanks for your effort!
Cheers

**Comment by dishankjindal1** [comment]
I am facing the similar issue, i want to implement a dismiss action button, but it is not removing the notification from the notification center.

**Comment by Levi-Lesches** [comment]
@dishankjindal1 Please file a new issue with your code for setting up the plugin, your code for showing the notification, and your platform/device. Please also confirm that you've followed the instructions for setup properly and try checking the example app to see if it's an issue in your project's code.
