### ISSUE TITLE
The method 'requestPermission' isn't defined for the type 'AndroidFlutterLocalNotificationsPlugin'. 

### ISSUE THREAD

**Issue by luohao123** [MaikuB/flutter_local_notifications#1992]
The method 'requestPermission' isn't defined for the type 'AndroidFlutterLocalNotificationsPlugin'.

**Comment by MaikuB** [comment]
You've most likely have a corrupt pub cache so will need to fix that as the plugin has had this API for a while and example has been working fine. In other words, there isn't an issue with the plugin here so something and would an issue in your development environment. You can see in other issues like https://github.com/MaikuB/flutter_local_notifications/issues/1991 that myself and others in the community are able to record the example app running on Android fine. If the plugin actually hd this issue then the app would've crashed

**Comment by Nimo11** [comment]
The method requestPermission must be replaced by requestNotificationsPermission now.
