### ISSUE TITLE
安卓上架审核被拒说是sdk频繁自启动

### ISSUE THREAD

**Issue by ly410726** [MaikuB/flutter_local_notifications#1996]
com.dexterous.flutterlocalnotifications提示频繁自启动引起app上架审核失败

**Comment by MaikuB** [comment]
Please use English to communicate here

**Comment by lwj1994** [comment]
Due to the privacy restrictions of Chinese app stores, apps can only be launch in the background after obtaining users' consent, Therefore, can provide a method for users to initialize BroadcastReceiver instead of  register it in AndroidManifest.xml @MaikuB

**Comment by lwj1994** [comment]
> Due to the privacy restrictions of Chinese app stores, apps can only be launch in the background after obtaining users' consent, Therefore, can provide a method for users to initialize BroadcastReceiver instead of register it in AndroidManifest.xml @MaikuB
 this my pr,   I moved the registration of the broadcast to initialization time
https://github.com/MaikuB/flutter_local_notifications/pull/2001
