### ISSUE TITLE
didNotificationLaunchApp is always false when I opened from killed app on IOS Flutter

### ISSUE THREAD

**Issue by jsolanas7** [MaikuB/flutter_local_notifications#2006]
I have a Flutter proyect and I'm using flutter_local_notifications. Everything is working fine, background notifications, when the app is opened. The problem is when the app is killed I receive the notification but when I click on it, this only open the app and when I check with didNotificationLaunchApp is always false. This happens only in iOS, in Android is working as expected.

How I'm validating? When the app starts I have the validation:

```
final NotificationAppLaunchDetails? notificationAppLaunchDetails =
  await flutterLocalNotificationsPlugin.getNotificationAppLaunchDetails();
if (notificationAppLaunchDetails != null &&
  notificationAppLaunchDetails.didNotificationLaunchApp){
Logic here...
}
```
Here is my AppDelegate

```
import UIKit
import Flutter
import Firebase

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate, MessagingDelegate  {
override func application(
_ application: UIApplication,
didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
 ) -> Bool {
FirebaseApp.configure()
Messaging.messaging().delegate = self
GeneratedPluginRegistrant.register(with: self)
if #available(iOS 10.0, *) {
    // For iOS 10 display notification (sent via APNS)
    UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate 
    let authOptions: UNAuthorizationOptions = [.alert, .badge, .sound]
    UNUserNotificationCenter.current().requestAuthorization(
            options: authOptions,
            completionHandler: {_, _ in })
} else {
    let settings: UIUserNotificationSettings =
    UIUserNotificationSettings(types: [.alert, .badge, .sound], categories: nil)
    application.registerUserNotificationSettings(settings)
}
application.registerForRemoteNotifications()
return super.application(application, didFinishLaunchingWithOptions: launchOptions)
 }
}
```
I read a lot of answers that I need this linein AppDelegate

```
UNUserNotificationCenter.current().delegate = self as? 
UNUserNotificationCenterDelegate 
```
But didNotificationLaunchApp is always false

**Comment by Mertcncifter** [comment]
Getting the same error, any way to fix this?

**Comment by jsolanas7** [comment]
@Mertcncifter Yes. Here is how I fixed it (is not a bug, just is not in the documentation)

You should use:

`FirebaseMessaging.instance.getInitialMessage().then((message) {
 ...your code here
}
`

And the most important part is:

Your notification MUST have in data this:

`'click_section' : 'FLUTTER_NOTIFICATION_CLICK'`

For example:

`const notification = {
     .....,
     'data': {
          'click_section' : 'FLUTTER_NOTIFICATION_CLICK'
      },
}`

**Comment by MaikuB** [comment]
The issue you're seeing is because you were dealing with a push/remote notification via Firebase. Therefore, it's required that you add the appropriate code for FCM as this plugin is for local notifications
