### ISSUE TITLE
The Notifications triggered in the Background aren't working well

### ISSUE THREAD

**Issue by KamathVishak96** [MaikuB/flutter_local_notifications#2009]
**Describe the bug**
I am Triggerring the notification from a Background service, that runs when the app is killed. When I tap on the Notification, it just opens the app and the `onDidReceiveBackgroundNotificationResponse` is not called. But, when I tap on the Action button in notification, it goes to this function but doesn't open the app. When I set `showsUserInterface: true` for this action button, it opens the app but control doesn't go to `onDidReceiveBackgroundNotificationResponse` function.
I have tried initialising the PLugin in both main() and inside service, behaves the same.
I'm trying to open the app, and based on the payload, open a specific page. 

**To Reproduce**
1. Run a service using flutter_background_service.
2. Kill the app and make sure the service is still running.
3. Make sure the notification is triggered after you kill the app.
4. Tap on the notification or the trigger.

**Sample code to reproduce the problem**

```
@pragma('vm:entry-point')
void scanToConnect(ServiceInstance? service) async {
// some code
bluetoothCharacteristic.listen((event){
    FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
  FlutterLocalNotificationsPlugin();

  const AndroidInitializationSettings androidSettings =
  AndroidInitializationSettings('app_icon');
  const DarwinInitializationSettings iOSSettings =
  DarwinInitializationSettings();
  const InitializationSettings initializationSettings = InitializationSettings(
    android: androidSettings,
    iOS: iOSSettings,
  );

  await flutterLocalNotificationsPlugin.initialize(
    initializationSettings,
    onDidReceiveNotificationResponse: onForegroundNotificationTapped,
    onDidReceiveBackgroundNotificationResponse: onBackgroundNotificationTapped,
  );


  const AndroidNotificationDetails androidNotificationDetails =
      AndroidNotificationDetails(
    "button_trigger",
    "Button Trigger",
  );
  const NotificationDetails notificationDetails =
      NotificationDetails(android: androidNotificationDetails);

  flutterLocalNotificationsPlugin.show(
      DateTime.now().millisecond,
      "Some title",
      "Some description",
      notificationDetails,
      payload: "some payload");  
});


@pragma('vm:entry-point')
Future<void> onBackgroundNotificationTapped(NotificationResponse details) async {
  print("Background Notification Details: ${details.payload}");
  print("Background Notification Details: Action: ${details.actionId}");

}
}
```

**Comment by TheFinestArtist** [comment]
I think I found a way.

From your MainActivity (Android code), override onCreate and getIntent. The action id will be saved in the intent as extra.

https://github.com/MaikuB/flutter_local_notifications/blob/ca71c96ba2a245175b44471e2e41e4958d480876/flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java#L303

```kotlin
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    Log.e("MainActivity", "onCreate ${intent.hasExtra("actionId")}")
  }
  ```
