### ISSUE TITLE
Android Notification Channel Management

### ISSUE THREAD

**Issue by mrmikezhang** [MaikuB/flutter_local_notifications#201]
Hi @MaikuB 

This is a new request based on the previous feature request: https://github.com/MaikuB/flutter_local_notifications/issues/167

First of all thank you for adding the support for updating existing channel name. I have tested it and it works as expected. However I would like to suggest a few improvements and suggestions.

1. There's no way to determine whether the notification channel exists or not, therefore it's not possible to determine which channel action to use (please correct me if I am wrong). 
`if ((notificationChannel == null && (notificationDetails.channelAction == null || notificationDetails.channelAction == NotificationChannelAction.CreateIfNotExists)) || (notificationChannel != null && notificationDetails.channelAction == NotificationChannelAction.Update))`
This line basically won't allow a new notification channel to be created if it doesn't exist while setting the NotificationChannelAction to Update.

2. It would be nice to have the ability to retrieve all existing channels as well as methods to update/delete them without having to schedule a notification first. (I know you are trying to avoid exposing platform-specific methods, but it will be really handy)

Thank you very much for your help in advance. Have a nice weekend.

**Comment by MaikuB** [comment]
Those features you mention would involve having platform specific and I've mentioned in #167 that I don't plan on supporting that. I would suggest you either fork this repository or make use of platform channels to add those features you need

**Comment by mrmikezhang** [comment]
Alright no problem mate. Will do, :)
