### ISSUE TITLE
onDidReceiveLocalNotification of DarwinInitializationSettings can be removed because Flutter does not support iOS Versions older than 11 anymore

### ISSUE THREAD

**Issue by saibotma** [MaikuB/flutter_local_notifications#2010]
The documentation of `onDidReceiveLocalNotification` states that 

> This property is only applicable to iOS versions older than 10.

According to https://docs.flutter.dev/deployment/ios#review-xcode-project-settings, the minium iOS version Flutter supports is 11. 

Is this correct? I would love to create a PR and remove the callback, as this would make configuring the plugin simpler.

**Comment by MaikuB** [comment]
The documentation there is based on the current version of Flutter. A PR and discussion (see https://github.com/MaikuB/flutter_local_notifications/pull/2002) relating to this was raised before and was closed as it missed that the plugin supports Flutter 3.0 as the minimum and that supports iOS 9 onwards
