### ISSUE TITLE
onDidReceiveBackgroundNotificationResponse callback is not getting navigate or not triggered function when tapped on notification

### ISSUE THREAD

**Issue by itsdani121** [MaikuB/flutter_local_notifications#2011]
**Describe the bug**

Here i implement flutter local notification with firebase messaging but the issue is when i receive notificaiton on foreground app then it navigate where i want to navigate it. but when my app is on background or terminated state then it will not working backgroundNotificationResponse function till now. here is my code.. 

**Expected behavior**

The expected behavior of this function is when app is background or terminated state then this function triggered and inside where i am using navigation then it navigate it without any problem

**Sample code to reproduce the problem**

```
AndroidNotificationChannel channel = AndroidNotificationChannel(
  'high_importance_channel', // id
  'High Importance Notifications', // title
  description: 'This channel is used for important notifications.', // description
  importance: Importance.max,
  playSound: true,
  enableLights: true,
  ledColor: Colors.purpleAccent,
);
final FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin = FlutterLocalNotificationsPlugin();
FirebaseMessaging messaging = FirebaseMessaging.instance;
AndroidInitializationSettings initializationSettingsAndroid = AndroidInitializationSettings('ic_launcher');
final InitializationSettings initializationSettings = InitializationSettings(android: initializationSettingsAndroid);

final GlobalKey<NavigatorState> navigatorKey = GlobalKey<NavigatorState>();
var mIdNotify;
@pragma('vm:entry-point')
Future<void> firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  RemoteNotification? notification = message.notification;
  AndroidNotification? androidz = message.notification?.android;
  if (message.notification != null && androidz != null) {
    flutterLocalNotificationsPlugin.show(
      notification.hashCode,
      notification?.title,
      notification?.body,
      NotificationDetails(
        android: AndroidNotificationDetails(
          'your channel id',
          'your channel name',
          channelDescription: 'your channel description',
          priority: Priority.high,
          importance: Importance.max,
          // Assigning vibration pattern to notification
          // Assigning custom sound to notification
          icon: '@mipmap/ic_launcher',
          // Assigning large icon to notification
          largeIcon: DrawableResourceAndroidBitmap('@mipmap/ic_launcher'),
        ),
      ),
    );
    mIdNotify = message.data['meeting_id'];
    print('meeting background id $mIdNotify  - ${box.read('nMeetingId')}');
  }
  // popUpMessage(message.notification!.android!.tag!);
  // }
  navigatorKey.currentState?.push(MaterialPageRoute(
    builder: (context) => MeetingViewPage(meetingId: box.read('nMeeting') != null ? int.parse(box.read('nMeetingId')) : int.parse(mIdNotify)),
  ));

  print('backgrond  mssss   ${message.notification?.toMap()}');
}

//main method.


void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await EasyLocalization.ensureInitialized();
  await Firebase.initializeApp();
  await GetStorage.init();
  await flutterLocalNotificationsPlugin
      .resolvePlatformSpecificImplementation<AndroidFlutterLocalNotificationsPlugin>()
      ?.createNotificationChannel(channel);

    messaging.getToken().then((value) {
      box.write('fcm_token', value!);
    });
    FirebaseMessaging.onBackgroundMessage(firebaseMessagingBackgroundHandler);

  await flutterLocalNotificationsPlugin
        .resolvePlatformSpecificImplementation<AndroidFlutterLocalNotificationsPlugin>()
        ?.createNotificationChannel(channel);
    await FirebaseMessaging.instance.setForegroundNotificationPresentationOptions(
      alert: true, // Required to display a heads up notification
      badge: true,
      sound: true,
    );

    _fcmForegroundHandler();
    runApp(SplashPage());
  
}

  Future<void> _fcmForegroundHandler() async {
    FirebaseMessaging.onMessage.listen((RemoteMessage message) async {
      RemoteNotification? notification = message.notification;
      AndroidNotification? androidx = message.notification?.android;
      if (notification != null && androidx != null) {
        flutterLocalNotificationsPlugin.show(
          notification.hashCode,
          notification.title,
          notification.body,
          NotificationDetails(
            android: AndroidNotificationDetails(
              'your channel id',
              'your channel name',
              channelDescription: 'your channel description',
              priority: Priority.high,
              importance: Importance.max,
              // Assigning icon to notification
              icon: '@mipmap/ic_launcher',
              // Assigning large icon to notification
              largeIcon: DrawableResourceAndroidBitmap('@mipmap/ic_launcher'),
            ),
          ),
        );
        mIdNotify = message.data['meeting_id'];
      }
      popUpMessage(message.data['meeting_id']);
    });

    print('fmc token  ${box.read('fcm_token')}');
  }

  popUpMessage(mId) async {
    box.write('nMeetingId', mId!);

    await flutterLocalNotificationsPlugin.initialize(initializationSettings,
        onDidReceiveNotificationResponse: notificationTapBackground, onDidReceiveBackgroundNotificationResponse: notificationTapBackground);
  }

  @pragma('vm:entry-point')
  void notificationTapBackground(NotificationResponse details) {
    // handle action

    Future(() async {
    
      await Navigator.push(
          context,
          MaterialPageRoute(
              builder: (context) => MeetingViewPage(
                    meetingId: 600,
                  )));
    });

  }


```

**Comment by MaikuB** [comment]
This isn't a bug as the expectations you've listed aren't based on how the plugin works. Please refer through the docs and example app

**Comment by itsdani121** [comment]
![issue](https://github.com/MaikuB/flutter_local_notifications/assets/30481834/898f5398-ecbc-478f-a5bb-ab0513be273a)

here is in documentation in which it mention to use how to use these plugin function  

![issue](https://github.com/MaikuB/flutter_local_notifications/assets/30481834/ce64b023-61a9-49af-9249-65c7a27d734c)

but it didnot work that's why i create issue. so kindly look into this matter or explain what i missed... @MaikuB

**Comment by itsdani121** [comment]
i also comments on other issues which are closed but didnot get response that's why i create this issue

**Comment by MaikuB** [comment]
The section of the documentation you are looking into is for notification actions, which you don't use at all. That's an explicit section in the readme for what you talked about even https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#handling-notifications-whilst-the-app-is-in-the-foreground. As mentioned earlier please take a careful look at docs and what you're using. I recommend you also run the example app to understand the behaviour

**Comment by itsdani121** [comment]
app run in the foreground properly, when I receive notification it navigates me to a specific screen but the issue came in the background or terminated state, also there is no clearly  explanation about android device. all steps clearly mention above code, and follow as per guidelines.

**Comment by itsdani121** [comment]
all android guidellines are followed here

**Comment by MaikuB** [comment]
All the info is there in the docs and example app. What you spoke about then is covered by
https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#getting-details-on-if-the-app-was-launched-via-a-notification-created-by-this-plugin. I had mentioned looking at the example app as well a number of times but seems like you haven't tried to do so either so please take a look at it

**Comment by sanjaycdev** [comment]
@itsdani121 have you found any solution , am also stuck in the same situation ,

**Comment by itsdani121** [comment]
I uae awesome notification now

**Comment by sanjaycdev** [comment]
Finally i think i have some findings,

**Comment by sanjaycdev** [comment]
After a while i would like to share my findings ,
the onDidReceiveBackgroundNotificationResponse is getting executed only while clicking on notification **Actions** or **attachments** , Tried in my app and also in shared example app , it works the same [Android].
![image](https://github.com/MaikuB/flutter_local_notifications/assets/110217923/02af2f17-69b4-478f-9ec3-255e11c06e3d)

**Comment by MaikuB** [comment]
@sanjaycdev that is correct. This is why I mentioned @itsdani121 expectations weren't correct as they were looking at the documentation that was for notification actions and none of their code used notification actions

**Comment by sanjaycdev** [comment]
**Is there any function which gets executed selecting on notification while app is in terminated state** ? @itsdani121 
i tried with FirebaseMessaging.instance.getInitialMessage() , this doesn't carry payload data its "null" 
Each time i select the notification it triggers the but its returning null.
  final RemoteMessage? _message = await FirebaseMessaging.instance.getInitialMessage();

`"notification" : {
"body" : "test",
"content_available" : true,
"priority" : "max",
"title" : "test",
"image":"https://fastly.picsum.photos/id/612/536/354.jpg?hmac=Q46mJFmXBiIMHIwDHpyVW2eC7hVZB11ag3JpXAglHEk"
},

 "data" : {
 "body" : "test notif",
 "contentavailable" : "true",
 "priority" : "high",
 "title" : "test data"
 }`

if i send notification with `"notification":{}` then its returning the payload , but without `"notification":{}` it returns null

**Comment by itsdani121** [comment]
@sanjaycdev i think @MaikuB  is only person who give answer about this question bcz still i dont get the solution about it , when app is terminate condition how i get notification and navigate it.

**Comment by sanjaycdev** [comment]
hi @MaikuB  I am happy share my solution here :),
So the package provides  getNotificationAppLaunchDetails() which helps to achieve what we are expecting . code below
```
 final NotificationAppLaunchDetails notificationAppLaunchDetails =
      await flutterLocalNotificationsPlugin.getNotificationAppLaunchDetails();

  if (notificationAppLaunchDetails.didNotificationLaunchApp) {
     print('Notification payload: ${notificationAppLaunchDetails.payload}');
}

```
a lot of effort to finally find this single line of code with a lot of satisfaction at the end :). @MaikuB correct me if am wrong

**Comment by MaikuB** [comment]
That is correct. Reminder this plugin is only for local notifications so trying to use this plugin to deal with when a user interacted with a push notification e.g. from FCM won't work. This means if you use FCM, it's plugin is what you should use to deal with notifications from FCM

**Comment by santhoshkumar4035** [comment]
@sanjaycdev
where to use

**Comment by sunil-singh-chaudhary** [comment]
did you find any solution 

> @sanjaycdev where to use this code final NotificationAppLaunchDetails notificationAppLaunchDetails = await flutterLocalNotificationsPlugin.getNotificationAppLaunchDetails();
> 
> if (notificationAppLaunchDetails.didNotificationLaunchApp) { print('Notification payload: ${notificationAppLaunchDetails.payload}'); }

**Comment by TinhHuynh** [comment]
@sunil-singh-chaudhary You can put the code on the first screen of your app.

**Comment by sunil-singh-chaudhary** [comment]
ok thanks for replying the exact problem is i am using {
  "message": {
    "token": "fprLORLLQGGc_luE7YpUjg:APA91bET--hCU5f68JCp",
  
   "data": {
     "channel_id": "channel_id_18",
     "sound": "app_sound",
    "title": "My First Notification",
   "body": "{\"description\": \"Hey you received a chat request from User\", \"notificationType\": 2}"

},
   
  }
} for custom sound ok so the problem with firebase is first time when app is in foreground it will running properly as it is intialized but if first time app is in background then it is playing defualt tone so i changed my api to send in data tag all sound and channel id "data": {
     "channel_id": "channel_id_18",
     "sound": "app_sound",
    "title": "My First Notification",
   "body": "{\"description\": \"Hey you received a chat request from User\", \"notificationType\": 2}"

}, instead of using notification so it is now working fine everywhere except when tap on notification now its now handle by firebase   FirebaseMessaging.onMessageOpenedApp.listen()) i wnat this data payload from notification but while app in foreground again then onDidReceiveNotificationResponse is called but giving wrong formate data like is 


 "{sound: app_sound, body: {\"description\": \"Hey you received a chat request from User\", \"notificationType\": 2}, title: My First Notification, channel_id: channel_id_18}"
[log] payload body "\"{sound: app_sound, body: {\\\"description\\\": \\\"Hey you received a chat request from User\\\", \\\"notificationType\\\": 2}, title: My First Notification, channel_id: channel_id_18}\"" well this is not converting to json frist second now if again app in background then onDidReceiveNotificationResponse is never called dont know what is happening here should i change lib to awsom notification  any idea

**Comment by thiagolioy** [comment]
This is not working.. The callback when the user taps a local notification is not being called. Everything is properly configured. I can send the notifications and tap them. Remote notifications are working fine also. The callbacks for the Flutter local notifications package are not being trigged. What am I doing wrong?


`Future<void> initNotification() async {
    const AndroidInitializationSettings androidInitializationSettings =
        AndroidInitializationSettings("app_icon");

    final DarwinInitializationSettings iOSInitializationSettings =
        DarwinInitializationSettings(
      requestAlertPermission: true,
      requestBadgePermission: true,
      requestSoundPermission: true,
      onDidReceiveLocalNotification: (id, title, body, payload) async {
        debugPrint(
            "onDidReceiveLocalNotification: id: $id, title: $title, body: $body, payload: $payload");
      },
    );

    final InitializationSettings initializationSettings =
        InitializationSettings(
      android: androidInitializationSettings,
      iOS: iOSInitializationSettings,
    );
    await notificationPlugin.initialize(
      initializationSettings,
      onDidReceiveNotificationResponse: ondDidReceiveLocalNotification,
      onDidReceiveBackgroundNotificationResponse:
          ondDidReceiveLocalNotification,
    );

    await notificationPlugin
        .resolvePlatformSpecificImplementation<
            AndroidFlutterLocalNotificationsPlugin>()
        ?.requestNotificationsPermission();

    

    final appNotification =
        await notificationPlugin.getNotificationAppLaunchDetails();
    if (appNotification != null && appNotification.didNotificationLaunchApp) {
      AnalyticsCenter.getInstance()
          .trackEvent('APP_LAUNCHED_BY_LOCAL_NOTIFICATION');

    }
  }`
  
  `@pragma('vm:entry-point')
  static Future<void> ondDidReceiveLocalNotification(
      NotificationResponse notificationResponse) async {
    debugPrint("ondDidReceiveLocalNotification: $notificationResponse");
  }`
  
  `notificationDetails() {
    return NotificationDetails(
        android: AndroidNotificationDetails(
            androidChannelID, androidChannelTitle,
            importance: Importance.max, priority: Priority.high),
        iOS: const DarwinNotificationDetails());
  }

  Future showNotification(
      {int id = 0, String? title, String? body, String? payload}) async {
    return notificationPlugin.show(
        id, title, body, payload: payload, await notificationDetails());
  }`

**Comment by tchouaffe** [comment]
I have the same problem. It is working on ios but not on android.
When the app is close/terminated and a notification is shown, clicking on the notification will direct me to the desired screen on ios. On Android the app gets started and stays at the home screen. I am not using actions.

**Comment by Gonn01** [comment]
> I have the same problem. It is working on ios but not on android. When the app is close/terminated and a notification is shown, clicking on the notification will direct me to the desired screen on ios. On Android the app gets started and stays at the home screen. I am not using actions.

same problem here, navigates to the homescreen

**Comment by Levi-Lesches** [comment]
As mentioned, use `getNotificationAppLaunchDetails()` when your app starts up

**Comment by lukepighetti** [comment]
anyone figure out how to trigger a callback for tapping on a notification (not an action) while the app is already running? @MaikuB i know you say the package doesn't do this but it's a common use case and people are confused by this not working as expected

**Comment by lukepighetti** [comment]
got this working: https://github.com/MaikuB/flutter_local_notifications/issues/1877#issuecomment-2641135728

**Comment by MaikuB** [comment]
@lukepighetti glad to see you got it working but where did you see that I said that use case isn't supported. Like you said, it's a standard use case and is covered in the example app so I doubt I would've said that

**Comment by enginuzunoglu** [comment]
Tapping the notification while the app is open and in the background triggers the app, but it doesn't trigger when it's closed. I found out why. onDidReceiveBackgroundNotificationResponse runs when the notification is tapped, but the app launches before it even has a chance to run. So, you need to ensure the app starts after the triggered function finishes its work.

**Comment by pqt-dev** [comment]
For anyone coming after:
After reading all the comments on this topic, here is what I understand:
`onDidReceiveBackgroundNotificationResponse` is only triggered when you click on actions (e.g., Reply, Mark as read) or attachments.

<img width="294" height="93" alt="Image" src="https://github.com/user-attachments/assets/f6ca9d1a-41ae-4f2b-b45f-cc85322ae0b4" />

If you want to navigate to a specific screen when clicking on a normal notification from a terminated state, use:
```
final NotificationAppLaunchDetails notificationAppLaunchDetails =
    await flutterLocalNotificationsPlugin.getNotificationAppLaunchDetails();

if (notificationAppLaunchDetails?.didNotificationLaunchApp ?? false) {
  print('Notification payload: ${notificationAppLaunchDetails!.notificationResponse?.payload}');
}
```
Then set the initial route accordingly.

**_Summary_**:

- `onDidReceiveNotificationResponse` is triggered when clicking on a normal notification while the app is in the foreground (or background but still running).
- `onDidReceiveBackgroundNotificationResponse`  is triggered when clicking on actions or attachments (e.g., Reply, Mark as read).
- `getNotificationAppLaunchDetails()`  is used to detect if the app was launched by clicking on a normal notification (check the didNotificationLaunchApp flag).

**Please let me known if I missed anything.**
