### ISSUE TITLE
Doesn't work onDidReceiveNotificationResponse

### ISSUE THREAD

**Issue by lcarielo** [MaikuB/flutter_local_notifications#2012]
Hello. When I click the notification, I get this message in the terminal `I/System.out(23765): mbui: onNewIntent`. Doesn't work the `onDidReceiveNotificationResponse`.
How do I fix this problem?
What information do you need about my project (ex: dependences, java version, etc)?

**Comment by MaikuB** [comment]
You would need to provide a link to a repository hosting a minimal app that can reproduce the issue. One way to start is to fork the repo to update the example app. I'd also suggest you cross-reference the app in case there's something that you've missed on this. Another thing I should mention is I've seen is reports on issues where developers are using both push notifications (e.g. via FCM) and local notifications. If you happen to use both then chances are you've confused the two as I've seen it happen where issues are raised and developers don't realise that the notification that has been tapped on is from a push notification. This requires using the associated plugin to handle.

**Comment by bibek-ranjan-saha** [comment]
@lcarielo Were you able to fix it?

**Comment by bibek-ranjan-saha** [comment]
@MaikuB I tried the example app on IOS and Its crashing and Its very critical issue 

Steps to reproduce:
>> Click on "Schedule notification to appear in 5 seconds based on local time zone" button and terminate the app(remove the app from recent)

>> once you receive notification after 5 seconds click on it

Finally -> app will crash at this point

**Comment by MaikuB** [comment]
@bibek-ranjan-saha unless you can provide evidence of there being a legitimate issue, it should mean you've done something wrong or missed something. One thing I should call out is that it is mentioned that you cannot just copy and paste the Dart code to your app and expect it to work. The following is a recording on iOS that shows it is working fine


https://github.com/MaikuB/flutter_local_notifications/assets/25263378/9a2d6978-920a-4fc5-8659-ec0965251af4

**Comment by MaikuB** [comment]
Closing this due to lack of response with link to a repo hosting a minimal app that can reproduce the issue
