### ISSUE TITLE
flutter_local_notifications and aliyun_push don't work together

### ISSUE THREAD

**Issue by eatfishs** [MaikuB/flutter_local_notifications#2017]
**Describe the bug**
On the IOS side, when flutter_local_notifications is used together with aliyun_push, the notification cannot be displayed normally, and the log of aliyun_push is triggered

**To Reproduce**
Install aliyun_push

  const iOS = DarwinNotificationDetails(
      categoryIdentifier: darwinNotificationCategoryText,
    );
    const NotificationDetails platformChannelSpecifics =
        NotificationDetails(android: androidPlatformChannelSpecifics, iOS: iOS);
    await flutterLocalNotifications.show(
        id ?? notificationId, title, content, platformChannelSpecifics,
        payload: payload);

**Expected behavior**
No notification pops up and aliyun_push logs appear
![image](https://github.com/MaikuB/flutter_local_notifications/assets/45836182/ddbde456-99ff-40c0-a9cd-8a923b72a167)

**Comment by MaikuB** [comment]
This is something you would need to look into further yourself. The other plugin has most likely decided to override any notification handling and have seen such issues before that requires other plugins to make changes to their own implementation
