### ISSUE TITLE
when tap on notification app return to home screen

### ISSUE THREAD

**Issue by heshesh2010** [MaikuB/flutter_local_notifications#2020]
Hi , 
I'm using latest local notification plugin version , 

when I tap on notification when app is foreground and navigate to login screen , I see app returned again to home screen ! 

here is my Getx service class :

   class FireBaseMessagingService extends GetxService {
  final _instance = FirebaseMessaging.instance;
  final FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
      FlutterLocalNotificationsPlugin();

  final channel = const AndroidNotificationChannel(
    'high_importance_channel', // id
    'High Importance Notifications', // title
    description:
        'This channel is used for important notifications.', // description
    importance: Importance.max,
  );

     Future<FireBaseMessagingService> init() async {
    requestPermission();

    initLocalNotification();

    final initMessage = await _instance.getInitialMessage();
    if (initMessage != null) {
      _newMessageNotification(initMessage);
    }

    print("FCM token: ${await FirebaseMessaging.instance.getToken()}");
    await fcmOnMessageListeners();
    return this;
  }

     Future<bool> requestPermission() async {
    if (kIsWeb) {
      return false;
    }

    FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
        FlutterLocalNotificationsPlugin();
    flutterLocalNotificationsPlugin
        .resolvePlatformSpecificImplementation<
            AndroidFlutterLocalNotificationsPlugin>()
        ?.requestPermission();

    await FirebaseMessaging.instance
        .setForegroundNotificationPresentationOptions(
      alert: true, // Required to display a heads up notification
      badge: true,
      sound: true,
    );
    FirebaseMessaging.instance.requestPermission(
        sound: true, badge: true, alert: true, provisional: true);

    /// Case unknown - First time open the app
    var granted = (await NotificationPermissions.requestNotificationPermissions(
          iosSettings: const NotificationSettingsIos(
            sound: true,
            badge: true,
            alert: true,
          ),
        )) ==
        PermissionStatus.granted;

    /// To support POST_NOTIFICATION on Android 13.
    /// Requires permission_handler 10+.
    if (UniversalPlatform.isAndroid) {
      granted = (await ph.Permission.notification.request()) ==
          ph.PermissionStatus.granted;
    }

    return granted;
  }

      Future fcmOnMessageListeners() async {
    FirebaseMessaging.onMessage.listen((RemoteMessage message) {
      final notification = message.notification;
      final android = message.notification?.android;
      if (notification != null &&
          android != null &&
          UniversalPlatform.isAndroid) {
        flutterLocalNotificationsPlugin.show(
          notification.hashCode,
          notification.title,
          notification.body,
          NotificationDetails(
            android: AndroidNotificationDetails(
              channel.id,
              channel.name,
              channelDescription: channel.description,
              icon: android.smallIcon,

              // other properties...
            ),
            iOS: const DarwinNotificationDetails(),
          ),
          payload: jsonEncode(message.data),
        );
      } else if (notification != null && UniversalPlatform.isIOS) {
        flutterLocalNotificationsPlugin.show(
          notification.hashCode,
          notification.title,
          notification.body,
          payload: jsonEncode(message.data),

          NotificationDetails(
            android: AndroidNotificationDetails(
              channel.id,
              channel.name,
              channelDescription: channel.description,
              icon: android?.smallIcon,
              // other properties...
            ),
            iOS: const DarwinNotificationDetails(),
          ),
          // payload: 'Notification'
        );
      }
    });
  }

      Future<void> setDeviceToken() async {
    await FirebaseMessaging.instance.getToken();
  }

      void _newMessageNotification(RemoteMessage message) {
    RemoteNotification? notification = message.notification;

    Get.showSnackbar(notificationSnackBar(
      title: notification?.title ?? "",
      message: notification?.body ?? "",
    ));
  }

     void initLocalNotification() {
    flutterLocalNotificationsPlugin
        .resolvePlatformSpecificImplementation<
            AndroidFlutterLocalNotificationsPlugin>()
        ?.createNotificationChannel(channel);
    const AndroidInitializationSettings initializationSettingsAndroid =
        AndroidInitializationSettings('launcher_icon');

    final InitializationSettings initializationSettings =
        InitializationSettings(
      android: initializationSettingsAndroid,
      iOS: initializationSettingsDarwin,
    );

      flutterLocalNotificationsPlugin.initialize(initializationSettings,
        onDidReceiveBackgroundNotificationResponse: notificationTapBackground,
        onDidReceiveNotificationResponse: onDidReceiveNotificationResponse);
  }

  final DarwinInitializationSettings initializationSettingsDarwin =
      DarwinInitializationSettings(
    requestSoundPermission: false,
    requestBadgePermission: false,
    requestAlertPermission: false,
    onDidReceiveLocalNotification: onDidReceiveLocalNotification,
  );

      @pragma('vm:entry-point')
      static notificationTapBackground(NotificationResponse notificationResponse) {
    if (notificationResponse.payload != null) {
      Notification payload = Notification.fromJson(
          json.decode(notificationResponse.payload ?? ""));
      Get.toNamed(
        Routes.sardComments,
        arguments: {
          "sardId": payload.parentDetails?.parentId,
          "listType": "home",
        },
      );
    }
  }

  static onDidReceiveNotificationResponse(
      NotificationResponse notificationResponse) async {
    if (notificationResponse.payload != null) {
      Notification payload = Notification.fromJson(
          json.decode(notificationResponse.payload ?? ""));
      ;
      switch (payload.event) {
        case "reacted.on.post":
          Get.toNamed(
            Routes.sardComments,
            arguments: {
              "sardId": payload.parentDetails?.parentId,
              "listType": "home",
            },
          );

          break;
      }
    }
  }

  static onDidReceiveLocalNotification(
      int id, String? title, String? body, String? payload) async {
    Get.showSnackbar(notificationSnackBar(
      title: title ?? "",
      message: body ?? "",
    ));
  }
}

main.dart file 

```
void main() async {
  HttpOverrides.global = MyHttpOverrides();

  WidgetsFlutterBinding.ensureInitialized();

  SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(
    systemNavigationBarIconBrightness: Brightness.light,
    systemNavigationBarDividerColor: Colors.black54,
    statusBarColor: pageBackgroundColor,
    statusBarIconBrightness: Brightness.dark,
    statusBarBrightness: Brightness.light,
  ));

  await Firebase.initializeApp();

  await account.getPreferences();
  SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp])
      .then((_) {
    runApp(MyApp());
  });
}

```
```
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ScreenUtilInit(
        designSize: const Size(430, 979),
        minTextAdapt: true,
        splitScreenMode: true,
        builder: (context, child) {
          return GetMaterialApp(
            onReady: () async {
              await Get.putAsync(() => FireBaseMessagingService().init());
            },
            title: 'Siyaq',
            navigatorKey: Get.key,
            debugShowCheckedModeBanner: false,
            // localizationsDelegates:
            locale: Locale(account.language),
            translations: Translation(),
            //    initialBinding: HomeBinding(),
            getPages: AppPages.routes,
            fallbackLocale: const Locale('ar', 'SA'),
            theme: ThemeData(
                primarySwatch: Colors.blue,
                fontFamily: Get.locale?.languageCode == "en"
                    ? "IBMPlexSans"
                    : "IBMPlexSansArabic",
                appBarTheme: AppBarTheme(
                  titleTextStyle: TextStyle(
                    fontFamily: Get.locale?.languageCode == "en"
                        ? "IBMPlexSans"
                        : "IBMPlexSansArabic",
                  ),
                  color: Colors.white,
                )),

            home: SplashScreen(),
          );
        });
  }
}   
```

**Comment by MaikuB** [comment]
Navigation is implemented by apps not this plugin so it's up to you to debug further into what is happening
