### ISSUE TITLE
Support Android setSilent(boolean) functionality

### ISSUE THREAD

**Issue by TheFinestArtist** [MaikuB/flutter_local_notifications#2021]
**Describe the bug**
Support Android [setSilent(boolean)](https://developer.android.com/reference/androidx/core/app/NotificationCompat.Builder#setSilent(boolean)) functionality

**Comment by MaikuB** [comment]
Could you please look at submitting a PR for this?

**Comment by aa-euclidk** [comment]
I made a PR with minimal changes here: https://github.com/MaikuB/flutter_local_notifications/pull/2102

I also wanted to use the Android setSilent functionality. My use case was that I wanted to play a notification with sound for the first time but then silence subsequent notifications after the notification channel was created.

**Comment by TheFinestArtist** [comment]
I just found the update here. I wonder if @MaikuB want to use `playSound` to support `setSilent` or let `setSilent` has its own method?

**Comment by MaikuB** [comment]
It should be separate as one is associated with a notification channel and another is associated with a notification.

**Comment by TheFinestArtist** [comment]
Thank you for the quick answer @MaikuB!

Hi @aa-euclidk, would you be interested in updating your pull request #2102? You can reference this [commit](https://github.com/SleepTimer/flutter_local_notifications/commit/c848041688c3da345c14540b3a8b86f5068a6c6f) if you want. You might also need to make some tests [here](https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/test/android_flutter_local_notifications_test.dart).

**Comment by aa-euclidk** [comment]
I agree that silent should be separate from playSound. Thanks for providing your commit. I will write some tests soon.

**Comment by aa-euclidk** [comment]
Hi @TheFinestArtist, @MaikuB,

I have updated my fork with unit tests added for the non default "silent" option.

Thanks again, @TheFinestArtist

**Comment by TheFinestArtist** [comment]
Thank you @aa-euclidk for the quick update.

Your PR looks amazing to me. 

I left a few comments on your PR to make the review quick and easy.

**Comment by MaikuB** [comment]
Fyi I'll be going on holidays so you may need to use a fork if you're in urgent need of this functionality

**Comment by TheFinestArtist** [comment]
Thank you for the heads-up. Happy holidays!

**Comment by TheFinestArtist** [comment]
Thank you for the support!

**Comment by MaikuB** [comment]
Thanks for closing this. Forgot there was an issue raised to close this that related to the PR that I could've also mentioned in the changeling
