### ISSUE TITLE
Scheduled notification custom sound issue 

### ISSUE THREAD

**Issue by wepashka** [MaikuB/flutter_local_notifications#2027]
I scheduled notifications by setting custom sound after that I scheduled another notification with other custom sound . The issue is the second notification's sound is the same with the oldest one; How to solve the issue

**Comment by MaikuB** [comment]
My guess is if you saw this on Android is that you used the same notification channel. If you looked at the official docs around Android notifications or for this plugin, you should see that it's mentioned that sound is tied to a notification channel as this is how the native Android APIs work

**Comment by hrshere** [comment]
@MaikuB what could be the fix for this...as i have option in my flutter app that user can select sound and mode from UI and reschedule notification....but the sound and mode remains same as it was for the first time

**Comment by hrshere** [comment]
@MaikuB, in the android docs, https://developer.android.com/develop/ui/views/notifications/channels#ReadChannel, and https://developer.android.com/develop/ui/views/notifications/channels#UpdateChannel, does that provide a way to update the notification features??
If yes, how can i do that using flutter_local_notification package. or maybe if i should look for some other package to achieve this task??
any kind of information or guidance will count.  Thankyou!

**Comment by hrshere** [comment]
moreover, a limitation, as far as i understand, https://pub.dev/packages/flutter_local_notifications#scheduled-android-notifications, that has been mentioned. Does this anyhow talk about this issue??

**Comment by MaikuB** [comment]
@hrshere per the docs you've linked, they explicitly say

> After you create a notification channel, you can't change the notification behaviors. The user has complete control at that point. However, you can still change a channel's name and description.

This means programatically, the only thing Android allows to be changed is the channel's name and description. This isn't a plugin limitation but how Android itself works. This means you can't change the sound for the channel. You would need to find another way to tackle this (e.g. create another channel) and if you can't then you may need to consider dropping the feature from your app.

Closing this issue as OP hasn't replied further and what I've shared was likely the issue

**Comment by hrshere** [comment]
@MaikuB thanks for the clarification buddy.
