### ISSUE TITLE
No custom actions on iOS

### ISSUE THREAD

**Issue by smolikja** [MaikuB/flutter_local_notifications#2028]
**Describe the bug**
Custom notifications does not work on the iOS. Demonstrated with the [example](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications/example) app

**To Reproduce**

1. Flutter 3.10.5
2. Xcode 14.3.1
3. iOS 16.4
4. flutter_local_notifications: ^14.1.1
5. [example app](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications/example)
6. See error

**Expected behavior**
show notification actions as is on the Android

https://github.com/MaikuB/flutter_local_notifications/assets/35193095/cfb20f26-4009-4fef-961e-e3bcdbb0663a

**Comment by MaikuB** [comment]
I'm guessing you thought that actions would show up on the notification tile itself. If you looked at the official docs from Apple e.g. https://developer.apple.com/documentation/usernotifications/declaring_your_actionable_notification_types you'll see that is not how they work. What you're missing is you have to tap and hold on the notification "tile" to bring up those buttons

**Comment by smolikja** [comment]
> I'm guessing you thought that actions would show up on the notification tile itself. If you looked at the official docs from Apple e.g. https://developer.apple.com/documentation/usernotifications/declaring_your_actionable_notification_types you'll see that is not how they work. What you're missing is you have to tap and hold on the notification "tile" to bring up those buttons

Thanks! The iOS UX is not native much obvious in this:)

**Comment by tashigeekyants** [comment]
This is fine for normal notification but what if we have a call incoming, we should show custom action in the tile itself, isn't it?

**Comment by MaikuB** [comment]
It sounds like there's some confusion so to be clear, what you see is what you get because this is how Apple has done the experience for notifications. It's not because of how the plugin implemented notifications. This is one of the reasons why developers should first understand each platform deals with notifications before looking at the plugin

**Comment by tashigeekyants** [comment]
Thanks for the clarification @MaikuB
