### ISSUE TITLE
onDidReceiveNotificationResponse is not returning callback on ios simulator

### ISSUE THREAD

**Issue by manisha-am** [MaikuB/flutter_local_notifications#2029]
Issue: onDidReceiveNotificationResponse not being called on iOS Simulator when clicking on push notifications

Description:
I have configured my iOS app to handle push notifications, including implementing the onDidReceiveNotificationResponse function to handle notification responses. However, when I run my app on the iOS Simulator and tap on a push notification, the onDidReceiveNotificationResponse function is not triggered.

Expected Result:
The onDidReceiveNotificationResponse function should be called, and I should see the corresponding print statements or any desired behavior implemented within the function.

Actual Result:
The onDidReceiveNotificationResponse function is not called when I tap on the simulated push notification. There are no print statements or any indication that the function is triggered.

Environment:

Xcode version: xcode 14
iOS version running on the simulator: 16.4

Please let me know if there's anything I'm missing from my side.

**Comment by MaikuB** [comment]
You need to provide a link to repository hosting a minimal app that can reproduce the issue using only this plugin. This way it will provide evidence that there's an issue with the plugin. Please ensure you have checked that you have done all the setup mentioned in the readme and can use the example app to cross-reference before doing so. Should you actually be using push notifications as you say, then note that those are different from local notifications. For example, if you use FCM, the FCM plugin is what will handle when a push notification is clicked/tapped on. It won't be this plugin as this plugin is purely for local notifications

**Comment by eijiotieno-official** [comment]
how can I launch/open the app once the action button is tapped
