### ISSUE TITLE
whats the callback when user clicks on notification?

### ISSUE THREAD

**Issue by Kavinkumarsimple** [MaikuB/flutter_local_notifications#2030]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Sample code to reproduce the problem**

**Comment by Kavinkumarsimple** [comment]
when user click on a notification i want to trigger an event like open a new screen based on the notification payload

**Comment by MaikuB** [comment]
`onDidReceiveNotificationResponse`. This was mentioned in the readme at https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#initialisation so please take a closer look at the readme and cross reference with the example app if you have questions on functionality

**Comment by eijiotieno-official** [comment]
Thanks, I had missed some implementation
