### ISSUE TITLE
Progress Bar Color & Icon Color

### ISSUE THREAD

**Issue by Ladeed** [MaikuB/flutter_local_notifications#2031]
Once I added icon and progress bar over notification, then i tried to change the progress bar color. on that time icon color also changing to the progress color. how can i assign color only for progress bar

**Comment by MaikuB** [comment]
This is something you would need to do your own research on to see if it's even possible. The purpose of the plugin is to be a wrapper to access the native notification APIs. This means developers still need to understand how notifications work on each platform
