### ISSUE TITLE
Accessing notifications settings

### ISSUE THREAD

**Issue by jesusrp98** [MaikuB/flutter_local_notifications#204]
Add a method that, when called, opens the notification settings page for the specific app. It could be implemented for both Android & iOS.

Would it be possible to add? It'd be great!

**Comment by MaikuB** [comment]
This sounds like something that could be better in a separate plugin for handling app settings. In fact, there appears to be one already 
https://pub.dartlang.org/packages/system_setting

**Comment by jesusrp98** [comment]
I'm sorry I took so long to answer. I used that package you recommended to me.
Thanks for all. Great job with this awesome package!
