### ISSUE TITLE
custom actions not showing in iOS on long press notification when device is in background or teminated state

### ISSUE THREAD

**Issue by CodingWithTashi** [MaikuB/flutter_local_notifications#2043]
**Describe the bug**
In iOS, custom action will be display on long press on notification and it is working fine when app is in foreground. but When the application is in the background or terminated state. Though I receive notification but the action are not displaying on long pressed.

**To Reproduce**
I have used the same example app.

**Expected behavior**
I am expecting to see the same action list as mentioned when app is in background or terminated https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#notification-actions

**Comment by MaikuB** [comment]
Long press only works when the notification first appears with the notification banner/alert/tile at the top of the screen. I'm guessing you've confused foreground/background with where the notification appears to interact with it that what you called background is when you interact with the notification in the notification centre. Long press doesn't work there and is to do with how Apple designed it, you have to swipe to get access to eventually see the actions

**Comment by CodingWithTashi** [comment]
Hi @MaikuB ,
Thanks for the quick response. I am sharing a demo video of the issue I am facing. please take a look and let me know.

1. First part show a notification with action when the app is in the foreground
2. Second part show a notification with action when the app is terminated

https://github.com/MaikuB/flutter_local_notifications/assets/25583737/60427527-22b7-48b4-b8a9-d9f608c54794

Feel free to close the issue if this is how expected to work.

Thanks
