### ISSUE TITLE
badge count in which devices supported in automatically 

### ISSUE THREAD

**Issue by krupalieBizTrait** [MaikuB/flutter_local_notifications#2045]
badge count or new notification dot not comming in ios device

**Comment by MaikuB** [comment]
What is it you're trying to say as what you've written doesn't make sense

**Comment by nhatvu95** [comment]
@MaikuB MAi
Android when the device receives a notification Icon app has a badge count, But Ios is not.?

**Comment by nhatvu95** [comment]
But how can listener notification(zonedSchedule) send when the app is killed to updateBadgeCount?

**Comment by MaikuB** [comment]
This is something you will likely need your own solution for. The plugin may not solve for all your scenarios that you can fork and modify appropriately for your needs as some apps may choose to set the badge count beyond simple rules beyond incrementing. If you or someone in the community were to help contribute to https://github.com/MaikuB/flutter_local_notifications/issues/1699, then this may allow for functionality to be notified when a notification is shown that the other plugin for managing badge count can be used.

Note that from the iOS/macOS side, Apple's APIs for setting the badge is done via an API that is tied to the application, it isn't part of their notifications API. Furthermore, the API is requires the person calling to specify the exact number to set the badge count to, it isn't an API that allows the caller to, say, increment the badge count. This is further complicated by how some applications may have push notifications where an app then needs to track the number of push notifications and local notifications

**Comment by nhatvu95** [comment]
My question like this.
https://github.com/MaikuB/flutter_local_notifications/pull/876#issuecomment-860034132

**Comment by MaikuB** [comment]
If you're asking the question then you haven't understood what I had written. I suggest you reread what I wrote earlier to understand it properly. If you still don't understand it with your English skills then unfortunately can't help much further there
