### ISSUE TITLE
Grouping scheduled notifications

### ISSUE THREAD

**Issue by daniel1414** [MaikuB/flutter_local_notifications#2047]
Hi, first of all, **great plugin**, and thank you for it!

In my app I have a page where the user can schedule notifications that repeat on a weekly basis. It's a common thing to schedule them so that there are around 10 notifications daily. 

The thing is that I can't seem to group them on Android. I've tried setting the **groupKey**, but on it's own it doesn't group notifications (at least in Android 13). They do group however when I specify **setAsGroupSummary**, but it has to be only one of them and that can't be determined at the time of scheduling the notifications. 

So I'm ending up with scheduled notifications that don't group together in the notification panel, is there already a solution for that?

Thanks,
Daniel

**Comment by daniel1414** [comment]
2 seconds after submitting this issue I found a workaround just to dismiss the notifications after a time period that can be determined upfront :D The issue is still valid though

**Comment by MaikuB** [comment]
From what I could gather on what you're describing, this isn't a plugin issue and something you would need to do research into on solving for your app. The need for a group summary is based on what Android provides and the readme has a snippet and link to official Android docs on this. For convenience it's https://developer.android.com/develop/ui/views/notifications/group. You'll need to understand how notifications work on the platform and see if the available functionality exposed by the platform's APIs allow you to do what is needed. If not, you may need to change the experience of your app

**Comment by daniel1414** [comment]
Yeah, it doesn't seem like Android supports what I have in mind apart from an automatic grouping of notifications. Thanks the answer!
