### ISSUE TITLE
App crashing on Android with type java.lang.RuntimeException. Possibly related to small icon

### ISSUE THREAD

**Issue by RishiKar** [MaikuB/flutter_local_notifications#2049]
**Describe the bug**
Hi, thank you for this wonderful package. I have been having app crashes related to using local notifications and I am trying to figure out where am I going wrong. 
The crash logs from Google Play state the following

Type: `java.lang.RuntimeException`
Details:
```
Exception java.lang.RuntimeException: Unable to start receiver com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:4357)
  at android.app.ActivityThread.access$1700 (ActivityThread.java:253)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2101)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:201)
  at android.os.Looper.loop (Looper.java:288)
  at android.app.ActivityThread.main (ActivityThread.java:7880)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:568)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1045)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
  at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.setSmallIcon
  at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification
  at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification
  at com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver.onReceive
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:4348)
```

**Sample code or usage in my app**
```
const androidInitSettings =
        AndroidInitializationSettings('@drawable/ic_stat_6000');
    const initializationSettings = InitializationSettings(
        android: androidInitSettings, iOS: iOSInitSettings);
    await flutterLocalNotificationsPlugin.initialize(initializationSettings,
        onSelectNotification: (payload) async {
      onPromiseNotificationTap.add(payload);
    });
```

I have included the ic_stat_6000.png in the relevant drawable folders.
Could you please help?

**Comment by MaikuB** [comment]
I suspect you haven't fully completed the [release build configuration](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#release-build-configuration). Please check this thoroughly and you can try to confirm the issue on your end by generating a release build of your app. This should be done as part of regular dev/testing processes prior to publishing to the store. Testing shouldn't be done via debug builds if that happened to be how it was done

**Comment by RishiKar** [comment]
Hi, Sorry, this took a long time to get back to. I am going to test this properly once again and then close it if this is indeed the fix. I really appreciate your quick response. Thanks again

**Comment by MaikuB** [comment]
I'm going to close in the mean time as this has always the issue and no one has proven otherwise. Your reply would suggest you hadn't originally followed these steps as well. You can reopen the issue if you still have a problem but if you do so, you'll need to provide a link to a repository hosting a minimal app that can reproduce the problem. A reminder that there's an example app in this plugin's repo as well so you can try to reproduce it through it
