### ISSUE TITLE
Few doubts over scheduling notifications 

### ISSUE THREAD

**Issue by milindgoel15** [MaikuB/flutter_local_notifications#2056]
Issue 1:
So when creating a function that creates a zonedSchedule notification, we have to provide some id in the type of integer. Suppose we gave the id of 0 as a constant value, so when we create a task for a specific date and time, the notification is created. 

But when we create another task on a different date and time under the same id of 0, does the previously scheduled notification get overwritten? Or they both get scheduled and occur according to their scheduled time?

I didn't test this exact behaviour till now. And I used a random() function to create random IDs for each notification that gets created. But this method is not so good as we cannot know for sure which notification we can cancel using the cancel function.

Edit: I tested using only 0 for scheduling multiple tasks and it does overwrite the previously scheduled task. Please suggest a some approach to deal with. For context, i have a todo app that can schedule todos for specific date and time.

Edit 2: I moved my zonedSchedule function to accept the item's index value for scheduling notifications. However, i was looking for a way to schedule a notification before an item is created. I was able to do that using a random integer but was not able to cancel them individually unless i store that random integer along with the item. 

~Issue 2:~
~I am not sure I should ask it here or not. It's related to the notification icon. I have added a monochrome based XML in 24dp by 24dp. But it shows a small icon in the notification.~

Edit:nvm i fixed this issue.

Please suggest thanks.

**Comment by MaikuB** [comment]
If you need to avoid notifications being overwritten then that would mean you have to have some form of tracking so the app knows notifications have been scheduled and the corresponding IDs. The approach to do this is something you'd have to come up that is specific to app and outside of the plugin. Given GitHub is more for when someone has an issue/bug with libraries etc, if you need ideas then it's better to go to places like Slack, Discord etc that allows for more open conversations
