### ISSUE TITLE
get notification when the phone is connected 

### ISSUE THREAD

**Issue by zakihou** [MaikuB/flutter_local_notifications#2059]
****When the phone is not connected to the Internet and the application is closed
And we send 5 different messages from
firebase
When the phone regains internet connection, only the last sent message arrives
Is there a way
to retrieve the other 4
Is there a way when the phone reconnects to the internet it will be able to retrieve the notifications sent to it when it was offline 
Firebase 
flutter****

**Comment by MaikuB** [comment]
Your concern relates to Firebase Cloud Messaging so isn't to do with this plugin that is for local notifications. You'll need to ask this question elsewhere
