### ISSUE TITLE
No such module 'flutter_local_notifications' - Xcode

### ISSUE THREAD

**Issue by graweb** [MaikuB/flutter_local_notifications#2061]
Hi.
I am trying to publish IOS but the Xcode show me this error No such module 'flutter_local_notifications'.

Could you help me?

<img width="1468" alt="Captura de Tela 2023-07-28 às 20 50 04" src="https://github.com/MaikuB/flutter_local_notifications/assets/12503317/b5fd8444-7f8c-4a15-9c53-aa6fd46530aa">

**Comment by MaikuB** [comment]
Not sure what is happening here and no-one else has reported this before. My best guess is you haven't properly added the plugin to your app yet and that's why it's not been able to resolve this. You may need to get help from someone through places like Slack, Discord etc if the problem persists so they can walk through your app. This isn't something I have capacity to help with

**Comment by urmamb** [comment]
same issue happens to me.

**Comment by graweb** [comment]
> same issue happens to me. @graweb any work arround?

Hi @urmamb.
Yes, I did some steps to resolve.

1 - In IOS folder, remove the file Podfile.lock
2 - Open the Podfile and remove the comment this line `platform:ios, '11.0'`
3 - Add a comment on this lines (this step resolve new error when you was upload the app)
```
#target 'RunnerTests' do
#inherit! :search_paths
#end
```
4 - Run `flutter clean` (out ios folder)
5 - Run `flutter pub get` (out ios folder)
6 - Into IOS folder, run `sudo gem install cocoapods`
7 - Into IOS folder, run `pod install`
8 - Into IOS folder, run `flutter build ios`

After this steps, now it's ok ;)

**Comment by holy-dev** [comment]
It's happening again and workaround is not working

**Comment by graweb** [comment]
Hi @holy-dev 
I didn't find other solution :(

Recently, I updated the Flutter SDK but I don't have any problem.

Do you use the last version of Flutter?

**Comment by Fintasys** [comment]
Exactly same problem. I follow all steps described in the ReadMe and tried the solutions described here, but no success. 😢

**Comment by A-EL** [comment]
faced the exact same problem with new flutter project.

**Comment by andywetherell** [comment]
Same issue without a clear solution. Seems like a common issue across other threads. 

Can confirm it is all installed properly as well because others in our team have it build fine and it releases fine to iOS. Does anyone know of any good resources to get a better grasp of exactly what xCode is doing when it runs a build so that we can build a more systematic approach to debugging?

**Comment by gavinuhran** [comment]
Same issue here. Feels like I've tried everything

**Comment by gavinuhran** [comment]
@holy-dev @Fintasys @A-EL @andywetherell 

Were any of you able to resolve your issue?

**Comment by Fintasys** [comment]
In my case it was a typo (missing s in import) otherwise it worked fine 😅

**Comment by andywetherell** [comment]
> @holy-dev @Fintasys @A-EL @andywetherell
> 
> Were any of you able to resolve your issue?

Not by doing anything systematically unfortunately.  Eventually, the error stopped being thrown but I didn't change anything, XCode being its usual temperamental self.

**Comment by jatinchaudhary** [comment]
Try running the IOS build from Flutter console it will automatically get all the cocoa pods and will update the pods after that you can use code to build, THIS FIX THE ISSUE IN MY CASE

**Comment by MaikuB** [comment]
Good call out @jatinchaudhary.  It looks like those who have this issue haven't had the build system execute to resolve app the dependencies properly or have had issues with the iOS that needs to be resolved that isn't a plugin-specific issue

**Comment by YuDavidCao** [comment]
I had the same issue but fixed it by first cd into the ios folder and do "pod update"

**Comment by ladzar** [comment]
For other when they stumble here like I did: be sure to use Runner.xcworkspace file and not the Runner.xcodeproj to open the app in Xcode
