### ISSUE TITLE
Run zonedSchedule only once

### ISSUE THREAD

**Issue by mahmood2772** [MaikuB/flutter_local_notifications#2069]
In my application, there is a notification that should be displayed at 9:30 every day, but when I use zonedSchedule, this notification is executed only once.

var now = DateTime.now();
var dateTime = DateTime(now.year,now.month,now.day,9,30);

flutterLocalNotificationPlugin.zonedSchedule(
      0,
      title,
      body,
      TZDateTime.from(dateTime, local),
      await notificationDetails,
      uiLocalNotificationDateInterpretation:
      UILocalNotificationDateInterpretation.absoluteTime,androidScheduleMode: AndroidScheduleMode.alarmClock,);

**Comment by milindgoel15** [comment]
Zoned schedule is used to scheduling a notification that appear at a very specific future time. Its not used for setting up periodic job. You have to add some background job scheduler methods using work manager or alarm manager or any other method that posts a notification after a time every day.

**Comment by MaikuB** [comment]
This is happening as your code has only specified to show a notification once. Please check the example app, API docs (e.g. https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/FlutterLocalNotificationsPlugin/zonedSchedule.html) and readme as they explain how to do a daily notification. If you've missed then I would suggest checking the docs further in case you have missed more information that is useful to ensure the app builds/runs properly
