### ISSUE TITLE
Cancel notification when when app is killed by swiping (force kill app) on android

### ISSUE THREAD

**Issue by dokhanhvu** [MaikuB/flutter_local_notifications#207]
Hi MaikuB, thank for your great work,
Can u add an option to create a Service for canceling notification when the app is killed on multitask panel? When I create an ongoing notification with autoCancel is false, there is no way to cancel it when force kills the app.

**Comment by MaikuB** [comment]
there are few things that need to be considered here

- https://developer.android.com/reference/android/app/NotificationManager#getActiveNotifications() is only supported in API level 23 onwards. This plugin is using the [NotificationManagerCompat](https://developer.android.com/reference/androidx/core/app/NotificationManagerCompat?hl=en) class to provide backwards compatibility and a similar method isn't available
- this means that the plugin would need to keep track of ongoing notifications that have been triggered through something like shared preferences. however, not everyone needs this functionality (and not everyone ongoing notification may need to be dismissed when the app is closed

as a result what i'm thinking is
- add an `cancelOnAppTermination` flag to the [AndroidNotificationDetails](https://github.com/MaikuB/flutter_local_notifications/blob/master/lib/src/platform_specifics/android/notification_details.dart) class. this flag indicates that the notification should be cancelled when the app has been killed and is used for any Android notification, not just ongoing ones. it helps indicate to the plugin the state it needs to track via shared preferences
- service class will go through the shared preferences to see if there are notifications it should cancel when onTaskRemoved() is fired

how does that sound? feel free to make suggestions on how to make it better. happy to take a PR that implements this as well

**Comment by carlosbz** [comment]
Hi MaikuB, thanks for this amazing flutter plugin.

I really need this functionality. I was trying to add a cancelOnAppTermination flag without success. 

I have add it as a boolean var like this

bool cancelOnAppTermination;

Also add it to the function and the map in the AndroidNotificationDetails.

Could you be more specific about how to do this? Thanks.

**Comment by MaikuB** [comment]
I don't have much more specifics to provide as it's not something I've gotten to look into much besides what I posted above. Generally idea is either the app or plugin needs to know when it's being killed. For plugins, I believe you can register to get callbacks for various activity lifecycle events. Some of the official/first-party plugins do this (e.g. see [here](https://github.com/flutter/plugins/blob/master/packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerPlugin.java)). If you do get this working then I'd be happy to look at PR for this

**Comment by carlosbz** [comment]
I will update in case I manage to get this done. Thanks MaikuB.

**Comment by MaikuB** [comment]
Closing this as I don't see myself getting to implement this. PRs from the community are welcome should someone come up with a solution that they want to contribute

**Comment by drifty005** [comment]
I'm late but my workaround is to use ```timeoutAfter: 2500,``` in the notification settings and a 2s timer with the ```.show``` command inside, the notification disappear only when the app is swiped from the overview...
