### ISSUE TITLE
67 duplicate symbols for architecture x86_64

### ISSUE THREAD

**Issue by superleexpert** [MaikuB/flutter_local_notifications#2072]
install in flutter pub
  flutter_local_notifications: ^9.9.1

Xcode :
67 duplicate symbols for architecture x86_64
Linker command failed with exit code 1 (use -v to see invocation)

How to fix it?  

Thanks

**Comment by MaikuB** [comment]
Not sure about this. It could be that this is because referencing a very old version that isn't compatible with the tooling you're using. This is something you would need to look into yourself
