### ISSUE TITLE
click on notification when app is closed , do not open target screen just open home screen. but when app is in background it worked well

### ISSUE THREAD

**Issue by mosayeb-masoumi** [MaikuB/flutter_local_notifications#2073]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Sample code to reproduce the problem**

**Comment by ItayBarFaye** [comment]
I also encounter similar issue but for me only happen in IOS in every app state

**Comment by MaikuB** [comment]
If you're going to file a bug report then you'll need to provide a link to a repo hosting a minimal app that can reproduce an issue. Please also ensure you've checked the example app to be about to reproduce the issue. This is mentioned in the bug report template

**Comment by under3415** [comment]
Do you have this code in `main.dart`?

```
 String initialRoute = '/';
  final NotificationAppLaunchDetails? notificationAppLaunchDetails =
      await flutterLocalNotificationsPlugin.getNotificationAppLaunchDetails();
  bool didNotificationLaunchApp =
      notificationAppLaunchDetails?.didNotificationLaunchApp ?? false;

  if (didNotificationLaunchApp) {
    initialRoute = '/special_screen';
  }
```

**Comment by MaikuB** [comment]
Closing this as OP hasn't responded. Suspect what @under3415 has mentioned is what the OP is missing
