### ISSUE TITLE
Flutter local notification not working in release mode

### ISSUE THREAD

**Issue by Souhaibbek** [MaikuB/flutter_local_notifications#2074]
```
I'm using flutter_local_notification show() method + registerPeriodicTask every 15min with the WorkManager Package, While in the debug mode, it works fine! (running on the real device or on emulator) but when Build an APK or use Fluter run --release comand , the local Notification doesnt show on release mode .
```

```
This my code syntax :
on main.dart
```

```
 void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await NotificationHelper().initialize(); // Initialize notification plugin

  // Initialize the workmanager
  await Workmanager().initialize(callbackDispatcher);

  await SharedPrefHelper.init();
  initValue = await SharedPrefHelper.getInt(key: 'index') ?? 0;

  SystemChrome.setSystemUIOverlayStyle(
    const SystemUiOverlayStyle(
      statusBarColor: Colors.transparent,
      statusBarIconBrightness: Brightness.light,
    ),
  );

  runApp(const Tawba());
}

void callbackDispatcher() {
  print('Callback dispatcher executed'); // Add this line
  Workmanager().executeTask((task, inputData) {
    NotificationHelper notificationHelper = NotificationHelper();
    notificationHelper.scheduleNotification();

    return Future.value(true);
  });
}
```

```
for the notification manager class

```
```
import 'dart:math';

import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:tawba/utils/jsons/zekr.dart';

class NotificationHelper {
  FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
      FlutterLocalNotificationsPlugin();

  Future<void> initialize() async {
    const AndroidInitializationSettings initializationSettingsAndroid =
        AndroidInitializationSettings(
            '@mipmap/ic_launcher'); // Replace with your app's icon

    const InitializationSettings initializationSettings =
        InitializationSettings(
      android: initializationSettingsAndroid,
    );

    await flutterLocalNotificationsPlugin.initialize(
      initializationSettings,
    );
  }

  Future<void> scheduleNotification() async {
    print('Scheduling random notification'); // Add this line

    final random = Random();
    int rndmID = Random().nextInt(zekrData.length - 1);
    AndroidNotificationDetails androidPlatformChannelSpecifics =
        AndroidNotificationDetails(
      '$rndmID.0',
      'تطبيق توبه',
      channelDescription: 'تطبيق اذكار وادعية وتلاوة وقراءة القرءان الكريم',
      importance: Importance.high,
      priority: Priority.high,
      styleInformation: const BigTextStyleInformation(''),
    );

    NotificationDetails platformChannelSpecifics =
        NotificationDetails(android: androidPlatformChannelSpecifics);

    final randomMessage = zekrData[random.nextInt(zekrData.length)];
    final notificationId = random.nextInt(1 << 31);

    await flutterLocalNotificationsPlugin.show(
      notificationId, // Notification ID
      'فَذَكِّرْ',
      randomMessage,
      platformChannelSpecifics,
      payload: '',
    );
  }
}
```

```
and i called the registerperiodictask on home page on initState :

```
```
void initState() {
    super.initState();
    periodicTask();
    }

    void periodicTask() {
    Workmanager().registerPeriodicTask(
      "1",
      "periodic Notification",
      frequency: const Duration(minutes: 15),
     );
    }
```

```
I tried all of these:
flutter clean
flutter pub get
flutter build apk --no-shrink
add keep.xml file to my android/app/src/main/res directory
add proguard-rules.pro file
edit AndroidManifest.xml based on this (add permission, etc.).
Check Dependencies and Configuration
Restart IDE or Emulator/Device and try on another devices

What should I do?!

Is there any solution?!

Thank you.
```

**Comment by MaikuB** [comment]
If you've done all the steps related to release build configuration then I suggest you in release mode test using only this plugin to show a notification to really confirm you've done everything. If you find it works then that should be an indicator that the work manager plugin require some configuration and isn't something I can advise on

**Comment by InspectlyMads** [comment]
Having same issue. Android notification doesn't work in release mode, however it does work in debug. iOS works both in debug and release mode

**Comment by InspectlyMads** [comment]
@Souhaibbek Did you ever find a work around for this?

**Comment by Souhaibbek** [comment]
no i cancelled this idea and deleted the workmanager package and used only the local notification package periodically

**Comment by InspectlyMads** [comment]
But are you able receive notification locally on android in release mode?

**Comment by Souhaibbek** [comment]
yes without workmanager its working fine

**Comment by droidwizard** [comment]
I have same issue, I cannot remove workmanager because logic need call API and send result to local notification.  In debug mode(in simulator) It's working, but release mode install on real device not working, Who have a solution for this, Thanks.

**Comment by TalionSD** [comment]
Having same issue

**Comment by TalionSD** [comment]
This solution can help you:

1. Add ProGuard rules in android/app/proguard-rules.pro 
=>
# Prevent removal of `flutter_local_notifications` classes
-keep class com.dexterous.flutterlocalnotifications.** { *; }
-keep class com.google.gson.** { *; }

# Prevent removal of `Gson` Type Parameters
-keepattributes Signature
-keep class * extends com.google.gson.reflect.TypeToken { *; }
-keep class com.google.gson.internal.** { *; }
-keep class com.google.gson.stream.** { *; }

2. Use ProGuard in build.gradle in android/app/build.gradle
=>
android {
    ...
    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

**Comment by faizsr** [comment]
Still this issue exists here is the exception throwing (I have also used workmanager and this cannot be removed).

For release build configurations I added keep.xml file and added custom sounds and icon to the file. Also added proguard-rules.pro file and mentioned it in build.gradle in the app level.

Still why this issue occurring? Do I have any other configurations?

This is the error I got when running it in the background.
Error scheduling notification: PlatformException(invalid_sound, The resource adhan_call_to_prayer could not be found. Please make sure it has been added as a raw resource to your Android head project., null, null).

**Comment by emran92** [comment]
> Still this issue exists!! (I have also used workmanager and this package cannot be removed).
> 
> For release build configurations I added keep.xml file and added custom sounds and icon to the file. Also added proguard-rules.pro file and mentioned it in build.gradle in the app level.
> 
> Still why this issue occurring? Do I have any other configurations?
> 
> This is the error I got when running it in the background in debug. Error scheduling notification: PlatformException(invalid_sound, The resource adhan_call_to_prayer could not be found. Please make sure it has been added as a raw resource to your Android head project., null, null).

did you fix it?

**Comment by faizsr** [comment]
> > Still this issue exists!! (I have also used workmanager and this package cannot be removed).
> > For release build configurations I added keep.xml file and added custom sounds and icon to the file. Also added proguard-rules.pro file and mentioned it in build.gradle in the app level.
> > Still why this issue occurring? Do I have any other configurations?
> > This is the error I got when running it in the background in debug. Error scheduling notification: PlatformException(invalid_sound, The resource adhan_call_to_prayer could not be found. Please make sure it has been added as a raw resource to your Android head project., null, null).
> 
> did you fix it?

No, I had to remove workmanager package inorder to work with the issue.

**Comment by farukiyyem** [comment]
Still no fixes available? Have the same issue...
