### ISSUE TITLE
when app is in background perticular screen is not opening withuot context 

### ISSUE THREAD

**Issue by navaghandabhi** [MaikuB/flutter_local_notifications#2075]
void notificationTapBackground(NotificationResponse notificationResponse) async {
  try {
    WidgetsFlutterBinding.ensureInitialized();
    await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
    Map payload = json.decode(notificationResponse.payload!);
    // ignore: avoid_print
    print('notification(${notificationResponse.id}) action tapped: '
        '${notificationResponse.actionId} with'
        ' payload: ${json.decode(notificationResponse.payload ?? "")}');
    if (notificationResponse.actionId == 'Accept') {
      log("Call Accepted");

///tryed [not working currentState getting null ]
      // navigatorKey.currentState!.pushNamed(Routes.CALL_PICKUP_SCREEN,arguments: {"userData": payload["userData"], "callId": payload["callId"]});

///tryed [not working without context]
      // Navigator.of(context).pushNamed(Routes.CALL_PICKUP_SCREEN,arguments: {"userData": 
payload["userData"), "callId": payload["callId"]});

///tryed [not working]
      // navigatorKey.currentState?.pushNamed(Routes.CALL_PICKUP_SCREEN, arguments: {"userData": payload["userData"], "callId": payload["callId"]});
    } else if (notificationResponse.actionId == 'Reject') {
      log("Call Rejected");
      
      FlutterLocalNotificationsPlugin().cancel(1); // Dismiss the notification
    } else {
      ///other action
    }
  } catch (error) {
    log("error on notification tap in background : $error");
  }
}

also tried getx
// Get.to(() => AudioCallView(), arguments: {"userData": json.decode(remoteMessage.data["userData"]), "callId": remoteMessage.data["callId"]});

also tried method channel 
await const MethodChannel('android_channel').invokeMethod("openCallPickUpScreen", {'userData': userData.toMap(), 'callId': callId});

how to resolve this and open perticular screen from background on click to notification button

**Comment by MaikuB** [comment]
Are you are trying to use `onDidReceiveBackgroundNotificationResponse` via the [`initialize()` method](https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/FlutterLocalNotificationsPlugin/initialize.html)? If so, this has nothing to do with if the application is in the background or not. Background is in the name because a background isolate is used for notification actions. This is why the readme only mentions using `onDidReceiveBackgroundNotificationResponse` within the context of using notification actions. The readme and example app already cover how to handle when a user taps on a notification. I suggest you spend time running the example app to understand further

**Comment by navaghandabhi** [comment]
@MaikuB thanks for response i'll work on example

**Comment by navaghandabhi** [comment]
@MaikuB I didn't find any code where the app opens in the background ,can you help to find...

**Comment by navaghandabhi** [comment]
@MaikuB  
ok 
thank you

**Comment by navaghandabhi** [comment]
hello dear @MaikuB i read the example and i am able to redirect on screen in background and foreground on click on notification and action button
using this 
//  await FlutterLocalNotificationsPlugin().initialize(initializationSettings, onDidReceiveNotificationResponse: onDidReceiveNotificationResponse, onDidReceiveBackgroundNotificationResponse: notificationTapBackground);

thank you for 

and can you help me to redirect to screen without clicking on notification when notification comes?

**Comment by MaikuB** [comment]
There is no such functionality and the plugin doesn't "advertise" that it does either. You would need to look into your own solution for this
