### ISSUE TITLE
Android Error: <receiver#com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver>

### ISSUE THREAD

**Issue by duong-futa** [MaikuB/flutter_local_notifications#2078]
**How to reslove**

Error: android:exported needs to be explicitly specified for element <receiver#com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details. android.app main manifest (this file), line 8

**Comment by MaikuB** [comment]
This has been fixed a long time ago so if you are having this issue then you need to update the version of the plugin you're using
