### ISSUE TITLE
Doesn't work with firebase_messaging

### ISSUE THREAD

**Issue by MhmdAlmz** [MaikuB/flutter_local_notifications#208]
when i use the flutter_local_notifications and firebase_messaging package together i get this error on console.

D8: Program type already present: android.support.v4.app.INotificationSideChannel

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: C:\Users\Muhammed\Desktop\my_app\build\app\intermediates\transforms\dexBuilder\debug\2.jar, C:\Users\Muhammed\Desktop\my_app\build\app\intermediates\transforms\dexBuilder\debug\3.jar, C:\Users\Muhammed\Desktop\my_app\build\app\intermediates\transforms\dexBuilder\debug\4.jar, C:\Users\Muhammed\Desktop\my_app\build\app\intermediates\transforms\dexBuilder\debug\5.jar, C:\Users\Muhammed\Desktop\my_app\build\app\intermediates\transforms\dexBuilder\debug\6.jar, C:\Users\Muhammed\Desktop\my_app\build\app\intermediates\transforms\dexBuilder\debug\7.jar, C:\Users\Muhammed\Desktop\my_app\build\app\intermediates\transforms\dexBuilder\debug\8.jar, C:\Users\Muhammed\Desktop\my_app\build\app\intermediates\transforms\dexBuilder\debug\9.jar, C:\Users\Muhammed\Desktop\my_app\build\app\intermediates\transforms\dexBuilder\debug\10.jar, C:\Users\Muhammed\Desktop\my_app\build\app\intermediates\transforms\dexBuilder\debug\11.jar, C:\Users\Muhammed\Desktop\my_app\build\app\intermediates\transforms\dexBuilder\debug\12.jar, C:\Users\Muhammed\Desktop\my_app\build\app\intermediates\transforms\dexBuilder\debug\13.jar, C:\Users\Muhammed\Desktop\my_app\build\app\intermediates\transforms\dexBuilder\debug\14.jar, C:\Users\Muhammed\Desktop\my_app\build\app\intermediates\transforms\dexBuilder\debug\15.jar, C:\Users\Muhammed\Desktop\my_app\build\app\intermediates\transforms\dexBuilder\debug\16.jar, C:\Users\Muhammed\Desktop\my_app\build\app\intermediates\transforms\dexBuilder\debug\17.jar, C:\Users\Muhammed\Desktop\my_app\build\app\intermediates\transforms\dexBuilder\debug\18.jar, C:\Users\Muhammed\Desktop\my_app\build\app\intermediates\transforms\dexBuilder\debug\19.jar, C:\Users\Muhammed\Desktop\my_app\build\app\intermediates\transforms\dexBuilder\debug\20.jar, C:\Users\Muhammed\Desktop\my_app\build\app\intermediates\transforms\dexBuilder\debug\21.jar, C:\Users\Muhammed\Desktop\my_app\build\app\intermediates\transforms\dexBuilder\debug\22.jar, C:\Users\Muhammed\Desktop\my_app\build\app\intermediates\transforms\dexBuilder\debug\23.jar, C:\Users\Muhammed\Desktop\my_app\build\app\intermediates\transforms\dexBuilder\debug\24.jar, C:\Users\Muhammed\Desktop\my_app\build\app\intermediates\transforms\dexBuilder\debug\25.jar, C:\Users\Muhammed\Desktop\my_app\build\app\intermediates\transforms\dexBuilder\debug\26.jar, C:\Users\Muhammed\Desktop\my_app\build\app\intermediates\transforms\dexBuilder\debug\27.jar, C:\Users\Muhammed\Desktop\my_app\build\app\intermediates\transforms\dexBuilder\debug\28.jar, C:\Users\Muhammed\Desktop\my_app\build\app\intermediates\transforms\dexBuilder\debug\29.jar, C:\Users\Muhammed\Desktop\my_app\build\app\intermediates\transforms\dexBuilder\debug\30.jar, C:\Users\Muhammed\Desktop\my_app\build\app\intermediates\transforms\dexBuilder\debug\31.jar
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: android.support.v4.app.INotificationSideChannel

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BU�LD FAILED in 20s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by MaikuB** [comment]
Please read the link that is printed out in the error message and follow the steps it mentions

**Comment by ozexpert** [comment]
I do have firebase_messaging but I am getting a different error.

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'androidx.core:core' has different version for the compile (1.0.0) and runtime (1.0.1) classpath. You should manually set the same version via DependencyResolution

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        11.8s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Gradle task assembleDebug failed with exit code 1
```

**Comment by MaikuB** [comment]
@ozexpert looks like you have migrated to AndroidX but running into conflicts. See https://flutter.dev/docs/development/packages-and-plugins/developing-packages#conflict-resolution

**Comment by minh98** [comment]
I want to ask how can both of them work together in one of my projects.
any idea ?

**Comment by MaikuB** [comment]
@MhmdAlmz I'm closing this issue since I haven't heard back further. If you still have a problem then feel free to reopen the issue with more details
