### ISSUE TITLE
Schedule notification works on IOS and MacOS but not working on Android.

### ISSUE THREAD

**Issue by wonderkidshihab** [MaikuB/flutter_local_notifications#2080]
Hi there,

I have been trying to build an app for my company. I have used the `flutter_local_notifications: ^16.0.0-dev.2` plugin in this project. All the things are working fine on IOS and MacOS but scheduled notifications are not working on Android. The method `zonedSchedule` does not throw any errors but is doesn't work.

I have added these permissions in my Added these permissions on my AndroidManifest.xml:
```xml
<uses-permission android:name="android.permission.SCHEDULE_EXACT_ALARM" android:maxSdkVersion="32"/>
<uses-permission android:name="android.permission.USE_EXACT_ALARM"/>
```

but still not working, No schedule notifications are being shown.

Here is the function call:
```dart
static void showDummyNotificaition() async {
    await _flutterNotificationsPlugin.zonedSchedule(
      0,
      'Dummy',
      'Dummy',
      tz.TZDateTime.now(prefferedLocale ?? tz.local)
          .add(const Duration(seconds: 5)),
      const NotificationDetails(
        android: AndroidNotificationDetails(
          'Dummy',
          'Dummy',
          importance: Importance.max,
          priority: Priority.high,
          playSound: true,
          enableVibration: true,
        ),
        iOS: DarwinNotificationDetails(
          presentAlert: true,
          presentBadge: true,
          presentSound: true,
          presentBanner: true,
          threadIdentifier: 'Dummy',
        ),
        macOS: DarwinNotificationDetails(
          presentAlert: true,
          presentBadge: true,
          presentSound: true,
          presentBanner: true,
          threadIdentifier: 'Dummy',
        ),
      ),
      uiLocalNotificationDateInterpretation:
          UILocalNotificationDateInterpretation.absoluteTime,
      matchDateTimeComponents: DateTimeComponents.time,
      payload: jsonEncode(
        {
          'id': 0,
          'title': 'Dummy',
          'body': 'Dummy',
          'hour': tz.TZDateTime.now(prefferedLocale ?? tz.local).hour,
          'minute': tz.TZDateTime.now(prefferedLocale ?? tz.local).minute,
        },
      ),
    );
  }
```

I have checked it on the devices: Pixel 4a, a Xiaomi phone and Pixel 5.

**Comment by InspectlyMads** [comment]
Having same issue. Android notification doesn't work in release mode, however it does work in debug. iOS works both in debug and release mode

**Comment by wonderkidshihab** [comment]
From my side it's not even working on debug mode.

**Comment by wonderkidshihab** [comment]
A small update `flutter_local_notifications: ^15.1.1` schedule notification works smoothly and expectedly on all the platforms including Android.

**Comment by InspectlyMads** [comment]
> A small update `flutter_local_notifications: ^15.1.1` schedule notification works smoothly and expectedly on all the platforms including Android.

This didnt do the trick for me. Have you done any other setup changes?

**Comment by under3415** [comment]
For me it works on Android but not on iOS!? Here is a sample app:
https://github.com/under3415/notifications_sample

**Comment by MaikuB** [comment]
Closing this as OP has resolved their issue

**Comment by XolmirzayevB** [comment]
> A small update `flutter_local_notifications: ^15.1.1` schedule notification works smoothly and expectedly on all the platforms including Android.

i was facing same issue, it worked when i did this thank you

**Comment by XolmirzayevB** [comment]
> > A small update `flutter_local_notifications: ^15.1.1` schedule notification works smoothly and expectedly on all the platforms including Android.
> 
> This didnt do the trick for me. Have you done any other setup changes?

do you need setup for android

**Comment by wonderkidshihab** [comment]
> > > A small update `flutter_local_notifications: ^15.1.1` schedule notification works smoothly and expectedly on all the platforms including Android.
> > 
> > 
> > This didnt do the trick for me. Have you done any other setup changes?
> 
> do you need setup for android

No, I just followed their documentation. Nothing else was needed for me.
