### ISSUE TITLE
Flutter local notification show error

### ISSUE THREAD

**Issue by tologonkudaiberdiuulu** [MaikuB/flutter_local_notifications#2086]
Hi. I'm facing with following issue:
"Top-level error: Invalid argument (id): must fit within the size of a 32-bit integer i.e. in the range [-2^31, 2^31 - 1]: 3774632073"
<img width="558" alt="image" src="https://github.com/MaikuB/flutter_local_notifications/assets/47391827/5c033da9-dbec-4d29-9914-41a9ad847782">

I've above code. Nothing chaged. I'm using following versions of packages:
1. flutter_local_notifications: ^15.1.1
2. firebase_messaging: ^14.6.7

**Comment by MaikuB** [comment]
The error tells you what the issue is so this is something you need to fix
