### ISSUE TITLE
Why ActiveNotification can't provide payload in Android

### ISSUE THREAD

**Issue by MominRaza** [MaikuB/flutter_local_notifications#2089]
I have a chat app I want to remove the notification when user open a chat room, so I need the `payload` to remove the notification only for particular chat room. But `payload` is coming `null` in Android

https://github.com/MaikuB/flutter_local_notifications/blob/4d8aa14bb6ee12a8c3fa5a29d1eb82a5d57a8fe7/flutter_local_notifications_platform_interface/lib/src/types.dart#L70-L73

Minimal code
```dart
final List<ActiveNotification> activeNotifications =
        await flutterLocalNotificationsPlugin.getActiveNotifications();
print(activeNotifications[0].payload);
```

**Comment by selawik** [comment]
Same issue. Any update?

**Comment by MominRaza** [comment]
I'm adding id in tag, and tag comes in `ActiveNotification` on android.

**Comment by MaikuB** [comment]
It can't do it because it's not possible. I'd suggest familiarise yourself with the native APIs as it's important you understand what capabilities your target platform can do as the plugin is a wrapper to native APIs
