### ISSUE TITLE
Bubbles API support

### ISSUE THREAD

**Issue by Cretezy** [MaikuB/flutter_local_notifications#209]
It would be great to have support for the new [Bubbles API](https://developer.android.com/preview/features/bubbles) on Android.

This would be to allow Bubble Metadata to be added to notifications

**Comment by MaikuB** [comment]
Noted though your link is redirecting to a link on the main Flutter repository though I have read that new feature in Android Q

**Comment by Cretezy** [comment]
Yep, total mistake. I've fixed the link: https://developer.android.com/preview/features/bubbles

**Comment by MaikuB** [comment]
No worries. Unless I've missed it, it seems like there's a note that wasn't there before that in the final release, it will only be for developer use. I imagine that this was because it was a feature that was being tested and decision has been to not include. It doesn't seem like there's much value in looking to support this then

**Comment by MaikuB** [comment]
Android 10 is out and looks like this is still only for developer use, as such I won't be looking at working on this and will close this. You're welcome to submit a PR if you need it

**Comment by MaddinMade** [comment]
Any updates on this? Since Android 11, bubbles are a requirement to be displayed in the conversation section.

**Comment by TheSunCat** [comment]
There is an example on how to use this API from Java [here](https://developer.android.com/develop/ui/views/notifications/bubbles#java). I'm not very familiar with dart <=> java interop but I looks like we would need to implement `setBubbleMetadata` as well as a way to pass/create a `Notification.BubbleMetadata` object to give to this function.
