### ISSUE TITLE
[MacOS] Notifications don't make any sound when running the example app on MacOS 

### ISSUE THREAD

**Issue by michalkubizna** [MaikuB/flutter_local_notifications#2091]
flutter_local_notifications: ^15.1.1
Mac mini 
Flutter 3.13.2 

Run the example app to reproduce this issue.

**Comment by MaikuB** [comment]
This is something you would need to check on your on Mac device as this is actually working and it calls the appropriate API so there's nothing further that can be looked into from the plugin side
