### ISSUE TITLE
Failed to handle method call | Unhandled Exception: PlatformException(error, null, null, java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by arnabonetraker** [MaikuB/flutter_local_notifications#2092]
**Describe the bug**
Background Notification is failing to produce and end with an exception
```
E/MethodChannel#dexterous.com/flutter/local_notifications(12737): Failed to handle method call
E/MethodChannel#dexterous.com/flutter/local_notifications(12737): java.lang.IllegalArgumentException
E/MethodChannel#dexterous.com/flutter/local_notifications(12737): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3044)
E/MethodChannel#dexterous.com/flutter/local_notifications(12737): 	at android.os.Parcel.createException(Parcel.java:3024)
E/MethodChannel#dexterous.com/flutter/local_notifications(12737): 	at android.os.Parcel.readException(Parcel.java:3007)
E/MethodChannel#dexterous.com/flutter/local_notifications(12737): 	at android.os.Parcel.readException(Parcel.java:2949)
E/MethodChannel#dexterous.com/flutter/local_notifications(12737): 	at android.app.INotificationManager$Stub$Proxy.createNotificationChannels(INotificationManager.java:3497)
E/MethodChannel#dexterous.com/flutter/local_notifications(12737): 	at android.app.NotificationManager.createNotificationChannels(NotificationManager.java:929)
E/MethodChannel#dexterous.com/flutter/local_notifications(12737): 	at android.app.NotificationManager.createNotificationChannel(NotificationManager.java:917)
E/MethodChannel#dexterous.com/flutter/local_notifications(12737): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.setupNotificationChannel(FlutterLocalNotificationsPlugin.java:1189)
E/MethodChannel#dexterous.com/flutter/local_notifications(12737): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification(FlutterLocalNotificationsPlugin.java:240)
E/MethodChannel#dexterous.com/flutter/local_notifications(12737): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification(FlutterLocalNotificationsPlugin.java:1225)
E/MethodChannel#dexterous.com/flutter/local_notifications(12737): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.show(FlutterLocalNotificationsPlugin.java:1545)
E/MethodChannel#dexterous.com/flutter/local_notifications(12737): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(FlutterLocalNotificationsPlugin.java:1387)
E/MethodChannel#dexterous.com/flutter/local_notifications(12737): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#dexterous.com/flutter/local_notifications(12737): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#dexterous.com/flutter/local_notifications(12737): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#dexterous.com/flutter/local_notifications(12737): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#dexterous.com/flutter/local_notifications(12737): 	at android.os.Handler.handleCallback(Handler.java:942)
E/MethodChannel#dexterous.com/flutter/local_notifications(12737): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#dexterous.com/flutter/local_notifications(12737): 	at android.os.Looper.loopOnce(Looper.java:240)
E/MethodChannel#dexterous.com/flutter/local_notifications(12737): 	at android.os.Looper.loop(Looper.java:351)
E/MethodChannel#dexterous.com/flutter/local_notifications(12737): 	at android.app.ActivityThread.main(ActivityThread.java:8381)
E/MethodChannel#dexterous.com/flutter/local_notifications(12737): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#dexterous.com/flutter/local_notifications(12737): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
E/MethodChannel#dexterous.com/flutter/local_notifications(12737): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
E/MethodChannel#dexterous.com/flutter/local_notifications(12737): Caused by: android.os.RemoteException: Remote stack trace:
E/MethodChannel#dexterous.com/flutter/local_notifications(12737): 	at com.android.internal.util.Preconditions.checkArgument(Preconditions.java:44)
E/MethodChannel#dexterous.com/flutter/local_notifications(12737): 	at com.android.server.notification.PreferencesHelper.createNotificationChannel(PreferencesHelper.java:949)
E/MethodChannel#dexterous.com/flutter/local_notifications(12737): 	at com.android.server.notification.NotificationManagerService$10.createNotificationChannelsImpl(NotificationManagerService.java:3981)
E/MethodChannel#dexterous.com/flutter/local_notifications(12737): 	at com.android.server.notification.NotificationManagerService$10.createNotificationChannels(NotificationManagerService.java:4026)
E/MethodChannel#dexterous.com/flutter/local_notifications(12737): 	at android.app.INotificationManager$Stub.onTransact(INotificationManager.java:1585)
E/MethodChannel#dexterous.com/flutter/local_notifications(12737): 
E/flutter (12737): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, null, null, java.lang.IllegalArgumentException
E/flutter (12737): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3044)
E/flutter (12737): 	at android.os.Parcel.createException(Parcel.java:3024)
E/flutter (12737): 	at android.os.Parcel.readException(Parcel.java:3007)
E/flutter (12737): 	at android.os.Parcel.readException(Parcel.java:2949)
E/flutter (12737): 	at android.app.INotificationManager$Stub$Proxy.createNotificationChannels(INotificationManager.java:3497)
E/flutter (12737): 	at android.app.NotificationManager.createNotificationChannels(NotificationManager.java:929)
E/flutter (12737): 	at android.app.NotificationManager.createNotificationChannel(NotificationManager.java:917)
E/flutter (12737): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.setupNotificationChannel(FlutterLocalNotificationsPlugin.java:1189)
E/flutter (12737): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification(FlutterLocalNotificationsPlugin.java:240)
E/flutter (12737): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification(FlutterLocalNotificationsPlugin.java:1225)
E/flutter (12737): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.show(FlutterLocalNotificationsPlugin.java:1545)
E/flutter (12737): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(FlutterLocalNotificationsPlugin.java:1387)
E/flutter (12737): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/flutter (12737): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter (12737): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/flutter (12737): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter (12737): 	at android.os.Handler.handleCallback(Handler.java:942)
E/flutter (12737): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (12737): 	at android.os.Looper.loopOnce(Looper.java:240)
E/flutter (12737): 	at android.os.Looper.loop(Looper.java:351)
E/flutter (12737): 	at android.app.ActivityThread.main(ActivityThread.java:8381)
E/flutter (12737): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (12737): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
E/flutter (12737): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
E/flutter (12737): Caused by: android.os.RemoteException: Remote stack trace:
E/flutter (12737): 	at com.android.internal.util.Preconditions.checkArgument(Preconditions.java:44)
E/flutter (12737): 	at com.android.server.notification.PreferencesHelper.createNotificationChannel(PreferencesHelper.java:949)
E/flutter (12737): 	at com.android.server.notification.NotificationManagerService$10.createNotificationChannelsImpl(NotificationManagerService.java:3981)
E/flutter (12737): 	at com.android.server.notification.NotificationManagerService$10.createNotificationChannels(NotificationManagerService.java:4026)
E/flutter (12737): 	at android.app.INotificationManager$Stub.onTransact(INotificationManager.java:1585)
E/flutter (12737): 
E/flutter (12737): )
E/flutter (12737): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
E/flutter (12737): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
E/flutter (12737): <asynchronous suspension>
E/flutter (12737): #2      FlutterLocalNotificationsPlugin.show (package:flutter_local_notifications/src/flutter_local_notifications_plugin.dart:240:7)
```

While sending notification plugin is facing PlatformException, but it doesnt happend everytime. If I were to run again it works, then once in a while it comes 

**To Reproduce**
1. Initialise 
2. Go outside the app
3. Generate a notification

**Expected behavior**
Notification should produce without any execption

**Sample code to reproduce the problem**
```
  Future<void> showMyCustomNotification(
      int id, Importance importance, Map<String, dynamic> message) async {
    String? title = message['title'] ?? "";
    String? thisMessage = message['message'] ?? "";
    String? to_address_data = message['to_address_data'] ?? "";
    String? from_address_data = message['from_address_data'] ?? "";
    String? body = "$thisMessage $to_address_data $from_address_data";
    String? payload = message.toString();

    AndroidNotificationDetails androidNotificationDetails =
        AndroidNotificationDetails(
      'custom_sound_notification',
      title!,
      channelDescription: body,
      playSound: true,
      sound: RawResourceAndroidNotificationSound('test'),
    );

    const DarwinNotificationDetails darwinNotificationDetails =
        DarwinNotificationDetails(
      presentAlert: true,
      presentSound: true,
      sound: 'test.wav',
    );

    final NotificationDetails notificationDetails = NotificationDetails(
      android: androidNotificationDetails,
      iOS: darwinNotificationDetails,
    );

    await _flutterLocalNotificationsPlugin.show(
      id,
      title,
      body,
      notificationDetails,
      payload: payload,
    );
  }
```

**Comment by MaikuB** [comment]
Please provide a link to a fork of this repo with the example app modified to show how this can be reproduced. The stack trace would indicate it doesn't have anything to do with being outside of the app but provide invalid/insufficient details needed for a notification channel to be created

**Comment by Hasan1376** [comment]
**### hello
I am facing this problem and I don't know what to do
I made a ringtone program that runs without problems on Samsung phones, but it doesn't run properly on Xiaomi phones and I get this error.**


E/MethodChannel#ringtone_set(27391): Failed to handle method call
E/MethodChannel#ringtone_set(27391): java.lang.IllegalArgumentException: Mutation of _data is not allowed.
E/MethodChannel#ringtone_set(27391): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
E/MethodChannel#ringtone_set(27391): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
E/MethodChannel#ringtone_set(27391): 	at android.content.ContentProviderProxy.insert(ContentProviderNative.java:557)
E/MethodChannel#ringtone_set(27391): 	at android.content.ContentResolver.insert(ContentResolver.java:2196)
E/MethodChannel#ringtone_set(27391): 	at android.content.ContentResolver.insert(ContentResolver.java:2157)
E/MethodChannel#ringtone_set(27391): 	at acr.rt.ringtone_set.RingtoneSetPlugin.setThings(RingtoneSetPlugin.java:226)
E/MethodChannel#ringtone_set(27391): 	at acr.rt.ringtone_set.RingtoneSetPlugin.onMethodCall(RingtoneSetPlugin.java:313)
E/MethodChannel#ringtone_set(27391): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/MethodChannel#ringtone_set(27391): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/MethodChannel#ringtone_set(27391): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#ringtone_set(27391): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#ringtone_set(27391): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#ringtone_set(27391): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#ringtone_set(27391): 	at android.os.Looper.loopOnce(Looper.java:210)
E/MethodChannel#ringtone_set(27391): 	at android.os.Looper.loop(Looper.java:299)
E/MethodChannel#ringtone_set(27391): 	at android.app.ActivityThread.main(ActivityThread.java:8319)
E/MethodChannel#ringtone_set(27391): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#ringtone_set(27391): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
E/MethodChannel#ringtone_set(27391): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
E/flutter (27391): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, Mutation of _data is not allowed., null, java.lang.IllegalArgumentException: Mutation of _data is not allowed.
E/flutter (27391): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
E/flutter (27391): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
E/flutter (27391): 	at android.content.ContentProviderProxy.insert(ContentProviderNative.java:557)
E/flutter (27391): 	at android.content.ContentResolver.insert(ContentResolver.java:2196)
E/flutter (27391): 	at android.content.ContentResolver.insert(ContentResolver.java:2157)
E/flutter (27391): 	at acr.rt.ringtone_set.RingtoneSetPlugin.setThings(RingtoneSetPlugin.java:226)
E/flutter (27391): 	at acr.rt.ringtone_set.RingtoneSetPlugin.onMethodCall(RingtoneSetPlugin.java:313)
E/flutter (27391): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/flutter (27391): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/flutter (27391): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/flutter (27391): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter (27391): 	at android.os.Handler.handleCallback(Handler.java:938)
E/flutter (27391): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (27391): 	at android.os.Looper.loopOnce(Looper.java:210)
E/flutter (27391): 	at android.os.Looper.loop(Looper.java:299)
E/flutter (27391): 	at android.app.ActivityThread.main(ActivityThread.java:8319)
E/flutter (27391): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (27391): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
E/flutter (27391): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
E/flutter (27391): )
E/flutter (27391): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651:7)
E/flutter (27391): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
E/flutter (27391): <asynchronous suspension>
E/flutter (27391): #2      setFromAsset (package:ringtone_set/src/setter_functions.dart:26:23)
E/flutter (27391): <asynchronous suspension>
E/flutter (27391): #3      _PlayItemState.build.<anonymous closure> (package:rington_apps_rc1/play_item.dart:84:34)
E/flutter (27391): <asynchronous suspension>
E/flutter (27391):
