### ISSUE TITLE
Question: The app limited to only 24 notifications? How can I increase this limit to, for example, 200?

### ISSUE THREAD

**Issue by Erchil66** [MaikuB/flutter_local_notifications#2093]
I'm experiencing an issue with notifications in release mode. When I tried to test it and received more than 120 notifications, I could only see 24 notifications.

I'm using a Samsung Galaxy S22+ (Android 13) and a Lenovo phone (Android 11).
![image](https://github.com/MaikuB/flutter_local_notifications/assets/92772509/8574a907-4deb-4395-b5fc-268a03e1b8a4)

**Comment by Kot19781978** [comment]
Czy mozna zwiększyć liczbę powiadomień?
