### ISSUE TITLE
`ondidReceiveNotificationResponse` is called when user lock device on Android

### ISSUE THREAD

**Issue by ndelanou** [MaikuB/flutter_local_notifications#2094]
**Describe the bug**
On Android, if `fullScreenIntent` is set to `true` and the notification is present on screen, `ondidReceiveNotificationResponse` is called when locking the device.
This result, in my case, in unwanted behavior.

**To Reproduce**
1. App is open.
2. User receive a notification that stays on screen.
3. User lock device
4. `ondidReceiveNotificationResponse` is called (triggering navigation in my case)
5. User finds that the app changed page while the phone was locked.

**Expected behavior**
Notification should not open by itself when the device is locked.

**Sample code to reproduce the problem**
```dart
static const _androidNotificationDetails = AndroidNotificationDetails(
    'notification_channel',
    'Notiffication channel',
    priority: Priority.high,
    importance: Importance.high,
    fullScreenIntent: true,
  );
```

**Comment by MaikuB** [comment]
I understand that this may be not what you want for your case but this is the expected behaviour and documented as such by Google themselves. See https://developer.android.com/develop/ui/views/notifications/build-notification#urgent-message. For convenience, the main points are

> When the notification is invoked, users see one of the following, depending on the device's lock status:
>
> * If the user's device is locked, a full-screen activity appears, covering the lockscreen.
> * If the user's device is unlocked, the notification appears in an expanded form that includes options for handling or dismissing the notification.

Closing this as it's behaving as expected
