### ISSUE TITLE
[Enhancement request / Discussion] updating com.android.tools:desugar_jdk_lib dependency

### ISSUE THREAD

**Issue by j-q-in-berlin** [MaikuB/flutter_local_notifications#2095]
The documentation suggests that we use v1.1.5 (released in February 2021) which works fine, but I noticed that there is already a v2.0.3 (released in March 2023). I tried updating but I get the following error: _

> 
> Task :app:l8DexDesugarLibQaDebug FAILED Warning: Human desugared library specification format version 200 mismatches the parser expected version (100). This is allowed and should happen only while extending the specifications. Error: java.lang.IllegalStateException: This is not a JSON Array. Human desugared library specification format version 200 mismatches the parser expected version (100). This is allowed and should happen only while extending the specifications.
> 
> java.lang.IllegalStateException: This is not a JSON Array.

_
I know many will say "if it ain't broke, don't fix it", but I wonder if this could lead to a security breach. 
What do you guys think?

**Comment by MaikuB** [comment]
I'd suggest you try asking this on Android/Java developer forums. A couple of points I'll mention on this though

- if your concerns are on security then you should be looking to having security scans done on your app and there are services that can check dependencies that would then find out if the library has security issues. Dependabot is enabled on this repo so if there were issues, I would expect GitHub to flag them.
- various versions of the library require a minimum Android Gradle plugin (AGP) version https://developer.android.com/studio/write/java8-support#library-desugaring-versions. Higher AGP versions would need higher versions of Flutter. This would limit those who could use the plugin. If you are you using a higher version of Flutter and still have concerns on this then you could fork the plugin and use the fork

**Comment by asmrtfm** [comment]
I'm getting a seemingly related error:

```
Execution failed for task ':app:checkUserDebugAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > 2 issues were found when checking AAR metadata:

       1.  Dependency ':flutter_local_notifications' requires core library desugaring to be enabled
           for :app.

           See https://developer.android.com/studio/write/java8-support.html for more
           details.
```
I have followed the recommendations at https://developer.android.com/studio/write/java8-support but still get the error.
Can anyone offer guidance on this matter?
