### ISSUE TITLE
[Feature request] A callback that gets fired when user receives a local notification.

### ISSUE THREAD

**Issue by Gaurav-CareMonitor** [MaikuB/flutter_local_notifications#2098]
Just like firebase has a callback `onBackgroundMessage` that gets triggered when a push notification is received when app is closed.
Can we also have a similar callback that gets fired when a local notification is received in the phone.

<img width="555" alt="image" src="https://github.com/MaikuB/flutter_local_notifications/assets/113885801/28c09971-18a0-47f2-883d-32bead766562">

I am working on showing notification history page, and want to save notification to db when user receives it on phone.
Something like `onDidReceiveBackgroundNotification`

**Comment by Gaurav-CareMonitor** [comment]
Seems similar to [this](https://github.com/MaikuB/flutter_local_notifications/issues/1699)

**Comment by MaikuB** [comment]
Closing this as there's already an existing issue on this
