### ISSUE TITLE
Feature Request: Add an Android notification style supporting background image

### ISSUE THREAD

**Issue by jice-lavocat** [MaikuB/flutter_local_notifications#2100]
I played around the extension to get a behavior similar to what is described here ([link](https://stackoverflow.com/q/49804120))

![image](https://github.com/MaikuB/flutter_local_notifications/assets/2247438/d680af13-38d5-49ba-a3c8-21871d4202fd)

I first got the impression that the MediaStyle would allow me to stretch the image and use it as a background, but this seems impossible.

So, I was wondering if there was a way to use one of the available plugin's styles (or to create one) to be able to display a custom background as the notification on Android.

_Please apologize it's not a bug report, so if that's relevant, just delete my question._

**Comment by MaikuB** [comment]
You would need to look into need to look the functionality exposed by the native notification APIs to find out and is actually something you should look into prior to looking at this plugin. I wouldn't be able to tell you myself. It may be you need to consider building your own custom notification layout
