### ISSUE TITLE
Split the example code to multiple features and files.

### ISSUE THREAD

**Issue by moinkhan780** [MaikuB/flutter_local_notifications#2105]
Split the example code to multiple features and files. in 1 file whole code is very much confusing for beginners. 

Like 

1. Schedule notification
2. Notification with firebase
3. Get permissions
4. Notification with image
5. Notification with custom icon

up to so on......

Thanks

**Comment by MaikuB** [comment]
Thanks for raising this and understand your point but I'm not looking to split this myself as this is already something I maintain in my spare time. There's a reason why it's all in one file as well as if you go to pub.dev then you will find the example tab of a package shows only the content of the `main.dart` file. There's also a reason why the buttons exist for each features as each button would trigger different callback methods and thus allows seeing the related code. If you want to try to look split the files then you can try to contribute but bear in mind this will affect what developers will see on pub.dev
