### ISSUE TITLE
Notification Actions for android

### ISSUE THREAD

**Issue by shafquat1** [MaikuB/flutter_local_notifications#2108]
I am not able to get the input from the notification, I type a message and hit send in the notification but I am not receiving any input.

this is my code for handling notifications: 

`await_notificationsPlugin.initialize(
        _initializationSettings,
        onDidReceiveNotificationResponse: (response) {
          final _tempDataMap = jsonDecode(response.payload ?? '');
          final _dataMap = _tempDataMap['data'];
          final _context = AppConstants.globalNavKey.currentContext;
          if (_context == null) {
            debugPrint('_context is null');
            return;
          }
          final _actionId = _dataMap['actionId'] ?? '';
          switch (response.notificationResponseType) {
            case NotificationResponseType.selectedNotification:
              debugPrint('notification clicked');
              debugPrint('reply is ${response.input}');
              debugPrint('_action is ${response.actionId}');
              debugPrint('payload is ${response.payload}');
              debugPrint('id is ${response.id}');
              debugPrint('type is ${response.notificationResponseType}');
              debugPrint('action id is $_actionId');
              _onLocalNotificationClicked(response.payload);
              break;
            case NotificationResponseType.selectedNotificationAction:
              debugPrint('notification action clicked');
              debugPrint('reply is ${response.input}');
              debugPrint('_action is ${response.actionId}');
              debugPrint('payload is ${response.payload}');
              debugPrint('id is ${response.id}');
              debugPrint('type is ${response.notificationResponseType}');
              debugPrint('action id is $_actionId');
              if (_actionId == replyActionId) {
                debugPrint('notification action clicked');
                selectNotificationStream.add(response.payload);
                _sendMessage(
                  response.payload,
                  response.input,
                );
              }
              break;
          }
        },
      );`

this is my notification detail settings: 

` final _androidNotificationDetails = AndroidNotificationDetails(
        _notifChannelID, _notifChannelName,
        channelDescription: _notifChannelDesc,
        groupKey: _notifGroupKey,
        importance: Importance.max,
        priority: Priority.high,
        actions: <AndroidNotificationAction>[
          AndroidNotificationAction(replyActionId, 'Reply',
              titleColor: ColorConstants.white,
              inputs: [
                AndroidNotificationActionInput(
                  label: 'Please type your reply',
                  allowFreeFormInput: true,
                ),
              ],
             ),
        ]
        );`

this is my send message to stream method:

` void _sendMessage(
    String? payload,
    String? input,
  ) async {
    final _tempDataMap = jsonDecode(payload ?? '');
    final _dataMap = _tempDataMap['data'];
    final _context = AppConstants.globalNavKey.currentContext;
    if (_context == null) {
      debugPrint('_context is null');
      return;
    }
    var chatState = sc.StreamChat.of(_context);
    final _channelType = _dataMap['channel_type'] ?? '';
    final _channelId = _dataMap['channel_id'] ?? '';
    var _channel = await chatState.client.channel(
      _channelType,
      id: _channelId,
    );
    late sc.Message message;
    message = sc.Message(
      text: input ?? '',
    );
    await _channel.sendMessage(
      message,
    );
  }`

Can someone please help me with this why am I not able to get anything in response.input and why am I not getting in the  case NotificationResponseType.selectedNotificationAction. It always executes the case NotificationResponseType.selectedNotification. This is important as I am working for a client and I have to meet a deadline.

**Comment by MaikuB** [comment]
You configured your notification actions to respond on the background isolate so should be using the `onDidReceiveBackgroundNotificationResponse` callback. This is why it looks like you're not getting any response. This is covered in the readme and something you could have checked via the example app.
