### ISSUE TITLE
Schedule and show notification even when app is kill

### ISSUE THREAD

**Issue by Inihood1** [MaikuB/flutter_local_notifications#2109]
Hi, I ran the sample app and it seems schedule notifications does not show when app is kill. Is there a way to achieve this?

**Comment by MaikuB** [comment]
Which device(s) did you use test this?

**Comment by Inihood1** [comment]
Android 11

**Comment by MaikuB** [comment]
What you mentioned is the OS and OS version, I was asking about the device(s) you used

**Comment by Inihood1** [comment]
A physical device. If that's what you're asking

**Comment by MaikuB** [comment]
I'm asking which specific device

**Comment by Inihood1** [comment]
You mean the brand? Techno device

**Comment by MaikuB** [comment]
A question on which device refers to specifics like brand and model. If you happened to not being use a device then it's simulator/emulator. For future reference, whenever you raise an issue to repositories, please provide more specifics as avoids continuous back and forth.

For this problem, please try to check the readme as this functionality is working and is a limitation of your device. This documented at https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#scheduled-android-notifications and if you ran the app on a stock Android device or emulator then you would find it works as expected

**Comment by Inihood1** [comment]
Let me try with a Samsung device
