### ISSUE TITLE
When used to display notifications of progress updates, the page cannot respond to other actions

### ISSUE THREAD

**Issue by MrRuiCoder** [MaikuB/flutter_local_notifications#211]
void downLoadApk(String url, String fileName) async {
    Directory dir = await CommonUtils.getLocalPath();
    ReceivePort receivePort = new ReceivePort();
    await Isolate.spawn(downLoader, receivePort.sendPort);
    SendPort sendPort = await receivePort.first;
    sendReceive(sendPort, url, dir.path + "/" + fileName).listen((result) {
      if (result is List) {
        NotificationUtils.showProgressNotification(
            flutterLocalNotificationsPlugin, result[1], result[0]);
      } else {
        flutterLocalNotificationsPlugin.cancel(0);
        InstallApk.installApk(result);
      }
    });
  }

  static downLoader(SendPort sendPort) async {
    ReceivePort port = new ReceivePort();
    sendPort.send(port.sendPort);

    await for (var msg in port) {
      Dio dio = new Dio();
      String url = msg[0];
      String path = msg[1];
      SendPort replyTo = msg[2];
      await dio.download(url, path, onProgress: (received, total) {
        replyTo.send([received, total]);
      });
      replyTo.send(path);
      port.close();
    }
  }

  ReceivePort sendReceive(SendPort port, String url, String fileName) {
    ReceivePort response = new ReceivePort();
    port.send([url, fileName, response.sendPort]);
    return response;
  }

**Comment by MaikuB** [comment]
I believe this happening as platform channels won't work on multiple isolates. There's a known issue on the Flutter repository on calling platform channels (which this plugin would do) on another isolate (see [here](https://github.com/flutter/flutter/issues/13937)). I suspect you may have to remove all the code on spawning another isolate and the message passing in the mean time if you want to get around this issue

**Comment by MaikuB** [comment]
Were you able to resolve this in the end?

**Comment by MaikuB** [comment]
Closing due to no further response
