### ISSUE TITLE
Exception "permissionRequestInProgress" on subsequent call of requestExactAlarmsPermission

### ISSUE THREAD

**Issue by liri2006** [MaikuB/flutter_local_notifications#2110]
**Describe the bug**
I'm trying to implement the flow of setting up of alarms for Android 13. Calling requestExactAlarmsPermission works as expected - settings page is opened, but if I hit back without turning on the permission, every subsequent call to requestExactAlarmsPermission end with exception "PlatformException(permissionRequestInProgress, Another permission request is already in progress, null, null)".

**To Reproduce**
1. Call requestExactAlarmsPermission().
2. On Settings screen tap back button.
3. Call requestExactAlarmsPermission() again.

Plugin version: 16.0.0-dev.3

**Expected behavior**
User is presented with setting screen again.

**Sample code to reproduce the problem**

```
await flutterLocalNotificationsPlugin
                .resolvePlatformSpecificImplementation<AndroidFlutterLocalNotificationsPlugin>()!
                .requestExactAlarmsPermission()
```

Am I missing something?

**Comment by MaikuB** [comment]
Thanks for raising this. You didn't miss anything, there's a bug here and found a fix for it. Will include this in the stable 16.0.0 release
