### ISSUE TITLE
 Unhandled Exception: Null check operator used on a null value: IOS

### ISSUE THREAD

**Issue by RNerdMine** [MaikuB/flutter_local_notifications#2120]
Unhandled Exception: Null check operator used on a null value
#0      FlutterLocalNotificationsPlugin.initialize (package:flutter_local_notifications/src/flutter_local_notifications_plugin.dart:129:50)
#1      PushNotificationService.registerNotificationListeners (package:/utils/push_notification_service.dart:29:37)
<asynchronous suspension>
#2      PushNotificationService.setupInteractedMessage (package:/utils/push_notification_service.dart:17:5)
<asynchronous suspension>

**Comment by MaikuB** [comment]
Please provide a link to a repo hosting the code for a minimal app that can reproduce the issue. This can also be done by forking this repo and updating the example app so it closely matches the code you have

**Comment by MaikuB** [comment]
Closing due to lack of response
