### ISSUE TITLE
"coreLibraryDesugaringEnabled true" throws error

### ISSUE THREAD

**Issue by VasilisPH** [MaikuB/flutter_local_notifications#2127]
While following your pub.dev's Android setup, I noticed that the 

"`coreLibraryDesugaringEnabled true`"  in 

```
compileOptions {
        // Flag to enable support for the new language APIs
        coreLibraryDesugaringEnabled true 
        // Sets Java compatibility to Java 8
        sourceCompatibility JavaVersion.VERSION_1_8 
        targetCompatibility JavaVersion.VERSION_1_8
    }
``` 

does not allow me to build my app in Android. This is the error: 

ERROR:D8: com.android.tools.r8.kotlin.H

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:dexBuilderDebug'.
> Could not resolve all files for configuration ':app:detachedConfiguration10'.
   > Failed to transform jetified-kotlin-stdlib-1.9.0.jar to match attributes {artifactType=ext-dex-dexBuilderDebug, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for DexingExternalLibArtifactTransform: /Users/name/.gradle/caches/transforms-3/b4ccd50d32e5e03b21888cc7fc5178c2/transformed/jetified-kotlin-stdlib-1.9.0.jar.
         > Error while dexing.

 Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 39s
┌─ Flutter Fix ───────────────────────────────────────────────────────────┐
│ [!] The shrinker may have failed to optimize the Java bytecode.            │
│ To disable the shrinker, pass the `--no-shrink` flag to this command.      │
│ To learn more, see: https://developer.android.com/studio/build/shrink-code │
└──────────────────────────────────────────────────────────┘
Exception: Gradle task assembleDebug failed with exit code 1
Exited

If I comment it, the app will build as normal.

![image](https://github.com/MaikuB/flutter_local_notifications/assets/89184975/c33abe88-4519-40eb-900b-ce5c8a29b7d1)

**Comment by alloza95** [comment]
Same error here after I upgraded Kotlin from 1.8.22 to 1.9.10 and AGP to 7.4.2

**Comment by MaikuB** [comment]
This wouldn't be an issue with the plugin but something to do with your own app's configuration. This stands out when you consider that the error message references a Kotlin library when the plugin is written with Java on the Android side. I'd suggest you look it up the error online to look for similar issues and see if there are solutions available. A quick search online reveals one similar issue at https://github.com/juliansteenbakker/mobile_scanner/issues/729 where there may be some solutions in the thread for you to try out
