### ISSUE TITLE
Notification doesn't work when the app is terminated

### ISSUE THREAD

**Issue by hlarchi** [MaikuB/flutter_local_notifications#2130]
On different android emulator, notification doesn't work when the app is terminated.
Tested with both method "zonedSchedule" and "periodicallyShow".

**Comment by MaikuB** [comment]
Besides the caveats mentioned in https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#scheduled-android-notifications that aren't to do with this plugin, this is working as expected so you'll need to check your device/emulator further and not something I can help with
