### ISSUE TITLE
 Issue with Conditional Custom Sound Notifications in Flutter

### ISSUE THREAD

**Issue by AkshayStackSum** [MaikuB/flutter_local_notifications#2131]
**Question:**
I'm experiencing an issue with conditional custom sound notifications in my Flutter app. Initially, I had a working setup for custom sound notifications. However, after introducing a condition to determine when to use custom sounds, the configuration seems to be cached and reused for all subsequent notifications.
 

**Problem:**

When I receive notifications with different types (e.g., "sos" and other types), I expect the sound to be played according to the message type. For example, a custom sound for "sos" messages and a default sound for other types.
Initially, the custom sound notification worked correctly when the "sos" type was detected.
However, after the introduction of this condition, the notification settings (including sound) appear to be cached, and the same settings are used for all notifications, regardless of the message type.
Steps Taken:

I've verified that the message type is correctly detected in the message.data['type'] field.
The sound file (alert.mp3) is correctly located in the res/raw directory in my Android project.
I have also ensured that the notification configuration is set for each individual message based on the message type.

**Code Example:**

` try {
      final id = DateTime
          .now()
          .millisecondsSinceEpoch ~/ 1000;

      // Check if the message type is "sos" to set the sound
      AndroidNotificationDetails androidNotificationDetails;
      var notificationDetails ;
      if (message.data['type'].toString().trim() == "sos") {
        print("Message gg: ${message.data['type']}");

        androidNotificationDetails = AndroidNotificationDetails(
          "pushnotificationapp",
          "pushnotificationappchannel",
          importance: Importance.max,
          priority: Priority.high,
          sound: RawResourceAndroidNotificationSound('alert'),
          playSound: true,
        );
        notificationDetails = NotificationDetails(
            android: androidNotificationDetails);
      } else {
        print("Message bb: ${message.data['type']}");

        androidNotificationDetails = AndroidNotificationDetails(
          "pushnotificationapp",
          "pushnotificationappchannel",
          importance: Importance.max,
          priority: Priority.high,
          sound: null,
          playSound: false,
        );
        notificationDetails = NotificationDetails(
            android: androidNotificationDetails);
      }

      await _notificationsPlugin.show(
        id,
        message.notification!.title,
        message.notification!.body,
        notificationDetails,
        payload: message.data['_id'],
      );
    } on Exception catch (e) {
      debugPrint(e.toString());
    }`
    
    **Request for Assistance:**
I would greatly appreciate any insights or suggestions on how to ensure that the custom sound notification settings are correctly applied for each message based on its type and that they are not cached and reused. I'm open to reviewing my code and making any necessary adjustments to resolve this issue.

Thank you for your help!

**Comment by burhanaksendir** [comment]
Hi @AkshayStackSum,
I'm experiencing the same issue. I've set up separate sound notifications for five different events, but it keeps playing the same sound for all of them. Have you been able to find a solution?

**Comment by burhanaksendir** [comment]
I struggled quite a bit, but I finally resolved the issue.
Make sure that you define a unique notification channel for each message type. The channel parameter in AndroidNotificationDetails should be different for different message types. This helps to avoid any caching or conflicts.

Here's a modified version of your code with these suggestions:

try {
  final id = DateTime.now().millisecondsSinceEpoch ~/ 1000;

  AndroidNotificationDetails androidNotificationDetails;
  if (message.data['type'].toString().trim() == "sos") {
    androidNotificationDetails = AndroidNotificationDetails(
      "sos_channel", // Unique channel for "sos" type
      "pushnotificationappchannel",
      importance: Importance.max,
      priority: Priority.high,
      sound: RawResourceAndroidNotificationSound('alert'),
      playSound: true,
    );
  } else {
    androidNotificationDetails = AndroidNotificationDetails(
      "default_channel", // Unique channel for other types
      "pushnotificationappchannel",
      importance: Importance.max,
      priority: Priority.high,
    );
  }
  
 await _notificationsPlugin.cancel(id); // Cancel previous notification
  await _notificationsPlugin.show(
    id,
    message.notification!.title,
    message.notification!.body,
    NotificationDetails(android: androidNotificationDetails),
    payload: message.data['_id'],
  );
} on Exception catch (e) {
  debugPrint(e.toString());
}

By ensuring unique channels for each message type and canceling previous notifications with the same ID, you should avoid caching issues and have custom sounds applied correctly based on the message type.

**Comment by AkshayStackSum** [comment]
Thank you so much for the help
My issue was resolved.
