### ISSUE TITLE
Flutter local Notification Error

### ISSUE THREAD

**Issue by devendra257** [MaikuB/flutter_local_notifications#2132]
[](url)
<img width="1358" alt="Screenshot 2023-10-19 at 6 43 06 PM" src="https://github.com/MaikuB/flutter_local_notifications/assets/141297341/12bf0c9f-4d05-4bcf-8083-4c7e43957396">
Please Check this error

**Comment by truongtm0598** [comment]
![Screenshot 2023-10-24 at 09 05 50](https://github.com/MaikuB/flutter_local_notifications/assets/43260383/73ae3d41-4ba0-4cc1-91dc-5b70c852bfa7)

I have an error same you. then, I saw it in this document

**Comment by devendra257** [comment]
Thank u sir 
Solved
