### ISSUE TITLE
onDidReceiveBackgroundNotificationResponse ios doesnt work since pakage version 15.1.2

### ISSUE THREAD

**Issue by mahirandigital** [MaikuB/flutter_local_notifications#2134]
IOS background push notification cannot handle when tapping the notification bubble? can someone solve it? I treat u a teh tarik

**Comment by MaikuB** [comment]
The `onDidReceiveBackgroundNotificationResponse` is currently only for notification actions. There's no support for dealing with tapping on the notification itself so perhaps this is where your confusion lies

**Comment by dinesh-brilworks** [comment]
This is what the code documentation says,
<img width="757" alt="Screenshot 2024-02-13 at 7 15 19 PM" src="https://github.com/MaikuB/flutter_local_notifications/assets/109799878/c1a4d656-c5a6-456f-bab2-de3612ad2d5d">

**Comment by MaikuB** [comment]
That's the documentation for the typedef. It is not the callback itself

**Comment by MarlonS05** [comment]
How would you recommend to check if the notification was tapped while the App is in the background or foreground?

**Comment by yuran09** [comment]
@MaikuB I am also having this same situation. Closing the issue does not solve. How can we trigger events when user clicks the bubble itself??

**Comment by aclowkey** [comment]
Hey @MaikuB, thanks for this amazing repo! It's so useful, appreciate it!
I'm also struggling with handling the background notifications on Android.

I want to navigate to a specific route inside my app when notification is tapped.
This works on iOS - background / foreground, and on Android - Foreground.
But when the app is shutdown on Android - it won't work..

Do you have an idea what can be done to make it work?

**Comment by SeakyLuo** [comment]
@MaikuB Hi, can you please make the readme clearer on how to handle the tapping notification event properly? Or what needs to be set? The readme is too long and really looks like it is ok to just have a `onDidReceiveNotificationResponse` by looking up this keyword around the context.

**Comment by Levi-Lesches** [comment]
@SeakyLuo  I'm currently rewriting the README and splitting it into smaller sections in #2477. It's very much a work in progress, but there is a [section](https://github.com/Levi-Lesches/flutter_local_notifications/blob/readme-refactor/flutter_local_notifications/docs/usage.md#the-initialize-function) on notification handlers. Hoping to push this out sometime this month!

**Comment by lukepighetti** [comment]
> [@SeakyLuo](https://github.com/SeakyLuo) I'm currently rewriting the README and splitting it into smaller sections in [#2477](https://github.com/MaikuB/flutter_local_notifications/pull/2477). It's very much a work in progress, but there is a [section](https://github.com/Levi-Lesches/flutter_local_notifications/blob/readme-refactor/flutter_local_notifications/docs/usage.md#the-initialize-function) on notification handlers. Hoping to push this out sometime this month!

nice docs! saw the section on detecting how the app was launched. curious how we can get the same type event if the app is already running and a notification is tapped
