### ISSUE TITLE
How to Prevent Past-Due Notifications in Flutter Using Flutter Local Notification Plugin?

### ISSUE THREAD

**Issue by burhanaksendir** [MaikuB/flutter_local_notifications#2137]
I'm using the Flutter Local Notification plugin to schedule notifications for future dates and times in my Flutter app. I want to handle the scenario where if the user restarts their device, notifications that were scheduled for a time in the past should not be displayed when the device is opened.

What is the recommended approach to prevent past-due notifications from appearing when using the Flutter Local Notification plugin in Flutter? For instance, if a scheduled notification is set for 27.10.2023 at 21:05, but the user restarts their device and opens the app at 27.10.2023 at 22:10, how can I ensure that the past-due notification does not appear?

**Comment by MaikuB** [comment]
It's not possible as the native iOS/macOS APIs behave like you described. If you are fine with an inconsistent UX where past notifications appear on iOS/macOS but not on Android then you can fork the plugin and comment out this line https://github.com/MaikuB/flutter_local_notifications/blob/033aea63808f4aa5fa817a258d1fdc9e9cd852f1/flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/ScheduledNotificationBootReceiver.java#L20

**Comment by burhanaksendir** [comment]
Hi @MaikuB ,

Thanks. I tried the suggested approach, but unfortunately, it didn't work as expected. However, I made some modifications to the loadScheduledNotifications method to handle past notifications more effectively. Here's the updated method:

```
private static ArrayList<NotificationDetails> loadScheduledNotifications(Context context) {
    ArrayList<NotificationDetails> scheduledNotifications = new ArrayList<>();
    SharedPreferences sharedPreferences =
            context.getSharedPreferences(SCHEDULED_NOTIFICATIONS, Context.MODE_PRIVATE);
    String json = sharedPreferences.getString(SCHEDULED_NOTIFICATIONS, null);

    if (json != null) {
        Gson gson = buildGson();
        Type type = new TypeToken<ArrayList<NotificationDetails>>() {}.getType();
        ArrayList<NotificationDetails> allNotifications = gson.fromJson(json, type);

        long currentTimeMillis = System.currentTimeMillis();

        for (NotificationDetails notification : allNotifications) {
            // If the notification's time has not passed, add it to the list.
            if (notification.millisecondsSinceEpoch > currentTimeMillis) {
                scheduledNotifications.add(notification);
            } else {
                // If the notification's time has passed, log for debugging purposes.
                Log.d("DebugNotification", "Notification expired: " + notification.toString());
            }
        }
    }

    // Log all notifications for debugging purposes.
    for (NotificationDetails notification : scheduledNotifications) {
        Log.d("DebugNotification", "Active Notification: " + notification.toString());
    }

    return scheduledNotifications;
}

```

**Comment by MaikuB** [comment]
Yep adding the date check is the correct approach. What I mentioned before is incorrect as I think I misunderstood it as not wanting any notifications to be rescheduled on reboot when I replied back then

**Comment by burhanaksendir** [comment]
Thanks @MaikuB,
If you could add a setting to the Flutter local notifications package that allows us to manage this behavior, it would be very helpful for everyone who needs such functionality like mine.

**Comment by burhanaksendir** [comment]
@MaikuB  Is it possible to achieve the same effect on the iOS side? Could you please guide me to the class or method similar to loadScheduledNotifications on the iOS side?

**Comment by MaikuB** [comment]
No I mentioned this in my original reply
