### ISSUE TITLE
version 16 FlutterLocalNotificationsPlugin  Undefined class 'FlutterLocalNotificationsPlugin'.

### ISSUE THREAD

**Issue by hidayet-poscu** [MaikuB/flutter_local_notifications#2138]
I get this error in Version 16. When I upgrade to version 15, I don't get any errors.
mistake:
Undefined class 'FlutterLocalNotificationsPlugin'.
Try changing the name to the name of an existing class, or creating a class with the name 'FlutterLocalNotificationsPlugin'.

**Comment by MaikuB** [comment]
Can't help you here as this would be an issue with your local environment and there are posts elsewhere on this repository that indicates others in the community have no such issues with version 16. You may have to try something like cleaning your pub cache to resolve this

**Comment by hidayet-poscu** [comment]
> Can't help you here as this would be an issue with your local environment and there are posts elsewhere on this repository that indicates others in the community have no such issues with version 16. You may have to try something like cleaning your pub cache to resolve this

The problem seems to be caused by the Apple M1 chip. When I clone your example, it gives the same error.

**Comment by Lukas2019** [comment]
I have the same problem. Have you found a solution? @hidayet-poscu

**Comment by hidayet-poscu** [comment]
> Aynı sorun bende de var. Bir çözüm buldunuz mu?@hidayet-poscu

I changed the package version. It fixed the issue.
