### ISSUE TITLE
Change icon to gray icon in status bar and colorful icon in notification panel on Android.

### ISSUE THREAD

**Issue by AlexVincent525** [MaikuB/flutter_local_notifications#214]
Hi dear author!
Now the plugin triggered notification with colorful icon in status bar, and gray icon when notification shown. But as many applications does, they use gray icon in status bar instead of a color one.
![image](https://user-images.githubusercontent.com/15884415/56337087-f2be5900-61d5-11e9-841f-903b2271b15a.png)
![image](https://user-images.githubusercontent.com/15884415/56337094-fe118480-61d5-11e9-9ef0-95dd11a53eac.png)
(Android 8.0 here)

That will made the application seems to be a little weird :(
Considered this as an enhancement plz~

**Comment by MaikuB** [comment]
This seems to be more of how you've created your notification icon and how you set up your notification. The colour in the status bar is determined by the OS. The ability to set the colour of the icon in the actual notification is already there and is in the example app. I suggest you look at that code and run it up

**Comment by AlexVincent525** [comment]
@MaikuB Thank you for your quick reply! And I read the example again with that configuration found~ Sorry for this issue.
