### ISSUE TITLE
[solved]stuck and cost a lot of cpu and memory after startup when run ios version on mac

### ISSUE THREAD

**Issue by andychucs** [MaikuB/flutter_local_notifications#2151]
My app is stuck on the startup after i add this package. just on macOS under iPad mode, the same release on iPhone and iPad is run well. 

sorry, i do not get some useful log to provide. because the flutter can not debug in this mode.  when i get i will update this issue.

it just stuck and cost a lot of cpu and memory after startup.

plateform: macOS 14.0 MacBook Air (M1, 2020) 

install by TestFlight

AppDelegate.swift is same as the example:
https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/example/ios/Runner/AppDelegate.swift

**Comment by MaikuB** [comment]
I've not heard of iPad mode so be curious to know more on this. Putting that aside a plugin doesn't specify what architecture it can or can't support so suspect there's another issue going on as it should work. It's actually applications that specify the supported architectures. I have an M2 MacBook and was able to run the example app on it as well

**Comment by andychucs** [comment]
@MaikuB Thanks for reply.

About the "iPad mode," I mean running iOS or iPadOS apps on a Mac. 
https://developer.apple.com/documentation/apple-silicon/running-your-ios-apps-in-macos
https://support.apple.com/guide/app-store/iphone-ipad-apps-mac-apple-silicon-fird2c7092da/mac

I haven't created a minimal reproducible sample yet. This issue was just discovered while I was testing previous versions of my app on the App Store. I will try to reproduce it by publishing  the example app on TestFlight. If successful, I will publish a test link here.

**Comment by andychucs** [comment]
It solved by flutter upgrade.
I am not sure which flutter version fix it.
After flutter sdk upgrade from 3.13 to 3.16 without any code change about `flutter_local_notifications`, my app work fine and the example app also work fine on Mac.
<img width="917" alt="截屏2023-12-14 21 45 36" src="https://github.com/MaikuB/flutter_local_notifications/assets/24852023/7c92851a-f9fa-45ad-ba51-069ccb0eecfa">
