### ISSUE TITLE
Cancel Notification using AndroidNotificationAction does nothing in 16.1.0 Regression

### ISSUE THREAD

**Issue by cekrozl1** [MaikuB/flutter_local_notifications#2152]
Add an Android Notification Action with showsUserInterface set to false and cancelNotification True.

In version 15.1.2 it cancels the notification - I set the title to this one to "Ignore".
In version 16.1.0 it doesn't cancel the notification. Using the same code does nothing.

I rolled back to 15.1.2 in the meantime.

**Comment by cekrozl1** [comment]
https://github.com/MaikuB/flutter_local_notifications/assets/86661185/7e278c15-ca8d-42b5-9a12-818a9869511d


https://github.com/MaikuB/flutter_local_notifications/assets/86661185/f5db9f11-4dd8-447d-b401-6a27b3c3b353

**Comment by cekrozl1** [comment]
I've added 2 videos to explain.
v15 is capturing the click on "ignore" and cancelling the push notification.
v16 is not. Clicking on "Ignore" doesn't seem to be taken into account.

**Comment by WesselvanDam** [comment]
I am having the same issue on 16.1.0

**Comment by MaikuB** [comment]
I'm guessing that you hadn't checked the change log where there documented breaking changes around the manifest file that would also impact notification actions. Please have a read through around the updated setup

**Comment by cekrozl1** [comment]
Hey @MaikuB !

I read a series of change logs but I cannot link any of them to this issue. 

More specifically, I can't figure out if the combination `showsUserInterface:false + cancelNotification:true` in androidNotificationAction :
1. Cannot be used to cancel a notification from version 16.1.0+ 
2. Can cancel the notification, if "a change" is performed in the manifest file

Both of these raise more questions such as : 
1. What can be used to dismiss a notification
2. What should be changed in the manifest file

**Comment by MaikuB** [comment]
You need to be checking the changelog and associated readme entry as this covers all the details. There's no bug here as if you run the example app then you will find that it still works as expected and you can cross reference what you have with the example app as well

**Comment by cekrozl1** [comment]
Hi @MaikuB,

Thank you for your answer but I cannot find an equivalent to this specific action in the example:

``` dart
AndroidNotificationAction( 'ignore', 'Ignore',  
showsUserInterface: false, // opens the app 
cancelNotification: true, // removes the notification
);
```

Can you tell me which `AndroidNotificationAction` configuration cancels the notification in 16.1.0?

**Comment by cekrozl1** [comment]
Hey @MaikuB,

I added the entirety of the Manifest File from the pub.dev v. 15.1.2 to my own manifest file and guess what? 
**It's working again**
Now it's a matter of removing the lines one by one to figure out which ones are required for the cancel.

Thanks for the RTFM tip ;)

**Comment by cekrozl1** [comment]
This was it:
`<receiver android:exported="false" android:name="com.dexterous.flutterlocalnotifications.ActionBroadcastReceiver" />`
