### ISSUE TITLE
[Android] Creating a notificagtion containing a large image / thumbnail

### ISSUE THREAD

**Issue by florian-obernberger** [MaikuB/flutter_local_notifications#2154]
I was wondering how to attach an image / thumbnail to a notification on Android?

I looked through all the issues and documentation and couldn't find anything... – I hope I didn't just overlook it.

I'd love to now if and / or how this is possible :)

Also thank you so so much for creating this amazing package!

**Comment by MaikuB** [comment]
You'll need to refer to the native APIs and what they support first as plugins like this are wrappers to said native APIs. This is  crucial as you should be trying to understanding how the platforms you target work and what is/isn't feasible. After that, is when you should look at if the plugin exposes the native APIs you need as you may need to cover the gaps or even come up with your own solution.

In addition to that what I mentioned above, you can look at the example app to see if one of the scenarios cover what's you need as it covers nearly all of the scenarios that the plugin supports. If there's one then you can look at the related code snippet
