### ISSUE TITLE
We need an ability to optionally use setExactAndAllowWhileIdle for Android

### ISSUE THREAD

**Issue by alexandr2levin** [MaikuB/flutter_local_notifications#216]
The name speaks for itself :D

**Comment by MaikuB** [comment]
This has been noted but has some extra implications when it comes to recurring notifications as that would require scheduling the next notification after one has been fired. Happy to look at a PR for this if anyone wants to take a stab at it

**Comment by MaikuB** [comment]
Closing this should be supported in 0.8.0
