### ISSUE TITLE
[iOS] Conflict with OpenCV

### ISSUE THREAD

**Issue by MarkerwApk** [MaikuB/flutter_local_notifications#2160]
Hi,

I can't build app with plugin and OpenCv Library. I have conflicts:

`duplicate symbol '_OBJC_CLASS_$_Converters' in:
    /Users/user/Workspace/Flutter/libero/build/ios/Debug-gkDev-iphoneos/flutter_local_notifications/flutter_local_notifications.framework/flutter_local_notifications[4](Converters.o)
    /Users/user/Workspace/Flutter/libero/ios/opencv2.framework/Versions/A/opencv2[arm64][841](Converters.o)

duplicate symbol '_OBJC_METACLASS_$_Converters' in:
    /Users/user/Workspace/Flutter/libero/build/ios/Debug-gkDev-iphoneos/flutter_local_notifications/flutter_local_notifications.framework/flutter_local_notifications[4](Converters.o)
    /Users/user/Workspace/Flutter/libero/ios/opencv2.framework/Versions/A/opencv2[arm64][841](Converters.o)

d: 2 duplicate symbols
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

Can You help me found solution?

**Comment by MarkerwApk** [comment]
I create PR: https://github.com/MaikuB/flutter_local_notifications/pull/2175

**Comment by MaikuB** [comment]
Closing this as original PR hasn't had updates to it after leaving feedback
