### ISSUE TITLE
Notification icon not appear on Android 10+

### ISSUE THREAD

**Issue by menezes85** [MaikuB/flutter_local_notifications#2168]
Hello guys, i am using this fantastic plugin for some time and im experiencing this issue, notification icon only appears on android <=10, newer versions (11,12 and 13) not working, im using ic_launcher as default no custom.., is this a bug or i miss some config ? 
Thanks

**Comment by DavidOrakpo** [comment]
I'm having the same issue as well

**Comment by menezes85** [comment]
Seems a bug in package, i really hope dev team reply us.

**Comment by menezes85** [comment]
Hello @MaikuB  after a deep search really not a plugin bug, it is android itself behaviour changes , generate correct those icons on newer android became a bit more complex, point is generate icon transparent and correct size via assets studio, it worked, we can close this for now, thanks for your time.

**Comment by MaikuB** [comment]
Thanks. Note that for future reference that you can close issues that you create on GitHub
