### ISSUE TITLE
Notification action button tap is not working properly

### ISSUE THREAD

**Issue by navaghandabhi** [MaikuB/flutter_local_notifications#2169]
Notification action button tap is not working properly i have two AndroidNotificationAction in diffrent notification in every notification first button is working fine but second button not working not triggring on NotificationResponseType.selectedNotificationAction this point but when i downgrade the version of package to 15.1.0+1 this is working fine when i upgrade the latest version then this issue is faced

**Comment by MaikuB** [comment]
If you believe there is an issue then you'll need to provide a link to a repo hosting a minimal app that can reproduce the problem. It would best if you can reproduce this with the example app first and you can fork the repo and if needed, update the code in the example to demonstrate the issue

**Comment by MaikuB** [comment]
Closing due to lack of response with the requested information
