### ISSUE TITLE
Issue establishing dependencies

### ISSUE THREAD

**Issue by shubhendumadhukar** [MaikuB/flutter_local_notifications#217]
I am trying to use the flutter_local_notification.dart to implement the notifications in my app. However while compilation I get below error:
`Your application could not be compiled, because its dependencies could not be established.
The following Dart file:
 <Path>\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_local_notifications-0.6.1\lib\flutter_local_notifications.dart
...refers, in an import, to the following library:
  <Path>\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_local_notifications-0.6.1\lib\src\platform_specifics\android\styles\default_style_information.dart
Unfortunately, that library does not appear to exist on your file system.`

I checked the required directory and the file default_style_information.dart already exists. Any idea why the above error while establishing dependencies?

**Comment by MaikuB** [comment]
probably something's gone with your dev environment. have you tried running `flutter clean` followed by `flutter packages get`? other thing to try is to reinstall the pub packages by running `flutter packages pub cache repair`

**Comment by shubhendumadhukar** [comment]
I encountered a similar results. Here are the things that I tried:
1. `flutter clean` then `flutter packages get`
2. `flutter clean` then `flutter packages get` then `flutter packages upgrade`
3. `flutter packages pub cache repair`

And though this might seems silly, I even tried creating a whole new project itself. I faced same error i.e. `Unfortunately, that library does not appear to exist on your file system.`

**Comment by MaikuB** [comment]
Not something I've been able to reproduce though I've read of some people who have had similar issues with other packages with no apparent reason unless the pub cache was somehow corrupt. Am wondering if your flutter installation is corrupt and requires running the instructions provided [here](https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#flutter-installation-corrupted)

**Comment by MaikuB** [comment]
Closing as there's nothing I can really do to help here as it's environmental
