### ISSUE TITLE
[Suggestion] Better error handling when android notification image is invalid

### ISSUE THREAD

**Issue by j-q-in-berlin** [MaikuB/flutter_local_notifications#2171]
**Describe the bug**
I had an invalid image as a notification image, because we changed our app logo and the notifications stopped working.

**To Reproduce**
Change notification image to invalid image.

**Expected behavior**
I expected an error related to this problem. Instead the notifications just stopped working and it took me a long time to find the cause.

**Comment by MaikuB** [comment]
There's already code around this in the plugin so if your have ideas on how to improve it then please look it submitting a PR. Presumably this is on Android so I would have expected this to show up on logcat. It sounds like you are talking about scheduled notifications too. If so, the place to check would have been something like logcat as it's happening in the background independently of the app running
