### ISSUE TITLE
how to hide or show the notifications for any particular day or time 

### ISSUE THREAD

**Issue by sumitmishra0** [MaikuB/flutter_local_notifications#2172]
If a user decides to turn on or off daily notifications, but we have already set notifications for specific days, how can we hide or display the notifications accordingly? For instance, if the user wants to turn off the notifications for today only, how can we hide all notifications that are scheduled for today? If the user decides to turn on daily notifications again tomorrow, they should receive notifications as per the usual schedule. 

@wanbok @domesticmouse @robert-ancell @dluksza 

I have added the code for reference.

class NotificationService {
  final FlutterLocalNotificationsPlugin notificationsPlugin =
      FlutterLocalNotificationsPlugin();

  // Android-specific settings for the notification.
  final androidPlatformChannelSpecifics = const AndroidNotificationDetails(
    'custom_habit_channel_id',
    'Custom Habit Notifications',
    channelDescription: 'Get custom habit notifications',
    importance: Importance.defaultImportance,
    priority: Priority.defaultPriority,
    enableVibration: true,
    playSound: true,
  );

    // iOS-specific settings for the notification.
    final iOSPlatformChannelSpecifics = const DarwinNotificationDetails(
      presentAlert: true,
      presentBadge: true,
      presentSound: true,
      presentBanner: true,
      // subtitle : '',

    );

  notificationDetails() async {
    return  NotificationDetails(
        android: androidPlatformChannelSpecifics,
        iOS: iOSPlatformChannelSpecifics);
  }

  Future scheduleNotification(
      {required int id,
      String? title,
      String? body,
      String? payLoad,
      required DateTime scheduledNotificationDateTime}) async {
    return notificationsPlugin.zonedSchedule(
        id,
        title,
        body,
        // tz.TZDateTime(tz.local, scheduledNotificationDateTime.year, scheduledNotificationDateTime.month, scheduledNotificationDateTime.day, scheduledNotificationDateTime.hour, scheduledNotificationDateTime.minute,),
        tz.TZDateTime.from(
          scheduledNotificationDateTime,
          tz.local,
        ),
        await notificationDetails(),
        androidAllowWhileIdle: true,
        uiLocalNotificationDateInterpretation:
            UILocalNotificationDateInterpretation.absoluteTime);
  }

  Future<void> scheduleCustomHabitNotifications (
      {required List<List<int>> remindertime,
      required DateTime startDate,
      required DateTime endDate,
      String title = 'Habit Tracker',
      String body = 'Reminder Alert'}) async {
    // Schedule notifications for each day between the start and end dates at custom times.
    for (DateTime date = startDate;
        date.isBefore(endDate) || date.isAtSameMomentAs(endDate);
        date = date.add(Duration(days: 1))) {
      for (List<int> time in remindertime) {
        DateTime combinedTime =
            DateTime(date.year, date.month, date.day, time[0], time[1]);
        if (combinedTime.isAfter(DateTime.now())) {
          Logger.log(message: "Schedule Notification for $combinedTime");
          await scheduleNotification(
              id: DateTime.now().millisecondsSinceEpoch & 0x7FFFFFFF,
              title: title,
              body: body,
              scheduledNotificationDateTime: combinedTime);
        }
      }
    }
  }
}

**Comment by MaikuB** [comment]
@sumitmishra0 not possible. In future you should check to make sure you check what the native APIs support as this should be the first step before looking at plugins to design a solution that meets the needs for your app. Kindly ask that you also avoid tagging randomly in the future as well
