### ISSUE TITLE
Why messageType , senderId ,category and some other data  is null ?

### ISSUE THREAD

**Issue by mazab99** [MaikuB/flutter_local_notifications#2173]
{
  "to": "c4TU6jxJTvGHFI2SLQPDCI:APA91bGNCT38rHNhSk_CfZFo2VlCE9Z_zK1L8pkqJ7a51nILSVHk38o-g2VHcaM_2WoRL0I4EY5DazVNxypmybePFJYYU9bK52empf6BI37Ytm3GZLvloAYze3J7PUJhQ_a_85LKonC2",
  "senderId": "905941271224",
  "category": "navigation",
  "collapseKey": "q_notification",
  "contentAvailable": true,
  "data": {},
  "from": "905241272032",
  "messageId": "0:1701354443523651%ee6fccc3ee6fccc4",
  "messageType": "Chat",
  "mutableContent": true,
  "notification": {
    "title": "Huston! The eagle has landed!",
    "body": "A small step for a man, but a giant leap to Flutter's community!",
    "android": {
      "channelId": "MahmoudID"
    }
  },
  "sentTime": 1701354443498,
  "ttl": 2419200
}

 onMessage ====>>>{senderId: null, category: null, collapseKey:q_notification, contentAvailable: false, data: {}, from: 905241272032, messageId: 0:1701601752914434%ee6fccc3ee6fccc3, messageType: null, mutableContent: false, notification: {title: Huston! The eagle has landed!, titleLocArgs: [], titleLocKey: null, body: A small step for a man, but a giant leap to Flutter's community!, bodyLocArgs: [], bodyLocKey: null, android: {channelId: null, clickAction: null, color: null, count: null, imageUrl: null, link: null, priority: 0, smallIcon: null, sound: null, ticker: null, tag: null, visibility: 0}, apple: null, web: null}, sentTime: 1701601752897, threadId: null, ttl: 2419200}

**Comment by mazab99** [comment]
and I send mutableContent > true
but I got it in response in false ?

**Comment by malukishtiaq** [comment]
It must be parsing issue. Try to test without using all these params. And then update it.

**Comment by MaikuB** [comment]
The content in your posts isn't to do with this plugin, it's to do with the firebase messaging

**Comment by malukishtiaq** [comment]
This post serves as a concept for incorporating notifications using Firebase along with local notifications. It is not exclusively focused on local notifications.

**Comment by MaikuB** [comment]
Even if the original poster is looking to use local notifications (note: they not said anything sort though), the issue they are asking is specifically to do with firebase messaging so should be asked on the associated repository
