### ISSUE TITLE
Flutter_Local_Notifications : The backgroundHandler needs to be either a static function or a top level function to be accessible as a Flutter entry point.

### ISSUE THREAD

**Issue by KetutKusuma** [MaikuB/flutter_local_notifications#2176]
**Explanation
the code doing well until i add ondidnotificationbackground on Android, maybe this is my fault but i think i was follow all the README, but it is still show can you help me to fix this bug??

**Sample code to reproduce the problem**
this is my code : 
<img width="705" alt="image" src="https://github.com/MaikuB/flutter_local_notifications/assets/71806737/7a3049b6-3c78-461f-81ba-721e8aa14eee">

and the error : 
[log] Error catch on init notification firebase : 'package:flutter_local_notifications/src/platform_flutter_local_notifications.dart': Failed assertion: line 872 pos 12: 'callback != null':           The backgroundHandler needs to be either a static function or a top 
                level function to be accessible as a Flutter entry point.

**Comment by ming-chu** [comment]
I think changing to a static method can help.
```dart
 static void notificationTapBackground(NotificationResposne notificationResponse) {
```

**Comment by MaikuB** [comment]
You will need to fix your code and the error message explains this

**Comment by zaid-bashir** [comment]
Yeah This error will gone if you change method to static but the code inside static method is not executing
(This is in my case what i saw).

**Comment by sunil-singh-chaudhary** [comment]
did any solution for this i am still getting same erorr i declared it outside too

**Comment by KetutKusuma** [comment]
thank you it was solve

**Comment by KetutKusuma** [comment]
> did any solution for this i am still getting same erorr i declared it outside too 

follow the top comment and it will solve

**Comment by davidakinfenwa** [comment]
> thank you it was solve

How did you solve it

**Comment by devmfouad** [comment]
same issue with me and i moved the background to the top outside the class but same error happened

**Comment by imsumit0303** [comment]
I have tried both, 
1. I shifted backgroundHandler on top,  It  gives error on launching the app the app, but as notification  comes backgroundHandler method gets called.
2. I tried by making it static as well. It  gives the same error.
Why error is coming on app launch. 
Please help in this regards.

**Comment by rashedswen** [comment]
> I have tried both,
> 
> 1. I shifted backgroundHandler on top,  It  gives error on launching the app the app, but as notification  comes backgroundHandler method gets called.
> 2. I tried by making it static as well. It  gives the same error.
>    Why error is coming on app launch.
>    Please help in this regards.

@imsumit0303 
any one have this issue make your function `static void` then write _flutterLocalNotificationsPlugin.initialize like this


```
_flutterLocalNotificationsPlugin.initialize(
      initSettings,
      onDidReceiveBackgroundNotificationResponse: localNotificationHandler,
      onDidReceiveNotificationResponse: (details) =>
          flutterNotificationClick(details.payload),
    );

```

from 

```
_flutterLocalNotificationsPlugin.initialize(
      initSettings,
      onDidReceiveBackgroundNotificationResponse: (details) =>
          localNotificationHandler(details),
      onDidReceiveNotificationResponse: (details) =>
          flutterNotificationClick(details.payload),
    );
```

I don't now why but it work
