### ISSUE TITLE
iOS privacy manifest required

### ISSUE THREAD

**Issue by stuartmorgan** [MaikuB/flutter_local_notifications#2177]
This plugin is listed on https://developer.apple.com/support/third-party-SDK-requirements/ as requiring a privacy manifest. Some action will be required, either to clarify with Apple whether this plugin should be on the list, or to add a privacy manifest.

See https://github.com/flutter/flutter/issues/131940 for context.

**Comment by MaikuB** [comment]
Will do. Unfortunately last time I got a generic answer to reference their docs even when I explained what my plugin does and asked if it was needed

**Comment by yuk1ch1** [comment]
the reason might be that this package uses other packages listed by Apple here
Might be helpful to check this out:

https://developer.apple.com/support/third-party-SDK-requirements/

I'm not totally sure, but it looks like you might need to:
- update these dependency packages 
- signatures for SDKs
- prepare a PrivacyInfo.xcprivacy

[FYI]
> In [flutter/flutter#131940 (comment)](https://github.com/flutter/flutter/issues/131940#issuecomment-1881641272) it states, that plugins that do not collect data should include an empty privacy manifest. I'm assuming that holds true here too.

ref: https://github.com/pichillilorenzo/flutter_inappwebview/issues/1909#issuecomment-1883014512

**Comment by MaikuB** [comment]
@yuk1ch1 it doesn't use other packages when it comes to iOS/macOS and only calls native APIs so is one of the reasons why I tried to ask for more details. I have seen the details of using an empty manifest so am aware of of that being a solution, just haven't gotten to it yet but will accept PRs on it

**Comment by Miya49-p0** [comment]
@MaikuB 
hi

It seems that UserDefaults are being used in this package. It may still require PrivacyPrivacyManifest support. Could you please confirm this?

I'd appreciate it if you could check this.

**Comment by MaikuB** [comment]
@Miya49-p0 Thanks for catching that. Sounds like updates to the manifest would be needed. If you happened to have already looked into this that you can submit a PR then that would be most welcome
