### ISSUE TITLE
I added keep.xml  and I change the sound as I want ,now I don't understand what is the benefit of it or why  we added it ?

### ISSUE THREAD

**Issue by mazab99** [MaikuB/flutter_local_notifications#2180]
<?xml version="1.0" encoding="utf-8"?>
<resources xmlns:tools="http://schemas.android.com/tools"
    tools:keep="@drawable/*,@raw/my_sound" />

**Comment by MaikuB** [comment]
If you want to know then you need to read the information that is linked to in the readme
