### ISSUE TITLE
Custom notification function only with emulator

### ISSUE THREAD

**Issue by lopallo** [MaikuB/flutter_local_notifications#2182]
If I use the android emulator I can choose whether to use the default notification sound or ringtone. If I use the release version of the play store the sound works by default but does not play sounds if the soundDefault variable is true:

Future<void> scheduleNotification(
    String title,
    String body,
    DateTime eventDate,
    String eventTime,
    int eventId,
    bool notificaBool,
    int advanceNotice,
    bool soundDefault,
  ) async {
    
    final formattedDateTimeString =
        '${eventDate.year}-${eventDate.month.toString().padLeft(2, '0')}-${eventDate.day.toString().padLeft(2, '0')} $eventTime:00.000';

    
    final parsedEventTime = DateTime.parse(formattedDateTimeString);

    
    if (parsedEventTime.isAfter(DateTime.now()) && notificaBool) {
      
      final delayNotice =
          parsedEventTime.subtract(Duration(minutes: advanceNotice));
      print(delayNotice);

     
      FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
          FlutterLocalNotificationsPlugin();
      flutterLocalNotificationsPlugin
          .resolvePlatformSpecificImplementation<
              AndroidFlutterLocalNotificationsPlugin>()
          ?.requestNotificationsPermission();

      AndroidNotificationDetails androidPlatformChannelSpecifics =
          AndroidNotificationDetails(
        soundDefault
            ? 'workSound2' : 'work2',             
        'calendario', 
        importance: Importance.max,
        priority: Priority.high,
        icon: 'logo',
        playSound: true,

        sound: soundDefault
            ? const RawResourceAndroidNotificationSound('ringtone') : null,             
        enableVibration: true,
      );

      NotificationDetails platformChannelSpecifics =
          NotificationDetails(android: androidPlatformChannelSpecifics);

      await flutterLocalNotificationsPlugin.zonedSchedule(
        eventId, 
        title,
        '$body$eventTime',
        tz.TZDateTime.from(delayNotice, tz.local),
        platformChannelSpecifics,
        uiLocalNotificationDateInterpretation:
            UILocalNotificationDateInterpretation.absoluteTime,
        androidScheduleMode: AndroidScheduleMode.exact,
      );
    }
  }

  Future<void> cancelNotification(int eventId) async {
    FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
        FlutterLocalNotificationsPlugin();
    await flutterLocalNotificationsPlugin.cancel(eventId);
  }

**Comment by lopallo** [comment]
the problem is that with custom notification sounds, the popup notification is seen but does not play sounds

**Comment by MaikuB** [comment]
I'm having trouble understanding what you've written. If you believe there's a bug then you'll need to produce a link to a repo hosting a minimal app that can reproduce the issue.

My guess from what you've written is you are seeing different behaviour between debug and release mode. If my guess is correct then you would need to check that you followed https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#release-build-configuration

**Comment by ankarastrix** [comment]
In the release mode, preserving certain resources or files during the app's build for distribution is crucial. Utilizing a file like "keep.xml" within the "raw resources" folder serves this purpose.

During release mode, the app undergoes optimization for enhanced performance and reduced size. This optimization process might lead to the removal of resources not directly referenced in the code but essential for the app's functionality.

By employing a file like "keep.xml" in the "raw resources" folder, you specify a list of resources to retain even when the application undergoes optimization for release. This file typically contains a list of resources—such as images, sounds, or other data—not directly referenced in the application's code but necessary for its proper functioning.

Including "keep.xml" ensures that these specific resources persist in the app, even during the optimization process aimed at improving its distribution-ready version.

[](https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/example/android/app/src/main/res/raw/keep.xml)

**Comment by amervelic** [comment]
In the release mode, preserving certain resources or files during the app's build for distribution is crucial. Utilizing a file like "keep.xml" within the "raw resources" folder serves this purpose.
During release mode, the app undergoes optimization for enhanced performance and reduced size. This optimization process might lead to the removal of resources not directly referenced in the code but essential for the app's functionality.
By employing a file like "keep.xml" in the "raw resources" folder, you specify a list of resources to retain even when the application undergoes optimization for release. This file typically contains a list of resources—such as images, sounds, or other data—not directly referenced in the application's code but necessary for its proper functioning.
Including "keep.xml" ensures that these specific resources persist in the app, even during the optimization process aimed at improving its distribution-ready version.

[keep example](https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/example/android/app/src/main/res/raw/keep.xml)

**Comment by lopallo** [comment]
Fixed by entering the keep.xml file
