### ISSUE TITLE
Duplicate background notification

### ISSUE THREAD

**Issue by A7mdlbanna** [MaikuB/flutter_local_notifications#2183]
**Duplicate background notification**

**To Reproduce**
1. Setup your Firebase Notifications environment 
2. Handle incoming messages with flutter_local_notifications
3. Run the code and go to your phone's home screen (App Background)
4. Send a notification from the Firebase console

**Expected behavior**
You should see duplicate notifications with one log (firebase sent only one notification)

**Sample code to reproduce the problem**
```dart
@pragma('vm:entry-point')
Future<void> handleBackgroundMessage(RemoteMessage message) async {
  final notification = message.notification;
  if (notification == null) return;

  print('Got a message while in the background!');

  final FlutterLocalNotificationsPlugin notificationsPlugin = FlutterLocalNotificationsPlugin();
  await notificationsPlugin.initialize(
    const InitializationSettings(
      android: AndroidInitializationSettings('image'),
      iOS: DarwinInitializationSettings(),
    ),
  );
  await notificationsPlugin.show(
    0,
    notification.title,
    notification.body,
    const NotificationDetails(
      android: AndroidNotificationDetails('test_channel_id', 'test_channel_name'),
      iOS: DarwinNotificationDetails(),
    ),
  );
}

```

**Comment by navaghandabhi** [comment]
can you show your code to sending notification these issue i solved before in my project when i push notification through FCM

**Comment by MaikuB** [comment]
Please check to ensure that you understand how FCM works as FCM itself can show a notification automatically that calling his plugin would then result in an additional notification

**Comment by balaji101010** [comment]
how do I override this behaviour? @MaikuB
