### ISSUE TITLE
Schedule notifications not working in Android 14

### ISSUE THREAD

**Issue by admincode1** [MaikuB/flutter_local_notifications#2185]
Schedule notifications not working since I upgraded my phone to Android 14 using Samsung A53.

Permissions in AndroidManifest:
USE_EXACT_ALARM
SCHEDULE_EXACT_ALARM
POST_NOTIFICATIONS

Expected:
Schedule notifications must be received at exact time.

I have like 10 schedule notifications a day and I receive most of them at once or when opening the App.
Never changed anything since Android 13 except adding the SCHEDULE_EXACT_ALARM.

Any idea what am missing?

**Comment by EArminjon** [comment]
Do you have added POST_NOTIFICATIONS inside your AndroidManifest ?

**Comment by admincode1** [comment]
> Do you have added POST_NOTIFICATIONS permissions inside your AndroidManifest ? i remember got an issue and console ask me to add it.

Yes I already have POST_NOTIFICATIONS permission in AndroidManifest.
The only work around solution I found so far is to disable "Battery Optimization" and all schedule notifications are received on exact time.

**Comment by ZSHUser01** [comment]
Hi, 
I also can confirm that the schedule notications are not working in Android 14 on my Google Pixel 4a 5G at the moment with both SCHEDULE_EXACT_ALARM e POST_NOTIFICATIONS permission enabled in AndroidManifest.

I'd also like to inform you that I've noticed that the scheduled notifications are working only when the app is compiled or is running in debug mode. As soon as I generate the apk file in release mode, the scheduled notifications stop showing on the screen. 

I hope this information can help to understand the cause of the issue.

**Comment by fleckdalm** [comment]
same problem here. any solution in sight?

**Comment by CarstenULarsen** [comment]
Same issue on Galaxy A34 running Android 14.

**Comment by MaikuB** [comment]
The plugin doesn't have anything that's Android 14 specific and I've had Pixel 6 and 8 devices where the example app works as expected on them. If you're experiencing delays then this is outside the control of the plugin and devices that don't run the stock Android OS are susceptible to this issue due to battery optimisations as covered in https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#scheduled-android-notifications. Please have a read of that section that I've linked. If you're seeing differences in OS versions then you'll need to see if the manufacturer introduced further changes.

@ZSHUser01 given what you've described, it would sound like you haven't followed the steps mentioned in https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#release-build-configuration

**Comment by ZSHUser01** [comment]
@MaikuB Thank you for for the feedback. I'll try to refollow the steps described in the README as you suggested. Probably, I' ve missed something in my release build configuration. 

Thank you again for the feedback

**Comment by wer-mathurin** [comment]
@MaikuB  and @ZSHUser01 
I had a similar problem. 

`Unhandled Exception: PlatformException(error, Missing type parameter., null, java.lang.RuntimeException: Missing type parameter.
E/flutter (23073):      at a7.a.d(SourceFile:27)
E/flutter (23073):      at a7.a.<init>(SourceFile:2)
E/flutter (23073):      at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin$a.<init>(SourceFile:1)
E/flutter (23073):      at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.loadScheduledNotifications(SourceFile:26)
E/flutter (23073):      at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.removeNotificationFromCache(SourceFile:1)
E/flutter (23073):      at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.cancelNotification(SourceFile:54)
E/flutter (23073):      at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.cancel(SourceFile:23)
E/flutter (23073):      at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(SourceFile:382)
E/flutter (23073):      at p8.k$a.a(SourceFile:18)
E/flutter (23073):      at g8.c.l(SourceFile:19)
E/flutter (23073):      at g8.c.m(SourceFile:41)
E/flutter (23073):      at g8.c.i(SourceFile:1)
E/flutter (23073):      at g8.b.run(SourceFile:1)`


**And this was cause by a missing the release configuration (proGuard).**  By just adding the _proguard-rules.pro_ everything works fine.

**Comment by PeperMarkreel** [comment]
Same on Galaxy S22 android 14. No problem on iOS, android 9, android 10.

**Comment by PeperMarkreel** [comment]
I need to do some more testing but adding the following parameter to the zonedSchedule notifications are shown at the right time at android 14. 

androidScheduleMode: AndroidScheduleMode.exactAllowWhileIdle,

As alternative I've found that adding the following permission also works (but might cause a Play Store rejection for what I've read. But I doubt they are so strict)

<uses-permission  android:name="android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS"/>

**Comment by MaikuB** [comment]
Note if you're targeting Android 13 or higher,  specifying the permissions in manifest won't be an alternative but actually mandatory for your app. If you specify `android.permission.SCHEDULE_EXACT_ALARM` then you need to ensure that your app also calls the `requestExactAlarmsPermission()` method provided by the plugin as the user needs to decide if they want to grant your app permission. This is mentioned at https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#androidmanifestxml-setup

@admincode1 you should check that you specified 

```
androidScheduleMode: AndroidScheduleMode.exactAllowWhileIdle
```

like @PeperMarkreel mentioned as that is what the plugin exposes to allow for notifications to trigger with exact timing even the phone has been doze/low-power idle mode. Certain Android OEMs may have stricter battery optimisations that is outside of the control the plugin and this is related to what is documented at https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#scheduled-android-notifications. This is something all developers will need to bear in mind and isn't a bug with the plugin but due to customisations done that by Android OEMs to the version of Android OS they put on their devices

**Comment by admincode1** [comment]
After adding "androidScheduleMode: AndroidScheduleMode.exactAllowWhileIdle" to zonedSchedule notifications, notifications are shown in the exact scheduled time. 
Thanks @PeperMarkreel & @MaikuB

**Comment by CarstenULarsen** [comment]
Samsung seems to ignore **setExact()** and **setExactAndAllowWhileIdle()**, but using **setAlarmClock()** is working so far on my end - at least on Galaxy A34. So in .zonedSchedule() you can use:

**androidScheduleMode: AndroidScheduleMode.alarmClock,**

Documentation on "exact alarms":
https://developer.android.com/develop/background-work/services/alarms/schedule#set-exact-alarm

**Comment by Bulgy404** [comment]
Having the same issue here. Has anybody found a way to reliably schedule notifications on Android for all the devices? My app has no problem running on iOS but Android is a pain...

**Comment by PeperMarkreel** [comment]
@Bulgy404 besides the manifest permissions, you'll need to pass it to the zonedSchedule method call, set androidScheduleMode to AndroidScheduleMode.alarmClock. 

When uploading a build to the Google Play store you get a question why you use this functionality, and you'll have to answer it's for agenda or alarm clock use. I chose agenda for my app and it was accepted. Not sure if they agree on my statement in the future.

**Comment by Bulgy404** [comment]
Hey @PeperMarkreel,
thanks for the info. alarmClock was not working on my Google Pixel 8 Pro emulator so I switched to setExactAndAllowWhileIdle() as discussed in previous posts. Hopefully that also works on a real device once I test it :D

**Comment by Jakuzeisme** [comment]
I have a question I'm sure about  use exact alarm but does schedule exact alarm require approval before uploading to the appstore

**Comment by Levi-Lesches** [comment]
Everything requires approval, but I don't know or think this will put you in a special category.

**Comment by Jakuzeisme** [comment]
@Levi-Lesches 
So how do most people solve the problem of scheduling daily reminders if there app isn't an alarm app or clock app?
Thanks for the reply btw

**Comment by Levi-Lesches** [comment]
This page might help you. https://developer.android.com/about/versions/14/changes/schedule-exact-alarms

**Comment by Jakuzeisme** [comment]
Seen that stuff, shit looks like spanish😂😂😂
I kinda started from flutter ,java less. But don't worry, will figure it
out. Imma bad man

**Comment by Jakuzeisme** [comment]
I've actually read them and removed the permissions.
The issue now is that notifications don't come in at all anymore.
And it's the same code.
Only difference was removing those 2 permisions

**Comment by Levi-Lesches** [comment]
Hm, that is tricky. Ignore the workarounds for a second. If the intended behavior of this package isn't functional, like sending non-alarm notifications, please open a separate issue with code to replicate the issue, your flutter, plugin, and Android versions, and any other interesting output. This issue has been closed so the owner will not be looking here for new bugs

**Comment by Jakuzeisme** [comment]
Thanks i might give that a try

**Comment by Jakuzeisme** [comment]
But to be fair I wasn't using this
androidScheduleMode: AndroidScheduleMode.inexactAllowWhileIdle, // or
AndroidScheduleMode.inexact
);

Was using .alarmClock

About to test it tho, let's see

**Comment by Jakuzeisme** [comment]
I think thay may have fixed it.
That one small change shouldn't have so much power  :)
Thanks 2 u all who maintain this package I know it's really hard keeping up
with android bs

**Comment by kamranbekirovyz** [comment]
> Samsung seems to ignore **setExact()** and **setExactAndAllowWhileIdle()**, but using **setAlarmClock()** is working so far on my end - at least on Galaxy A34. So in .zonedSchedule() you can use:
> 
> **androidScheduleMode: AndroidScheduleMode.alarmClock,**
> 
> Documentation on "exact alarms": https://developer.android.com/develop/background-work/services/alarms/schedule#set-exact-alarm

How do you determine whether the device is Samsung or not?

I'll test the following code: 

```
    final bool isSamsung = await DeviceInfoPlugin().androidInfo.then(
      (value) {
        return value.manufacturer.toLowerCase() == 'samsung';
      },
    );

    final AndroidScheduleMode androidScheduleMode = isSamsung
        ? AndroidScheduleMode.alarmClock
        : AndroidScheduleMode.exactAllowWhileIdle;
```

**Comment by robertnicjoo** [comment]
This works for me for all android versions including android versions 12+ :

add these to `Manifest` file

```xml
<uses-permission android:name="android.permission.POST_NOTIFICATIONS" />
<uses-permission android:name="android.permission.SCHEDULE_EXACT_ALARM" android:maxSdkVersion="32"/>
```

**Note:** for android below 12 `<uses-permission android:name="android.permission.SCHEDULE_EXACT_ALARM" android:maxSdkVersion="32"/>` is enough and it will work but for android above version 12 add following to your code

For android 12+ ask permission for SCHEDULE_EXACT_ALARM

```dart
await localNoticiationService.resolvePlatformSpecificImplementation<
            AndroidFlutterLocalNotificationsPlugin>()?.requestExactAlarmsPermission();
```

**Comment by Fukulu** [comment]
If your app category is not related to ALARM, CALENDAR, or HEALTH, do not use this block in your Manifest file. It violates Google Play rules...

```
<uses-permission android:name="android.permission.SCHEDULE_EXACT_ALARM" android:maxSdkVersion="32"/>
```

I only adjust a receiver than everything works fine. Sometimes Notification delayed by android system only a couple minute thats all...

```
    <uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
```


```
<!-- Scheduled Notifications Receivers -->
        <receiver android:exported="false" android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver" />
        <receiver android:exported="false" android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"/>
                <action android:name="android.intent.action.MY_PACKAGE_REPLACED"/>
                <action android:name="android.intent.action.QUICKBOOT_POWERON" />
                <action android:name="com.htc.intent.action.QUICKBOOT_POWERON"/>
            </intent-filter>
        </receiver>
```
