### ISSUE TITLE
[Question] Can i customize repeat interval ?

### ISSUE THREAD

**Issue by z3r0c00l-2k** [MaikuB/flutter_local_notifications#219]
I want show notifications on my app based on the user preference,
which should be in 30 mins interval, 1 hour, 1.5 hour and 2 hour. 
Can i solve this problem with this plugin?

**Comment by MaikuB** [comment]
no it isn't. think your question is similar to #92 and #147

**Comment by z3r0c00l-2k** [comment]
Would you implement this in future updates???

**Comment by MaikuB** [comment]
Sorry missed this but not at this stage. Feel free to submit a PR or consider looking at using platform channels for your own app
