### ISSUE TITLE
receiver class not getting detected in AndroidManifest.xml

### ISSUE THREAD

**Issue by avdhootu27** [MaikuB/flutter_local_notifications#2191]
As per given on pub.dev, I tried adding receiver `<receiver android:exported="false" android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver" />` and others in AndroidManifest.xml file.

After adding, I found only "com." part of the name is in green color and other part is in red color. Why is this so?
It looks like those classes are not getting detected
![Screenshot from 2023-12-29 19-36-03](https://github.com/MaikuB/flutter_local_notifications/assets/72180606/8b82d951-3705-4eec-9c92-7293dc0d98ac)
Is this issue is because of IDE or project? I have added the package in pubspec.yaml

And also scheduled notifications are not showing when app is killed. I was testing on Redmi Note 7S device

**Comment by MaikuB** [comment]
That would be an IDE issue as if there was a legitimate problem then you would've also noticed issues with scheduled notifications when the app is running and presumably you have already confirmed that works.

As for the other issue, this is covered in the readme and outside the control of the plugin as it's to do with your device. Please read https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#scheduled-android-notifications
