### ISSUE TITLE
Crash while debugging

### ISSUE THREAD

**Issue by mgriffin27** [MaikuB/flutter_local_notifications#2192]
Awesome plugin!  I am porting an Android Java app to Flutter, this plugin is a lifesaver.

Here's the crash I am seeing.  It reproduces using the sample app from pub.dev.

1) run the app
2) grant notification permission at dialog box
2) try out some notifications
3) go into Android settings and disable notifications for the sample app
4) return to the app and it has crashed

This happens on the Emulator.

It also happens on a USB attached device while it's plugged in and running debug.  If I unplug the phone and try the reproduction steps it does not crash.

**Comment by MaikuB** [comment]
Thanks for reporting this but not something the plugin can solve and possibly a limitation of debugging as there aren't even any logs relating to the plugin. It's not specific to this plugin so I suspect this is how the debugger works and noticed entries in logcat around the app being forced to stop. Closing as it's not the plugin can control
