### ISSUE TITLE
Added Static Method to "onDidReceiveBackgroundNotificationResponse" Which Resolves the error but the code is not executing in that static method

### ISSUE THREAD

**Issue by zaid-bashir** [MaikuB/flutter_local_notifications#2193]
I added static method to it, the error has gone but the callback is not working.
![Screenshot 2023-12-30 at 4 53 20 PM](https://github.com/MaikuB/flutter_local_notifications/assets/53346938/0d9efb34-e49b-44e6-bfe6-8fc2e9748994)
And Here is the static Method
![Screenshot 2023-12-30 at 4 53 38 PM](https://github.com/MaikuB/flutter_local_notifications/assets/53346938/b812b383-30e1-4779-a22a-aa56110977fe)

**Comment by MaikuB** [comment]
Please make sure you've understood when to use the callback and gone through the readme on how to do deal with notifications as I believe you've misunderstood how to use this plugin and not properly understood the details . I'm saying based on how you don't even handle the regular callback and most likely explains why you think there's a problem
