### ISSUE TITLE
I want to Show Scheduled notification as In app Notification when Running and Send Actual Scheduled Notification when app is Closed.

### ISSUE THREAD

**Issue by Arpit144** [MaikuB/flutter_local_notifications#2195]
I am working on Appointments Module which locally schedule the Notification.
I Have Used flutterLocalNotificationsPlugin.zonedSchedule to schedule the notification.
When App is Running so I want to show IN APP Notification at scheduled time instead of actual notification and if app Closed than send actual Notification at scheduled time.

I Have Somehow manged this functionality in IOS doing Some Native Swift code but how can i do in my android devices.

**Comment by MaikuB** [comment]
If you want this behaviour then you need to develop your own custom solution for it. This wouldn't be a plugin concern to solve though it may be that you can fork the plugin to help make a start on it
