### ISSUE TITLE
Local Push Notification Payload is overrided by the latest notification.

### ISSUE THREAD

**Issue by rsillador** [MaikuB/flutter_local_notifications#2200]
**Describe the bug**
Local Push notification "onDidReceiveNotificationResponse" function does not retrieve the exact payload, When I have two local push notification and tap the old one, I always get the latest notifcation payload?

**To Reproduce**

1. Send two different push notification
2. Tap the old notification
3. Notice on the logs that the payload being retrieved is always the latest one.

**Expected behavior**

When opening the notification, I should be able to retrieve the exact payload of the specific notification.

**Sample code to reproduce the problem**

`AndroidNotificationChannel channel = const AndroidNotificationChannel(
        'default_notification_channel_id', // id
        'Notification', // titleescription
        importance: Importance.high,
        // groupId : "GEMINI_CHAT"
      );

      var flutterLocalNotificationsPlugin1 =
          FlutterLocalNotificationsPlugin();

      await flutterLocalNotificationsPlugin1!
          .resolvePlatformSpecificImplementation<
          AndroidFlutterLocalNotificationsPlugin>()
          ?.createNotificationChannel(channel!);

      await flutterLocalNotificationsPlugin1!
          .resolvePlatformSpecificImplementation<
          IOSFlutterLocalNotificationsPlugin>()
          ?.requestPermissions(
        alert: true,
        badge: true,
        sound: true,
      );

        const AndroidInitializationSettings initializationSettingsAndroid =
        AndroidInitializationSettings('@mipmap/ic_launcher');
        DarwinInitializationSettings initializationSettingsDarwin = DarwinInitializationSettings();

      InitializationSettings initializationSettings = InitializationSettings(
          android: initializationSettingsAndroid,
          iOS: initializationSettingsDarwin,
        );

        await flutterLocalNotificationsPlugin1!.initialize(initializationSettings!,
            onDidReceiveNotificationResponse: (str) {
                print("str ${str.payload!.toString()}");
            });

      Map? item = message.item;

      await flutterLocalNotificationsPlugin1?.show(
          Random().nextInt(100), "Notification", "Notification Content", getNotificationDetails("Notification Content", conversationUid),
          payload: jsonEncode(chatMessage));
    }`
    
    
    
    
    `NotificationDetails getNotificationDetails(String? messageContent, String? conversationUid){
      AndroidNotificationDetails androidNotificationDetails =
      AndroidNotificationDetails(
        "default_notification_channel_id",
        "Notification",
        channelDescription: messageContent ?? "",
        importance: Importance.max,
        priority: Priority.high,
        ticker: 'ticker',
        channelShowBadge: true,
        groupKey: conversationUid,
        icon: '@mipmap/ic_launcher',
        showProgress: true,
        tag: conversationUid,
      );
      DarwinNotificationDetails iOSNotificationDetails =
      const DarwinNotificationDetails(
        presentAlert: true,
        presentBadge: true,
        presentSound: true,
        // badgeNumber : 1
      );
      print("notification triggered");
      return NotificationDetails(
          android: androidNotificationDetails, iOS: iOSNotificationDetails);
  }`

**Comment by MaikuB** [comment]
Please fork the repository, update the example app to provide a way that can reproduce and prove there is a problem. Once done, please share the link here

**Comment by MaikuB** [comment]
Closing as requested information hasn't been provided and I had checked the example app that shows this is working fine
