### ISSUE TITLE
Trying to cancel set notifications using isolate, still blocks the main UI

### ISSUE THREAD

**Issue by abdimussa87** [MaikuB/flutter_local_notifications#2202]
**Describe the bug**
So I was trying to cancel around 295 notifications set using the `cancelAll()` method. I noticed an issue in performance and decided to use an isolate so that the `main` thread won't get blocked. However, even when using isolates, I'm experiencing the same issue where the UI freezes when the cancelAll() method executes.

**To Reproduce**

Here's a simple, reproducible step:

0. Clone the forked repo provided below, and add Google Maps Api key inside the AndroidManifest.xml
1. Click schedule notifications which first cancels all notifications(if set), then schedules 295 notifications. 
2. Then click on cancel all notifications and observe the UI being unresponsive when dragging the map around for some seconds.

**Expected behavior**
The UI doesn't freeze

**Sample code to reproduce the problem**
[Fork of the repo that contains updated code in the main.dart](https://github.com/abdimussa87/flutter_local_notifications)

**Comment by naamapps** [comment]
Same here, the cancel functions are blocking the UI thread and taking long time for some reason.

**Comment by Lzyct** [comment]
Do we have any updates on this?
I've issues on some devices, like in Samsung Flip 3 with Android 14 One UI 6, when the app cancels all alarms and creates 500 new alarms the app freezed and shows force close.

![image](https://github.com/MaikuB/flutter_local_notifications/assets/1531684/e2ef2bee-f444-4549-8e65-e5b626c857e8)
