### ISSUE TITLE
A problem occurred configuring project ':flutter_local_notifications'.

### ISSUE THREAD

**Issue by AndreCMR** [MaikuB/flutter_local_notifications#2206]
I installed the flutter local notification plugin in my project but when I run flutter run it gives me the following error

*What went wrong:
There was a problem configuring the ':flutter_local_notifications' project.
> Failed to notify listener of project review.
   > Unable to get unknown property 'android' for project ':flutter_local_notifications' of type org.gradle.api.Project.
   > Unable to get unknown property 'android' for project ':flutter_local_notifications' of type org.gradle.api.Project.

* To try:
> Run with --stacktrace option to get stack trace.
> Run with the --info or --debug option to get more log output.
> Run with --scan to get full insights.

I've tried everything and nothing solves my problem.

**Comment by MaikuB** [comment]
This is something that looks like a setup issue with your app as opposed to a bug and would be something you need to get help from the community through places like Slack, Discord etc where they can look at your app to help you out. This is further reinforced but how no one else has reported an issue like this on the repository either. Will be closing this issue as a result

**Comment by rabar1995** [comment]
I upgrade my flutter and java versions had same problem 
Execution failed for task ':app:checkDebugAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > An issue was found when checking AAR metadata:

       1.  Dependency ':flutter_local_notifications' requires core library desugaring to be enabled
           for :app.

           See https://developer.android.com/studio/write/java8-support.html for more
           details.
