### ISSUE TITLE
 Local notification tap not redirecting to SecondPage on iOS

### ISSUE THREAD

**Issue by Adrien300101** [MaikuB/flutter_local_notifications#2208]
**Describe the bug**
I am using the example project for this plugin and I noticed that on Android once I click on the notification the app will redirect the user to the SecondPage. However, on IOS this is not working at all. Once the user clicks on the notification nothing happens and there is also no error messages. 

**To Reproduce**
1. Click Show plain notification with payload
2. Click on the notification that appears
3. Nothing happens on IOS

**Expected behavior**
On clicking on the notification it is supposed to redirect the user to the SecondPage

**Sample code to reproduce the problem**
I used the same example and tried to add a log message in the _configureDidReceiveLocalNotificationSubject() function to check if the message appears in the log on IOS but it did not appear which I can only conclude that this function is not being triggered when running on IOS:

void _configureDidReceiveLocalNotificationSubject() {
    didReceiveLocalNotificationStream.stream
        .listen((ReceivedNotification receivedNotification) async {
          log("Is this being triggered for IOS?");
      await showDialog(
        context: context,
        builder: (BuildContext context) => CupertinoAlertDialog(
          title: receivedNotification.title != null ? Text(receivedNotification.title!) : null,
          content: receivedNotification.body != null ? Text(receivedNotification.body!) : null,
          actions: <Widget>[
            CupertinoDialogAction(
              isDefaultAction: true,
              onPressed: () async {
                Navigator.of(context, rootNavigator: true).pop();
                await Navigator.of(context).push(
                  MaterialPageRoute<void>(
                    builder: (BuildContext context) => SecondPage(receivedNotification.payload),
                  ),
                );
              },
              child: const Text('Ok'),
            )
          ],
        ),
      );
    });
  }

**Comment by MaikuB** [comment]
For future reference, please try to clone the repository and run the example app to see if you can reproduce the issue first before reporting an issue and if you report one, please include a link to a repository hosting a minimal app that can reproduce the issue. In your case, what you're describing would indicate that the step mentioned [here](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#general-setup) hasn't been done
