### ISSUE TITLE
Doesn't show notification automatically after boot 

### ISSUE THREAD

**Issue by avdhootu27** [MaikuB/flutter_local_notifications#2209]
**Describe the bug**

I have created a daily scheduled notification. When device is restarted, the scheduled notification doesn't work. But if I open the app atleast once after restart then scheduled notification works.

**To Reproduce**

1. Scheduled daily notification
2. Restart device just before scheduled time

**Expected behavior**

The notification should be automatically shown if device is ON at the time of scheduled notification. There should not be any need to open the app atleast once.

**Comment by JMApps** [comment]
I have a similar problem on Android version 14 (34). If the application is minimized or open, notifications arrive normally, but if the application is closed and cleared from the background, then notifications no longer arrive.

**Comment by avdhootu27** [comment]
Are you scheduling the notification in app while debugger is on?
Because if your phone is connected with laptop and debugger is on and at same time you schedule a notification and then kill app and wait for notification then notification will not show.
You should first install the app in phone, then kill the app, remove from recents, stop debugger, disconnect from laptop then open the app, schedule notification and then try.

**Comment by iquirino** [comment]
> I have a similar problem on Android version 14 (34). If the application is minimized or open, notifications arrive normally, but if the application is closed and cleared from the background, then notifications no longer arrive.

Me too, I am not receiving notification from firebase.

**Comment by avdhootu27** [comment]
Don't know how but now it is working correctly. So closing this issue

**Comment by iquirino** [comment]
> Don't know how but now it is working correctly. So closing this issue

Have you made any updates to the lib version? Which version are you running?

**Comment by avdhootu27** [comment]
16.3.0
