### ISSUE TITLE
getNotificationAppLaunchDetails always returns false

### ISSUE THREAD

**Issue by kataklysmo** [MaikuB/flutter_local_notifications#221]
didNotificationLaunchApp is returning always false using latest version of the plugin ( 0.7.0)

With the app opened or running in the background i can receive the notification without any issue here it's the content of the notification received from the backend.
{notification: {body: TestPush, title: Test}, data: {type: JustTesting, click_action: FLUTTER_NOTIFICATION_CLICK}}

Using the example code, opening the app using a push notification the response is always false.

It's required to add something to the manifest file?

Thank you!

```
void main() async {
  flutterLocalNotificationsPlugin = FlutterLocalNotificationsPlugin();
   var notificationAppLaunchDetails =
       await flutterLocalNotificationsPlugin.getNotificationAppLaunchDetails();
print(notificationAppLaunchDetails.didNotificationLaunchApp);
  runApp(
    MaterialApp(
      home: HomePage(),
    ),
  );
}
```

**Comment by MaikuB** [comment]
This method is meant to be used for checking when a local notification has launched the app. Based on what you've described above, you're tapping on a push notification. The sample content of that push notification suggests to me that you're sending a notification message via FCM and displaying of notification messages is handled by the firebase messaging plugin. This means you should be checking the firebase messaging plugin to find out if tapping on the notification caused the app to launch

**Comment by kataklysmo** [comment]
Thank you MaikuB! You're absolutely right about notifications having to be checked using firebase messaging plugin. So right now when the app is terminated Data Message on Android is lost.

More info here:
https://pub.dartlang.org/packages/firebase_messaging
