### ISSUE TITLE
main.dart not found when the commend 'flutter build apk' 

### ISSUE THREAD

**Issue by aly7yaNasser** [MaikuB/flutter_local_notifications#2210]
as you described in your docs In shoulde copy my project in side your head project and its working in debug mode but when I'm tring to generate the apk file it's saying ' the fail lib/main.dart' not found' becuse you head project does'n have main.dart file.

even I have tried to generate the apk from my project it's generated but the notifications are not working

**Comment by MaikuB** [comment]
> as you described in your docs In shoulde copy my project in side your head project

This is never stated so would explain the issue you are having as you're misinterpreting instructions
