### ISSUE TITLE
custom sound plays only 7 secs on IOS 

### ISSUE THREAD

**Issue by ilimsource** [MaikuB/flutter_local_notifications#2213]
I am using flutter_local_notification version 16.2.0 for a flutter app. I can play custom sounds on both Android and IOS. For IOS, I have stored custom sound clips in the ios/Runner folder in .caf and .aiff format. The duration of the sound file is between 20 - 30 seconds. 

Custom sounds plays at the scheduled time - in both cases, when the app is in the foreground or background. However, it only plays the first 7-8 seconds. 

Is there are setting or limit in flutter_local_notification that restricts the custom sound to play for only 7-8 seconds? 
Can you please help me figure out what I am missing?

**Comment by MaikuB** [comment]
No there is no such setting with the plugin. The plugin just passes the relevant information to the native APIs so what you see/hear is what you get. This means I would expect that even if you wrote an app using Objective-C/Swift directly and called the native APIs then you would encounter the same behaviour
