### ISSUE TITLE
Navigating to specific screen when tapping notifications

### ISSUE THREAD

**Issue by Yonas-T** [MaikuB/flutter_local_notifications#2214]
**Describe the bug**

**To Reproduce**

1. Tap the notification
2. Change the state of the app to navigate to specific screen

**Expected behavior**

I wanted to navigate to a specific screen when the notification is tapped instead of just opening the application. I can do this if the app is not opened using the getNotificationAppLaunchDetails function. But when the app is in the background or opened, i couldn't execute any action i needed to do.

**Comment by Aziz-cs** [comment]
I have the same issue I can't find clear guidance on Readme file for doing that.
