### ISSUE TITLE
The sample code flutterLocalNotificationsPlugin.initialize has the same end result on both branch conditions.  Why?

### ISSUE THREAD

**Issue by snowch** [MaikuB/flutter_local_notifications#2215]
**Describe the bug**

Documentation bug?

The sample has the following code where both conditions have the same action, what is the rationale for this?

Some inline documentation would be useful to explain why both conditions are shown even though they have the same end result.

```
  await flutterLocalNotificationsPlugin.initialize(
    initializationSettings,
    onDidReceiveNotificationResponse: (NotificationResponse notificationResponse) {
      switch (notificationResponse.notificationResponseType) {
        case NotificationResponseType.selectedNotification:
          selectNotificationStream.add(notificationResponse.payload);
          break;
        case NotificationResponseType.selectedNotificationAction:
          if (notificationResponse.actionId == navigationActionId) {
            selectNotificationStream.add(notificationResponse.payload);
          }
          break;
      }
    },
```

**Comment by MaikuB** [comment]
I'll need to revisit the example app code when I can to check. Support for actions was a community contribution and I believe it was like this help make it explicit that only certain notification actions  were allowed to navigate to another page. This is why there's the check on the action ID as some of the code snippets for notification actions will result in notifications with multiple actions

**Comment by MaikuB** [comment]
Apologies for late response. I've taken a look and it is as I said. With regards to documentation, there are comments on the IDs notification actions

https://github.com/MaikuB/flutter_local_notifications/blob/3a62532af4a495dd3035cdbbc73a956392fd6cad/flutter_local_notifications/example/lib/main.dart#L57

If you look above that there's an ID notification action with a comment that it's for opening a URL
https://github.com/MaikuB/flutter_local_notifications/blob/3a62532af4a495dd3035cdbbc73a956392fd6cad/flutter_local_notifications/example/lib/main.dart#L54
