### ISSUE TITLE
Csv file is not opening in google sheets from notification in Android.

### ISSUE THREAD

**Issue by Julienjthomas** [MaikuB/flutter_local_notifications#2216]
**Describe the bug**
I'm trying to open a CSV file in Google Sheets from notification. but it's seeing that the file is corrupted after opening the app.
But it is working when I try to open the same file from the file manager.
I am able to open other types mainly pdf file from notification

**To Reproduce**
Im using   flutter_local_notifications: 16.2.0
To reproduce this
create a csv file and then in the notification give the path as payload and then try to open the file from the notification. it wont work

**Expected behavior**

**Sample code to reproduce the problem**

**Comment by MaikuB** [comment]
Closing this as opening a CSV file isn't a concern for this plugin for it to be considered a bug of this plugin. That you're raising a bug on this plugin with your scenario would indicate you need to understand your app better around what it uses for different functionality as you would've used something different to open the file. This plugin doesn't provide any functionality to open a file

**Comment by Julienjthomas** [comment]
@MaikuB , when i try to open a csv file from notifications in  google sheets, it wont work.

**Comment by MaikuB** [comment]
As mentioned earlier this has nothing to do with the plugin
