### ISSUE TITLE
[Feature] Cancel only pending scheduled notifications

### ISSUE THREAD

**Issue by naamapps** [MaikuB/flutter_local_notifications#2219]
Currently there are only 2 ways to cancel notifications, one is specific by ID and another is the `cancelAll` function that cancels pending AND active (presented) notifications.

I would like to have a function that cancels only pending notifications (without canceling the presented ones).

I have a workaround working but it's not ideal.
The workaround uses the `pendingNotificationRequests` function and then I use the specific cancel function and cancel every pending notification one by one.

Please let me know what you think.
Thanks

**Comment by MaikuB** [comment]
This would be something you would need to see if it's possible to do and if so, submit a PR for it
