### ISSUE TITLE
Three dots ' ...' are added to the body of the message while the message fits on the screen.

### ISSUE THREAD

**Issue by PeperMarkreel** [MaikuB/flutter_local_notifications#2225]
![Screenshot_20240122_210048_One UI Home](https://github.com/MaikuB/flutter_local_notifications/assets/87121128/108c496c-7b5f-4d01-8fa2-65697bd54431)

**Describe the bug**
A space and three dots ' ...' are added to the message while the message fits on the screen and there is no need for expansion.

**Expected behavior**
No three dots when the message fits on screen. 

Is this the standard behavior of android, am I doing something wrong? Longer messages that do not fit on the screen at once obviously should have this, but shorter not.

**Comment by MaikuB** [comment]
This is something you'd need to check up on e.g. through the docs. The plugin's purpose is to call the corresponding APIs so you would still check the functionality available on the platform on this e.g. through the official Android docs. This would typically mean what you see is what you get. It may well be that you need to consider adjusting your code to do what you're after to work within the constraints so to speak

**Comment by dragongesa** [comment]
@PeperMarkreel Try to use BigText layout
