### ISSUE TITLE
Issue with Custom Sound Notification on Android 11

### ISSUE THREAD

**Issue by burhanaksendir** [MaikuB/flutter_local_notifications#2226]
Hello,

I've downloaded the project and successfully ran the sample application within the downloaded project on both an Android 11 simulator and a real device (Samsung A70). However, I've encountered an issue with custom sound notifications. Despite receiving notifications, there is no sound on Android 11, and I've specifically noticed this problem on a Samsung A70.

I've extensively researched this problem and found that it seems to occur only on Android 11. Could you please perform a test to reproduce and investigate this issue? Your assistance in resolving this matter is greatly appreciated.

Thank you in advance for your attention and help.

**Comment by MunibullahShah** [comment]
I have the same issue, It works on android 12,13 and 14 but not on 11, just show the notification and does not play the sound.
Here is my code
`
 await _requestPermissions();

    const DarwinNotificationDetails darwinNotificationDetails =
        DarwinNotificationDetails(
      sound: 'azaan.aiff',
    );

    AndroidNotificationDetails androidPlatformChannelSpecifics =
        const AndroidNotificationDetails(
      'daily Salaat',
      'daily Salaat notification channel name',
      channelDescription: 'daily Salaat notification description',
      sound: RawResourceAndroidNotificationSound('azaan'),
      importance: Importance.high,
      priority: Priority.high,
      ongoing: true,
    );
    await flutterLocalNotificationsPlugin.zonedSchedule(
      0,
      'Time for Salat',
      'Salat is better than sleep',
      tz.TZDateTime.from(
          DateTime.now().add(const Duration(minutes: 1)), tz.local),
      NotificationDetails(
        android: androidPlatformChannelSpecifics,
        iOS: darwinNotificationDetails,
      ),
      androidScheduleMode: AndroidScheduleMode.exactAllowWhileIdle,
      uiLocalNotificationDateInterpretation:
          UILocalNotificationDateInterpretation.absoluteTime,
      matchDateTimeComponents: DateTimeComponents.time,
    );
`

**Comment by MaikuB** [comment]
I do not have an Android 11 device. Note that what this plugin does is call the native APIs and this plugin doesn't do anything is specific to Android 11. The only code is to do with Android 8 where they introduced notification channels.. What this means is this really shouldn't a plugin issue and that if you were to write the native Java/Kotlin code to call the notification APIs yourself then it should mean that you would see the same behaviour. If you have an Android 11 device yourself and already doing research into then you can try to confirm this yourself. Furthermore, the plugin is open-sourced so if you believe there's something that the plugin needs to account for some weird behaviour with Android 11 (e.g. perhaps an issue within the OS itself) then you can submit a PR on this. From what I've seen, this works on the Android 11 emulator so should've been an indication then this should work

**Comment by burhanaksendir** [comment]
@MaikuB  @MunibullahShah 

**Introduction:**
If you've encountered an issue where custom notification sounds are not playing on devices running Android 7, you're not alone. This problem can be frustrating, but fortunately, there's a simple solution that often works: restarting your device.

**Explanation:**
On some Android 7 devices, particularly older models, there can be occasional glitches or conflicts that prevent custom notification sounds from playing as expected. This issue may arise due to various factors, including system resource allocation or temporary software bugs.

**Solution:**
To resolve this issue, try restarting your Android 7 device. A restart clears the device's memory and resets various system processes, which can help eliminate any temporary glitches affecting notification sound playback.

**Comment by MaikuB** [comment]
Going to close this as there's nothing I can do further on this

**Comment by sklaboi** [comment]
Hey @burhanaksendir! Did you manage to solve this issue?

**Comment by USardorB** [comment]
I've noticed that, on Redmi 9C NFC, which has also Android version of 11, this problem exsist. The possible problem, is that, I can hear the sound only if I were to go inside of app's notification settings, and then enable allow-playing-sound option there. In other words, the plugin I think, is not enabling that option programmatically
