### ISSUE TITLE
Notifications are not displaying after the app is terminated

### ISSUE THREAD

**Issue by Abdulbasheer095** [MaikuB/flutter_local_notifications#2229]
Notifications are not displaying after the app is terminated, please suggest me how to resolve this issue and display the notification every minute even though the app is terminated by the user
Thanks in advance

**Comment by MeetSolguruz** [comment]
Which Android version are you checking the notification implementation?

**Comment by Abdulbasheer095** [comment]
using Version 12

**Comment by MeetSolguruz** [comment]
Okay, Can you share you code?

**Comment by Abdulbasheer095** [comment]
**********///////////Notification Page Start here*********
import 'dart:math';

import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:timezone/timezone.dart' as tz;

class NotificationService {
  final FlutterLocalNotificationsPlugin notificationsPlugin =
      FlutterLocalNotificationsPlugin();

  @pragma('vm:entry-point')
  void notificationTapBackground(NotificationResponse notificationResponse) {
    // ignore: avoid_print
    print('notification(${notificationResponse.id}) action tapped: '
        '${notificationResponse.actionId} with'
        ' payload: ${notificationResponse.payload}');
    if (notificationResponse.input?.isNotEmpty ?? false) {
      // ignore: avoid_print
      print(
          'notification action tapped with input: ${notificationResponse.input}');
    }
  }

  Future<void> initNotification() async {
    AndroidInitializationSettings initializationSettingsAndroid =
        const AndroidInitializationSettings('@mipmap/ic_launcher');

    var initializationSettingsIOS = DarwinInitializationSettings(
        requestAlertPermission: true,
        requestBadgePermission: true,
        requestSoundPermission: true,
        onDidReceiveLocalNotification:
            (int id, String? title, String? body, String? payload) async {});

    var initializationSettings = InitializationSettings(
        android: initializationSettingsAndroid, iOS: initializationSettingsIOS);
    await notificationsPlugin.initialize(initializationSettings,
        onDidReceiveNotificationResponse: notificationTapBackground);
  }

  notificationDetails() {
    return const NotificationDetails(
        android: AndroidNotificationDetails('channelId', 'channelName',
            playSound: true, importance: Importance.max, enableVibration: true),
        iOS: DarwinNotificationDetails());
  }

  Future showNotification(
      {int id = 0, String? title, String? body, String? payLoad}) async {
    return notificationsPlugin.show(
        id, title, body, await notificationDetails());
  }

  String _nextInstanceOfTenAM() {
    final tz.TZDateTime now = tz.TZDateTime.now(tz.local);
    print(now);
    tz.TZDateTime scheduledDate = tz.TZDateTime(
        tz.local, now.year, now.month, now.day, 15, now.minute - 29);

    print("scheduledDate ${scheduledDate.toString().substring(0, 19)}");
    print(scheduledDate.isAfter(now));
    if (scheduledDate.isAfter(now)) {
      scheduledDate;
      //scheduledDate = scheduledDate.add(const Duration(days: -1));
      print("schedulegdDate$scheduledDate");
    }
    return scheduledDate.toString().substring(0, 19);
  }

  Future<void> scheduleDailyTenAMNotification() async {
    print(tz.TZDateTime.from(
      DateTime.parse(_nextInstanceOfTenAM()),
      tz.local,
    ));
    return notificationsPlugin.zonedSchedule(
      0,
      'daily scheduled notification title',
      'daily scheduled notification body',

      tz.TZDateTime.from(
        DateTime.parse(_nextInstanceOfTenAM()),
        tz.local,
      ),

      await notificationDetails(),
      // const NotificationDetails(
      //   android: AndroidNotificationDetails('daily notification channel id',
      //       'daily notification channel name',
      //       channelDescription: 'daily notification description'),
      // ),
      androidScheduleMode: AndroidScheduleMode.exactAllowWhileIdle,
      uiLocalNotificationDateInterpretation:
          UILocalNotificationDateInterpretation.absoluteTime,
      //matchDateTimeComponents: DateTimeComponents.time
    );
  }

  Future repeatNotification() async {
    Random random = new Random();
    int randomNumber = random.nextInt(10);
    // const AndroidNotificationDetails androidNotificationDetails =
    //     AndroidNotificationDetails(
    //         'repeating channel id', 'repeating channel name',
    //         channelDescription: 'repeating description');
    // const NotificationDetails notificationDetails =
    //     NotificationDetails(android: androidNotificationDetails);
    return notificationsPlugin.periodicallyShow(
      randomNumber,
      'repeating title',
      'repeating body',
      RepeatInterval.everyMinute,
      await notificationDetails(),
      androidScheduleMode: AndroidScheduleMode.exactAllowWhileIdle,
    );
  }

  Future scheduleNotification(
      {int id = 0,
      String? title,
      String? body,
      String? payLoad,
      required DateTime scheduledNotificationDateTime}) async {
    return notificationsPlugin.zonedSchedule(
        id,
        title,
        body,
        tz.TZDateTime.from(
          scheduledNotificationDateTime,
          tz.local,
        ),
        await notificationDetails(),
        androidAllowWhileIdle: true,
        uiLocalNotificationDateInterpretation:
            UILocalNotificationDateInterpretation.absoluteTime);
  }
}
***************//Home page*****/// Start 

import 'package:flutter/material.dart';
import 'package:flutter_datetime_picker/flutter_datetime_picker.dart';

import 'notifi_service.dart';

DateTime scheduleTime = DateTime.now();

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: const [
            DatePickerTxt(),
            ScheduleBtn(),
          ],
        ),
      ),
    );
  }
}

class DatePickerTxt extends StatefulWidget {
  const DatePickerTxt({
    Key? key,
  }) : super(key: key);

  @override
  State<DatePickerTxt> createState() => _DatePickerTxtState();
}

class _DatePickerTxtState extends State<DatePickerTxt> {
  @override
  Widget build(BuildContext context) {
    return TextButton(
      onPressed: () {
        DatePicker.showDateTimePicker(
          context,
          showTitleActions: true,
          onChanged: (date) => scheduleTime = date,
          onConfirm: (date) {},
        );
      },
      child: const Text(
        'Select Date Time',
        style: TextStyle(color: Colors.blue),
      ),
    );
  }
}

class ScheduleBtn extends StatelessWidget {
  const ScheduleBtn({
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ElevatedButton(
      child: const Text('Schedule notifications'),
      onPressed: () {
        debugPrint('Notification Scheduled for $scheduleTime');
        NotificationService().repeatNotification();
        // NotificationService().scheduleDailyTenAMNotification();
        // NotificationService().scheduleNotification(
        //     title: 'Scheduled Notification',
        //     body: '$scheduleTime',
        //     scheduledNotificationDateTime: scheduleTime);
      },
    );
  }
}
************//////////Main dart page Start Here***********

import 'package:flutter/material.dart';
import 'package:timezone/data/latest.dart' as tz;

import 'home_page.dart';
import 'notifi_service.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  NotificationService().initNotification();

  tz.initializeTimeZones();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Notifications',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Local Notifications'),
    );
  }
}

**Comment by Abdulbasheer095** [comment]
@MeetSolguruz  Thanks Boss  the code works fine.

**Comment by Abdulbasheer095** [comment]
fine

**Comment by anmolstuteja** [comment]
@Abdulbasheer095 What changes did you make? is it working even after the app gets terminated?
