### ISSUE TITLE
how can i change the content of the recurring notification over time

### ISSUE THREAD

**Issue by minh98** [MaikuB/flutter_local_notifications#223]
my code: 
```
  void showRepeat() async{
    // Show a notification every minute with the first appearance happening a minute after invoking the method
    var androidPlatformChannelSpecifics =
    new AndroidNotificationDetails('repeating channel id',
    'repeating channel name', 'repeating description');
    var iOSPlatformChannelSpecifics =
    new IOSNotificationDetails();
    var platformChannelSpecifics = new NotificationDetails(
    androidPlatformChannelSpecifics, iOSPlatformChannelSpecifics);
    await flutterLocalNotificationsPlugin.periodicallyShow(0, 'repeating title',
    'scheduled body ${DateTime.now().hour}-${DateTime.now().minute}-${DateTime.now().second}', RepeatInterval.EveryMinute, platformChannelSpecifics);
  }
```
it always return same content,same time.
i can't update it

**Comment by MaikuB** [comment]
that's by design. if the contents could be different then it's not really a recurring notification anymore. you'll need to schedule individual notifications on your own

**Comment by minh98** [comment]
We are developing a calendar management project.
and I am doing the function of announcing the amount of work for the next day at 8pm.
So I need a daily notification with daily updates.
Do you have any ideas to solve the problem I'm having? help me please!

**Comment by MaikuB** [comment]
You can schedule them individually as per my previous response either through the plugin or look at using platform channels

**Comment by eagleteam** [comment]
Thanks.
