### ISSUE TITLE
error when run the command ' flutter bild apk'

### ISSUE THREAD

**Issue by aly7yaNasser** [MaikuB/flutter_local_notifications#2230]
**Describe the bug**
My application is working as expected but when I tried to run the command 'flutter build apk' an error message show up 'main.dart file not found'

https://github.com/aly7yaNasser/Praye-times-with-notication-flutter

**Comment by MaikuB** [comment]
This is an issue with your own app and not a problem with the plugin. The error tells you why there's a problem and this is something you would need to look into. Given you don't seem to be aware that it's a problem with your app then I would suggest you revisit the basics of the Flutter applications
