### ISSUE TITLE
zonedSchedule doesn't work for > 500 notifications

### ISSUE THREAD

**Issue by Lzyct** [MaikuB/flutter_local_notifications#2231]
**Describe the bug**
I've created a `zonedSchedule` notification with about 500 notifications.
The notification is created. But it doesn't work. But when I decrease the amount of notifications to 6-30 notifications, that's working well.

![image](https://github.com/MaikuB/flutter_local_notifications/assets/1531684/7da71695-3f50-4c9a-970a-90e666d98532)

**To Reproduce**
1. Create a loop to create the `zonedSchedule` of about 500
2. Observe the notification.

**Expected behavior**
That notification should be work because there no error when creating the `zoneSchedule` notification.

**Sample code to reproduce the problem**
``` dart
...

for (int index=0;index<100;index++){
  flutterLocalNotificationsPlugin.zonedSchedule(
              index + 1,
              title,
              message,
              TZDateTime.now(local).add(
                Duration(seconds: 60 * (index + 1)),
              ),
              notificationDetails,
              uiLocalNotificationDateInterpretation:
                  UILocalNotificationDateInterpretation.absoluteTime,
              androidScheduleMode: AndroidScheduleMode.alarmClock,
            );

}

```

**Comment by nbergemann** [comment]
Hello,

It looks like you're encountering the device-specific limit (500) for scheduled notifications, which is common on some Android devices. The Flutter Local Notifications plugin documentation mentions this limit, and reducing the number of notifications to below this threshold, as you did, is a common workaround.

To avoid hitting these limits, you might consider:
- **Batching** notifications where possible.
- **Dynamically scheduling** notifications to keep under the limit.

Here's a quick code snippet to limit the number of scheduled notifications:

```dart
int maxNotifications = 100; // Adjust based on your needs
for (int index = 0; index < maxNotifications; index++) {
  flutterLocalNotificationsPlugin.zonedSchedule(
    index + 1,
    title,
    message,
    TZDateTime.now(local).add(Duration(seconds: 60 * (index + 1))),
    notificationDetails,
    uiLocalNotificationDateInterpretation:
        UILocalNotificationDateInterpretation.absoluteTime,
    androidScheduleMode: AndroidScheduleMode.alarmClock,
  );
}
```
Adjust `maxNotifications` based on testing or device-specific limits. Hope this helps!

**Comment by Lzyct** [comment]
Okay, thanks @nbergemann
