### ISSUE TITLE
`ongoing` property not working on Android 14

### ISSUE THREAD

**Issue by praxder** [MaikuB/flutter_local_notifications#2232]
**Describe the bug**
`Ongoing` notifications on Android 14 are dismissable

**To Reproduce**
1. Create a notification using the [example `ongoing` code](https://github.com/MaikuB/flutter_local_notifications/blob/a3d58bd6a59d0ea79e260ae7347a65ebb41a914b/example/lib/main.dart#L560) and run on an Android 14 device (I'm using a Pixel 6 Pro).
2. Notice that you can dismiss the notification

**Expected behavior**
You cannot dismiss the notification

**Sample code to reproduce the problem**
See the above sample code, but for good measure here's the specific code I'm using:
```dart
    await FlutterLocalNotificationsPlugin().show(
      notification.id,
      notification.title,
      notification.body,
      NotificationDetails(
        android: AndroidNotificationDetails(
          'key',
          'your channel name',
          channelDescription: 'woot',
          ongoing: true,
          category: AndroidNotificationCategory.service,
          importance: Importance.max,
          priority: Priority.high,
          autoCancel: false,
          additionalFlags: Int32List.fromList([2]), // FLAG_ONGOING_EVENT https://developer.android.com/reference/android/app/Notification#FLAG_ONGOING_EVENT
          styleInformation: const MediaStyleInformation(),
        ),
      ),
    );

```

Edit: I just confirmed that the `ongoing` property _does_ work properly on an Android 12 phone.

**Comment by DarkCaster** [comment]
This is intended change in android 14: [link](https://developer.android.com/about/versions/14/behavior-changes-all#non-dismissable-notifications)
I suppose this cannot be fixed at application level at all. Eh, Google at its best...

**Comment by MaikuB** [comment]
Thanks @DarkCaster for helping to answer

@praxder as mentioned by @DarkCaster this isn't a plugin issue so not much can be done here. If your scenario is to do with phone calls then note that the plugin doesn't have support for call style notifications as mentioned in the link and would need a PR for this. Looking at your code snippet though, I suspect that's not applicable for you since you're using media style notifications. 

Sidenote: these changes probably explains why I noticed Google's own Youtube Music app has a notification that is dismissable even when music still plays in the background...

**Comment by riadhmoussa** [comment]
so guys what is the solution for this issue i faced the same prob

**Comment by SDIDSA** [comment]
> so guys what is the solution for this issue i faced the same prob

i assume there's no solution, if your app is running on android 14 and above, there's no way to make it stick, as mentioned in the [link](https://developer.android.com/about/versions/14/behavior-changes-all#non-dismissable-notifications) provided by @DarkCaster

**Comment by DarkCaster** [comment]
> so guys what is the solution for this issue i faced the same prob

The only solution is to sometimes reopen the notification, hoping that your background service (if any) has not yet been stopped by android.

**Comment by Levi-Lesches** [comment]
I would disagree. The reason behind the change is to give users more control over what's on their screen. If a user dismisses your notification, it can be considered frustrating and an abuse of your permissions to just put the same notification back up

**Comment by DarkCaster** [comment]
I partially agree, the problem with notifications does exist. But it would have been possible to make an additional permission to show pinned notifications, or at least not break the behavior of notifications for old applications.
