### ISSUE TITLE
Limit for daily notifications on iOS?

### ISSUE THREAD

**Issue by desmeit** [MaikuB/flutter_local_notifications#2233]
In the docs it says: `There is a limit imposed by iOS where it will only keep 64 notifications that will fire the soonest.`

What about daily or weekly notifications? For example with this code:

 ```
 static tz.TZDateTime _scheduleDaily(hour, minute, second) {
    final now = tz.TZDateTime.now(tz.local);
    final scheduledDate = tz.TZDateTime(
      tz.local,
      now.year,
      now.month,
      now.day,
      hour,
      minute,
      second,
    );

    return scheduledDate.isBefore(now)
        ? scheduledDate.add(Duration(days: 1))
        : scheduledDate;
  }

  static Future showDailyNotification({
    int id = 0,
    String? title,
    String? body,
    String? payload,
    int hour = 0,
    int minute = 0,
    int second = 0,
    bool sound = true,
  }) async {

    _notifications.zonedSchedule(
      id,
      title,
      body,
      _scheduleDaily(hour, minute, second), 
      await _notificationDetails(sound),
      payload: payload,
      androidScheduleMode: AndroidScheduleMode.exactAllowWhileIdle,
      uiLocalNotificationDateInterpretation:
          UILocalNotificationDateInterpretation.absoluteTime,
      matchDateTimeComponents: DateTimeComponents.time,
    );
  }
```

Are these basically also scheduled notifications and are they added to the 64? Or do they run indefinitely?

Thanks for the clarification.

**Comment by MaikuB** [comment]
Presumably, a notification is considered unique based on ID regardless of its recurring or not. As this is an Apple restriction not a plugin restriction then really not something I can definitively answer. You may need to try It out to confirm and/or check forums where developers working on the Apple ecosystem can answer
