### ISSUE TITLE
AndroidNotificationAction is not dismissable, also has no action on click.

### ISSUE THREAD

**Issue by hassanali2596** [MaikuB/flutter_local_notifications#2236]
I made a notification with two actions "Accept" and "Decline".
 Accept button should open calling screen.
 Decline button should dismiss the notification and decline the call.

The problem is with decline button, it does not dismiss the notification, and no action executed.
I attached a video to explain the issue.

And her is the sample code of the two action buttons:

AndroidNotificationAction(
            'accept',
            'Accept',
            showsUserInterface: true,
            cancelNotification: true,
            contextual: true,
            icon: DrawableResourceAndroidBitmap('accept_call'),
          ),

           AndroidNotificationAction(
            'decline',
            'Decline',
            contextual: true,
            cancelNotification: true,
            icon: DrawableResourceAndroidBitmap('end_call'),
          ),
        

https://github.com/MaikuB/flutter_local_notifications/assets/61476402/439caa42-d2c1-4fae-8d37-9c26836c755b

**Comment by teenrage-dev** [comment]
same for me

**Comment by MaikuB** [comment]
Sorry for late response but do you have a link to repo hosting a minimal app that reproduce the problem? I suggest forking the repo to update the example app to reproduce the scenario. I've tried this myself by modifying/removing the following line

https://github.com/MaikuB/flutter_local_notifications/blob/3a62532af4a495dd3035cdbbc73a956392fd6cad/flutter_local_notifications/example/lib/main.dart#L1144

It worked as expected.

If you haven't already, check to ensure your app is properly configured. Based on how you mentioned actions aren't being executed, it could be you missed the step on configuring your app's AndroidManifest.xml file as mentioned [here](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#androidmanifestxml-setup). There's specific setup required if you intend to use notification actions

**Comment by MaikuB** [comment]
Closing due to lack of response and from not being able to reproduce. Feel free to reopen if you can provide the requested info
