### ISSUE TITLE
Local notification is automatically dismissed on iOS after a few seconds

### ISSUE THREAD

**Issue by younesouhbi** [MaikuB/flutter_local_notifications#2237]
I am trying to create a notification on iOS and Android (only testing on iOS Simulator at this time) with a custom sound. On iOS, the sound can be as long as 30 sec according to Apple documentation. The issue is that my notification is dismissed after only a few seconds and the sound never gets to finish playing. Is there a way to have the notification stay on screen until the user dismisses it?

My use case is that the app lets the user create alarm schedules, so each alarm is supposed to be critical to the user and they are the one who requested them. The user can also choose the custom sound to associate with each alarm. Is this possible using local notifications?

Thank you

**Comment by yahyaizala** [comment]
i have same error. please respond  how to solve.

**Comment by kamranbekirovyz** [comment]
I have the same issue: any news?
