### ISSUE TITLE
Notifications tap event callback not getting in dart code for iOS

### ISSUE THREAD

**Issue by Saket7042** [MaikuB/flutter_local_notifications#2238]
iOS version - 17.0.0
Library version - 16.2.0

Not getting callback in :

await flutterLocalNotificationsPlugin.initialize(
      initializationSettings,
      onDidReceiveNotificationResponse: notificationTapBackground,
      onDidReceiveBackgroundNotificationResponse: notificationTapBackground,
    );

Notifications on iOS we are receiving in foreground and background states and on tap App is getting open as well and We can get the tap action in AppDelagate.swift class but from there we are not getting callback in onDidReceiveNotificationResponse and onDidReceiveBackgroundNotificationResponse methods.  

Kindly provide any solution as we have checked your example code as well and in that we have followed the same code.

**Comment by teenrage-dev** [comment]
same for me on android
But I haven't tested it on iOS

**Comment by MaikuB** [comment]
If you believe there's an issue then you need to provide a link to a repository to a minimal app that can reproduce the problem. Right now, it would sound like the iOS setup hasn't been done properly

**Comment by MaikuB** [comment]
Closing due to lack of response. Note that the plugin doesn't require setup on the native side so if you were checking only the Dart code then you may well have missed this. You can check the readme for the steps and cross reference with the example app
