### ISSUE TITLE
"error": "NotRegistered"

### ISSUE THREAD

**Issue by mazab99** [MaikuB/flutter_local_notifications#2239]
{
  "to" : "c5su1CAtuEo7gmkdYBlLuc:APA91bF9h5lSePNWpK5DJWb4QfXEbow1Y5FoFfKNrHt4pYyraXKFBQgQcOEth5-SjYhmhsjisj3ozrhy_XzepKDZGKa11P9r_d_dJD6mRsqFv766Zy1GSiVpvlsjdZAbWrqYrCcHKkxa",
  "collapse_key" : "New Message",
  "priority": "high",
  "notification" : {
    "title": "Title of Your Notification",
    "body" : "Body of Your Notification"
  }
}

**{
    "multicast_id": 743879351780417013,
    "success": 0,
    "failure": 1,
    "canonical_ids": 0,
    "results": [
        {
            "error": "NotRegistered"
        }
    ]
}**

**Comment by MaikuB** [comment]
What you're saying is to do with FCM not this plugin
