### ISSUE TITLE
get id select notification

### ISSUE THREAD

**Issue by wuilmerj24** [MaikuB/flutter_local_notifications#224]
Hello
How can i get the id of the notification that i select?. The callback that is in the documentation only returns empty.

**Comment by MaikuB** [comment]
you would need to add it to payload in some form (e.g. JSON) of the various methods available for displaying a notification and parse the payload to extract it out

**Comment by wuilmerj24** [comment]
@MaikuB 
If I already realized, thank you. Actions can be added

**Comment by MaikuB** [comment]
if i understood you correctly, sounds like you realised what needs to be done so will close this issue

**Comment by wuilmerj24** [comment]
@MaikuB 
Yes, I just wanted to take this opportunity to ask you if you can already use the add actions to the notification, since I did not see them because of the documentation.

**Comment by MaikuB** [comment]
No it's not. there's already an open issue on this and no further progress on that can be made at the moment. You may need to consider handling that by writing the code on the Android (with Kotlin or Java) and iOS side (with Objective-C or Swift)

**Comment by wuilmerj24** [comment]
Ok thanks.
