### ISSUE TITLE
Anomaly in Badge Count Mechanism

### ISSUE THREAD

**Issue by FairyWorld** [MaikuB/flutter_local_notifications#2244]
**Describe the bug**

I've encountered an anomaly with the badge count display functionality. Each time I invoke the show method on my application, the badge count increments by one, as expected, until it reaches 9. However, upon the subsequent trigger of the show method that would theoretically increase the count to 10, the badge count briefly shows 10 before reverting back to 9.

Upon further investigation, I discovered that this behavior might be tied to a limitation on Xiaomi devices, where the maximum number of notifications displayed is capped at 9. It seems that receiving a notification that would increase the count above this limit results in older notifications being destroyed or hidden. This mechanism could be interfering with the badge count, causing the abnormal decrement back to 9 after attempting to increase the count to 10.

I am encountering an issue with the badge count functionality when using the flutter_local_notifications plugin in my Flutter application. Specifically, the badge count does not correctly increment beyond 9, which seems to be a limitation or bug within the plugin.

Notably, I have explored using alternative plugins that allow for custom badge count increments and have successfully implemented solutions where the badge count could exceed 10 and be displayed correctly. This discovery leads me to believe that the issue is isolated to the flutter_local_notifications plugin itself.

Moreover, I attempted to circumvent this problem by delegating the badge handling to other plugins. I tried to disable the badge count feature within flutter_local_notifications by setting channelShowBadge to false. Unfortunately, this attempt was unsuccessful—the setting did not take effect, and the badge count issue persisted, indicating a potential bug with the plugin's badge handling configuration.

**To Reproduce**

1. Ensure the application is running on a Xiaomi device.
2. Trigger the show method multiple times to increase the badge count.
3. Observe the badge count as it increases up to 9.
4. Trigger the show method once more, attempting to increase the count to 10.
5. Note the badge count initially increasing to 10 and then reverting back to 9.
6. Implement badge incrementation using the flutter_local_notifications plugin.
7. Attempt to increment the badge count beyond 9 and observe the behavior.
8. Explore alternative plugins to handle badge count and successfully increment beyond 10.
9. Attempt to disable the flutter_local_notifications badge feature by setting channelShowBadge to false.
10. Observe that the setting does not take effect, and the badge count issue remains.

**Expected behavior**

The badge count should correctly increment beyond 9 without reverting, accurately reflecting the number of times the show method has been triggered.

**Sample code to reproduce the problem**

**Comment by MaikuB** [comment]
It isn't a bug with the plugin as the plugin uses the official notification APIs. You could write the native code yourself and you would see this behaviour. Rather, what you're seeing is the reason why this is mentioned in the readme https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#updating-application-badge. Various Android OEMs have done their own customisation when it comes to the Android OS that may not follow the official APIs. So as covered in that cavaet, if this is applicable to your scenario then you'll need to look into using a solution like the one mentioned there
