### ISSUE TITLE
Gradle error "app:mergeExtDexDebug" resulting from following Readme instructions for Android Gradle setup

### ISSUE THREAD

**Issue by Mercutio1243** [MaikuB/flutter_local_notifications#2245]
Following the ReadMe for setting up flutter_local_notifications results in the following error for me when building the app. I would be super grateful if someone could share some advise why this might be happening.

Specifically, the error occurs as soon as I add the relevant entries to android/app/build.gradle. The gradle version higher than 7.3.1 as required in the Readme (see below).

**Error producing entries in android/app/build.gradle:**
```
android {
    compileOptions {
        coreLibraryDesugaringEnabled true
        [...]
    }

dependencies {
    [...]
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.2.2'
}
```

**Error message**
```
Launching lib\main.dart on SM G996U1 in debug mode...
ERROR:D8: com.android.tools.r8.kotlin.H
ERROR:D8: com.android.tools.r8.kotlin.H

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeExtDexDebug'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform play-services-measurement-api-21.5.0.aar (com.google.android.gms:play-services-measurement-api:21.5.0) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=29, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingNoClasspathTransform: C:\Users\thoma\.gradle\caches\transforms-3\be28739f3b88e514cae428a888626c65\transformed\jetified-play-services-measurement-api-21.5.0-runtime.jar.
         > Error while dexing.
   > Failed to transform kotlin-stdlib-1.9.22.jar (org.jetbrains.kotlin:kotlin-stdlib:1.9.22) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=29, org.gradle.category=library, org.gradle.jvm.environment=standard-jvm, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=jvm}.
      > Execution failed for DexingNoClasspathTransform: C:\Users\thoma\.gradle\caches\transforms-3\1e91f56926b46718b31b0d96dfa5d5f0\transformed\jetified-kotlin-stdlib-1.9.22.jar.
         > Error while dexing.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 8s
```

**My app-level build.gradle is set up as follows:**
```
plugins {
    id "com.android.application"
    id "kotlin-android"
    id "dev.flutter.flutter-gradle-plugin"
    id 'com.google.gms.google-services'
    id 'com.google.firebase.crashlytics'
}

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '2'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '0.2.5'
}

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
} 

android {
    namespace "com.cbt.app_name"
    compileSdkVersion flutter.compileSdkVersion
    ndkVersion flutter.ndkVersion

    compileOptions {
        coreLibraryDesugaringEnabled true // flutter_local_notifications
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        applicationId "com.cbt.app_name"
        minSdkVersion 29 
        targetSdkVersion 34
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        multiDexEnabled true
    }

   signingConfigs {
       release {
           keyAlias keystoreProperties['keyAlias']
           keyPassword keystoreProperties['keyPassword']
           storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
           storePassword keystoreProperties['storePassword']
       }
   }
   buildTypes {
       release {
           signingConfig signingConfigs.release
       }
   }
}

flutter {
    source '../..'
}

dependencies {
    implementation platform('com.google.firebase:firebase-bom:32.7.1')
    implementation 'com.google.firebase:firebase-analytics'
    implementation 'com.google.firebase:firebase-crashlytics'
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.2.2'
}

apply plugin: 'com.google.gms.google-services'
```

**My android-level gradle is as follows:**
```
buildscript {
    ext.kotlin_version = '1.9.22'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.4.0'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.0'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
```

**Flutter doctor:**
```
[√] Flutter (Channel stable, 3.16.5, on Microsoft Windows [Version 10.0.19045.4046], locale de-DE)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.1)
[√] Android Studio (version 2022.3)
[√] VS Code (version 1.86.2)
[√] Connected device (4 available)
[√] Network resources
```

Many thanks!!

**Comment by haihv433** [comment]
Same here, remove desugaring will work, but not sure that the best practice

**Comment by Mercutio1243** [comment]
What is the consequence of removing desugaring here?

**Comment by amrgetment** [comment]
@MaikuB Not all of the users using Android version less than Android 8 SDK 26, they are just 7% of Android users
so desugaring is only required for older devices than SDK 26

From Gemini and My search too:

> The Android version that first offered full support for Java 8 was Android 8.0 (Oreo), represented by API level 26.  This means that starting with Oreo, the underlying Dalvik runtime was replaced with a new Android Runtime (ART) that functioned more like a traditional Java VM, allowing direct execution of Java 8 bytecode.

So I think you can add to your Readme that desugaring step is required in case users support Android SDK lower than 26

**Comment by amrgetment** [comment]
@MaikuB Not all of the users using Android version less than Android 8 SDK 26, they are just 7% of Android users
so desugaring is only required for older devices than SDK 26

From Gemini and My search too:

> The Android version that first offered full support for Java 8 was Android 8.0 (Oreo), represented by API level 26.  This means that starting with Oreo, the underlying Dalvik runtime was replaced with a new Android Runtime (ART) that functioned more like a traditional Java VM, allowing direct execution of Java 8 bytecode.

So I think you can add to your Readme that desugaring step is required in case users support Android SDK lower than 26

**Comment by amrgetment** [comment]
I think we should make min SDK 26 then removing the desugaring step

https://www.composables.com/tools/distribution-chart
![image](https://github.com/MaikuB/flutter_local_notifications/assets/149420647/93e906f8-5ffe-413c-9d83-605d97badc99)

**Comment by amrgetment** [comment]
@Mercutio1243 if you removed desugaring in your app it won't compile as it is required by flutter_local_notifications and if flutter_local_notifications removed it then it won't support Android 7.1 SDK 25 and lower

**Comment by ahmedsabahi** [comment]
update compileSdkVersion 34

**Comment by serhii-k** [comment]
Try the following inside your app/build.gradle

1) Inside `android{...}` above `compileOptions` and `defaultConfig` define:
```
def debugMode = gradle.startParameter.taskNames.contains("assembleDebug")
```

2) Inside `compileOptions` instead of `coreLibraryDesugaringEnabled true` write:
```
coreLibraryDesugaringEnabled debugMode ? false : true // flutter_local_notifications
```
This will disable the desugaring in the debug mode.

3) Inside `defaultConfig` instead of `minSdkVersion YOUR_MIN_SDK_VERSION` write:
```
minSdkVersion debugMode ? 24 : YOUR_MIN_SDK_VERSION
```

### Additionally ###

1) As your minSdkVersion is 29 (>= 21), you don't need to specify `multiDexEnabled true`

2) As your AGP is 7.4.2 you should use:
```
coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.0.3'
```

[Desugaring docs](https://developer.android.com/studio/write/java8-support#library-desugaring)

**Comment by Mercutio1243** [comment]
> update compileSdkVersion 34

Thank you! Changing this line to 34 and leaving everything else as is, seems to have helped for me.

Could you still please explain to me: Up to now I had
`compileSdkVersion flutter.compileSdkVersion`
which to my understanding is the recommended approach. I should have an up to date flutter SDK, so why am I not automatically on at least 34 here?

As a personal remark, this is all highly complicated. If you can reduce the complexity by reducing support for super old devices, I would personally recommend doing so...

**Comment by MaikuB** [comment]
> Could you still please explain to me: Up to now I had
compileSdkVersion flutter.compileSdkVersion
which to my understanding is the recommended approach. I should have an up to date flutter SDK, so why am I not automatically on at least 34 here?

@Mercutio1243 All this means is it's setting to what is used as the default for the SDK version you have

> As a personal remark, this is all highly complicated stuff just to get this package set up - and quite a substantial barrier to use it. If you can reduce complexity by reducing support for super old devices, from the view point of a layman like me, I would recommend doing so

@Mercutio1243 I assume by this comment that you believe that setting this means it affects support for older devices. That is not the case. This needed due to the requirement of how the Android ecosystem works where newer APIs require leveraging newer SDK versions. It doesn't break/limit support for older devices.  Other first party plugins from the Flutter team themselves have also bumped their compileSdk versions let alone this plugin. Ironically, it's actually to support older devices that there's other setup needed by this plugin. Had you had written the code to access the native APIs yourself then you would've needed to to do the same thing. Given your questions, it sounds like you aren't familiar with the native APIs and other parts of the native ecosystem even you are essentially writing apps that target said platforms. I highly suggest you familiarise yourself with the native APIs and ecosystem as trying to make use of a platform's features without this understanding would be detrimental in the long run. Will be closing this issue now that you've found out what was missing to solve the original problem

>  I think we should make min SDK 26 and then remove the desugaring step

@ahmedsabahi not looking to this. What you presented ignores what versions Flutter itself supports as per https://docs.flutter.dev/reference/supported-platforms. As of this writing, the minimum version is 21 though even if Flutter team don't test/support lower versions, apps may still run on them. In the future, it's quite likely the plugin will bump this to minimum of 21 as well
