### ISSUE TITLE
background notification is not working and new update

### ISSUE THREAD

**Issue by puneetflutter** [MaikuB/flutter_local_notifications#2246]
Hello sir, in Flutter, with flutter_local_notifications, when a notification arrives in the background, buttons do not appear, and there is no wakeup functionality. When a notification arrives, the application does not automatically open, and there should be support for displaying big images. Additionally, custom buttons similar to those in a music player need to be added to make it more versatile, similar to what is available in awesome_notifications. Various new features should be incorporated to provide further assistance to Flutter developers. I am looking forward to a new update from you soon. Thank you.

**Comment by LuuNgocLan** [comment]
I think you should post an issue with your implemented code

**Comment by LuuNgocLan** [comment]
> Hello sir, in Flutter, with flutter_local_notifications, when a notification arrives in the background, buttons do not appear, and there is no wakeup functionality. When a notification arrives, the application does not automatically open, and there should be support for displaying big images. Additionally, custom buttons similar to those in a music player need to be added to make it more versatile, similar to what is available in awesome_notifications. Various new features should be incorporated to provide further assistance to Flutter developers. I am looking forward to a new update from you soon. Thank you.

I think you should post an issue with your implemented code

**Comment by puneetflutter** [comment]
Initially, I was fetching the response from the API inside Firebase Messaging, so it was showing the default Firebase notification. I hadn't implemented Flutter Local Notification in the background. Now, this issue has been resolved. However, there is still no big image in Flutter Local Notification.
![image](https://github.com/MaikuB/flutter_local_notifications/assets/135137213/d01ffc52-7f1c-4948-879e-5af9eaf1474b)
In Flutter Local Notification, there is still no availability of defining custom buttons.
![image](https://github.com/MaikuB/flutter_local_notifications/assets/135137213/7024ff64-0475-4dbf-b91b-abe73b3608fa)
Awesome Notifications provides better features. Flutter Local Notification should also be equipped with features as good as Awesome Notifications.
https://pub.dev/packages/awesome_notifications

**Comment by puneetflutter** [comment]
Hello @LuuNgocLan  I am Facing Proglam in Flutter Local Notification Action Button Click is not Working
Code is :- 

import 'dart:io';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'flutterLocalNotification.dart';
import 'PayLoadModel/Data.dart';
import 'ShowNotification.dart';

mixin FirebaseInitialization {
  static Future<void> firebaseInit(BuildContext context) async {
    debugPrint('** Firebase Initialization **');
    await Firebase.initializeApp();
    FirebaseMessaging.onMessage.listen((payloads) async {
      final navigationDetailsModel =
          NavigationDetailsModel.fromJson(payloads.data);
      debugPrint('* Payloads *');
      debugPrint(payloads.toMap().toString());
      debugPrint(
          'Notification Android Channel is :-> ${navigationDetailsModel.androidChannelId}');
      debugPrint('* Title *');
      debugPrint('${navigationDetailsModel.title}');
      debugPrint('* Body *');
      debugPrint('${navigationDetailsModel.body}');
      debugPrint('* Argument *');
      debugPrint('${navigationDetailsModel.arg?.toJson()}');
      if (Platform.isAndroid) {
        FlutterLocalNotification.initLocalNotification(
            context, navigationDetailsModel);
        ShowNotification.show(navigationDetailsModel);
      }
      if (Platform.isIOS) {
        await FirebaseMessaging.instance
            .setForegroundNotificationPresentationOptions(
          alert: true,
          badge: true,
          sound: true,
        );
        ShowNotification.show(navigationDetailsModel);
      }
        });
  }
  @pragma('vm:entry-point')
  void notificationTapBackground(NotificationResponse notificationResponse) {
    print('notificationTapBackground');
    print('notification(${notificationResponse.id}) action tapped: '
        '${notificationResponse.actionId} with'
        ' payload: ${notificationResponse.payload}');
  }
}
