### ISSUE TITLE
Tap notification to show list of actions in a small alert box

### ISSUE THREAD

**Issue by Rafia-Chy** [MaikuB/flutter_local_notifications#2252]
I cannot find parameter or a way to use showDialog when a notification arriving in app-kill state or background state is tapped
In effect, I want to achieve something similar to this  in android
![image](https://github.com/MaikuB/flutter_local_notifications/assets/126666981/b4835236-8558-4187-a0a1-526182255ef2)

**Comment by MaikuB** [comment]
What you're seeing there on iOS isn't to do with dialogs so is why you can't find anything. You will need to familiarise yourself with the native platforms
