### ISSUE TITLE
Action Buttons Not Showing in Notification When Application is in Background on Real Device

### ISSUE THREAD

**Issue by RafiaChy** [MaikuB/flutter_local_notifications#2254]
Description:
Action buttons are not appearing in notifications when the application is running in the background on real devices. Despite implementing the necessary code to display action buttons in notifications, they fail to appear when the application is not in the foreground.

Steps to Reproduce:

- Ensure the application is installed and running on a real device.
- Send a notification to the device with action buttons configured.
- Observe the device screen when the application is in the background.

 Expected Behavior:
 Action buttons should be visible in the notification when the application is running in the background, allowing users to interact with the notification without bringing the application to the foreground.

Actual Behavior:
Action buttons are not displayed in the notification when the application is in the background on real devices. As a result, users cannot interact with notifications without opening the application.
![image](https://github.com/MaikuB/flutter_local_notifications/assets/55042866/ca3185f3-d0f6-41cf-9011-51173f45ad68)
![image](https://github.com/MaikuB/flutter_local_notifications/assets/55042866/956a3df1-edad-4fe9-a016-cbe4f098de6c)

Here is the code snippet
`FirebaseMessaging messaging = FirebaseMessaging.instance;

retrieveFcmApnsTokens() async {
  String? fcmToken = await messaging.getToken();
  debugPrint("FCM Token: $fcmToken");

  await Future.delayed(const Duration(seconds: 3));

  String? apnToken = await FirebaseMessaging.instance.getAPNSToken();
  debugPrint("APN Token: $apnToken");

  return fcmToken;
}

class FirebaseCloudMessage {
  late FirebaseMessaging fcm;
  late FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin;
  late NotificationSettings settings;

  Future setUpNotificationServiceForOS() async {
    flutterLocalNotificationsPlugin = FlutterLocalNotificationsPlugin();
    var android = const AndroidInitializationSettings('@mipmap/launcher_icon');
    var ios = const DarwinInitializationSettings(
      requestSoundPermission: true,
      requestBadgePermission: true,
      requestAlertPermission: true,
    );
    var initializationSetting = InitializationSettings(
      android: android,
      iOS: ios,
    );
    await flutterLocalNotificationsPlugin.initialize(initializationSetting);

    await configureFCM();
  }

  Future showNotification(title, notification, payload) async {
    var android = AndroidNotificationDetails(
      'your channel id',
      'your channel name',
      channelDescription: 'your channel description',
      importance: Importance.max,
      color: AppColor.colorPrimaryText,
      priority: Priority.high,
      playSound: true,
      enableVibration: true,
      enableLights: true,
      ticker: 'ticker',
      actions:const <AndroidNotificationAction>[
        AndroidNotificationAction(
          'yes_action', // ID of the action
          'Yes', // Label of the action
          showsUserInterface: true,
          titleColor: Colors.white,
        ),
        AndroidNotificationAction(
          'no_action', // ID of the action
          'No', // Label of the action
          showsUserInterface: true,
          titleColor: Colors.white,
        ),
      ],
    );

    var ios = const DarwinNotificationDetails(
        presentAlert: true,
        presentSound: true,
        presentBadge: true,
        presentBanner: true,
        presentList: true);

    var platformSpecifics = NotificationDetails(
      android: android,
      iOS: ios,
    );

    Random random = Random();
    int uniqueNumber = random.nextInt(1000);
    debugPrint("object number is $uniqueNumber");

    var load = jsonDecode(payload);
    debugPrint("payload is $load");

    await flutterLocalNotificationsPlugin.show(
        uniqueNumber, '$title', '$notification', platformSpecifics,
        payload: payload);
  }

  Future<void> configureFCM() async {
    fcm = FirebaseMessaging.instance;

    settings = await fcm.requestPermission(
      alert: true,
      announcement: false,
      badge: true,
      carPlay: false,
      criticalAlert: false,
      provisional: false,
      sound: true,
    );

    if (kDebugMode) {
      debugPrint('User granted permission');
    }

    FirebaseMessaging.onMessage.listen((RemoteMessage message) async {
      debugPrint("Received notification ${message.notification!.toMap()}");
      debugPrint("Toast message is here ${message.data}");
      debugPrint("Ref id is here ${message.data["ref_id"]}");
      showNotification(
        message.notification!.title,
        message.notification!.body,
        jsonEncode(message.data),
      );
    });

    FirebaseMessaging.onBackgroundMessage(firebaseMessagingBackgroundHandler);
  }
}

@pragma('vm:entry-point')
Future<void> firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  debugPrint('Handling a background message ${message.messageId}');
  await Firebase.initializeApp();
}
`

**Comment by emersion** [comment]
Please don't ping me to have a look at your issues.

**Comment by MaikuB** [comment]
This isn't a plugin problem but a problem with your implementation. Please make sure you are familiar with the behaviours of the libraries you use
