### ISSUE TITLE
Please adapt to Android 14 as soon as possible

### ISSUE THREAD

**Issue by zhengqingqing** [MaikuB/flutter_local_notifications#2256]

**Comment by MaikuB** [comment]
Note this is an open-source project worked on in spare time with contributions from the community. If you're dependent on this project then you should look at making contributions as well

**Comment by MaikuB** [comment]
Another thing is your post doesn't mention much. Permission checks relevant to Android 14 were added in 16.0. If you're an older version of the plugin then note that you need upgrade

**Comment by Mike-Benoit** [comment]
Local notifications are not appearing for us on Android 14, but work fine on older versions.

**Comment by MaikuB** [comment]
Closer to due lack of further response and from what I've experienced and seen, plugin already supports Android 14
