### ISSUE TITLE
Expired scheduled notifications on restart

### ISSUE THREAD

**Issue by rovshan-b** [MaikuB/flutter_local_notifications#2263]
Hi.
When I schedule a notification in an alarm clock app, and user turns off phone, some time passes and when user turns on his phone again, all expired notifications also come up immediately. But in alarm clock app, they are already expired and are not necessary any more.
Is there an option to specify that expired notifications should not come up on phone boot?

**Comment by MaikuB** [comment]
No there isn't and this is how I've seen the native APIs work for iOS with no control over it. It could be possible for Android only but then you would have inconsistent behaviours on both platforms. If you are fine with this then you'll likely need to look a fork for your app as the approach taken for the plugin is to try to have all the platforms behave consistently as much as possible. Note that it might also be that you need to consider using a different approach for your app in a general but that would be something you would need to research into
