### ISSUE TITLE
Updating of installing doc with Plugin DSL

### ISSUE THREAD

**Issue by atharvsharma1998** [MaikuB/flutter_local_notifications#2264]
I have recently updated my project to Flutter 3.19.3. As a result I had to manually upgrade to use Plugin DSL(https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply) I keep on getting

```
 Plugin [id: 'com.android.tools.build', version: '7.3.0', apply: false] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Included Builds (None of the included builds contain this plugin)
- Plugin Repositories (could not resolve plugin artifact 'com.android.tools.build:com.android.tools.build.gradle.plugin:7.3.0')
  Searched in the following repositories:
    Google
    MavenRepo
    Gradle Central Plugin Repository
 ```
Im unable to figure out how to solve this

**Comment by pechischev** [comment]
I have the same request on updating installing doc for android

**Comment by MaikuB** [comment]
The only difference when using the plugin DSL syntax is around specifying the AGP version where the plugin says you should aim to be on 7.3.1 at a minimum. The docs you linked to at https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply already document where the AGP version is specified. The rest of the steps mentioned in the plugin still apply
