### ISSUE TITLE
iOS - onDidReceiveNotificationResponse method not function

### ISSUE THREAD

**Issue by emanuelzallikodelabs** [MaikuB/flutter_local_notifications#2266]
In iOS onDidReceiveNotificationResponse method when app is in foreground not function in android work fine

When I schedule notification and after I click on notification I don't get payload just in Android devices, but when app is killed and I click in notification work fine, I want to get payload when app is running.

I have latest version: flutter_local_notifications: ^17.0.0

Flutter 3.19.3
Dart 3.3.1 • DevTools 2.31.1

**Comment by emanuelzallikodelabs** [comment]
Add this code in AppDelegate.swift
 
@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    FirebaseApp.configure()

    GeneratedPluginRegistrant.register(with: self)
    UNUserNotificationCenter.current().delegate = self
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
    
    override func userNotificationCenter(
          _ center: UNUserNotificationCenter,
          willPresent notification: UNNotification,
          withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void
      ) {
          completionHandler([.alert, .sound, .badge])
      }
}

**Comment by dilpreetgill550** [comment]
Hi, same issue the code you provided works on ios but not on macos?
