### ISSUE TITLE
Flutter local notification not works properly when the app is terminated

### ISSUE THREAD

**Issue by santhoshkumar4035** [MaikuB/flutter_local_notifications#2267]
import 'package:flutter/material.dart';
    import 'package:flutter_local_notifications/flutter_local_notifications.dart';
    
    void main() => runApp(MyApp());
    
    class MyApp extends StatelessWidget {
      // This widget is the root of your application.
      @override
      Widget build(BuildContext context) {
        return MaterialApp(
          debugShowCheckedModeBanner: false,
          title: 'Flutter Demo',
          theme: ThemeData(
            // is not restarted.
            primarySwatch: Colors.blue,
          ),
          home: MyHomePage(title: 'Local Notifications'),
        );
      }
    }
    
    class MyHomePage extends StatefulWidget {
      MyHomePage({Key key, this.title}) : super(key: key);
    
      final String title;
    
      @override
      _MyHomePageState createState() => _MyHomePageState();
    }
    
    class _MyHomePageState extends State<MyHomePage> {
      FlutterLocalNotificationsPlugin flutterNotificationPlugin;
    
      @override
      void initState() {
        var initializationSettingsAndroid =
            new AndroidInitializationSettings('app_icon');
    
        var initializationSettingsIOS = new IOSInitializationSettings();
    
        var initializationSettings = new InitializationSettings(
            android: initializationSettingsAndroid, iOS: initializationSettingsIOS);
    
        flutterNotificationPlugin = FlutterLocalNotificationsPlugin();
    
        flutterNotificationPlugin.initialize(initializationSettings,
            onSelectNotification: onSelectNotification);
      }
    
      Future onSelectNotification(String payload) async {
        showDialog(
            context: context,
            builder: (_) => AlertDialog(
                  title: Text("Hello Everyone"),
                  content: Text("$payload"),
                ));
      }
    
      @override
      Widget build(BuildContext context) {
        return Scaffold(
          appBar: AppBar(
            title: Text(widget.title),
          ),
          body: Center(
              child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              TextButton(
                child: Text("Notification with Default Sound"),
                onPressed: () {
                  notificationDefaultSound();
                },
              ),
            ],
          )),
        );
      }
    
      Future notificationDefaultSound() async {
        var androidPlatformChannelSpecifics = AndroidNotificationDetails(
          'Notification Channel ID',
          'Channel Name',
          channelDescription: 'Description',
          importance: Importance.max,
          priority: Priority.high,
        );
    
        var iOSPlatformChannelSpecifics = IOSNotificationDetails();
    
        var platformChannelSpecifics = NotificationDetails(
            android: androidPlatformChannelSpecifics,
            iOS: iOSPlatformChannelSpecifics);
    
        flutterNotificationPlugin.show(0, 'New Alert',
            'How to show Local Notification', platformChannelSpecifics,
            payload: 'Default Sound');
      }
    }

**Comment by MaikuB** [comment]
Please add more details on what it is you're trying to describe as besides the title, the only other thing mentioned here is some code

**Comment by MaikuB** [comment]
Closing due to lack of response. I would say though that based on the code you shared, you think the plugin isn't working properly when it comes to responding to when the notification is tapped on and the app is terminated. If so, the issue is that your app is missing code to handle this properly and you'll need to go through the readme again on this
