### ISSUE TITLE
Foreground notification click event 

### ISSUE THREAD

**Issue by praveengitsit-pro** [MaikuB/flutter_local_notifications#2272]
_Not sure this is a bug but I looked through the documentations and could not find anything for this feature._ 

**Describe the bug**
I cannot know when a user clicked on a notification when app is in foreground

**To Reproduce**

1. App is in foreground
2. App receives notification
3. User clicks on notification 
4. Nothing happens

**Expected behavior**
I want something like the `FirebaseMessaging`'s `onMessageOpenedApp` method that exposes when a user has clicked on a notification when app is in background.

**Comment by ib-ganz** [comment]
did you find a solution?

**Comment by MaikuB** [comment]
This is explained in the readme at https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#initialisation and the repo has an example app and this is mentioned in the issue template when trying to submit a report as well
