### ISSUE TITLE
didNotificationLaunchApp always return false on ios when app killed

### ISSUE THREAD

**Issue by mystery198** [MaikuB/flutter_local_notifications#2273]
**Describe the bug**
I had the problem didNotificationLaunchApp always returns false (payload is null) on ios, on android it works fine. Even though I tried running the example in your repo, the result is still the same.

**To Reproduce**
1. Download source code in repo
2. Run flutter_local_notification/example
3. After the application is run, kill it
4. Send notification to device
5. Click notification
6. App opened -> but didNotificationLaunchApp return false and initialRoute always is HomePage, not SecondPage

**Expected behavior**
How to make it work properly in case the app has been killed and click on the notification to open the app, with payload data

https://github.com/MaikuB/flutter_local_notifications/assets/92310829/9105d2c1-2ca5-482d-a333-4eb34e674aef

**Comment by MaikuB** [comment]
Based on the video you shared, it doesn't sound like you actually followed the steps in you mentioned. The video shows the content of the notification is different. If you actually clone the repo then it works as expected. The video you showed would indicate to me that you've copied the Dart code or made modifications that doesn't with what's actually done in the example app and mentioned in the readme e.g. https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#-ios-setup
