### ISSUE TITLE
[Feature Request] : Add a custom RepeatInterval value

### ISSUE THREAD

**Issue by Tom3652** [MaikuB/flutter_local_notifications#2274]
Hello ! 

Thanks for the amazing package that is very useful. 
It's not a bug report but a feature request regarding having a custom interval value to schedule notifications / reminder. 

Thanks in advance for your consideration !

**Comment by MaikuB** [comment]
There's already a feature request at https://github.com/MaikuB/flutter_local_notifications/issues/92 and PR at https://github.com/MaikuB/flutter_local_notifications/pull/2197 so closing this as duplicate. Note that native APIs don't support a combination of a date and custom interval. If your scenario is also do to with what I linked, please help test it out. I have left comments to the author to address that's more on minor cleanup. I've done testing myself but would like to see the community help out and if it works as expect then I could look at doing the cleanup myself when I can and merge it in

**Comment by Tom3652** [comment]
Oh alright perfect this is exactly what i needed. 
Indeed i have forked the project and added custom intervals myself for my Android app and it works very fine but i have not done any testing on iOS nor considering it. 
My scenario is very basic, just showing periodic notifications at specific intervals like every 2 days, every 6 hours and so on so my naive approach is that i didn't think there would be "more" complications with 2 days than with 1 day since it's "Just maths", but i get it that it's more complicated than this obviously 😅

**Comment by MaikuB** [comment]
If the code in the PR is same as what you're after, would you be about to help test using the fork and let me know how it goes?
