### ISSUE TITLE
No sound playing on Android 12

### ISSUE THREAD

**Issue by GabLedesma** [MaikuB/flutter_local_notifications#2278]
**Describe the bug**
The notification with custom sound is working fine on my Android 14 but when I use Android 12, the notification is showing but there is no sound. I'm using FCM.

Android channel setup:
<img width="599" alt="Screenshot 2024-03-21 at 9 56 19 AM" src="https://github.com/MaikuB/flutter_local_notifications/assets/36905550/29f6ab59-d638-41bb-9532-531290bc3728">

<img width="621" alt="Screenshot 2024-03-21 at 9 56 45 AM" src="https://github.com/MaikuB/flutter_local_notifications/assets/36905550/9417ad6a-3a48-4967-ac35-1e25c689f706">

How I trigger notification:
<img width="352" alt="Screenshot 2024-03-21 at 9 59 28 AM" src="https://github.com/MaikuB/flutter_local_notifications/assets/36905550/4bbb2e3d-029b-4d9c-8369-9bda00dd53c2">

**Comment by ditheshthegreat** [comment]
@GabLedesma 
`    test(
        'show with default Android-specific details and custom sound from raw '
        'resource', () async {
      const AndroidInitializationSettings androidInitializationSettings =
          AndroidInitializationSettings('app_icon');
      const InitializationSettings initializationSettings =
          InitializationSettings(android: androidInitializationSettings);
      await flutterLocalNotificationsPlugin.initialize(initializationSettings);
      const AndroidNotificationDetails androidNotificationDetails =
          AndroidNotificationDetails(
        'channelId',
        'channelName',
        channelDescription: 'channelDescription',
        sound: RawResourceAndroidNotificationSound('sound.mp3'),
      );`

Based on test case, you need to specify the file type in 'RawResourceAndroidNotificationSound'

**Comment by InShad7** [comment]
by providing the extension to the RawResourceAndroidNotificationSound('sound.mp3'),

Error scheduling notification: PlatformException(invalid_sound, The resource asound.mp3 could not be found. Please make sure it has been added as a raw resource to your Android head project., null, null)

**Comment by MaikuB** [comment]
I've had a Pixel 6 that's had Android 12 on it before with the plugin and not had these issues. I don't recall others saying they had such issues either. From what I know with how the APIs work, there's no OS-specific issues when it comes to notification sounds unless there is something that the manufacturer has done with their version of Android. With that in mind, this isn't something I can help with and you'd need to investigate further. One thing I'll also mention is to check in both cases that you're actually triggering the local notification via this plugin to avoid confusion between a local notification and push notification from FCM
