### ISSUE TITLE
Display scheduled notification conditionally

### ISSUE THREAD

**Issue by Ran-E** [MaikuB/flutter_local_notifications#2281]
I am using flutter_local_notifications plugin to schedule notifications, but I want to achieve two things.

- The scheduled notification should run some code every time, before showing the notification to check whether or not to display the notification.
- I want to specify a custom time interval, instead of the options given by RepeatInterval

**Comment by MaikuB** [comment]
This isn't possible via the plugin. This is something you would need to investigate further for your app. What you're describing is scheduling a notification but scheduling general logic to run that may then trigger a notification to show. This may be where you may need to consider plugins such as https://pub.dev/packages/workmanager
