### ISSUE TITLE
Android direct reply

### ISSUE THREAD

**Issue by ssorrychoi** [MaikuB/flutter_local_notifications#2284]
Hello, flutter developers. 

I hope this message finds you well. I am currently developing an application using the Flutter Local Notifications library and I am particularly interested in implementing the "direct reply" feature for notifications on Android devices. This functionality is crucial for enhancing user interaction within my app by allowing users to respond to notifications directly from the notification interface.

I have looked through the current documentation and resources available for the Flutter Local Notifications library, but I was unable to find specific guidance or examples on how to implement the "direct reply" feature within the context of this library.

Could you please advise if the "direct reply" feature is supported by the Flutter Local Notifications library? If it is supported, could you provide me with any examples, documentation, or links that detail how to implement this feature within my Flutter application?

Additionally, if this feature is not currently supported, are there any plans to include "direct reply" functionality in future updates of the library? Any information on potential timelines or development plans would be greatly appreciated.

Thank you for your time and assistance. I look forward to your response and any guidance you can provide.

**Comment by MaikuB** [comment]
This is covered in the example app that you can run and check around https://github.com/MaikuB/flutter_local_notifications/blob/5375645b01c845998606b58a3d97b278c5b2cefa/flutter_local_notifications/example/lib/main.dart#L561
