### ISSUE TITLE
Why there is no implementation for the Windows

### ISSUE THREAD

**Issue by abdulrehman192** [MaikuB/flutter_local_notifications#2285]
Please add the notification for windows and web as well.

**Comment by MaikuB** [comment]
There's already an existing issue on Windows https://github.com/MaikuB/flutter_local_notifications/issues/746. This is open-source so you can contribute to it. With that in mind, I'd ask that you be mindful when asking questions like "Why there is no implementation for the Windows" in the future when engaging others in the community
