### ISSUE TITLE
'flutter_local_notifications' requires core library desugaring to be enabled for app

### ISSUE THREAD

**Issue by hafeezrana** [MaikuB/flutter_local_notifications#2286]
when I run the app. It crashes .
where as the compatible versions are

-  flutter_local_notifications: 17.0.0
-  ext.kotlin_version = '1.8.0'
-  compileSdkVersion 34
-  minSdkVersion 26
-  targetSdkVersion 34

- Flutter Version : 3.19.3

Console Output:
<img width="934" alt="Screenshot 2024-03-30 at 11 43 10 PM" src="https://github.com/MaikuB/flutter_local_notifications/assets/87476445/e5ec432c-4c36-4411-ae0f-21e2e754730c">

**Comment by khalidrinaldy** [comment]
have you fix this issue?

**Comment by hafeezrana** [comment]
> have you fix this issue?

not yet. Still facing the same .

**Comment by Silfalion** [comment]
have the same issue

**Comment by Silfalion** [comment]
Check this https://pub.dev/packages/flutter_local_notifications#gradle-setup

You need to add a compile option as well as a dependency for the the desugaring core library

**Comment by khalidrinaldy** [comment]
I added on build.gradle:app like

`compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17

        // add this code
        coreLibraryDesugaringEnabled true
    }`

`dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation platform('com.google.firebase:firebase-bom:30.4.1')
    implementation 'com.google.firebase:firebase-analytics'

    // add these codes
    // you can upgrade the window library too
    implementation 'androidx.window:window:1.0.0'
    implementation 'androidx.window:window-java:1.0.0'
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.2.2'
}`

this solved my issue

**Comment by hafeezrana** [comment]
> I added on build.gradle:app like
> 
> `compileOptions { sourceCompatibility JavaVersion.VERSION_17 targetCompatibility JavaVersion.VERSION_17
> 
> ```
>     // add this code
>     coreLibraryDesugaringEnabled true
> }`
> ```
> 
> `dependencies { implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version" implementation platform('com.google.firebase:firebase-bom:30.4.1') implementation 'com.google.firebase:firebase-analytics'
> 
> ```
> // add these codes
> // you can upgrade the window library too
> implementation 'androidx.window:window:1.0.0'
> implementation 'androidx.window:window-java:1.0.0'
> coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.2.2'
> ```
> 
> }`
> 
> this solved my issue

**Comment by agelospanagiotakis** [comment]
i will try these solutions as i am still not able to compile correctly for google to accept my app
anyhow the documentation should be updated for clarity

**Comment by ITApexGroup** [comment]
> I added on build.gradle:app like
> 
> `compileOptions { sourceCompatibility JavaVersion.VERSION_17 targetCompatibility JavaVersion.VERSION_17
> 
> ```
>     // add this code
>     coreLibraryDesugaringEnabled true
> }`
> ```
> 
> `dependencies { implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version" implementation platform('com.google.firebase:firebase-bom:30.4.1') implementation 'com.google.firebase:firebase-analytics'
> 
> ```
> // add these codes
> // you can upgrade the window library too
> implementation 'androidx.window:window:1.0.0'
> implementation 'androidx.window:window-java:1.0.0'
> coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.2.2'
> ```
> 
> }`
> 
> this solved my issue

<img width="883" alt="Screenshot 2024-10-25 at 14 45 37" src="https://github.com/user-attachments/assets/9c332633-310f-47da-abc3-3f8e76ac92f7">
How to add   coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.2.2' and  coreLibraryDesugaringEnabled true my file

**Comment by wahyudizulhaidar** [comment]
> <img alt="Screenshot 2024-10-25 at 14 45 37" width="883" src="https://private-user-images.githubusercontent.com/59428338/380070820-9c332633-310f-47da-abc3-3f8e76ac92f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MTU1NTcsIm5iZiI6MTczMjUxNTI1NywicGF0aCI6Ii81OTQyODMzOC8zODAwNzA4MjAtOWMzMzI2MzMtMzEwZi00N2RhLWFiYzMtM2Y4ZTc2YWM5MmY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDA2MTQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwZmVkMmI1NThmY2UyMWYxOGY1NTg4ZWFmNDNmNzkwMjY0MjhlZWJkOTExMzY1NWQzMDhkZDk1MjFkMGJmNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.17BgBPt-5zz4mB-2iPZcWxojFUykFrcFD8gR2177y3E"> How to add coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.2.2' and coreLibraryDesugaringEnabled true my file

To add these dependencies, include them in the app-level build.gradle 

```
android {
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
        coreLibraryDesugaringEnabled true // add this
}

dependencies {
    // add required dependencies here
}
```

**Comment by khairulanas** [comment]
> I added on build.gradle:app like
> 
> `compileOptions { sourceCompatibility JavaVersion.VERSION_17 targetCompatibility JavaVersion.VERSION_17
> 
> ```
>     // add this code
>     coreLibraryDesugaringEnabled true
> }`
> ```
> 
> `dependencies { implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version" implementation platform('com.google.firebase:firebase-bom:30.4.1') implementation 'com.google.firebase:firebase-analytics'
> 
> ```
> // add these codes
> // you can upgrade the window library too
> implementation 'androidx.window:window:1.0.0'
> implementation 'androidx.window:window-java:1.0.0'
> coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.2.2'
> ```
> 
> }`
> 
> this solved my issue

thanks, it works:
![image](https://github.com/user-attachments/assets/7221ee21-57ab-4fb2-9799-d30bc9cbc536)

**Comment by Levi-Lesches** [comment]
Updated docs are temporarily [here](https://github.com/Levi-Lesches/flutter_local_notifications/blob/readme-refactor/flutter_local_notifications/docs/android-setup.md), see #2477 for progress

**Comment by saranshane** [comment]
> I added on build.gradle:app like
> 
> `compileOptions { sourceCompatibility JavaVersion.VERSION_17 targetCompatibility JavaVersion.VERSION_17
> 
> ```
>     // add this code
>     coreLibraryDesugaringEnabled true
> }`
> ```
> 
> `dependencies { implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version" implementation platform('com.google.firebase:firebase-bom:30.4.1') implementation 'com.google.firebase:firebase-analytics'
> 
> ```
> // add these codes
> // you can upgrade the window library too
> implementation 'androidx.window:window:1.0.0'
> implementation 'androidx.window:window-java:1.0.0'
> coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.2.2'
> ```
> 
> }`
> 
> this solved my issue

This One Works

**Comment by iamraghavan** [comment]
Yeah, it's Buddy's @MaikuB who can fix this officially, or the Flutter official team can fix this natively.

**Comment by FlorianKipeta** [comment]
Version 10+ on the plugin now relies on [desugaring](https://developer.android.com/studio/write/java8-support#library-desugaring) to support scheduled notifications with backwards compatibility on older versions of Android. Developers will need to update their application's Gradle file at android/app/build.gradle. Please see the link on desugaring for details but for convenience, you can expand below to see the relevant portions based on if your app has a build.gradle or build.gradle.kts file

`android {
    defaultConfig {
        multiDexEnabled = true
    }

    compileOptions {
        // Flag to enable support for the new language APIs
        isCoreLibraryDesugaringEnabled = true
        // Sets Java compatibility to Java 11
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
  
    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_11.toString()
    }
}

dependencies {
    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.1.4")
}`

**Comment by Himanshusha673** [comment]
For build.gradle.kts 

 compileOptions {
        isCoreLibraryDesugaringEnabled = true
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
       
    }

and in dependencies use

dependencies {
    implementation("androidx.window:window:1.0.0")
    implementation("androidx.window:window-java:1.0.0")
    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.1.4")
