### ISSUE TITLE
Can't group scheduled Android notifications without grouping per new notification

### ISSUE THREAD

**Issue by auradigitaldev** [MaikuB/flutter_local_notifications#2292]
I'm trying to group scheduled notifications, but am having issues because AFAICT the only way to group scheduled notifications is to schedule a notification with `setAsGroupSummary=true`. When a new notification is delivered I want it to be added to the group (if it already exists) or create a group if none already exists. However, I don't see a way to do this with scheduled notifications other than scheduling a group summary notification for every standard notification.

Let me know if this makes sense, and if there are any workarounds!

**Comment by MaikuB** [comment]
This isn't a plugin specific issue and would be what is expected by the native platform that you should check the Android docs on this
