### ISSUE TITLE
Documentation link out of date for Gradle desugaring

### ISSUE THREAD

**Issue by jamesncl** [MaikuB/flutter_local_notifications#2293]
The link in the README to the desugaring setup documentation is currently:

[https://developer.android.com/studio/releases/gradle-plugin#j8-library-desugaring](https://developer.android.com/studio/releases/gradle-plugin#j8-library-desugaring)

This appears to be out of date because that page has no mention of desugaring. I believe this is the correct link:

[https://developer.android.com/studio/write/java8-support#library-desugaring](https://developer.android.com/studio/write/java8-support#library-desugaring)

**Comment by jamesncl** [comment]
[PR](https://github.com/jamesncl/flutter_local_notifications/pull/1)

**Comment by MaikuB** [comment]
Thanks for raising this. The PR got raised on your fork. Would you be update it so it's raised on this repository?

**Comment by jamesncl** [comment]
Sorry, I'm still learning how to do PRs! I think I've done it correctly now
