### ISSUE TITLE
Support updating/rescheduling a pending notification

### ISSUE THREAD

**Issue by auradigitaldev** [MaikuB/flutter_local_notifications#2295]
For my to-do list app, it would be nice to be able to update pending notifications. However, there is not enough data in the PendingNotificationRequest to be able to schedule an identical notification with maybe 1-2 different fields.

One example use case is updating the time zone of all of the pending notifications when switching time zones, but there are many others (updating a todo list item time, name, description, etc).

**Comment by MaikuB** [comment]
This plugin may not be suitable in covering all use cases. This is where you as a developer need to decide whether or not using the plugin is appropriate and can either write the native code yourself or look at having a fork
