### ISSUE TITLE
How can I send a local notifications instead of a firebase notification

### ISSUE THREAD

**Issue by woshitom** [MaikuB/flutter_local_notifications#230]
Hi,

I'm using Firebase messaging to send my push notifications but I can only display text.
My goal is to display a local notification (with an image) when a Firebase notification is received.
Should I trigger the local notification in the Firebase  Messaging's callbacks? And if I do so, both notifications will be displayed right?

**Comment by MaikuB** [comment]
From my understanding, yes. You may need to learn the difference between data and notification messages

https://firebase.google.com/docs/cloud-messaging/concept-options

If you were to send data notifications then you could use callbacks to show a local notification but there are limitations in `firebase_messaging` when it comes to handling data messages that is covered in the plugin's readme

**Comment by joaomarcos96** [comment]
Is there a way to receive notifications with `firebase_messaging` OR with `flutter_local_notifications` based on a condition, without ending up with a duplicate notification?
