### ISSUE TITLE
Can't avoid empty group summary notifications when dimissing child notifications

### ISSUE THREAD

**Issue by auradigitaldev** [MaikuB/flutter_local_notifications#2300]
I'm running into an issue with group notifications. Basically, I want notifications from my app to always be grouped, but I never want the group summary to be able to be shown on its own. To accomplish this, every time any number of notifications is scheduled at a specific time, I also schedule a group notification (because there's no way of knowing whether a group notification is active when the new notifications fire). However, I've been realizing that this means that if I schedule two sets of notifications, I'll have two group notifications and so after dismissing all the child notifications, an empty group notification will show.

Is there any way around this issue? I'm trying to imitate the behavior of other to-do list apps such as Google Tasks and Todoist, which both seem to be able to pull off this desired behavior. The most promising approach to me was to cancel all active notifications if the only active notifications remaining after a notification tap are all group notifications, but this doesn't work to dismiss group notifications when the user swipes away the child notifications instead of tapping on them. I also tried making all my group notifications fire with the same notification ID, but we're not allowed to have 2 pending notifications with the same ID.

**Comment by MaikuB** [comment]
You'll need to read the Android docs around how grouping notifications works and what the OS expects. This isn't a plugin-specific issue so will be closing this
