### ISSUE TITLE
Gradle build failed

### ISSUE THREAD

**Issue by apiornoIA** [MaikuB/flutter_local_notifications#2305]
**Describe the bug**
I am trying to build my app on android side in release mode and i got errors from this plugin: 

com.dexterous.flutterlocalnotifications.IsolatePreferencesTest > saveAndGet_ShouldReturnCorrectValues FAILED
    java.lang.NoClassDefFoundError at Shadows.java:2457
        Caused by: java.lang.ClassNotFoundException at SandboxClassLoader.java:161
            Caused by: java.lang.IllegalArgumentException at ClassReader.java:199

com.dexterous.flutterlocalnotifications.models.NotificationActionTest > constructor_populatesAllFields FAILED
    java.lang.NoClassDefFoundError at Shadows.java:2457
        Caused by: java.lang.ClassNotFoundException at SandboxClassLoader.java:161
            Caused by: java.lang.IllegalArgumentException at ClassReader.java:199

**To Reproduce**
I run ./gradlew clean build

**Expected behavior**
Not crush

**Sample code to reproduce the problem**
Just having it as a dependency and running the gradle build

**Comment by MaikuB** [comment]
This kind of error is indicates your app hasn't completed all of the platform-specific configuration that is covered in the readme. Please make sure you check your app and cross reference with the readme thoroughly
