### ISSUE TITLE
Remove GSON dependency

### ISSUE THREAD

**Issue by ened** [MaikuB/flutter_local_notifications#231]
Does this plugin really need the GSON dependency to read/write notifications into the shared preferences?

Android has JSON classes included as well.
Could those, or a simpler property list format, be used instead?

**Comment by MaikuB** [comment]
From what I recall seeing with the other approaches, they seemed too simple and required more manual work to convert between classes and json when compared to GSON. 

Sounds like you have reservation with GSON? If there's a better approach that I may have missed, I'm happy to accept contributions provided it won't cause a breaking change when apps upgrade.

**Comment by ened** [comment]
My only reservation is to pull in external dependencies on each plugin which:
 - increase APK size
   - Should be fine if every 3rd party plugin uses the same json dependency, however there are alternatives and developers can choose whatever they like.
 - increase integration effort
   - GSON on release builds will require special Proguard configuration - else this notifications plugin dies ungracefully once instantiated.

**Comment by MaikuB** [comment]
I'm not sure what you're trying to convey in the first point as it's not like developers are forced to use GSON directly. A search also seems to shows that GSON is also being used in Google's `firebase_auth` plugin so I would imagine it's already been picked as the standard so to speak. Probably runs into the same Proguard configuration issue you're referring to as well unless they've been able to get around that

**Comment by ened** [comment]
@MaikuB 

1. My point is that different plugin developers may choose additional 3rd party libraries, at any version, to solve essentially the same problems while functionality is already included in the platform.

JSON parsing can be done with GSON, Jackson, Moshi and probably many other future libraries that solve it or reduce a few lines of code.

2. Will take a look at firebase_auth - it uses Gson to parse a SINGLE field out of the the Phone Credentials response. This may warrant a simplification PR as well to reduce dependencies. Thank you for pointing it out.

**Comment by MaikuB** [comment]
Fair enough. As mentioned earlier, I'm happy to accept contributions for these changes as plugins like this are things I can only work on in my spare time. Happy to be involved discussing the changes that would be needed as well. If you look into it, you may find there better ways to improve the Android code in general as I come from more of a .NET background

**Comment by MaikuB** [comment]
I'm closing this as this is something I won't be looking to address myself and haven't heard of others that feel that this is a significant issue
