### ISSUE TITLE
Notification color on Samsung device

### ISSUE THREAD

**Issue by danielL22** [MaikuB/flutter_local_notifications#2310]
Hello everyone,
on samsung phones you can choose between a short and a detailed notification style. The detailed is like the normal notification style for android while the short one is an one liner with settings for a light effect on the screen border. This effect can have a color by setting one or let the system set an automatic color for your app.
Now I set the notification color in my showLocalNotification-function to a pink. This works with the detailed-style but as soon as I set it to the short style the color stays green for some reason. In the notification settings the color is set to be choosen automatically

This is the code for showing the notification:
``` 
void showLocalNotification(String title, String body) {
    debugPrint("Trying to notify");
    try{
      const androidNotificationDetail = AndroidNotificationDetails(
        '0', //channel Id
        'general', //channel name,
        importance: Importance.max,
        priority: Priority.high,
        ticker: 'ticker',
        color: Color(0xFFFF5B9E),
      );
      const iosNotificatonDetail = DarwinNotificationDetails();
      const notificationDetails = NotificationDetails(
        iOS: iosNotificatonDetail,
        android: androidNotificationDetail,
      );
      _flutterLocalNotificationsPlugin.show(0, title, body, notificationDetails, payload: "test");
    }catch(e){
      debugPrint(e.toString());
    }
  }
  ```

![Screenshot_20240421_232627](https://github.com/MaikuB/flutter_local_notifications/assets/62314277/96a116f9-4b65-41c3-8958-47d304fff208)
![Screenshot_20240421_232702](https://github.com/MaikuB/flutter_local_notifications/assets/62314277/1fb1883d-d9ad-46fe-9359-f31577145e3c)

**Comment by MaikuB** [comment]
Android doesn't have APIs for brand/OEM-specific functionality. This may be why you see this issue and there may nothing else that can be done. Closing as there's nothing further the plugin can do

**Comment by vinecave** [comment]
Other applications, that probably do not use Flutter - not having this problem.

**Comment by danielL22** [comment]
Searching a solution I directly contacted the samsung support regarding this issue. Their response was that there is no way to set the colors programmatically

> Unfortunately, it is not possible to programmatically set colors for brief notifications. Brief notification color can be only set in two ways: 1. By default, color is extracted from the App icon that is showing in launcher. 2. The user changes brief popup color for all popup notification.

They also told me that the color is picked according to Android Palette API

> For more information regarding extracting colors from image, you can check the Android Palette API: https://developer.android.com/develop/ui/views/graphics/palette-colors 
For the icon file you provided, this library will return the green color (specifically #00f878) as the vibrant color.

**Comment by MaikuB** [comment]
@vinecave the "brand-specific" comment I left has a specific context and that is around how this plugin provides a wrapper for the official Android notification APIs. Even if the other brands happen to have some way to do so, it would be via other APIs. This could be something the brands have (e.g. like how there's other unofficial APIs to handle badging) or  like what @danielL22 shared

**Comment by vinecave** [comment]
@MaikuB @danielL22 Yeah, it happens so, that OneUI uses most dominant app icon color calculation to pick that color, that is how that Android Palette API works, but only if you are not using custom color palette in OneUI. Other apps have icons, both in "brief" and "detailed" popup coloured the same color, because their notification icon color settings and the app icon itself - has the same color shades. That is why, may be, majority of Android apps have flat mono-colored icons - to be compliant with Palette API usage, because it picks main color in you app icon.
