### ISSUE TITLE
iOS pending notification limit

### ISSUE THREAD

**Issue by armandsLa** [MaikuB/flutter_local_notifications#2312]
**Describe the bug**
Scheduling more than 64 local notifications on iOS results in no notifications being fired. I'm aware of the 64 notification limit on iOS, but the documentation states that scheduling more than 64 notifications will preserve the soonest ones. I'm not sure if this issue is a bug in the `flutter_local_notifications` or in Apple's user notification framework.

**To Reproduce**
1. Schedule 65 local notifications
2. Wait for them to fire - nothing will happen

**Expected behavior**
64 soonest notifications to be fired instead of no notifications being fired.

**Comment by MaikuB** [comment]
If you believe there's an issue with the plugin then you'll need to provide a link to a repo hosting a minimal app that can reproduce the problem. Personally this is something I've already tried before and another member of the community has shown this worked at https://github.com/MaikuB/flutter_local_notifications/issues/2275 that they submitted a PR to update the documentation on the behaviour so it's more accurate. Based on this, I would suspect there's an issue in your app for you to investigate further
