### ISSUE TITLE
Issue with Android 14

### ISSUE THREAD

**Issue by p3pp8** [MaikuB/flutter_local_notifications#2316]
Hello there, i'm facing an issue with a device running on Android 14 OS, the device is Galaxy A23 5g. 
I followed the configuration steps and everything seem to be ok, i set permission to use SCHEDULE_EXACT_ALARM and request permission for OS 14 as described in the guide but when i run my application it opens the alarms permission screen but the authorization switch is locked and i'm not able to enable it, so the plugin initialization fails with:

`
Unhandled Exception: PlatformException(exact_alarms_not_permitted, Exact alarms are not permitted, null, nul
`

Of course adding USE_EXACT_ALARMS permission everything works just fine but as you know this permission is subject to vendor revision.

Any help really appreciated!

**Comment by adnanjpg** [comment]
please first of all make sure you're on the latest version.

if you're not building an alarm app, setting `zonedSchedule` method's `androidScheduleMode` parameter to `AndroidScheduleMode.inexact` or `AndroidScheduleMode.inexactAllowWhileIdle` will fix this for you.

```dart
final myinst = FlutterLocalNotificationsPlugin();
myinst.zonedSchedule(
            ...,
            ...,
            ...,
            ....,
            ...,
            androidScheduleMode: AndroidScheduleMode.inexactAllowWhileIdle, // or AndroidScheduleMode.inexact
);
```

**Comment by p3pp8** [comment]
Hello, thank You for the answer, yes i'm using latest version of the plugin but unfortunately setting to mode inexact doesn't solve the issue, the switch button in system alarms and reminders screen is still locked.

**Comment by p3pp8** [comment]
@adnanjpg Yes, it works, even when permission switch is locked. It solved the issue. Thank You!

**Comment by MaikuB** [comment]
Sounds like OP has gotten issue resolved so closing this

**Comment by Istiak-Ahmed78** [comment]
> please first of all make sure you're on the latest version.
> 
> if you're not building an alarm app, setting `zonedSchedule` method's `androidScheduleMode` parameter to `AndroidScheduleMode.inexact` or `AndroidScheduleMode.inexactAllowWhileIdle` will fix this for you.
> 
> ```dart
> final myinst = FlutterLocalNotificationsPlugin();
> myinst.zonedSchedule(
>             ...,
>             ...,
>             ...,
>             ....,
>             ...,
>             androidScheduleMode: AndroidScheduleMode.inexactAllowWhileIdle, // or AndroidScheduleMode.inexact
> );
> ```

Thanks. It worked

**Comment by chiragdhunna** [comment]
> adnanjpg

If it works, why is it not added in the main branch?

@adnanjpg

**Comment by chiragdhunna** [comment]
> please first of all make sure you're on the latest version.
> 
> if you're not building an alarm app, setting `zonedSchedule` method's `androidScheduleMode` parameter to `AndroidScheduleMode.inexact` or `AndroidScheduleMode.inexactAllowWhileIdle` will fix this for you.
> 
> ```dart
> final myinst = FlutterLocalNotificationsPlugin();
> myinst.zonedSchedule(
>             ...,
>             ...,
>             ...,
>             ....,
>             ...,
>             androidScheduleMode: AndroidScheduleMode.inexactAllowWhileIdle, // or AndroidScheduleMode.inexact
> );
> ```

If it works, why is it not in the main branch?

@adnanjpg

**Comment by adnanjpg** [comment]
> > please first of all make sure you're on the latest version.
> > if you're not building an alarm app, setting `zonedSchedule` method's `androidScheduleMode` parameter to `AndroidScheduleMode.inexact` or `AndroidScheduleMode.inexactAllowWhileIdle` will fix this for you.
> > ```dart
> > final myinst = FlutterLocalNotificationsPlugin();
> > myinst.zonedSchedule(
> >             ...,
> >             ...,
> >             ...,
> >             ....,
> >             ...,
> >             androidScheduleMode: AndroidScheduleMode.inexactAllowWhileIdle, // or AndroidScheduleMode.inexact
> > );
> > ```
> 
> If it works, why is it not in the main branch?
> 
> @adnanjpg

Hi, I'm not really sure what you meant by this. Please elaborate the issue you're facing with this.
