### ISSUE TITLE
Notification Body Truncate issue in iOS

### ISSUE THREAD

**Issue by KallepalliTirumalesh** [MaikuB/flutter_local_notifications#2321]
Hi ,
I am working on firebase push notification everything is working fine except in iOS when there is more characters in body the entire notification not showing its truncating the text but works fine on Android.

Is there any limitation for iOS or am i missing anything please let me know

Here is the code:

```
const AndroidNotificationDetails androidPlatformChannelSpecifics =
        AndroidNotificationDetails('your channel id', 'your channel name',
            channelDescription: 'your channel description',
            importance: Importance.max,
            priority: Priority.high,
            styleInformation: BigTextStyleInformation(''),
            ticker: 'ticker');
    const NotificationDetails platformChannelSpecifics =
        NotificationDetails(android: androidPlatformChannelSpecifics);
    await _localNotificationsPlugin.show(0, remoteMessage.notification!.title,
        remoteMessage.notification!.body, platformChannelSpecifics,
        payload: jsonEncode(remoteMessage.data));
```

**Comment by MaikuB** [comment]
This isn't a plugin issue and you also mention Firebase so will be closing this. If you want to know if there's a limitation or not for iOS then you need to do your research onto how iOS behaves
