### ISSUE TITLE
build appbundle  notification sound does not change

### ISSUE THREAD

**Issue by hidayet-poscu** [MaikuB/flutter_local_notifications#2322]
When I send a notification with flutter local notification, the notification sound that I set as the notification sound that I set the device as emulator plays. When I download the flutter build as an appbundle, upload it to the store and download it from there, the sound I set as the notification sound does not play on the same device, but the system notification sound plays. How do I overcome this problem

**Comment by MaikuB** [comment]
Please make sure you've done the all the setup mentioned in the docs. What you described would suggest to me that you hadn't done everything, especially the release build configuration
