### ISSUE TITLE
Repeated/Scheduled notifications should have a condition parameter, only show notification when condition met 

### ISSUE THREAD

**Issue by joukhar** [MaikuB/flutter_local_notifications#2326]
Repeated/Scheduled notifications should have an optional parameter called "condition" as function that return true or false, and show notification when it returns true.

**Comment by MaikuB** [comment]
This isn't possible. Please try to familiarise yourself with the native APIs in the future as this is really a prerequisite before using the plugin so that you understand what the native platforms can and can't do

**Comment by joukhar** [comment]
@MaikuB relax, it was just a suggestion.
