### ISSUE TITLE
Error bigPictureStyle.bigLargeIcon(null) v17.1.2

### ISSUE THREAD

**Issue by JaTocora** [MaikuB/flutter_local_notifications#2329]
flutter_local_notifications-17.1.2/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java:1033: error: reference to bigLargeIcon is ambiguous
      bigPictureStyle.bigLargeIcon(null);
                     ^
  both method bigLargeIcon(Bitmap) in BigPictureStyle and method bigLargeIcon(Icon) in BigPictureStyle match

**Comment by godzyken** [comment]
pareil quelqu'un à t'il resolu ce probleme?

**Comment by MaikuB** [comment]
Whilst I understand why you're seeing this, this isn't something I've seen that can reproduced and hasn't happened via the pipelines. I suspect it might be an issue specific with the Android SDK you're using

**Comment by ducdx-0072** [comment]
I faced this problem too, and I don't understand the reason ;(

**Comment by MaikuB** [comment]
Which versions of the Android SDK do you have installed? I only have the ones for Android 13 and 14 installed and don't have this issue

**Comment by godzyken** [comment]
J'ai aussi 13 et 14

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by MaikuB** [comment]
@godzyken could you write in English please?

**Comment by mark8044** [comment]
> @godzyken could you write in English please?

I just had this issue for the first time today.

I was on master branch `Flutter 3.23.0-13.0.pre.300` and 17.1.2 perfectly fine, then upgraded to master branch `Flutter  3.23.0-13.0.pre.370` and I got the error.

I moved to 17.2.0 and it still occurrs

I downgraded to master branch `Flutter 3.23.0-13.0.pre.300` and its gone.   

This only occurs on Android.  iOS remains ok.

I think something has changed in latest flutter framework, so I believe this needs attention

**Comment by gnprice** [comment]
Very helpful, thanks @mark8044 for bisecting!

That commit changes `bin/internal/engine.version` from flutter/engine@d1506c12808ec42e1b277376c4c2b1bd4ec20ac7 to flutter/engine@ddd4814b9d407962eee4dc52919e3abddb0c3641.

Looking at the Git log between those, it's just three commits:
flutter/engine@3f40c6875 Fix AccessibilityFeatures.disableAnimations flag on Android 12+ (flutter/engine#53428)
flutter/engine@7ccef46a8 Roll Skia from dee7339d0b53 to c73e514838b4 (7 revisions) (flutter/engine#53613)
flutter/engine@ddd4814b9 Re-re-re-land "Upgrade all[most] androidx dependencies to latest" (flutter/engine#53592)

Seems like the last one is the most likely to be related. It's upgrading a long list of AndroidX dependencies.

**Comment by khaled-0** [comment]
exact error is back on flutter 3.24?
I just saw one of our CI fail with this error 
I'll report back with more info soon

**Comment by Ko-Dean** [comment]
I too have similar problem when I run flutter build appbundle.
flutter build version 3.24

**Comment by gnprice** [comment]
Yes, the issue was fixed in #2355 which went out in [flutter_local_notifications 17.2.1](https://github.com/MaikuB/flutter_local_notifications/releases/tag/flutter_local_notifications-v17.2.1). If you're seeing the issue on an older version, you need to upgrade.

**Comment by cyberpwnn** [comment]
Its is very much not fixed

**Comment by gnprice** [comment]
@cyberpwnn If you include details of what you're seeing, that can make it possible for someone to act on your report.

**Comment by gnprice** [comment]
@Volko61 Your error message shows you're using version 12.0.4 of this library. That is older than the fix for this issue. I recommend upgrading.

(Upgrading your dependencies is a good idea in general ­— but in particular when there's a bug that's been fixed and you want the fix, upgrading is the way you get the fix.)

**Comment by Volko61** [comment]
Unfortunately I can't due to to conflicting dependencies.
However, I edited the java file to cast and handle null and now it is working

**Comment by SwamyDigitalRaiz** [comment]
> @gnprice @cyberpwnn I have the same error ![image](https://private-user-images.githubusercontent.com/147256076/358034497-cd641091-8e93-44af-ad19-afd8bf0052d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0OTI4MDMsIm5iZiI6MTcyNDQ5MjUwMywicGF0aCI6Ii8xNDcyNTYwNzYvMzU4MDM0NDk3LWNkNjQxMDkxLThlOTMtNDRhZi1hZDE5LWFmZDhiZjAwNTJkNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNFQwOTQxNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZjA5NWUwMTdlMzE3YjYwMGMzMGU2ZmQ0YzQ0ZmUzZDllMzk1NGQzNWE2ZmQ2YTZlM2RhZTZmNzUxZjIyMWIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.m7CHJyBHqx_s8etu1C_BzqL-5SuuG8jj8JahFpm-_nA)
> 
> ![image](https://private-user-images.githubusercontent.com/147256076/358034638-76a17532-7c2e-44ae-a177-80b296b26291.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0OTI4MDMsIm5iZiI6MTcyNDQ5MjUwMywicGF0aCI6Ii8xNDcyNTYwNzYvMzU4MDM0NjM4LTc2YTE3NTMyLTdjMmUtNDRhZS1hMTc3LTgwYjI5NmIyNjI5MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNFQwOTQxNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZjQ4ZWI5ZjBkOGZlZGVlNjRjMzE3Y2MwMmIyZGI4ZmUwZDE5ZTZiNDcxNjExMDU1MWEzYzhiZDBiN2ZlMTQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5IrqnzmLfWIOTtc5uZAoMS9rq1Z4cCGIUcsWu0kqCx8)

same issues

**Comment by benardelia** [comment]
I got this error after update the flutter to the latest release, simply i upgrade the flutter local notification package to the last release. 

You can do one of these, down grade flutter to the release that working fine or upgrade the package to the last release.

**Comment by theranjithmenon** [comment]
I too got this after updating to latest flutter version. Just update the 'flutter_local_notifications' to latest version.

**Comment by ahmedevcode** [comment]
> I too have similar problem when I run flutter build appbundle. flutter build version 3.24
> 
> Using flutter_local_notifications: ^17.2.1+2 is no problem

thanks this solution slove my issus

**Comment by Mohamed-Essam-Mohamed** [comment]
> I too have similar problem when I run flutter build appbundle. flutter build version 3.24
> 
> Using flutter_local_notifications: ^17.2.1+2 is no problem

thanks this solution solve my issues.

**Comment by nbo001** [comment]
Just update the 'flutter_local_notifications' to latest version solve this issue

**Comment by HabunoGD1809** [comment]
> I too have similar problem when I run flutter build appbundle. flutter build version 3.24
> 
> Using flutter_local_notifications: ^17.2.1+2 is no problem

Thank' you 🥇

**Comment by Levi-Lesches** [comment]
@Anandk02 your error indicates you're on an older version (16.3.3), others are saying you should be able to upgrade to 17.2.1 to fix it. 

If you _need_ version 16.3.3, this could be another approach

**Comment by ervindobri** [comment]
I'm using simple_push_notifications package which uses version 14.0.0 and this error persists.
Flutter SDK version: 3.24.5+

**Comment by ILoveScratch2** [comment]
> I'm using simple_push_notifications package which uses version 14.0.0 and this error persists. Flutter SDK version: 3.24.5+

It is not this plugin
