### ISSUE TITLE
Example Notifications with Actions not working on iOS

### ISSUE THREAD

**Issue by dkbast** [MaikuB/flutter_local_notifications#2332]
**Describe the bug**
No actions are displayed under the notifications of the example app on an iPhone Simulator. This means that the example does not properly showcase the functionality and also cannot be used as a "role model" for implementing actions.

**To Reproduce**
1. clone this repo
2. cd example
3. flutter run (iPhone Simulator)
4. Scroll to "Notifications with actions" choose any
5. No action is displayed

**Expected behavior**
The appropriate action should be displayed

**Comment by MaikuB** [comment]
Have you looked up how actions work on iOS? If not, please do so e.g. https://developer.apple.com/documentation/usernotifications/handling-notifications-and-notification-related-actions. I'm guessing you're not aware that you are required to take additional action to actually see the actions, which is how the platform behaves

**Comment by MaikuB** [comment]
I assume this resolved the issue so will close this. A suggestion that if in future that you find that a response you get has resolved an issue on any repo to close it. This would help save time for maintainers :)
