### ISSUE TITLE
Remove USE_FULL_SCREEN_INTENT

### ISSUE THREAD

**Issue by AKortak** [MaikuB/flutter_local_notifications#2335]
Could you please remove the USE_FULL_SCREEN_INTENT from the android manifest. It should be optional to add this permission. It is also described in the documentation to add it if needed.

**Comment by alicja-ogonowska** [comment]
I think that it needs to be removed from the example code, as it's not there in package's AndroidManifest.xml file itself.
My app uses flutter_local_notifications plugin without any use of full screen intent, yet I got following message from Google Play Store:

> Upcoming restrictions on the USE_FULL_SCREEN_INTENT permission
> 31 May 2024 00:15
> You are receiving this email because you are using the USE_FULL_SCREEN_INTENT permission in your app and there are upcoming platform changes that you should be prepared for. To prevent ad spam and credential phishing, only apps that have calling or alarm functionalities will have the permission enabled by default. Otherwise, you must get user permission to use the USE_FULL_SCREEN_INTENT permission.
> 
> The use of full-screen intent notifications is intended to share high-priority messages that require the user's immediate attention. All developers using this permission are required to complete the Play Console declaration starting from 31 May 2024, to indicate if your app has a permitted core functionality and qualifies for default enablement of the USE_FULL_SCREEN_INTENT permission. Starting on 31 October 2024, all apps that did not complete the declaration, or have not been approved for default enablement, will need to surface a prompt to users to grant permission on new installs on devices running Android 14 or above, and downgrade the app experience gracefully if permission is denied.

The only usage of USE_FULL_SCREEN_INTENT that I can find is the README and example of this package.

**Comment by spdeol20** [comment]
**remove these both permission because google not allowing these permission for notification**
    <uses-permission android:name="android.permission.USE_FULL_SCREEN_INTENT" />
    <uses-permission android:name="android.permission.SCHEDULE_EXACT_ALARM" />

**Comment by spdeol20** [comment]
USE_FULL_SCREEN_INTENT,  SCHEDULE_EXACT_ALARM

**Comment by cristian1980** [comment]
I also got that email fom google but I am using flutter_local_notifications version 15.1.1 .
Someone says here it's fixed in 16.0.0 https://github.com/MaikuB/flutter_local_notifications/issues/1687 .
The latest version is 17.1.2 .
What version are you guys using?

**Comment by spdeol20** [comment]
I haven't tried the latest version yet but I will check it on 17.1.2

**Comment by acousticm** [comment]
Solution 1:
You can force remove the permission by adding this line into AndroidManifest.xml. I have tested this on some Android devices, and it works fine.

```
<uses-permission
    android:name="android.permission.USE_FULL_SCREEN_INTENT"
    tools:node="remove" />

```
Solution 2:
Wait for the library to be updated.

**Comment by MaikuB** [comment]
As mentioned by @spdeol20, the plugin was already done in 16.0. I kindly ask that to check for existing issues and changelog in the future. Note that GitHub supports the ability to be notified of releases when they're published as well so that you can stay on top of changes that could be critical to tie application

**Comment by spdeol20** [comment]
i updated the package to 17.0.1 and it seems resolved in that version

**Comment by deandreamatias** [comment]
Would be nice if exists a template of issues with a form. In these case, should require the version number when create a issue

**Comment by MaikuB** [comment]
@deandreamatias PRs are welcome

**Comment by deandreamatias** [comment]
I created a issue to improve this #2340. Can assign to me if do you want

**Comment by vivekmavani** [comment]
facing same issue in latest version

**Comment by fedeakd** [comment]
I have the same problem

**Comment by MohamedMinhaj-developer** [comment]
> facing the same issue in the latest version I am using flutter_local_notifications: ^17.2.2 I removed USE_FULL_SCREEN_INTENT from the manifest file of my flutter project.
> 
> Google Play Store reject my application

why it's rejected?
