### ISSUE TITLE
zonedSchedule notifications not working in AGP8

### ISSUE THREAD

**Issue by under3415** [MaikuB/flutter_local_notifications#2336]
**Describe the bug**
After upgrading AGP to version 8.4, `zonedSchedule` notifications causes app to crash

**To Reproduce**
Use this minimally altered sample project: [NotificationsSample](https://github.com/under3415/NotificationsSample)

1. Run `Pixel 7 API 33` emulator from `Android Studio Jellyfish 2023.3.1` (don't think the version matters, but just in case)
2. Run the project in VS Code on the above emulator
3. Click `Show plain notification with payload` button. This works OK.
4. Now click `Schedule notification to appear in 5 seconds` button.
5. App crashes with below error:

```
E/AndroidRuntime( 7543): FATAL EXCEPTION: main
E/AndroidRuntime( 7543): Process: com.example.notifications, PID: 7543
E/AndroidRuntime( 7543): java.lang.RuntimeException: Unable to start receiver com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver: java.lang.RuntimeException: Missing type parameter.
E/AndroidRuntime( 7543): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4315)
E/AndroidRuntime( 7543): 	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
E/AndroidRuntime( 7543): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2153)
E/AndroidRuntime( 7543): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 7543): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime( 7543): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime( 7543): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/AndroidRuntime( 7543): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7543): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime( 7543): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/AndroidRuntime( 7543): Caused by: java.lang.RuntimeException: Missing type parameter.
E/AndroidRuntime( 7543): 	at com.google.gson.reflect.TypeToken.getSuperclassTypeParameter(TypeToken.java:84)
E/AndroidRuntime( 7543): 	at com.google.gson.reflect.TypeToken.<init>(TypeToken.java:62)
E/AndroidRuntime( 7543): 	at com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver$1.<init>(ScheduledNotificationReceiver.java:58)
E/AndroidRuntime( 7543): 	at com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver.onReceive(ScheduledNotificationReceiver.java:58)
E/AndroidRuntime( 7543): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4306)
```

Interestingly, the app will not start again until the cache/storage is cleared in the OS!?

If you downgrade AGP version from `8.4.0` to `7.4.2` in `settings.gradle` file, the scheduled notification works fine, this only happens in AGP 8.

**Expected behavior**
Notification is displayed in AGP 8

**Sample code to reproduce the problem**
[NotificationsSample](https://github.com/under3415/NotificationsSample)

**Comment by under3415** [comment]
This is related to R8. Adding below option to `gradle.properties` fixed the issue
```
android.enableR8.fullMode = false
```

Some users suggest that adding these options to `proguard-rules.pro` fixes the issue without disabling R* full mode, but this does not fix the issue
```
-keep class org.xmlpull.** { *; }
# Retain generic signatures of TypeToken and its subclasses with R8 version 3.0 and higher.
-keep,allowobfuscation,allowshrinking class com.google.gson.reflect.TypeToken
-keep,allowobfuscation,allowshrinking class * extends com.google.gson.reflect.TypeToken

```

Can someone advise what is the best thing to do here?

**Comment by MaikuB** [comment]
Can't run your app as I would need to change the version of Flutter, which I can't do right now. I did however try to update the example to AGP8 and didn't run into issues.  Looking at the link you provided though, you haven't completed the [release build configuration](build/app/outputs/flutter-apk/app-release.apk ) that was mentioned in the readme.  What you added was only a part of the rules needed for GSON and were ** additions** to other rules that were needed

**Comment by under3415** [comment]
Hi,
Thanks for you reply. 

I am not sure which part of the `release build configuration` was missed. I read it again carefully, and I cannot see  anything that applies to me that was missed except for the more extensive R8 GSON rules . I have added that but makes no difference. 

````
##---------------Begin: proguard configuration for Gson  ----------
# Gson uses generic type information stored in a class file when working with fields. Proguard
# removes such information by default, so configure it to keep all of it.
-keepattributes Signature

# For using GSON @Expose annotation
-keepattributes *Annotation*

# Gson specific classes
-dontwarn sun.misc.**
#-keep class com.google.gson.stream.** { *; }

# Application classes that will be serialized/deserialized over Gson
-keep class com.google.gson.examples.android.model.** { <fields>; }

# Prevent proguard from stripping interface information from TypeAdapter, TypeAdapterFactory,
# JsonSerializer, JsonDeserializer instances (so they can be used in @JsonAdapter)
-keep class * extends com.google.gson.TypeAdapter
-keep class * implements com.google.gson.TypeAdapterFactory
-keep class * implements com.google.gson.JsonSerializer
-keep class * implements com.google.gson.JsonDeserializer

# Prevent R8 from leaving Data object members always null
-keepclassmembers,allowobfuscation class * {
  @com.google.gson.annotations.SerializedName <fields>;
}

# Retain generic signatures of TypeToken and its subclasses with R8 version 3.0 and higher.
-keep,allowobfuscation,allowshrinking class com.google.gson.reflect.TypeToken
-keep,allowobfuscation,allowshrinking class * extends com.google.gson.reflect.TypeToken

##---------------End: proguard configuration for Gson  ----------
````

Turning off R8 full mode fixes the issue, but is a bit too radical a solution. This is not necessary in AGP7.
`android.enableR8.fullMode = false`

Btw, in the readme there are links to these two locations which, as far as I can see, contain identical R8 rules:
```
https://github.com/google/gson/blob/main/examples/android-proguard-example/proguard.cfg

https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/example/android/app/proguard-rules.pro
```

**Comment by MaikuB** [comment]
The release build configuration includes updating the Proguard rules and your app was missing good number of them before.

I updated my Flutter SDK and still can't build your app on either the stable (3.22.2) or master channel (build 3.5.0-288.0.dev). I tried to make tweaks to make it build but then it wouldn't start properly and I don't have the capacity to find out what exactly is wrong. From what I can see, the build.gradle structure of your app looks out of date compared to an app using the `flutter create` command on either version. This seems strange when your app required a higher Dart SDK, which normally requires a higher Flutter SDK too.

Can I ask that you either fork the repo and reproduce this via the example app or provide a link that built based on the newly created app from 3.22.2? For what it's worth, my own preference is for it to forked from this repo where you can update the example app if needed. I wonder though if the issue is experiencing is to do with how your sample was created given the issues I've experienced

**Comment by under3415** [comment]
I see what the problem was, I keep some settings in `local.properties` file which is ignored by git. This is why you were getting a build error. I have fixed that. If you clone the project now you should be able to build it and run it as is. 

`git clone https://github.com/under3415/NotificationsSample.git`

By the way, I followed these instructions on the latest [plugin management approach](https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply), this is why my Gradle settings look a bit different. They are not outdated, they are the latest and recommended.

**Comment by MaikuB** [comment]
> By the way, I followed these instructions on the latest [plugin management approach](https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply), this is why my Gradle settings look a bit different. They are not outdated, they are the latest and recommended.

I was referring to the deprecated property names (reference: https://docs.flutter.dev/deployment/android#properties-to-adjust-in-build-gradle). Having seen that, I was conscious there could be other things out of date so flagged it

I don't believe your issue is to do with full mode though as I've been able to use the example app on AGP 8.4.2 and saw another person reply to you at https://github.com/MaikuB/flutter_local_notifications/issues/2223#issuecomment-1971805349. Presumably they would've confirmed this too. The example app in the repo works without updating to AGP 8.x with full mode enabled too.

From what I can tell, the issue seems to be with the version of GSON used. I don't know the cause and haven't had a chance to look more into it but it looks like if you were to specify in your app that it depends on the latest version of GSON per their [docs](https://github.com/google/gson) then the issue is resolved. I will be bumping the dependency in the plugin in the future and suggest you do it in your app for now. It's not something I'll do immediately as the changeling for the recent version says GSON now requires Android API 21+

**Comment by under3415** [comment]
You were write, adding below line to `app\build.gradle` fixes the problem with R8 full mode enabled.
    
```
    implementation 'com.google.code.gson:gson:2.11.0'
```

I am not sure why my project requires this and the example does not.

**Comment by MaikuB** [comment]
@under3415 I was going to raise a PR on this to bump GSON where I could reproduce it fixes the issue in your app. However, given I couldn't reproduce this on AGP8 with the example app, I dug further and noticed there's a difference with how you have configured your app.

The key parts in your app's build.gradle file is that doesn't have it set as follows

```
    compileOptions {
        coreLibraryDesugaringEnabled = true
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
         
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_1_8
    }
```

I'm not sure why you changed it for your app but these are the settings that match what is documented by Google when it comes to using Java 8 APIs. It also matches what is generated from the Flutter 3.24 SDK when creating a new app

**Comment by under3415** [comment]
I was following [AGP documentation](https://developer.android.com/build/releases/gradle-plugin)
![image](https://github.com/user-attachments/assets/bf89e921-ed47-43d6-a649-3a17e32fa4bc)

JDK8 was released in 2014 and public support ended in 2019. 

I am not sure why Flutter uses such outdated software by default.

**Comment by under3415** [comment]
Btw, the new Android Studio Ladybug has moved from java 17 to 21. I am having to install an older version for my flutter builds...

**Comment by MaikuB** [comment]
> I was following [AGP documentation](https://developer.android.com/build/releases/gradle-plugin)

I don't see a part on there that says to have the toolchain specified to be 17 though. Are you able to point me to this? Though on this, the most important thing I've seen you have noticed is that the plugin needs to use desugaring as I saw you have links to https://developer.android.com/studio/write/java8-support.html. If you check that link there though that is where the snippet I took comes from so is official guidance from Google. From my understanding, this helps declare the an app is using Java 8 features, which the plugin needed to use to make use of APIs around timezones whilst supporting older Android versions. This allows avoids having to bump the minimum Android SDK requirements. Presumably, what you had in declaring the usage of Java 17 APIs/language features instead has caused buggy behaviour as the docs would indicate desugaring, including the related libraries were built around Java 8 not 17.  Based on what is described [here](https://developer.android.com/build/jdks#source-compat), it also says developers should be declaring either the toolchain **or** source compatibility. I'm not an expert on Java but this may have also contributed to the issue you originally experienced.

> Btw, the new Android Studio Ladybug has moved from java 17 to 21. I am having to install an older version for my flutter builds...

Curious what issues you're facing but Flutter itself has had issues when a new version of Android Studio or XCode is released

**Comment by under3415** [comment]
This is how I went down this rabbit hole. I have been working on this project for a few years using VS Code as my IDE. I could see information on how to update pub packages and Android SDK version, but no info on how to update a number of other tools:

- Gradle
- AGP
- NDK
- JDK + associated settings
- Kotlin
- Build tools

So I looked at what documentation I could find so I could update these tools. Seems I misinterpreted some for the Java instructions!

Anyway, using a new Flutter project created using Android Studio Ladybug these seem to be the default versions in 2024:

- Gradle: 8.3 (latest 8.10.2)
- AGP: 8.1.4 (latest 8.7.0)
- JDK: 21.0.3+-12282718-b509.11 (latest for 21 from Oracle: 21.0.4+8-LTS-274)
- Kotlin: 2.0.20 (latest =)

No idea where the defaults are stored any more, cannot find it in the docs, used to be `flutter.gradle`, I am using these values:
- NDK: 27.1.12297006
- Bulild Tools: 34.0.0

I have reverted java related settings to these values as per vanilla new project (I thought these should match JDK, but obviously not):
```
 compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_1_8
    }
```

With aligning my project with vanilla Ladybug project I am now getting about dozen of these warnings on build (plus a couple of deprecation warnings from `firebase auth` that they don't think should be on their backlog):
```
warning: [options] source value 8 is obsolete and will be removed in a future release
warning: [options] target value 8 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
3 warnings
```

**Comment by MaikuB** [comment]
> So I looked at what documentation I could find so I could update these tools. Seems I misinterpreted some for the Java instructions!

Gotcha and all good. The Android ecosystem is pretty complicated

> With aligning my project with vanilla Ladybug project I am now getting about dozen of these warnings on build (plus a couple of deprecation warnings from firebase auth that they don't think should be on their backlog):

I believe the deprecation warnings are from Gradle. I'm not sure if they are really planning to remove support it given desugaring focuses on Java 8. Perhaps the view is that by the time it gets removed, the market share for the older Android devices would become significantly smaller
