### ISSUE TITLE
Play Store Console SCHEDULE_EXACT_ALARM permission warning... ignorable?

### ISSUE THREAD

**Issue by MichaelM-ZGuy** [MaikuB/flutter_local_notifications#2339]
I'm getting this warning in the Play Store Console:

> Your app schedules exact alarms without checking whether the SCHEDULE_EXACT_ALARM permission has been granted. This is causing your app to crash for users on Android 14 because the permission is no longer granted by default.

The thing is, the app doesn't schedule any alarms.

The app does use `flutter_local_notifications`, which _can_ schedule alarms, but we don't use it for that. We use: 

- `FlutterLocalNotificationsPlugin.initialize()`
- `FlutterLocalNotificationsPlugin.createNotificationChannel()`
- `FlutterLocalNotificationsPlugin.requestNotificationsPermission()`
- `FlutterLocalNotificationsPlugin.show()`

I don't think any of those methods go anywhere near any SCHEDULE_EXACT_ALARM code, but before I write it off as an erroneous warning from Google, can someone please confirm which `flutter_local_notifications` methods/functionality use SCHEDULE_EXACT_ALARM permissions, even tangentially?

PS. Crashlytics is not reporting any scheduled alarms-related errors.

**Comment by jxstxn1** [comment]
Hey @MichaelM-ZGuy did you set the `SCHEDULE_EXACT_ALARM` in your `AndroidManifest.xml`?
This should be the reason you get the warning from the Play Store.

**Comment by arturoespinosag** [comment]
I got the same message from Google Play, I can confirm I didn't add that permission, maybe it could be the permission added in the example in flutter_local_notifications  AndroidManifest file?

**Comment by MichaelM-ZGuy** [comment]
> Hey @MichaelM-ZGuy did you set the `SCHEDULE_EXACT_ALARM` in your `AndroidManifest.xml`? This should be the reason you get the warning from the Play Store.

@jxstxn1 No, `SCHEDULE_EXACT_ALARM` is not in our `AndroidManifest.xml`.

My understanding, inferred from the wording of the warning, is that Google thinks that our app scheduling an alarm (`FlutterLocalNotificationsPlugin.zonedSchedule()`) without first asking the user for permission (`FlutterLocalNotificationsPlugin.resolvePlatformSpecificImplementation<AndroidFlutterLocalNotificationsPlugin>()
 ?.requestExactAlarmsPermission()`) .
 
 I _think_ the warning would go away if I added `FlutterLocalNotificationsPlugin.resolvePlatformSpecificImplementation<AndroidFlutterLocalNotificationsPlugin>()
 ?.requestExactAlarmsPermission()`, but that would be bad UX: it would make the user think the app is setting alarms when it isn't.

**Comment by MaikuB** [comment]
I suspect you were using an older version of the plugin before 16.0.0 where the permission was requested by the plugin. Since 16.0.0, it was up to developers to request/specify the permissions needed. I would guess that the newer versions you're working already made the appropriate changes when it comes to using a newer version of this plugin etc so is why you don't see the issue on the testing tracks

**Comment by MichaelM-ZGuy** [comment]
@MaikuB @jxstxn1 

> My current thinking is that when I deploy a newer version to production, the warning will disappear.

I just released the updated version to production and Google Play Console is no longer showing the warning. Thanks for your help; closing this issue now.
