### ISSUE TITLE
Payload null when app is terminated

### ISSUE THREAD

**Issue by matteoberla** [MaikuB/flutter_local_notifications#2343]
**Describe the bug**
Payload when the app is terminated is null, the notification opens the app correcly but without the paylod is impossible to route the user to the correct page.

**To Reproduce**
-Foreground app
-Receiving a notification
-Close the app
-Tap on the notification
-App opens but the payload is null (currently handled with `FirebaseMessaging.instance.getInitialMessage()`)

**Expected behavior**
As when the app is in foreground or background, when pressing the notification the payload has the correct value and is correctly passed to the callback.

**Sample code to reproduce the problem**
code that i'm using with firebase cloud messaging
```
import 'dart:convert';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';

Future handleBackgroundMessage(RemoteMessage message) async {
  print("Title: ${message.notification?.title}");
  print("Body: ${message.notification?.body}");
  print("Payload: ${message.data}");
}

class FirebaseApi {
  final _firebaseMessaging = FirebaseMessaging.instance;

  final _androidChannel = const AndroidNotificationChannel(
    'high_importance_channel',
    'High Importance Notifications',
    description: "This channel is used for important notifications",
    importance: Importance.defaultImportance,
  );

  final _localNotification = FlutterLocalNotificationsPlugin();

  void handleMessage(RemoteMessage? message) {
    if (message == null) return;
    print("Title: ${message.notification?.title}");
    print("Body: ${message.notification?.body}");
    print("Payload: ${message.data}");

    //action after the user tapped on the notification
  }

  Future initLocalNotifications() async {
    const iOS = DarwinInitializationSettings();
    const android = AndroidInitializationSettings("@drawable/ic_launcher");
    const settings = InitializationSettings(android: android, iOS: iOS);

    await _localNotification.initialize(settings,
        onDidReceiveNotificationResponse: (response) {
      final message = RemoteMessage.fromMap(jsonDecode(response.payload!));
      handleMessage(message);
    });

    final platform = _localNotification.resolvePlatformSpecificImplementation<
        AndroidFlutterLocalNotificationsPlugin>();
    await platform?.createNotificationChannel(_androidChannel);
  }

  Future initPushNotifications() async {
    await FirebaseMessaging.instance
        .setForegroundNotificationPresentationOptions(
            alert: true, badge: true, sound: true);

    FirebaseMessaging.instance.getInitialMessage().then(handleMessage);
    FirebaseMessaging.onMessageOpenedApp.listen(handleMessage);
    FirebaseMessaging.onBackgroundMessage(handleBackgroundMessage);
    FirebaseMessaging.onMessage.listen(
      (message) {
        final notification = message.notification;

        _localNotification.show(
          notification.hashCode,
          notification?.title ?? "Default title",
          notification?.body ?? "Default body",
          NotificationDetails(
            android: AndroidNotificationDetails(
                _androidChannel.id, _androidChannel.name,
                channelDescription: _androidChannel.description,
                icon: "@drawable/ic_launcher"),
          ),
          payload: jsonEncode(
            message.toMap(),
          ),
        );
      },
    );
  }

  Future<String?> initNotification() async {
    await _firebaseMessaging.requestPermission();
    String? fcmToken = await _firebaseMessaging.getToken();
    //log
    print(fcmToken);
    //start notifications
    initPushNotifications();
    initLocalNotifications();
    return fcmToken;
  }
}
```

**Comment by MaikuB** [comment]
The code you say you have issue with is to do with the FCM plugin so unless you can properly give an explanation on how the issue you have is with this plugin with a link to a repository with a minimal app that can reproduce the issue then will be closing this. This should demonstrate the issue using only this plugin as well. Based on what you have shown so far, it would seem to indicate to me that you are likely confused between push/remote notifications and local notifications

**Comment by matteoberla** [comment]
i'm not confused, just this piece of code was needed in order to make it works as expected.

```
final appLaunchDetails =
        await _localNotification.getNotificationAppLaunchDetails();

    if (appLaunchDetails != null && appLaunchDetails.didNotificationLaunchApp) {
      if (appLaunchDetails.notificationResponse != null) {
        final message = RemoteMessage.fromMap(
            jsonDecode(appLaunchDetails.notificationResponse!.payload!));
        handleInitialMessage(message);
      }
    }
```

flutter_local_notification seems not to pass to firebase initialMessage the payload once the notification is pressed with terminated state app.
Try to be a little nicer with others and not to judge, Thank you.

**Comment by MaikuB** [comment]
> Try to be a little nicer with others and please don't judge, Thank you.

It wasn't a judgement but a guess (note: which is why I used the word "likely") as to the actual cause of the problem that goes beyond code but rather on understanding or misunderstanding (i.e. a knowledge gap. Based on the what you've shared you were only using the method from the plugin FCM to process a notification when the app is in a terminated. With your last reply, this confirms that you were expecting FCM, which is for push notifications, to also handle local notifications. However, a local notification isn't a push notification and vice versa. Their own API docs (e.g. https://pub.dev/documentation/firebase_messaging/latest/firebase_messaging/FirebaseMessaging/getInitialMessage.html) state that they only handle push notifications as represented by the `RemoteMessage` class
