### ISSUE TITLE
Problems with scheduled daily notification on Android

### ISSUE THREAD

**Issue by kate-kate** [MaikuB/flutter_local_notifications#236]
Hello @MaikuB 
First of all thank you for your package, it is a quite convenient to work with.
I created an app with daily scheduled notifications and tested it in iOS and it worked well, but then I debugged it on Android simulator and notifications didn't appear at all.
Here is my [AndroidManifest](https://github.com/kate-kate/lucid-dreams/blob/master/android/app/src/main/AndroidManifest.xml) file, you can double-check that I added <receiver> and <uses-permissions> tags that are mentioned in instruction for Android notifications scheduling. 
This seems quite strange, just maybe you can advice me how can I debug this, cause there are no errors, nothing, notifications are just not raising

**Comment by kate-kate** [comment]
UPD: sorry, the problem was on emulator. If someone will face same problem - here is the tip: by default emulator never turn "sleep mode", and notifications will appear only as a small square on the left top corner of device

**Comment by MaikuB** [comment]
Thanks for your kind words. Regarding the behaviour you saw, I'd suggest you check the Android docs around setting the priority and importance levels for notifications e.g. [here](https://developer.android.com/guide/topics/ui/notifiers/notifications#importance)
