### ISSUE TITLE
Throwing error - Android

### ISSUE THREAD

**Issue by admincode1** [MaikuB/flutter_local_notifications#2365]
E/MethodChannel#dexterous.com/flutter/local_notifications(26031): Failed to handle method call
E/MethodChannel#dexterous.com/flutter/local_notifications(26031): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
E/MethodChannel#dexterous.com/flutter/local_notifications(26031): 	at android.content.ComponentName.<init>(ComponentName.java:132)
E/MethodChannel#dexterous.com/flutter/local_notifications(26031): 	at android.content.Intent.<init>(Intent.java:8269)
E/MethodChannel#dexterous.com/flutter/local_notifications(26031): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.zonedScheduleNotification(FlutterLocalNotificationsPlugin.java:577)
E/MethodChannel#dexterous.com/flutter/local_notifications(26031): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.zonedSchedule(FlutterLocalNotificationsPlugin.java:1610)
E/MethodChannel#dexterous.com/flutter/local_notifications(26031): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(FlutterLocalNotificationsPlugin.java:1431)
E/MethodChannel#dexterous.com/flutter/local_notifications(26031): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/MethodChannel#dexterous.com/flutter/local_notifications(26031): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/MethodChannel#dexterous.com/flutter/local_notifications(26031): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#dexterous.com/flutter/local_notifications(26031): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#dexterous.com/flutter/local_notifications(26031): 	at android.os.Handler.handleCallback(Handler.java:958)
E/MethodChannel#dexterous.com/flutter/local_notifications(26031): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#dexterous.com/flutter/local_notifications(26031): 	at android.os.Looper.loopOnce(Looper.java:230)
E/MethodChannel#dexterous.com/flutter/local_notifications(26031): 	at android.os.Looper.loop(Looper.java:319)
E/MethodChannel#dexterous.com/flutter/local_notifications(26031): 	at android.app.ActivityThread.main(ActivityThread.java:8919)
E/MethodChannel#dexterous.com/flutter/local_notifications(26031): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#dexterous.com/flutter/local_notifications(26031): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
E/MethodChannel#dexterous.com/flutter/local_notifications(26031): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

**Comment by MaikuB** [comment]
Please provide a link to a repository hosting a minimal app that can reproduce the issue. If it helps, you can start by forking the repository to tweak the example app there so there's a reproducible case of the issue

**Comment by admincode1** [comment]
In my case this related to workmanager plugin.
Closing since this is not Flutter Local Notifications plugin.
Thanks @MaikuB
