### ISSUE TITLE
Call Style Ongoing Notification - Android

### ISSUE THREAD

**Issue by swarupbc** [MaikuB/flutter_local_notifications#2367]
**Describe the bug**
Call Style Ongoing Notification (Android only)

I want to achieve non-dismissible notifications for Ongoing Call like Whatsapp voice call with this plugin.
https://developer.android.com/develop/ui/views/notifications/call-style#ongoing_call
https://developer.android.com/about/versions/14/behavior-changes-all#non-dismissable-notifications

**To Reproduce**
If I use ongoing true, user will be dismiss the notification easily.

**Expected behavior**
I want the notification to be sticky as it's a ongoing voice call

**Sample code to reproduce the problem**
Basic android configuration with ongoing true.

**Comment by MaikuB** [comment]
Please make sure you check the docs and example app as this is already supported

**Comment by swarupbc** [comment]
Hi @MaikuB, I’ve already explained what I want to achieve, user can easily swipe and dismiss the ongoing notification in android 14, I want call style notification, I’ve attached the links to official documentation with the  issue details.

**Comment by MaikuB** [comment]
As mentioned in the update to my previous response, you would need to submit a PR for that functionality yourself
