### ISSUE TITLE
All notifications are received at once while in doze mode

### ISSUE THREAD

**Issue by berkaycelebi** [MaikuB/flutter_local_notifications#2369]
In our app, we send notifications every 3 hours from 08:00 to 22:00 (e.g., water reminder notifications). We use zonedSchedule to achieve this.

However, many users report receiving most notifications all at once. After investigating, we found that when the device is in idle mode (Doze mode), the alarm manager doesn't work as expected, as described in the [Android documentation](https://developer.android.com/training/monitoring-device-state/doze-standby#understand_doze).

Our notifications don't need to be sent at an exact time, but we expect them to be received within a few hours. In reality, users sometimes don't receive notifications for a whole day and then receive all of them at once. (mostly in android 13+)

Here is our working code:

```dart
const androidDetails = AndroidNotificationDetails(
  'Workout Daily Notification',
  'Workout Daily Notification',
  channelDescription: 'Workout Daily Notification',
  importance: Importance.max,
  enableVibration: true,
  icon: 'ic_stat_buttocks1',
  priority: Priority.high,
  styleInformation: BigTextStyleInformation(''),
);

_generalNotificationDetails = const NotificationDetails(
  android: androidDetails,
  iOS: iosDetails,
);

await _flutterLocalNotification.zonedSchedule(
  123,
  "anyString",
  "otherString",
  tz.TZDateTime.from(scheduledDate, tz.local),
  _generalNotificationDetails,
  uiLocalNotificationDateInterpretation: UILocalNotificationDateInterpretation.absoluteTime,
  matchDateTimeComponents: DateTimeComponents.dateAndTime,
  androidScheduleMode: AndroidScheduleMode.inexact,
  payload: 'id:${date.millisecondsSinceEpoch} scheduledDate:$scheduledDate',
);
```

Is it possible to set up notifications to be sent at inexact times and avoid receiving them all at once? Or what should we do to resolve the described issue?

**Comment by MaikuB** [comment]
Have you checked the other values for the `AndroidSchedule` enum? My understanding is [`AndroidScheduleMode.inexactAllowWhileIdle`](https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/AndroidScheduleMode.html#inexactAllowWhileIdle) would've been what you're after

**Comment by berkaycelebi** [comment]
Thanks. `inexactAllowWhileIdle`  solved the problem.

 We focused on only inexact and exact and could not see other options. Thanks you for your time. I am closing this issue.

**Comment by marcellocamara** [comment]
@berkaycelebi Did you test it while app is in background?

I noticed that when the app is in background (app terminated), the notification scheduled is ok.
But, when the app is **terminated** (app is not minimized), don't show the notification scheduled, using `inexactAllowWhileIdle`.

**Comment by marcellocamara** [comment]
@berkaycelebi Did you test it while app is in background?

I noticed that when the app is in background (app terminated), the notification scheduled is ok.
But, when the app is **in background and not terminated** (app is minimized), don't show the notification scheduled, using `inexactAllowWhileIdle`.

**Comment by kamranbekirovyz** [comment]
In my app, where users should receive a push notification at 06:10 in the morning about the starting of prayer, they receive it exactly 4 hours later at 10:10.

I've tried setting `androidScheduleMode: AndroidScheduleMode.exactAllowWhileIdle` and `androidScheduleMode: AndroidScheduleMode.alarmClock`, yet, none of them seem to resolve it.
