### ISSUE TITLE
Is there any way to add Lock Screen notifications with this library?

### ISSUE THREAD

**Issue by Jumpbotron** [MaikuB/flutter_local_notifications#237]
I ask a way to do it on StackOverflow and they told me to try with this library, Thanks anyway what i've done so far with it is great!

**Comment by MaikuB** [comment]
I'm not sure specifically what you're after here or feel is missing but there's an example app in this repo. I'd suggest you clone it and run it to see if it meets your needs. In general, notifications that haven't been read will show up on the lock screen, you can't specifically say you want notifications to appear on your lock screen if that's what you meant
