### ISSUE TITLE
Notification Display Callback Support

### ISSUE THREAD

**Issue by mehmetpeker** [MaikuB/flutter_local_notifications#2382]
Hello,

I need to trigger a callback when a notification is displayed on the phone using the flutter_local_notifications package. Currently, the callback is only triggered when the notification is clicked, but in my scenario, I need to start a process as soon as the notification is displayed. Is it possible to support this functionality? If not, is there a roadmap or suggestion for adding this feature?

Thank you.

**Comment by MaikuB** [comment]
There's already an open [issue](https://github.com/MaikuB/flutter_local_notifications/issues/1699) on this one though you'll need to ignore that the title is specific to scheduled notifications and on Android. No plans to work on this one myself so if you're interested in the functionality, please submit PR. Will close this as there's an existing issue used for tracking this
