### ISSUE TITLE
In release mode. TypeToken must be created with a type argument

### ISSUE THREAD

**Issue by Unevenn** [MaikuB/flutter_local_notifications#2392]
I am getting this error only on release mode. flutter_local_notifications version is 17.2.2.

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, TypeToken must be created with a type argument: new TypeToken<...>() {}; When using code shrinkers (ProGuard, R8, ...) make sure that generic signatures are preserved., null, java.lang.IllegalStateException: TypeToken must be created with a type argument: new TypeToken<...>() {}; When using code shrinkers (ProGuard, R8, ...) make sure that generic signatures are preserved.
E/flutter ( 6610):      at ab.a.b(Unknown Source:40)
E/flutter ( 6610):      at ab.a.<init>(SourceFile:1)
E/flutter ( 6610):      at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin$1.<init>(Unknown Source:0)
E/flutter ( 6610):      at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.loadScheduledNotifications(Unknown Source:25)
E/flutter ( 6610):      at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.pendingNotificationRequests(Unknown Source:2)
E/flutter ( 6610):      at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(Unknown Source:398)
E/flutter ( 6610):      at lf.k$a.a(Unknown Source:17)
E/flutter ( 6610):      at cf.c.l(Unknown Source:18)
E/flutter ( 6610):      at cf.c.m(Unknown Source:41)
E/flutter ( 6610):      at cf.c.i(Unknown Source:0)
E/flutter ( 6610):      at cf.b.run(Unknown Source:12)
E/flutter ( 6610):      at android.os.Handler.handleCallback(Handler.java:938)
E/flutter ( 6610):      at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter ( 6610):      at android.os.Looper.loopOnce(Looper.java:210)
E/flutter ( 6610):      at android.os.Looper.loop(Looper.java:299)
E/flutter ( 6610):      at android.app.ActivityThread.main(ActivityThread.java:8250)
E/flutter ( 6610):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 6610):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
E/flutter ( 6610):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
E/flutter ( 6610): )
E/flutter ( 6610): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651)
E/flutter ( 6610): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334)
E/flutter ( 6610): <asynchronous suspension>
E/flutter ( 6610): #2      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:520)
E/flutter ( 6610): <asynchronous suspension>
E/flutter ( 6610): #3      MethodChannelFlutterLocalNotificationsPlugin.pendingNotificationRequests (package:flutter_local_notifications/src/platform_flutter_local_notifications.dart:78)
E/flutter ( 6610): <asynchronous suspension>

**Comment by Unevenn** [comment]
I downgraded gradle version from 8.0.2 to 7.3.1 and it fixed.

**Comment by ChrisAPQ** [comment]
Alternatively you could flick R8 into compatibility mode. This is the default before Gradle 8.

You can do this by adding `android.enableR8.fullMode=false` to your `gradle.properties` file.
