### ISSUE TITLE
Show image in notification without expanding 

### ISSUE THREAD

**Issue by n2ng-dev** [MaikuB/flutter_local_notifications#2394]
Can show image as banner in without expanding notifications?
Like this

Thankyou

 ![Screenshot_20240827_005308_QuranBest Indonesia.jpg](https://github.com/user-attachments/assets/ffa30b6c-afc7-4b28-82f1-a9210961f429)

**Comment by MaikuB** [comment]
You'll need to do research on the native notification APIs and capabilities on if and how this could be done. The plugin is meant to expose some of the native APIs so doing this research is a prerequisite. It also benefits you in the long run as knowing what each platform supports would inform you of what is feasible irrespective of if you are using frameworks like Flutter
