### ISSUE TITLE
Grouped notifications without summary notification 

### ISSUE THREAD

**Issue by richie-south** [MaikuB/flutter_local_notifications#240]
I cant for the life of me create grouped notifications that don't use the summary notification required for older devices. `create the summary notification required for older devices that pre-date Android 7.0 (API level 24)` Could you please help me with an example of grouped notification without the summary? 🙏😃

**Comment by MaikuB** [comment]
you actually need the summary there. it's more to do with how older devices will show it. I may need to update the notes there since there was a similar issue reported [here](https://github.com/MaikuB/flutter_local_notifications/issues/226)

**Comment by MaikuB** [comment]
I've updated the comments in the example to make it clearer that it's always required in #294 so will close this now
