### ISSUE TITLE
Scheduled Notifications on iOS

### ISSUE THREAD

**Issue by mdmota** [MaikuB/flutter_local_notifications#2401]
Plugin 17.2.2
Flutter 3.22.0

I recently noticed that my app is not generating scheduled notifications on iOS. Are there any recent changes?
What settings do I need to follow?
Has Apple introduced any new policies?

**Comment by MaikuB** [comment]
Not aware of changes on this. If you believe there's a problem then it would be best to provide a link to a repo hosting a minimal app that can reproduce the problem. This allows seeing if there's a legitimate issue or if there was a configuration problem

**Comment by MaikuB** [comment]
Hmm actually, do you know how many notifications your app was scheduling? Asking as there's been a couple of issues reported by devs and common theme is when they have too many scheduled. Apple is supposed to keep 64 of them and they have had a history of undocumented behaviour before e.g. http://ileyf.cn.openradar.appspot.com/38065340
