### ISSUE TITLE
Get Notification status on iOS

### ISSUE THREAD

**Issue by gridfriday** [MaikuB/flutter_local_notifications#241]
Is it possible to get the notification status on iOS?

I'd like to check this status before scheduling a notification. I'd like to present a pop up if the status is undetermined or disallowed.

This would also eliminate the tersely worded system-supplied "allow notification" pop up as soon as FlutterLocalNotificationsPlugin.initialize() is run and let me show a more subtle pop up notice first.

**Comment by MaikuB** [comment]
Sounds like you're asking about if permissions have been granted for notifications to be displayed not about the status of the notifications themselves. If so, similar question has been asked here https://github.com/MaikuB/flutter_local_notifications/issues/189

There's a plugin you could use to check the status if needed or you could make use of platform channels to write that part yourself
