### ISSUE TITLE
Problem with access amount of notifications

### ISSUE THREAD

**Issue by devanshu00000** [MaikuB/flutter_local_notifications#2411]
Hello,

I tried to schedule 400 notifications in one go but not getting any notification, whereas if I schedule less then 70 notifications it's working fine not sure what to do.

Just to explain, what I am trying to do is, I am building a local notification service where user can define number of notifications per day, Start time, End time and Repeating Weeks. Here I tried to use the DateTimeComponents.dayOfWeekAndTime logic where we are going to set the notification for week with time and it's going to repeat it for upcoming weeks. But the problem here is that we need different notification body with every notification. I was not able to find any solution to that problem so we implemented the logic where we are going to generate notification for 6 months in advance but as we found it's not possible to schedule notifications above 500. Now that we are generating notifications below 500 we are getting this issue. 

Not sure what to do. Please help!

**Comment by MaikuB** [comment]
I believe you are running into OS level restrictions. This wouldn't be a plugin related issue and would then mean you need to researching a different way to solve your problem
