### ISSUE TITLE
Slow performance when batch scheduling 

### ISSUE THREAD

**Issue by LiGangwei** [MaikuB/flutter_local_notifications#242]
Hi, I have a need to batch schedule somewhere around 50 scheduled notifications quite often, and it takes a bit north of a second to do so right now, can we please get a mass scheduling API function?

**Comment by MaikuB** [comment]
None of the native APIs provide the functionality to batch schedule notifications and as such won't be something I'm looking to add. If you're scheduling that many that perhaps you should be re-evaluating if the use of local notifications is appropriate and look at an alternative using push notifications. If you schedule that many then your app could end up hitting the OS limits
