### ISSUE TITLE
Push notification not working when app is Killed permanently?? Can you please suggest me about this, its stopped working in my live app???

### ISSUE THREAD

**Issue by DeepakYiron** [MaikuB/flutter_local_notifications#2424]
(DEBUG MODE) It is working fine in **foreground** and **background** as well, 
 it was working even when the app is killed some day back in my project.
  But suddenly it stopped working in only when app is killed,  
  
  I AM using V1 api of firebase 
  
  https://fcm.googleapis.com/v1/projects/project_id/messages:send
  
  
  Can you please look over this as i need to sort it out as soon as possible...I will be thankful to you for this.

**Comment by Levi-Lesches** [comment]
(It might be helpful to start closing the issues about FCM to get the issue count down a bit)

**Comment by DeepakYiron** [comment]
Thanks for update , I got it and my issue has been resolved,
Thank you so much for your support.

You can close this issue.
________________________________

**Comment by MaikuB** [comment]
@Levi-Lesches I will but left it open to give those who raise issues some time to respond. I know there are other issues in general I can go back and close but requires time to do so. I had considered a bot but seems rather "cold". I might revisit that though. Anyway OP has replied so will close this one
