### ISSUE TITLE
getActiveNotifications function does not work for notifications that are created later with the ongoing property set to true.

### ISSUE THREAD

**Issue by muhammetikbalkeklik** [MaikuB/flutter_local_notifications#2426]
Handling Multiple Active Zoned Notifications

Description:
We are using the flutter_local_notifications package to schedule multiple notifications. Among these, some notifications are scheduled as zonedNotification with the ongoing property set to true. However, there is an unexpected behavior occurring: when the time for the notifications arrives, sometimes two notifications remain active simultaneously. This is not the desired outcome.

Ideally, when the user interacts with (taps on) one of these notifications, the issue should resolve itself by closing other active notifications. However, the following problem occurs:

The function:

var activeNotificationList = await flutterLocalNotificationsPlugin.getActiveNotifications();
does not correctly detect a zonedScheduleNotification that becomes active after it is triggered. In fact, it sometimes returns 0, indicating no active notifications even when there are ongoing notifications. This means that the newly active notifications are not properly identified and managed, leading to multiple ongoing notifications being displayed at the same time.

my example code : 

   var aktifNotificationList =
        await flutterLocalNotificationsPlugin.getActiveNotifications();
    if (aktifNotificationList.length !=1) {
      for (var notification in aktifNotificationList) {
        if (notification.id! >= 15000) {
          await flutterLocalNotificationsPlugin.cancel(notification.id!);
        }
      }
    }

**Comment by muhammetikbalkeklik** [comment]
When I corrected my own codes the problem was solved.

**Comment by joshminton** [comment]
@muhammetikbalkeklik What was the problem with your code that you corrected? I think I am facing a similar issue.

**Comment by muhammetikbalkeklik** [comment]
I encountered this issue due to a scope error. Here is my corrected code, which now works without any problems. It's a bit of spaghetti code since I wrote it when I was first learning Dart. But in its current form, it runs smoothly:
Future<void> fixActiveStatusBar(WidgetRef ref) async {
    var aktifNotificationList =
        await flutterLocalNotificationsPlugin.getActiveNotifications();
    aktifNotificationList = aktifNotificationList
        .where(
          (element) => (element.id! >= 15000),
        )
        .toList();
    if (aktifNotificationList.length != 1) {
      for (var notification in aktifNotificationList) {
        if (notification.id! >= 15000) {
          await flutterLocalNotificationsPlugin.cancel(notification.id!);
        }
      }
      print("aktifNotificationList.length ${aktifNotificationList.length}");
      var mixbox = await Hive.openBox('ayarlar');
      var bildirimBarirTema = mixbox.get('statustema');
      var imsakiyeverisi =
          Sabitler.genelRefimiz.read(aylikImsakiyeVerisiProvider);
      imsakiyeverisi.when(
          data: (data) async {
            locationName = Sabitler.genelRefimiz.read(secilenilProvider);
            subLocationName = Sabitler.genelRefimiz.read(secilenilceProvider);
            List<EzanVakti> ilkGosterimeDair = [
              EzanVakti(
                  vakit: 'imsak'.tr(),
                  saat: data.first.fajr!,
                  hicriDate: data.first.hijriDateLong.toString()),
              EzanVakti(
                  vakit: 'sabah'.tr(),
                  saat: data.first.sunrise!,
                  hicriDate: data.first.hijriDateLong.toString()),
              EzanVakti(
                  vakit: 'ogle'.tr(),
                  saat: data.first.dhuhr!,
                  hicriDate: data.first.hijriDateLong.toString()),
              EzanVakti(
                  vakit: 'ikindi'.tr(),
                  saat: data.first.asr!,
                  hicriDate: data.first.hijriDateLong.toString()),
              EzanVakti(
                  vakit: 'aksam'.tr(),
                  saat: data.first.maghrib!,
                  hicriDate: data.first.hijriDateLong.toString()),
              EzanVakti(
                  vakit: 'yatsi'.tr(),
                  saat: data.first.isha!,
                  hicriDate: data.first.hijriDateLong.toString()),
              EzanVakti(
                  vakit: 'imsak'.tr(),
                  saat: data[1].fajr!,
                  hicriDate: data.first.hijriDateLong.toString()),
            ];

            await showNotificationStatusBar(
                ilkGosterimeDair, bildirimBarirTema);
          },
          loading: () {},
          error: (Object error, StackTrace stackTrace) {});
    }
  }
