### ISSUE TITLE
[Question] html text and image in MessagingStyleInformation 

### ISSUE THREAD

**Issue by mbenci** [MaikuB/flutter_local_notifications#2429]
I would like to understand if it is possible to use text in html format inside the "Message" object and possibly how to do it. In my tests the text in the notification was plain (<p>hello</p>).
I would also like to understand if it was possible to insert an image instead of text.
These are possibilities that I have seen done in chat like WhatsApp but I cannot reproduce the same result here.
Thank you

**Comment by MaikuB** [comment]
I don't believe so but this is something you would need to explore more. As the purpose of the plugin is to provide access to native notification APIs, knowledge of how those APIs work is a prerequisite. Whilst I maintain the plugin, this doesn't mean I know all the details about the APIs either

**Comment by Levi-Lesches** [comment]
@mbenci  I'm also not really familiar with the native APIs, but I took a look for you: 

[`MessagingStyle`](https://developer.android.com/reference/android/app/Notification.MessagingStyle): 

> The messages should be added in chronologic order, i.e. the oldest first, the newest last.
> 
> Multiple Messages in a row with the same timestamp and sender may be grouped as a single message. This means an app should represent a message that has both an image and text as two Message objects, one with the image (and fallback text), and the other with the message text. For consistency, a text message (if any) should be provided after Uri content.

I'd say based on this, it seems more proper to use `Message.dataUri` and `Message.dataMimeType`, but again, I haven't tried it myself.
