### ISSUE TITLE
[Question] Handling onDidReceiveBackgroundNotificationResponse actions to play audio on the background

### ISSUE THREAD

**Issue by suarezjulian** [MaikuB/flutter_local_notifications#2431]
Thanks MaikuB for this great library and the extensive documentation, really appreciate it

I'm creating an app that plays some audio files with positive affirmations, and I have a feature on my app to get a notification to remind users to play some affirmations.

I'm able to create the notification and to handle when users click on the notifications but I'm having trouble handling when they click on a 'Play' action in the notification.

When I receive an event on 'onDidReceiveBackgroundNotificationResponse' this is received on a background isolate. I have a Riverpod provider to play audio on the background (using just_audio_background) but it seems that I can't access it because my main function has not been called and the provider has not been created. How should I handle cases like this one, when the notification handler is in a background handler but I need stuff from my main isolate?

**Comment by suarezjulian** [comment]
Hi all,

I managed to solve this myself, I had to create a new riverpod provider Container  inside my background notification handler, since I don't have access to the one created in the min function. Something like:

`var providerContainer = **ProviderContainer**(); // This is the key part
  var audioPlayer = providerContainer.read(audioPlayerProvider);
  ....`

**Comment by minhtaama** [comment]
OMG! I stuck at this part like you for 2 days and so lucky I found your question! Your way to solve this is awesome! Working like a charm! Thank you so much!!!
