### ISSUE TITLE
FlutterLocalNotificationsPlugin.java:1019: bigLargeIcon is ambiguous

### ISSUE THREAD

**Issue by AKarchi** [MaikuB/flutter_local_notifications#2438]
C:\Users\marie\AppData\Local\Pub\Cache\hosted\pub.dev\flutter_local_notifications-14.1.5\android\src\main\java\com\dexterous\flutterlocalnotifications\FlutterLocalNotificationsPlugin.java:1019: error: reference to bigLargeIcon is ambiguous
      bigPictureStyle.bigLargeIcon(null);
                     ^
  both method bigLargeIcon(Bitmap) in BigPictureStyle and method bigLargeIcon(Icon) in BigPictureStyle match
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_local_notifications:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --info option to get more log output.
> Run with --scan to get full insights.

BUILD FAILED in 1s
Error: Gradle task assembleDebug failed with exit code 1

**Comment by joemdjossou** [comment]
You can fix it by upgrading flutter_local_notifications to 17.2.1, or latest. Because by this version the issue has been fixed

**Comment by helloixan** [comment]
> You can fix it by upgrading flutter_local_notifications to 17.2.1, or latest. Because by this version the issue has been fixed

Thanks! i was lookin for this answer and thats work on my problem!

**Comment by AKarchi** [comment]
Thank you!!

**Comment by Fredoski26** [comment]
> 17.2.1

It works for me . Thanks
