### ISSUE TITLE
Add Swift Package Manager support

### ISSUE THREAD

**Issue by loic-sharma** [MaikuB/flutter_local_notifications#2448]
Hello,

Flutter is migrating to [Swift Package Manager][]. Please [add Swift Package Manager support][] to your plugin.

Flutter will eventually deprecate and then remove support for CocoaPods. Adding Swift Package Manager support future-proofs your plugins.

[Swift Package Manager]: https://www.swift.org/documentation/package-manager/
[add Swift Package Manager support]: https://docs.flutter.dev/packages-and-plugins/swift-package-manager/for-plugin-authors#how-to-add-swift-package-manager-support-to-an-existing-flutter-plugin

### How to add Swift Package Manager support to your plugins

You can find the migration guide here: https://docs.flutter.dev/packages-and-plugins/swift-package-manager/for-plugin-authors#how-to-add-swift-package-manager-support-to-an-existing-flutter-plugin

If you run into issues or have questions, please reach out to the Flutter team. You can ping me at @loic-sharma, send a message to the #hackers-ios channel on [Flutter’s discord][], or [open a GitHub issue][].

Thank you for your wonderful contributions to the Flutter ecosystem!

[Flutter’s discord]: https://github.com/flutter/flutter/blob/master/docs/contributing/Chat.md
[open a GitHub issue]: https://github.com/flutter/flutter/issues/new/choose

### Why is Flutter migrating to Swift Package Manager?

[CocoaPods is now in maintenance mode][].

Swift Package Manager support is one of Flutter’s most requested features: [flutter#33850][].

Flutter's Swift Package Manager integration has several benefits:

1. **Access to the Swift package ecosystem**. Flutter plugins can use the growing ecosystem of [Swift packages][].
2. **Simplifies Flutter installation**. Swift Package Manager is bundled with Xcode. In the future, you won’t need to install Ruby and CocoaPods to target iOS or macOS.

[CocoaPods is now in maintenance mode]: https://blog.cocoapods.org/CocoaPods-Support-Plans/
[flutter#33850]: https://github.com/flutter/flutter/issues/33850
[Swift packages]: https://swiftpackageindex.com/

**Comment by MaikuB** [comment]
I've sent a DM on Twitter but didn't receive a response. The rules for the hackers channel also indicate that they're for those contributing directly to Flutter. Can you advise how ready/mature is this? The docs say the work is still in progress and the implementation may change and last I checked, some first party plugins still haven't migrated. If I were to migrate then is it possible rework is needed?

**Comment by loic-sharma** [comment]
Ah sorry, I don't check my Twitter DMs regularly!

> Can you advise how ready/mature is this?

Flutter's SwiftPM feature is stable for package authors. Plugins like `flutter_local_notifications` should migrate as soon as possible.

In the next release of Flutter, the SwiftPM feature will be available on the stable channel with an opt-in.

However, Flutter's SwiftPM integration doesn't support [add-to-app](https://docs.flutter.dev/add-to-app) apps yet. These apps will need to continue using CocoaPods for now. This is something we're actively working on though! :)

> If I were to migrate then is it possible rework is needed?

The package structure is stable and will not change.

>  last I checked, some first party plugins still haven't migrated

This is correct, but that's due to blockers unrelated to Flutter's SwiftPM feature. For example, we've been rewriting `in_app_purchase` from Objective-C to Swift. We've been focusing on that rewrite before adding SwiftPM support. We will migrate all of our plugins as soon as possible too :)
