### ISSUE TITLE
PendingNotificationRequest get time

### ISSUE THREAD

**Issue by RobertBrunhage** [MaikuB/flutter_local_notifications#245]
Is it possible to get the time a notification is planned for? I was able to the the `title` and `body` but just wondering if I could also get the time planned or do I need to store this myself?

**To Reproduce**
1. Scedule a notification with `showDailyAtTime`
2. Get all notifications with `pendingNotificationRequests()`
3. The object doesn't have a time variable

**Expected behavior**
I could get the time to display in the app

**Sample code to reproduce the problem**
The project is completely open source and at the bottom of this file you will be able to see the `ListTile` with title and body but would love a way to show the time it's planned for

[GitHub](https://github.com/RobertBrunhage/water_reminder_app_youtube/blob/feature/notification/lib/src/home/pages/notifcation_page.dart)

**Comment by MaikuB** [comment]
Hmm will need to look into that, happy to take a PR as well. There's a known issue though around daylight savings as well when it comes to the times that notifications get displayed

**Comment by RobertBrunhage** [comment]
Would love to make a PR but don't have much experience with native Android and iOS. Really appreciate all your hard work on the plugin, it's really top notch! :)

**Comment by MaikuB** [comment]
I took a look. Problem is that on Android, there doesn't to be an API to get the next time it will trigger (which is what iOS does). This is further complicated in that currently the notifications may not fire at the exact time. The only way to possibly do this is that for recurring notifications, it would need to change so even though a recurring notification is requested, the plugin only schedules one. When it fires, plugin would need to schedule the next time it happens. So to summarise, it's not looking to be doable unless there are changes on how Android ones are scheduled and it may not apply to notifications that have already been scheduled

**Comment by RobertBrunhage** [comment]
Ahh okay, thanks for taking some time to look in to it!

I will probably save the info for the notification in my database and each startup I will just make sure to schedule them and unschedule them when I sign out of the app :)

But this pretty much answered my question so will close it, and thanks again for the fast responses!

**Comment by MaikuB** [comment]
No worries. Worth mentioning that I will be looking at how notifications get scheduled on Android as I've described earlier. This is tied to #216 though could be redundant for recurring notifications if a callback can be provided when a notification is shown since that could be done on the Dart side
