### ISSUE TITLE
Update dependency timezone to latest

### ISSUE THREAD

**Issue by shatanikmahanty** [MaikuB/flutter_local_notifications#2450]
Time zone database updated to [2024b](https://lists.iana.org/hyperkitty/list/tz-announce@iana.org/thread/IZ7AO6WRE3W3TWBL5IR6PMQUL433BQIE/).

Because of the above change, the authors of timezone released timezone v10.0.0. Please update to the latest version as flutter local notifications depends on v0.9.0 of timezone.

**Comment by MaikuB** [comment]
This should be resolved now with 18.0.1 but if your app uses `http` package then you would need to bump your app's dependency on it for it to work

**Comment by shatanikmahanty** [comment]
> This should be resolved now with 18.0.1 but if your app uses `http` package then you would need to bump your app's dependency on it for it to work

Thanks @MaikuB!
