### ISSUE TITLE
[Help Wanted] Notifications on iOS won't show up, when app is terminated. 

### ISSUE THREAD

**Issue by JHarzenetter** [MaikuB/flutter_local_notifications#2468]
Hi there, 
as i mentioned i would like to request some help. I cant get this running corretly. In my case, the notifications work beautifully when the app is in the foreground/background but i cant figure out what i should do for the terminated state. Android works fine, only iOS is affected.

Here are my configurations:

AppDelegate.swift:
```
import UIKit
import Flutter
import flutter_local_notifications

@main
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {

    // This is required to make any communication available in the action isolate.
    FlutterLocalNotificationsPlugin.setPluginRegistrantCallback { (registry) in
        GeneratedPluginRegistrant.register(with: registry)
    }
      
    if #available(iOS 10.0, *){
        UNUserNotificationCenter.current().delegate = self as UNUserNotificationCenterDelegate
    }
      
    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}
```
In XCode > Runner > Signing & Capabilities > Background Modes:
- Remote notifications is checked

In flutter the following initialisation is called:
```
FirebaseMessaging.onBackgroundMessage(firebaseMessageBackgroundHandler);
```

```
await flutterLocalNotificationsPlugin
        .resolvePlatformSpecificImplementation<
            IOSFlutterLocalNotificationsPlugin>()
        ?.requestPermissions();

    FirebaseMessaging.instance.setForegroundNotificationPresentationOptions(
        badge: true, alert: true, sound: true);
```

and when a notification is recieved this is called:

```
@pragma('vm:entry_point')
Future<void> firebaseMessageBackgroundHandler(RemoteMessage message) async {
  if (kDebugMode) {
    print('BackgroundHandler: ${message.data}');
  }
  await flutterLocalNotificationsPlugin.show(
    Random().nextInt(0x7FFFFFFF),
    'App Name put here',
    message.data['message'], //this is secured beforehand
    NotificationDetails(
      android: AndroidNotificationDetails(...),
      iOS: const DarwinNotificationDetails(
        presentAlert: true,
        presentBadge: true,
        presentSound: true,
        interruptionLevel: InterruptionLevel.active,
      ),
    ),
    payload: "Some Payload",
  );
}
```

Did i miss something or is there any obvious missconfiguration?
Thanks

**Comment by Levi-Lesches** [comment]
So, just to clarify, you're able to have the handler run, but you're not able to trigger a notification while the app is terminated? Your code shows both firebase cloud messaging (push notifications) and this package (local notifications) so it's not entirely obvious where exactly your problem is

**Comment by JHarzenetter** [comment]
As far as i know, yes thats the Problem.

FCM is only used for communicating, not for showing the notification

**Comment by Levi-Lesches** [comment]
I can't really answer the specifics of your problem, but have you tried: 
- calling initialize in the handler
- calling `WidgetsBinding.ensureInitialized()` in the binding
- just using firebase for push notifications directly

Most advice online about sending notifications when the app is terminated point to push, instead of local, notifications. You may want to set up fcm to show the notifications instead of attempting to use regular code and a plugin
