### ISSUE TITLE
SCHEDULE AND PERIODICALLY NOTIFICATION DOESNT WORK

### ISSUE THREAD

**Issue by wxkz** [MaikuB/flutter_local_notifications#248]
**IMPORTANT**
the flutter dont give me erro, but... schedule doesn't work

**MY CODE**

import 'package:flutter/material.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'dart:async';

             RaisedButton(

              onPressed: () => showOngoingNotification(notifications,title: 'Title', body: 'Body'),
              child: Text('Click here')
            ),
            RaisedButton(
              onPressed: () async {await scheduleNotification(notifications,title: 'teste', body: 'tettete');},
              child: Text('Schedule notifications')
            ),
            RaisedButton(
              onPressed: () async {await periodicallyNotification(notifications,title: 'periodi', body: 'tpeortete');},
              child: Text('Periodically notifications')
            ),

NotificationDetails get _ongoing {
  final androidChannelSpecifics = AndroidNotificationDetails(
    'your channel id',
    'your channel name',
    'your channel description',
    importance: Importance.Max,
    priority: Priority.High,
    ongoing: true,
    autoCancel: true,
  );
  final iOSChannelSpecifics = IOSNotificationDetails();
  return NotificationDetails(androidChannelSpecifics, iOSChannelSpecifics);
}

// Schedule Notificaton -------------------------------------------------------------

var scheduledDate = DateTime.now().add(Duration(seconds: 5));

Future scheduleNotification(
  FlutterLocalNotificationsPlugin notifications, {
  @required String title,
  @required String body,
  int id = 0,
}) =>
    showScheduledNotification(notifications,
        title: title, body: body, id: id, type: _ongoing);

Future showScheduledNotification(
  FlutterLocalNotificationsPlugin notifications, {
  @required String title,
  @required String body,
  @required NotificationDetails type,
  int id = 1,
}) =>
notifications.schedule(id, title, body, scheduledDate, type);
//notifications.show(id, title, body, type);

// Periodically Notificaton -------------------------------------------------------------

Future periodicallyNotification(
  FlutterLocalNotificationsPlugin notifications, {
  @required String title,
  @required String body,
  int id = 0,
}) =>
    showPeriodicallyNotification(notifications,
        title: title, body: body, id: id, type: _ongoing);

Future showPeriodicallyNotification(
  FlutterLocalNotificationsPlugin notifications, {
  @required String title,
  @required String body,
  @required NotificationDetails type,
  int id = 1,
}) =>
notifications.periodicallyShow(id, title, body, RepeatInterval.EveryMinute, type);

**PUBSPEC.YAML**

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_local_notifications:
dev_dependencies:
  flutter_test:
    sdk: flutter

// I ALREADY PUT THINGS IN ANDROIDMANIFEST.XML ( SHOW NOTIFICATION WORKS FINE )

**configs**
runnning on android 9 with zenfone max pro m1 ( debug mode )

**Comment by MaikuB** [comment]
Likely an issue with the phone you're using. See https://stackoverflow.com/questions/37171730/alarmmanager-not-working-on-asus-zenfone-2-devices-with-android/40694048

**Comment by wxkz** [comment]
oh thanks, i will test in other device tomorrow, if a get god news i close the issue

**Comment by wxkz** [comment]
i was testing now with pixel 2 on android 9 and 8 but in both doesn't worked, i published my code on github: https://github.com/wxkz/flutterApp i'm yet trying fix that using others phones 

some error that i get on pixel

![Screenshot_20190613_073612](https://user-images.githubusercontent.com/44681621/59426876-ae9f9d00-8daf-11e9-8510-34caa9f86869.png)

obs = see terminal ( the app crashed because my computer was dying )

**Comment by MaikuB** [comment]
you mentioned you had configured the AndroidManifest.xml but it looks like you didn't add in the receivers mentioned in the readme for scheduled notifications to work. also note that the plugin has an example app that you can run by cloning this repo
