### ISSUE TITLE
Make Android permission (Post notification) as optional

### ISSUE THREAD

**Issue by Santhosh-4035** [MaikuB/flutter_local_notifications#2487]
Hi @MaikuB, I’m currently testing my app and have encountered an issue related to the permissions required by the flutter_local_notifications plugin. The app’s AndroidManifest.xml file currently requests the POST_NOTIFICATIONS permission, which is marked as a dangerous permission according to Android’s security guidelines.

After Tested my app through MOBSF for security testing, I noticed that this permission is flagged as dangerous. You can see more about it here:
[Android Developer Documentation on POST_NOTIFICATIONS](https://developer.android.com/reference/android/Manifest.permission#POST_NOTIFICATIONS).

Given that the **POST_NOTIFICATIONS** permission has a protection level of "dangerous," I’m wondering if it is strictly necessary for the functionality of the app, especially since it seems to be flagged as a security concern.

Could you please clarify if this permission is required for proper functioning, or if there’s an alternative approach that avoids using this permission?

**Screenshots**
![image](https://github.com/user-attachments/assets/2e0a8319-dd71-4121-89e0-3ed94c41a06a)

@MaikuB, have a look at this issue.
Thank you!

**Comment by Levi-Lesches** [comment]
See [the Android docs on `POST_NOTIFICATIONS`](https://developer.android.com/reference/android/Manifest.permission#POST_NOTIFICATIONS): 

> Allows an app to post notifications

Yes, this is considered "dangerous" because it can disrupt the user visibly -- but that's what this plugin is for! Without the permission, the plugin cannot function at all.

**Comment by Levi-Lesches** [comment]
Do you mean you removed it from your own app's manifest? Because even if you did, this plugin has its own manifest file that requests those permissions anyway.

**Comment by MaikuB** [comment]
@Santhosh-4035 If a developer is making use of the plugin then they intend to display notifications. Making the permission optional adds more friction in being able to display notifications so this isn't a change that won't be done. Various other libraries like FCM also request this permission. Given you weren't aware of what the permission was for, I would guess the thinking behind raising the issue to ask for it to be optional was a reaction on seeing the permission is flagged as dangerous looking into the explanation behind the permission that was in the screenshot you shared understanding what it's for. I'd suggest you properly digest and think about what it is you're trying to achieve here. Will close the issue as the plugin won't be making any changes
