### ISSUE TITLE
Custom callback

### ISSUE THREAD

**Issue by jonasmende** [MaikuB/flutter_local_notifications#251]
Hi,

have you planned to allow custom callback for showing notifications?
Currently, I have to define a global callback for any notification sent.
If I have multiple types of notifications, I would like to define a custom callback per notification (for example in the show() function). Otherwise, I would have add routing information into the payload of the message in order to determine what to do in the global callback.
Is anything like that planned?

Mamy thanks in advance.

**Comment by MaikuB** [comment]
Was attempted before but ran into issues. See #21
