### ISSUE TITLE
[Windows] How to play a custom sound?

### ISSUE THREAD

**Issue by JulienDev** [MaikuB/flutter_local_notifications#2510]
**Describe the bug**
Hello, I’m trying to play a custom sound on Windows, but nothing I’ve tried is working. The README doesn’t explain how this should be achieved, and the example project `_showNotificationCustomSound()` only plays a preset sound: `WindowsNotificationAudio.preset(sound: WindowsNotificationSound.alarm5)`.

In the source code, I noticed a function that allows playing a sound from a URI: `WindowsNotificationAudio.fromFile`. However, I’m unsure of the exact path format required or how to test it. Additionally, in the `allowedSchemes`, I see that only `ms-appx and ms-resource` are supported. Does this mean I need to package it as an MSIX?

Any documentation or sample code would be great :)

**To Reproduce**

- Create a new notification with an audio file: 
```
WindowsNotificationDetails(
        audio: WindowsNotificationAudio.fromFile(file: Uri.parse("ms-appx://data/flutter_assets/assets/custom_sound.mp3"))
      )
```
- Error in the console:
```
flutter: Error :  Unsupported operation: Cannot extract a file path from a ms-appx URI
flutter: StackTrace :  #0      _SimpleUri.toFilePath (dart:core/uri.dart:4905:7)
#1      new WindowsNotificationAudio.fromFile (package:flutter_local_notifications_windows/src/details/notification_audio.dart:109:23)
#2      LocalNotificationsManager.schedule (package:projects/data/notifications/local_notifications_manager.dart:103:41)
#3      AlarmsManager.schedulePrayer (package:projects/data/alarms/alarms_manager.dart:118:28)
#4      AlarmsManager.showTestPrayer (package:projects/data/alarms/alarms_manager.dart:69:5)
```

**Expected behavior**
The custom sound should be played

**Comment by Levi-Lesches** [comment]
Hey, yeah this isn't the most clear. I'm actually in the process of rewriting the README and expanding on platform-specific documentation over at #2477. There will be a whole Windows-specific document that goes into all the nitty-gritty details, hopefully by the end of January. 

>  Additionally, in the allowedSchemes, I see that only ms-appx and ms-resource are supported. Does this mean I need to package it as an MSIX?

Based on the [Windows docs](https://learn.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/custom-audio-on-toasts), yes the only supported URI schemes are `ms-appx://` and `ms-resource://`, which refer to assets bundled in the MSIX and not just any random file on the device. In general with this package, you'll want to use MSIX packaging as many features will not work without it. 

Seems like the error you're getting is from an error in my code though: 

https://github.com/MaikuB/flutter_local_notifications/blob/2f5215df623489c476d910432fde59f3a35d991c/flutter_local_notifications_windows/lib/src/details/notification_audio.dart#L105-L109

I shouldn't be calling `.toFilePath()`. Silly bug from when I was using `Uri.file()` in an old branch. The correct usage should be `source = file.toString()`. 

 I'll try to send in a PR to fix that and test it soon, and update the Windows sections of the new docs.

**Comment by JulienDev** [comment]
Thank you so much for your work, I'll try again when the PR will be ready :)

**Comment by Levi-Lesches** [comment]
Thanks for the report -- #2511 should fix it. In short, 

```dart
WindowsNotificationDetails(
  audio: WindowsNotificationAudio.asset("assets/custom_sound.mp3"),
)
```

**Comment by JulienDev** [comment]
I just tested your branch and it's working perfectly when a msix is built! Thank you so much for this quick fix and happy new year!
