### ISSUE TITLE
Pending notification request

### ISSUE THREAD

**Issue by gsifni** [MaikuB/flutter_local_notifications#252]
Hello this is not a bug more an improvement. 

The function pendingNotificationRequests() which return a List of PendingNotificationRequest doesn't return the scheduled date only the id, the title ,the body and the extra data. 

It would be much useful to return the scheduled date also.

Thank you

**Comment by MaikuB** [comment]
See #245

**Comment by gsifni** [comment]
Oh i see thank you.
