### ISSUE TITLE
custom notification sound did not work on iOS

### ISSUE THREAD

**Issue by hujianhang2996** [MaikuB/flutter_local_notifications#255]
**Describe the bug**
Maybe it's not a bug. Because it works fine when I run the example, but not when I run my own app it just plays the default sound. I have copied the aiff file to the ios dir. So I want to know what else should I do to play custom sound. Thanks.

**Comment by MaikuB** [comment]
You'll need to use Xcode. There should be a number of tutorials around about adding sounds to an iOS application such as this one https://medium.com/@dmennis/the-3-ps-to-custom-alert-sounds-in-ios-push-notifications-9ea2a2956c11

**Comment by hujianhang2996** [comment]
thanks a lot.That’s so helpful.

**Comment by FineTillYouCameAlong** [comment]
Anyone else wondering about this: you need to open Xcode and drag files into the Runner project (so they are on the same level with Flutter and Runner folders). Simply copying the files to the folder outside of Xcode won't be enough.
