### ISSUE TITLE
Using a device's sound on Android

### ISSUE THREAD

**Issue by altherat** [MaikuB/flutter_local_notifications#257]
Is it possible to use sound/ringtone that is already available on the device? Looking at the example and some [code](https://github.com/MaikuB/flutter_local_notifications/blob/03ab073b474cb7e7be0a4bde2f3b9274d0b940ae/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java#L576-L586), it appears that it's only possible to play a sound that is provided in the resources. I think it should be possible to provide a URI to play a sound that's already on the device. The URIs can be obtained with [`RingtoneManager`](https://developer.android.com/reference/android/media/RingtoneManager.html#getCursor()).

**Comment by MaikuB** [comment]
As you may have noticed already when looking at the code, it's not possible to do so with the plugin. That would likely involve querying all of the available ringtones that IMO is outside the scope of the functionality of the plugin. If you need that functionality to look at forking or write platform-specific code to do so in your app. I could, however, look at making changes that would accept a URI for the sound.

**Comment by MaikuB** [comment]
Support for passing in a URI has been in added in 1.4.0

**Comment by ouazom** [comment]
This still does not work for me, I'm properly passing the URI but the sound is not playing.

here is the code
```dart
// ---------

    final AndroidNotificationSound? channelSound = UriAndroidNotificationSound(customUri);

    final AndroidNotificationChannel channel = AndroidNotificationChannel(
      'timer_alarm_channel',
      'Timer Alarms',
      description: 'Notifications for timer alarms',
      importance: Importance.max,
      playSound: true,
      sound: channelSound,
    );

    await _notifications
        .resolvePlatformSpecificImplementation<AndroidFlutterLocalNotificationsPlugin>()
        ?.createNotificationChannel(channel);
  }

```
