### ISSUE TITLE
flutter_local_notifications: ^0.7.1+3  & cloud_firestore create issue on the compilation

### ISSUE THREAD

**Issue by NikolinNgjela** [MaikuB/flutter_local_notifications#261]
AAPT: error: resource android:attr/fontVariationSettings not found.

AAPT: error: resource android:attr/ttcIndex not found.

after adding _flutter_local_notifications: ^0.7.1+3_ indeed I'll try some versions and I think the issue is related with the firestore. 

I've try also this solution but it doesn't work for me 
https://github.com/MaikuB/flutter_local_notifications/issues/86

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Failed to process resources, see aapt output above for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
Finished with error: Gradle task assembleDebug failed with exit code 1
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************

**Comment by MaikuB** [comment]
Before you check the other versions, I suggest you look at the link that's in the error message that says it will provide more information on how to fix the problem

**Comment by NikolinNgjela** [comment]
Yes indeed, I've try this one.
I have use flutter_local_notifications in more than one project with firebase push notifications and other packages works fine, on this project it show the error when is running with firestore.

**Comment by NikolinNgjela** [comment]
@MaikuB The only version that I was available to compile and work for every FCM sync the local notifications when the app is running (open) was the version **0.4.5**

  cloud_firestore: ^0.12.6
  flutter_local_notifications: 0.4.5

I've also try the other version and I'm seeing that the version 0.5.0 was published one day after.
0.5.0 | Jan 31, 2019 // This one and the other that comes until 0.7.1+3 // throw the above error.
0.4.5 | Jan 30, 2019  // This one works!

**Comment by MaikuB** [comment]
That's the version before migrating to AndroidX and there's a note about AndroidX in the readme. As mentioned above, please read the link that's in the error message and follow the instructions

**Comment by MaikuB** [comment]
Closing to due lack of further response. Note that another similar issue was raised [here](https://github.com/MaikuB/flutter_local_notifications/issues/268) that was more to do with not configuring the Android app properly in order to use the cloud_firestore. You may want to check to see if you need to make similar changes
