### ISSUE TITLE
Unhandled Exception: MissingPluginException

### ISSUE THREAD

**Issue by DenisMrGnusa** [MaikuB/flutter_local_notifications#262]
I tried to install the plugin but instead an error appeared as below:

D8: Program type already present: android.support.v4.app.INotificationSideChannel

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: /home/denis/AndroidStudioProjects/spmi_conference_v2/build/app/intermediates/transforms/dexBuilder/debug/39.jar, /home/denis/AndroidStudioProjects/spmi_conference_v2/build/app/intermediates/transforms/dexBuilder/debug/84.jar, /home/denis/AndroidStudioProjects/spmi_conference_v2/build/app/intermediates/transforms/dexBuilder/debug/35.jar, /home/denis/AndroidStudioProjects/spmi_conference_v2/build/app/intermediates/transforms/dexBuilder/debug/78.jar, /home/denis/AndroidStudioProjects/spmi_conference_v2/build/app/intermediates/transforms/dexBuilder/debug/75.jar, /home/denis/AndroidStudioProjects/spmi_conference_v2/build/app/intermediates/transforms/dexBuilder/debug/87.jar, /home/denis/AndroidStudioProjects/spmi_conference_v2/build/app/intermediates/transforms/dexBuilder/debug/69.jar, /home/denis/AndroidStudioProjects/spmi_conference_v2/build/app/intermediates/transforms/dexBuilder/debug/81.jar, /home/denis/AndroidStudioProjects/spmi_conference_v2/build/app/intermediates/transforms/dexBuilder/debug/72.jar, /home/denis/AndroidStudioProjects/spmi_conference_v2/build/app/intermediates/transforms/dexBuilder/debug/43.jar, /home/denis/AndroidStudioProjects/spmi_conference_v2/build/app/intermediates/transforms/dexBuilder/debug/18.jar, /home/denis/AndroidStudioProjects/spmi_conference_v2/build/app/intermediates/transforms/dexBuilder/debug/34.jar, /home/denis/AndroidStudioProjects/spmi_conference_v2/build/app/intermediates/transforms/dexBuilder/debug/27.jar, /home/denis/AndroidStudioProjects/spmi_conference_v2/build/app/intermediates/transforms/dexBuilder/debug/36.jar, /home/denis/AndroidStudioProjects/spmi_conference_v2/build/app/intermediates/transforms/dexBuilder/debug/19.jar, /home/denis/AndroidStudioProjects/spmi_conference_v2/build/app/intermediates/transforms/dexBuilder/debug/8.jar, /home/denis/AndroidStudioProjects/spmi_conference_v2/build/app/intermediates/transforms/dexBuilder/debug/33.jar, /home/denis/AndroidStudioProjects/spmi_conference_v2/build/app/intermediates/transforms/dexBuilder/debug/42.jar, /home/denis/AndroidStudioProjects/spmi_conference_v2/build/app/intermediates/transforms/dexBuilder/debug/41.jar, /home/denis/AndroidStudioProjects/spmi_conference_v2/build/app/intermediates/transforms/dexBuilder/debug/9.jar, /home/denis/AndroidStudioProjects/spmi_conference_v2/build/app/intermediates/transforms/dexBuilder/debug/28.jar, /home/denis/AndroidStudioProjects/spmi_conference_v2/build/app/intermediates/transforms/dexBuilder/debug/24.jar, /home/denis/AndroidStudioProjects/spmi_conference_v2/build/app/intermediates/transforms/dexBuilder/debug/37.jar, /home/denis/AndroidStudioProjects/spmi_conference_v2/build/app/intermediates/transforms/dexBuilder/debug/7.jar, /home/denis/AndroidStudioProjects/spmi_conference_v2/build/app/intermediates/transforms/dexBuilder/debug/32.jar, /home/denis/AndroidStudioProjects/spmi_conference_v2/build/app/intermediates/transforms/dexBuilder/debug/38.jar, /home/denis/AndroidStudioProjects/spmi_conference_v2/build/app/intermediates/transforms/dexBuilder/debug/44.jar, /home/denis/AndroidStudioProjects/spmi_conference_v2/build/app/intermediates/transforms/dexBuilder/debug/25.jar, /home/denis/AndroidStudioProjects/spmi_conference_v2/build/app/intermediates/transforms/dexBuilder/debug/6.jar, /home/denis/AndroidStudioProjects/spmi_conference_v2/build/app/intermediates/transforms/dexBuilder/debug/31.jar, /home/denis/AndroidStudioProjects/spmi_conference_v2/build/app/intermediates/transforms/dexBuilder/debug/26.jar, /home/denis/AndroidStudioProjects/spmi_conference_v2/build/app/intermediates/transforms/dexBuilder/debug/13.jar, /home/denis/AndroidStudioProjects/spmi_conference_v2/build/app/intermediates/transforms/dexBuilder/debug/5.jar, /home/denis/AndroidStudioProjects/spmi_conference_v2/build/app/intermediates/transforms/dexBuilder/debug/21.jar, /home/denis/AndroidStudioProjects/spmi_conference_v2/build/app/intermediates/transforms/dexBuilder/debug/30.jar, /home/denis/AndroidStudioProjects/spmi_conference_v2/build/app/intermediates/transforms/dexBuilder/debug/12.jar, /home/denis/AndroidStudioProjects/spmi_conference_v2/build/app/intermediates/transforms/dexBuilder/debug/14.jar, /home/denis/AndroidStudioProjects/spmi_conference_v2/build/app/intermediates/transforms/dexBuilder/debug/20.jar, /home/denis/AndroidStudioProjects/spmi_conference_v2/build/app/intermediates/transforms/dexBuilder/debug/15.jar, /home/denis/AndroidStudioProjects/spmi_conference_v2/build/app/intermediates/transforms/dexBuilder/debug/4.jar, /home/denis/AndroidStudioProjects/spmi_conference_v2/build/app/intermediates/transforms/dexBuilder/debug/11.jar, /home/denis/AndroidStudioProjects/spmi_conference_v2/build/app/intermediates/transforms/dexBuilder/debug/2.jar, /home/denis/AndroidStudioProjects/spmi_conference_v2/build/app/intermediates/transforms/dexBuilder/debug/16.jar, /home/denis/AndroidStudioProjects/spmi_conference_v2/build/app/intermediates/transforms/dexBuilder/debug/3.jar, /home/denis/AndroidStudioProjects/spmi_conference_v2/build/app/intermediates/transforms/dexBuilder/debug/23.jar, /home/denis/AndroidStudioProjects/spmi_conference_v2/build/app/intermediates/transforms/dexBuilder/debug/40.jar, /home/denis/AndroidStudioProjects/spmi_conference_v2/build/app/intermediates/transforms/dexBuilder/debug/10.jar, /home/denis/AndroidStudioProjects/spmi_conference_v2/build/app/intermediates/transforms/dexBuilder/debug/29.jar, /home/denis/AndroidStudioProjects/spmi_conference_v2/build/app/intermediates/transforms/dexBuilder/debug/17.jar, /home/denis/AndroidStudioProjects/spmi_conference_v2/build/app/intermediates/transforms/dexBuilder/debug/22.jar
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: android.support.v4.app.INotificationSideChannel

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 47s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Finished with error: Gradle task assembleDebug failed with exit code 1

I have tried migrating to androidX on the https://goo.gl/CP92wY page, according to the description of the error report.

what am i missing?

Thank you in advance,

**Comment by MaikuB** [comment]
Have you checked to see that Android studio did make changes to your app's build.gradle file after  trying to do the migration? I've noticed that every now and then, Android studio doesn't actually make any changes and I needed to do it a few times for it to work. Also check the gradle.properties file. You may need to put the entries mentioned in the guide manually

**Comment by MaikuB** [comment]
Closing due to lack of further response. One thing to perhaps check is see if this is happening because of another plugin that requires you to enable [multidex](https://developer.android.com/studio/build/multidex)
