### ISSUE TITLE
SmartWatch notifications not vibrating,

### ISSUE THREAD

**Issue by rydal** [MaikuB/flutter_local_notifications#264]
Hi.

I'm using the following code:

 // Method 2
  Future _showNotificationWithDefaultSound(
      int difference, String title, String message) async {
    var androidPlatformChannelSpecifics = new AndroidNotificationDetails(
        'your channel id', 'your channel name', 'your channel description',
        importance: Importance.Max, priority: Priority.Max, );
    var iOSPlatformChannelSpecifics = new IOSNotificationDetails();
    var platformChannelSpecifics = new NotificationDetails(
        androidPlatformChannelSpecifics, iOSPlatformChannelSpecifics);
      await flutterLocalNotificationsPlugin.show(
        0,
        title,
        message,
        platformChannelSpecifics,
        payload: 'Default_Sound',

      );

I get a notificaiton on my smartwatch (a samsung gear s3, but  the watch doesn't vibrate, is there anything i'm missing?

Thanks,
  Rob Brew.

**Comment by MaikuB** [comment]
See https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/AndroidNotificationDetails/enableVibration.html

**Comment by MaikuB** [comment]
Closing since there's been no further response
