### ISSUE TITLE
Android - is it possible to use a sound not from raw folder ?

### ISSUE THREAD

**Issue by rtmzshw** [MaikuB/flutter_local_notifications#265]
**Note - android only**
in my aplication i want to give the clinet an option to record the sound for his notification.
is it even possible in android to pop a notification from an mp3 file that is not stored in the raw folder ?
**if it is,** is this package allows that ? i couldnt find anything in the docs.
and if this package dosent suppots that but it is possible, do you know any workaround i can use?

thank you very much for your help, and BTW great job on the package, so far ive been using it alot and i found it very helpfull.

**Comment by MaikuB** [comment]
It's not something that is supposed by the plugin as it assumes it's a raw resource. Android's notification APIs retrieve the sound from an [Android Uri](https://developer.android.com/reference/android/net/Uri) (I say Android as this is different from the one in the Dart APIs) so if you have the Uri then it could be passed as a sound. This isn't something supported at the moment. You could look at writing your own code on the Android side to handle this or look at adding support to it by submitting a PR

**Comment by rtmzshw** [comment]
thank you @MaikuB , when you say "This isn't something supported at the moment", not supported by who? dart or this package?
and by saying "You could look at writing your own code on the Android side to handle", whats this ? converting the uri to Android Uri?

**Comment by MaikuB** [comment]
Not supported by the plugin as per the first sentence. The sentences following were to elaborate on it.

With regards to writing your own code, I'm talking about writing Java or Kotlin code to get the behaviour you want through the use of platform channels (see https://flutter.dev/docs/development/platform-integration/platform-channels)

**Comment by rtmzshw** [comment]
Thank you very much, appreciate it :)
