### ISSUE TITLE
FlutterHeadlessDartRunner warning on iOS

### ISSUE THREAD

**Issue by diegomgarcia** [MaikuB/flutter_local_notifications#267]
Hi guys,

I've noted that when building on iOS I'm getting the warning:

.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-0.7.1+3/ios/Classes/FlutterLocalNotificationsPlugin.m:61:1: 'FlutterHeadlessDartRunner' is deprecated: FlutterEngine should be used rather than FlutterHeadlessDartRunner

Is this planned to be fixed ? as I've seem that its marked as deprecated.

Best Regards,
Diego Garcia

**Comment by MaikuB** [comment]
Yep will be looking to remove it

**Comment by MaikuB** [comment]
Should be gone in 0.8.0 now. Thanks

**Comment by diegomgarcia** [comment]
Thanks @MaikuB will test it.
