### ISSUE TITLE
Modification of MainActivity and Application

### ISSUE THREAD

**Issue by fre391** [MaikuB/flutter_local_notifications#271]
I stumbled across the following files in your example and wonder in which situation we need to modify MainActivity.java and add Application.java.

It seems for simple notifications we dont need them. However I noticed about some exceptions in my app like ClassNotFoundException of BaseDexClassLoader. I think the reason is that I have defined the both receivers in the AndroidManifest.xml, but not added the Application.java...
Does this make sense? Thx for your kind feedback...

https://github.com/MaikuB/flutter_local_notifications/blob/master/example/android/app/src/main/java/com/dexterous/flutterlocalnotificationsexample/Application.java

https://github.com/MaikuB/flutter_local_notifications/blob/master/example/android/app/src/main/java/com/dexterous/flutterlocalnotificationsexample/MainActivity.java

**Comment by MaikuB** [comment]
You shouldn't need to at all right now. If you look at Application.java, it's commented out anyhow. Something I had left behind from trying to implement headless execution so that there was a way to know when a notification was being shown. It didn't work out but left the code there so I could revisit if needed. I'll likely remove it soon as I was trying to clean some of that code up

**Comment by fre391** [comment]
ah, I see! Thx for letting me know...Well, I thought I might have found the bug in my app, but unfortunately that doesn't work out, hehe... However, good to know...Thx do much....

Whats the purpose of modifications in MainActivity? Also not necessary?

**Comment by MaikuB** [comment]
Not necessary as it's purely for the example app. If these things are needed, I'd make sure to include it in the readme. If you search for "drawableToUri" (without the quotes), you can sort of see how it hangs together on the Dart side as I left a comment in the example app about it. Link to section of the code is [here](https://github.com/MaikuB/flutter_local_notifications/blob/78c879c354094e7a7a2b278e0ecf819e6ece3b09/example/lib/main.dart#L391). Probably not relevant for you use case.

A lot of Android errors I hear about here seem to stem from not having migrated the Android app side to AndroidX. Don't know if you've done so yet but if not, check [here](https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility) for more info

**Comment by fre391** [comment]
Thx for the feedback and the hints.. I will close this "issue" as it is not relevant for your project anyway. All the best for you and keep your package dev up. Its a good one!

**Comment by pedromassango** [comment]
I'm also having `ClassNotFoundException` on my application. any tips to slove it?

**Comment by MaikuB** [comment]
You probably haven't added the proguard rules mentioned in the readme

**Comment by pedromassango** [comment]
Where I can found an example? or just the code that I must add in proguard

**Comment by MaikuB** [comment]
Mentioned in my previous post that it's in the readme unless you're looking for something else

**Comment by MaikuB** [comment]
You may want to refer to this for more info https://developer.android.com/studio/build/shrink-code

**Comment by pedromassango** [comment]
I already have the proguard file. I just want to know wich class name should I add into it.

Is this the correct class name? `com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver`

**Comment by MaikuB** [comment]
Yep so I mean the content you need to add is in the readme (search for Proguard), which should lead you to see the following

```
-keep class com.dexterous.** { *; }
```

The previous link was more for further reading on the topic

**Comment by pedromassango** [comment]
Thanks. I just noticed that I already have that on proguard. but still having this issue

**Comment by MaikuB** [comment]
Suspect the issues lies elsewhere then. For example it could be with another plugin that you're using.

**Comment by MaikuB** [comment]
Perhaps something else worth looking into is if you need to turn on multidex for your app as well

**Comment by MaikuB** [comment]
@pedromassango the exception you're getting is different than what's reported [here](https://github.com/MaikuB/flutter_local_notifications/issues/382#issuecomment-559960296) but can you try adding the Proguard rules that are linked in that post to see if it helps?
