### ISSUE TITLE
android 8+ doesn't play sound

### ISSUE THREAD

**Issue by mahmoudparandeh** [MaikuB/flutter_local_notifications#272]
in android 8+ i set sound: 'notification' and place notification.mp3 under raw folder the app build without error but no sound played. i thinks notification handling is changed since android 8+. is it any way to play sounds?

**Comment by MaikuB** [comment]
Sounds can be played and is demonstrated in the sample app. If you're having trouble then please provide a full sample app that reproduces the problem you're having
