### ISSUE TITLE
selectNotification how to pass payload?

### ISSUE THREAD

**Issue by sante85** [MaikuB/flutter_local_notifications#276]
**Describe the bug**
when i call selectNotification payload is null.
How to pass payload to read

**To Reproduce**
If applicable, steps to reproduce the behavior:
this is body sended via fcm
{
 "to" : "/topics/VgtARwhilq",
  "notification" : {
 "body" : "body",
 "content_available" : true,
 "priority" : "high",
 "title" : "test"
 },
 "data" : {
 "body" : "body",
 "title": "test"
 "content_available" : true,
 "priority" : "high"
 }
}

**Comment by sante85** [comment]
in onSelectNotification you  can pass entire map, or you make another call back?

**Comment by MaikuB** [comment]
Every method that will show a notification has an optional `payload` parameter and takes. The first couple of paragraphs in the getting started section cover this (note: realised I'll need to make a little bit of a correction there) and you'll see it's a string. I'd suggest you also run the example app and look at the code

**Comment by sante85** [comment]
fcm reject any other contents. PR #277 can be a solution

**Comment by MaikuB** [comment]
I don't see how the use of FCM is related to what you're asking. That PR is an attempt at solving another issue

**Comment by sante85** [comment]
Fcm remove from body any other properties except "notification" and "data".

If you accept PR, i can read "data" object

Il Mar 30 Lug 2019, 10:55 Michael Bui <notifications@github.com> ha scritto:

**Comment by MaikuB** [comment]
You could convert what you need to a string (e.g. json) and decode it to the format that suits what you're doing

**Comment by sante85** [comment]
When i call show method?

Il Mar 30 Lug 2019, 10:59 Michael Bui <notifications@github.com> ha scritto:

**Comment by MaikuB** [comment]
Assuming that is what you're calling, yes

**Comment by sante85** [comment]
- this is the signature

Future<void> show(int id, String title, String body,
      NotificationDetails notificationDetails,
      {String payload})

how can pass five th param ?

**Comment by MaikuB** [comment]
`payload` is a named parameter so you'll need specify it's name. An example is

```
await flutterLocalNotificationsPlugin.show(
    0, 'plain title', 'plain body', platformChannelSpecifics,
    payload: 'item x');
```
This was taken from the readme and example app that I had mention covers how to pass the payload. A lot of widgets in Flutter have optional, named parameters though so unless you haven't worked on doing the UI before, you've most likely would have use methods with similar signatures. Here's the documentation on optional, named parameters https://dart.dev/guides/language/language-tour#optional-parameters

**Comment by sante85** [comment]
i have tryed, but, i pass payload, notification is not showed, and audio and vibration not working.
please accept pr #277

**Comment by sante85** [comment]
await flutterLocalNotificationsPlugin.show(0, msg["notification"]["title"],
        msg["notification"]["body"], platformChannelSpecifics,
        payload: msg["data"]);

not sound, vibrating and notification is not showed

await flutterLocalNotificationsPlugin.show(0, msg["notification"]["title"],
        msg["notification"]["body"], platformChannelSpecifics);

in OnSelectNotification not pass payload

**Comment by sante85** [comment]
this are

 var androidPlatformChannelSpecifics = new AndroidNotificationDetails(
        'your channel id', 'your channel name', 'your channel description',
        importance: Importance.Max, priority: Priority.High);
    var iOSPlatformChannelSpecifics = new IOSNotificationDetails();
    var platformChannelSpecifics = new NotificationDetails(
        androidPlatformChannelSpecifics, iOSPlatformChannelSpecifics);

**Comment by MaikuB** [comment]
Make sure the object you pass as a payload is a string. The fact that you're not seeing any notification anymore means that an error had occurred and I believe that's the reason why. This is something you'll need to debug and work out

**Comment by sante85** [comment]
ok, but payload parameter can be as Map type instead as String?

**Comment by MaikuB** [comment]
no it can't, which is why I was saying above that you may need to convert what you have. it looks as though you still tried to pass a map
