### ISSUE TITLE
backgroun notification not call onSelectNotification

### ISSUE THREAD

**Issue by sante85** [MaikuB/flutter_local_notifications#281]
**Describe the bug**
If a notification is in status bar, when i click  onSelectNotification is not called

**Expected behavior**
onSelectNotification is called

**Comment by sante85** [comment]
if screen is black, message arrive from firebase, but if i click on notification, onSelectNotification is not called

**Comment by MaikuB** [comment]
Please provide a full sample to reproduce the problem if there is indeed one. If you're using firebase messaging and it's that plugin that is actually displaying the notification then you should be using the callbacks provided by that plugin. There is documentation about what firebase messaging does in their readme https://pub.dev/packages/firebase_messaging
