### ISSUE TITLE
The method 'schedule' was called on null.

### ISSUE THREAD

**Issue by BwesShr** [MaikuB/flutter_local_notifications#282]
Recently started getting this error in my android build. Haven't tried the ios though. 
This is the notification schedule which was working fine until recent update.
`_var androidSpecific = new AndroidNotificationDetails('com.biwesh.alarm',
        'Alarm', 'Notification',
        icon: 'mipmap/ic_launcher',
        largeIcon: 'drawable/alarm',
        playSound: true,
        vibrationPattern: vibrationPattern);
    var iosSpecific = IOSNotificationDetails(sound: "alarm.aiff");
    var platformSpecific = NotificationDetails(androidSpecific, iosSpecific);
    print('alarm scheduled: $scheduledDate');
    _notificationsPlugin.schedule(1, 'test', 'this is a notification testing',
        scheduledDate, platformSpecific,
        androidAllowWhileIdle: true);`
This is the error I m getting...
![Capture](https://user-images.githubusercontent.com/23470402/62229981-97108800-b3e0-11e9-827e-b470551c702d.PNG)

**Comment by MaikuB** [comment]
Without a full sample to reproduce, may be difficult to know what's going. You haven't what version your application use to be on as well

**Comment by BwesShr** [comment]
I was using version ^0.4.4+2. I didnot submit the sample coz I have just copy pasted the same code you have in the example.

**Comment by MaikuB** [comment]
Yep so you're on a fairly old version. From 0.5.0 onwards, the Android app side needs to be migrated to AndroidX. Details on AndroidX and migrating can be found [here](https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility). Should you encounter breaking changes as you migrate I would suggest taking a look at the change log as I document these there

**Comment by BwesShr** [comment]
I am aware of the migration to AndroidX and I have used the AndroidX migration in the project.

**Comment by MaikuB** [comment]
Will need a full sample app that can reproduce this problem then

**Comment by tomosullivan8** [comment]
@BwesShr how did you manage to fix this in the end? I have migrated to AndroidX and have the same issue still.

**Comment by BwesShr** [comment]
Yes, I did it. Just add -keep class com.dexterous.** { *; } to your ProGuard configuration file. I had missed that line in the documentation.

**Comment by tomosullivan8** [comment]
This is what i have in my android/app/build.gradle in the buildTypes;

`useProguard true`
`proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'`

and then in the android/app/proguard-rules.pro i have the following included;

`-keep class com.dexterous.** { *; }`

The error keeps occurring, any idea what I'm doing wrong?

**Comment by tomosullivan8** [comment]
Ignore this, I have fixed it now!

**Comment by MaikuB** [comment]
@tomosullivan8 would you be able to share what the solution was in case others run into the same problem?

**Comment by tomosullivan8** [comment]
School boy error - hadn't initialised the FlutterLocalNotificationsPlugin properly 

`FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin = FlutterLocalNotificationsPlugin();`

I had only the `FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin;` included before putting it through the initState which I forgot to do.
