### ISSUE TITLE
How to get PUSH notification on android with PAYLOAD triggered on 'selectNotification' method?

### ISSUE THREAD

**Issue by Tristan-gu** [MaikuB/flutter_local_notifications#288]
Hi,

Thank you very much for your work, I really love your plugin.
I'm trying to manage local and push notification at the same time.

For push notification, I'm using only [plain_notification](https://github.com/kikuchy/plain_notification_token) (in order to get the token.)

I don't use Flutter firebase SDK for managing push notificaiton.
I want to get push notification details (payload) with your plugin when I click on notification.

On iOS, no problem, I push a notification with [pushNotification](https://github.com/onmyway133/PushNotifications), and add "payload" attribute to the notification, so, I get it on 'onSelectNotification' method.

But, on Android, I'm stopped by this code when I send a push notification:
![image](https://user-images.githubusercontent.com/41323690/62555533-68c4f980-b873-11e9-9610-0a0c82db1b69.png)

The test returns "false", this is logic on the code but is it possible to open this method to call "selectNotification" method even if the action content is not "SELECT_NOTIFICATION." ?

Like this, your plugin would be more open to various notifications ?

Thank you

**Comment by MaikuB** [comment]
Sorry but I'm having trouble understanding what steps you took. That logic will only evaluate to true if you show a local notification via this plugin and tap on the notification. That it's false from what you've explained would suggest that perhaps you didn't show a local notification. If you're having push notifications shown through other means then you'll need to look at how that should be handled as that's not the responsibility of this plugin
