### ISSUE TITLE
Notifications worked in development but not working in the released version on the PlayStore

### ISSUE THREAD

**Issue by richardbonneau** [MaikuB/flutter_local_notifications#293]
Title is self-explanatory. I'm not sure where to go from there. Do you need to enable any permission through the android manifest in the code? Do you need to enable something on the google play console?

I have no clue. Any pointers?

**Comment by MaikuB** [comment]
Try connecting your phone to your PC and check the logcat output whilst running the app. The permissions needed are in the readme. Also worth checking if you have proguard turned on and have added the configuration details required for it that is in the readme as well

**Comment by richardbonneau** [comment]
Hey Maiku, thanks for the quick response. I did not enable ProGuard. I am now trying to enable permission for Internet and see if that's required for push notifications. I will see if I can get anything from the logcat.

**Comment by richardbonneau** [comment]
After Fiddling around here's what I found : 

The code never gets to the `show` function on line 114 of flutter_local_notifications.dart. Here's where I call it : `Future _showNotifications(
  FlutterLocalNotificationsPlugin notifications, {
  @required String title,
  @required String body,
  @required NotificationDetails type,
}) =>
    notifications.show(0, title, body, type);`

and the error I get in the logcat : `E/flutter (22383): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference, null)`

I've tried a lot of things without success.

**Comment by richardbonneau** [comment]
I found the solution and will post it tomorrow. Thank you Maiku.

**Comment by MaikuB** [comment]
Did you have an update?

**Comment by martyniak** [comment]
I have similar issue with my app, quick workaround was to enable "Autostart" option for the app from the Settings.

**Comment by MaikuB** [comment]
closing since there's been no more further updates
