### ISSUE TITLE
Notification routing does not work properly if app is not running on IOS

### ISSUE THREAD

**Issue by Journerist** [MaikuB/flutter_local_notifications#295]
**Describe the bug**
Routing does not work if app is not running on IOS

**To Reproduce**
If applicable, steps to reproduce the behavior:
1. Start example app (or other similar app where routing is properly setup)
2. Press button "Repeat notification every minute"
3. Close and exit the app, it's important to really close the app
4. Wait for a notification
5. Click on the notifcation
6. You will see the first screen, not the second

**Expected behavior**
Instead of the first screen you should see the second screen. This works if the app is already running (open & in background).

**Sample code to reproduce the problem**
Check it in the example of this repository.

**Comment by MaikuB** [comment]
Thanks for reporting that, looks like the PR I've referenced broke that behaviour will address this soon.

**Comment by MaikuB** [comment]
This should hopefully be fixed now
