### ISSUE TITLE
how to send image along with text in notification??

### ISSUE THREAD

**Issue by praveendp526** [MaikuB/flutter_local_notifications#30]

**Comment by MaikuB** [comment]
Short answer is you can't with the plugin. Longer answer is I'd kindly that you consult the documentation as you would've seen that it's not possible. There's also #26 on the roadmap that may or may be of interest to you, at least on Android. It would've helped if you had specified the platforms you're targeting. In the case that you're targeting both iOS and Android (which is highly likely given you're looking at Flutter), it's quite likely that you'll need to implement it yourself via native code through the use of custom layout files on Android and custom view controllers on iOS. That way you can get the notifications to look as similar to each other as possible. 

Note that this plugin just aims to solve some of the more common use cases. As far as I know, plugins for other cross platform app development frameworks don't offer the functionality you seem to be after either but you're welcome to submit a PR if you've come up with a solution that would be of use to the rest of the community :)
