### ISSUE TITLE
Does Android app need to be running for notification to fire?

### ISSUE THREAD

**Issue by aronnelson** [MaikuB/flutter_local_notifications#300]
**Describe the bug**
I set a notification to fire 8 hours later. However the notification never delivers.
I am assuming Android kills the app at some point during the 8 hours. Shorter durations work fine. 
This is on a Pixel 3a with Android 10 beta.

**To Reproduce**
I use the example code with:
DateTime scheduledNotificationDateTime =
        new DateTime.now().add(new Duration(minutes: minsRemaining));

minsRemaining is 8*60.
I have verified scheduledNotificationDateTime is correct.

await flutterLocalNotificationsPlugin.schedule(
      0,
      'Alert - done',
      'Done!',
      scheduledNotificationDateTime,
      platformChannelSpecifics,
    );

var androidPlatformChannelSpecifics = new AndroidNotificationDetails(
        'your other channel id',
        'your other channel name',
        'your other channel description',
        importance: Importance.Max,
        priority: Priority.High,
        ticker: 'ticker');

**Expected behavior**
It should fire at the correct time.

**Comment by MaikuB** [comment]
no the app doesn't need to be running. have checked that trying to show a notification immediately works fine (i.e. by calling the `show` method)? also do have you tried running the example app to see if you run into the same issue? you should be able to modify the times in the code to see if you observe the same behaviour
