### ISSUE TITLE
How to Implement Big Picture but the image is online ?

### ISSUE THREAD

**Issue by riskikukuh** [MaikuB/flutter_local_notifications#305]
I want to show Notification with big picture style, and the picture is online. But i can't solve that.

**Comment by MaikuB** [comment]
It needs to be downloaded onto the device's storage. Take a look at sample code in the example app as it covers this particular scenario

**Comment by riskikukuh** [comment]
I've some way to implement Online Big Picture. But i don't know this way is correct or not. I'm using Volley request for get image. In my device it's working well

**Comment by MaikuB** [comment]
I don't have experience with Volley to comment on that. My understanding is that it's an Android library so not sure why you're using that with a Flutter application. How you get it on the device and get the file path is something you'll need to solve for your context and the example app has code that demonstrates one way.

As your issue more with getting your app to work as opposed to having found an issue with the plugin, I would suggest you use other [community resources](https://flutter.dev/community) for more help

**Comment by MaikuB** [comment]
Also to provide a general overview of what needs to be done, in case you're having trouble following the example code

1. download the image
2. save to file storage
3. get the path of where the image was saved
4. pass that to the notification plugin as per https://github.com/MaikuB/flutter_local_notifications/blob/1a42855697b062ee8db85d5008a63caefe2528f1/example/lib/main.dart#L303. Make sure the source of the bitmap is specified as `BitmapSource.FilePath`

Steps 1-3 are what you'll need to figure out

**Comment by riskikukuh** [comment]
If i use that way, will the file i downloaded before show in gallery app ?

**Comment by MaikuB** [comment]
No

**Comment by MaikuB** [comment]
Also I'd suggest you run the example app included in the repository and take a closer look at the code. Closing this issue now as there isn't an issue in the plugin to be resolved here

**Comment by riskikukuh** [comment]
Thanks for your answer.
