### ISSUE TITLE
Feature request: Notification showing a Countdown timer

### ISSUE THREAD

**Issue by dpedrinha** [MaikuB/flutter_local_notifications#306]
Would be very nice to have a notification showing a countdown timer like the new android system does.

If you start a the system countdown timer now it places a sticky notification with the countdown.

So it would be a notification that takes a Duration and shows a countdown timer once it is started. When it ends, it rings and vibrate and start counting forwards in red so the user knows for how long the timer have been set off. And of course, by this point, the notification should have a way to be dismissed.

Cheers and great job with this plugin.

**Comment by MaikuB** [comment]
Thanks for the kind words. What you're asking for is very specific to an app IMO (I believe this will only work on Android as well) and isn't something I intend to work. As such I'll be closing this I'd suggest you look at using platform channels to implement this yourself for your app

**Comment by ghenry** [comment]
I was looking to do this too like MS Teams does in their Android app. Android specific I think?
