### ISSUE TITLE
scheduled notifications cannot be pushed in android P

### ISSUE THREAD

**Issue by btbj** [MaikuB/flutter_local_notifications#308]
getting error message: 
```
Accessing hidden field Ljava/nio/Buffer;->address:J (light greylist, reflection)
```
all the notifications gose in to pending list, but not getting pushed

**Comment by MaikuB** [comment]
There's an example app in the repository. Check to see if it works for you, otherwise you'll need to provide a full app that reproduced the problem. I've run this on Android P and don't run into issues

**Comment by btbj** [comment]
@MaikuB sorry, my fault.

**Comment by btbj** [comment]
@MaikuB sorry, it's my fault.
i forgot to apply Android Integration in dev branch. _(:з」∠)_
