### ISSUE TITLE
Is it possible to tap on/dismiss the notification without opening the app?

### ISSUE THREAD

**Issue by dpedrinha** [MaikuB/flutter_local_notifications#316]
I just need to show a notification, I don't need the app to be opened when the user taps on it.
Is it possible?
I tried to initialize the plugin without onSelectNotification but it still opens the app.

**Comment by MaikuB** [comment]
No it's not. If I'm not mistaken, the only thing that is also allowed on iOS is for it to launch the app. Ignoring what's allowed, that experience may be confusing to users since that's not a default as dismissing is typically done via swiping or an action button
