### ISSUE TITLE
Not fired notifications in result of pendingNotificationRequests()

### ISSUE THREAD

**Issue by eugvb** [MaikuB/flutter_local_notifications#317]
After this issue #307
I have seriously improved my code, so I don't cancel all notifies, I load pending requests with `pendingNotificationRequests()`, then compare results with new list and schedule only new notifies.
This helps to decrease amount of new notifications to be scheduled, but I've ran into a new problem: old notifies doesn't work.
I will describe in more detail.
For example i have this list of notifies

1. Notify 1 after 5 min
2. Notify 2 after 10 min
3. Notify 3 after 30min
4. Notify 4 tomorrow at 9.00
5. Notify 5 tomorrow at 12.00

So, notifies 1-3 is "hot", they have changed several times during the day.
Notifies 4-5 is "cold" and doesn't change during this day.

When tomorrow comes notifications 4-5 doesn't work. I do `pendingNotificationRequests()` at 9.15 and see Notify 4 in this list, I don't know what it waiting for.

Briefly about the problem: If I periodicaly update list of scheduled notifies, not updated notifications stop working.

**Comment by MaikuB** [comment]
Please provide a full sample app that reproduces the problem you're having. Note that this plugin is open source so you can debug to find out what's going on

**Comment by MaikuB** [comment]
Closing due to lack of response
