### ISSUE TITLE
Icon not working on Android

### ISSUE THREAD

**Issue by zbaylin** [MaikuB/flutter_local_notifications#32]
Hello. I am fairly sure I am just misunderstanding the syntax, but I cannot get Notifications to show on Android.

This is my Android initialization settings:
```
    InitializationSettingsAndroid initializationSettingsAndroid = new InitializationSettingsAndroid('app_icon');

```

And when I schedule a notification, I get the following error
```
Caused by: java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(channel=DEFAULT pri=2 contentView=null vibrate=null sound=null defaults=0x0 flags=0x0 color=0x00000000 vis=PRIVATE)
```

No matter what I put for `'app_icon'`, such as a path to an image, "app_icon" itself, i still get this error. Any help would be greatly appreciated.

**Comment by MaikuB** [comment]
I assume you made sure to call the initialize method? If you specified 'app_icon' as the argument to the constructor then you need to make sure that there's a corresponding file in your Android head project as a drawable resource

**Comment by Galahand** [comment]
i had the same problem pointed out here, to fix i just changed from 'app_icon' to 'mipmap/ic_launcher' (it has an @ at the beggining of mipmap/ic_launcher), it is the icon specified in AndroidManifest.xml

**Comment by MaikuB** [comment]
Closing due to lack of response and the code at [this repository](https://github.com/zbaylin/bibliotech) appears to be ok

**Comment by matejthetree** [comment]
I have the same problem. followed the readme, but didnt see how to set up the icon in the readme.

**Comment by matejthetree** [comment]
E/MethodChannel#dexterous.com/flutter/local_notifications(11676): java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(pri=0 contentView=null vibrate=null sound=content://settings/system/notification_sound defaults=0x0 flags=0x10 color=0x00000000 vis=PRIVATE)

**Comment by matejthetree** [comment]
solved it as well by using 'mipmap/ic_launcher'

**Comment by matejthetree** [comment]
thank you

**Comment by ThinkDigitalRepair** [comment]
Yeah, I had to search and find what Android head project means. Many of us didn't come from Android and never have to reference this file. Thanks for the work. it would be nice if the docs were more specific about those details, since a search in the repo for "app_icon" only yielded the dart code.

**Comment by MaikuB** [comment]
GitHub's search is designed to search code not files. The readme calls out checking the Android integration section about adding the icon, which in turn has note about notes about adding it as a drawable resource and links to official Android documentation on the Android side on where these files go and what sizes they should be. I'm aware not many people come from an Android background and I don't really either so links to the official docs as that's what Android people would follow (and what I followed).

**Comment by ThinkDigitalRepair** [comment]
Thank you for the links. It's just that it makes it a higher learning curve, since, at least speaking for myself, I feel like I need to decide what to pay attention to and what to ignore when it comes to reading docs for Android, since not all things apply with Flutter. I'm more comfortable reading things in docs from a Flutter package because I know it's already been tested and applies for Flutter. Of course, it shouldn't be that way, but I think this is many Flutter dev's experiences with reading documentation

**Comment by MaikuB** [comment]
I'm not sure there's a way around it given it involves dealing with the native platform side of things and the official docs would get maintained e.g. if they add support for more resolutions. Two of the links are already specific to notification icons and the other is around the Android project structure so developers know the structure of what icons go. You're welcome to submit a PR on what you think would help make it clearer

**Comment by ThinkDigitalRepair** [comment]
That’s a good point. If I have the time, I’ll submit one. Thanks!

**Comment by adrianvintu** [comment]
HI @MaikuB, can I add a 

```
largeIcon: iconPath,
largeIconBitmapSource: BitmapSource.FilePath,
```
where the icon is stored in 
```flutter_test_project\assets\images\someimage.jpg```

The above is not the android root, the "assets" folder is on the sale level as "android" and "lib", right under "flutter_test_project".

If this is possible, what is the correct path?

If not, should I make a copy of the file to the internal memory and point the app there?

**Comment by MaikuB** [comment]
@adrianvintu i don't believe so or you would need to find a way to resolve the asset to an Android URI (possibly through what's mentioned here). I don't see the benefit of doing it though, particularly in your scenario. If you kept it as an asset, I would suspect the size of your app on iOS would be bigger even though the asset is only used on Android. I would recommend adding it as a drawable resource like the normal/small icon. The file path option was really more for if the app has downloaded the image. Refer to the example app if you haven't already

**Comment by adrianvintu** [comment]
Thank you @MaikuB . 

> I would recommend adding it as a drawable resource like the normal/small 

This will duplicate my assets, since they are also used by the Flutter code.

I think I will go use the workaround mentioned:

>should I make a copy of the file to the internal memory and point the app to the path there?

**Comment by MaikuB** [comment]
Noticed I forgot to add a link to my reply. I'd suggest taking a look at the API at https://flutter.dev/docs/development/ui/assets-and-images#android as it might solve the problem though I haven't had a chance to check

**Comment by eastrd** [comment]
Hi, sorry to reply to an old issue.

I have tried to directly use "mipmap/ic_launcher" and "mipmap-hdpi/ic_launcher".

I have also tried to add the image asset as `notification icons` in Android Studio, and use the URI without `.png` at the end.
But all the above approaches ended up with `INVALID_ICON`.

I'm new to Android, I have also checked the example repo, and I cannot see any difference in the XML configuration files. 


Am I missing something here?

**Comment by MaikuB** [comment]
I'd avoid using mipmap. Some members of the community have used it with success but best practices under to put it under resources/drawable

**Comment by danarteaga** [comment]
To be explicit, as this thread did an incomplete job of actually answering the question in full, 'app_icon' within the flutter_local_notifications package documentation refers to 'app_icon.png', which is located in 'example/android/app/src/main/res/drawable' within the source code. To specify your own custom icon, save an image in your own android/app/src/main/res/drawable folder. Of note, app_icon.png is 36x36 pixels in size, and has a transparent background.

**Comment by vfiruz97** [comment]
I fixed it by renaming icon file from **ic_notification**.png to **app_icon**.png in the res/drawable/
