### ISSUE TITLE
Show a weekly notification on specific day and time

### ISSUE THREAD

**Issue by MahdiPishguy** [MaikuB/flutter_local_notifications#321]
Hi, i have question about, this feature can be work when app state is close? for example when we set it and we don't open application. notification can be shown in specific time?

**Comment by MaikuB** [comment]
Yes it should work. I believe you should be able to more quickly confirm this by setting the day and time such that the first notification is triggered minutes from you, say, hit a button

**Comment by MahdiPishguy** [comment]
@MaikuB 

thanks. could you describe about

`'your channel id', 'your channel name', 'your channel description',`

in this code?

```dart
var androidPlatformChannelSpecifics = AndroidNotificationDetails(
'your channel id', 'your channel name', 'your channel description',
```

**Comment by MaikuB** [comment]
The channel details refer to Android notification channels. Refer to the docs at https://developer.android.com/training/notify-user/channels for me details
