### ISSUE TITLE
FlutterHeadlessDartRunner has been explicitly marked deprecated

### ISSUE THREAD

**Issue by delef** [MaikuB/flutter_local_notifications#323]
Hi! Thank you for your work on this project.

After update to Flutter v1.9.1 and Xcode 11.0, I began to see these warnings:
<img width="272" alt="Screenshot 2019-09-22 at 00 21 01" src="https://user-images.githubusercontent.com/2103263/65379387-d1572100-dccf-11e9-8a66-3f63364cc49b.png">

**Comment by MaikuB** [comment]
Thanks. It's been noted. Will be remove in next release

**Comment by MaikuB** [comment]
Actually I just took a look and this was already removed. What version of the plugin are you using? Perhaps you're on an older version
