### ISSUE TITLE
Swipe to dismiss - help wanted

### ISSUE THREAD

**Issue by MitchellQ** [MaikuB/flutter_local_notifications#328]
I have set this up using the basic set up for testing purposes (except its in its own class as opposed to a widget) and it works fine except for swiping to dismiss neither the heads up nor the system tray notifications work. Im pretty sure that I have missed a setting somewhere but it would be great if you could help me out.

Thanks in advance.

**Comment by MaikuB** [comment]
> it works fine except for swiping to dismiss neither the heads up nor the system tray notifications work

Sorry i'm a bit confused on what's not working for you. Also what device are you testing this on? If you are you able to a link to a repository that has a basic example to demonstrate the problem then that would be great. Note that the repository also has an example app. Worth running it to see if you have the same issue in case you haven't done so already. Requires cloning the repository though to ensure that all the icons etc have been configured correctly

**Comment by MaikuB** [comment]
Another thing is if you're running this on Android and have set [this property](https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/AndroidNotificationDetails/ongoing.html) to true then this results in a sticky notification that can't be dismissed

**Comment by MitchellQ** [comment]
That was my problem, I misunderstood what the ongoing flag meant - thanks

**Comment by MaikuB** [comment]
No worries. Note that the naming was made to be consistent with the Android Notification APIs
