### ISSUE TITLE
ios自定义通知声音不起作用

### ISSUE THREAD

**Issue by danyunLu** [MaikuB/flutter_local_notifications#329]
请问为什么iOS的自定义通知声音不起作用，安卓的可以

**Comment by MaikuB** [comment]
Could you post your question in English?

**Comment by salah-rashad** [comment]
_Translation depending on Google translate:_

> Why does iOS custom notification sound not work, while Android works?

**Comment by MaikuB** [comment]
@salah-rashad thanks I'm aware that Google translate can be used but doesn't help have a proper conversation and translations may not be accurate. If developers can't post in English then IMO it would be better to ask communities that speak the same language. It appears to be written in Chinese and I do believe there's a fairly big Chinese Flutter community that there's a Chinese version of the Flutter website.

@danyunLu: assuming the translation to your question is accurate, custom sound does work on iOS and is demonstrated in the example app. If it's not working then perhaps the sound is not in the right format or hasn't been added to the project properly. Going to close this issue as a result. If you have a problem, I'd kindly ask to reply in English or visit a Chinese developer community site to get further assistance
