### ISSUE TITLE
Rich Notifications

### ISSUE THREAD

**Issue by marco2250** [MaikuB/flutter_local_notifications#330]
This is my first idea in github...

Is it possible to have the ability of Rich Notifications, like playing youtube videos within the notification?

Below is an ios example
https://medium.com/@tibinmutholy/ios-rich-notifications-and-how-to-play-a-youtube-video-within-a-notification-867ee6184b44

(duknow if this is possible in Android...)

Thank you for great work!

**Comment by MaikuB** [comment]
It's not possible with the plugin as this is something devs will need to build out in their own app. Reason being is that rich notifications rely on building native views i.e. XML layout files on Android and a view controller on iOS
