### ISSUE TITLE
Firebase Messaging does not call onResume and onLaunch when sending data including "notification" when app is background or terminated.

### ISSUE THREAD

**Issue by thieplehuu** [MaikuB/flutter_local_notifications#332]
I use nodejs firebase-admin to send notifications to Android devices
I have configured flutter_local_notification as instructed in
https://pub.dev/packages/firebase_messaging#optionally-handle-background-messages

When I send the notification from node js with payload:
              var payload = {
                  "data": {
                    "Nick": "Mario",
                    "body": "great match!",
                    "Room": "PortugalVSDenmark",
                    "screen": "ChannelScreen",
                  },
                };
then firebase_messaging trigger onBackgroundMessage and flutter_local_notification show the notification success, but when I click on firebase_messaging does not trigger the onResume and onLaunch functions.
When I send the notification from node js with payload:
                var payload = {
                  "data": {
                    "Nick": "Mario",
                    "body": "great match!",
                    "Room": "PortugalVSDenmark",
                    "screen": "ChannelScreen",
                  },
                  "notification": {
                    "clickAction": "FLUTTER_NOTIFICATION_CLICK"
                  }
                };
then the notification appears in the device's navigation bar and firebase_messaging's onResume  was  trigger when I click on the notificaition but flutter_local_notification does not trigger onBackgroundMessage when the app is in the background.

Please help me! thank alot!

Sorry because my English is not good

**Comment by luckycreationsindia** [comment]
Hope you added this Intent-filter in AndroidManifest.xml

```
<intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK" />
                <category android:name="android.intent.category.DEFAULT" />
</intent-filter>
```

And click_action must be inside data not notification and make sure you use "click_action" and not "clickAction"
