### ISSUE TITLE
Firebase Messaging does not call onResume and onLaunch when sending data including "notifications" when app is background or terminated

### ISSUE THREAD

**Issue by thieplehuu** [MaikuB/flutter_local_notifications#333]
I use nodejs firebase-admin to send notifications to Android devices
I have configured flutter_local_notification as instructed in
https://pub.dev/packages/firebase_messaging#optionally-handle-background-messages

When I send the notification from node js with payload:
              var payload = {
                  "data": {
                    "Nick": "Mario",
                    "body": "great match!",
                    "Room": "PortugalVSDenmark",
                    "screen": "ChannelScreen",
                  },
                };
then flutter_local_notification trigger onBackgroundMessage and displays the success message, but when I click on firebase_messaging does not trigger the onResume and onLaunch functions.
When I send the notification from node js with payload:
                var payload = {
                  "data": {
                    "Nick": "Mario",
                    "body": "great match!",
                    "Room": "PortugalVSDenmark",
                    "screen": "ChannelScreen",
                  },
                  "notification": {
                     "click_action": "FLUTTER_NOTIFICATION_CLICK" //or "clickAction": 
                  }
                };
then the notification appears in the device's navigation bar and firebase_messaging's onResume  was  trigger when I click on the notificaition but flutter_local_notification does not trigger onBackgroundMessage when the app is in the background

Please help me, Thank so much.

sorry because my English not good

**Comment by MaikuB** [comment]
You are creating the issue on the wrong repository since your problem is related to using the `firebase_messaging`
