### ISSUE TITLE
when you add rich notificatiom ios

### ISSUE THREAD

**Issue by sante85** [MaikuB/flutter_local_notifications#335]
Hi, 

this link describe how to create  rich notification.

https://stackoverflow.com/questions/37839171/how-to-display-image-in-ios-push-notification

it possible to implement, or a PR?

Best regards

**Comment by MaikuB** [comment]
This is something you need to do on your own and was asked recently in #330

**Comment by sante85** [comment]
#330 Is closed because you Say that Is not possibile, but Is possibile
implement.

I not understand because you have closed this.

Il mar 1 ott 2019, 11:48 Michael Bui <notifications@github.com> ha scritto:

**Comment by MaikuB** [comment]
> #330 Is closed because you Say that Is not possibile, but Is possibile
implement.

The context here is important, that the functionality is availability (which is what you're referring to) doesn't meant it can be done via the plugin.

> I not understand because you have closed this.

It was explained in #330 so I'll quote it below for convenience

> rich notifications rely on building native views i.e. XML layout files on Android and a view controller on iOS

The UI for rich notifications is a lot more customised and are done per app. As such only your app knows what kind of logic it needs to happen e.g. how many buttons there are, their IDs, what tapping on them should do etc. If you still don't understand then I can only suggest that you spend more time understanding how building user interfaces in Android and iOS work, as well as how rich notifications make use of them etc

**Comment by sante85** [comment]
But you can implement a standard minimal customizable view

Il mar 1 ott 2019, 12:18 Michael Bui <notifications@github.com> ha scritto:

**Comment by MaikuB** [comment]
If you are suggesting that a standard view is provided then that negates the benefit of being able to have a rich notification. If you're after something "standard" as you say then you are welcome to implement this yourself

**Comment by sante85** [comment]
In this case i must create a custom plugin that import locale notifications?

Il mar 1 ott 2019, 12:36 Michael Bui <notifications@github.com> ha scritto:

**Comment by MaikuB** [comment]
I don't know what you mean, particularly around the importing local notifications but creating a plugin isn't necessary. I'd suggest you read about [platform channels](https://flutter.dev/docs/development/platform-integration/platform-channels)
