### ISSUE TITLE
The app crash after scheduling notification on iOS

### ISSUE THREAD

**Issue by SHRJamal** [MaikuB/flutter_local_notifications#336]
Hi!
The app crash and the error can't be caught inside try-catch 

<AppName>[20646:117294] -[NSNull un_stringWithMaxLength:]: unrecognized selector sent to instance 0x1082bb000
2019-10-01 15:51:55.294854+0100 <AppName>[20646:117294] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull un_stringWithMaxLength:]: unrecognized selector sent to instance 0x1082bb000'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000108031bde __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x0000000107e9fb20 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000108052704 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00000001080367bc ___forwarding___ + 1436
	4   CoreFoundation                      0x00000001080386c8 _CF_forwarding_prep_0 + 120
	5   UserNotifications                   0x000000011600dd19 -[UNNotificationContent encodeWithCoder:] + 248
	6   Foundation                          0x0000000106336ac3 -[NSXPCEncoder _encodeObject:] + 474
	7   UserNotifications                   0x000000011600154f -[UNNotificationRequest encodeWithCoder:] + 93
	8   Foundation                          0x0000000106336ac3 -[NSXPCEncoder _encodeObject:] + 474
	9   Foundation                          0x0000000106250b8b _NSXPCSerializationAddInvocationWithOnlyObjectArgumentsArray + 95
	10  Foundation                          0x0000000106336f93 -[NSXPCEncoder _encodeInvocationObjectArgumentsOnly:count:typeString:selector:isReply:into:] + 188
	11  Foundation                          0x00000001063343ef -[NSXPCConnection _sendInvocation:orArguments:count:methodSignature:selector:withProxy:] + 1998
	12  Foundation                          0x0000000106333ae4 -[NSXPCConnection _sendSelector:withProxy:arg1:arg2:arg3:] + 133
	13  Foundation                          0x0000000106344589 _NSXPCDistantObjectSimpleMessageSend3 + 44
	14  UserNotifications                   0x0000000116016172 __104-[UNUserNotificationServiceConnection addNotificationRequest:forBundleIdentifier:withCompletionHandler:]_block_invoke + 295
	15  libdispatch.dylib                   0x000000010975ed64 _dispatch_client_callout + 8
	16  libdispatch.dylib                   0x000000010976d9f5 _dispatch_lane_barrier_sync_invoke_and_complete + 132
	17  UserNotifications                   0x0000000116015fb9 -[UNUserNotificationServiceConnection addNotificationRequest:forBundleIdentifier:withCompletionHandler:] + 426
	18  UserNotifications                   0x00000001160129b2 -[UNUserNotificationCenter addNotificationRequest:withCompletionHandler:] + 106
	19  flutter_local_notifications         0x0000000106fa81a6 -[FlutterLocalNotificationsPlugin showUserNotification:] + 3078
	20  flutter_local_notifications         0x0000000106fa6531 -[FlutterLocalNotificationsPlugin showNotification:result:] + 4609
	21  flutter_local_notifications         0x0000000106fa6dfe -[FlutterLocalNotificationsPlugin handleMethodCall:result:] + 862
	22  Flutter                             0x00000001041134fd __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 104
	23  Flutter                             0x00000001040acec0 _ZNK7flutter21PlatformMessageRouter21HandlePlatformMessageEN3fml6RefPtrINS_15PlatformMessageEEE + 166
	24  Flutter                             0x00000001040b0780 _ZN7flutter15PlatformViewIOS21HandlePlatformMessageEN3fml6RefPtrINS_15PlatformMessageEEE + 38
	25  Flutter                             0x000000010410ddb3 _ZNSt3__110__function6__funcIZN7flutter5Shell29OnEngineHandlePlatformMessageEN3fml6RefPtrINS2_15PlatformMessageEEEE4$_31NS_9allocatorIS8_EEFvvEEclEv + 57
	26  Flutter                             0x00000001040bf3f1 _ZN3fml15MessageLoopImpl10FlushTasksENS_9FlushTypeE + 123
	27  Flutter                             0x00000001040c4742 _ZN3fml17MessageLoopDarwin11OnTimerFireEP16__CFRunLoopTimerPS0_ + 26
	28  CoreFoundation                      0x0000000107f951e4 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
	29  CoreFoundation                      0x0000000107f94ed2 __CFRunLoopDoTimer + 1026
	30  CoreFoundation                      0x0000000107f9452a __CFRunLoopDoTimers + 266
	31  CoreFoundation                      0x0000000107f8f29e __CFRunLoopRun + 2238
	32  CoreFoundation                      0x0000000107f8e6b6 CFRunLoopRunSpecific + 438
	33  GraphicsServices                    0x000000010d79cbb0 GSEventRunModal + 65
	34  UIKitCore                           0x00000001115f1a67 UIApplicationMain + 1621
	35  HG Guide                            0x00000001021ba488 main + 72
	36  libdyld.dylib                       0x00000001097e6cf5 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by MaikuB** [comment]
Please provide more details, like the version of the plugin you're using, device, OS version and ideally, small sample app that can reproduce the issue. The stack trace would seem to imply invalid arguments were passed.

**Comment by MaikuB** [comment]
Please make sure to also to include the output of `flutter doctor -v`

**Comment by SHRJamal** [comment]
the schedule function:
`flutterLocalNotificationsPlugin.schedule(
        event.id,
        "${event.title} happening today. ",
        event.description,
        event.date.subtract(Duration(hours: 2)),
        NotificationDetails(
          AndroidNotificationDetails(
            event.id,
            event.title,
            event.description,
          ),
          IOSNotificationDetails(),
        ),
      );`

When I do 'flutterLocalNotificationsPlugin.show' or other functions they work, but schedule crash 
I get the problem only on iOS, it works fine on Android

flutter doctor -v:

Flutter (Channel beta, v1.9.1+hotfix.4, on Mac OS X 10.14.4 18E226, locale en-MA)
    • Flutter version 1.9.1+hotfix.4 at /Users/shrjamal/Developement/flutter
    • Framework revision cc949a8e8b (4 days ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/shrjamal/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/shrjamal/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.8.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.0

[✓] VS Code (version 1.38.1)
    • VS Code at /Users/shrjamal/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.0

[✓] Connected device (2 available)
    • Nokia 2   • E1MGAP27C1721339                     • android-arm • Android 7.1.1 (API 25)
    • iPhone Xʀ • F44284FE-A279-4220-83B5-F25F5B298FE7 • ios         •
      com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

**Comment by MaikuB** [comment]
The only scenario I can think of is one of the parameters you passed through is null. Have you debugged to see if either the notification title or body that you're specifying is null?

**Comment by SHRJamal** [comment]
@MaikuB  you are right, thanks.
the problem because the subtitle is null.
The thing is that on Android its work even if it's null, but iOS crash the app and no way to catch error.

**Comment by MaikuB** [comment]
@SHRJamal there is indeed a bug here so thanks for reporting this. Will get a fix out shortly

**Comment by MaikuB** [comment]
Try out version 0.8.4 that I've pushed out
