### ISSUE TITLE
Problem with Local notification when app terminate only IOS

### ISSUE THREAD

**Issue by rodrigorahman** [MaikuB/flutter_local_notifications#340]
My App is not showing notification when the app is closed, but it only happens on iOS.  I tried several ways, the app receives notifications but only displays when I open the app.  would it be some configuration or is it really a bug?

**Comment by MaikuB** [comment]
Please provide more details. Sounds vague to me and don't know what kind of code you're writing to show notifications

**Comment by griks-lab** [comment]
Sorry,

theoretically i implemented according to the documentation, so much so that when i open the app all the notifications i received are presented.

Below is the code snippet with the implementation:
```
FlutterLocalNotificationsPlugin _flutterLocalNotificationsPlugin = new FlutterLocalNotificationsPlugin();

var initializationSettingsAndroid = new AndroidInitializationSettings('app_icon');
    var initializationSettingsIOS = IOSInitializationSettings(onDidReceiveLocalNotification: onDidReceiveLocalNotification);
    var initializationSettings = InitializationSettings(initializationSettingsAndroid, initializationSettingsIOS);

_firebaseMessaging.requestNotificationPermissions();
    _firebaseMessaging.configure(
      onMessage: firebaseMessagingOnMessage,
      onResume: firebaseMessagingOnMessage,
      onLaunch: firebaseMessagingOnLaunch,
    );

    _flutterLocalNotificationsPlugin.initialize(initializationSettings, onSelectNotification: onSelectNotification);
        var iOSPlatformChannelSpecifics = IOSNotificationDetails(presentAlert: true, presentBadge: true, presentSound: true);
        var platformChannelSpecifics = NotificationDetails(
            androidPlatformChannelSpecifics , iOSPlatformChannelSpecifics);

          await _flutterLocalNotificationsPlugin.show(
              localNotification, title, message, platformChannelSpecifics,
              payload: payload);
        }

```

**Comment by MaikuB** [comment]
I see that you're using firebase messaging with this plugin. There's a known issue around using both plugins together that's mentioned in the readme. Not saying it's the solution but if you removed the firebase messaging plugin, you should see it working

**Comment by luckycreationsindia** [comment]
> I see that you're using firebase messaging with this plugin. There's a known issue around using both plugins together that's mentioned in the readme. Not saying it's the solution but if you removed the firebase messaging plugin, you should see it working

Any possible way to use both together?

**Comment by MaikuB** [comment]
You can but right now you'd have issues with the callbacks and there's an existing issue about this already. See https://github.com/MaikuB/flutter_local_notifications/issues/111

**Comment by MaikuB** [comment]
Closing this as it looks like it's potentially due to a known issue where there are conflicts when used with firebase messaging, which I can't do much about at the moment and there's already an existing issue on this
