### ISSUE TITLE
call functions on receive a notification - Help request

### ISSUE THREAD

**Issue by salah-rashad** [MaikuB/flutter_local_notifications#341]
Hi, 
First thing first I want to thank you for this package it really helped me a lot.

Now i'm using scheduled notifications in my app and I want to make it do this on receive a notification (**Android & iOS**):

- Get current notification id.
- Call a function.

Is there's any way to make that happen?
Thank you, have a nice day!

**Comment by MaikuB** [comment]
Thanks, glad to hear that it's helped you. It's not possible to make this happen at the moment (in fact I tried to before) as there are some limitations on the Flutter side. If your use case allows for it, you may need to write your own Android and iOS code to run code when a notification is displayed

**Comment by jaripekkala** [comment]
Hi @MaikuB, what are the limitations (on the Flutter side) that is preventing implementing this feature?

**Comment by MaikuB** [comment]
Background execution. There are existing open issues on this repo that are blocked for the same reason and one is about a callback when a notification is shown as one. I created an issue in the Flutter repo [here](https://github.com/flutter/flutter/issues/23904)
