### ISSUE TITLE
Conflicto con cloud_firestore

### ISSUE THREAD

**Issue by Juancito1984** [MaikuB/flutter_local_notifications#342]
Al agregar el paquete de cloud_firestore estoy recibiendo el siguiente error

D8: Program type already present: android.support.v4.os.ResultReceiver$1

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.

y la aplicación no compila.

**Comment by MaikuB** [comment]
I'd kindly ask that you post issues you have in English. If you can't then please use a community forum/chat (e.g. slack workspace) that speaks your language. If you search the error you've shown, you should see that there have been reports of these before 

https://github.com/MaikuB/flutter_local_notifications/search?q=app%3AtransformDexArchiveWithExternalLibsDexMergerForDebug&type=Issues

You should look at the bottom of the stack trace as it likely mentions that your app needs to be migrated to AndroidX, which is also mentioned in the readme. Going to close this as this is likely the problem you're facing. If you have any further comments, either post in English or seek help elsewhere
