### ISSUE TITLE
Set custom time interval for User Notifications Framework iOS 10.0 onwards

### ISSUE THREAD

**Issue by LSmint** [MaikuB/flutter_local_notifications#343]
iOS version: 10.0 onwards

Is it possible to set custom time interval for User Notifications? For example, I want to set every 2 days repeatedly on 1pm instead of daily. It looks like this only can be done in UILocalNotification.

Instead of using User Notifications, can iOS 10.0 onwards support for UILocalNotification?

**Comment by MaikuB** [comment]
The UILocalNotification APIs are deprecated and can lead to warnings when run on iOS 10+. Furthermore Apple may completely remove them and I may even remove the usage of them in the plugin as the device's running on older versions of iOS have a very low market share.  As such I have no plans to support using deprecated APIs in the scenario you've described. You're welcome to make your own fork or supplement using this plugin with your own code via platform channels
