### ISSUE TITLE
Open app when onSelectNotification is called for scheduled notification

### ISSUE THREAD

**Issue by TannerYoung** [MaikuB/flutter_local_notifications#345]
How does one open the application within the onSelectNotification if the application is closed at that point because the notification was scheduled? In the example section there is this:

```
Future onSelectNotification(String payload) async {
    if (payload != null) {
      debugPrint('notification payload: ' + payload);
    }
    await Navigator.push(
      context,
      new MaterialPageRoute(builder: (context) => new SecondScreen(payload)),
    );
}
```

But by the time the callback is called, the context referred would no longer be valid, right? Perhaps this is out of the scope of this plugin, and if so I apologize, but how can I launch to a named route or the main app within this callback?

**Comment by TannerYoung** [comment]
I figured out how to do this by setting up a global navigator key for the MaterialApp:

```
GlobalKey<NavigatorState> navigatorKey = new GlobalKey<NavigatorState>();
...

MaterialApp(navigatorKey: navigatorKey,
...

onSelectNotification: (String payload) async {
        await navigatorKey.currentState.pushNamed("/");
},

```

**Comment by MaikuB** [comment]
Just a note that if you look at the comments in the example app around the main function that you can query if an application launched the app so you can set the initial route. `onSelectNotification` will still be called though so your app may need extra logic to ensure that it doesn't do work like navigate to another page if intend on taking the approach of setting the initial route of your app
