### ISSUE TITLE
Notifications not appearing on Apple Watch

### ISSUE THREAD

**Issue by mayhew3** [MaikuB/flutter_local_notifications#347]
I'm not seeing scheduled notifications forwarded to my Apple Watch (Series 3). 

I have the presentAlert, presentBadge, and presentSound options enabled.

When I disconnect the watch from the iPhone, it makes a sound, or vibrates when silenced, and the screen lights up to show the notification. 

But when the Apple Watch is connected, no sound or vibration, the phone doesn't wake, and nothing happens on the Watch. The notification is there on my lock screen when I wake it manually.

In the Apple Watch Settings / Notifications, I've verified the app is enabled in the list. All my other apps will cause the Apple Watch to vibrate and display notification when it is connected, but this one does not.

Do you know if there is anything special that needs to be done to enable notifications to be passed through to the Apple Watch?

Thanks!
Mayhew

```

    flutterLocalNotificationsPlugin = new FlutterLocalNotificationsPlugin();
    // initialise the plugin. app_icon needs to be a added as a drawable resource to the Android head project
    var initializationSettingsAndroid =
    new AndroidInitializationSettings('app_icon');
    var initializationSettingsIOS = new IOSInitializationSettings(
        onDidReceiveLocalNotification: onDidReceiveLocalNotification);
    var initializationSettings = new InitializationSettings(
        initializationSettingsAndroid, initializationSettingsIOS);
    flutterLocalNotificationsPlugin.initialize(initializationSettings,
        onSelectNotification: onSelectNotification);

```
```

Future<void> scheduleNotification(int id, DateTime scheduledTime, String name, String payload, String dateType, bool replacingOriginal) async {

    var androidPlatformChannelSpecifics = AndroidNotificationDetails(
      'taskmaster',
      'TaskMaster',
      'Notifications for the TaskMaster app',
      importance: Importance.Max,
      priority: Priority.High,
      ticker: 'ticker',
    );
    var iOSPlatformChannelSpecifics = IOSNotificationDetails(
      presentAlert: true,
      presentBadge: true,
      presentSound: true,
    );
    var platformChannelSpecifics = NotificationDetails(
        androidPlatformChannelSpecifics,
        iOSPlatformChannelSpecifics
    );
    await flutterLocalNotificationsPlugin.schedule(
        id,
        name,
        'Task has reached $dateType date',
        scheduledTime,
        platformChannelSpecifics,
        payload: payload,
        androidAllowWhileIdle: true);
}

```

**Comment by MaikuB** [comment]
When you say

> All my other apps will cause the Apple Watch to vibrate and display notification when it is connected, but this one does not.

are you referring to apps you wrote or just apps you've installed from the store?

Note that I don't have an Apple Watch to test this out so if there is an issue, this is likely something you'll need to track down and submit a PR. Based on my understanding though, there shouldn't be anything extra required. The OS is suppose to handle forwarding notifications on it's own and is covered in the documentation [here](https://developer.apple.com/documentation/watchkit/enhancing_your_watchos_app_with_notifications?language=objc)

**Comment by mayhew3** [comment]
Okay, I'll try to track it down myself.

**Comment by troyshu** [comment]
@mayhew3 did you resolve this? I'm also running into notifications `flutter_local_notifications` not being forwarded to my Apple watch (but they show up fine on my iPhone).

**Comment by mayhew3** [comment]
I wish I remembered! It is working now, though I don't remember ever finding a silver bullet that did it. Sorry that isn't very helpful!
