### ISSUE TITLE
Support for non dismissible Android notifications

### ISSUE THREAD

**Issue by GiorgioBertolotti** [MaikuB/flutter_local_notifications#349]
Hi!  
I'd need to create a non dismissible Android notification, is this feature already implemented in the package?  
I couldn't find any documentation about it.  
  
Thanks!  
Giorgio

**Comment by MaikuB** [comment]
Yes they're referred to as notifications that are "ongoing" on Android

https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/AndroidNotificationDetails/ongoing.html

Example code is in the repo
https://github.com/MaikuB/flutter_local_notifications/blob/a3d58bd6a59d0ea79e260ae7347a65ebb41a914b/example/lib/main.dart#L560

**Comment by GiorgioBertolotti** [comment]
Great job, thanks a lot!
