### ISSUE TITLE
[Feature Request] Notification Timeout

### ISSUE THREAD

**Issue by TannerYoung** [MaikuB/flutter_local_notifications#350]
Android supports the ability to timeout a notification after a period of time. It seems reasonable to have that functionality here as well.

https://developer.android.com/reference/android/app/Notification.Builder#setTimeoutAfter(long)

**Comment by MaikuB** [comment]
How about submitting a PR?

**Comment by TannerYoung** [comment]
Sounds good, I'll look into it tomorrow or early next week.

**Comment by MaikuB** [comment]
Any updates?

**Comment by TannerYoung** [comment]
Apologies, this slipped further down on my prioritization list and although still something I can eventually tackle, won't be able to get to for a while.

**Comment by MaikuB** [comment]
This is version 1.1.1 now
