### ISSUE TITLE
schedule notification not working after terminate the app on devices

### ISSUE THREAD

**Issue by 2000calories** [MaikuB/flutter_local_notifications#351]
When the app is running: the scheduled notifications works on my HuaWei devices.
When the app is terminated: the schedule notification works on emulators but not on my HuaWei devices.

Here is the log from Logcat.
<img width="924" alt="log" src="https://user-images.githubusercontent.com/25191098/67020635-133d8080-f131-11e9-8627-a90b1e2b9ba0.PNG">
[log.txt](https://github.com/MaikuB/flutter_local_notifications/files/3739927/log.txt)

**Comment by MrMagloire** [comment]
Same for me

**Comment by MaikuB** [comment]
This isn't an issue with the plugin but an issue with particular versions of Android that have restrictions in place. If you do search, you'll see that it has been discussed before e.g. https://github.com/MaikuB/flutter_local_notifications/issues/213
