### ISSUE TITLE
Can't pick multiple weekdays

### ISSUE THREAD

**Issue by badaween-ahmed** [MaikuB/flutter_local_notifications#352]
```dart
  Future<void> _showWeeklyAtDayAndTime() async {
    var time = Time(10, 0, 0);
    var androidPlatformChannelSpecifics = AndroidNotificationDetails(
        'id',
        'name',
        'description');
    var iOSPlatformChannelSpecifics = IOSNotificationDetails();
    var platformChannelSpecifics = NotificationDetails(
        androidPlatformChannelSpecifics, iOSPlatformChannelSpecifics);
    await flutterLocalNotificationsPlugin.showWeeklyAtDayAndTime(
        0,
        'show weekly title',
        'Weekly notification',
        Day.values[0],
        time,
        platformChannelSpecifics);
  }
```
I am trying to get weekly notification not just for one weekday (like Sunday) I want to select more than one weekday (like Sunday, Tuesday, Thursday, Friday). I couldn't find any solution to implement.

**Comment by MaikuB** [comment]
Schedule it for the other weekdays i.e. call the method multiple times.

**Comment by badaween-ahmed** [comment]
Sorry for the late reply..
What if the user changes the selected weekday? like if they remove one weekday from selected weekdays I have to call 
```
  Future<void> _cancelNotification() async {
    await notification.cancel(uniqueId);
  }
```
That will remove notification from other weekdays too?

I have another issue when I am trying to generate a unique id for each item `int id = DateTime.now().millisecondsSinceEpoch; ` 
I am getting this exception 
`[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Invalid argument(s): id must fit within the size of a 32-bit integer i.e. in the range [-2^31, 2^31 - 1] `

**Comment by MaikuB** [comment]
Yes you would. Regarding the error, please read the message as it tells you what the problem is

**Comment by badaween-ahmed** [comment]
So I have to cancel all weekday notification and schedule notification again? I understand the message but I was looking for the solution. Anyway thanks for the reply.

**Comment by MaikuB** [comment]
Yes you would

**Comment by badaween-ahmed** [comment]
I already succeded I created a List of Map then mapped over that List to call  _showWeeklyAtDayAndTime() multiple times. I am really thankful for this useful library and your help.
