### ISSUE TITLE
[Request] Is it possible to do an http request before showing a daily notification?

### ISSUE THREAD

**Issue by GiacomoK** [MaikuB/flutter_local_notifications#357]
Hi,  
I would like to know if it is possible to do an http request before showing daily notification.

I need to get the title and the body of the notification from the server, and they change every day.

**Comment by MaikuB** [comment]
Nope. The kind of work you're trying to wouldn't be the responsibility of this plugin to begin with as what you're trying to do in general is to schedule code to execute. You should be looking to see if there are plugins that can do this. Worst case you can write code that uses the APIs of the native platforms
