### ISSUE TITLE
Combine schedule and periodicallyShow

### ISSUE THREAD

**Issue by febg11** [MaikuB/flutter_local_notifications#358]
Is there a method of showing a daily notification but doing so at a scheduled time. 

For example sending a notification every day at 10am UTC starting tomorrow i.e. do not show today even if it scheduled before 10am. 

I realize there is schedule method but  this doesn't repeat and the periodicallyShow method seems to start the notifications based on the time that it was executed. 

If this is not a feature it would be really useful. 
 
Edit***

I just found the showDailyAtTime which is close, except  it will show the notification today instead of starting tomorrow.

**Comment by MaikuB** [comment]
Is this somehow different to the `showDailyAtTime` method mentioned in the readme?

**Comment by febg11** [comment]
Sorry i found the method after I made the issue. It is yes.  

Say I want to schedule the notification to start in 3 days time and repeat every day thereafter. 

Is this possible with the current version?

Thanks for replying so promptly.

**Comment by MaikuB** [comment]
No the native APIs don't support this to begin with. Like https://github.com/MaikuB/flutter_local_notifications/issues/357, what you should be looking to do a schedule code to execute. This may require looking for a plugin or worst case, write the code to do this yourself that makes of the native APIs
