### ISSUE TITLE
[Question] - iOS icon badge support

### ISSUE THREAD

**Issue by angel1st** [MaikuB/flutter_local_notifications#363]
Hi there,
Does the plugin support an icon badge when running under iOS? Since now, I have a Android app and it shows a badge over the icon in the moment notification appears. I cannot however see such badge on iOS app icon.
If I miss a specific iOS config, I would appreciate if you can direct me to it, thanks!

**Comment by MaikuB** [comment]
No it doesn't, you'd need to fork or add this logic yourself. There's a longer explanation [here](https://github.com/MaikuB/flutter_local_notifications/issues/81)

**Comment by angel1st** [comment]
Thanks, @MaikuB, I am closing the issue then.
