### ISSUE TITLE
Notification not working/showing when app killed.

### ISSUE THREAD

**Issue by shivamkapasia0** [MaikuB/flutter_local_notifications#364]
Hi MaikuB, thanks for this amazing flutter plugin.
But I'm facing problem like whenever i set notification and kill app from background then notification doesn't appear but when i open app again at the time of notification time it shows notification. Please help and thanks in advance.

**Comment by MaikuB** [comment]
What device are you running this on? Certain devices from companies like Xiaomi, Huawei etc will have this problem and it's a restriction placed by their customised version of Android. You can search the issues in the repo to see that this has been raised before

**Comment by MaikuB** [comment]
I see a reaction on my reply but no actual response. Going to assume that you were using a device from companies that I've mentioned so will close this issue
