### ISSUE TITLE
Scheduling new notification in app instance, which was started via notification

### ISSUE THREAD

**Issue by Feralnex** [MaikuB/flutter_local_notifications#366]
Is it intended to behave like this? I mean: When you schedule a notification => close the app => open the app by clicking on notification => schedule new notification (on app instance created by notification), the callback onSelectNotification is fired for notification which created app instance. Every time You schedule new notification, the callback fires with the notification which created the app instance in which you're scheduling new notification. I don't know how to go around this. Can You enlighten me?

**Comment by MaikuB** [comment]
No. Can you try the example app to see if you can reproduce the behaviour you've described? From what I quickly tried, it doesn't exhibit the same problem so would imply there's an issue in your code. I suspect you are calling the `initalize` method multiple times as that is what is used to trigger the callback if the app was launched from a notification

**Comment by Feralnex** [comment]
Yes, You're right, I was initializing it multiple times. Thank You for help ^^
