### ISSUE TITLE
Dynamic notification content

### ISSUE THREAD

**Issue by erolasan** [MaikuB/flutter_local_notifications#367]
Hi,
I am developing a habit tracking app and i am trying to implement daily notifications, which will remind the user about his habits. A simple case is to show a notification every morning stating how many habits the user has to work on for that day. In order to that i need to get the info about the current state of the user's habits, which will change every day, but when you schedule a notification it's scheduled with the data you pass initially. 

Is there any way i can update the content of the scheduled notification? And if there isn't, can you suggest a way to reschedule a new notification with new content or any other way to handle this scenario. 

Thanks 😊

**Comment by MaikuB** [comment]
A similar question has been asked been before. Please see https://github.com/MaikuB/flutter_local_notifications/issues/357

**Comment by erolasan** [comment]
There are plugins that let you run code in the background periodically, but the problem is that IOS limits and controls the schedule and it decides based on app usage patterns when to actually run your code, it may even not run at all. Where as the scheduling system for notifications in this plugin seems more accurate on both platforms and i wondered if I can use this system to reschedule a notification with the new content every time the old one is shown.

And i know that for my case is best to use a server-side scheduler and send push notifications from there, but the app has to work even without any network connection.

**Comment by MaikuB** [comment]
As per the response in the issue I've linked the plugin isn't going to help you. On iOS, scheduling is based on using a set of APIs that is just for showing notifications. 

The mechanisms behind the work manager you've described are likely the best you option given you have opted not to go for push notifications

**Comment by erolasan** [comment]
Thanks i will try with workmanager, and if it is really inaccurate scheduling on IOS i will have to use push notifications after all
