### ISSUE TITLE
Regarding idle mode on android

### ISSUE THREAD

**Issue by febryituery** [MaikuB/flutter_local_notifications#370]
> Note that on Android devices, the default behaviour is that the notification may not be delivered at the specified time when the device in a low-power idle mode. This behaviour can be changed by setting the optional parameter named androidAllowWhileIdle to true when calling the schedule method.
> 

Hi, Maiku. i just want to get more info regarding this _androidAllowWhileIdle_. i can't find it on your documentation/example project about how to set it to true. by the way, i'm using _showDailyAtTime_ method, is this method also affecting to that  _androidAllowWhileIdle_?

thank you.

**Comment by MaikuB** [comment]
You can't find it as the section of the documentation you are looking at is only for scheduling for a single notification, which is the only scenario where this functionality is supported at this point in time.
