### ISSUE TITLE
Initializing from main doesn't trigger onSelectNotification when terminated

### ISSUE THREAD

**Issue by quangduy-luong** [MaikuB/flutter_local_notifications#372]
**Describe the bug**
The onSelectNotificationCallback is not being triggered when the app is launched from terminated state using the new initialization approach from the example app.

**To Reproduce**
1. Launch the example app
2. Display a notification
3. Close the app by swiping up
4. Tap on the notification

**Expected behavior**
The app should launch and navigate the user to the second screen.

This is fixed if I move the initialization code back to the first StatefulWidget's initState.

**Comment by MaikuB** [comment]
D'oh! Many thanks for catching that as I forgot to test that scenario. I won't get to push an update today but if you intend to initialise in the `main` please try the following

- call `WidgetsFlutterBinding.ensureInitialized();` in your main function
- switch from `StreamController` to `BehaviourSubject` from rxdart package

Let me know if this works for you. Worked fine for me

**Comment by quangduy-luong** [comment]
Works like a charm! Thanks, I'll be closing for now then.
