### ISSUE TITLE
Scheduled notification doesn't appear on the time it should- on Galaxy note 5

### ISSUE THREAD

**Issue by ShiraNeuman** [MaikuB/flutter_local_notifications#375]
Our app uses this package and lets the user schedule notifications. We have been tested it on several devices and it seems to work fine on all of them except galaxy note 5, with android version 7.
When we schedule to nearby time (in an hour or two) the notifications appear at the exact time. 
But when we schedule to a later time it seems to have a not fixed delay from 1-3 hours.
On a galaxy 7 device, we scheduled a lot of notifications, it always worked perfectly, except once it popped in 3 minutes late. 
Perhaps it has something to do with the internet connection? or something with the device settings?
Thank you in advance.

**Comment by MaikuB** [comment]
Are you scheduling individual notifications or recurring notifications? There are notes on the readme about the behaviour where it may not precise along with the following comment if you're using the `schedule` method

> Note that on Android devices, the default behaviour is that the notification may not be delivered at the specified time when the device in a low-power idle mode. This behaviour can be changed by setting the optional parameter named androidAllowWhileIdle to true when calling the schedule method.

**Comment by MaikuB** [comment]
Closing due to lack of further response
