### ISSUE TITLE
Redirect on acceptance / did not accept of push notification permission

### ISSUE THREAD

**Issue by jsonthor** [MaikuB/flutter_local_notifications#376]
Hi,

Really sorry if this is somewhere as I just couldn't find it, and I'm new to Flutter but is there a way to navigate the user to a specific part of your app if they accept or don't accept the push notification permission dialogue?

Thanks!

**Comment by MaikuB** [comment]
`initialize` returns a boolean that depends on if the user has granted permissions on iOS. I'll need to update the docs to indicate this so thanks for raising this. Having said that, bear in mind that Apple's documentation says to display the permissions dialog when the app launches

**Comment by MaikuB** [comment]
To clarify, what I meant was you could use the boolean value returned by the `initialize` and navigate to the desired page.

**Comment by jsonthor** [comment]
That works like an absolute charm - thanks so much for getting back to me!

**Comment by MaikuB** [comment]
No worries :)
