### ISSUE TITLE
I want to add a Action Button branch to the project

### ISSUE THREAD

**Issue by rafaelsetragni** [MaikuB/flutter_local_notifications#377]
I just want to contribute to the project adding the Action Button functionality. I already did it in my local project but i wanna share with you, guys.

**Comment by MaikuB** [comment]
There's already an issue on notification actions with reasons why it's not implemented yet. Please see https://github.com/MaikuB/flutter_local_notifications/issues/17

**Comment by rafaelsetragni** [comment]
You do not get it. I coded it!

Its all done and im using on my actual project. 

I just wanna have permission to push a new branch with this feature, to everyone can see, check if its okay and use it. And if everyone likes the branch it could be merge to the master one.

And i do not use a different channel to do that, as you explained on the link posted on your answer. My code reuses everything that you did and i followed your code standards. I just edited 2 Java files and 1 dart to make it. I attempted to did the code as simple as possible.

**Comment by MaikuB** [comment]
> You do not get it. I coded it!

I understood that you wrote some code but please be mindful of what you write as that seemed a bit uncalled for and can come off as rude.

If you followed the discussion in that thread, you'll see that I have talked about how I and others have attempted this before. There are issues with being able to execute generic code when the application isn't running. A big part of this that there are limitations within Flutter that I have raised an issue on the main Flutter repository that has yet to be addressed.

If you wanted to share the code to see if it can be merged, you could fork the repository and create a pull request like others in the community have done. However, given what I have stated above I would think your code would have the same issues and wouldn't be merged.
