### ISSUE TITLE
Crash in Scheduller Notification

### ISSUE THREAD

**Issue by medemin** [MaikuB/flutter_local_notifications#383]
hello when I use scheduller notifications, the action fails and returns these two errors:

> E/EGL_emulation( 1735): tid 1767: eglSurfaceAttrib(1354): error 0x3009 (EGL_BAD_MATCH)

> W/OpenGLRenderer( 1735): Failed to set EGL_SWAP_BEHAVIOR on surface 0xded057e0, error=EGL_BAD_MATCH

it's important to note that the most common notifications work normally, follow my code block:

@override
  initState() {
    super.initState();
    // initialise the plugin. app_icon needs to be a added as a drawable resource to the Android head project
    // If you have skipped STEP 3 then change app_icon to @mipmap/ic_launcher
    var initializationSettingsAndroid =
        new AndroidInitializationSettings('app_icon');
    var initializationSettingsIOS = new IOSInitializationSettings();
    var initializationSettings = new InitializationSettings(
        initializationSettingsAndroid, initializationSettingsIOS);

    flutterLocalNotificationsPlugin = new FlutterLocalNotificationsPlugin();
    flutterLocalNotificationsPlugin.initialize(initializationSettings);
  }

  @override
  Widget build(BuildContext context) {
    return FlatButton(
      onPressed: () {
        DatePicker.showDateTimePicker(context, showTitleActions: true,
            onChanged: (date) {
          print('change $date');
        }, onConfirm: (date) {
          print('confirm $date');
          scheuleAtParticularTime(
              DateTime.fromMillisecondsSinceEpoch(date.millisecondsSinceEpoch));
        }, currentTime: DateTime.now(), locale: LocaleType.pt);
      },
      child: Text(
        'Select time for notification arrival',
        style: TextStyle(color: Colors.black, fontWeight: FontWeight.w900),
      ),
    );
  }

  Future scheuleAtParticularTime(DateTime timee) async {
    var time = DateTime(timee.day, timee.month, timee.year, timee.hour,
        timee.minute, timee.second);

    var scheduledNotificationDateTime =  new DateTime.now().add(new Duration(seconds: 5));
    var androidPlatformChannelSpecifics = new AndroidNotificationDetails(
        'your other channel id',
        'your other channel name',
        'your other channel description');
    var iOSPlatformChannelSpecifics = new IOSNotificationDetails();
    NotificationDetails platformChannelSpecifics = new NotificationDetails(
        androidPlatformChannelSpecifics, iOSPlatformChannelSpecifics);
    await flutterLocalNotificationsPlugin.schedule(
        0,
        'scheduled title',
        'scheduled body',
        scheduledNotificationDateTime,
        platformChannelSpecifics);

  }

**Comment by MaikuB** [comment]
Those "errors" you have included in the post don't have anything to do with notifications. The code you submitted doesn't provide much more info either. There aren't any known issues the completely prevent a scheduled notification. I would guess that you haven't followed all of the instructions in the Android integration section of the readme but without being able to see more of your app that can't confirm. I suggest refer to the readme and example to cross check with what's in your app to see what you may have missed

**Comment by MaikuB** [comment]
Closing due to lack of further response
