### ISSUE TITLE
I need help to test Notifications Action Buttons and Replies

### ISSUE THREAD

**Issue by rafaelsetragni** [MaikuB/flutter_local_notifications#385]
Since last week i´ve been implementing a new version of Flutter Local Notifications who allows to use `Action Buttons` and `Reply Buttons` over notifications. Also i changed the payload to work with Map object to improve security and bring new usefull informations for further handling.

**Android Version:**
![android-notifications](https://user-images.githubusercontent.com/40064496/69969689-aa04a780-14fb-11ea-97a8-4cb668e1fcf3.png)

**IOS Version:**
![ios-notifications](https://user-images.githubusercontent.com/40064496/69972166-d8848180-14ff-11ea-81ab-26be7e70a6af.png)

I had keeped all the old functionalities compatible and they still working with this new version. I had putted deprecated marks on methods declaration and warning messages over debug console, leving it clear to who is using the deprecated methods. I did it to allow the developers to use this new version with others improvements without need to change its own code imediatly.

**But the problem is**: i programmed the IOS using Objective C for the first time in last 4 days using a virtual machine on Windows. Is really slow and painful to build and test the application using this kind of enviroment, but its all i have right now.

So i need to someone to helpe-me to test if everything its running okay on IOS devices to finally request a merge to promote a new version of this pluggin.

Source at:
https://github.com/rafaelsetragni/flutter_local_notifications

**OBS 1**: I do not implemented the reply action on IOS yet, but is totaly possible to do. Ill do it latter on.

**OBS 2**: I already finded a issue on IOS on notifications without body, but i believe this is a old issue. Ill gonna fix it untill today.

**Comment by quangduy-luong** [comment]
Putting aside my issues with the Payload refactoring and the whole security debate aside, how do you set up actions for the buttons? Looking through the source code, it doesn't seem like anything except for the text input reply and canceling notification would work with them. Would the buttons support actions such as snooze the notification or making HTTP requests headlessly, or does the app need to launch in the background to execute those tasks?

**Comment by rafaelsetragni** [comment]
The app needs to handle the incomming request to do whatever it wants to. im kepping it simple as possible for the first version.

**Comment by rafaelsetragni** [comment]
An interest thing to implement next is to make the action buttons to send a request to the background app without needs to open it.

**Comment by MaikuB** [comment]
I previously mentioned in https://github.com/MaikuB/flutter_local_notifications/issues/377, I'm not looking to take PRs at this stage related to notification actions unless it works even when the app isn't running. You mentioned how you only had one platform channel in your code, yet the reason that I'm not sure you understand, is that another platform channel is currently needed for background execution. Moreover, if I were to look at a PR then I'd be looking at the older PRs that members had submitted.

In light of this, as this isn't really a message board,  if you need someone to who test your fork, I'd suggest you use an actual message board or other channels of communication to do so.

**Comment by rafaelsetragni** [comment]
You guys want to get a huge step to implement action buttons, but now in fact you have the amount of 0 (zero, none, nothing, non-existent anywhere) functionalities available to developers who want to use this feature, calling the app only on background or not. Thats the reallity!

Have you imagine at a time once in life that for some developers who will use this plugin could be intersting (and MAYBE fulfilled all their needs) just adding action buttons?

Im spliting from that community and i will launch my own version of notifications for flutter. Keep waiting for a miracle to someone arrive with all your solutions at once.

I like to make small moves at time. I suggest you to do the same.
