### ISSUE TITLE
Should let user to set color of icon.

### ISSUE THREAD

**Issue by realcarlos** [MaikuB/flutter_local_notifications#39]
I test this plugin in Android 7.1.1   , only a white square displayed.

**Comment by MaikuB** [comment]
I believe what you're after should now be addressed in the PR referenced in this issue that allows passing the color as per [this method](https://developer.android.com/reference/android/app/Notification.Builder.html#setcolor). Grab the latest version and let me know how you go

**Comment by realcarlos** [comment]
Thank you for quick reply , but I tried the sample , there is some error : 

E/MethodChannel#dexterous.com/flutter/local_notifications( 3851): Failed to handle method call
[        ] E/MethodChannel#dexterous.com/flutter/local_notifications( 3851): java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long

so the notification can not be sent.

**Comment by MaikuB** [comment]
Uploaded a bug fix release. Try again, if it still fails let me know what colour you're using or if possible see if you can clone my repo and track down the issue as I was only able to reproduce the problem where passing a colour value with a value of zero for it's ARGB components

**Comment by realcarlos** [comment]
I tested , it works well ! Thank you @MaikuB  .
