### ISSUE TITLE
[Question] How to schedulle notifications monthly or annualy

### ISSUE THREAD

**Issue by rodrigobastosv** [MaikuB/flutter_local_notifications#390]
The RepeatInterval enum don't contemplate month or annual interval. What's the way to go to implement this? Should i manually create separate notifications for each month or year or there is a straight forward way to acomplish what i want?

Thanks for the great job!

**Comment by MaikuB** [comment]
Yep you'd need to do that

**Comment by rodrigobastosv** [comment]
Thanks for the reply. I'll close this
