### ISSUE TITLE
[FeatureRequest] Add timestamp to PendingNotificationRequest

### ISSUE THREAD

**Issue by esDotDev** [MaikuB/flutter_local_notifications#391]
Would it be possible to add the timestamp / datetime into the payload for PendingNotificationRequest? 

I'd like to pull down a bunch of events, and replace any notifications that have been changed, however I need to know the time of the event to know whether it's changed.

**Comment by esDotDev** [comment]
I can workaround this using payload, but I think it would still be a nice addition?

**Comment by MaikuB** [comment]
See https://github.com/MaikuB/flutter_local_notifications/issues/245#issuecomment-502432339

**Comment by esDotDev** [comment]
Ah I see. You mentioned DST issues, would it be problematic to store msSinceEpoch in Payload, and then use that to compare to the times stored in our database?

**Comment by MaikuB** [comment]
I believe only you can answer that as it'll depend on if the database adjusts the times stored in response to daylight savings

**Comment by esDotDev** [comment]
Well I just store as UTC, and convert back to local time when I pull it down.

As far as I know this works fine, but was just curious if you found something in your research that said otherwise?

**Comment by MaikuB** [comment]
If that's how you're storing it then it should be fine but as you may come across from looking at the DST related issues, the plugin doesn't account for DST at the moment so it may be possible that the time the notification shows is wrong

**Comment by esDotDev** [comment]
Cool. My use case is just not canceling events that haven't changed, that way I don't dismiss a notification that may already be showing. So I think this should work.

Thanks for the great plugin and being so responsive!

**Comment by MaikuB** [comment]
No worries and thanks for the support
