### ISSUE TITLE
Return time and date for pendingNotificationRequests

### ISSUE THREAD

**Issue by jsonthor** [MaikuB/flutter_local_notifications#392]
Hi,

Apologies if I've missed this, but when returning a list from pendingNotificationRequests I can't see how to get the time and date for the scheduled notification.

Is this possible?

Thanks!

**Comment by MaikuB** [comment]
Nope. This was asked recently in https://github.com/MaikuB/flutter_local_notifications/issues/391 where I point out an old response to this (see https://github.com/MaikuB/flutter_local_notifications/issues/245#issuecomment-502432339)

**Comment by jsonthor** [comment]
Ah, no worries. I'll pass it in the payload for now and get it from there.
