### ISSUE TITLE
Could asset served with `ContentUri` or `FilePath` as an icon?

### ISSUE THREAD

**Issue by AlexVincent525** [MaikuB/flutter_local_notifications#393]
## What I want to do
I'm trying to serve some png/svg as icon with messaging notifications.
This might be the same as https://github.com/MaikuB/flutter_local_notifications/issues/32#issuecomment-521642682 .

## What I've done
I've checked the comment https://github.com/MaikuB/flutter_local_notifications/issues/32#issuecomment-521644742 with `AssetManager`, and it seems all of the assets should be associate with a unique key then registered.

## Question
Could this propose be handled more properly? I mean without register those assets one by one, and for more flexibility when added new asset.

**Comment by AlexVincent525** [comment]
Or maybe there's a demo can be provided? 😄

**Comment by MaikuB** [comment]
I kinda get what you're asking but could you be more specific? The Android Notification APIs tend to require that the resources be part of the Android app package itself. Note that you can submit a PR for new functionality to support your needs ;)

**Comment by AlexVincent525** [comment]
The comment in https://github.com/MaikuB/flutter_local_notifications/issues/32#issuecomment-521642682 mentioned:

> This will duplicate my assets, since they are also used by the Flutter code.

I have a set of images stored as flutter assets. (path: `/assets/icons/`) When I want to make a messaging notification, according to your comment in https://github.com/MaikuB/flutter_local_notifications/issues/32#issuecomment-521644742 :

> Noticed I forgot to add a link to my reply. I'd suggest taking a look at the API at https://flutter.dev/docs/development/ui/assets-and-images#android as it might solve the problem though I haven't had a chance to check

I need to share my asset with the platform. (In my case is Android)

But what I don't know is how to share, because the code which the document provided seems incomplete. And after shared, how to import to the notification setting?

If this is impossible, Can an asset in flutter side be served as a drawable or something else to use in notification?

**Comment by MaikuB** [comment]
I still can't understand what scenarios you are trying to solve. Let's ignore that you want to reuse your assets, in what scenarios are you trying to use the images assets? The small icon, big icon or...?

> Can an asset in flutter side be served as a drawable or something else to use in notification

No, resources on the Android side get assigned an id. This only happens for things that have been added directly as an Android resource. These IDs are what a lot of the Android Notification APIs expect to be passed

**Comment by AlexVincent525** [comment]
Maybe it's just because of my bad english 😞. What is the difference between icons? Cause I can only tell that I want to use image asset in the notification with the specific style `AndroidNotificationStyle.Messaging`. Something like:
https://github.com/MaikuB/flutter_local_notifications/blob/5286b412b03c6f87952121e61cf035f10a77ccf3/example/lib/main.dart#L497-L502
Display the image asset to an avatar.

**Comment by MaikuB** [comment]
Ok that's clearer now. I believe what you're after is possible and once implemented, would require  adding something like `Asset` to the `IconSource` enumeration. As mentioned above, I'd encourage you into submit a PR. The code in the Flutter documentation appears incomplete before it's let to developers to decide what to do afterwards. You could explore the APIs and look for other samples to figure out how to do it, which is the same as what I would need to do

**Comment by AlexVincent525** [comment]
Thanks for your explanation, I'll try it in my spare time. 😄

**Comment by MaikuB** [comment]
Support for this has been added in 1.4.0
