### ISSUE TITLE
not working properly in android real device

### ISSUE THREAD

**Issue by Oss2093** [MaikuB/flutter_local_notifications#394]
I'm trying the example code, and it is not working properly in android real devices, the notification is not popping up, you have to pull down the notification bar to see the notification and no sound, only three dots is showing in the notification bar when the notification arrives, I have tried it in Xiaomi redmi 3S and Nexus 6p. but in emulator and IOS devices it is working just fine.

I am using android studio 3.3
and this is flutter doctor response.

\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.17763.914], locale en-US)
    • Flutter version 1.12.13+hotfix.5 at \flutter
    • Framework revision 27321ebbad (3 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at \sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME = \sdk
    • Java binary at: \android-studio-ide-183.5522156-windows\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[!] Android Studio (version 2.2)
    • Android Studio at \Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_76-release-b03)

[!] Android Studio (version 2.3)
    • Android Studio at  \Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Android Studio (version 3.0)
    • Android Studio at  \android-studio-ide-171.4443003-windows\android-studio
    • Flutter plugin version 23.2.1
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.3)
    • Android Studio at  \android-studio-ide-182.5199772-windows\android-studio
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] Android Studio (version 3.4)
    • Android Studio at  \android-studio-ide-183.5522156-windows\android-studio
    • Flutter plugin version 23.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] Connected device (2 available)
    • Redmi 3S                  • 329954c27d63  • android-arm64 • Android 6.0.1 (API 23)
    • Android SDK built for x86 • emulator-5554 • android-x86   • Android 7.1.1 (API 25) (emulator)

! Doctor found issues in 2 categories.
Process finished with exit code 0

**Comment by MaikuB** [comment]
Whether or not notifications show up as a heads-up display depends on the priority and importance. I'd suggest checking the settings on your phone. This plugin has been around for a while so if there were issues like that on real devices, I would think someone else in the community would have raised it sooner. I forgot I had turned off the ringer volume so had no sound coming out from the notifications in the example on my Pixel 4 XL. Upon turning it back on, the sounds were playing fine

**Comment by Oss2093** [comment]
"This plugin has been around for a while so if there were issues like that on real devices, I would think someone else in the community would have raised it sooner." 
That's obvious but i couldn't find any reason why it's not working even though it's the example app not my code, I thought it might be some sort of update coursed that. 
OK after i checked the setting it seams like in some devices the default is not showing the notification as a heads-up and to be silent

**Comment by Oss2093** [comment]
But isn't there away to force notification to have a sound and to show as a heads-up in this kind of devices.

**Comment by MaikuB** [comment]
I would expect it to work on nexus 6p given its stock Android. However, for devices like Xiaomi, which I'm not familiar, I know there tends to be more restrictions in place. There aren't any APIs to bypass this and it wouldn't seem right if there was a way to do so

**Comment by Oss2093** [comment]
Thanks very much.
