### ISSUE TITLE
The local_notifications plugin migrate to Embedding v2

### ISSUE THREAD

**Issue by wangbo4020** [MaikuB/flutter_local_notifications#395]
The local_notifications plugin migrate to Embedding v2

**Comment by MaikuB** [comment]
Sorry but what are you trying to communicate here? If you're trying to say that this plugin hasn't been migrated to it then I'm aware of it. There are a couple of things that haven't landed on stable yet around it so it doesn't seem to be something that has a lot of urgency. There are some parts that should be straightforward to do though.
