### ISSUE TITLE
Flutter local Notification pluggin Lacks button functionality

### ISSUE THREAD

**Issue by Arham1995** [MaikuB/flutter_local_notifications#396]
Flutter local Notification pluggin Lacks button functionality like alarm snooze dismiss functionality

**Comment by MaikuB** [comment]
There's an existing open issue on this. Please see https://github.com/MaikuB/flutter_local_notifications/issues/17

**Comment by MaikuB** [comment]
Will be closing this as a duplicate. This functionality is not available at the moment due to limitations

**Comment by Arham1995** [comment]
What Limitations ?? will these be solved soon ??

**Comment by MaikuB** [comment]
Limitations in flutter. These have been covered in the thread I've linked. These are out of my control so I can't comment on how soon they'll be solved. Depending on your use cases, it may something you can do in your own app by writing the code to show and handle the notifications yourself

**Comment by Arham1995** [comment]
yes i want similar kind of functionality and only onSelectNotification functionality is available i want more then tap functionality if buttons could have been added i would have multiple choices sir i also want to ask that can we use java for notification and show them in flutter 
thanks.
