### ISSUE TITLE
Feature Request: Cancel All Pending

### ISSUE THREAD

**Issue by esDotDev** [MaikuB/flutter_local_notifications#397]
Currently if you call cancelAll, it will remove any notifications that are currently in the notification drawer.

It would be nice if there could be a cancelAllPending() fxn for when this behavior is not wanted.

For example, when I pull down a bunch of events from the server, the easiest way to reschedule is just cancelAll, and then schedule the new ones, but I do not want to remove any notifications that may have already shown themselves, as the user has already seen it, and it should persist until they clear. 

I think this should be possible, as the pendingNotificationRequests does not contain requests that have already triggered.

**Comment by MaikuB** [comment]
You can cancel the individual notifications you get back upon querying the pending notification requests

**Comment by esDotDev** [comment]
Yes I am, just thought it might make for a nice addition to the API.

**Comment by MaikuB** [comment]
Feel free to submit a PR as this is more of a helper method given that the Android at least doesn't have anything like this. This won't be something I'll be looking to add in myself except on the iOS side when I get time to move to a federated plugin structure that allows platform specific methods, or someone else in the community helps with that effort

**Comment by esDotDev** [comment]
Isn't that kind of an argument to implement it? It's nice to have consistent functionality across platforms from a developer perspective, so if a workaround is possible on Android, to match what exists on iOS, that would make for a cleaner API surface.

I will try and find some time to submit a PR for Android, I don't have the test environment to do iOS, but it sounds like you have a plan there already.

**Comment by MaikuB** [comment]
No, my plans are around a restructure the enable platform-specific functionality and if I'm to create the interface/contract, enables others in the community to implement notifications on other platforms.  Shouldn't stop anyone from doing a PR. My point was that is lower priority given there are ways around it. Providing a consistent API surface isn't necessarily the way forward anymore though I agree that it's nice

**Comment by esDotDev** [comment]
Ok you're the expert! I agree it's not high priority, just a nice to have.
