### ISSUE TITLE
How to detect `selectPushNotfication` come from `background state` or `terminated state`

### ISSUE THREAD

**Issue by tronghuy5555** [MaikuB/flutter_local_notifications#404]
As question above, I think we should divide `selectNotfication` into 2 function. One for background state and one for terminated state.

**Comment by MaikuB** [comment]
The results of calling `getNotificationAppLaunchDetails` that is mentioned in the readme will tell you if the app was launched from the user tapping on a notification from a terminated state

**Comment by tronghuy5555** [comment]
Thank you for supporting me. I read the readme careless.
