### ISSUE TITLE
Android Plugin API error / warning

### ISSUE THREAD

**Issue by princeteck** [MaikuB/flutter_local_notifications#405]
**IMPORTANT**
Currently migrated a project and Gradle and since then facing this warning. The version I am using is  flutter_local_notifications: ^0.9.1

**Describe the bug**
The plugin `flutter_local_notifications` is built using an older version of the Android plugin API which assumes that it's running in a full-Flutter environment. It may have undefined behaviours when Flutter is integrated into an existing app as a module.
The plugin can be updated to the v2 Android Plugin APIs by following https://flutter.dev/go/android-plugin-migration.

**Comment by MaikuB** [comment]
Thanks but aware of that as raised in https://github.com/MaikuB/flutter_local_notifications/issues/395

If this affects you, feel free to submit a PR

**Comment by MaikuB** [comment]
Migration has been done now
