### ISSUE TITLE
 Crash launching application after build using split abi - cannot find icon.

### ISSUE THREAD

**Issue by electriko3** [MaikuB/flutter_local_notifications#407]
With the split abi build, the application crashes that it cannot find the icon that I specify in final settingsAndroid = AndroidInitializationSettings ('@ mipmap / bell');

Maybe it will be possible to make it so that if you do not specify an icon in the android, the application icon stretches ?!

**Comment by MaikuB** [comment]
I'm assuming this is with a release build? If so your issue is likely more to do with resource shrinking being enabled and you need to configure your app to make sure your icons don't get discarded. If you haven't done this yet, see the readme for more info

**Comment by MaikuB** [comment]
Closing due to lack of further response
