### ISSUE TITLE
Scheduling a notification with strange behavior

### ISSUE THREAD

**Issue by bionan** [MaikuB/flutter_local_notifications#410]
In my Android application I need to show a notification 5 minutes before the events occur. These events occur within a maximum of 2 weeks. For this I wrote the following code:

    Future<void> _eventNotification (int id, String date, String startTime) async {
    
    // the event occurs at most 2 weeks later
    
    // date      like "2020-01-08"
    // startTime like "08:30"
    

    DateTime now = DateTime.now();
  
    DateTime eventDate = DateTime.parse( "$date $startTime:00.000" );
    
    int difference = eventDate.difference(now).inSeconds - 300; // show notification 5 minutes early event
    
    // if difference variable is a small number (5, 15, 60,...) everything works fine.
    // But if the difference is a large number like 1200000 the notification not show up 
    
    var scheduledNotificationDateTime = DateTime.now().add(Duration(seconds: difference));
    
    var androidPlatformChannelSpecifics = AndroidNotificationDetails(
        'ExplikaNotifications',
        'Explika',
        'Explika notifications',
        );
        
    var iOSPlatformChannelSpecifics = IOSNotificationDetails();
    
    NotificationDetails platformChannelSpecifics = NotificationDetails(androidPlatformChannelSpecifics, iOSPlatformChannelSpecifics);
    
    await flutterLocalNotificationsPlugin.schedule(
        id,
        "Event Title",
        'Event body',
        scheduledNotificationDateTime,
        platformChannelSpecifics,
        androidAllowWhileIdle: true);
        
        }

The problem is that **notifications sometimes work and sometimes not!**
**if difference variable is a small number (5, 15, 60,...) everything works fine.
But if the difference is a large number like 1200000 (aprox. 14 days) the notification not show up** 

My doubts:
- do scheduled notifications work only for short time intervals?
- Can the app be closed after notification has been created?

Thank you for any help.

**Comment by MaikuB** [comment]
1.There shouldn't be differences on if you used a short or long "interval" as you put it. It's just a date at the end. I don't know what is causing the issue you're seeing though I'm curious how you're testing notifications that trigger weeks later, like so you actually wait until that amount of time has elapsed?

2. Yes it can be

**Comment by MaikuB** [comment]
Also have you looked at setting reminders using the device_calendar plugin? That seems more appropriate since you're dealing with events

**Comment by bionan** [comment]
> 1.There shouldn't be differences on if you used a short or long "interval" as you put it. It's just a date at the end. I don't know what is causing the issue you're seeing though I'm curious how you're testing notifications that trigger weeks later, like so you actually wait until that amount of time has elapsed?

Thanks so much for the quick response!
I didn't wait 14 days to test the notification :-)
 I tested just 1 day apart and the notification didn't show up. Then I did more testing and came to the conclusion that the problem arose when the time interval for the notification to appear was longer than tens / hundreds of seconds.

Thanks for the suggestion: I will check the device_calendar plugin.

**Comment by bionan** [comment]
Sorry for reopen this issue. 
Is there anything I can check about notification scheduling using logcat?

**Comment by MaikuB** [comment]
No. I'm not sure what you mean by testing one day apart here. Do you mean you scheduled a notification to appear a day later? If so I do remember testing this a while back by modifying the example app and it worked fine

**Comment by MaikuB** [comment]
Btw is there a reason you use the current time in your calculations as opposed to subtracting 5 minutes from the event date directly? You also call `DateTime.now` twice so there will likely be a minor difference in the values

**Comment by bionan** [comment]
After several tests using different smartphones I came to the conclusion that the problem I reported was related to my smartphone ... I couldn't figure out the reason for this strange behavior.
Anyway, thank you very much for all your support in solving the problem and for developing such a useful plugin.
