### ISSUE TITLE
is:issue is:open Xcode Build Error "expected ',' separator"

### ISSUE THREAD

**Issue by esDotDev** [MaikuB/flutter_local_notifications#412]
I get this error when trying to build for iOS: 
 _/Users/builder/clone/familysnap/ios/Runner/AppDelegate.swift:10:26: error: expected ',' separator
        if ![[NSUserDefaults standardUserDefaults]objectForKey:@"Notification"]{_

I think it's because this is objective-c code, and not swift, but the README and /example do not show this code in swift.

**Comment by MaikuB** [comment]
If you're using Swift then yes you'll need to convert that code to Swift. Shouldn't be difficult to do though I'm currently not at a place where I can try it out. Feel free to submit a PR to add a Swift version to the readme

**Comment by esDotDev** [comment]
I'm building on windows and pushing builds to Codemagic via git, so I don't have xcode, code-hinting, or any sort of way to tell if the code I'm pasting in is correct. 

No rush or anything, but if you could add instructions at some point for swift that would be much appreciated.

**Comment by MaikuB** [comment]
Swift version of the code has been added now
