### ISSUE TITLE
Any plans for supporting macos?

### ISSUE THREAD

**Issue by iampawan** [MaikuB/flutter_local_notifications#413]

**Comment by MaikuB** [comment]
Potentially yes but I'd need move the plugin to a federated plugin structure first. My understanding is that APIs for MacOS are the same for iOS or very similar. I haven't seen much when it comes to MacOS plugins in general though.

**Comment by MaikuB** [comment]
Oh I stand corrected, noticed some of the first party plugins have MacOS versions now

**Comment by iampawan** [comment]
Yes @MaikuB you are right. I am also using them

**Comment by MaikuB** [comment]
The initial beginnings of the platform interface are there but I'm trying to see if the timezone issues with scheduling can be fixed. Trying to avoid expanding to a new platform that would have the same issues as #118 and #179. Should anyone want to submit a PR that at least implements the methods as defined in the platform interface then I'd be happy to look at that.

**Comment by MaikuB** [comment]
For those interested in a macOS implement, I would appreciate if you could upvote this issue  https://github.com/flutter/flutter/issues/57944. It's not a showstopper but without that being resolved, the plugin will have some limitations on devices running on older macOS versions

**Comment by MaikuB** [comment]
FYI, i'll be publishing a prerelease version of the plugin soon that includes macOS support. Need to test some other changes before I do so

**Comment by MaikuB** [comment]
I've got a [beta release](https://pub.dev/packages/flutter_local_notifications/versions/1.5.0-beta.1) out with better timezone support and macOS support. If you can give it a spin and let me know if you run into issues then that would be great

**Comment by MaikuB** [comment]
Changes from beta release are now in the stable 1.5.0 release so will be closing this now
