### ISSUE TITLE
Show a daily notifications at a specific time using showDailyAtTime method is delayed

### ISSUE THREAD

**Issue by ZayRTun** [MaikuB/flutter_local_notifications#414]
Hi,
I am trying to implement a daily notification at specific times using the **showDailyAtTime** method. Though the notifications are popping up, they are delayed.
I am testing on Android 9. I have followed all the instructions on the plugin page but this issue persisting.
Please advice,

Thank you.

`Future scheduleNotification(
      int id, String title, String prayerDate, String prayerTime) async {
    String prayerTitle = title;
    String dateTime =
        DateFormat('hh:mm a').format(DateTime.parse('$prayerDate $prayerTime'));
    int hour = int.parse(
        DateFormat('HH').format(DateTime.parse('$prayerDate $prayerTime')));
    int minute = int.parse(
        DateFormat('mm').format(DateTime.parse('$prayerDate $prayerTime')));

    var time = Time(hour, minute, 0);
    var androidChannelSpecifics = AndroidNotificationDetails(
      '$prayerTitle',
      '$prayerTitle Adhan',
      '$prayerTitle Adhan Notification',
      playSound: true,
      sound: 'adhan_madina',
      importance: Importance.Max,
      priority: Priority.High,
    );
    var iOSChannelSpecifics =
        IOSNotificationDetails(sound: 'adhan_madina.aiff');

    NotificationDetails platformChannelSpecifics =
        NotificationDetails(androidChannelSpecifics, iOSChannelSpecifics);
    await Provider.of<DataProvider>(context)
        .flutterLocalNotificationsPlugin
        .showDailyAtTime(
          id,
          '$prayerTitle Adhan',
          'Isha Adhan at: $dateTime',
          time,
          platformChannelSpecifics,
        );
  }`

**Comment by MaikuB** [comment]
This is expected behaviour for the plugin and is documented in the readme

**Comment by vifird** [comment]
@MaikuB  Will this problem be fixed?

**Comment by ench0** [comment]
Sorry to post in closed issue, but is there any plan to have 'androidAllowWhileIdle' available for _showDailyAtTime_ method, like it is in _schedule_ method?
