### ISSUE TITLE
Not able to build

### ISSUE THREAD

**Issue by Faiyyaz** [MaikuB/flutter_local_notifications#419]
Error while building xcode build on latest version of xcode

```
Undefined symbols for architecture arm64:
      "_OBJC_CLASS_$_FlutterMethodChannel", referenced from:
          objc-class-ref in FlutterLocalNotificationsPlugin.o
      "_FlutterMethodNotImplemented", referenced from:
          -[FlutterLocalNotificationsPlugin handleMethodCall:result:] in FlutterLocalNotificationsPlugin.o
    ld: symbol(s) not found for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by MaikuB** [comment]
You'll need to provide more info. Best if there's a link to a repo that reproduces this problem. Haven't seen other accounts on this error and I haven't run into the issue either

**Comment by Faiyyaz** [comment]
Sorry it was my sdk which was corrupted

**Comment by hiashutoshsingh** [comment]
> Error while building xcode build on latest version of xcode
> 
> ```
> Undefined symbols for architecture arm64:
>       "_OBJC_CLASS_$_FlutterMethodChannel", referenced from:
>           objc-class-ref in FlutterLocalNotificationsPlugin.o
>       "_FlutterMethodNotImplemented", referenced from:
>           -[FlutterLocalNotificationsPlugin handleMethodCall:result:] in FlutterLocalNotificationsPlugin.o
>     ld: symbol(s) not found for architecture arm64
>     clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ```

I am getting the same error now, how did you resolve it?
