### ISSUE TITLE
Cancelling scheduled notifications 

### ISSUE THREAD

**Issue by andrewpmoore** [MaikuB/flutter_local_notifications#42]
Does the cancel and cancelAll methods cancel outstanding notification or scheduled notifications (or both)?

**Comment by MaikuB** [comment]
By outstanding, do you mean those that have already been presented? If so, then the answer is both

**Comment by andrewpmoore** [comment]
Thanks, I've just looked at the android code for this and can see if cancels the outstanding notification and also cancels the scheduled alarms. I'll do a bit more debugging of my code and I seem to have an issue that the notifications when changed aren't firing at the new time. (this is when using the weekly scheduling and the user then subsequently changes the time of a notification)

**Comment by MaikuB** [comment]
Sure you may want to reference a copy of the plugin code as well so that you can debug even further since I'm not sure what your code is like. I'm assuming that when you schedule a weekly notification that you assign it a unique ID that you track and when the user changes the time, you cancel the notification with that ID (and await that method call) and then reschedule it at a new time

**Comment by andrewpmoore** [comment]
It should be simpler than that with what I've got as any time someone goes into the page regarding setting up notifications I'm just trying to cancel them all. Then when they exit the page it should recreate them all again.

**Comment by andrewpmoore** [comment]
I've noticed that when I'm calling showWeeklyAtDayAndTime that the notification will trigger straight away frequently. I'm not sure if that's what's causing me to think things aren't cancelling.

Looking at the android code for scheduling it returns a date in the past to alarmManager which causes it to run straight away.

I just ran the logic through from the data in shared preferences for a trigger at 9AM on monday.

`
    
    long startTimeMilliseconds = 1526988654085L;  //the value stored in shared preferences
    
    Calendar calendar = Calendar.getInstance();
    calendar.setTimeInMillis(System.currentTimeMillis());
    calendar.set(Calendar.HOUR_OF_DAY, 9);
    calendar.set(Calendar.MINUTE, 0);
    calendar.set(Calendar.SECOND, 0);
    calendar.set(Calendar.DAY_OF_WEEK, 2);
    
    startTimeMilliseconds = calendar.getTimeInMillis();
    
    System.out.print("start time: " + startTimeMilliseconds);

`

and I got out 1526893200747 which converts to yesterday at 9am. This triggers the notification straight away. I'm not sure if that's intended or whether the check should see if startTimeMilliseconds is before now and if so, add 7 days onto the date.

**Comment by MaikuB** [comment]
Ah yes, good spot. I'd say it should add 7 days as I ran into a similar issue with implementing the ``periodicallyShow`` method. However, not sure that explains your issue

**Comment by MaikuB** [comment]
Uploaded a new version now

**Comment by MaikuB** [comment]
No worries and thanks for the compliment :)

Just a thought though that with your issue, I'd imagine it'd also occur with the ``showDailyAtTime`` method too so may be quicker to change the code to debug against that so you don't have to wait a week though I imagine you're testing with day and time values that are more closer to each other anyway

**Comment by andrewpmoore** [comment]
Thanks, looking at the code I can see how similar they are and I'd been testing with showDailyAtTime to confirm that also had the issue before delving into the code. I'll report back if it seems to be working (in a day or 2!)

**Comment by MaikuB** [comment]
Did you manage to sort it out?

**Comment by MaikuB** [comment]
Closing due to lack of response
