### ISSUE TITLE
Callback when receiving notification in Android

### ISSUE THREAD

**Issue by mrhabibi** [MaikuB/flutter_local_notifications#420]
Hi, do you have any plan to add callback when `ScheduledNotificationReceiver.onReceive()` is getting triggered? For my case, it's used for tracking purpose. Thanks!

**Comment by MaikuB** [comment]
Not at the moment. It wouldn't be possible for the same reason why actions aren't implemented. If you need this kind of functionality for your purposes (and since it's for tracking then it's probably doable) then you need go down to the native Android and iOS code.

**Comment by Harishwarrior** [comment]
@MaikuB Is this feature available now? or Do you have any suggestions on implementing this?
