### ISSUE TITLE
[Question] Can I set the start Datetime of the periodically or daily notification? 

### ISSUE THREAD

**Issue by shadyshrif** [MaikuB/flutter_local_notifications#422]
I want to set the start DateTime for the planned notification. 

In my case, I'm reminding the user to take planed medicine on specific dates. The user can download the app today and the app will calculate his next dose after two weeks and the user will close the app. During the two weeks, the app won't popup any reminders. When the dose time comes the app will keep reminding the user periodically until the user takes the medicine.

What I understand that the periodically notification starts from now which doesn't cover my case. is there a solution?

**Comment by MaikuB** [comment]
You'll need to either look at writing your own native code or possibly look at the device calendar plugin
