### ISSUE TITLE
iTunes connect error - Missing Push Notification Entitlement

### ISSUE THREAD

**Issue by guybashan** [MaikuB/flutter_local_notifications#424]
Getting the following error when uploading to iTunesConnect:
`ITMS-90078: Missing Push Notification Entitlement - Your app appears to register with the Apple Push Notification service, but the app signature's entitlements do not include the "aps-environment" entitlement. If your app uses the Apple Push Notification service, make sure your App ID is enabled for Push Notification in the Provisioning Portal, and resubmit after signing your app with a Distribution provisioning profile that includes the "aps-environment" entitlement. Xcode does not automatically copy the aps-environment entitlement from provisioning profiles at build time. This behavior is intentional. To use this entitlement, either enable Push Notifications in the project editor's Capabilities pane, or manually add the entitlement to your entitlements file. For more information, see https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/HandlingRemoteNotifications.html#//apple_ref/doc/uid/TP40008194-CH6-SW1.`

I do not use Push notification at any place only local notifications using the plugin.

**Comment by MaikuB** [comment]
This is a general Flutter issue. See https://github.com/flutter/flutter/issues/9984
