### ISSUE TITLE
AndroidAlarmManager calls flutterLocalNotificationsPlugin.show() but no notification is displayed

### ISSUE THREAD

**Issue by Anon-65535** [MaikuB/flutter_local_notifications#426]
**Describe the bug**

When I call show() from AlarmManager callback, in order to write a scheduled notification, no notification is displayed.

Below are the steps to reproduce the bug.

I initialise flutter_local_notification plugin in the main() function of the App in this way:
`NotificationManager n = new NotificationManager();
void main() async
{
  WidgetsFlutterBinding.ensureInitialized();
  await AndroidAlarmManager.initialize();
  n.initNotificationManager();
  runApp(MainClass());
}`

NotificationManager class is:
`class NotificationManager
{
  FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin;
  AndroidInitializationSettings initializationSettingsAndroid;
  IOSInitializationSettings initializationSettingsIOS;
  InitializationSettings initializationSettings;
  void initNotificationManager()
  {
    initializationSettingsAndroid = new AndroidInitializationSettings('@mipmap/ic_launcher');
    initializationSettingsIOS = new IOSInitializationSettings();
    initializationSettings = new InitializationSettings(initializationSettingsAndroid, initializationSettingsIOS);
    flutterLocalNotificationsPlugin = new FlutterLocalNotificationsPlugin();
    flutterLocalNotificationsPlugin.initialize(initializationSettings);
  }
  void showNotificationWithDefaultSound(String title, String body, String payload) 
  {
    var androidPlatformChannelSpecifics = new AndroidNotificationDetails('your channel id', 'your channel name', 'your channel description', importance: Importance.Max, priority: Priority.High);
    var iOSPlatformChannelSpecifics = new IOSNotificationDetails();
    var platformChannelSpecifics = new NotificationDetails(androidPlatformChannelSpecifics, iOSPlatformChannelSpecifics);
    flutterLocalNotificationsPlugin.show(0, title, body, platformChannelSpecifics, payload: payload);
  }
}`

In the initState() of a page inside the App I make AlarmManager calls the callback in this way:
`void initState()
  {
    super.initState();
    AndroidAlarmManager.oneShotAt(DateTime.now().add(Duration(seconds: 5)), 0, alarmCallback);
   //......
  }`

The callback is: 
`alarmCallback()
{
  n.showNotificationWithDefaultSound("Title", "MySuperBody", "Hey, this is the Payload!");
  return;
}`

Please, consider to write an example using AlarmManager.

Thank you.

**Comment by MaikuB** [comment]
Note that the main purpose of the bug report is to report a bug with the plugin on its own. It's not for when there's an issue with integrating with other libraries. If you need help with using the plugin with other libraries than I would kindly suggest you look at the places mentioned on https://flutter.dev/community. Reason being is it's not sustainable for me to provide examples on using the plugin with other libraries as there would be many permutations. It would require me to be familiar with the libraries as well and I've not used the `android_alarm_manager` plugin. This repo may help you though https://github.com/seamonkeysocial/rainbowmonkey
