### ISSUE TITLE
Ongoing notifications not sticky?

### ISSUE THREAD

**Issue by honga** [MaikuB/flutter_local_notifications#43]
Using the example app, seems like ongoing notifications can still be swiped away and dismissed in the tray on Android? Is there a way to make it sticky?

**Comment by MaikuB** [comment]
You'll have to familiarise yourself with the Android APIs to configure the settings to achieve what you're after as what's exposed in the NotificationDetailsAndroid class is almost a direct mapping to the Android settings e.g. set autoCancel to false so it can't be dismissed

**Comment by MaikuB** [comment]
Also autoCancel has a default value of true to match as that's the default on Android. I suspect your issue is that you'll have to set it to false

**Comment by honga** [comment]
Thanks for getting back, forgot to mention I added autoCancel like this
```
  Future _showOngoingNotification() async {
    var androidPlatformChannelSpecifics =
    new NotificationDetailsAndroid(
        'your channel id', 'your channel name', 'your channel description',
        importance: Importance.Max, priority: Priority.High, ongoing: true, autoCancel: false);
    var iOSPlatformChannelSpecifics =
    new NotificationDetailsIOS();
    var platformChannelSpecifics = new NotificationDetails(
        androidPlatformChannelSpecifics, iOSPlatformChannelSpecifics);
    await flutterLocalNotificationsPlugin.show(0, 'ongoing notification title',
        'ongoing notification body', platformChannelSpecifics);
  }
```

**Comment by MaikuB** [comment]
do you mean you added that and you still have the same issue?

**Comment by MaikuB** [comment]
Uploaded new version to fix the issue

**Comment by honga** [comment]
Awesome! Thanks @MaikuB
