### ISSUE TITLE
Ios when kill app not call onDidReceiveLocalNotification

### ISSUE THREAD

**Issue by SiNguyen0604** [MaikuB/flutter_local_notifications#431]
Hi MaikuB,
I set a timer to show local pushnotification. But the case when killing my app I select local pushnotification but not call onDidReceiveLocalNotification.

**Comment by MaikuB** [comment]
That's expected behaviour. Please see the API docs https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/IOSInitializationSettings/onDidReceiveLocalNotification.html

**Comment by MaikuB** [comment]
Another thing is that the `initialize` method has the onSelectNotification callback (see https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/FlutterLocalNotificationsPlugin/initialize.html) that is for when the user selects a notification. Not sure why you tried to handle selection using `onDidReceiveLocalNotification` when it's specific to iOS

**Comment by SiNguyen0604** [comment]
Hi MaikuB,
Thank for your support .
Current Only if I kill the app does this not work and all the other cases it works with I . I am using flutter_local_notifications 0.7.1+3.

**Comment by MaikuB** [comment]
Are you sure you're referring to `onDidReceiveLocalNotification`? That's a callback that will only work when the app is running. This is the native behaviour in iOS as well so this isn't a bug. What I'm trying to say above is it looks like you're using the wrong callback for what your trying to achieve

**Comment by SiNguyen0604** [comment]
Hi MaikuB,
new issue with me . when my app foreground recevice pushnotification . it auto remove.  I can't see again message push notification in my phone.
Any solution  help me .

**Comment by SiNguyen0604** [comment]
[Ios.mov.zip](https://github.com/MaikuB/flutter_local_notifications/files/4043747/Ios.mov.zip)
I don't know for what reason . Plz check video .
