### ISSUE TITLE
Questions about Scheduled Notifications

### ISSUE THREAD

**Issue by nemoryoliver** [MaikuB/flutter_local_notifications#432]
I have a few dumb questions about this package.

- Do scheduled notifications work even if the app is not running in the background?
- Do we have to call the showDailyAtTime() every time the app is opened? Or should we have logic to only run it once?
- Does calling the showDailyTime() schedules a separate notification instance every time or it just initializes it?
- What's the proper way to change the scheduled time if ever? Do we have to cancel all the pending notifications first?

Will appreciate any inputs. Thanks a lot!

**Comment by MaikuB** [comment]
> Do scheduled notifications work even if the app is not running in the background?

Yes

> Do we have to call the showDailyAtTime() every time the app is opened? Or should we have logic to only run it once?

Only once

> Does calling the showDailyTime() schedules a separate notification instance every time or it just initializes it?

Just initialises it

> What's the proper way to change the scheduled time if ever? Do we have to cancel all the pending notifications first?

Cancel using the id

Just a general note that you can clone the repository and run the example app to explore as ot demonstrates all of the functionality available

**Comment by nemoryoliver** [comment]
Hi @MaikuB thanks so much for clarifying. I'll try to clone it if I need to know more how it works but I wish you add more information in your readme as well. Thanks again for your amazing work and contribution to the flutter community

**Comment by MaikuB** [comment]
No worries. There's less in the readme as there's a lot of functionality and the plugin is a wrapper around the native APIs. Finding the right balance in the size of the readme is also tricky and there have been cases where issues have been reported as portions of the readme had been skipped. A documentation site would probably be more suitable but not something I can get to. If anyone is keen on that and is willing to help then that would be awesome.

As the questions have been answered I'm going to close this.
