### ISSUE TITLE
How can I get the list of all notifications which user have scheduled?

### ISSUE THREAD

**Issue by Zeeshan0201** [MaikuB/flutter_local_notifications#435]
I want to show a list of all notifications which users scheduled and can cancel it by the method which
you have mentioned.

> await flutterLocalNotificationsPlugin.cancel(0);

as any default method which package providing regarding the list of all notifications which scheduled for future?

**Comment by MaikuB** [comment]
https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/README.md#retrieve-pending-notification-requests

**Comment by Zeeshan0201** [comment]
@MaikuB thanks ! not able to find while reading docs..thanks again

**Comment by Zeeshan0201** [comment]
@MaikuB how can I get details of DateTime, When This Notification Scheduled? Can you please check...
![error](https://user-images.githubusercontent.com/45591301/72153124-fed8ef00-33d2-11ea-90ac-fc7207914ff2.png)

**Comment by MaikuB** [comment]
It's not there because you can't. This has previously been asked in https://github.com/MaikuB/flutter_local_notifications/issues/245#issuecomment-502432339 with more details there

**Comment by Zeeshan0201** [comment]
@MaikuB alright, Thanks for your all replies and for providing a great package! :clap:
