### ISSUE TITLE
notification id is always int

### ISSUE THREAD

**Issue by codenamics** [MaikuB/flutter_local_notifications#436]
Hello,

Not a bug but question. It that a must that id of notification should be int?. It is important as when i wat to schedule a reminder for particular item i want to add this item id (from db) as an id notification. Id's from MongoDB are strings. 

Maybe other way to bind item to it's notification?

regards

**Comment by MaikuB** [comment]
Yes it's required as it's an integer on Android. See https://developer.android.com/training/notify-user/build-notification#notify. Applications will need to be responsible for managing the IDs

**Comment by codenamics** [comment]
ok thanks i just figured it out how to mange it
