### ISSUE TITLE
Notification is not popping up on the first time - iOS

### ISSUE THREAD

**Issue by RocketStormNet** [MaikuB/flutter_local_notifications#437]
Hi!
I've implemented your example code in my app. Everything works perfectly on Android! On iOS I've met with issue when on the first creation of notification it doesn't work. But next notifications popping up successfully.

What it might be?

Thank you!

**Comment by MaikuB** [comment]
I would think it's an issue somewhere in your code. No one has mentioned having this issue and you can clone the repository to confirm if you run into the same problem. Perhaps the first time you do it in your code, you are trying to show are notification before permissions have been granted

**Comment by MaikuB** [comment]
Closing to lack of further information. If you have run into a bug, appreciate if you can fork the repo and update the example app to provide a sample that can reproduce it
