### ISSUE TITLE
Feature request: Support 'delayed' repeating notifications

### ISSUE THREAD

**Issue by KholofeloMoyaba** [MaikuB/flutter_local_notifications#438]
This plugin already covers scheduling once-off notifications for a given time and it also supports repeating notifications. I'm looking for a mix between the two. Consider the following scenario:
I want to be reminded to watch a show every Monday 15h00 but only starting next month (because the show starts airing next month). With the current implementation, I can either schedule a once-off notification for the first monday of next month. Or I can set a weekly notification which would start on the very next Monday.

I'm proposing a method that looks something like this:
```dart
Future<void> schedulePeriodic(int id, String title, String body,
      DateTime initialDate,
      RepeatInterval repeatInterval, NotificationDetails notificationDetails,
      {String payload})
```

This will work like the current `periodicallyShow` but it will only start sending notifications when the current time/date is after (or at) `initialDate`.

Alternatively, is there a way to achieve the desired functionality with the plugin as is?

**Comment by MaikuB** [comment]
I don't believe any of native notification APIs support something like what you're after so this isn't something that would be implemented. However, I believe you can use the device_calendar plugin to do something. Failing that, it would need to be application specific logic that you'll need to implement

**Comment by KholofeloMoyaba** [comment]
Thanks for the very prompt response @MaikuB

**Comment by MaikuB** [comment]
You're welcome. Closing as this isn't something that will be worked on
