### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by shinewanna** [MaikuB/flutter_local_notifications#442]
Notification icon can set network image for look like rich notification.
Now,it can only set app_icon or other default one.
If u can change to network image,it's very useful to use in messaging conversation.

**Comment by MaikuB** [comment]
Rich/custom notifications require developers to create their own native layouts. The usual local notifications on Android only allow using drawable resources bundled with the Android project of your application. To summarise this isn't something that I believe can be done in the plugin so will close this. If you know of a way then you're welcome to submit a pull request.

**Comment by MaikuB** [comment]
Forgot to mention the example app has sample code for displaying notifications like a messaging conversation where one is a network image. Your application will need to be responsible for downloading it as the native APIs don't accept a network URL
