### ISSUE TITLE
Request permission when initializing NotificationController on ios 11

### ISSUE THREAD

**Issue by vlad-bel** [MaikuB/flutter_local_notifications#448]
**Describe the bug**
NotificationController from flutter_local_notifications library
behaves strangely when initialized on different versions of ios. On ios> 11 it initializes normally. On ios = 11, when the class is initialized, for some reason, a request to access notifications occurs. Updating to the latest version did not help.

**To Reproduce**
1) Run the application on the device with iOS = 11
2) Create an instance of the NotificationController class

**Expected behavior**
Nothing should happen. Request for permission must be done by another method.

**Current behavior**
A request for permission to display notifications

**Sample code to reproduce the problem**
`  void initPushNotifications() {
   final notificationController = NotificationController(androidMipMapIcon);
  }`

**Comment by MaikuB** [comment]
The plugin doesn't have a `NotificationController` class. Calling `initialize` is suppose to show the permissions prompt on iOS and has been this way since the beginning
