### ISSUE TITLE
Building release leads to hard crash in app

### ISSUE THREAD

**Issue by JannikSc** [MaikuB/flutter_local_notifications#450]
**Summary**
When building the app in release mode and installing it on an android device, the app crashes as soon as a notification is scheduled.

Edit:
**It works with `flutter channel stable`.** I'll further test with other channels.

**To Reproduce**
1. Clone example project
2. `flutter build apk`
3. `adb install -r build\app\outputs\apk\release\app-release.apk`
4. launch app, click on button "Schedule notification to appear in 5 seconds, ..." 

**Expected behavior**
Notification within 5 seconds

**Actual Behaviour**
App closes without an error message. The same applies to other functions like "Repeat notification every minute". Seems like only immediate notifications work.
Deploying an apk built with `flutter build apk --debug` works fine.

NOTE: there is no Exception thrown either. A try catch block does nothing and the app still crashes.

**Sample code to reproduce the problem**
I used the example app included in the repository. If needed I can provide a minimal example.
NOTE: plugins `http`, `path_provider`, `shared_preferences` and `rxdart` have been commented in pubspec.yaml. Build errors (when building release) were appearing and the functionality is not needed in this case anyway.

**Devices**
LG Nexus 5X (Android 8.1, Custom Rom)
Huawei P20 Pro (Android 9.1, stock Huawei)

**Comment by MaikuB** [comment]
Did you clone the entire repository or at least copy the entire example? There's a ProGuard rules that needs to be included (see https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/example/android/app/proguard-rules.pro)

**Comment by MaikuB** [comment]
Wonder if you have other environmental issues given you had build errors with some of the plugins. I don't get a hard crash on my own device or build errors. Can you also include the output of running `flutter doctor -v`?

**Comment by JannikSc** [comment]
The issue has been resolved.
I was using an older version of the repo. Can't reproduce with current version.

Sorry to bother you, my bad.
