### ISSUE TITLE
Crashes Android apps published to the Play Store

### ISSUE THREAD

**Issue by urmilshroff** [MaikuB/flutter_local_notifications#452]
**Describe the bug**
Android apps published to the Google Play Store that utilize this plugin's features simply crash when trying to create a notification. If I build the same app in debug or release mode and test it on a device, it works absolutely fine. But when I create the appbundle and publish it to the Play Store, then download the app from there, it will crash when trying to set a notification. This has happened to three different apps of mine, all of which use this plugin, so I've come to the conclusion that it is a problem with the plugin.

**To Reproduce**
1. Create an app using this plugin's features
2. Test on a device in debug or release mode, it'll work fine
3. Build the appbundle and publish to Play Store
4. Download from the Play Store and the same app will crash when setting a notification.

**Sample code to reproduce the problem**
[Goalkeeper GitHub](https://github.com/urmilshroff/goalkeeper)
[Goalkeeper Google Play](https://play.google.com/store/apps/details?id=tech.urmilshroff.goalkeeper)

[Fliver Rider GitHub](https://github.com/fliverdev/rider)
[Fliver Rider Google Play](https://play.google.com/store/apps/details?id=dev.fliver.rider)

[Fliver Driver GitHub](https://github.com/fliverdev/driver)
[Fliver Driver Google Play](https://play.google.com/store/apps/details?id=dev.fliver.driver) (Crashes on launch as the notification is created in `main()` itself)

**Comment by MaikuB** [comment]
It looks like none of your apps included a Proguard rules file. Can you try adding one (see readme for more info) and see how that goes?

**Comment by urmilshroff** [comment]
> It looks like none of your apps included a Proguard rules file. Can you try adding one (see readme for more info) and see how that goes?

The latest documentation for [Building an Android App for Release](https://flutter.dev/docs/deployment/android) talks about R8 and how it automatically optimizes the code. There's no mention of using ProGuard anymore, so should I still use it?

**Comment by MaikuB** [comment]
Yes https://developer.android.com/studio/build/shrink-code

**Comment by urmilshroff** [comment]
Looks like I managed to fix it by using the `proguard-rules.pro` from your example app. Now let's hope that the apps work when the updates go live on the Play Store. Thanks a lot!

**Comment by chrystoffer** [comment]
I had the same problem and creating proguard-rules.pro solved my problem

**build.gradle**
`    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug

            // Enables code shrinking, obfuscation, and optimization for only
            // your project's release build type.
            minifyEnabled true

            // Enables resource shrinking, which is performed by the
            // Android Gradle plugin.
            shrinkResources true

            // Includes the default ProGuard rules files that are packaged with
            // the Android Gradle plugin. To learn more, go to the section about
            // R8 configuration files.
            proguardFiles getDefaultProguardFile(
                    'proguard-android-optimize.txt'),
                    'proguard-rules.pro'
        }
    }`

**proguard-rules.pro**
`## Flutter wrapper
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }
-dontwarn io.flutter.embedding.**

## Gson rules
# Gson uses generic type information stored in a class file when working with fields. Proguard
# removes such information by default, so configure it to keep all of it.
-keepattributes Signature

# For using GSON @Expose annotation
-keepattributes *Annotation*

# Gson specific classes
-dontwarn sun.misc.**
#-keep class com.google.gson.stream.** { *; }

# Prevent proguard from stripping interface information from TypeAdapter, TypeAdapterFactory,
# JsonSerializer, JsonDeserializer instances (so they can be used in @JsonAdapter)
-keep class * implements com.google.gson.TypeAdapter
-keep class * implements com.google.gson.TypeAdapterFactory
-keep class * implements com.google.gson.JsonSerializer
-keep class * implements com.google.gson.JsonDeserializer

# Prevent R8 from leaving Data object members always null
-keepclassmembers,allowobfuscation class * {
  @com.google.gson.annotations.SerializedName <fields>;
}

## flutter_local_notification plugin rules
-keep class com.dexterous.** { *; }`

in case anyone needs the code.
tks

**Comment by MaikuB** [comment]
@urmilshroff glad to hear it. In case you haven't already, it's worth creating other tracks in the Google Play store for testing. Flutter's documentation did use to mention have the rules file but I believe that's been removed because there tooling will now generate one when creating a new app. From memory, that didn't use to be the case

**Comment by urmilshroff** [comment]
> @urmilshroff glad to hear it. In case you haven't already, it's worth creating other tracks in the Google Play store for testing. Flutter's documentation did use to mention have the rules file but I believe that's been removed because there tooling will now generate one when creating a new app. From memory, that didn't use to be the case

Yes, I think I remember some `proguard-rules.pro` files being generate in projects when I was initially learning Flutter. Looks like they've stopped it now.

I didn't consider launching my apps as beta because the release builds were working perfectly on my devices, so didn't think publishing would cause any issues. But I'll definitely keep that in mind from now on😅

Anyway, all my apps are working fine now after adding the `proguard-rules.pro`, so cheers!🍻

**Comment by oofimaconsumer** [comment]
I think You should put this info somewhere in the README :)

**Comment by MaikuB** [comment]
I did under the Android integration guide

**Comment by MaikuB** [comment]
If you feel there's something else, you can submit a pull request
