### ISSUE TITLE
Handle exception: MissingPluginException(No implementation found for method initialize on channel dexterous.com/flutter/local_notifications)

### ISSUE THREAD

**Issue by camilleblrt** [MaikuB/flutter_local_notifications#46]
When I try to use your package on an iOS device, I have this exception: 
> Handle exception: MissingPluginException(No implementation found for method initialize on channel dexterous.com/flutter/local_notifications)

Do you know how to deal with it?

**Comment by MaikuB** [comment]
Hmm generally that error occurs when plugins haven't been wired up properly at all. As such, I suspect you're running into issues with Flutter. I'd suggest trying another plugin to see if you get the same error. I can see one issue on the official Flutter repository where they've run into the same exception with official plugins

**Comment by MaikuB** [comment]
FYI, I've fixed an error that started occurring on iOS versions < 9 before that I hadn't encountered before that was happening on the ``initialize`` method but it's a different error than what you would've seen

**Comment by MaikuB** [comment]
Closing due to lack of response and more likely a Flutter/environment issue

**Comment by wqafzal** [comment]
yes it was Flutter issue as Android Studio took pull from beta channel and i Didn't knew that later i discovered and shifted to Stable channel
