### ISSUE TITLE
onSelectNotification called twice on android

### ISSUE THREAD

**Issue by vladogl** [MaikuB/flutter_local_notifications#462]
Clicking on notification, onSelectNotification is called two times in row. That happen on every notirification click attempt. 
version:
Flutter (Channel stable, v1.12.13+hotfix.7, on Linux, locale en_US.UTF-8)

**Comment by MaikuB** [comment]
I don't see this happening in the example app. Do you see the same behaviour there? There haven't been any other reports on this either and would be something I would have expected to have been reported before

**Comment by vladogl** [comment]
Yes, example work like it should.
Here is blank flutter app with only plugin added [app](https://github.com/vladogl/flutter_notifications_test) it still call onSelectNotification twice

**Comment by MaikuB** [comment]
Thanks, can reproduce that. I may need to migrate the plugin to use some new APIs. It looks as those the apps being created by recent tooling are creating the Android plugin class twice, which results in the behaviour you're seeing

**Comment by MaikuB** [comment]
Dug further and there's a similar issue in the firebase_messaging plugin as well. Looks like it's actually an issue with Flutter itself. Plugins are being registered twice and a fix (https://github.com/flutter/flutter/commit/4fbb85e0c207132e0ed9130d7410784c00f0d066) has been made to Flutter but it's only on master right now.

**Comment by vladogl** [comment]
Ok, thanks. Closed

**Comment by MilkBiscuit** [comment]
> I don't see this happening in the example app. Do you see the same behaviour there? There haven't been any other reports on this either and would be something I would have expected to have been reported before

I could reproduce it on example App, "Schedule notification to appear in 5 seconds..."

**Comment by MaikuB** [comment]
@MilkBiscuit You're quoting an earlier message. Please look at the most recent messages in the thread

**Comment by benyaminbeyzaie** [comment]
when I back to page that I called _initializeNotifications in initState() method the onSelectNotification call again but I don't want that!
