### ISSUE TITLE
Blank notification icon in Release build

### ISSUE THREAD

**Issue by prolongservices** [MaikuB/flutter_local_notifications#466]
I m getting strange issue, whenever i run debug build in my phone having android version 9 then i got the notification icon. But in release build showing empty icon. I tried changing icon as well but still showing empty icon.
You can check in screenshot below. (app name -> Vehicle 24x7)
![Screenshot_2020-02-05-13-18-38-442_com vehicle24x7 app](https://user-images.githubusercontent.com/59371022/73821640-63dd0480-481a-11ea-8e7f-134c237ca6c9.jpg)

**Comment by MaikuB** [comment]
See the note in the readme on resource shrinking. You'll need to do some configuration on the Android side to avoid this from happening and there's an XML file for the example app that can be used as reference.

**Comment by MaikuB** [comment]
This is the link to the XML file that is applicable to the example app in the repo https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/example/android/app/src/main/res/raw/keep.xml

**Comment by prolongservices** [comment]
let me try

**Comment by prolongservices** [comment]
yes problem resolved,
thanks.
