### ISSUE TITLE
onSelectNotification called two times on android but works perfectly on iOS

### ISSUE THREAD

**Issue by krishnakumarcn** [MaikuB/flutter_local_notifications#467]
Setting the local notifications on main function which is getting called only once.

```
void setUpLocalNotification() {
  var initializationSettingsAndroid =
      new AndroidInitializationSettings('@mipmap/ic_launcher');
  var initializationSettingsIos = new IOSInitializationSettings();
  var initializationSettings = new InitializationSettings(
      initializationSettingsAndroid, initializationSettingsIos);
  flutterLocalNotificationsPlugin.initialize(initializationSettings,
      onSelectNotification: onSelectNotification);
}
```

onSelectNotification is a global function

```
Future onSelectNotification(String payload) {
  print('received notification: $payload');
  navKey.currentState.push(_createRoute());
}
```

Now the payload is printing twice and navigating to the new route two times. So on the new page it is required to click two times for a back action.

This issue only occurs in Android.

**Comment by MaikuB** [comment]
This was raised in https://github.com/MaikuB/flutter_local_notifications/issues/462 and it's an issue with the Flutter framework
