### ISSUE TITLE
Badge number parameter on IOSNotificationDetails

### ISSUE THREAD

**Issue by FelixYew** [MaikuB/flutter_local_notifications#468]
Can you please add badge number parameter on IOSNotificationDetails so that this value can set the UNMutableNotificationContent.badge or UILocalNotification.applicationIconBadgeNumber to update app badge when local notification trigger. Thanks.

**Comment by MaikuB** [comment]
Please look at submitting a pull request given you know of the native APIs involved

**Comment by MaikuB** [comment]
Closed by #470 and in release by version 1.1.6. Thanks again for the PR
