### ISSUE TITLE
How to change notification icon color? (Android)

### ISSUE THREAD

**Issue by egeondundee** [MaikuB/flutter_local_notifications#469]
How is it possible to set the NotificationIcon Color for this plugin in Android? 
For instance, while I was using cloud messaging for remote notifications it was necessary to declare in AndroidManifest.xml this line: 
```
        <meta-data
                android:name="com.google.firebase.messaging.default_notification_color"
                android:resource="@color/colorAccent" />
```

**Comment by MaikuB** [comment]
There's an example app in the repository that covers this. Please refer to the code there and API docs for more info

**Comment by MaikuB** [comment]
https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/AndroidNotificationDetails/color.html
