### ISSUE TITLE
Notificaitons do not show on Samsung Galaxy S8 until app is opened when Power Mode is enabled

### ISSUE THREAD

**Issue by NedWilbur** [MaikuB/flutter_local_notifications#471]
**Describe the bug**
Notificaitons do not show on Samsung Galaxy S8 until app is opened when `Power mode` is enabled (a battery saving feature). The notification will show as soon as the application is opened or power mode is disabled (as long as the scheduled notification's time has passed). I do not see any way of whitelisting. Other applications on the device show notifications regardless, even when applications is killed.

**To Reproduce**
1. Enable `Power mode` on a Samsung Galaxy S8
2. Schedule a notification for a future date
3. Close the application & wait for schedule time to pass
4. Observe notification does not show
5. Disable `Power mode` or open application
6. Observe notification shows

**Expected behavior**
Expect the notifications to show regardless

**Comment by MaikuB** [comment]
You might need to check the importance and priority levels that you're setting for your notifications. I don't believe there's anything I can do if there are Samsung specific issues and I don't have access to one of their phones. As such, this is likely an issue you'll need to investigate further to fix should you find something that can be added to the plugin via a pull request

**Comment by ziggycrane** [comment]
My users are having the same problem. I have set the highest importance and priority but notifications only show up when the phone is woken up and not at the time when they were scheduled.

**Comment by MaikuB** [comment]
See my previous reply. Also should've added that repeating notifications on Android use [this API](https://developer.android.com/reference/android/app/AlarmManager#setInexactRepeating(int,%20long,%20long,%20android.app.PendingIntent)). My understanding is this respects the power settings used and there isn't a native API for scheduling recurring work at the exact frequency that has been specified. Note that recurring notifications not showing up at the exact time was a documented limitation in the readme as well. If this is not suitable for your use case then you can look at using the native APIs on Android to see how schedule one notification at a time and when it appears, to schedule the next one

To @NedWilbur's point that there are other notifications showing, it's likely they are appearing through other means. Quite likely they're push notifications so those appear immediately

**Comment by MaikuB** [comment]
I forgot to mention this before but the `schedule` method has a `androidAllowWhileIdle` parameter, you need to set this to `true` ignore the lower power idle mode. As this wasn't mentioned before, I assume this left at the default value (`false`) so will close. I can't do much about recurring notifications given the APIs available on Android.
