### ISSUE TITLE
No more notifications after launch an APP via onSelectNotification

### ISSUE THREAD

**Issue by CarlosCastroWolf** [MaikuB/flutter_local_notifications#473]
**Describe the bug**
When i close the APP, send a notification and launch the APP via onSelectNotification, i can't receive any Notifications in the background.

**To Reproduce**
1. Register FlutterLocalNotifications and FirebaseMessaging plugins manually.
2. Send a DATA notification via Firestore Cloud Functions.
3. Create a onSelectNotification function redirecting to another Screen.
4. Close the app and send a notification.
5. Click the notification to launch the App.

**Comment by MaikuB** [comment]
Sorry but I'm having trouble following the steps you've described. Are you trying to say you write the code to connect the `onSelectNotification` callback in step 3 after the firebase notification is sent? Do any of your steps involve showing a local notification using this plugin and if so, which steps are those?

Note that there's a documented issue around compatibility with `firebase_messaging`. I believe your issue is the same as that mentioned in https://github.com/MaikuB/flutter_local_notifications/issues/111. May close this if this ends up being a duplicate. Note that I do have a pull request waiting to be reviewed by the firebase team to fix this issue and you can try using the fork to see if it fixes your issue. Steps to do are mentioned at https://github.com/MaikuB/flutter_local_notifications/issues/111#issuecomment-575843590

**Comment by CarlosCastroWolf** [comment]
Oh, sorry for the bad explanation.

I'm using firebase_messaging to receive a data push notification, when the notification arrives, i trigger the local notification via onBackgroundMessage method from firebase_messaging . But when the app is closed and a notification in the Status Bar is clicked, the app opens normally and redirects to a specific page, but the application dont show notifications anymore.

**Function that initializes the Flutter_Local_Notifications and Firebase_Messaging:**
```
initializeFcmNotification() async {
    var initializationSettingsAndroid =
    new AndroidInitializationSettings('app_icon');
    var initializationSettingsIOS = new IOSInitializationSettings();
    var initializationSettings = new InitializationSettings(
        initializationSettingsAndroid, initializationSettingsIOS);
    flc.initialize(initializationSettings,
        onSelectNotification: onSelectNotification);
    if (Platform.isAndroid) {
      _saveDeviceToken();
    }
    _fcm.configure(
      onBackgroundMessage: Platform.isAndroid
          ? myBackgroundMessageHandler
          : null,
      onMessage: (Map<String, dynamic> message) async {},
      onLaunch: (Map<String, dynamic> message) async {},
      onResume: (Map<String, dynamic> message) async {},
    );
    _fcm.requestNotificationPermissions(const IosNotificationSettings(sound: true, badge: true, alert: true));
  }
```


**Firebase_Messaging Background message handler:** 
```
static Future<dynamic> myBackgroundMessageHandler(Map<String, dynamic> message) {
    if (message['data'] != null) {
      final data = message['data'];
      final title = data['title'];
      final body = data['body'];
      final documentID = data['id'];
      final pedido = data['pedido'];
      var androidPlatformChannelSpecifics = AndroidNotificationDetails(
          '0', 'jcom.autorizacao', 'autorizações enviadas',
          importance: Importance.Max, priority: Priority.High);
      var iOSPlatformChannelSpecifics = IOSNotificationDetails();
      var platformChannelSpecifics = NotificationDetails(
          androidPlatformChannelSpecifics, iOSPlatformChannelSpecifics);
      flc.show(
        int.parse(pedido),
        '$title',
        '$body',
        platformChannelSpecifics,
        payload: documentID,
      );
    }
    return Future<void>.value();
  }
```


**Flutter_Local_Notification onSelectNotification method:**
```
Future<void> onSelectNotification(String payload) async {
    DocumentReference documentReference = Firestore.instance
        .collection('users')
        .document(this.widget.prefs.getString('email'))
        .collection('pedidos')
        .document(payload);
    await documentReference.get().then((doc) {
      if (doc.data['Tipo'] == '3') {
        Get.to(ProdutoRequest(
          this.widget.prefs,
          doc,
          themeBloc: this.widget.themeBloc,
        ));
      } else {
        Get.to(ClientRequest(
          this.widget.prefs,
          doc,
          themeBloc: this.widget.themeBloc,
        ));
      }
    });
  }


```

**Comment by MaikuB** [comment]
so to confirm, this is on Android? With regards to the following...

>  But when the app is closed and a notification in the Status Bar is clicked, the app opens normally and redirects to a specific screen, but the application dont show notifications anymore.

When the app is launched and redirects in this scenario, do you still make it initialise both plugins?

**Comment by MaikuB** [comment]
Closing this as seems to be an issue with the `firebase_messaging` plugin and has been tracked on the associated repository [here](https://github.com/FirebaseExtended/flutterfire/issues/1590). If you follow the thread there you'll see there's a PR for the plugin that supposedly fixes the issue as well
