### ISSUE TITLE
Pin the notification to the status bar

### ISSUE THREAD

**Issue by hkndzdr** [MaikuB/flutter_local_notifications#476]
Can I pin the notification to the status bar? How do I keep notifications in the same place when cleared.

**Comment by MaikuB** [comment]
I think you're referring to oingoing/sticky notifications? If so, these can only be done on Android . Please refer to the example app that you can run by cloning the repo (code: https://github.com/MaikuB/flutter_local_notifications/blob/462316f7ee2954682f2396cd8421214b938d8cfb/flutter_local_notifications/example/lib/main.dart#L682)
