### ISSUE TITLE
Accept a Bitmap object to render largeIcon

### ISSUE THREAD

**Issue by haroldolivieri** [MaikuB/flutter_local_notifications#479]
As the native local notification library on Android, it would be more flexible accepting a raw Bitmap to render the `largeIcon`.

Nowadays I can't render a URL from the payload to show an image without creating a temporary file.

**Comment by MaikuB** [comment]
I'm not too familiar with this as you appear to be so I'd suggest submitting a pull request to solve your problem

**Comment by MaikuB** [comment]
Something else I wanted to ask for more clarification on here is you mention passing a raw bitmap, by that are you referring to passing the image as a byte array?

**Comment by MaikuB** [comment]
Closing due to lack of response to provide more info
