### ISSUE TITLE
Flutter notification doesn't Work when app is terminated - Android X

### ISSUE THREAD

**Issue by nidhi1612** [MaikuB/flutter_local_notifications#482]
Flutter notification doesn't work when we terminate the app from background in case of Android X.
I have been testing it on one plus 7T. it works fine in case of any below Android version but fails with One plus 7T - having android 10.
It also works when App is in the background but once I kill the App notification doesn't show up.

**Comment by MaikuB** [comment]
This sounds like a bug report, if so please fill in the details new the template that appears when creating a new issue. So far what you've said doesn't describe how you use the plugin in more detail, no code to demonstrate etc. Furthermore, I have run the example app on Pixel 4 XL that is an Android 10 device without any issues

**Comment by nidhi1612** [comment]
I could solve the issue by changing the Battery optimization setting to "Don't Optimize."

**Comment by MaikuB** [comment]
You may need to look at the importance and priority levels you're using. Battery related issues that are phone/OEM-specific aren't something I can look into so may require your own investigation to look to address.
