### ISSUE TITLE
AndroidX

### ISSUE THREAD

**Issue by keinou** [MaikuB/flutter_local_notifications#483]
**Describe the bug**
On compile:
``  symbol:   variable NotificationManagerCompat
  location: class GenerateLocalNotificationsTask
C:\flutter\.pub-cache\hosted\pub.dartlang.org\local_notifications-0.0.7\android\src\main\java\com\mythichelm\localnotifications\LocalNotificationsPlugin.java:129: error: cannot find symbol
        NotificationManagerCompat notificationManager = getNotificationManagerCompat();
        ^
  symbol:   class NotificationManagerCompat
  location: class LocalNotificationsPlugin
C:\flutter\.pub-cache\hosted\pub.dartlang.org\local_notifications-0.0.7\android\src\main\java\com\mythichelm\localnotifications\LocalNotificationsPlugin.java:161: error: cannot find symbol
        return NotificationManagerCompat.from(getActiveContext());
               ^
  symbol:   variable NotificationManagerCompat
  location: class LocalNotificationsPlugin
17 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':local_notifications:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin flutter_local_notifications...
The plugin flutter_local_notifications could not be built due to the issue above.
Exited (sigterm)

**Comment by MaikuB** [comment]
Your logs mention `local_notifications-0.0.7`, which isn't this plugin. Though strangely I can see `flutter_local_notifications` mentioned at the end, which is this plugin. Not sure if you are somehow using two different notification plugins. Please double check

**Comment by MaikuB** [comment]
Closing since there's been no further response on this for a while
