### ISSUE TITLE
Create a way to schedule notifications daily starting in a x day

### ISSUE THREAD

**Issue by Lima21** [MaikuB/flutter_local_notifications#484]
Create a way to schedule notifications daily starting in an x day
Example: I want to show a notification every day to a user but I need the notifications starting to show in the next week

**Comment by MaikuB** [comment]
This has been asked before in https://github.com/MaikuB/flutter_local_notifications/issues/438 and isn't something offered by the native notification APIs for the plugin to wrap around. I believe you'll need to look into your own custom solution to solve this problem

**Comment by Lima21** [comment]
Thank you ;)
