### ISSUE TITLE
Update the contents of an existing notification

### ISSUE THREAD

**Issue by chiragmittal19** [MaikuB/flutter_local_notifications#486]
I want to update the contents of a notification which already exists in the notification panel. Currently using the following code to show notification. If I use this with same notificationId, it does override the notification, but it also plays sound and vibration like a new notification is created.

Code -

    import 'package:flutter_local_notifications/flutter_local_notifications.dart';

    class NotificationUtil {

      static void showNotification(FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin,
          int notificationId, String title, {String channelId = "ThirdWave Notifications",
            String channelName = "ThirdWave Notifications",
            String channelDescription = "ThirdWave Notifications", String subtitle,
            bool showProgress = false, int maxProgress = 0, int progress = 0,
            bool autoCancel = true, bool ongoing = false, bool enableVibration = true,
            bool playSound = true
          }) async {

        var androidPlatformChannelSpecifics = AndroidNotificationDetails(
            channelId, channelName, channelDescription, autoCancel: autoCancel, ongoing: ongoing,
            showProgress: showProgress, maxProgress: maxProgress, progress: progress,
          playSound: playSound, enableVibration: enableVibration
        );
        var iOSPlatformChannelSpecifics = IOSNotificationDetails(presentSound: playSound);
        var platformChannelSpecifics = NotificationDetails(
            androidPlatformChannelSpecifics, iOSPlatformChannelSpecifics);

        await flutterLocalNotificationsPlugin.show(
            notificationId, title, subtitle ?? showProgress ? progress.toString() + "%" : null, platformChannelSpecifics);

      }

    }

Is there a way to update the notification with sound/vibration playing only in the first time?

**Comment by MaikuB** [comment]
Sound and vibration are tied to the notification channel and those settings remain fixed for every notification sent on that channel. One way might be to send your update using the same notification id but on a different channel that has different settings. Not something I've tried but I think it should work

**Comment by MaikuB** [comment]
Should clarify the above is related to Android since notification channels are specific to Android. On iOS there are details you can provide for each notification. See https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/IOSNotificationDetails-class.html.

Closing this as this is the extent of what I know. You can try asking the [community](https://flutter.dev/community) to see if they have an idea on this
