### ISSUE TITLE
Clearing badge number?

### ISSUE THREAD

**Issue by jaykovski** [MaikuB/flutter_local_notifications#492]
Is there a better/proper way of clearing badge number?
At the moment I am firing silent, empty notification (which user can't see) with a `badgeNumber: 0` to remove badge number, any better way?

**Comment by MaikuB** [comment]
Try https://pub.dev/packages/flutter_app_badger

**Comment by edwin-alvarez** [comment]
should this be part of the same plugin?

**Comment by MaikuB** [comment]
That kind of functionality uses a different set of APIs that has no relation to notifications so won't be included in this plugin.

**Comment by greymag** [comment]
Hello. I'm understand why you are not want to include this functionality in the plugin, but I would ask to consider it again. 

Here is why:
- Plugin provider an ability to set counter when we schedule a notification, but without resetting it - it's useless. 
- You suggest to use `flutter_app_badger` - and it is a solution, but it's not good one. I need one more dependency, which may not be supported in the future and which adds much more than needed (what affects the size of the application).
- Implementation of the feature - is one line and not affect any other parts of the plugin. So it does no harm those who don't need a feature, but it's makes life way more easier for those who needs it.

I'd make little PR #876 with adding this feature, hope you accept it. 

Regards!

**Comment by muarachmann** [comment]
@MaikuB I get your point but I think it will be harmless and more or less, a plus to this plugin. bwt the #876 works cool

**Comment by SalahAdDin** [comment]
@MaikuB could you provider an example about how to do this?

We can't found a event listener to update it when the notifications are comming.
