### ISSUE TITLE
More flexible frequencies

### ISSUE THREAD

**Issue by ssiddharth** [MaikuB/flutter_local_notifications#493]
Apologies in advance if this is not the right place to ask this (or I'm missing an obvious way to do this).

I'm looking to show notifications at a user set interval but from a quick look at the code, the enum only contains `EveryMinute, Hourly, Daily, Weekly`.

Is there a way I'm missing where I can repeat a notification every x minutes or hours? 

Thanks! Appreciate your work on this.

**Comment by MaikuB** [comment]
No there isn't a way to do so. I'm going to close this as there's an existing issue on this at https://github.com/MaikuB/flutter_local_notifications/issues/92
