### ISSUE TITLE
Android dependency 'com.android.support:support-compat' has different version for the compile (25.2.0) and runtime (27.1.0) classpath

### ISSUE THREAD

**Issue by samapraku** [MaikuB/flutter_local_notifications#5]
When I add   flutter_local_notifications: "^0.1.0" to pubspec.yaml, I get this error when I start my project.

> app:preDebugBuild'. Android dependency 'com.android.support:support-compat' has different version for the compile (25.2.0) and runtime (27.1.0) classpath. You should manually set the same version via DependencyResolution

I resolved it by adding the below to android\build.gradle file
```
allprojects {
    repositories {
       //...
    }
    subprojects {
        project.configurations.all {
            resolutionStrategy.eachDependency { details ->
                if (details.requested.group == 'com.android.support'
                        && !details.requested.name.contains('multidex') ) {
                    details.useVersion "27.1.0"
                }
            }
        }
    }
}
```

After it was resolved, there is still this warning in Run console

> Note: C:\Users\xxx\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\flutter_local_notifications-0.1.0\android\src\main\java\com\dexterous\flutterlocalnotifications\FlutterLocalNotificationsPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

**Comment by MaikuB** [comment]
I'll see if I'll get some time to look into it as this issue project in just working on in my spare time. If you happen to find a fix feel free to submit a PR :)

**Comment by MaikuB** [comment]
Also I think if you had changed the compilesdk version then that probably fixed the error. That probably needs to be done for the plugin as well

**Comment by MaikuB** [comment]
Took a look and can't reproduce your first problem and the cause of the deprecation warning (there's a Html.fromHtml method call). I'll address that in a later release once I've at least added a feature but it's nothing to really be concerned about IMO

**Comment by MaikuB** [comment]
I've fixed the deprecation warning now though you may still see some warnings in the code (those are around casting) so will close off the issue

**Comment by eggenstein** [comment]
Update for new versions using AndroidX:

Error:
```
Android dependency 'androidx.versionedparcelable:versionedparcelable' has 
different version for the compile (1.0.0-rc01) and runtime (1.0.0) classpath.
You should manually set the same version via DependencyResolution
```

Solution: Add:
```
if (details.requested.group == 'androidx.core'
    && !details.requested.name.contains('androidx') ) {
        details.useVersion "1.0.1"
    }
```
