### ISSUE TITLE
Why to override notifications delegate in AppDelegate? Selecting notification not trigger any callback on iOS.

### ISSUE THREAD

**Issue by pawlowskim** [MaikuB/flutter_local_notifications#501]
**Describe the bug**
`onDidReceiveLocalNotification` is not triggered when tapping on the notification.

**To Reproduce**
That's actually strange. It worked, then we work with other plugin that uses notifications, and suddenly it stopped working (I wrote some native code for deviceToken, other native library was updated - not open sourced, device target had to be changed to iOS 10) . So actually I don't have any 100% reproduce solution. Example app with above library works, but I don't want to configure firebase (yes, I'm using firebase as well).
**Expected behavior**
`onDidReceiveLocalNotification` or `onSelectNotification` should be triggered.

**Sample code to reproduce the problem**
I don't have.

But, I start digging and I cannot understand one thing.
Why do we need use this:
```
if #available(iOS 10.0, *) {
  UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate
}
```

It overrides delegate, so AFAIK we need to handle everything manually. But plugin does have handling implementation inside:
```
- (void)application:(UIApplication*)application
didReceiveLocalNotification:(UILocalNotification*)notification {
    if(@available(iOS 10.0, *)) {
        return;
    }
    if(![self isAFlutterLocalNotification:notification.userInfo]) {
        return;
    }
    
    NSMutableDictionary *arguments = [[NSMutableDictionary alloc] init];
    arguments[ID]= notification.userInfo[NOTIFICATION_ID];
    if (notification.userInfo[TITLE] != [NSNull null]) {
        arguments[TITLE] =notification.userInfo[TITLE];
    }
    if (notification.alertBody != nil) {
        arguments[BODY] = notification.alertBody;
    }
    if (notification.userInfo[PAYLOAD] != [NSNull null]) {
        arguments[PAYLOAD] =notification.userInfo[PAYLOAD];
    }
    [_channel invokeMethod:DID_RECEIVE_LOCAL_NOTIFICATION arguments:arguments];
}
``` 
But it also contains this return statement for iOS 10. I can't figure it out why this was added.

Right now, if I remove snippet from AppDelegate and this if statement from didReceiveLocalNotification everything starts working again.

**Comment by MaikuB** [comment]
> Example app with above library works, but I don't want to configure firebase (yes, I'm using firebase as well).

Do you mean you are using `firebase_messaging` with this plugin? If so then the issue you're running into is this one https://github.com/MaikuB/flutter_local_notifications/issues/111 and has no relation to the code snippets you've been posting further below. It's an issue with the `firebase_messaging` plugin. You can read the thread for more details, including a fork you can use.

> Why do we need use this:

It's needed for flutter to invoke the methods in the plugin and is required so it can work with other notification plugins like the `firebase_messaging` plugin

> It overrides delegate, so AFAIK we need to handle everything manually. 

That is incorrect, see above response.

> But plugin does have handling implementation inside:

That code for `didReceiveLocalNotification` actually has no relation to the registration of the notification delegate. As for why it was done, you can read the documentation https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1622930-application?language=objc. It's meant for iOS versions below 10 and is deprecated for iOS 10+, which has a new set of notification APIs

**Comment by pawlowskim** [comment]
@MaikuB Thanks for explanation. I have removed firebase_messaging and you are right, that is working. Changing iOS target from 8.0 -> 10 must have broken working feature for us.
