### ISSUE TITLE
Android Notification Icon not on every API-Version visible

### ISSUE THREAD

**Issue by sanders07** [MaikuB/flutter_local_notifications#503]
The notification Icon is visible in the Emulator and on some devices like the Samsung Galaxy S6 but on other devices the icon is just a grey square.

**Comment by MaikuB** [comment]
Follow steps on https://developer.android.com/studio/build/shrink-code#keep-resources that is linked in the readme

**Comment by MaikuB** [comment]
Closing due to lack of further response
