### ISSUE TITLE
How to cancel a daily notification?

### ISSUE THREAD

**Issue by urmilshroff** [MaikuB/flutter_local_notifications#509]
I have used the [showDailyAtTime](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#show-a-daily-notification-at-a-specific-time) feature to repeatedly display the same notification every day in my app. However, my users find it annoying and I want to publish an update which will cancel all the notifications for existing users, and never display them for new users. How can I achieve this? I couldn't find a "cancel" function in the documentation. Thanks in advance.

**Comment by MaikuB** [comment]
See https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/README.md#cancellingdeleting-all-notifications

**Comment by urmilshroff** [comment]
> See https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/README.md#cancellingdeleting-all-notifications

Thank you. For some strange reason, I thought that meant it would clear the notification from the notifications tray😅

**Comment by fauzi2107** [comment]
> See https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/README.md#cancellingdeleting-all-notifications

I'm sorry i'm still curious, if i have set for showDailyAtTime at 14:00 and before that time i cancell it, is it only cancel for today or another next day to?

**Comment by RafaRuiz** [comment]
Honestly I thought the same. Amending the README.md wouldn't be bad :)
