### ISSUE TITLE
Question regarding scheduled conditional notifications

### ISSUE THREAD

**Issue by MperorM** [MaikuB/flutter_local_notifications#510]
This function will show a notification every minute
```
flutterLocalNotificationsPlugin.periodicallyShow(RepeatInterval.EveryMinute)
```

even while the app is closed, which is almost what I'm trying to do. Is there a way to make it only show the notification conditionally?

So while the app is closed, every minute run a function, if the function returns true, then show the notification?

**Comment by MaikuB** [comment]
No this isn't something that can be done by the plugin. That kind of problem requires a more generic solution that periodically schedules work to be run.
