### ISSUE TITLE
Suggestion to allow add image url to local notification

### ISSUE THREAD

**Issue by OptivolveThiyraashDavid** [MaikuB/flutter_local_notifications#511]
I have suggestion, is that will be great if we can add image to the local notification? I think currently none of flutter local notification support this feature?

**Comment by MaikuB** [comment]
This is not supported as the native APIs don't support this in the first place

**Comment by OptivolveThiyraashDavid** [comment]
So Is that any way we can set image in the local notification bro?either bitmap or url?

**Comment by MaikuB** [comment]
Have you checked the example app? It demonstrates what how you can do and one is ability download an image and then use it later for the larger icon

**Comment by OptivolveThiyraashDavid** [comment]
I'm very sorry I didn't check it properly. Thanks again for your reply and for this wonderful library @MaikuB
