### ISSUE TITLE
Is there any way to repeat a notification with a different message everytime?

### ISSUE THREAD

**Issue by CedYF** [MaikuB/flutter_local_notifications#513]
I can easily repeat notifications with the plugin, but is there is anyway to make a unique random message?

var theList = ["hey","MAIKUB","my","friend","please find","how","I","can","do","you","GOD"];

Future<void> _repeatNotification() async {
    var androidPlatformChannelSpecifics = AndroidNotificationDetails(
        'repeating channel id',
        'repeating channel name',
        'repeating description');
    var iOSPlatformChannelSpecifics = IOSNotificationDetails();
    var platformChannelSpecifics = NotificationDetails(
        androidPlatformChannelSpecifics, iOSPlatformChannelSpecifics);
    await flutterLocalNotificationsPlugin.periodicallyShow(
        10,
        theList[Random().nextInt(theList.length)],
        //"REWIND",
        DateTime.now().toString(), RepeatInterval.EveryMinute, platformChannelSpecifics);
  }

This always shows the same random item and the same date.

**Comment by MaikuB** [comment]
What you've shown above is working as intended as the code evaluates the random number at the time the method is called. You'll need to looking into other libraries that can schedule general code to run. I believe some members of the community have used something like https://pub.dev/packages/workmanager, which you can evaluate.
