### ISSUE TITLE
[Question] dynamic (after building) notifications sounds, looking for hacks/Ideas 

### ISSUE THREAD

**Issue by terryBaz** [MaikuB/flutter_local_notifications#514]
I would like to give the user the ability to **change the notification sound** (ie: set notification sound dynamically and not from the prebuilt raw resources).

any hacks/Ideas ?

For now my **target users platform is android** ( so i am not seeking for any Ios support for now)
Thank you.

**Comment by MaikuB** [comment]
No I don't. You can look up the native Android notification APIs on what can be done and develop your own code to achieve this. As far as I know, what you're after isn't possible.
