### ISSUE TITLE
APP crashes when receiving push in foreground

### ISSUE THREAD

**Issue by kennenfromchina** [MaikuB/flutter_local_notifications#517]
**IMPORTANT**
If you are getting a build error on Android that mentions AndroidX incompatibilities, before reporting an issue, please make sure look at the error information carefully as there should be a URL that provides information on migrating your application to AndroidX.

Also note that the plugin has an example application that should cover all of the available functionality. Please check the example application and see if the functionality works before logging an issue. You'll need to clone the repository to run it

**Describe the bug**

**To Reproduce**
If applicable, steps to reproduce the behavior:

**Expected behavior**
If applicable, clear and concise description of what you expected to happen.

**Sample code to reproduce the problem**
Ideally, include a link to a repository that contains code that can reproduce the problem. Suggestion is to fork this repository to modify the example app. Note that without a sample, it'll be may be more difficult to reproduce the problem and/or investigate further

When I access IMSDK push and local push at the same time
APP crashes when receiving push in foreground
crash in this method

```swift
public func userNotificationCenter(_ center: UNUserNotificationCenter,
                                       willPresent: UNNotification,
                                       withCompletionHandler: @escaping (UNNotificationPresentationOptions)->()) {
        let showNotificationWhileAppOpen = willPresent.request.content.userInfo[SwiftLocalNotificationsPlugin.PRESENT_WHILE_APP_OPEN_KEY] as! Bool
        if (showNotificationWhileAppOpen) {
            withCompletionHandler([.alert, .sound, .badge])
        }
    }
```

**Comment by MaikuB** [comment]
Closing this as the code you have posted belongs to another plugin.
