### ISSUE TITLE
How to make the icon fill the white circle in notification bar?

### ISSUE THREAD

**Issue by realcarlos** [MaikuB/flutter_local_notifications#52]
Now I am using the code below to initialize 

      if( _sdkInt >= 22) {
        initializationSettingsAndroid = new InitializationSettingsAndroid('ic_notification');
      }

the white circle is my icon , I want it fill the whole circle.

**Comment by realcarlos** [comment]
I noticed that you are using 'setSmallIcon' to set icon , but I think we need add a option 'setLargeIcon' methond after Android Lolipop .

**Comment by MaikuB** [comment]
If that were true then the example app would have the same problem you showed but it doesn't exhibit that behaviour on Lollipop. You can run that to verify. Have you checked if your image meets the Android guidelines? 

https://developer.android.com/guide/practices/ui_guidelines/icon_design_status_bar

**Comment by MaikuB** [comment]
That just shows that there's no issue because there isn't a white circle...

**Comment by realcarlos** [comment]
Yes, but the problem is the size of the icon is too small :)

**Comment by MaikuB** [comment]
My bad, I see what you're getting it. Been misreading what you said the whole time. Thought you meant to say you want the white circle gone. I gotcha now

**Comment by MaikuB** [comment]
Added this to version 0.3.0. See updated example app for sample code on how to specify the large icon
