### ISSUE TITLE
Isn't It possible to create reminders for selected days in a weed

### ISSUE THREAD

**Issue by being-yash-t** [MaikuB/flutter_local_notifications#520]
```
List daysToRepeat = [DateTime.sunday, DateTime.monday];
ScheduleNotifications.schedule("Notification Text", DateTime.now(), daysToRepeat);
```

Need to send notifications something like this, will this be available later in any update??

**Comment by MaikuB** [comment]
No as the native notification APIs don't support this. if your use case is to create a reminder then consider using https://pub.dev/packages/device_calendar
