### ISSUE TITLE
Question: Do multiple initializations reset notifications?

### ISSUE THREAD

**Issue by emptyopen** [MaikuB/flutter_local_notifications#521]
I seemed to be having intermittent notifications (I specifically notice this on Android), so I tried initializing any time there is an update to the screen. I'm sure this is a bad practice, but I can't seem to find anything on intermittent notifications and possible solutions.

**Comment by MaikuB** [comment]
No they don't reset notifications but will cause problems where the `onSelectNotification` callback may be called multiple times if you can `initialize` in multiple places. I don't understand what you mean by intermittent notifications but if can't any similar reported issue then there's a chance there's a bug in your app

**Comment by MaikuB** [comment]
Closing since there's been no response to provide more info
