### ISSUE TITLE
Android Notification Icon

### ISSUE THREAD

**Issue by bretie** [MaikuB/flutter_local_notifications#522]
There are vague instructions on how to initialize Android settings with a default icon. You show in the example app to use 'app_icon'. Looking through the files I do not see any resource named 'app_icon' using a recursive search.

Can you provide more detailed information on how to configure Android icons?

**Comment by MaikuB** [comment]
Refer to the links in the Android docs linked to in the readme [here](https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/README.md#adding-notification-icons-and-sounds). They are linked to as they are essentially the source of truth that will get updated with the various guidelines on sizes for the images.

I'm not sure what kind of search you did the image is there. See https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications/example/android/app/src/main/res/drawable

**Comment by atheros** [comment]
I think this article explains better how to use the icon: https://medium.com/@nitishk72/flutter-local-notification-1e43a353877b

In short, place the icon file in [flutter_app_name] > android > app > src > res > drawable > app_icon.png

**Comment by MaikuB** [comment]
It may have the location but doesn't explain the sizes required and that requires having multiple images at different resolutions that the Android documentation covers. Based on the two responses given, I believe that should be sufficient to solve @bretie's issue as the location has been pointed out
