### ISSUE TITLE
notification doesn't work on android under version 9

### ISSUE THREAD

**Issue by vivinapriyanti** [MaikuB/flutter_local_notifications#524]
hello, i'm trying use this plugin, when i run on android 9 it works properly. but in android version 6.0.1 and 8.1.0 it doesn't work and show error 'Unfortunately, system ui has stopped.' 

is there any required android version beside Supported Platforms mentioned? or any way to handle that? 

thank you

**Comment by MaikuB** [comment]
It should work on all Android versions supported by Flutter.

- Does this happen on an emulator as well?
- If you clone the repository and run the example app on the same devices/emulators you saw this behaviour on, do you see the same problem?

**Comment by vivinapriyanti** [comment]
i've already try your example on android 8 and 9 working properly. but, on android 5 and 6 (emulator) doesn't work at all.

**Comment by MaikuB** [comment]
Have you run the standard counter app on Android 5 and 6 emulators? Off memory you can't do that in general with passing in an additional flag so won't have anything to do with this plugin

**Comment by MaikuB** [comment]
Closing due to lack of further response
