### ISSUE TITLE
Question: What set up needs to be done on Android head project for notification scheduling to work

### ISSUE THREAD

**Issue by Roshanalexander** [MaikuB/flutter_local_notifications#527]
Having trouble getting scheduled notification on Android to work. On-demand notification seems to work fine and on iOS, both on-demand and scheduled notifications work fine.

I would like to know if I need to do something specifically to get the scheduled notification to work on Android.

I set up and new project with the example code in this repository and is having the same issue.

**Comment by MaikuB** [comment]
https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/README.md#configuration-for-scheduled-notifications

**Comment by Roshanalexander** [comment]
Thanks @MaikuB 

I missed that. 😄
