### ISSUE TITLE
Question: Volume settings and iOS critical alerts

### ISSUE THREAD

**Issue by Finn0811** [MaikuB/flutter_local_notifications#528]
Hi!

First of all, thank you for your work on this addon, it really helps me a lot!

I'd like to ask two questions:
1. Is it possible to modify the volume used to play the notification sound? I'd like the user to be able to define a volume level, which will overwrite the current level.

2. Is it possible to send [critical alert notifications](https://developer.apple.com/documentation/usernotifications/unnotificationsettings/2963116-criticalalertsetting) on iOS? I currently don't see an option for that so I'd really like to see it in a futre version if possible.

**Comment by MaikuB** [comment]
1. As far as I know, this isn't possible
2. Nothing has been implemented to allow for this. The code is open-source so you can contribute in adding features that you need

**Comment by Finn0811** [comment]
Unfortunately I have no experience with native code, yet.
Maybe someone else can do it, otherwise I might try to look into it at some time.

**Comment by MaikuB** [comment]
For what it's worth, I didn't either before this project and I only work on this in my spare time

**Comment by Finn0811** [comment]
The main purpose of my app is to alert people using push notifications. Critical alerts on iOS are very handy because it overwrites the silent mode etc. :)

**Comment by MaikuB** [comment]
You mention push notifications and that's the scenario critical alerts are used for but this plugin is for local notifications. It's more appropriate to be looking at the plugin you're using for push notifications (assuming you're using one) to request those permissions

**Comment by Finn0811** [comment]
Currently I only transfer data messages and build notifications using this plugin because it's the only way to get background notifications working. 

My idea was to send an argument like "critical: true" and build a critical notification using this plugin if the user enabled that feature in their settings. If its disabled it'll just build a normal notification (already working).

**Comment by MaikuB** [comment]
I assume you read that critical alerts require a special entitlement from Apple

**Comment by Finn0811** [comment]
Yes, that should be no problem

**Comment by MaikuB** [comment]
Closing due to lack of interest and updates. Please submit a PR if you need this functionality

**Comment by Finn0811** [comment]
Still no macOS environment to work on this but for sure in the future ;)

**Comment by systemtechnikfey** [comment]
> Still no macOS environment to work on this but for sure in the future ;)

Hi @Finn0811 ,
were you successful in implementing critical alerts?

**Comment by Ted-Zhang** [comment]
> > Still no macOS environment to work on this but for sure in the future ;)
> 
> Hi @Finn0811 ,
> were you successful in implementing critical alerts?

Critical alerts was quite straight forward for us, we submitted the entitlement request to Apple, then regenerated the provision file for our app, and update the firebase payload to enable the critical alert. If you also want to invoke this local notification plugin, could includes content-available in your payload to trigger the backend code. 

Skip the "code part", I think it described how to set it up.
https://stackoverflow.com/questions/66057840/ios-how-do-you-implement-critical-alerts-for-your-app-when-you-dont-have-an-en

**Comment by Maqcel** [comment]
Is it implemented? I can see `critical` inside request permissions for IOSFlutterLocalNotificationsPlugin

**Comment by Levi-Lesches** [comment]
Seems like it is:
- use requestCriticalPermission in your DarwinInitializationSettings
- Check plugin.checkPermissions().isCriticalEnabled 
- use InterruptionLevel.critical in your notification details

**Comment by ininmm** [comment]
Hi @Levi-Lesches thanks for your comment, it helps me a lot. I have another feature that we need to control the volume of the notification, and I've noticed that apple doc already implement a method [criticalSoundNamed](https://developer.apple.com/documentation/usernotifications/unnotificationsound/criticalsoundnamed(_:withaudiovolume:)). 

Is there any plans to implement this feature into the package?

**Comment by Levi-Lesches** [comment]
Interesting, seems a volume field could be added to the Darwin details that must be used with critical. 

I'm focusing more on the windows, android, and web sides of this plugin and don't have an iOS device to test on, so I cannot help here
