### ISSUE TITLE
schedule day interval

### ISSUE THREAD

**Issue by RobertBrunhage** [MaikuB/flutter_local_notifications#53]
I have a Duration which is, for example, two days and four days.

Is there any way we can schedule a notification to happen every two days and every four days?

**Comment by MaikuB** [comment]
unfortunately there isn't a way to do that via the plugin as each platform has limitation (particularly for iOS versions < 10) so it's not possible to provide an abstraction that works for all of them that would do what you're after. If you don't care about those iOS versions, feel free to fork/grab a copy of the plugin code and modify it to do what you're after

**Comment by RobertBrunhage** [comment]
Is it possible to select which days a notification will be shown, or is it only every day, every week and so on?

like, is there any way at all to select multiple days a week? :)

**Comment by MaikuB** [comment]
Only every day at a specific time and every week on a specific day and time. Both of these are covered in the readme so if you haven't checked it already, please take a look at that and the example code as it covers all the available functionality. API docs are also available on pub listing for the plugin at https://pub.dartlang.org/packages/flutter_local_notifications

If you need to show notifications on a weekly basis for a number of selected days each week then you could simply make multiple calls to the `showWeeklyAtDayAndTime`

**Comment by RobertBrunhage** [comment]
Thanks that solved my problem! Never thought about calling it multiple times.
