### ISSUE TITLE
Question: Clearing notifications

### ISSUE THREAD

**Issue by CyberGhost007** [MaikuB/flutter_local_notifications#530]
How to clear notification from Notification Tray after we tap on that.

**Comment by MaikuB** [comment]
The operation system should take care of that on its own. The only exception is if had an ongoing/sticky notification on Android. If you are still seeing a notification after tapping on it then you'll need to debug to see why it's still there. Could be you still have code to display one somewhere within the flow of handling when it is tapped

**Comment by CyberGhost007** [comment]
Is there any method to manually clear notifications from the Notification Tray?

**Comment by MaikuB** [comment]
https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/README.md#cancellingdeleting-a-notification

If you clone the repository, there's an example app that you can run
