### ISSUE TITLE
Unable to disable vibration

### ISSUE THREAD

**Issue by cormalenv** [MaikuB/flutter_local_notifications#531]
As per title I am unable to disable vibrate using the code below

All notifications are being channelled through the `displayNotification` method below. There are no other notifications called outside this method. All notifications from the start therefore have `enableVibration: false`.

Am I doing something wrong here?

```
void initialiseNotifications() async {//the following is all linked to notifications https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/example/lib/main.dart
  var initializationSettingsAndroid = AndroidInitializationSettings('@mipmap/ic_launcher');
  var initializationSettingsIOS = new  IOSInitializationSettings();
  var initializationSettings = InitializationSettings(
      initializationSettingsAndroid, initializationSettingsIOS);
  await flutterLocalNotificationsPlugin.initialize(initializationSettings);
}

void displayNotification(int _id, String _title, String _body) async {
  var androidPlatformChannelSpecifics = new AndroidNotificationDetails(
      'your channel id', 'your channel name', 'your channel description',
      enableVibration: false, playSound: false, importance: Importance.Min, priority: Priority.Min);
  var iOSPlatformChannelSpecifics =
  new IOSNotificationDetails(presentSound: false);
  var platformChannelSpecifics = new NotificationDetails(
      androidPlatformChannelSpecifics, iOSPlatformChannelSpecifics);
  await flutterLocalNotificationsPlugin.show(
    _id,
    _title,
    _body,
    platformChannelSpecifics,
    payload: 'No_Sound',
  );
}
```
Doctor output 
```
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.476], locale en-AU)
    • Flutter version 1.12.13+hotfix.8 at ...
    • Framework revision 0b8abb4724 (5 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at ...
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at ...
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • Redmi 6 • 672382f37d26 • android-arm • Android 8.1.0 (API 27)

• No issues found!
```

**Comment by MaikuB** [comment]
Vibration is tied to the notification channel and that setting will remain unless you recreate the channel. You've likely had this enabled before and simply changing the setting won't work. If you uninstall the app then I believe it should work

**Comment by cormalenv** [comment]
Yep that works. So the notification is set permanently for that channel on the first install not just the first call in the app. Closing/reinstalling (say from AS) then does not change the settings for the channel. Only a complete uninstall and reinstall will effect a change.

Thanks @MaikuB

**Comment by MaikuB** [comment]
It's set in the first call to create a notification. There are ways to update the setting it (see https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/AndroidNotificationDetails/channelAction.html) but in most cases apps aren't updating channel settings. I normally get reports of this issue when development work isn't completed and developers decide to change the channel settings midstream

**Comment by cormalenv** [comment]
Thanks. Yep I noted it was set in the first call but didn't appreciate that this was the first call of the first install. Sorry to raise a bug then. Hopefully your response here will help others and prevent further reports of the issue!

**Comment by UffizioHimanshu** [comment]
Hey I am unable to disable vibration. Can you please help me with it.
