### ISSUE TITLE
[Android] Notification is not displayed at the top of the screen

### ISSUE THREAD

**Issue by IsaacKB** [MaikuB/flutter_local_notifications#532]
**IMPORTANT**
I've been trying to solve this problem for almost 1 full week, I've seen most of the reported problems similar to mine and I've tried several solutions considered and none of them worked for me, I'm starting to get distressed because I can't find any answer and my last one choose to write this document begging for help.

I'm using a stable version of flutter v1.12.13 + hotfix.8 I've tried to downgrade and it's always the same result

At the moment I have a clean project, with nothing implemented, just what is requested in README.md. I've tried with the following devices: XIAOMI REDMI NOTE 7, SAMSUNG GALAXY S9; and so far with none of them I got the desired result

**Flutter Doctor**
[flutter_doctor.txt](https://github.com/MaikuB/flutter_local_notifications/files/4341714/flutter_doctor.txt)

**To Reproduce**
1. flutter create myapp;
2. I followed the README.md file step by step!;
3. and android integration!;
4. notification is not displayed as in the example video (there is only one icon in the notification bar);

**Expected behavior**
My expectation was that it would appear if the notification popup on top of the screen.

**Sample code to reproduce the problem**
The code is simply the "flutter create" that comes with a counter and nothing else with the README.md step by step followed

**Comment by MaikuB** [comment]
You need to set the appropriate importance and priority level. See official docs at https://developer.android.com/guide/topics/ui/notifiers/notifications#Heads-up for reference

**Comment by MaikuB** [comment]
Want to also point out that the importance is linked to a notification channel so if you initially sent a notification to a channel with a lower importance level and change it to a higher level in your code later, the initial setting will stick unless you uninstall and reinstall the app

**Comment by IsaacKB** [comment]
♥ I LOV U ♥ Tnks u so much♥

so that I can configure the channel and the importance can I follow this next tutorial smoothly?

https://developer.android.com/training/notify-user/build-notification#Priority

**Comment by IsaacKB** [comment]
So answering about uninstall and reinstall the application. 
I tried several times to do this, the problem is that it ignores the importance that I always configure at the beginning or at any time, and most of the tests done (not to say they were all) were applied with the importance in MAX and the priority at HIGH

**Comment by MaikuB** [comment]
> so that I can configure the channel and the importance can I follow this next tutorial smoothly?

> https://developer.android.com/training/notify-user/build-notification#Priority

No, you're writing a Flutter application so the tutorial isn't going to apply.

> I tried several times to do this, the problem is that it ignores the importance that I always configure at the beginning or at any time, and most of the tests done (not to say they were all) were applied with the importance in MAX and the priority at HIGH

Importance is tied to a channel so if you have code that sends notifications to the same channel but different importance levels then that could be the other cause of your problem.

Looks like you're problem is solved though so going to close this
