### ISSUE TITLE
AndroidX incompatibilities in a plugin

### ISSUE THREAD

**Issue by kasrasaeed** [MaikuB/flutter_local_notifications#535]
hey, i have below error while just after installing the package and run and so my app does not run.
do you have any idea how can i fix it?

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find media.aar (androidx.media:media:1.1.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/media/media/1.1.0/media-1.1.0.aar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 46s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin flutter_local_notifications...
Running Gradle task 'assembleAarRelease'...
Finished with error: The plugin flutter_local_notifications could not be built due to the issue above.

**Comment by MaikuB** [comment]
> do you have any idea how can i fix it?

No I don't. Likely an issue in your Android environment (given the url exists, not sure if you have a firewall issue) or Android project (check that it's using AndroidX)

**Comment by MaikuB** [comment]
If you're running Android Studio 3.6, I heard there were issues with it using together that I'm not sure it's related to your issue. There's a solution for it https://flutter.dev/docs/get-started/install/macos#install-android-studio

**Comment by kasrasaeed** [comment]
Fixed by running below command for those who has the same problem:
<YOUR APP DIRECTORY> cd android> gradlew build --stacktrace 

At this time my flutter ver and dart sdk ver are latest versions. Also android studio v 3.5
