### ISSUE TITLE
Progress Update

### ISSUE THREAD

**Issue by netofontess** [MaikuB/flutter_local_notifications#536]
Hi!

Great job with this Project...

I want to know if I can stop jumping the pop-up every time I edit a notification. I am using the progress and whenever I change the value, it is jumping on the screen.

Tk's!

**Comment by MaikuB** [comment]
I think you can get around that by making it an ongoing/sticky notification

**Comment by netofontess** [comment]
It worked!
I also defined the priority and importance to low...

Thanks!
