### ISSUE TITLE
IOS foreground notification does not work

### ISSUE THREAD

**Issue by realrnbboy** [MaikuB/flutter_local_notifications#537]
hi
i use example(https://pub.dev/packages/flutter_local_notifications#-example-tab-). ctrl c,v.
android perfectly working, but ios does not work in foreground.

what i miss.

help me. please

[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.14.6 18G1012, locale ko-KR)
 
[!] Android toolchain - develop for Android devices (Android SDK version 27.0.3)
    ✗ Flutter requires Android SDK 28 and the Android BuildTools 28.0.3
      To update using sdkmanager, run:
        "/Users/benife/Library/Android/sdk/tools/bin/sdkmanager" "platforms;android-28" "build-tools;28.0.3"
      or visit https://flutter.dev/setup/#android-setup for detailed instructions.
    ✗ Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[!] Android Studio (version 3.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (1 available)

**Comment by MaikuB** [comment]
Did you check the readme?

**Comment by realrnbboy** [comment]
thank you.

It was because firebase_message and flutter_local_notifications were used together.
I'll search for more problems where the two collide.

**Comment by nutjaa** [comment]
@realrnbboy Did u slove issue ? i also used firebase and cannot make foreground notification working

**Comment by realrnbboy** [comment]
@nutjaa yes. i used updated plugin - flutter_local_notifications: ^1.4.0 over
setting is same. - https://pub.dev/packages/flutter_local_notifications
good luck.
