### ISSUE TITLE
Notification icon won't show on flutter build, shows a filled square instead 

### ISSUE THREAD

**Issue by TheWCKD** [MaikuB/flutter_local_notifications#538]
Hello, 

The issue I'm facing is pretty simple.

When I run ```flutter run --release```, the notification icon is showing perfectly as you can see here.

![image](https://user-images.githubusercontent.com/37099416/76954645-59ce1b80-6919-11ea-8400-501569d24e5d.png)

But when I run ```flutter build```, after the fat apk builds and I install it manually on my device, the issue appears.

![image](https://user-images.githubusercontent.com/37099416/76954749-8aae5080-6919-11ea-8e22-87d208221548.png)

Do you have any idea on what may cause this? I'm running the latest version of flutter_local_notifications and latest flutter channel master.

Thank you!

**Comment by MaikuB** [comment]
This happens when you haven't done all of the steps mentioned [here](https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/README.md#release-build-configuration), particularly the one around resource shrinking

**Comment by TheWCKD** [comment]
> This happens when you haven't done all of the steps mentioned [here](https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/README.md#release-build-configuration), particularly the one around resource shrinking

Thank you so much, I actually read that but didn't know how to configure that proguard file. Will try again and let you know! Thank you again!

**Comment by MaikuB** [comment]
Whilst the Proguard rules need to be setup, it's the other paragraph on making sure your resources are kept by R8 that is the main cause of your problem

**Comment by TheWCKD** [comment]
> Whilst the Proguard rules need to be setup, it's the other paragraph on making sure your resources are kept by R8 that is the main cause of your problem

Thank you so much for your help, mate, everything is fixed now! I really appreciate your time and help! Thank you again! I'll close the issue now.
