### ISSUE TITLE
push notification in background 

### ISSUE THREAD

**Issue by II11II** [MaikuB/flutter_local_notifications#540]
I could not find accurate information how to use this plugin in background or when the app is terminated. Could you provide with potential guides please

**Comment by MaikuB** [comment]
I believe you are confused on what this plugin is for. This is not a plugin for **local** notifications not push notifications. There is no need for such guides as local notifications can be scheduled to appear in the future where they will appear even if the app is in the background or terminated. It is up to your app to decide when to display them. This isn't something sent by a remote server
