### ISSUE TITLE
Notification get 2 builder when application are on first plan

### ISSUE THREAD

**Issue by baaaaaziiiiingaaaaa** [MaikuB/flutter_local_notifications#543]
Hello,

I progress little by little on my application, and the module works. 

But I don't find it ok that when you click on the notification and the application remains in the foreground there is 2 times the call "Future onSelectNotification". 

This it generates two "builder: (_) => new AlertDialog" and it is necessary press's tuch the bouton two time "back".
I have print to console "debugPrint("payload : $payload");" to function "onSelectNotification"

![1](https://user-images.githubusercontent.com/21372462/77254586-33ceb100-6c62-11ea-96fe-64e81cc7afef.png)
![2](https://user-images.githubusercontent.com/21372462/77254585-33361a80-6c62-11ea-9644-fc2facf261d5.png)
It's ok if we close or switch to another application.

Thanks for you help

Github : [https://github.com/baaaaaziiiiingaaaaa/flutterLocalNotifications](url)

**Comment by MaikuB** [comment]
This has been raised before. See https://github.com/MaikuB/flutter_local_notifications/issues/462#issuecomment-580981640. This is an issue with Flutter
