### ISSUE TITLE
onLaunch is not clearing when logout

### ISSUE THREAD

**Issue by balajiks-dev** [MaikuB/flutter_local_notifications#544]
Hi,
I'm using flutter_local_notification package.
When the app is killed and tap on the notification it launches and navigate to the Notification List Page. But when I logout from the user and login , it navigating to the Notification List Page instead of home_page. How to clear the Notification onLaunch data while logout.

**Comment by MaikuB** [comment]
From what I'm reading, this isn't really a issue to do with this plugin but issue on how you should manage your state that you should be solving or use one of the sites at mentioned at https://flutter.dev/community to seek help

**Comment by balajiks-dev** [comment]
@MaikuB  Okay Close this issue.
