### ISSUE TITLE
Daily and Schedule Notification Issues

### ISSUE THREAD

**Issue by kosong0926** [MaikuB/flutter_local_notifications#545]
Hello,Sir. How are you?
I am trying with Daily and Schedule Notification.
I have already implement Normal Notification. It is working well.
But the Daily and Schedule Notification is not working without any issues in android platform.
And I tried your example code. It is great.
Could you help me, please?
Thanks
![Capture](https://user-images.githubusercontent.com/54272208/77315700-f55cf300-6d42-11ea-9952-3822f35662cc.PNG)

**Comment by MaikuB** [comment]
Please follow the instructions in the readme

**Comment by kosong0926** [comment]
Thank you for your reply.
I followed the instructions in the readme.
So the simple notification is working now.
But Schedule and Daily Notification is not working.
How do you think about it?

**Comment by MaikuB** [comment]
I still suspect you haven't actually done so. Please provide a link to a repository that can reproduce this issue

**Comment by MaikuB** [comment]
A few things to add

- I edited my original reply with a link to the relevant section but not sure if you saw that. That is what I often see people missing that is the cause of scheduled notifications not working on Android
- I'm not sure why you posted your screenshot as it doesn't help show anything that is relevant to what's needed to configure the app to work with the plugin
- There's an example app in the repository that you can use for reference to see what you've missed

**Comment by kosong0926** [comment]
I checked example app carefully.
I just missed "configureFlutterEngin" function  in "app/src/main/java/.../MainActivity.java" and "final MethodChannel platform =
  MethodChannel('crossingthestreams.io/resourceResolver');" in main.dart.
So I thought this issue because of missing its.
I think it is not because of its now.
So I am trying copy your example to new flutter project.

**Comment by MaikuB** [comment]
Those are not relevant, otherwise they would be mentioned in the readme. I'm concerned you are copying things blindly, it's stated in the example Dart code that simply copying the code won't work either. If anything you should check the manifest file, which is mentioned in the section of the readme i had linked to above

**Comment by kosong0926** [comment]
yeah, I have already checked manifest file and implemented it to new project.
I hope it will be working well.
As soon as finish it, I will message you
Thank you

**Comment by kosong0926** [comment]
It is working well now.
Thank you
