### ISSUE TITLE
only after release- the icons of the notification appears as black square

### ISSUE THREAD

**Issue by ShiraNeuman** [MaikuB/flutter_local_notifications#546]
In debug, it works perfect and the icons are shown, but after release when the notification pop the icons are filled black square as shown in the picture. It worked fine before and I didn't change anything so someone has an idea what could cause this? 
The version I use is 1.3.0.
![20200323_220911](https://user-images.githubusercontent.com/46919790/77358128-f5b0ba80-6d51-11ea-8ec9-07bfdde9ea39.png)

**Comment by MaikuB** [comment]
Please read the last few paragraphs on resource shrinking https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/README.md#release-build-configuration

**Comment by ShiraNeuman** [comment]
It worked! I missed this part of the documentation. Thank you very much!
