### ISSUE TITLE
Issue with pubspec.yaml

### ISSUE THREAD

**Issue by hamesjan** [MaikuB/flutter_local_notifications#555]
I was using flutter_local_notifications to build an app, however when I updated flutter, I started receiving the following error message when I tried to call flutter pub get to retrieve the package in my pubspec.yaml file.

I was using flutter_local_notifications to build an app, however when I updated flutter, I started receiving the following error message when I tried to call flutter pub get to retrieve the package in my pubspec.yaml file.

**Could not find a file named "pubspec.yaml" in "/Users/jameshan/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-1.3.0".
pub get failed (66; Could not find a file named "pubspec.yaml" in "/Users/jameshan/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-1.3.0”.)**

I don’t really understand how to fix the error or if its an error with the actual plugin, however this started happening after I updated flutter so I’m thinking its an issue with the compatibility between the newest version of flutter and your plugin. 

I am using Android Studio and currently using Flutter 44.0.2 and Dart 192.7761. I am trying to code the app for iOS.

If someone could get back to me about how I could fix the issue or if it just a compatibility issue, that would be awesome!

**Comment by MaikuB** [comment]
This won't be an issue with the plugin, your pub cache is likely corrupt or there's an issue with your SDK installation. There are solutions that can be found online for similar issues that can provide steps on deleting your pub cache. 

Sidenote: those versions you mentioned are to do with the Android studio plugins for Flutter and Dart. They are not versions of the Flutter and Dart SDK

**Comment by hamesjan** [comment]
Thank you Mr.MaikuB!!!
**flutter pub cache repair**
did it for me.
