### ISSUE TITLE
Ongoing (sticky) notification doesn't dismiss on app kill

### ISSUE THREAD

**Issue by Veerse** [MaikuB/flutter_local_notifications#559]
Hello, first I'd like to thank you for this awesome package. Helped me a lot.

I'm facing an issue. I'm making an audio player and I have a sticky notification for audio control.

The problem is that when I kill the application, the notification doesn't disapear. How to make the notification go when I kill the app from the app switcher ?

Here is my notification :

`var androidPlatformChannelSpecifics = AndroidNotificationDetails(
        '0', 'Channel', 'Channel description',
        importance: Importance.Max, priority: Priority.High, ticker: 'ticker',
        playSound: false, style: AndroidNotificationStyle.Media, channelShowBadge: false,
        visibility: NotificationVisibility.Public, autoCancel: false, ongoing: true,
      );`

**Comment by MaikuB** [comment]
The plugin has no way to know your app has been killed to support this, especially when users may use the plugin in a native Android app where part of it is done using Flutter (which means there may be multiple activities). As such, you'll likely need to write your own code that makes use of the native Android APIs for handling this. I'm not sure how you were planning to do the audio controls given that's something else that isn't supported either
