### ISSUE TITLE
Alarm for Specific Time

### ISSUE THREAD

**Issue by volcano2906** [MaikuB/flutter_local_notifications#560]
Hi,

i try to do alarm app, for example, i have six different specific time in my list such as List<timeofday> listt = [14:00, 15:40, 16:20 ] time between two time is constant. So i want to notify when this time come. But i cannot find how i can do that with your library, 
1- do i need store those information in phone local history
2- your code works in background even if terminated or closed app ?

Thanks

**Comment by MaikuB** [comment]
> 1- do i need store those information in phone local history

I don't know what you mean by "local phone history."

> 2- your code works in background even if terminated or closed app ?

Yes it does

General note here is the you most likely need to solve this on your own without using the plugin.
