### ISSUE TITLE
custom sound doesn't work on android

### ISSUE THREAD

**Issue by JakaboosD** [MaikuB/flutter_local_notifications#563]
I'm trying to play my own custom sound for my notifications on android. But on my android emulator, it just plays the default sound and on my personal device, it doesn't even make a sound (both run android 9).
```
FlutterLocalNotificationsPlugin _notifications = FlutterLocalNotificationsPlugin();

var initializationSettingsAndroid = AndroidInitializationSettings('app_icon');
var initializationSettingsIOS = IOSInitializationSettings();
var initializationSettings = InitializationSettings(initializationSettingsAndroid, initializationSettingsIOS);
await _notifications.initialize(initializationSettings);
var androidPlatformChannelSpecifics = AndroidNotificationDetails('test_channel', 'test', '', playSound: true, sound: RawResourceAndroidNotificationSound('my_sound'));
var iOSPlatformChannelSpecifics = IOSNotificationDetails();
var platformChannelSpecifics = NotificationDetails(androidPlatformChannelSpecifics, iOSPlatformChannelSpecifics);
await _notifications.show(0, 'test', 'this is a test', platformChannelSpecifics);
```

I don't get any errors. My file is in android/app/src/main/res/raw/my_sound.mp3

**Comment by MaikuB** [comment]
Note that the sound is tied to the notification channel, which is created the first time you try to show a notification against a particular channel ID. The settings passed in will persist so won't change even if you changed the settings around the sound but use the same channel ID. So if you went through using the default sound (which is what happens by default when you don't specify anything) to specifying a custom sound, you'll need to uninstall and reinstall the app

**Comment by MaikuB** [comment]
Regarding the sound not playing on your phone, you'll need to check the settings on your phone. The volume level is separate from getting notification sounds

**Comment by JakaboosD** [comment]
Thanks! That did the trick! On my personal phone it was the same problem. I had just been updating the app. I uninstalled and reinstalled the app and now it plays my custom sound!
