### ISSUE TITLE
Notification Icon not working in release build

### ISSUE THREAD

**Issue by briosheje** [MaikuB/flutter_local_notifications#566]
**Describe the bug**
Android icon does not work after build release on phisical device, although it works on the simulator with the debug build.

**To Reproduce**
I've added the notification icon in app/src/main/res/drawable (app_icon.png as mentioned in the docs).
Debug build works, but when releasing the icon does not work anymore.

**Expected behavior**
I would expect the icon to work in release mode as well.

May the problem, perhaps, be related to the fact that the flutter build process remove unused assets? If so, since the asset is located in the android folder and not included in the flutter assets it is likely removed in the build phase?

**Comment by MaikuB** [comment]
@briosheje that is correct, which is why developers need to follow the steps in https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/README.md#release-build-configuration

**Comment by briosheje** [comment]
> @briosheje that is correct, which is why developers need to follow the steps in https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/README.md#release-build-configuration

Oh, sorry, I didn't see that there was a section about the release configuration.

My apologies and thanks for the fast feedback!

**Comment by MaikuB** [comment]
No worries 😊
