### ISSUE TITLE
rich notification ios

### ISSUE THREAD

**Issue by sante85** [MaikuB/flutter_local_notifications#567]
**Describe the bug**
Is Difficult implement rich notification in ios?
 
Best Regads

**Comment by sante85** [comment]
{
    "aps": {
        "alert": {
            "body": "Push notification body",
            "title": "Push notification title"
        },
        "mutable-content": 1,
        category: "rich-apns"    
},
    "media-url": "https://i.imgur.com/t4WGJQx.jpg"
}

simple add "mutable-content": 1, and media url

**Comment by MaikuB** [comment]
What you're posting about here is for push/remote notifications not local notifications. Closing as it's not related this plugin

**Comment by fxyong** [comment]
Is there a way to implement a rich local push notification for iOS that shows an image?

**Comment by MaikuB** [comment]
@fxyong please look at the example app for displaying attachments

**Comment by fxyong** [comment]
> @fxyong please look at the example app for displaying attachments

I've just downloaded the example app and for iOS, none of the notifications is working. as for Android, it's showing me a blank screen.

**Comment by MaikuB** [comment]
> I've just downloaded the example app and for iOS

Can you elaborate more on exactly what you mean and did when you say you downloaded the app?

**Comment by fxyong** [comment]
> > I've just downloaded the example app and for iOS
> 
> Can you elaborate more on exactly what you mean and did when you say you downloaded the app?

sorry. i missed out on the configures parts. Now it's working on both iOS and Android. Thanks so much for the prompt reply! :)
