### ISSUE TITLE
custom sound does not work

### ISSUE THREAD

**Issue by F-James** [MaikuB/flutter_local_notifications#569]
Hi,
I have some question about the usage of custom sound.I clone the project and run it in my phone,but the custom sound does not work only virbation.So,it's maybe cause by phones or any other resaon.
And,thanks a lot for the project,It's saves a lot of work.

    var androidPlatformChannelSpecifics = new AndroidNotificationDetails(
        'test_channel', 'test', '',
        importance: Importance.Max, priority: Priority.Max,
        sound: RawResourceAndroidNotificationSound('slow_spring_board'),
        enableVibration: true,
        vibrationPattern: Int64List.fromList([0,1000,1000,1000]),
        playSound: true);
    var iOSPlatformChannelSpecifics = new IOSNotificationDetails();
    var platformChannelSpecifics = new NotificationDetails(
        androidPlatformChannelSpecifics, iOSPlatformChannelSpecifics);

**Comment by F-James** [comment]
run the demo and click Schedule notification to appear in 5 seconds ,custom sound... ,only virbate but custom sound does not work

**Comment by MaikuB** [comment]
Have you checked the settings of your phone to make sure they're correct? Being able to play a sound is completely separate from volume.

For example the following only give you vibration

![image](https://user-images.githubusercontent.com/25263378/78888900-f2356700-7aa5-11ea-82d0-77fa88fe63fb.png)

This however, will play notification sounds

![image](https://user-images.githubusercontent.com/25263378/78888924-01b4b000-7aa6-11ea-9631-e5acc4f59412.png)

**Comment by prabhunath111** [comment]
> run the demo and click Schedule notification to appear in 5 seconds, custom sound... ,only virbate but custom sound does not work
I am also getting the same issue. When I allowed for notification sound from settings manually then it's working otherwise not working.

**Comment by MaikuB** [comment]
@prabhunath111 if you're referring to general phone settings then that is going to be expected since you haven't allowed the phone to play a sound.

**Comment by F-James** [comment]
(url)
![Screenshot_2020-04-10-13-45-37-858_com dexterous flutterlocalnotificationsexample](https://user-images.githubusercontent.com/24688159/78966321-1fc7f200-7b32-11ea-834c-4ee0fe4a4b6a.jpg)  it's my phone's setting.I have uninstalled and reinstalled it,but  just vibration.

**Comment by MaikuB** [comment]
Given it's your phone's settings then there's no bug here. No app is suppose to play a notification sound if the general phone setting for it has been turned off. Closing

**Comment by F-James** [comment]
wow,it's working.Both the setting of system and application should be truned on, otherwise not working.thanks a lot.

**Comment by xiaoxiaohua333** [comment]
![5331586595141_ pic](https://user-images.githubusercontent.com/9317990/79039599-e0be9d00-7c14-11ea-87ba-0ba20eab96c6.jpg)

version: 1.4.1
device:OnePlus6T;10;

I am also getting the same issue. 
![5341586595335_ pic](https://user-images.githubusercontent.com/9317990/79039642-46128e00-7c15-11ea-9bd9-699ed0181b1e.jpg)

**Comment by MaikuB** [comment]
@xiaoxiaohua333 the plugin works fine so you will need to look into this to see what setting needs to be changed when Android OEMs put their customisations on the operating system

**Comment by xiaoxiaohua333** [comment]
OK , I have solved it , thanks !
