### ISSUE TITLE
Not make sound when notification is coming and i wanted add periodic notification for every 30 minutes, How can i do?

### ISSUE THREAD

**Issue by prabhunath111** [MaikuB/flutter_local_notifications#570]

**Comment by MaikuB** [comment]
Showing notifications for a custom period like 30 minutes isn't supported. Please see the example app on how to display notifications without a sound

**Comment by prabhunath111** [comment]
> Showing notifications for a custom period like 30 minutes isn't supported. Please see the example app on how to display notifications without a sound

Can you please add for 30 minutes?
