### ISSUE TITLE
Huawei or Xiaomi, the notice bar displays a white dot, and the drop-down view message icon is a gray box. How to deal with it

### ISSUE THREAD

**Issue by tianshangwuyun** [MaikuB/flutter_local_notifications#571]
Huawei or Xiaomi, the notice bar displays a white dot, and the drop-down view message icon is a gray box. How to deal with it

**Comment by tianshangwuyun** [comment]
The picture is transparent with white background

**Comment by tianshangwuyun** [comment]
Simulator is normal

**Comment by MaikuB** [comment]
https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#release-build-configuration

**Comment by briosheje** [comment]
@tianshangwuyun sounds like you had my exact problem: https://github.com/MaikuB/flutter_local_notifications/issues/566

Please read the documentation, you need to configure the release build for android as mentioned above.
