### ISSUE TITLE
Can system icons be used directly?

### ISSUE THREAD

**Issue by nioncode** [MaikuB/flutter_local_notifications#574]
Is it possible to use Android system icons as part of the notification?

For example, I'd like to use the equivalent of `builder.setSmallIcon(android.R.drawable.stat_sys_download)`. I tried simply providing the resource id as string with:
```dart
  var androidPlatformChannelSpecifics = AndroidNotificationDetails(
    'channel',
    'name',
    'description',
    icon: 'android.R.drawable.stat_sys_download',
  );
```
but this did not work.

Is there an easy way to re-use existing system drawables?

**Comment by MaikuB** [comment]
I don't believe so and my understanding is that using system icons is discouraged as they may change and differ amongst the Android OEMs. If you'd like to use them with this plugin then I think one way is to copy them from SDK into your own app and then you could reference the drawable by its name

**Comment by MaikuB** [comment]
Forgot to add is if you do need to use the system icons as you got there then you could fork the repository and make the modifications you need for it to work in your app. This won't be something I'll be looking to support in the plugin since it's not recommended to use so will be closing this.

**Comment by nioncode** [comment]
Thanks for the fast response. For anyone needing this, here is how I solved this for me:

Create an alias resource in `res/values/alias.xml` with the following content:
```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <drawable name="ic_stat_download_progress">@android:drawable/stat_sys_download</drawable>
</resources>
```

You can then use this drawable like any other drawable by string:
```dart
var androidPlatformChannelSpecifics = AndroidNotificationDetails(
  'channel',
  'name',
  'description',
  icon: 'ic_stat_download_progress',
);
```

**Comment by Aoi-hosizora** [comment]
@nioncode Actually you can use `@android:drawable/stat_sys_download` as icon parameter directly.

```dart
var details = AndroidNotificationDetails(
  NTF_CHANNEL_ID,
  NTF_CHANNEL_NAME,
  channelDescription: NTF_CHANNEL_DESCRIPTION,
  icon: '@android:drawable/stat_sys_download',
  // ...
);
```
