### ISSUE TITLE
schedule local notification by workManager 

### ISSUE THREAD

**Issue by 3than7** [MaikuB/flutter_local_notifications#577]
hi 
Can we schedule notification from background dart code
like using work manager plugin from executeTask method
as if i register service that run every hour and schedule today notification base on current location
I tried out but no luck.
Can anyone help me with that?

**Comment by MaikuB** [comment]
As this is not really a messaging board that the community will frequent to answer questions, I'd suggest you try one of the places listed at https://flutter.dev/community to get help. I don't have experience with this myself but have heard of others that have done so
