### ISSUE TITLE
Localize background notification

### ISSUE THREAD

**Issue by thphuc** [MaikuB/flutter_local_notifications#578]
I'm using firebase to implement notification. When the app receives events from firebase, I use this local notification library to show local notification.
All works well but now I want to localize the message in the notification.
When the app is on foreground, we can use the context to get locale and again it works.
But when the app is in background, I still don't find any solution to have the context to get the current language of the phone.
Does anyone face the same situation?

Here is how I catch the event from firebase:
```
 _firebaseMessaging.configure(
        onMessage: (Map<String, dynamic> message) async {
          _showInAppNotification(message, context);
        },
        onBackgroundMessage: (Map<String, dynamic> message) async {
          handleNotificationInBackground(message);
        },
        onLaunch: (Map<String, dynamic> message) async {
          print("onLaunch: $message");
        },
        onResume: (Map<String, dynamic> message) async {
          print("onResume: $message");
        });
```

In the handleNotificationInBackground(message) method, I need to localize the message before firing the notification. But I can not have the app context here...

**Comment by MaikuB** [comment]
Your issue is more of a general Flutter problem as such I'd recommend you ask on one of the sites listed at https://flutter.dev/community. The info on this thread may also help https://github.com/flutter/flutter/issues/14518

**Comment by MaikuB** [comment]
Also one thing I forgot to mention is perhaps you might need to consider having your app send the user's current/selected locale to your backend so that your backend sends the localised message.
