### ISSUE TITLE
iOS: Cancel Notifications not reset badge count

### ISSUE THREAD

**Issue by bierbaumtim** [MaikuB/flutter_local_notifications#580]
**Describe the bug**
If you cancel all notifications on iOS the badge count is not reset. 
I've looked at the code, and it looks to me like if only a specific notification is deleted, the badge count will not be updated either. But I never code on iOS so it is only a guess. 

**Expected behavior**
- Cancel all notifications should set the badge count to 0. 
- Cancel a specific notification should set badge count to the amount of left notifications
As example you have 10 notifications, if you cancel 1 of them the badge count should be 9.

**Comment by MaikuB** [comment]
Yep, this probably should be documented (better) but badge management is up to developers as the badge number to update to is application-specific. For example, an application may decide that 3 notifications from the same source should have the badge number set to 1. The native iOS notifications APIs only support setting the badge number when the notification is presented and it's not an increment operation, rather it sets it to the specified value.

You may need to consider using https://pub.dev/packages/flutter_app_badger

**Comment by bierbaumtim** [comment]
Your answer only explain the issue when cancelling a specific notifations but not when I cancel all notifications.

**Comment by bierbaumtim** [comment]
If I cancel all notifications there is no reason to have an badge count greater then 0. 
So in my opinion when you give the opportunity to set badge count, you also have to manage this badge count when no notification is available.

**Comment by MaikuB** [comment]
> Your answer only explain the issue when cancelling a specific notifications but not when I cancel all notifications.

> So in my opinion when you give the opportunity to set badge count...

This is only because the notification APIs provide a way to do so and giving access to those APIs is the primary purpose of the plugin

>...you also have to manage this badge count when no notification is available.

 As you mentioned you're not an iOS developer, I was trying to explain to you that within the native iOS APIs, deleting notifications and resetting the badge count are independent. So currently Apple separate the two.

I get where you're coming but I don't have plans to change this behaviour at the moment and there's a solution available.  If you'd like to see this change then feel free to submit a PR

**Comment by bierbaumtim** [comment]
I'm not happy with this, but I have to accept it.  The solution for me is unstable.
I will implement something which will work for me, but will not add this as PR.
