### ISSUE TITLE
Is it possible to display an image in a IOS notification ?

### ISSUE THREAD

**Issue by Yirmerah** [MaikuB/flutter_local_notifications#581]
Hi!

I want to know if we can display an image in a IOS notification like we can in a Android ?
You can check this video at 3:27 who will explain what i mean :  
https://youtu.be/lVDO58jCiCo?t=206

What i want to do is that, but with the IOSNotificationDetails in it too : 

Future<NotificationDetails> _icon(BuildContext context, Image icon) async {
  final iconPath = await saveImage(context, icon);

  final androidPlatformChannelSpecifics = AndroidNotificationDetails(
    'big text channel id',
    'big text channel name',
    'big text channel description',
    largeIcon: iconPath,
    largeIconBitmapSource: BitmapSource.FilePath,
  );

  return NotificationDetails(androidPlatformChannelSpecifics, null);
}

Thank you,

**Comment by MaikuB** [comment]
Yes you can. Have you taken a look at the example app [here](https://github.com/MaikuB/flutter_local_notifications/blob/60072d6806bf531ac2ec88570027a7a9445c7184/flutter_local_notifications/example/lib/main.dart#L323)

**Comment by Yirmerah** [comment]
Thank you for your reply
Oh no i didn't, and do you know if it's also possible to do a on going notification with image in it ?
I did not see anything similar.
I also try the example but i can't find where some functions are define in it.
Like for example :
BitmapFilePathAndroidIcon(largeIconPath),
Is it something that i have to define myself ?

**Comment by MaikuB** [comment]
Ongoing notifications for iOS aren't supported. If you're asking about Android then it should be supported and up to you to define it

**Comment by Yirmerah** [comment]
Ok, alright thank you.
I try to use the showSoundUriNotification but it's doesn't even display a notification, could you know why ?
I also try to use other notification with sounds but no sound coming..
I already check my emulator setting and everythings looks fine.
Notification sounds are activate and the volume is on.
Do you know why ?

**Comment by MaikuB** [comment]
No you need to investigate that and see if there are any logs. Also take note of the API docs for URI sounds at https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/UriAndroidNotificationSound-class.html. It's not for sounds hosted on the web

**Comment by Yirmerah** [comment]
Alright, i was thinking it was using the default actual notification sounds of the device.
Do you know how do we have the default notification sounds of the device has the notification sound ?

**Comment by MaikuB** [comment]
Sorry I don't understand what you're asking. If you want to play the default sound then you need to ensure [playSound](https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/AndroidNotificationDetails/playSound.html) is true and leave [sound](https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/AndroidNotificationDetails/sound.html) as null. Both of these points are covered in API docs.

If you have yet to do so please clone the repo and run the example app to explore the various functionality and code needed to implement.

Closing as the original question has been answered
