### ISSUE TITLE
Notifications not showing on iOS

### ISSUE THREAD

**Issue by ErnestoCuesy** [MaikuB/flutter_local_notifications#583]
Hi all

I think I'm missing some setup steps for iOS as I can't get the notifications to work. Everything is fine on Android. I've cut and pasted most of the sample app code to suit my needs and all the initialization steps on Dart have been done properly. The proof is that on Android notifications are working ok. I tried to compare iOS files on the sample project against mines as well as Xcode settings and I can't find any significant difference. Please share your thoughts. Thanks!

**Comment by andxingwu** [comment]
I have same problem, but only in release mode.

**Comment by MaikuB** [comment]
@ErnestoCuesy I would guess that the AppDelegate file within the iOS project hasn't been modified.

**Comment by ErnestoCuesy** [comment]
@MaikuB thanks for the clue. My project only has AppDelegate,swift and the example project has AppDelegate.h and AppDelegate.m, so I copied them across to my project and after the build the notifications are still not working. I'm not familiar with iOS development (as you can see) and I can't really figure out what is going on inside those AppDelegate files. Is there any other advice you can provide? Thanks!

**Comment by MaikuB** [comment]
You're not suppose to copy them across. I covered what's needed depending on if you have a Swift or Objective-C project in https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#ios-integration. Note a similar question around Swift was asked [here](https://github.com/MaikuB/flutter_local_notifications/issues/480) as well

**Comment by ErnestoCuesy** [comment]
@MaikuB sir, you deserve a round of applause! It's working now, thank you very much. Maybe a bit more detailed information in the README file for future noobs like me? Thanks again a have a great day!

**Comment by MaikuB** [comment]
@ErnestoCuesy i'm not sure what you mean by more detailed information in the readme as the steps were covered but you mentioned you were copying from example code as opposed to following the steps in readme. The steps also mention to add lines not to copy files.

**Comment by MaikuB** [comment]
@andxingwu there are no known issues around release mode so you'll need to investigate this. If there's an issue then I would expect the same problem to occur with the example app but haven't seen this happen

I'm going to close this now as the problem for the OP has been resolved

**Comment by ErnestoCuesy** [comment]
@MaikuB my apologies, sir. Everything is there. I think I rushed through the installation and overlooked those important steps. Kind regards.

**Comment by psyanite** [comment]
@MaikuB Seems like developers are missing out the last 2 sections "Android Integration" and "iOS Integration" sections of the README. I would suggest 2 things.

1. Add a table of contents section under "Acknowledgements" 
2. Putting the iOS and Android setup instructions first, before the "How to use" section (which will cover subsections like Initialisation, Display, Grouping notifications etc.)

Maybe this will save everyone's time :)

**Comment by MaikuB** [comment]
@psyanite How about a pull request? What you suggest may help in some cases. Most issues seem to be about copying code from the example without actually looking at the comments to say it won't work if that's done, or steps in the readme are followed but miss that getting started section says to do the integration

**Comment by psyanite** [comment]
Thought you'd never ask 😉 https://github.com/MaikuB/flutter_local_notifications/pull/648
