### ISSUE TITLE
Notification icon doesn't display on Galaxy S10+

### ISSUE THREAD

**Issue by huynhphu-pufu** [MaikuB/flutter_local_notifications#584]
**Describe the bug**

I have discovered an error. Specifically, when I run your example project, many devices works. However, with the S10 +, it has a gray icon as shown below. Thanks for your reading.

[image](https://drive.google.com/file/d/1iuLari-2XCZLOY8g34Y3-0hkhrX9qZOC/view?usp=sharing)

**Comment by MaikuB** [comment]
Did you clone the repo to run the example or did you copy the code? The problem you showed typically occurs when the steps mentioned at https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/README.md#release-build-configuration

**Comment by huynhphu-pufu** [comment]
I copied the code and run, my `proguard-rules.pro` file has the code line `-keep class com.dexterous.** { *; }`. I tried run code with `proguard-rules.pro` file of your example, and result is same.

**Comment by MaikuB** [comment]
Please read the last paragraph of the section of the docs I linked to. Setting up the Proguard rules isn't the only thing you're supposed to do

**Comment by huynhphu-pufu** [comment]
I have fully setup the steps that you noted. I tried devices running Android 10 that got the same bug, not just S10+. As for devices from Android 9 and earlier, the example works fine.

**Comment by MaikuB** [comment]
Have you tried cloning the entire repository and running the example from there to see if you have the same problem?

**Comment by huynhphu-pufu** [comment]
I can not run your example which I cloned, because it will make app stop. But I can publish my project running for you. Hope you do not mind.

**Comment by MaikuB** [comment]
Yes a link to a repository works as well

**Comment by huynhphu-pufu** [comment]
git clone https://phuhd-dev@bitbucket.org/phuhd-dev/flutter_local_notification_example.git

**Comment by huynhphu-pufu** [comment]
That's the project I discovered the bug on. It is copied just like your example project.

**Comment by MaikuB** [comment]
I took a look and you didn't do everything that was mentioned in the section of the documentation that I mentioned before. Note that I have a Pixel 4 XL with Android 10 as well. Please read through it carefully

**Comment by MaikuB** [comment]
Forgot to add I'm going to close this as this was an issue of not completing all the steps. Note that you didn't copy everything either

**Comment by huynhphu-pufu** [comment]
Yes, I will read it again, sorry for bothering you, thank you for your support.

**Comment by mahmoudatef925** [comment]
![WhatsApp Image 2020-11-19 at 7 27 26 PM](https://user-images.githubusercontent.com/36286101/99701901-c186c880-2a9d-11eb-8b2c-8957dc352d67.jpeg)
I followed all steps on  https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/README.md#release-build-configuration  
and the issue still existis
