### ISSUE TITLE
Badge Launcher Icon do not display

### ISSUE THREAD

**Issue by Yirmerah** [MaikuB/flutter_local_notifications#586]
Hi ! 

I'm trying to display a notification counter badge on Android, do you know if it's possible to do so?
Here the device i'm using:
![image](https://user-images.githubusercontent.com/56249904/79370462-fdc7d880-7f52-11ea-9d5b-becb029cae73.png)

Here my notification function:
Future<void> showNotificationMediaStyle(String notificationTitle,
    String notificationBody, String notificationMedia) async {
  var largeIconPath =
      await _downloadAndSaveFile(notificationMedia, 'largeIcon');
  var androidPlatformChannelSpecifics = AndroidNotificationDetails(
      'media channel id', 'media channel name', 'media channel description',
      importance: Importance.Max,
      priority: Priority.Max,
      color: Colors.blue,
      largeIcon: FilePathAndroidBitmap(largeIconPath),
      playSound: true,
      channelShowBadge: true,
      onlyAlertOnce: true);
  var iOSPlatformChannelSpecifics = IOSNotificationDetails(
      presentBadge: true,
      presentSound: true,
      presentAlert: true,
      attachments: [IOSNotificationAttachment(largeIconPath)]);
  var platformChannelSpecifics = NotificationDetails(
      androidPlatformChannelSpecifics, iOSPlatformChannelSpecifics);
  await flutterLocalNotificationsPlugin.show(
      3, notificationTitle, notificationBody, platformChannelSpecifics);
}

Thank you in advance for your answer.

**Comment by MaikuB** [comment]
Please read the Android documentation about how badges work https://developer.android.com/training/notify-user/badges
