### ISSUE TITLE
Doest not work background

### ISSUE THREAD

**Issue by volcano2906** [MaikuB/flutter_local_notifications#588]
Hi, 
My problem here is that when i call showNotification function when app is closed, no alarm appear but while on app, alarm comes right time. i do not use schuled alarm, i simply try to match time on my list and time on device, if they match, there will be alarm. like 16:00 if in my list 16 && 00 then alarm.

showNotification() async {
    int minutesIncrement = 1;
    debugPrint(widget.saatler.length.toString());
    var now = new DateTime.now();
    var suansaat = DateFormat("H").format(now);
    var suuadk = DateFormat("mm").format(now);
    for(int i=0;i < 100; i++ )  {
      var now = new DateTime.now();
      var suansaat = DateFormat("HH").format(now);
      var suuadk = DateFormat("mm").format(now);
      await new Future.delayed(const Duration(seconds : 30));
    if (widget.saatler.contains('$suansaat') && widget.dakikalar.contains('$suuadk')) {
      debugPrint("alarm zamanı");
      var android = new AndroidNotificationDetails(
          'channel id', 'channel NAME', 'CHANNEL DESCRIPTION',
          priority: Priority.High, importance: Importance.Max
      );
      var iOS = new IOSNotificationDetails();
      var platform = new NotificationDetails(android, iOS);
      await flutterLocalNotificationsPlugin.show(
          0, 'New Video is out', 'Flutter Local Notification', platform,
          payload: 'volkan is part time Youtuber');
      await new Future.delayed(const Duration(seconds : 31));
    } else {

    }

    }

**Comment by MaikuB** [comment]
There is no bug here because no code actually can get executed using a `Future` like you have done when the app is killed.
