### ISSUE TITLE
Got Default Sound On Background.

### ISSUE THREAD

**Issue by huonsokly** [MaikuB/flutter_local_notifications#591]
Hello, I have configure notification using custom sound. During my app running the custom sound work fine but on background it has notification with default sound.

**Below is my configure notification from api:** 

$notificationBuilder = new PayloadNotificationBuilder($title);
        $notificationBuilder->setBody($body)
            ->setIcon('app_icon')
            ->setSound('slow_spring_board.mp3')
            ->build();

How can make to the same custom sound? 
**Thank in Advance!**

**Comment by MaikuB** [comment]
That does not look like Dart code let alone code that uses this plugin. Please make sure you're on the right repository

**Comment by huonsokly** [comment]
Future _showNotification(notification) async {
    setState(() {
      countNotification += 1;
    });
    var androidPlatformChannelSpecifics = new AndroidNotificationDetails(
        'realtime-76906', 'realtime', 'your channel description',
        sound: 'slow_spring_board',
        importance: Importance.Max,
        priority: Priority.High);
    var iOSPlatformChannelSpecifics =
    new IOSNotificationDetails(sound: "slow_spring_board.aiff");
    var platformChannelSpecifics = new NotificationDetails(
        androidPlatformChannelSpecifics, iOSPlatformChannelSpecifics);
    await flutterLocalNotificationsPlugin.show(
      0,
      notification['title'],
      notification['body'],
      platformChannelSpecifics,
    );
  }
