### ISSUE TITLE
_showDailyAtTime Does not work 

### ISSUE THREAD

**Issue by volcano2906** [MaikuB/flutter_local_notifications#592]
Hi,

Firstly thanks for great plugin. 

I try to make multiple alarms daily, but it does not seem to work properly. flutterLocalNotificationsPlugin.show () work fine but not showDailyAtTime  

My android manifest doc here, i implement

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.flutterapp">
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <uses-permission android:name="android.permission.WAKE_LOCK"/>
    
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="flutterapp"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
        <service
            android:name="io.flutter.plugins.androidalarmmanager.AlarmService"
            android:permission="android.permission.BIND_JOB_SERVICE"
            android:exported="false"/>
        <receiver
            android:name="io.flutter.plugins.androidalarmmanager.AlarmBroadcastReceiver"
            android:exported="false"/>
        <receiver
            android:name="io.flutter.plugins.androidalarmmanager.RebootBroadcastReceiver"
            android:enabled="false">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"></action>
            </intent-filter>
        </receiver>

    </application>
</manifest>

Here is my intiated code here; 

 @override
  void initState() {
    super.initState();
    flutterLocalNotificationsPlugin = new FlutterLocalNotificationsPlugin();
    var android = new AndroidInitializationSettings('@mipmap/ic_launcher');
    var iOS = new IOSInitializationSettings();
    var initSetttings = new InitializationSettings(android, iOS);
    flutterLocalNotificationsPlugin.initialize(initSetttings,
        onSelectNotification: onSelectNotification);
    _showDailyAtTime();

  }

Here is how i call the function. 

RaisedButton(
                          onPressed: () async {await _showDailyAtTime();} ,
                          child: new Text(
                            'Demo',
                            style: Theme.of(context).textTheme.headline,
                          ),
                        ),

here is alarm funtion

 Future<void> _showDailyAtTime() async {
    var time = Time(16,0);

    var androidPlatformChannelSpecifics = AndroidNotificationDetails(
        'repeatDailyAtTime channel id',
        'repeatDailyAtTime channel name',
        'repeatDailyAtTime description');
    var iOSPlatformChannelSpecifics = IOSNotificationDetails();
    var platformChannelSpecifics = NotificationDetails(
        androidPlatformChannelSpecifics, iOSPlatformChannelSpecifics);
    await flutterLocalNotificationsPlugin.showDailyAtTime(
        0,
        'show daily title',
        'Daily notification shown at approximately ${_toTwoDigitString(time.hour)}:${_toTwoDigitString(time.minute)}:${_toTwoDigitString(time.second)}',
        time,
        platformChannelSpecifics);
    debugPrint("did vait await fun");
  }

For problem i have , 
1- When i set cuurent time (like 18:20), then press raised button, does not appear any alarm,
2-When check future alarm such as i want to make alarm 18:30, but now 18:20 , await flutterLocalNotificationsPlugin.showDailyAtTime funtion does not wait until finish alarm process, this code is just passed.
3-İ want to use pendingNotificationRequests(), i can not find how can i add my alarm list and where?
4-How can i call back these alarm in pendingNotificationRequests()

Thanks

How can make this code work ? thank in advance

**Comment by MaikuB** [comment]
1. You've only pasted a single line from the AndroidManifest file. There's an example app in this repository for you to refer to. If you're not seeing scheduled notifications then you've most likely haven't done your configuration properly. This isn't probably why you don't see anything
2. The await is not to wait for the notification to be appear but to wait for it be finished scheduling. If it is to wait for notifications then could mean the app never resumes after the await as the notification is shown every day. However, I do see how the naming may add some confusion and looking at deprecating some methods as part of tackling issues with timezones
3. I'm not sure what you mean by alarm list. This method is suppose to return notifications that have been scheduled
4. I don't understand your question

**Comment by MaikuB** [comment]
Closing this as there's a lack of information and the questions aren't clear. If you believe there's a bug, feel free to reopen if you're also able to link to a repository that has an app that can reproduce the problem
