### ISSUE TITLE
example app crashes after installing - android

### ISSUE THREAD

**Issue by MojtabaTavakkoli** [MaikuB/flutter_local_notifications#595]
Hello and thanks for your great job here.

I tried to download and run the project (https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications/example) on android device but after a successful compile and installation the app stops working. There's not much info that I can share with you, just after the app launch I get the error app stopped.

**Comment by MaikuB** [comment]
1. How did you download it?
2. How did you try to install the app?
3. What is the output of running `flutter doctor -v`

Note that this the first time I've heard of anyone with this issue so possibly something wrong with your environment that needs to be resolved

**Comment by heri1876** [comment]
I have the same problem, I fix it by creating a new project and copying all the code to the new project.

**Comment by MojtabaTavakkoli** [comment]
> 
> 
> I have the same problem, I fix it by creating a new project and copying all the code to the new project.

Can you please provide a summary of what you did for setting up the new project? Android manifest and IOS runner.

**Comment by MojtabaTavakkoli** [comment]
> 
> 
>     1. How did you download it?
> 
>     2. How did you try to install the app?
> 
>     3. What is the output of running `flutter doctor -v`
> 
> 
> Note that this the first time I've heard of anyone with this issue so possibly something wrong with your environment that needs to be resolved

1.  I simply download and opened the project in Android Studio. (Not clone)

2. As opened project in Android studio, tried to Run the app on real device.

3. flutter doctor:
```
D:\FlutterSDK\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18363.778], locale en-US)
    • Flutter version 1.12.13+hotfix.9 at D:\FlutterSDK\flutter
    • Framework revision f139b11009 (3 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\mojta\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: D:\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[√] Android Studio (version 3.6)
    • Android Studio at D:\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
Process finished with exit code 0


```

**Comment by heri1876** [comment]
> > I have the same problem, I fix it by creating a new project and copying all the code to the new project.
> 
> Didn't work for me...
> 
> Can you please provide a summary of what you did for setting up the new project? Android manifest and IOS runner etc.

I set up Android manifest, pubspec.yaml, images on drawable and all items on raw folder in res folder.

**Comment by MojtabaTavakkoli** [comment]
> 
> 
> > > I have the same problem, I fix it by creating a new project and copying all the code to the new project.
> > 
> > 
> > Didn't work for me...
> > Can you please provide a summary of what you did for setting up the new project? Android manifest and IOS runner etc.
> 
> I set up Android manifest, pubspec.yaml, images on drawable and all items on raw folder in res folder.

Yea I did the same. Stops working again.

**Comment by MaikuB** [comment]
The output of your `flutter doctor -v` would seem to indicate there's a problem that may be related. I've heard of issues when using Android Studio 3.6 with Flutter as well that there's a note about it in the installation guide at https://flutter.dev/docs/get-started/install/windows#install-android-studio

**Comment by MojtabaTavakkoli** [comment]
Yea you're right. The problem was causing of sdk version. there is an issue here (https://github.com/flutter/flutter/issues/51712) for it. Sorry that i didn't search well before opening the issue. 

Thanks for your time. Keep on the good work <3
