### ISSUE TITLE
Android: support `setWhen`

### ISSUE THREAD

**Issue by nioncode** [MaikuB/flutter_local_notifications#596]
It would be great if the plugin would support the [setWhen](https://developer.android.com/reference/androidx/core/app/NotificationCompat.Builder?hl=en#setWhen(long)) method for the notification to set a custom timestamp for the notification.

This is especially important if you have multiple notifications displayed at the same time (e.g. one per download) and update them independently. Then, whichever notification gets updated last will be moved to the left-most side in the status bar. When the other notification updates, this one will be moved to the left and the notifications will swap places all the time, which looks quite weird.

To fix this, it should be possible to set a fixed timestamp for each of the notifications (e.g. the time of the first creation of the notification) in order to keep the notifications in the initial order (see https://stackoverflow.com/questions/31574474/stop-sorting-android-notifications).

**Comment by MaikuB** [comment]
If there's a feature you need, it'd be great if you submit a PR for it :)
