### ISSUE TITLE
Title doesn't display with MediaStyleInformation

### ISSUE THREAD

**Issue by nomadcore** [MaikuB/flutter_local_notifications#599]
I tried this sample from examples

Future<void> _showNotificationMediaStyle() async {

	var largeIconPath = await _downloadAndSaveFile(
	    'http://via.placeholder.com/128x128/00FF00/000000', 'largeIcon');
	var androidPlatformChannelSpecifics = AndroidNotificationDetails(
	  'media channel id',
	  'media channel name',
	  'media channel description',
	  largeIcon: FilePathAndroidBitmap(largeIconPath),
	  styleInformation: MediaStyleInformation(),
	);
	var platformChannelSpecifics =
	    NotificationDetails(androidPlatformChannelSpecifics, null);
	await flutterLocalNotificationsPlugin.show(
    0, 'notification title', 'notification body', platformChannelSpecifics);
}

resulted notification has no title, just only body text

**Comment by MaikuB** [comment]
This is from an Android emulator with Android 10 and the title is visible

![image](https://user-images.githubusercontent.com/25263378/80266576-d8b83000-86df-11ea-895f-7633d3392b80.png)

Not sure what device and which version of Android you have it and but the appearance may differ, which is to do with the Android OS not the plugin

**Comment by nomadcore** [comment]
Hmm, that's true. In emulator title displays correctly. Probably it's "feature" of my real phone. Sorry for disturbing.
