### ISSUE TITLE
RepeatInterval.EveryMinute actually notifies every 5 minutes on actual Samsung S7 w/8.0

### ISSUE THREAD

**Issue by Simpler1** [MaikuB/flutter_local_notifications#60]
I built the example code with no changes (flutter build apk).  When I run it on my actual device (Samsung S7 Edge with Android 8.0) and click "Repeat notification every minute", I actually get a notification every 5 minutes (not every minute).

I tried the same apk on an an emulator (Pixel 2 XL API 24) and it notified every minute as expected.

Very odd.

**Comment by MaikuB** [comment]
I think you're running into behaviour described here where the OS may shift the alarms https://developer.android.com/reference/android/app/AlarmManager.html#setRepeating(int,%20long,%20long,%20android.app.PendingIntent)

**Comment by Simpler1** [comment]
I can see that it may shift the first notification, but subsequent notifications should be spaced one minute apart.  Correct?  This shouldn't affect my use of the tool, but I thought you would want to know.  Feel free to close this out if you can't address it.

By the way, nice tool.  Thanks.

**Comment by MaikuB** [comment]
Yeah there's not much I can do and sorry I sent the wrong link earlier. This is the correct one

https://developer.android.com/reference/android/app/AlarmManager#setInexactRepeating(int,%20long,%20long,%20android.app.PendingIntent)

Though if you looked at the notes for `setRepeating`,  Android has made changes that it's inexact now as well so I believe they'll just behave the same. You'll find there there's guidance too on if you want precise delivery times. That could probably be achieve using [this plugin](https://github.com/flutter/plugins/tree/master/packages/android_alarm_manager) to fire of the one-shot exact alarm. I believe that notification libraries for other frameworks like React Native use the same `setInexactRepeating` method too as the Android guidance is to use that method as per this [link](https://developer.android.com/training/scheduling/alarms)
