### ISSUE TITLE
How to schedule a daily notification starts from tomorrow

### ISSUE THREAD

**Issue by Goxiaoy** [MaikuB/flutter_local_notifications#601]
Thanks for this wonderful package!
But I have come an issue recently. I have set an daily notification to notify user to do something, but once use already do this stuff, I want to delay this notification to tomorrow. 
For now ,it seems impossible for `showDailyAtTime`  api, but it seems that the native android and ios can do that. I am not familiar with android and ios development , but it seems some of the following codes can be changed to meet my requirement. Am I right?

https://github.com/MaikuB/flutter_local_notifications/blob/66bf8be9f2b5133e3ab54be4ff443e07fc021924/flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java#L300-L311

https://github.com/MaikuB/flutter_local_notifications/blob/f46755e7b6a41ddcebf5f1afd312ee95589ea972/flutter_local_notifications/ios/Classes/FlutterLocalNotificationsPlugin.m#L289-L299

**Comment by MaikuB** [comment]
Changing the above code is unlikely to help you achieve what you need and the functionality you're after isn't supported by the plugin. To meet your requirements, at this stage you're going to need to learn the native APIs and come up with your own solution. You might also want to see if using https://pub.dev/packages/device_calendar meets your requirements

**Comment by erolasan** [comment]
I know this is closed a long time ago, but is this something that the plugin currently supports or it's still not possible?

**Comment by vishnuagbly** [comment]
I have the same question, if this is currently supported?

**Comment by Levi-Lesches** [comment]
Reading the docs for `zonedSchedule`:

> If a value for matchDateTimeComponents parameter is given, this tells the plugin to schedule a recurring notification that matches the specified date and time components. Specifying DateTimeComponents.time would result in a daily notification at the same time whilst DateTimeComponents.dayOfWeekAndTime would result in a weekly notification that occurs on the same day of the week and time. This is similar to how recurring notifications on iOS/macOS work using a calendar trigger. 

But specifically this part:

> Note that when a value is given, the scheduledDate may not represent the first time the notification will be shown. An example would be if the date and time is currently 2020-10-19 11:00 (i.e. 19th October 2020 11:00AM) and scheduledDate is 2020-10-21 10:00 and the value of the matchDateTimeComponents is DateTimeComponents.time, then the next time a notification will appear is 2020-10-20 10:00.

In this example, you schedule a daily notification to start on the 21st but it actually starts on the 20th, because that's the next time it's 10:00. 

So it seems you CAN start tomorrow, but you can't "skip" a notification, so you'll need to use a time that already passed today such that the next available time is tomorrow.
