### ISSUE TITLE
Notifications never appear when app is terminated.

### ISSUE THREAD

**Issue by ManasviPatidar** [MaikuB/flutter_local_notifications#604]
**Describe the bug**
The plugin doesn't work when the app is completely terminated.

**To Reproduce**
1. Run the example app.
2. Click on the "schedule notification to appear in 5 seconds ........"
3. Close the app immediately, also remove it from the multitasking tab. (i.e. completely terminate it) 
4. The notification never appears.

I have also tried it by increasing the time to 1min. I tried it on android.

Is it necessary for the app to be present in the memory for notifications to appear? By reading the README I was under the impression that this was supposed to be handled by a background process and not depend on the state of the app.

**Comment by MaikuB** [comment]
Similar issues have been raised before e.g. https://github.com/MaikuB/flutter_local_notifications/issues/213. Check to see what device you're using as there may be restrictions in place that by the operating system of your device

**Comment by ManasviPatidar** [comment]
Yes, that seems to be the problem in my case too. I suggest adding this warning somewhere in the README along with the list of devices. I got this issue on an OnePlus6.

**Comment by mcradha** [comment]
I am still getting this issue on OnePlus7. Is there any workaround for it?
