### ISSUE TITLE
Run code on notification shown

### ISSUE THREAD

**Issue by Greatcallie** [MaikuB/flutter_local_notifications#606]
I will like to be able to run code with showing the notification. Could that be possible? Thanks.

**Comment by MaikuB** [comment]
No it isn't

**Comment by Greatcallie** [comment]
Please i would like to know why it isn't possible. Is it an iOS limitation or not intended for by this plugin?

**Comment by MaikuB** [comment]
Due to limitations. A similar issue was open a long time ago on this that you can read through for more info https://github.com/MaikuB/flutter_local_notifications/issues/21. If the limitations don't affect you then you can implement it on your fork
