### ISSUE TITLE
Customize sound with long duration

### ISSUE THREAD

**Issue by cahyofendhi** [MaikuB/flutter_local_notifications#611]
i want to create alarm notification, and using own sound, but not working when sound duration more than 30 seconds, how to solve this issue

**Comment by MaikuB** [comment]
Nothing you can do besides picking a sound that shorter than 30 seconds. iOS has limits (see https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/SupportingNotificationsinYourApp.html) so you need to make sure you work with the limits
