### ISSUE TITLE
 I just want a feature in action button  i want a parameter in NotificationAction onClick app launch or not 

### ISSUE THREAD

**Issue by younasud** [MaikuB/flutter_local_notifications#614]
**IMPORTANT**
If you are getting a build error on Android that mentions AndroidX incompatibilities, before reporting an issue, please make sure look at the error information carefully as there should be a URL that provides information on migrating your application to AndroidX.

Also note that the plugin has an example application that should cover all of the available functionality. Please check the example application and see if the functionality works before logging an issue. You'll need to clone the repository to run it

**Describe the bug**

**To Reproduce**
If applicable, steps to reproduce the behavior:

**Expected behavior**
If applicable, clear and concise description of what you expected to happen.

**Sample code to reproduce the problem**
Ideally, include a link to a repository that contains code that can reproduce the problem. Suggestion is to fork this repository to modify the example app. Note that without a sample, it'll be may be more difficult to reproduce the problem and/or investigate further

**Comment by MaikuB** [comment]
There is already an issue open about custom notification actions https://github.com/MaikuB/flutter_local_notifications/issues/17 that is marked as blocked. So I'm closing this as a duplicate. You can always implement what you need for your scenarios on your own.

As a sidenote, I'd kindly ask that you look more closely at issues you open as you used a bug report template to ask for feature and didn't delete the templated message
