### ISSUE TITLE
Notification Sound not plays in Android 9

### ISSUE THREAD

**Issue by taciomedeiros** [MaikuB/flutter_local_notifications#619]
**Describe the bug**
The same sound plays in notifications in device emulators as (Nexus One, Nexus 4 API 22), but can't play on Nexus 5X API 28. I think that the problem could be associated with the use of Android 9 platform!

**Expected behavior**
The sound should be played.

**Sample code to reproduce the problem**
I use the example code in the repository and it didn't played to.

**Comment by MaikuB** [comment]
Can you clarify which button you tapped on in the example app so I know which sound you are referring to (e.g. the custom sound or default notification sound)? I've used this on an Android 9 phone before with no issues. Just ran this on a Pixel 2 XL API 28 emulator and both the default sound and custom sound play fine. No one else has reported this before too, so perhaps you have an issue with your emulator that needs looking into

**Comment by MaikuB** [comment]
Another thing I should point out is sound settings are tied to notification channels. If you had fiddled around with making the channel to not play sounds and then reverted the change, then you need to uninstall the app as the original setting would remain.

**Comment by MaikuB** [comment]
Closing due to lack of further response. Feel free to reopen if you have more info

**Comment by PO15ON** [comment]
I'm deleting the notification channel before updating the "playSound" parameter, it still doesn't work..
Is there anything I should do?
