### ISSUE TITLE
Hello, my test popup failed on Android 10

### ISSUE THREAD

**Issue by 309791679** [MaikuB/flutter_local_notifications#620]
Hello, my test popup failed on Android 10

Low version can be used

**Comment by MaikuB** [comment]
Sorry but you're not providing enough information here to look into this further and I don't understand what you mean by "Low version can be used". No one else has reported an issue with notifications appearing on Android 10 and i have an Android 10 device as well. I suspect you have an issue in your own app that you'll need to investigate further.

There's an example app in this repo that is used to demonstrate the functionality of the app for reference in case you weren't aware of that. This could also be used to report suspected bugs

**Comment by MaikuB** [comment]
Closing due to lack of further response. Feel free to reopen if you have more info
