### ISSUE TITLE
How to stop the notification from popping onto the screen? lowering the "importance" of the notification is also not preventing the notification from interrupting 

### ISSUE THREAD

**Issue by PiyushPrakhar** [MaikuB/flutter_local_notifications#626]
Is there any way to just put the notification in the notification bar without interrupting the user by a notification pop-up on the screen?

**Comment by MaikuB** [comment]
Only on Android. Please read the official documentation to understand how notifications work on Android https://developer.android.com/guide/topics/ui/notifiers/notifications#importance. Note that importance is tied the notification channel as per the API docs. Once specified, the setting will remain even if try to change the value unless you delete and recreate the channel, or uninstall and reinstall the app

**Comment by PiyushPrakhar** [comment]
Thanks, the importance is changing on re-installing the app.
