### ISSUE TITLE
pendingNotificationRequests does not deliver DateTime of the notifications notifications pending to be delivered/shown.

### ISSUE THREAD

**Issue by nickpnmrv** [MaikuB/flutter_local_notifications#629]
**Description**
There is no way to get the date time object of the notifications already scheduled

**Expected behavior**
PendingNotificationRequest has an additional member to show date and time of the notification scheduled

**Sample code to reproduce the problem**
```
List<PendingNotificationRequest> requests =
        await flutterLocalNotificationsPlugin.pendingNotificationRequests();

class PendingNotificationRequest {
  final int id;
  final String title;
  final String body;
  final String payload;

  const PendingNotificationRequest(
      this.id, this.title, this.body, this.payload);
}
```

**Comment by MaikuB** [comment]
This isn't a bug and by design. See #245 for a previous discussion on this
