### ISSUE TITLE
notification not working.. no error message

### ISSUE THREAD

**Issue by aldwnesx** [MaikuB/flutter_local_notifications#630]
wrong file name typo

**Comment by MaikuB** [comment]
Please make sure you followed all the steps in the readme. Your code snippets aren't sufficient to help provide more info on what's missing. I can only guess you that you didn't follow all the steps

**Comment by aldwnesx** [comment]
> Please make sure you followed all the steps in the readme. Your code snippets aren't sufficient to help provide more info on what's missing. I can only guess you that you didn't follow all the steps

I added permissions to manifestm, but now it keeps crashing

E/AndroidRuntime(19946): java.lang.RuntimeException: Unable to start receiver com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
E/AndroidRuntime(19946): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3454)
E/AndroidRuntime(19946): 	at android.app.ActivityThread.access$1400(ActivityThread.java:206)
E/AndroidRuntime(19946): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1711)
E/AndroidRuntime(19946): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(19946): 	at android.os.Looper.loop(Looper.java:201)
E/AndroidRuntime(19946): 	at android.app.ActivityThread.main(ActivityThread.java:6820)

**Comment by MaikuB** [comment]
You need to make sure you provide the correct information such as the correct name of the icon to use. This is something you need to check on your end

**Comment by aldwnesx** [comment]
you are right.. i had a typo..thanks so much

**Comment by MaikuB** [comment]
No worries. Closing this as looks like you've been able to resolve the issue
