### ISSUE TITLE
Person's icon is rotated

### ISSUE THREAD

**Issue by kirhammer** [MaikuB/flutter_local_notifications#634]
When applying MessagingStyleInformation, if the downloaded image used as a Person's icon is a portrait (height grater than width), the notification displays the image rotated 90 degrees. 

![Test](https://user-images.githubusercontent.com/43619730/82508236-0bc8c600-9aca-11ea-8a7a-bfb65257c85e.png)

**Comment by MaikuB** [comment]
If that's the behaviour then you'll need to look at making changes at your end as what you're seeing is being done by the Android APIs and isn't due to an issue with the plugin

**Comment by MaikuB** [comment]
Closing as this isn't due to an issue with the plugin
