### ISSUE TITLE
Show notification without popup

### ISSUE THREAD

**Issue by goranristic123** [MaikuB/flutter_local_notifications#635]
Hi,

This is not a bug report, I'm just curious if this is possible. I read the documentation but can't find anything related to this.

Is it possible to push the notification to the notification center without displaying the popup?

![99436720_1145449909170293_3547510594129100800_n](https://user-images.githubusercontent.com/8156001/82608050-3d20bf00-9bba-11ea-8b31-9075fc0b7b38.jpg)

**Comment by MaikuB** [comment]
Only on Android. You'll need to read the official docs that talk about the various importance levels
