### ISSUE TITLE
Does it work when app is terminated ?

### ISSUE THREAD

**Issue by II11II** [MaikuB/flutter_local_notifications#637]
I tried your example app 
It works perfectly when app is launched 
But if it is terminated The notifications cannot be shown 
After launching app it is showing  the notification  which should be shown f.e 5 minutes ago (5 minutes ago app was termianted)

**Comment by II11II** [comment]
Phone Samsung s9 android 10 
The saving battery mode is turned off

**Comment by II11II** [comment]
It would be great to take the video w how the notification works when app is terminated

**Comment by II11II** [comment]
F.e instagram works if the saving mode is turned on

**Comment by II11II** [comment]
if saving mode is off it works but 100% correctly first 3 minutes each minutes sends notifications  ,then during 5 minutes it did not send any , then it sent

**Comment by MaikuB** [comment]
You cannot compare this with Instagram as they're using push notifications.

Is your scenario on recurring notifications? If so, please read the notes in the readme about recurring notifications as it is documented as expected behaviour
