### ISSUE TITLE
No pop-up notification on lock screen

### ISSUE THREAD

**Issue by jafitz26** [MaikuB/flutter_local_notifications#638]
I'm working with the example code, with just some modifications to the _showNotification widget so that it is scheduled and the visibility is set to public:

 ` Future<void> _showNotification() async {
    var scheduledNotificationDateTime =
    DateTime.now().add(Duration(seconds: 5));
    var androidPlatformChannelSpecifics = AndroidNotificationDetails(
        'your channel id', 'your channel name', 'your channel description',
        importance: Importance.Max, priority: Priority.High, ticker: 'ticker',
    visibility: NotificationVisibility.Public);
    var iOSPlatformChannelSpecifics = IOSNotificationDetails();
    var platformChannelSpecifics = NotificationDetails(
        androidPlatformChannelSpecifics, iOSPlatformChannelSpecifics);
    await flutterLocalNotificationsPlugin.schedule(
        0, 'plain title', 'plain body',
        scheduledNotificationDateTime,
        platformChannelSpecifics,
        payload: 'item x');
  }`

This results in a popup when the phone is active, but not on the lockscreen.

Here is what I did for set up, in case I'm missing something:

Copied the following into both Main>AndroidManifest and Debug>AndroidManifest:
 `<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>`

and within the Application tag on Main>AndroidManifest:
`<receiver android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"></action>
            </intent-filter>
        </receiver>
        <receiver android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver" />`

**Comment by edwin-alvarez** [comment]
![Simulator Screen Shot - iPhone Xʀ - 2020-05-23 at 11 51 06](https://user-images.githubusercontent.com/5774873/82738342-c4218480-9ceb-11ea-98dd-ae733dbb176d.png)

I see it working on the simulator with no issues.

what OS are yo using

**Comment by jafitz26** [comment]
I'm using Android 10. Everything works as expected on a simulator, and I discovered the issue on my physical device was with the way my lock screen is set up.

So the popup works fine now, but the sound on the physical device still isn't working, though there is sound on the simulator.
