### ISSUE TITLE
[feature] Get current permission status

### ISSUE THREAD

**Issue by otopba** [MaikuB/flutter_local_notifications#639]
Your plugin has the ability to request permissions, but there is no way to find out what permissions we currently have. Sometimes it is necessary to change the flow of an application. Please add this feature, that would be very helpful. 

Thank you

**Comment by MaikuB** [comment]
I don't have plans for doing this. The community has already provided packages for this so I don't see much reason to duplicate the work that would also reduce the value of their work

**Comment by otopba** [comment]
@MaikuB OK, got it. Thanks for the quick response

**Comment by ziggycrane** [comment]
The fact that the notification library has no way to detect notification status makes no sense to me.
