### ISSUE TITLE
alert once

### ISSUE THREAD

**Issue by mostafasolati** [MaikuB/flutter_local_notifications#642]
Hi
After discarding the progress notification It keeps popping up on the screen .Despite of setting onlyAlertOnce to true.
If I leave it be, it wont show up after a few seconds.

**Comment by MaikuB** [comment]
Please refer to the API docs for that property https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/AndroidNotificationDetails/onlyAlertOnce.html

The property isn't about preventing the notification from popping up again.

**Comment by mostafasolati** [comment]
So how can I handle this problem?

**Comment by MaikuB** [comment]
I'm assuming you're dismissing a progress notification for a download that hasn't finished so your app is triggering another notification? If so, this is something you have to come up with a solution on your own that may require writing your native Android code

**Comment by MaikuB** [comment]
Closing this since this has been clarified
