### ISSUE TITLE
Is it possible to add logic to a notification?

### ISSUE THREAD

**Issue by robwafle** [MaikuB/flutter_local_notifications#643]
The use case I have for this is that a user needs to be reminded daily to do something at 6pm, but they open the app and record that they did the action at 5:55pm.

Since I've scheduled a notification at 6pm every day, the notification will still trigger.   It would be really amazing if I could add logic to the notification that could run to see if the notification still needs to show on the user's screen.

I'd really like to avoid unneeded notifications.

**Comment by MaikuB** [comment]
No as what's you're describing is specific to your application so will need a customised solution specific to your app.

If you're dealing with reminders, you might need to consider if using https://pub.dev/packages/device_calendar is more appropriate as well in case you haven't come across it

**Comment by robwafle** [comment]
Hi MaikuB! Wow! Thanks for the quick response!  I have seen the other library and I believe that your library is more appropriate for my use case.  I can indeed schedule individual reminders and cancel those individual reminders as needed.

**Comment by MaikuB** [comment]
No worries :)

Yep that's likely the only solution you can do as the native APIs for scheduling recurring notifications don't support what you're after. If your solution will still use this plugin, note that it currently has issues with daylight savings. I'll be doing a beta release soon around this

**Comment by robwafle** [comment]
Thanks!  I looked into the native APIs after I got your response.  I noticed the daylight savings issue.  Everything is coming together very well.  Could not have done it without your library!
