### ISSUE TITLE
Does this plugin provide background service?

### ISSUE THREAD

**Issue by II11II** [MaikuB/flutter_local_notifications#647]
I am creating Alarm App in flutter using this plugin for **notification**. Im taking AlarmTime from sharedpreferences. 
Can this plugin change **Notify time** depending on data that taking from **SharedPreference**?
If yes How can i do it? 
P.s. it is taking almost a week to do it So i decided to ask here

**Comment by MaikuB** [comment]
A background service to do what?

**Comment by II11II** [comment]
background service to check is Datetime.now() equal to Datetime (which is in String,which will be converted to DateTime)   from shared preference, if yes send the datetime to the plugin to notifiy user if not dont notify user
It is kind of Alarm App like in android phones

**Comment by MaikuB** [comment]
No. That is application-specific logic and as such is to applications to implement

**Comment by II11II** [comment]
Do i need to include other plugin to do this ? 
Or i need to replace flutter_local_notifications with other plugin or write native code?

**Comment by MaikuB** [comment]
This is something you need to research and/or make use of other sites listed in https://flutter.dev/community
