### ISSUE TITLE
_showDailyAtTime() is not working on example app

### ISSUE THREAD

**Issue by imSaharukh** [MaikuB/flutter_local_notifications#655]
I just clone the example  app from github and _showDailyAtTime() is not working I just change the  Time(17, 15, 0); like this to test and its not working 

device K20Pro Android 10

**Comment by MaikuB** [comment]
I looked up the device and see it's by Xiaomi. They have restrictions that prevent things from running in the background. It's a limitation/issue with their devices

**Comment by imSaharukh** [comment]
i tested also with vivo 1801. and 
_showDailyAtTime()  the local device time  right?

**Comment by imSaharukh** [comment]
this issue is only for Xiaomi?

**Comment by MaikuB** [comment]
Yes it's local but I would suggest you run on an emulator first as other devices you have restrictions as well that you may not be aware of and may need to look up. There are no known issues on this API that prevent the method from completely working except for manufacturers that customise the Android OS itself and putting restrictions on there. Xiaomi is one, there may be others out there.

**Comment by imSaharukh** [comment]
Thanks, brother I appreciate your work

**Comment by imSaharukh** [comment]
I would be great if you make a list of this kind of devices like xiaomi

**Comment by MaikuB** [comment]
I don't have these devices to be about to come to with a list myself and there are many companies out there that I don't even know about. Can add a general note to the readme though
