### ISSUE TITLE
problem notification data back when in background

### ISSUE THREAD

**Issue by bardoun7894** [MaikuB/flutter_local_notifications#659]
hello my friend i have a problem  in Notification where the app is killed i can get the data back ,
(the notification is popup but no data,if i clicked in notification  is push me to homepage ), 
but if the app is not killed and go to background  if i press notification is good and can acces the page with data that i want  
sorry for my english .

**Comment by MaikuB** [comment]
This means you have an issue where you have structured your code to handle the notification launching the app properly. There's documentation on this in the readme and there's an example app [here](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications/example) (please downloading the complete repo so it works properly) that demonstrates how this can be done. Please refer to those and adjust your app accordingly. If you need more detailed help, please use on the sites listed at https://flutter.dev/community
