### ISSUE TITLE
Play Default Incoming Call Sound

### ISSUE THREAD

**Issue by gfiury** [MaikuB/flutter_local_notifications#662]
Hello guys,

I could not find a way to do it so I believe it is a feature or enhancement. I'm trying to create an Android (it would be great also for iOS) notification for incoming calls.

Checking the class flutter_local_notifications/lib/src/platform_specifics/android/notification_details.dart for the Android specification, I managed to add the FLAG_INSISTENT from here [Android FLAGS](https://developer.android.com/reference/android/app/Notification#FLAG_INSISTENT).

So the notification does not stop until the user checks the phone, like any other phone call, but the notification sound is the default sound of the notifications :/.

Checking the specification there is an AndroidNotificationSound property, but you need to assign a sound to this right? 
Does the plugin have a way to play the default sound of the call and not the default of the notification?

Regards,
William

**Comment by MaikuB** [comment]
In the example app is a code snippet for passing a sound based on an Android URI. This requires you to write native code to find out what the URI is for the default call sound

**Comment by gfiury** [comment]
@MaikuB thanks, I will do that
