### ISSUE TITLE
App crash after click notification( When app is background)

### ISSUE THREAD

**Issue by kalismeras61** [MaikuB/flutter_local_notifications#666]
**IMPORTANT**
If you are getting a build error on Android that mentions AndroidX incompatibilities, before reporting an issue, please make sure look at the error information carefully as there should be a URL that provides information on migrating your application to AndroidX.

Also note that the plugin has an example application that should cover all of the available functionality. Please check the example application and see if the functionality works before logging an issue. You'll need to clone the repository to run it

**Describe the bug**
When app is background and get the firebase data notification and click the notification and then app crashed

[        ] E/AndroidRuntime( 5196): java.lang.IllegalArgumentException: Parameter specified as non-null is null: method p.t.c.h.b, parameter o
[        ] E/AndroidRuntime( 5196):     at j.h.a.c.a(Unknown Source:2)
[        ] E/AndroidRuntime( 5196):     at j.h.a.a.b(:353)
[        ] E/AndroidRuntime( 5196):     at j.h.a.a.a(:321)
[        ] E/AndroidRuntime( 5196):     at io.flutter.embedding.engine.c$c.a(:715)
[        ] E/AndroidRuntime( 5196):     at io.flutter.embedding.engine.c.a(:391)
[        ] E/AndroidRuntime( 5196):     at io.flutter.embedding.android.e.a(:571)
[        ] E/AndroidRuntime( 5196):     at io.flutter.embedding.android.d.onNewIntent(:589)
[        ] E/AndroidRuntime( 5196):     at android.app.Activity.performNewIntent(Activity.java:7471)
[        ] E/AndroidRuntime( 5196):     at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1387)
[        ] E/AndroidRuntime( 5196):     at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1399)
[        ] E/AndroidRuntime( 5196):     at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:3685)
[        ] E/AndroidRuntime( 5196):     at android.app.ActivityThread.performNewIntents(ActivityThread.java:3701)
[   +5 ms] E/AndroidRuntime( 5196):     at android.app.ActivityThread.handleNewIntent(ActivityThread.java:3718)
[        ] E/AndroidRuntime( 5196):     at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:49)
[        ] E/AndroidRuntime( 5196):     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
[        ] E/AndroidRuntime( 5196):     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
[        ] E/AndroidRuntime( 5196):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
[        ] E/AndroidRuntime( 5196):     at android.os.Handler.dispatchMessage(Handler.java:112)
[        ] E/AndroidRuntime( 5196):     at android.os.Looper.loop(Looper.java:216)
[        ] E/AndroidRuntime( 5196):     at android.app.ActivityThread.main(ActivityThread.java:7625)
[   +1 ms] E/AndroidRuntime( 5196):     at java.lang.reflect.Method.invoke(Native Method)
[        ] E/AndroidRuntime( 5196):     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
[        ] E/AndroidRuntime( 5196):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
[  +29 ms] E/        ( 5196): [ZeroHung]zrhung_get_config: Get config failed for wp[0x0008]
[  +48 ms] W/CrashlyticsCore( 5196): Cannot send reports. Settings are unavailable.
[ +206 ms] I/Process ( 5196): Sending signal. PID: 5196 SIG: 9
[ +144 ms] Service protocol connection closed.
[        ] Lost connection to device.

**Comment by MaikuB** [comment]
> When app is background and get the firebase data notification and click the notification and then app crashed

Report the issue on GitHub repository for `firebase_messaging`. Not sure why you've filed an issue here

**Comment by kalismeras61** [comment]
> > When app is background and get the firebase data notification and click the notification and then app crashed
> 
> Report the issue on GitHub repository for `firebase_messaging`. Not sure why you've filed an issue here

Because i am using your library or background data messages. When i receive data onBackgroundMessageHandler i just convert the local notification.

**Comment by MaikuB** [comment]
1. Have you tried removing the code that cake this plugin to confirm the issue is with this plugin? Your stack trace doesn't mention anything about this plugin
2. What does the notification JSON itself look like
3. Got a link to a repo hosting a minimal example app that can reproduce this?
