### ISSUE TITLE
Notification sound not working on release built

### ISSUE THREAD

**Issue by bingcheng45** [MaikuB/flutter_local_notifications#668]
On debug mode, the Scheduled notifications work as expected and with sound.
However, when I build the apk for release, the notification still works and is shown but no sound is heard. This occurs in my app, I have already included the stuff required for proguard-rules.pro

Does anyone face this issue for release build? 
1. `flutter clean`
2. `flutter build apk`
3. `flutter install`

And why does the sound works for debug mode and not release mode?

I have tried replicating what you have in _scheduleNotification() on my project, noting the proguard, keep.xml, checking the androidmanifest.xml.
couldn't find what is causing the difference in release build to not play custom sound while debug works fine.

I have tried building your app and run in release mode and there is sound, what else did you do beside the documentation?

my project link is here : [https://github.com/bingcheng45/PomodoRemastered/blob/master/lib/home.dart](url)
I have accelerated the notifications to display after 10s when you tap

**Comment by MaikuB** [comment]
> I have tried replicating what you have in _scheduleNotification() on my project, noting the proguard, keep.xml, checking the androidmanifest.xml

But there's no keep.xml file https://github.com/bingcheng45/PomodoRemastered/tree/master/android/app/src/main/res/values

**Comment by bingcheng45** [comment]
> > I have tried replicating what you have in _scheduleNotification() on my project, noting the proguard, keep.xml, checking the androidmanifest.xml
> 
> There's no keep.xml file in your project https://github.com/bingcheng45/PomodoRemastered/tree/master/android/app/src/main/res/values

My bad, I forgot to push my code. After checking my keep.xml file which is in my raw folder, I realized I forgot to change the filename to my audio file name. Really sorry about that.
Thanks for highlighting my mistake.
I have updated my GitHub already and it is working great.

Love your package btw, would be helpful to others if you have some documentation about the keep.xml file for audio as how I found out about it was by digging through your folders and comparing with mine.

**Comment by MaikuB** [comment]
There is a release build configuration section that mentions this and links to official Android documentation https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/README.md#release-build-configuration

**Comment by bingcheng45** [comment]
> There is a release build configuration section that mentions this and links to official Android documentation https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/README.md#release-build-configuration

oh my bad again, i only saw where the sound file should be kept and missed out about the keep.xml link. Thanks for the fast response! :)
