### ISSUE TITLE
Support For Notifications With Custom Views : A Player App Use Case

### ISSUE THREAD

**Issue by eddywm** [MaikuB/flutter_local_notifications#67]
I have been trying to wrap my mind about implementing a player app control widget  in a Flutter app that appears as a notification and on locked screen, it is shows basic player controls.
I was about to start thinking about implementing them myself and then I came across this plugin, please a sample code showing how to achieve might really helpful for me.

**Comment by MaikuB** [comment]
The widget you're building is not something that could just be displayed on a notification and lock screen. I would suggest you look at how an app like would normally be built natively in Android and iOS app to see what's involved. I assume that this app you're building will be playing audio media and if i'm not mistaken, iOS handles showing playback controls out of the box. On the Android side, this would be done via [media style notifications](https://developer.android.com/reference/androidx/media/app/NotificationCompat.MediaStyle). Support for this is something I could add but this would be blocked by #17 and requires you to pass it a media session token.

**Comment by eddywm** [comment]
I already have a an in app audio player.
By what you say iOS gives audio control widget out of the box? I have played it on iOS but it’s not giving those controls out of the box as you said.
Please more clarifications might be more helpful.

**Comment by MaikuB** [comment]
Soryr what I meant was there are other APIs on iOS for showing those controls that don't have anything to do with notifications and thus is something you should do research on e.g. https://developer.apple.com/documentation/avfoundation/media_assets_playback_and_editing/creating_a_basic_video_player_ios_and_tvos/controlling_background_audio

**Comment by MaikuB** [comment]
Also to elaborate on my original reply, I believe that you're essentially asking for sample code on something that is technically not possibly. Therefore, I'll be closing this issue but I will likely look into support for media style notifications on Android once the Flutter team has finished the necessary changes that would unblock #17
