### ISSUE TITLE
inconsistent/incorrect response to getNotificationAppLaunchDetails() on Android

### ISSUE THREAD

**Issue by carlleeswanson** [MaikuB/flutter_local_notifications#670]
On Android, if the call to getNotificationAppLaunchDetails() is placed after the call to initialize(), then the value returned for didNotificationLaunchApp is always false.

If this is expected behavior, then the documentation should be updated to indicate the requirement that it be called before initialize(). Although the example app is structured that way, it is counter-intuitive that other calls can be made before initialize().

On IOS, the correct value is returned both when getNotificationAppLaunchDetails() is called before initialize() and when it is called after initialize(). So I assume this is a bug in the Android implementation.

To reproduce in the example app:
- cut the call to getNotificationAppLaunchDetails() from lines 46-47.
- paste after the call to initialize() and before runApp().
- launch the app, and select "Schedule notification to appear in 5 seconds"
- close the app
- when the notification appears, click on it to re-launch the app.
On Android, the indicator "Did notification launch app?" (at the top of the page) will incorrectly indicate "false".

Tested on Android v10/API29 on a Pixel 2

**Comment by chriswiesner** [comment]
I think it also depends on how you close the app.
Afaik pressing the "home" button is not closing the app, just stopping it.
If you hit the back button, the application is usually closed.

**Comment by carlleeswanson** [comment]
@chriswiesner Yes, bringing an app from background to foreground is not the same as launching. If brought from background to foreground, getNotificationAppLaunchDetails().didNotificationLaunchApp correctly indicates "false". 
In both cases (launch and bringing from background to foreground), the onSelectNotification() callback will be executed. However, I believe that is unrelated to the value that should be returned from getNotificationAppLaunchDetails().

Are you saying that you see a different behavior than I do when you launch? (i.e. exactly what results do you get when you follow the steps above?)

**Comment by MaikuB** [comment]
@carlleeswanson Thanks for finding this. There is indeed an issue, as there's 1.5.0 beta release at the moment and the severity of this, I'm going to include the fix in 1.5.0-beta.3 that I'll push a release out for soon

**Comment by JHBitencourt** [comment]
+1 vote for this.
I am facing this same issue and came here to investigate better.

**Comment by MaikuB** [comment]
@JHBitencourt This issue has already been fixed in the beta release

**Comment by MaikuB** [comment]
Recently released 2.0 that includes this fix so closing this
