### ISSUE TITLE
Help with Scheduled Notifications 

### ISSUE THREAD

**Issue by Azazel17** [MaikuB/flutter_local_notifications#671]
When i turn off my phone all the scheduled notifications are lost, i have already implemented the following in the manifest: 

`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.notificacioneslocales">
    
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />

    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="notificacioneslocales"
        android:icon="@mipmap/ic_launcher">
        <service          android:name="com.example.notificacioneslocales.localnotifications.services.LocalNotificationsService"
            android:exported="false" />

        <activity
        android:name=".MainActivity"
        android:launchMode="singleTop"
        android:theme="@style/LaunchTheme"
        android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
        android:hardwareAccelerated="true"
        android:windowSoftInputMode="adjustResize">
        
        <meta-data
            android:name="io.flutter.embedding.android.NormalTheme"
            android:resource="@style/NormalTheme"
            />
        
        <meta-data
            android:name="io.flutter.embedding.android.SplashScreenDrawable"
            android:resource="@drawable/launch_background"
            />
        <intent-filter>
            <action android:name="android.intent.action.MAIN"/>
            <category android:name="android.intent.category.LAUNCHER"/>
        </intent-filter>
    </activity>

        <receiver android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver" />
        <receiver android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"></action>
            </intent-filter>
        </receiver>

        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>
`

And still not working, when i turn off my phone all the notifications disappear, by the way, this lines are in red 

`receiver android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver" />
        <receiver android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"></action>
            </intent-filter>
        </receiver>`

And they say: 

Class referenced in the manifest, com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver, was not found in the project or the libraries

**Comment by MaikuB** [comment]
> Class referenced in the manifest, com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver, was not found in the project or the libraries

That's likely your reason why. Haven't seen any other reports of this and the example app doesn't have this problem either. I suspect you possibly a corrupt installation or some other issue in your local environment that prevents the Android build process from being able to find that class. As such it's not something I can help you with. Only suggestions I have are to try cleaning your app build, pub cache etc to see that will resolve the issue.

**Comment by Azazel17** [comment]
Already create, new project, already apply flutter clean ,already flutter pub cache repair, not sure why is this. 

Any other idea please? 
I'm desperate

**Comment by MaikuB** [comment]
If you clone or download this repository and check the example app (location is [here](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications/example), do you see the same issue reported?

I don't have any other ideas except that you may have an issue with the installation of your Android SDK and/or Flutter SDK installation. You may need to try uninstalling and reinstalling those. If that doesn't work then you may need to find someone that can help look into the setup of your dev environment (e.g. can start from looking [here](https://flutter.dev/community)) as this isn't something I can help with

**Comment by Azazel17** [comment]
Already done, repo cloned, and the example says 'unresolved package dexterous'

Schedules notifications works, however when i restart the phone scheduled notifications are lost, if i understood the documentation well, adding these lines i can preserve the notifications, am i right?

**Comment by MaikuB** [comment]
Yes that's what those lines would achieve. Since you have the same problem with the example app then that would indicate an issue in your dev environment. I'm assuming you have already run `flutter doctor -v`. If it doesn't indicate any issues then you may need to look at reinstalling the SDK and Android build tools, as well as using a third-party service for doing builds if you can't resolve issues with your setup

**Comment by Azazel17** [comment]
In fact, isn´t working  i have two PC's with the same problem, shouldnt i register the plugin or something?, just like here: 

https://stackoverflow.com/questions/53572110/flutter-push-notifications-even-if-the-app-is-closed

**Comment by Azazel17** [comment]
This is how the manifest from the Example looks


![image](https://user-images.githubusercontent.com/21000114/85216122-a117de00-b346-11ea-9c4c-71bc2ed1963f.png)

This is how my app manifest looks 

![image](https://user-images.githubusercontent.com/21000114/85216138-c278ca00-b346-11ea-970c-ea73676e7be8.png)

And i don´t know what´s wrong

**Comment by MaikuB** [comment]
No. Plugin registration is already handled by Flutter itself. That you have two PCs with the same problem doesn't indicate much. That both have the same issue is not surprisingly if both had been setup the same way.

To reiterate, this is an "environmental" issue not a plugin issue so not something I can help with. You'll need to look elsewhere for help with your Android environment. As you're running on Windows, perhaps you need to look at where the Android SDK and dependencies are installed. The reason I mention this is because Windows has problems with file paths that are too long

**Comment by Azazel17** [comment]
So, about the path and the direrctories, what sugestions you give me to a fresh install

**Comment by MaikuB** [comment]
As close to the root of the drive as possible to avoid running into file path length issues. I'm closing this now because it's not a plugin issue. Please use one of the sites mentioned at https://flutter.dev/community or some live chat app (e.g. Slack) if you need to find more on sorting out your environment

**Comment by Surk217** [comment]
@Azazel17 I've got the same issue.
did you end up solving it?
