### ISSUE TITLE
How to preserve showWeeklyAtDayAndTime notifications even after phorn reboot 

### ISSUE THREAD

**Issue by Azazel17** [MaikuB/flutter_local_notifications#674]
So flutterLocalNotificationsPlugin.schedule are now working after reboot, however Weekly notifications are not working after phone reboot. 

Is this right? Or is a bug on the notifications. 

This part of the  documentation is only for flutterLocalNotificationsPlugin.schedule? 

By the way scheduled notifcations start working after android studio reboot

**Comment by MaikuB** [comment]
> Is this right? Or is a bug on the notifications

That's not right. Did you check the behaviour in the example app?

**Comment by MaikuB** [comment]
Closing due to lack of response.  If you have found a bug, then feel free to open a new issue using the bug report template and provide all of the information mentioned in it

**Comment by man991** [comment]
I have an issue. this library will stop working after the user clear the app data or clear cache. is there any idea to solve this problem?

**Comment by MaikuB** [comment]
None as far as I know. The native Android APIs don't persist alarms on reboot so the info needs to be saved so they can stay scheduled on a reboot. You may need to consider putting in a warning about what clearing the app data will do
