### ISSUE TITLE
Periodicaly notification with different content

### ISSUE THREAD

**Issue by burhanerdinc** [MaikuB/flutter_local_notifications#675]
I made a dictionary app  and with local notification i remind the words randomly selected. But app shows same notification every time. I'm don't able to show different word.
```
 Future _showNotification(RepeatInterval rp) async {
    Peyv peyv = await dbHelper.getRand();
    var androidPlatformChannelSpecifics = new AndroidNotificationDetails(
        'asd', 'Ferhenga Kurdî Tirkî', 'your channel description',
        ticker:'ticker',
        importance: Importance.Max,
        priority: Priority.High,
        groupKey: "rozer.ferheng",
        playSound: false,
        channelAction: AndroidNotificationChannelAction.Update);
    var iOSPlatformChannelSpecifics = new IOSNotificationDetails(presentSound: false);
    var platformChannelSpecifics = new NotificationDetails(
        androidPlatformChannelSpecifics, iOSPlatformChannelSpecifics); 
  
    await fnp.periodicallyShow(
      peyv.id,
      peyv.peyv,
      peyv.wate,
      rp,
      platformChannelSpecifics,
      payload: peyv.id.toString(),
    );
   
  }
```

**Comment by MaikuB** [comment]
This is working as expected. You'll need to write your own code to schedule a notification one at a time to be able to do what you need

**Comment by burhanerdinc** [comment]
I wanna show randomly show content in notification in every.hour but shows same content always

**Comment by MaikuB** [comment]
I know what you're tried to do but the code you wrote doesn't match your intent. Take a closer look at your code, when `_showNotification` is called, what it does it get a random instance of a `Peyv` object and requests to periodically show a notification with the details of that specific `Peyv` object. The method is called `periodicallyShow` because it's meant to periodically show the same notification as opposed to something like `periodicallyShowRandomDetails`

**Comment by MaikuB** [comment]
Forgot to add, this has been approached from the wrong angle as well. You should be looking at how to periodically run a task that would obtain a random word and show that word via a notification. Completely different from periodically showing a notification. Take a look at pub.dev for plugins that can assist you with this
