### ISSUE TITLE
Add option to set notification subtitle on iOS

### ISSUE THREAD

**Issue by MindaugasVarkalys** [MaikuB/flutter_local_notifications#676]
iOS has a capability to show not only title and body, but also subtitle of the notification. This is unique to iOS, but I cannot find such option in `IOSNotificationDetails`. Is it possible to set subtitle using this plugin? If not, I think it would be a useful feature, which is easy to implement.

**Comment by MaikuB** [comment]
This is available in the 1.5.0 beta release
