### ISSUE TITLE
Custom notification icon color

### ISSUE THREAD

**Issue by ravitejaavv** [MaikuB/flutter_local_notifications#678]
How do i change notification icon color?

**Comment by MaikuB** [comment]
Please refer to the example app that has sample code for this. There are API docs as well

**Comment by antoine92190** [comment]
@MaikuB I cannot see any sample code referring to the notification icon color, and cannot find it in the docs.
The same issue was raising for firebase_messaging, and the solution was to add the below code in AndroidManifest:
```
        <meta-data
          android:name="com.google.firebase.messaging.default_notification_icon"
          android:resource="@drawable/ic_stat_ic_notification" />
        <meta-data
          android:name="com.google.firebase.messaging.default_notification_color"
          android:resource="@color/colorAccent" />
```

The `colorAccent` then needs to be added in `app/src/main/res/values/colors.xml`

Is there a similar approach for this plugin? Else what is the correct way to do it? I tried to add a coloured icon in `app/src/main/res/drawable/my_icon.png` but the icon color is still grey

**Comment by MaikuB** [comment]
How are your looking through the docs and code? Did you run the example app? One of the very first buttons in the example app is described as showing the icon in red 

https://github.com/MaikuB/flutter_local_notifications/blob/dbe1e65429f647611f60f157c9177d3e46f8dcae/flutter_local_notifications/example/lib/main.dart#L260

There's a search bar you can use for the API docs too

![Screenshot_20200724-093213](https://user-images.githubusercontent.com/25263378/88348492-e8075200-cd90-11ea-9dff-ba5b254b395c.png)

**Comment by antoine92190** [comment]
Indeed, thanks.
I searched through the Readme and was expecting the setting to be in AndroidManifest or in other android files.
Forgot the API docs generated by pub.
