### ISSUE TITLE
My Build fails

### ISSUE THREAD

**Issue by kcilek** [MaikuB/flutter_local_notifications#68]
I am very new to Flutter so maybe someone can help me.
When I have added this package to the pupspec.yaml the following error comes up:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'com.android.support:support-compat' has different version for the compile (26.1.0) and runtime (27.1.0) classpath.

**Comment by MaikuB** [comment]
See #5
