### ISSUE TITLE
Introduce condition function that decides whether or not to show a scheduled notification

### ISSUE THREAD

**Issue by limburgie** [MaikuB/flutter_local_notifications#684]
First of all, congratulations with this awesome plugin.

I'm working on an app that followups patients with their daily medication. In the app, the patient can confirm if he/she took her daily dose. A notification should be shown at 9PM if today's dose was not yet taken.

I used the following code succesfully (I left the initialization code out):

```
Future<void> scheduleNotification(Time time) async {
    await _notificationPlugin.cancelAll();

    var androidSettings = AndroidNotificationDetails(CHANNEL_ID, CHANNEL_NAME, CHANNEL_DESCRIPTION);
    var iosSettings = IOSNotificationDetails();
    var settings = NotificationDetails(androidSettings, iosSettings);

    await _notificationPlugin.showDailyAtTime(0, "My Meds", "Forgot to take your daily dose?", time, settings);
}
```

However, with the code above the notification is also displayed if the patient already took the dose. I found no way to make the appearance of the notification conditional.

E.g.:

```
Future<void> scheduleNotification(Time time) async {
    ...

    await _notificationPlugin.showDailyAtTime(0, "My Meds", "Forgot to take your daily dose?", time, settings, showCondition);
}

Future<bool> showCondition() async {
    return await DailyDoseRepo.userTookTodaysDose();
}
```

Is something like this on your roadmap or do you see another way of doing this with the current state of your plugin?

Thanks a lot for your time and any pointers.
Peter

**Comment by MaikuB** [comment]
This was asked in an older issue. Please see the response [here](https://github.com/MaikuB/flutter_local_notifications/issues/131#issuecomment-491754391)
