### ISSUE TITLE
How to give notice according to the working day, or according to the specified days of the week? Can you specify only one week at the moment? I hope I can get a response from you, thank you!

### ISSUE THREAD

**Issue by Tate-zwt** [MaikuB/flutter_local_notifications#687]
How about monthly notifications? If you do not have this feature, hope to add this feature, or can you tell me how to modify it?, thank you!

**Comment by MaikuB** [comment]
There are no plans to add either feature, though I would've thought you just schedule multiple weekly notifications for each day of the week. If you need certain features for app, then you'll need to write your own code for it e.g. fork the plugin and study the native notification APIs to see how to do it
