### ISSUE TITLE
Interested in a PR to support getActiveNotifications?

### ISSUE THREAD

**Issue by vkammerer** [MaikuB/flutter_local_notifications#690]
Hello @MaikuB ,

Would you be interested in a PR that adds support for [Android's getActiveNotifications](https://developer.android.com/reference/android/app/NotificationManager#getActiveNotifications()) ?
The implementation could check the API Level and return an error message if the user is under version 23.

**Comment by MaikuB** [comment]
If there's a way for developers to check the API level and not just rely on the error then yeah I'm happy to take a look at it. Haven't use it for checking API level but it looks like the `device_info` plugin can do this. If so, updating the example app to make use of that would be awesome :)

**Comment by MaikuB** [comment]
Forgot to add, if you open a PR can you do that against the `timezone_macos_support` branch? That's the branch I'm using for the beta release

**Comment by vkammerer** [comment]
Ok great, so just to clarify, what do you think if I:
- add a new method in [flutter_local_notifications_plugin.dart](https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/lib/src/flutter_local_notifications_plugin.dart) that would look like
```dart
Future<List<ActiveNotification>> getActiveNotifications() async {
    if (_platform.isAndroid) {
      await resolvePlatformSpecificImplementation<
              AndroidFlutterLocalNotificationsPlugin>()
          ?.getActiveNotifications();
    } else {
      return null;
    }
}
```
- implement the method `getActiveNotifications` that would return the following values:
```dart
[Instance of ActiveNotification] // with the active notifications if any are present 
[] // if there is no active notification
null // if the API level is under 23
```
- implement a new button in the example app, which would:
  - first query the Android API Level with the `device_info` plugin
  - then either:
    - display a message "ActiveNotifications is available only for Android API Level 23 +
and above" if the user is under 23
    - or display a message with the notifications data

**Comment by MaikuB** [comment]
With the federated plugin implementation (see this [doc](https://docs.google.com/document/d/1LD7QjmzJZLCopUrFAAE98wOUQpjmguyGTN2wd_89Srs/edit) for more info if you're interested), the shift is to move away from having no-op methods in the cross-platform facing API to have it being a monolith. As such,  `getActiveNotifications()` should be left out of the `FlutterLocalNotificationsPlugin` class. Developers do have the ability to get the underlying platform-specific implementation to access platform-specific methods. Everything else sounds good to me.  Wasn't mentioned happy to have the readme updated to include mention of the feature as well :)

**Comment by vkammerer** [comment]
Ok that sounds great. I'll open the PR next week as I just left for a small
vacation touring the North Island

**Comment by MaikuB** [comment]
No worries. Only other thing that came to mind now is whether not an exception should be thrown instead when API level is under 23.

Anyway enjoy your time off. I'll have to check out the North Island one day as I've only visited the south :)

**Comment by vkammerer** [comment]
closing since the discussion can go on in https://github.com/MaikuB/flutter_local_notifications/pull/704
