### ISSUE TITLE
MacOS support

### ISSUE THREAD

**Issue by maxisme** [MaikuB/flutter_local_notifications#695]
Hello,

I got this up and running on MacOS:
```
$ flutter config --enable-macos-desktop
$ flutter create .
$ flutter run -d macos
```

But unfortunately when clicking any of  the buttons I do not get a notification on my Mac. Am I doing something wrong (entitilements perhaps?), or is it just unsuported?

Thank you.

**Comment by MaikuB** [comment]
Did you make sure to get the correct version of the plugin? MacOS support was only added in the current 1.5.0 beta

**Comment by maxisme** [comment]
I did not - Thank you for that! Sorry!
