### ISSUE TITLE
send notifications after APP terminated

### ISSUE THREAD

**Issue by jinfagang** [MaikuB/flutter_local_notifications#696]
Is that possible send scheduled notification after app terminated? (say user killed it in background manager?)

**Comment by MaikuB** [comment]
The functionality about to schedule is available in the plugin and is mentioned in the documentation. If you to explore how things work, please make use of the example app included in the repo

**Comment by jinfagang** [comment]
@MaikuB  hi, I knew it can schedule, i just want to know if it can keep notification when app terminated by user

**Comment by MaikuB** [comment]
Yes and that should be something you can confirm yourself using e.g. using the example app

**Comment by jinfagang** [comment]
Question is, once I killed the app, the scheduled notification doesn't show.... my phone is Xiaomi

**Comment by MaikuB** [comment]
https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#scheduled-android-notifications
