### ISSUE TITLE
Navigating to a second screen in the example app doesn't result in a full-screen transition upon tapping on a notification on Android while the app is running 

### ISSUE THREAD

**Issue by praveendp526** [MaikuB/flutter_local_notifications#70]
This issue i am facing when using flutter version 2.3, u have mentioned like it got fixed in flutter master channel.
can you help which files need to be modified for fixing this

**Comment by MaikuB** [comment]
see other thread and it would also help if you don't spam comments across multiple issues. this was a flutter issue not an issue with the plugin so i'm closing this
