### ISSUE TITLE
Auto remove notification with IOS in foreground while not yet click or tap  

### ISSUE THREAD

**Issue by Kimsoer** [MaikuB/flutter_local_notifications#701]
I have problem with IOS:
it always auto remove notification with IOS in foreground while not yet click or tap. if app in background no problem

**Comment by MaikuB** [comment]
It's not mentioned in your post but are you using `firebase_messaging`? If so, this is an issue with that plugin

**Comment by adario** [comment]
@MaikuB Any suggestions about how to make `flutter_local_notifications` with `firebase_messaging`?
I'm using the latest version of both plugins on iOS 13+: both plugins appear to be initialised properly, but `firebase_messaging` always consumes all notifications before `flutter_local_notifications` has a chance to receive them...

**Comment by MaikuB** [comment]
Sorry but not sure what you mean and how your issue relates to the issue that was originally reported. `firebase_messaging` does have steps that need to be followed to allow both plugins to work together though the issue of notifications being cleared automatically is an issue with `firebase_messaging`

**Comment by adario** [comment]
@MaikuB Apologies if I've posted on the wrong issue.
What I meant was: both plugins work fine for me, on both iOS and Android — as long as they are not used together.
When the plugins are used together, `firebase_messaging` always ends up consuming all received notifications, before `flutter_local_notifications` has any chance to process them...
Thanks anyways.

**Comment by Kimsoer** [comment]
@MaikuB Hello bro, i use it both with firebase_messaging and local notification, i receive notification from firebase then i notify to call  local notification to push it . it show normally but it auto remove

**Comment by MaikuB** [comment]
@Kimsoer this is an issue with the `firebase_messaging` plugin https://github.com/FirebaseExtended/flutterfire/issues/762 not an issue with this plugin
