### ISSUE TITLE
Support for Yearly and Monthly schedulers

### ISSUE THREAD

**Issue by nsjcorps** [MaikuB/flutter_local_notifications#702]
Currently, you can set notifications to repeat daily and weekly. Can there be support for Monthly and Yearly repeat?

**Comment by MaikuB** [comment]
I've no plans to work on this. Monthly has been asked about and there've been explanations on why it's not supported as monthly can mean different things for different use cases. You'll need to look into your own solution for this and the code is open source for you to use as a starting point

**Comment by nsjcorps** [comment]
Alright. Thanks!
