### ISSUE TITLE
Cannot run example project on real ios divice

### ISSUE THREAD

**Issue by cuong1112035** [MaikuB/flutter_local_notifications#703]
I download the example of this package and try to run it. 
I run into an issue, which is I cannot run the example on my real ios device but it work pretty well on my real android device. When running, the console log show some messages then stop working

```
Running Xcode build...
Xcode build done.                                           14.4s
Installing and launching... 
```
Please help

**Comment by MaikuB** [comment]
Assuming you got the example by downloading/cloning the entire repo, I'd suggest you double check your iOS setup. I haven't heard anyone else with this issue so can't really help you

**Comment by cuong1112035** [comment]
Seem like the app is opened, then somehow, it enters background. To run project, I have to tap on the app icon on my device

**Comment by MaikuB** [comment]
I believe you have an issue with your own environment that you need to sort out so not something related to this plugin or the example app. As mentioned earlier, no one else has reported this issue and if there was a problem like this, someone else would've reported it. I just double checked and it runs on my iPad. Closing this as you'll need to find help elsewhere e.g. try one of the places mentioned at https://flutter.dev/community
