### ISSUE TITLE
When apps goes back to homescreen, notification doesn shows

### ISSUE THREAD

**Issue by jinfagang** [MaikuB/flutter_local_notifications#705]
Hi, when apps goes back to homescreen (not eliminate it), the scheduled notifications can not be shown anylonger.

**Comment by MaikuB** [comment]
If you have found a bug, make sure to file a proper/full bug report and do due diligence in making sure that the example app doesn't exhibit the same behaviour. Part of this is to ensure open source projects are sustainable as many of them are done in spare time and provided freely. So far it looks like you're opening issues after missing steps and having issues in your own code. Closing until you investigated this on your own fully to file a bug report properly

**Comment by jinfagang** [comment]
@MaikuB I dont think it's a bug, but notification not works as I expected. I tried your example APP, when fire a scheduled notification, If app keeps in foreground, it can show, if swip back to homescreen, the notification will not show.

**Comment by MaikuB** [comment]
> I dont think it's a bug, but notification not works as I expected.

What you're describing would be a bug

> . I tried your example APP, when fire a scheduled notification, If app keeps in foreground, it can show, if swip back to homescreen, the notification will not show.

Have you tested this on an Android emulator?
