### ISSUE TITLE
Question about initializing plugin only once

### ISSUE THREAD

**Issue by elouiestudent** [MaikuB/flutter_local_notifications#707]
The documentation states that initialization should be done once and can be done either in the main function or within the first page of the app. My question is what happens if you initialize the plugin in a function that has the potential to be called multiple times (e.g. google_maps_flutter onMapCreated method in the GoogleMaps class)?

**Comment by MaikuB** [comment]
You may see issues like this https://github.com/MaikuB/flutter_local_notifications/issues/698
