### ISSUE TITLE
Option to have a String ID.

### ISSUE THREAD

**Issue by junaidlodhi22** [MaikuB/flutter_local_notifications#709]
i am using firestore for my backend. It would be nice to have an id as String. So i would be able to delete a particular notification whose entry has been deleted from firestore?

**Comment by MaikuB** [comment]
This can't be done, they were made integers to begin with as that's the only option on Android. It's your application's responsibility to map the IDs to whatever data is there in Firestore.

**Comment by junaidlodhi22** [comment]
ok... Thank you for your response

**Comment by Bryanx** [comment]
You can store the firestore id in the payload, you will have duplicate id's but I think this is the best alternative right now.
