### ISSUE TITLE
[iOS] Calling requestPermissions a second time after denying permissions

### ISSUE THREAD

**Issue by elouiestudent** [MaikuB/flutter_local_notifications#710]
After the user denies the initial request for notification permissions, any further calls of requestPermissions just gives the status of the permission and does not show the permission requesting popup again. Is this the intended behavior of the method?

**Comment by MaikuB** [comment]
Yes as that's the behaviour on iOS for any permissions prompt when it's been denied. Users need to go to the settings of the phone to manually change

**Comment by elouiestudent** [comment]
Got it. Thanks for the clarification!

**Comment by MaikuB** [comment]
Not something I've tried out but you may want to consider plugins like https://pub.dev/packages/app_settings to open the settings from your application as well

**Comment by elouiestudent** [comment]
Thanks for the help! I will look into it.
