### ISSUE TITLE
Setting banner to alert style in MacOS

### ISSUE THREAD

**Issue by maxisme** [MaikuB/flutter_local_notifications#715]
**Describe the bug**
When adding `NSUserNotificationAlertStyle`: `alert` to my Resources/info.plist  my notifications are still acting as banners. (i.e shouldn't disappear and should have close button) Any idea why?

**To Reproduce**

1.  Add `NSUserNotificationAlertStyle`: `alert` to my Resources/info.plist in your macos project.

**Expected behavior**
Show an alert style notification

**Sample code to reproduce the problem**
N/A

**Comment by MaikuB** [comment]
Perhaps to do with code signing according to this thread. That setting in info.plist is an app setting and isn't something used directly by the plugin

**Comment by MaikuB** [comment]
Closing this as from my understanding it's outside the control of this plugin
