### ISSUE TITLE
Payload  in onSelectNotification remains not null forever after notification click

### ISSUE THREAD

**Issue by Shakle** [MaikuB/flutter_local_notifications#716]
**Describe the bug**
_Reproduces in example app_

**Android only**
If you click on a notification with payload, it then makes actions in onSelectNotification, then on every app restart the payload is not null, it is the same as it was on last notification click

**To Reproduce**
1. Click show plain notification with payload
2. Restart the app

**Expected behavior**
Payload must become null after notification has been clicked and onSelectNotification method has finished its work

**Comment by MaikuB** [comment]
Sorry but I don't understand what you're trying to describe here, could you please add more details to describe the exact steps you're referring and include a recording if possible. Whilst I don't have a full understanding of what you're trying to describe, it sounds like something that should've been reported more by many others if there was a bug. I'm also wondering if you may have confused resuming a running app with actually restarting an app after it has been killed.

**Comment by Shakle** [comment]
> Sorry but I don't understand what you're trying to describe here, could you please add more details to describe the exact steps you're referring and include a recording if possible. Whilst I don't have a full understanding of what you're trying to describe, it sounds like something that should've been reported more by many others if there was a bug. I'm also wondering if you may have confused resuming a running app with actually restarting an app after it has been killed.


1. I'm in the app
2. Notification with payload comes
3. I click on notification
4. onSelectNotification method redirects me to page 2
5. I click on green play icon in Android Studio (full app restart)
6. It reloads the app and onSelectNotification method continues to see the payload from last notification, so it continues to redirect to page 2 on each app restart (without clicking on any notifications)

**Comment by Shakle** [comment]
Hm, tested it with built .apk and it appears that if I totally close the app, then there is no such problem, but it can be a problem for developing in such case, because it will open something on every app refresh

**Comment by MaikuB** [comment]
I believe you're referring to a hot restart, this doesn't actually restart the app like it would normally do on an actual device. What you're seeing is more of a quirk on Android and isn't something that can be changed/addressed. Closing this based on what I mentioned and it's not something that occurs upon an actual restart
