### ISSUE TITLE
custom sound doesn't work on release build

### ISSUE THREAD

**Issue by mahmoud-haj-ali** [MaikuB/flutter_local_notifications#718]
First of all thanks for this nice work.
I am new in flutter and i tried to play a custom sound when the notification is pushed on android but in release mode I only have the default sound.
I added the mp3 file in raw directory and it works fine in debug mode.
any help please?

**Comment by MaikuB** [comment]
Please make sure you've followed everything in the readme. There's a section that explicitly calls out that there are steps needed for release builds on Android https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#release-build-configuration

**Comment by mahmoud-haj-ali** [comment]
I forgot to add keep.xml file in raw.
now it's work, thanks alot.
