### ISSUE TITLE
Scheduling error on relaunching the app

### ISSUE THREAD

**Issue by pashva** [MaikuB/flutter_local_notifications#719]
Hello,
      Scheduling a notification is working fines unless and until I relaunch the application.
The scheduled notifications no longer work after that. What is the reason behind this?

**Comment by MaikuB** [comment]
Sorry but it's not clear exactly what you mean here but suspect you have a bug in your own app that you'll need to solve. If you've come a bug with the plugin, you can file a bug report using the template with the details that's needed. Also note the cavaets etc mentioned in the readme [here](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#scheduled-android-notifications)

**Comment by MaikuB** [comment]
Closing due to lack of further response
