### ISSUE TITLE
Exception: android.content.ComponentName android.content.Intent.getComponent()

### ISSUE THREAD

**Issue by felipemy** [MaikuB/flutter_local_notifications#721]
Hi,
After reading the readme and the example back and forth several times, and even trying other examples, the same error stills showing up by the time the notification should be displayed.
I couldn't identify which object is being considered null (the icon is ok and clearly throws a different exception, and all others elements are strings).
What could be missing?

Notes:
- Plugin version: 1.4.4+2
- Android: 8.1
- Proguard rules set as the example

Thanks for the help!

The error:
> E/MethodChannel#dexterous.com/flutter/local_notifications(22472): Failed to handle method call
E/MethodChannel#dexterous.com/flutter/local_notifications(22472): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.ComponentName android.content.Intent.getComponent()' on a null object reference
E/MethodChannel#dexterous.com/flutter/local_notifications(22472): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.getMainActivityClass(FlutterLocalNotificationsPlugin.java:477)
E/MethodChannel#dexterous.com/flutter/local_notifications(22472): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification(FlutterLocalNotificationsPlugin.java:131)
E/MethodChannel#dexterous.com/flutter/local_notifications(22472): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification(FlutterLocalNotificationsPlugin.java:688)
E/MethodChannel#dexterous.com/flutter/local_notifications(22472): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.show(FlutterLocalNotificationsPlugin.java:827)
E/MethodChannel#dexterous.com/flutter/local_notifications(22472): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(FlutterLocalNotificationsPlugin.java:750)
E/MethodChannel#dexterous.com/flutter/local_notifications(22472): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:230)
E/MethodChannel#dexterous.com/flutter/local_notifications(22472): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#dexterous.com/flutter/local_notifications(22472): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:650)
E/MethodChannel#dexterous.com/flutter/local_notifications(22472): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#dexterous.com/flutter/local_notifications(22472): 	at android.os.MessageQueue.next(MessageQueue.java:325)
E/MethodChannel#dexterous.com/flutter/local_notifications(22472): 	at android.os.Looper.loop(Looper.java:145)
E/MethodChannel#dexterous.com/flutter/local_notifications(22472): 	at android.app.ActivityThread.main(ActivityThread.java:6521)
E/MethodChannel#dexterous.com/flutter/local_notifications(22472): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#dexterous.com/flutter/local_notifications(22472): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/MethodChannel#dexterous.com/flutter/local_notifications(22472): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
E/flutter (22472): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'android.content.ComponentName android.content.Intent.getComponent()' on a null object reference, null)

**Comment by MaikuB** [comment]
I don't know what's missing. Do you run into the same problem with the example app? If not, then you'll need to check more thoroughly to see what the difference is as I haven't seen anyone report the same kind of error

**Comment by felipemy** [comment]
I didn't commit the example app into my project (currently not using RXdart and other stuff), but did implemented as close as possible file by file. Looking again, the example import those two libs at Main activity: 

> import android.content.ContentResolver;
> import android.content.Context;

May be there are related?
I copied as they are, but still got they same error. What would be a minimal implementation (without the testing side i.e.)?

PS: I also tested trying to parse almost every possible argument to AndroidNotificationDetails(), but still no lucky.

**Comment by MaikuB** [comment]
With regards to running the example app to seeing if you have the same issue there,  I'm referring to downloading/cloning the repository and running the example app. That app is pretty much a minimal implementation. It's best to run the example app to see if you have the same problem first instead of guessing

**Comment by felipemy** [comment]
Yes, when downloading the example and running it apart everything works as expected!
I'm new to Flutter, so that is why I'm trying to check what there is in example app that isn't in the Readme, aside from stuff like Rxdart and provider, that could be related to that error message.
Thanks for helping!

**Comment by MaikuB** [comment]
Afraid I don't know what the issue is here then unless you're able to stand up a minimal sample app that reproduces the problem. Also need to know what version of Flutter you're running and what mode (debug or release) that this occurs on

**Comment by felipemy** [comment]
As when reproducing the same code of the particular dart file in another file its works, I can't figure which part of the app is causing the error. So for now I'm unable to post what would a sample app that reproduces this in minimal.
I'll seek for help on internet to see how can trace this error.
For reference:
Occurs both in debug and release mode
Flutter 1.19.0-4.3.pre
Dart 2.9.0 (build 2.9.0-14.1.beta)
Thank you

**Comment by felipemy** [comment]
@MaikuB ,
After a deep digging, I found the root cause is the addition of the intent filters required by the usage of **Firebase Dynamic Link** plugin at the **AndroidManifest.xml**:
**If you add:**
`    <data
        android:host="example.com"
        android:scheme="https"/>`
**Or:**
`    <data android:host="example.com/link" android:scheme="http"/>`
`    <data android:host="example.com/link" android:scheme="https"/>`

Reference: https://firebase.google.com/docs/dynamic-links/android/receive

I made a separate test by creating a new project and the plugin doesn't need to be used at all (no matter if is included in pubspec.yaml). Just by adding those lines in the AndroidManifest.xml in enough to cause the error.

**Comment by MaikuB** [comment]
Can you fork the repo and make the changes you're referring to in the example app so I can see the difference and reproduce this more easily?

**Comment by felipemy** [comment]
Sure, here is it:
https://github.com/felipemy/flutter_local_notifications/blob/master/flutter_local_notifications/example/android/app/src/main/AndroidManifest.xml

**Comment by MaikuB** [comment]
Getting late so haven't run and confirmed this but my understanding is (and the docs say this as well) that you're suppose to *add* an intent filter. In the link you sent you've modified the existing intent filter

**Comment by felipemy** [comment]
I tested and can confirm that by creating a new intent-filter cluster, it works again!
A think to note is by modifying, everything else runs without any errors on debug messages. FB Dynamic Links was working as expected and other platform dependent plugins as well. Therefore, don't know why this affected flutter_local_notifications in particular.
At last, as new to this development, wasn't clear to me that add a new filter actually means a new cluster, thanks for helping!
