### ISSUE TITLE
local notification not coming in android 10 while app is closed

### ISSUE THREAD

**Issue by krivir** [MaikuB/flutter_local_notifications#724]
Hello,
I have two different android OS devices, that is android 8 & android 10.
Scheduling a local notification is working fine in android 10 unless and until my app is either in foreground or background. When my app is closed or killed from the latest app list tray, in android 10 local notification are not worked.

While  in android 8 , all the state local notification are perfect.

This i have checked from sample example.
Where m going wrong?

**Comment by MaikuB** [comment]
Exactly what Android 10 device do you have?

**Comment by MaikuB** [comment]
Should add there no issues related to Android 10. I have a Pixel 4 XL myself

**Comment by krivir** [comment]
Hey,
i was testing in RedMi with android 8 & OnePlus with android 10 devices,

but after adding the channelId, ChannelNamel in example, notifcations are working fine with device.

sorry for the inconvenience.

**Comment by MaikuB** [comment]
Sounds like it's sorted so will close though not sure why you said you had to add things unless things weren't working because you modified the code.

Also note that as mentioned in the readme, some Android devices restrict what can run in the background. This isn't something the plugin can circumvent

**Comment by saswatsaubhagya** [comment]
i am using Asus rog 2 android 10 . it is not working for me.

[✓] Flutter (Channel stable, 2.0.4, on macOS 11.2.3 20D91 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.55.0)
[✓] Connected device (2 available)

//set up

```

    FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
        FlutterLocalNotificationsPlugin();
// initialise the plugin. app_icon needs to be a added as a drawable resource to the Android head project
    const AndroidInitializationSettings initializationSettingsAndroid =
        AndroidInitializationSettings('icon');
    final IOSInitializationSettings initializationSettingsIOS =
        IOSInitializationSettings(
            onDidReceiveLocalNotification: onDidReceiveLocalNotification);
    final MacOSInitializationSettings initializationSettingsMacOS =
        MacOSInitializationSettings();
    final InitializationSettings initializationSettings =
        InitializationSettings(
            android: initializationSettingsAndroid,
            iOS: initializationSettingsIOS,
            macOS: initializationSettingsMacOS);
    await flutterLocalNotificationsPlugin.initialize(initializationSettings,
        onSelectNotification: selectNotification);
  }
```


//periodic notification


```
    const AndroidNotificationDetails androidPlatformChannelSpecifics =
        AndroidNotificationDetails('saswat', 'saswat', 'saswat');
    const NotificationDetails platformChannelSpecifics =
        NotificationDetails(android: androidPlatformChannelSpecifics);
    await FlutterLocalNotificationsPlugin().periodicallyShow(
        0,
        'repeating title',
        'repeating body',
        RepeatInterval.everyMinute,
        platformChannelSpecifics,
        androidAllowWhileIdle: true);
```

**Comment by MaikuB** [comment]
@saswatsaubhagya check your phone's settings as as this would related to what I wrote [here](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#scheduled-android-notifications).
