### ISSUE TITLE
Cancel notification prints round brackets

### ISSUE THREAD

**Issue by BassamxMednini** [MaikuB/flutter_local_notifications#725]
**To Reproduce**

1. Download the example project
2. Start the app and tap on "Cancel notification"

<img width="771" alt="screenshot" src="https://user-images.githubusercontent.com/28794374/88196793-e2e7bd00-cc41-11ea-802d-be8b37ceac04.png">

**Comment by MaikuB** [comment]
This isn't something the plugin itself is doing as there's no code to print brackets so outside of the plugin's control so not something that can be fixed

**Comment by BassamxMednini** [comment]
What then could be the cause?

**Comment by MaikuB** [comment]
Could be something to do with Flutter as it's not printing the brackets in XCode
