### ISSUE TITLE
Default sound not working and icon always in grey

### ISSUE THREAD

**Issue by JinxParas** [MaikuB/flutter_local_notifications#726]
Hi i have configured local notifications, but getting issue for playing default sound.
Also facing issue with icon, notification icon always showing in grey color

**Comment by MaikuB** [comment]
This is happening as you haven't configured everything properly. Please go through the readme and follow all instructions

**Comment by JinxParas** [comment]
I have read and found its configured properly

**Comment by MaikuB** [comment]
That is what a few of others have said before when they raised this issue (which you can search) only to find out that was not the case. Regardless this is an issue on your end and until you follow all instructions (e.g. https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#release-build-configuration). This is for you to resolve on your end as there no bugs around the plugin on this
