### ISSUE TITLE
Badge not showing on application icon iOS

### ISSUE THREAD

**Issue by pkmangukiya** [MaikuB/flutter_local_notifications#727]
I sent a push notification with a badge but it does not show the number on an app icon

**Comment by MaikuB** [comment]
This plugin is for *local* notifications not push notifications. Are you sure you're asking on the right repository? If so please make sure to include more detailed information on what you're doing. There are no known issues on showing the badge number when using this plugin on its own on iOS provided you have configured everything properly. Running the example would show that the functionality you've described is working fine.

**Comment by ssabbarw** [comment]
I am using this framework for local notifications.
i have added icon for android notificaion but i couldn't find how to add icon for ios notifications.
Kindly help...

**Comment by MaikuB** [comment]
@ssabbarw what you mention isn't related to this issue but add icons on iOS isn't supported by the platform itself hence why there's nothing on it

**Comment by ssabbarw** [comment]
> @ssabbarw what you mention isn't related to this issue but add icons on iOS isn't supported by the platform itself hence why there's nothing on it
Thanks for reply.

**Comment by MaikuB** [comment]
Closing due to lack of response containing more details of if this is really to do with local notifications
