### ISSUE TITLE
Callback to handle notification is delivered to the user

### ISSUE THREAD

**Issue by leang27** [MaikuB/flutter_local_notifications#729]
Hello there. I’m working on flutter Reminder app that has remind as habit or task. Yeah, your plugin is great and mostly cover on my use cases. But, I don’t see a callback for handle a notification is instantly delivered to the user. I saw a callback on IOSinitialize called “onDidReceivedNotification” but it’s not work as I want. Thank in advance. Appreciate :-)

**Comment by MaikuB** [comment]
Please make sure to read the docs as `onDidReceiveLocalNotification` only works on older iOS versions. General callbacks aren't supported and has been requested before. Please see https://github.com/MaikuB/flutter_local_notifications/issues/21. Even on iOS, the native callbacks only work when the app is in the foreground. If you only need to support those scenarios then the code is there for you to fork and add for yourself.
