### ISSUE TITLE
Notification background color

### ISSUE THREAD

**Issue by mk-dev-1** [MaikuB/flutter_local_notifications#731]
Good Morning,

I would like to customize the background color for a notification that is scheduled via `showWeeklyAtDayAndTime`, however it looks like this is not possible or at least I have been unable to do it. I have set a color in `AndroidNotificationDetails`, which is passed to the `showWeeklyAtDayAndTime` method, but it seems it is only changing the notification's icon color.

I have checked the source code and it seems the `createNotification` method in `FlutterLocalNotificationsPlugin.java` does set the background color, but it seems to be called only for notifications that are shown once, not for repeating notifications.

Can you tell me if I am missing something here or if what I am looking for does indeed not exist currently?

If it does not exist, it would be fantastic if this could be added.

Thank you very much,
Matthias

**Comment by MaikuB** [comment]
> I have checked the source code and it seems the createNotification method in FlutterLocalNotificationsPlugin.java does set the background color, but it seems to be called only for notifications that are shown once, not for repeating notifications.

Where is this code that you mention?

Rather than looking at the plugin's code, what you should be looking at is to see what the native APIs support.

**Comment by mk-dev-1** [comment]
Hi,

what I am looking for is referred to in the native API docs at
[https://developer.android.com/reference/android/app/Notification#EXTRA_COLORIZED](https://developer.android.com/reference/android/app/Notification#EXTRA_COLORIZED)
and at
[https://developer.android.com/reference/android/app/Notification.Builder#setColorized(boolean)](https://developer.android.com/reference/android/app/Notification.Builder#setColorized(boolean)).

Indeed I seem to have mixed up what `flutter_local_notifications` supports. I was referring to this section here:

```dart
    private static Notification createNotification(Context context, NotificationDetails notificationDetails) {
        setupNotificationChannel(context, NotificationChannelDetails.fromNotificationDetails(notificationDetails));
        Intent intent = new Intent(context, getMainActivityClass(context));
        intent.setAction(SELECT_NOTIFICATION);
        intent.putExtra(PAYLOAD, notificationDetails.payload);
        PendingIntent pendingIntent = PendingIntent.getActivity(context, notificationDetails.id, intent, PendingIntent.FLAG_UPDATE_CURRENT);
        DefaultStyleInformation defaultStyleInformation = (DefaultStyleInformation) notificationDetails.styleInformation;
        NotificationCompat.Builder builder = new NotificationCompat.Builder(context, notificationDetails.channelId)
                .setContentTitle(defaultStyleInformation.htmlFormatTitle ? fromHtml(notificationDetails.title) : notificationDetails.title)
                .setContentText(defaultStyleInformation.htmlFormatBody ? fromHtml(notificationDetails.body) : notificationDetails.body)
                .setTicker(notificationDetails.ticker)
                .setAutoCancel(BooleanUtils.getValue(notificationDetails.autoCancel))
                .setContentIntent(pendingIntent)
                .setPriority(notificationDetails.priority)
                .setOngoing(BooleanUtils.getValue(notificationDetails.ongoing))
                .setOnlyAlertOnce(BooleanUtils.getValue(notificationDetails.onlyAlertOnce));

        setSmallIcon(context, notificationDetails, builder);
        if (!StringUtils.isNullOrEmpty(notificationDetails.largeIcon)) {
            builder.setLargeIcon(getBitmapFromSource(context, notificationDetails.largeIcon, notificationDetails.largeIconBitmapSource));
        }
        if (notificationDetails.color != null) {
            builder.setColor(notificationDetails.color.intValue()); //I think this is used to set the accent (icon) color, not the background, right?
        }

        if (notificationDetails.showWhen != null) {
            builder.setShowWhen(BooleanUtils.getValue(notificationDetails.showWhen));
        }

        if (notificationDetails.when != null) {
            builder.setWhen(notificationDetails.when);
        }

        setVisibility(notificationDetails, builder);
        applyGrouping(notificationDetails, builder);
        setSound(context, notificationDetails, builder);
        setVibrationPattern(notificationDetails, builder);
        setLights(notificationDetails, builder);
        setStyle(context, notificationDetails, builder);
        setProgress(notificationDetails, builder);
        setCategory(notificationDetails, builder);
        setTimeoutAfter(notificationDetails, builder);
        Notification notification = builder.build();
        if (notificationDetails.additionalFlags != null && notificationDetails.additionalFlags.length > 0) {
            for(int additionalFlag:notificationDetails.additionalFlags) {
                notification.flags |= additionalFlag;
            }
        }
        return notification;
    }
```

So unless I'm missing something, there should be a something like (simplified) this added:

```dart
        if (notificationDetails.colorized != null) {
            builder.setColorized(notificationDetails.colorized);
        }
```

**Comment by MaikuB** [comment]
Please submit a PR if it's something you need then

**Comment by mk-dev-1** [comment]
I've tried implementing this, but can't get it to work.

This [source](https://android.jlelse.eu/change-the-colour-of-my-notification-30f00531c13e) suggests it's only possible for foreground service notifications anyway.

Can your or someone else confirm this is not possible? If yes, then I think this issue can be closed (unfortunately)...

**Comment by joandervieira** [comment]
I have the same problem

**Comment by MaikuB** [comment]
@mk-dev-1 yes looks like you'll need custom code for a foreground service for this work as calling `setColorized` did nothing for me either so will close this

**Comment by benechiu** [comment]
Please check this PR for background color support.
#1459
![Screenshot_20220124-181714325](https://user-images.githubusercontent.com/6835856/150765991-47aef357-6914-4683-a4ca-ef26c8398c40.jpg)
