### ISSUE TITLE
Change sound on the same notification channel id does not works

### ISSUE THREAD

**Issue by tukangbikinapps** [MaikuB/flutter_local_notifications#732]
I wanted to replace old notification sound with a new one, however seems it does not work on the same channel id. I tried it on android 29. Let me know if you have feedback on this. thanks

**Comment by MaikuB** [comment]
As covered in the docs, things like sound are tied to the channel and cannot be changed once set. You could uninstall or reinstall the app, or delete (an API exists for this, use the API docs to find it) and recreate the channel. Please read the Android docs around notification channels for to understand more on how they work https://developer.android.com/training/notify-user/channels

**Comment by tukangbikinapps** [comment]
Ah i see, thanks for the quick feedback. Really appreciated.

**Comment by abhishekchotaliya** [comment]
@tukangbikinapps - I solved the same thing using dynamic channels.
```
var androidDetails = new AndroidNotificationDetails(
  "CH$selectedSound",
  selectedSound,
  "timer",
  importance: Importance.High,
  playSound: true,
  sound: sound
);
```
