### ISSUE TITLE
Accessing sound from assets instead raw folder

### ISSUE THREAD

**Issue by tukangbikinapps** [MaikuB/flutter_local_notifications#733]
Hi, i tried to accessing the sound notification from my asset folder instead android/raw folder. I cannot find a way to do this, is it something possible to do ?
The problem it is hard to accesing raw folder on android from flutter code, unless i made a custom plugin to access it. Let me know if you have any feedback on this. Thank you

**Comment by MaikuB** [comment]
>  I cannot find a way to do this, is it something possible to do ?

No. This is the way the native APIs work so you'll need to find your own solution
