### ISSUE TITLE
Notifican icon and largeIcon from SVG asset

### ISSUE THREAD

**Issue by apoleo88** [MaikuB/flutter_local_notifications#738]
Hi!
Thanks for this package, I just started experimenting with it and it works great!

I use SVG assets in my flutter project and I was trying to use them as icon and LargeIcon for the notification.

I saw some references here https://github.com/MaikuB/flutter_local_notifications/issues/393 and here https://github.com/MaikuB/flutter_local_notifications/pull/550 but it is not clear to me how to do that, it appears to me that it still accepts only Android resources?
If it is possible can you provide a small example?

**Comment by MaikuB** [comment]
You're looking at things that are specific to displaying icons for people messages. There are API docs (e.g. https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/AndroidNotificationDetails/largeIcon.html) and the example app to refer to. if you look at those then you should find only bitmaps are supported. The regular notification icon only supports Android resources whilst the large icon can be an Android resource or a file path

**Comment by apoleo88** [comment]
The documentation is not so clear actually.
Anyway, since it is possible to load bitmaps from a file path, then it is possible to convert and save the SVG to a bitmap and use that.

I share the code for who will ever have the same problem.

You need **flutter_svg** library, that you probably already use if you are playing with SVG.
You need also **bitmap** library.

```

    import 'package:bitmap/bitmap.dart';
    import 'package:flutter_svg/flutter_svg.dart';

    String svgString = await DefaultAssetBundle.of(context).loadString(svg_path);
    DrawableRoot svgDrawableRoot = await svg.fromSvgString(svgString, null);
    
    // to have a nice rendering it is important to have the exact original height and width
    // the easier way to retrieve it is directly from the svg string
    String temp = svgString.substring(svgString.indexOf('height="')+8);
    int originalHeight = int.parse(temp.substring(0, temp.indexOf('p')));
    temp = svgString.substring(svgString.indexOf('width="')+7);
    int originalWidth = int.parse(temp.substring(0, temp.indexOf('p')));

    // toPicture() and toImage() don't seem to be pixel ratio aware, so we calculate the actual sizes here
    double devicePixelRatio = MediaQuery.of(context).devicePixelRatio;

    double width = originalHeight * devicePixelRatio; // where 32 is your SVG's original width
    double height = originalWidth * devicePixelRatio; // same thing

    // Convert to ui.Picture
    ui.Picture picture = svgDrawableRoot.toPicture(size: Size(width, height));

    // Convert to ui.Image. toImage() takes width and height as parameters
    // you need to find the best size to suit your needs and take into account the screen DPI
    ui.Image image = await picture.toImage(width.toInt(), height.toInt());
    ByteData bytes = await image.toByteData(format: ui.ImageByteFormat.png);

    // finally to Bitmap
    Bitmap bitmap = await Bitmap.fromHeadless(width.toInt(), height.toInt(),
        bytes.buffer.asUint8List()
    );

    // Let's save the bitmap in the temporary Folder
    File file = File(await getTempFilenamePath(format: '.bmp'));
    file.writeAsBytesSync(bitmap.content);
```
Now you can use:
`      largeIcon: FilePathAndroidBitmap(file.path),`

Some credit to [this StackOverflow answer](https://stackoverflow.com/a/57609840/2155494)

**Comment by MaikuB** [comment]
> The documentation is not so clear actually.

As the type of `largeIcon` is `AndroidBitmap` that can be drilled further to find the subtypes and description, do you have a suggestion on how to make it clearer that only bitmaps are supported then?

**Comment by apoleo88** [comment]
> 
> As the type of `largeIcon` is `AndroidBitmap` that can be drilled further to find the subtypes and description, do you have a suggestion on how to make it clearer that only bitmaps are supported then?
> 
> Edit: PRs are welcome

I think that what misled me was the name `FilePathAndroidBitmap`, I thought it was referring to the file path in the Android Resources. The description in the documentation `Represents a file path that should be used for a bitmap on Android.` as much as it makes sense now, didn't at the time.

In the example you use links, and it confused me because the links are without format and going to the URLs, they look png from the browser?
```
var largeIconPath = await _downloadAndSaveFile('http://via.placeholder.com/48x48', 'largeIcon');
var bigPicturePath = await _downloadAndSaveFile('http://via.placeholder.com/400x800', 'bigPicture');
....
FilePathAndroidBitmap(bigPicturePath)
```

I don't know, it created me some confusion when in the end, is possible to use any type of image, of course, it is not the job of this library to convert and save it as a bitmap on the fly.

**Comment by MaikuB** [comment]
> The description in the documentation Represents a file path that should be used for a bitmap on Android. as much as it makes sense now, didn't at the time.

What was your interpretation at the time and what would help make it clearer then?

> In the example you use links, and it confused me because the links are without format and going to the URLs, they look png from the browser?

The site provides a service for placeholders using the dimensions and the file extension optional. Thanks for the feedback though, will update the example app to make the extension more explicit
