### ISSUE TITLE
Is it possible to customize notification layout?

### ISSUE THREAD

**Issue by vipulgupta114** [MaikuB/flutter_local_notifications#739]
I want to design the layout as in the image. If not can I atleast set a background color to the notification as we used to do in Android using .setColorised( )

![image](https://user-images.githubusercontent.com/30376051/89130185-7a8dbb00-d520-11ea-9841-edcf992732ea.png)

**Comment by MaikuB** [comment]
If you want to a custom layout or a background then you need to do this on your own
