### ISSUE TITLE
[Question] periodic/daily/weekly notifications on iOS

### ISSUE THREAD

**Issue by antoine92190** [MaikuB/flutter_local_notifications#740]
I am aware of the 64 iOS limit to schedule notifications.
Can you confirm that periodic, daily and weekly notifications are indeed considered as a single notification?

**Comment by MaikuB** [comment]
I believe so but not something I've tried. You can run an experiment to confirm

**Comment by antoine92190** [comment]
Ok thanks. I'll run an experiment and post the results here

**Comment by antoine92190** [comment]
It seems like this is indeed the case, it schedules a single notification.
I haven't tested so much on real device, will comment here if I get some issues.

**Comment by MaikuB** [comment]
Thanks for the update. I would expect to be the same, it's rare that I've seen the simulator act different for things like this
