### ISSUE TITLE
Is there way to change push message icon on system tray?

### ISSUE THREAD

**Issue by pineful** [MaikuB/flutter_local_notifications#743]
I want to indicate device status on push message icon, but I think there is only one initialized icon must be used with it.
Is there way to change icon on each push message?
Or do you have any plan to implement this feature?

**Comment by therladbsgh** [comment]
`AndroidNotificationDetails` has a `largeIcon` parameter, which you can use as follows:

```
var androidPlatformChannelSpecifics = new AndroidNotificationDetails(
    'com.example.',
    'Example',
    'Channel example',
    largeIcon: DrawableResourceAndroidBitmap('@drawable_here'),
    playSound: true,
    enableVibration: true,
    importance: Importance.Max,
    priority: Priority.High,
  );
```

**Comment by pineful** [comment]
> `AndroidNotificationDetails` has a `largeIcon` parameter, which you can use as follows:
> 
> ```
> var androidPlatformChannelSpecifics = new AndroidNotificationDetails(
>     'com.example.',
>     'Example',
>     'Channel example',
>     largeIcon: DrawableResourceAndroidBitmap('@drawable_here'),
>     playSound: true,
>     enableVibration: true,
>     importance: Importance.Max,
>     priority: Priority.High,
>   );
> ```

I found the details on your explanation page, thank you so much!
