### ISSUE TITLE
[Feature] Add bi-weekly notifications

### ISSUE THREAD

**Issue by antoine92190** [MaikuB/flutter_local_notifications#744]
Would it be possible to add bi-weekly notifications, so we can schedule notifications every 2 weeks?
I would be happy to make a pull request for that.

**Comment by MaikuB** [comment]
I don't believe so but you may want to take a closer look at the native APIs to confirm. Off memory, the newer iOS notification APIs only allow for time interval (e.g. X number of seconds between each notification) or to match on certain date/time components

**Comment by antoine92190** [comment]
Wouldn't it be the exact same logic than for weekly notifications, but instead of a period of 7 days, it would be 14 days?

**Comment by MaikuB** [comment]
It depends on exactly what you're trying to do e.g. showing a notification at an exact date, which takes daylight savings into account or having a notification fire based on elapsed time.

**Comment by antoine92190** [comment]
It would be to match an exact date, i.e. if I schedule a bi-weekly notification starting on the 15th of August, it will show a notification the 15/08, then 29/08, then 12/09, etc.

Actually I though it would be similar to the `showWeeklyAtDayAndTime` method, but as it's based on weekdays I guess it would be different.

Do you know if it's possible to schedule a recurring notification not based on weekdays as `showWeeklyAtDayAndTime`, but rather on the week number of a year?

For example trigger a notification at the 12th week number of every year?
So we could use that to schedule notifications the 1st, 3rd, 5th... week of each year.

**Comment by MaikuB** [comment]
Not sure. I'd suggest you check their docs and try it out  I don't profess to be an expert on all things to do with notifications. Some knowledge was gained during the development of the plugin as well. Currently I'd have to check the docs to answer your questions and even then I can't say for sure without actually trying

**Comment by antoine92190** [comment]
Ok got it, I'll have a look then

**Comment by antoine92190** [comment]
I looked through the native API, and indeed, bi-weekly notifications is not natively supported.
I have no experience with native coding, so it will be difficult for me to implement a solution at the moment.

However, while browsing for a solution, I found that monthly and yearly notifications are supported.
I know you answered several issues about the subject, and I understand if you're not looking to add this feature.
In that case I will try to implement it myself. But would there be any issue to implement the code below?

```
// The 1st of every month at 12pm
var monthly = DateComponents()
monthly.hour = 12
monthly.day = 1
let monthlyTrigger = UNCalendarNotificationTrigger(dateMatching: monthly, repeats: true)
monthlyTrigger.nextTriggerDate() // "Feb 1, 2017, 12:00 PM"

// Every 1st of February at 12pm
var yearly = DateComponents()
yearly.hour = 12
yearly.day = 1
yearly.month = 2
let yearlyTrigger = UNCalendarNotificationTrigger(dateMatching: yearly, repeats: true)
yearlyTrigger.nextTriggerDate() // "Feb 1, 2017, 12:00 PM"
```
Reference: https://stackoverflow.com/questions/41441124/ios-notification-trigger-fortnightly-and-or-quarterly

**Comment by MaikuB** [comment]
Not as far as I know. Again, I should preface this that I learnt from writing this plugin and don't proclaim to be an expert. That includes learning to write native code as I come from a .NET background. Though I had some familiarity with the APIs having written Xamarin apps that requires using the same APIs but can use C#

**Comment by MaikuB** [comment]
Forgot to add, I'm closing this as bi-weekly notifications as mentioned in your original post isn't supported

**Comment by antoine92190** [comment]
Ok thanks. I'll probably dig into monthly and yearly notifications, and send you a pull request if you are interested.

**Comment by MaikuB** [comment]
If you're going to do any work around scheduling then you should base this off the `time_zone_macos_support` branch as the APIs available around scheduling  notifications that exist in the stable release have been deprecated to allow for new methods where developers need to specify a date and time relative to a time zone. This was done to fix issues with daylight savings

**Comment by antoine92190** [comment]
Ok will do
