### ISSUE TITLE
Is it possible to add 'androidAllowWhileIdle' parameter to 'showDailyAtTime' notification

### ISSUE THREAD

**Issue by Roshanalexander** [MaikuB/flutter_local_notifications#747]
My app uses the ```showDailyAtTime``` function to schedule daily notification. 

``` dart
Future<void> showDailyAtTime (
 int id,
 String title,
 String body,
 Time notificationTime,
 NotificationDetails notificationDetails,
 {String payload}
)
```

The notification does not seem to be triggering on Android at the desired time. There seems to be a delay in showing the notification.

 While looking at the documentation, I found that the ```schedule``` function takes in ```androidAllowWhileIdle``` boolean parameter to have notification appear without a delay. 

``` dart
Future<void> schedule (
 int id,
 String title,
 String body,
 DateTime scheduledDate,
 NotificationDetails notificationDetails,
 {String payload,
 bool androidAllowWhileIdle: false}
)
```
But it seems ```showDailyAtTime'```doesn't support it. Am I missing something? If this feature is not there yet, is it possible to implement it?
Thanks!

**Comment by MaikuB** [comment]
> But it seems showDailyAtTime'doesn't support it. Am I missing something? If this feature is not there yet, is it possible to implement it?

Yes, this is a documented caveat and it's not possible to add it to this method. The method has been deprecated in the 1.5.0 beta and a `zonedSchedule` method was added. Refer to the changelog for more details https://pub.dev/packages/flutter_local_notifications/versions/1.5.0-beta.6/changelog
