### ISSUE TITLE
Provide method to get list of scheduled notifications

### ISSUE THREAD

**Issue by radzish** [MaikuB/flutter_local_notifications#75]

**Comment by MaikuB** [comment]
Would you be able to submit a PR for this? Methods will need to work on both iOS and Android though

**Comment by jonahgreenthal** [comment]
@radzish You might want to keep your own list using the SharedPreferences plugin. You can set/save a `bool` indicating whether a given notification has been set. Obviously you need to have a `String` key; you can just use `id.toString()` or (probably wiser) something like `com.myapp.notifications/####`, where `####` is the ID.

**Comment by MaikuB** [comment]
I've added a `pendingNotificationRequests` method to version 0.6.1. This will return a list of scheduled notifications. Each item will contain basic info common to each platform (id, title, body and payload). Will consider this closed now

**Comment by adrianvintu** [comment]
Hi  @MaikuB, can you also add the trigger/scheduled date as "basic" info?

**Comment by MaikuB** [comment]
no see https://github.com/MaikuB/flutter_local_notifications/issues/245

**Comment by adrianvintu** [comment]
Damn, thank you.
