### ISSUE TITLE
Custom sound doesn't work in background state

### ISSUE THREAD

**Issue by abhijitrajmane** [MaikuB/flutter_local_notifications#753]
**Describe the bug**
 I'm trying to play my own custom sound for firebase notifications in the background state. It just plays the default sound on my own device, it doesn't play custom sound. I tried this but it didn't help me.

**Tested on**
Android 8
flutter_local_notifications: ^1.4.4

**Expected behavior**
When app in background mode play custom sound of a notification

```
class MyApp extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return MyAppState();
  }
}

Future<dynamic> myBackgroundHandler(Map<String, dynamic> message){
  return MyAppState()._showNotification(message);
}


class MyAppState extends State<MyApp> {
  FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin = FlutterLocalNotificationsPlugin();

  final FirebaseMessaging _firebaseMessaging = FirebaseMessaging();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('notification'),
      ),
      body: Center(
        child: Text('button'),
      ),
    );
  }

  Future _showNotification(Map<String, dynamic> message) async {
    var androidPlatformChannelSpecifics = new AndroidNotificationDetails(
      'channel id',
      'channel name',
      'channel desc',
      importance: Importance.Max,
      sound: RawResourceAndroidNotificationSound('alert'),
      playSound: true,
      priority: Priority.High,
    );

    var platformChannelSpecifics = new NotificationDetails(
        androidPlatformChannelSpecifics, null);
    await flutterLocalNotificationsPlugin.show(
      0,
      'new message arived',
      'i want ${message['data']['title']} for ${message['data']['price']}',
      platformChannelSpecifics,
    );
  }


  getToken() async {
    String token = await _firebaseMessaging.getToken();
    print(token);
  }

  Future selectNotification(String payload)async{
    await flutterLocalNotificationsPlugin.cancelAll();
  }


  @override
  void initState() {
    var initializationSettingsAndroid = AndroidInitializationSettings('@mipmap/ic_launcher');

    var initializationSettings = InitializationSettings(
        initializationSettingsAndroid, null);
    flutterLocalNotificationsPlugin.initialize(initializationSettings,
        onSelectNotification: selectNotification);
    super.initState();

    _firebaseMessaging.configure(
      onBackgroundMessage: myBackgroundHandler,
      onMessage: (Map<String, dynamic> message) async {
        print("onMessage: $message");
        _showNotification(message);
      },
    );

    getToken();
  }
}

```

**Comment by MaikuB** [comment]
Integration with firebase isn't something I can help with. Furthermore, you haven't provided a link to a minimal sample app. It's very likely that what you're seeing is a push notification as opposed to a local notification created by this plugin. I say this as background execution runs in its own separate context, which means that instance of the `FlutterLocalNotificationsPlugin` that you created can't be accessed in `_showNotification()` when called in the background. With that it mean, I don't believe the method you wrote is being executed at all.

**Comment by abhijitrajmane** [comment]
> **Describe the bug**
> I'm trying to play my own custom sound for firebase notifications in the background state. It just plays the default sound on my own device, it doesn't play custom sound. I tried this but it didn't help me.
> 
> **Tested on**
> Android 8
> flutter_local_notifications: ^1.4.4
> 
> **Expected behavior**
> When app in background mode play custom sound of a notification
> 
> ```
> class MyApp extends StatefulWidget {
>   @override
>   State<StatefulWidget> createState() {
>     return MyAppState();
>   }
> }
> 
> Future<dynamic> myBackgroundHandler(Map<String, dynamic> message){
>   return MyAppState()._showNotification(message);
> }
> 
> 
> class MyAppState extends State<MyApp> {
>   FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin = FlutterLocalNotificationsPlugin();
> 
>   final FirebaseMessaging _firebaseMessaging = FirebaseMessaging();
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(
>         title: Text('notification'),
>       ),
>       body: Center(
>         child: Text('button'),
>       ),
>     );
>   }
> 
>   Future _showNotification(Map<String, dynamic> message) async {
>     var androidPlatformChannelSpecifics = new AndroidNotificationDetails(
>       'channel id',
>       'channel name',
>       'channel desc',
>       importance: Importance.Max,
>       sound: RawResourceAndroidNotificationSound('alert'),
>       playSound: true,
>       priority: Priority.High,
>     );
> 
>     var platformChannelSpecifics = new NotificationDetails(
>         androidPlatformChannelSpecifics, null);
>     await flutterLocalNotificationsPlugin.show(
>       0,
>       'new message arived',
>       'i want ${message['data']['title']} for ${message['data']['price']}',
>       platformChannelSpecifics,
>     );
>   }
> 
> 
>   getToken() async {
>     String token = await _firebaseMessaging.getToken();
>     print(token);
>   }
> 
>   Future selectNotification(String payload)async{
>     await flutterLocalNotificationsPlugin.cancelAll();
>   }
> 
> 
>   @override
>   void initState() {
>     var initializationSettingsAndroid = AndroidInitializationSettings('@mipmap/ic_launcher');
> 
>     var initializationSettings = InitializationSettings(
>         initializationSettingsAndroid, null);
>     flutterLocalNotificationsPlugin.initialize(initializationSettings,
>         onSelectNotification: selectNotification);
>     super.initState();
> 
>     _firebaseMessaging.configure(
>       onBackgroundMessage: myBackgroundHandler,
>       onMessage: (Map<String, dynamic> message) async {
>         print("onMessage: $message");
>         _showNotification(message);
>       },
>     );
> 
>     getToken();
>   }
> }
> ```

**Comment by UttamPanchasara** [comment]
@abhijitrajmane did you found any way?
