### ISSUE TITLE
No sound, no led

### ISSUE THREAD

**Issue by Mr-Martini** [MaikuB/flutter_local_notifications#754]
**Describe the bug**
The notification title, body, and vibration pattern works as expected in my app, but i can't get the led, sound and color properties to work. So after a fews day trying to solve this, i just cloned the example app and tested in 3 devices (android). None of them worked. The same problem described aboved happened. 
I'm using the default android notification sound, by setting playSound to true, as the documentation says: " If playSound is set to true but this (the sound i assume) is not specified then the default sound is played"

**To Reproduce**
Well, i just cloned the example app

**Expected behavior**
The notification should deliver the specified color, led, sound, title, body, and vibration pattern.

**Sample code to reproduce the problem**
It's the example app of the documentation

flutter doctor -v
[√] Flutter (Channel stable, 1.20.1, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.20.1 at C:\src\flutter
    • Framework revision 2ae34518b8 (8 days ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\marco\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.47.2)
    • VS Code at C:\Users\marco\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.2

[√] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

• No issues found!

**Comment by MaikuB** [comment]
Have you turned on the settings on those devices? From what I remember the setting for the notification led is off by default and some devices may not even have it e.g. Pixel 4. The setting to have the notification sound play is different from volume slider

**Comment by Mr-Martini** [comment]
Hi, thansk for the response.
Yes, my physical device turned on led and sound permission by the default, but it didn't work. 
I'm not sure if i understood your last sentence correctly. Is the notification sound volume independent from android's "main" volume slider?

**Comment by MaikuB** [comment]
Yes as an example the following on my pixel 4 would only cause the phone to vibrate if a notification is displayed

![Screenshot_20200814-091508](https://user-images.githubusercontent.com/25263378/90196262-ba9d4980-de0e-11ea-9d40-5a1bdab45d50.png)

However the sound will play if it's like this 

![Screenshot_20200814-091602](https://user-images.githubusercontent.com/25263378/90196324-d4d72780-de0e-11ea-9ba2-63d21e797cf5.png)

Were you running the example app with the code untouched or did you modify it? Are you able to record and upload a video of you running the example app that also includes showing the settings you have on the phone?

**Comment by Mr-Martini** [comment]
So to make sure I didn't mess the example app, i deleted everything up and cloned it again. Now it works!. I problably edited something and didn't notice it. Thanks for you help. I'm closing this issue.
