### ISSUE TITLE
onSelectNotification callback triggering without click (even in 1.4.4+3 version)

### ISSUE THREAD

**Issue by Keader** [MaikuB/flutter_local_notifications#757]
**Describe the bug**

I'm using version 1.4.4+3 and getting a weird behavior.
Using default flutter application, i made home generate a notification everytime that you hit "+" button

Code is below
main: https://gist.github.com/Keader/278a8f41ea41761bceb4a2f4a1b71975
localNotification: https://gist.github.com/Keader/7e28b3a02190d31ce5135d708d9c3637

Inside of callback, i just put a print on payload.
But after i click in any notification, if i generate any new notification, it will trigger onSelectNotification callback.

**To Reproduce**
1. Check the video: https://www.youtube.com/watch?v=Yf5Q1ZDGK80
2. Note that i click in "1" notification. But when i generate notification 2, 3, 4... i dont click on it, but callback is still called

**Expected behavior**
Callback called only when i click on notification

**Comment by MaikuB** [comment]
You need to restructure your app so it doesn't calling the `initialize` method multiple times and I've mentioned in the readme that this should only be done once. If you look at the example app then you should then it doesn't have the problem you described
