### ISSUE TITLE
[Feature] Permanent / persistent Notifications

### ISSUE THREAD

**Issue by MasseElch** [MaikuB/flutter_local_notifications#76]
I'd like to see a feature to have a persistent / permanent Notification, that cannot be dismissed. 

I myself are very new to Flutter / Dart / Mobile Development, so i wont be able to submit a PR myself (although i am very happy to help where i can).

Example use case:

My app has a offline storage for user experience. If there are changes made that are no yet pushed to the remote server-backend i like to show a permanent notification so the user is reminded he has to open the app to trigger a sync.

**Comment by MaikuB** [comment]
This is only possible on Android and there's already an example for that (ongoing notification)

**Comment by MasseElch** [comment]
Ah, i somehow managed to not see that. Thank you! Closing issue.

**Comment by iftik-OP** [comment]
> Ah, i somehow managed to not see that. Thank you! Closing issue.

Where do you find it, In my case I am using firebase for notifications and I also want the notification to be sticked untill the user completes the task

**Comment by masseelch** [comment]
> > Ah, i somehow managed to not see that. Thank you! Closing issue.
> 
> Where do you find it, In my case I am using firebase for notifications and I also want the notification to be sticked untill the user completes the task
> 

This is 5 years old. I guess the API changed but I don't know since I haven't touched flutter in a long time 🥲
