### ISSUE TITLE
Not working on Redmi phones....

### ISSUE THREAD

**Issue by String-error-404** [MaikuB/flutter_local_notifications#764]
this is a amazing plugin that can i have ever used but in the case of xiaomi devices the while testing it is not working the notification is not triggering with the sound.. 
I have tried in many other phones but the xiaomi devices never worked welll

**Comment by MaikuB** [comment]
Any device-specific issues aren't to do with the plugin. If you're referring to scheduled notifications, please note that it has already been documented that some brands put restrictions in that prevent scheduled notifications from running and Xiaomi is one of those brands

**Comment by String-error-404** [comment]
thanks for your reply i will close the issue

**Comment by String-error-404** [comment]
Hey Micheal Bui that i figured out a way to get the permissions in the
xiaomi phone or huawei phone's that you can use the permission handler
plugin:
https://pub.dev/packages/permission_handler

So that very one knows when they are coming  to your pub.dev and seeing
your plugin so that they can use it for their use .

So i recommend that you mention it in the readme file so that everyone can
know......

Thanks for instant replies...
