### ISSUE TITLE
Notification not firing on android phone reboot

### ISSUE THREAD

**Issue by defemz** [MaikuB/flutter_local_notifications#767]
Hi, thanks for this plugin,
I an developing an application to display notification at chosen dates by users. The notification work properly until android phone is rebooted. The notification is not fired once phone is restarted. I followed the steps in the readme file to the letter, but no luck still. Must i do i any additional thing on my part before the notification can be fired on phone restart? Any help would be appreciated. Thanks. The following is my AndroidManifest file:

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.frame.sched">
    
    <uses-permission android:name="android.permission.READ_CONTACTS" />
    <uses-permission android:name="android.permission.WRITE_CONTACTS" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <uses-permission android:name="android.permission.WAKE_LOCK" />

    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="zozo"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
        <receiver android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver" />
        <receiver android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"/>
                <action android:name="android.intent.action.MY_PACKAGE_REPLACED"/>
            </intent-filter>
        </receiver>

        <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ca-app-pub-xxxxxxxxxxxxxxxxxxxxxxxxxxxx"/>
    </application>
</manifest>

**Comment by MaikuB** [comment]
Have you tried running the example app to see if you have the same problem? You can clone/download the repo to run it but may need to tweak the code for showing a scheduled notification (currently set to appear in 5 seconds) so that you have enough time to have it scheduled and reboot the phone. Asking to see if it's something device-specific as the example has been tested to work before

**Comment by defemz** [comment]
> Have you tried running the example app to see if you have the same problem? You can clone/download the repo to run it but may need to tweak the code for showing a scheduled notification (currently set to appear in 5 seconds) so that you have enough time to have it scheduled and reboot the phone. Asking to see if it's something device-specific as the example has been tested to work before

Hi thanks for the reply. I downloaded the repo and ran it on a phone as is. Unfortunately the notification is still not fired on phone restart. It work as expected before phone restart.

**Comment by MaikuB** [comment]
A few questions

1. What phone are you using?
2. Have you tried this on an emulator and if so, what happens then?
3. When you say it works as expected before restarting, is the app still running in the foreground or has it been killed? If it was from when it was still running, have you tried killing them and not restarting to see if it still appears?

**Comment by MaikuB** [comment]
Closing due to lack of further response

**Comment by chadn4u** [comment]
hello im facing this issue too... notification not fired after reboot... but only in showDailyAtTime when using Importance.max and Priority.High

Im using Xiaomi mi 6 device

**Comment by MaikuB** [comment]
@chadn4u sounds like you haven't read the readme

https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#-caveats-and-limitations

Please make sure you do so

**Comment by hkndzdr** [comment]
> A few questions
> 
> 1. What phone are you using?
> 2. Have you tried this on an emulator and if so, what happens then?
> 3. When you say it works as expected before restarting, is the app still running in the foreground or has it been killed? If it was from when it was still running, have you tried killing them and not restarting to see if it still appears?

I have the same problem. The result is the same in both the example app and my own app.

1. I tried it on Xiaomi Mi5, Samsung Galaxy S7. (Both release and debug mode)
2. No problem with the emulator. (Running after reboot)
3. I can get notifications when the application is killed on all real devices. The problem only occurs when the device is rebooted.
