### ISSUE TITLE
Support for asychronous data

### ISSUE THREAD

**Issue by Jon1105** [MaikuB/flutter_local_notifications#769]
Is it possible to determine the contents of the notification with an asynchronous function at the time that the notification gets displayed. 
This way the user could directly see the asynchronous data he would need inside the notification instead of having to open the app and wait for the asynchronous task to function

For example we could run the function in the background 1 minute before wanting to send the notification and retrieve data from the internet

**Comment by MaikuB** [comment]
No. You should look at approaching this in terms of figuring out how to schedule general computational work to be done. There are native APIs for this and I believe one of the plugins that makes use of it is https://pub.dev/packages/background_fetch. It's not something I've though given the limitations with running Dart code when the app isn't running, you may need to write of all to do background work, fetch data and show notifications all on the native side using Objective-C/Swift on iOS and Kotlin/Java on Android
