### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by rrifafauzikomara** [MaikuB/flutter_local_notifications#772]
I have a case like this. Every 9 PM I want to execute my function (get data from the API) on the background (when the app is closed) or on the foreground (when the app is opened), and when successful it will show the notification. It's possible using this package?

**Comment by MaikuB** [comment]
No as the plugin is meant to be wrapper for the native notification APIs. There are different APIs for doing background work that you may need to look into. A similar issue was raised [here](https://github.com/MaikuB/flutter_local_notifications/issues/769)
