### ISSUE TITLE
Schedule notifications is not wokring 

### ISSUE THREAD

**Issue by srinikande** [MaikuB/flutter_local_notifications#773]
1) Use Schedule notification api
2) give future date time  (minimum after 60 seconds )
3) Build app in release mode.
4) Deploy in android studio emulator 
5) Call Schedule notification api
6) Application getting crashed 
=============

1) Use Schedule notification api
2) give future date time  (minimum after 60 seconds )
3) Build app in release mode.
4) Deploy in android 6 phone 
5) Call Schedule notification api
6) Application getting crashed 

But Same application  is working in  Debug Build & Running from android  studio, 

I have tested with example code also. 

[main.zip](https://github.com/MaikuB/flutter_local_notifications/files/5142912/main.zip)

*

**Comment by srinikande** [comment]
Click on  "Schedule notification to appear in 60 seconds, custom sound, red colour, large icon, red LED" Button

**Comment by MaikuB** [comment]
For security reasons, I won't be downloading an zip file. If you have code then post a link to a repository on GitHub.

When you say you have tested with the example code, what steps did you take to get it running? Did you simply copy and paste the Dart code into your own app (note: it's explicitly written that it should **not** be done [here](https://github.com/MaikuB/flutter_local_notifications/blob/8fe0bd6039a941e10d755a0490a255fe6a53dc58/flutter_local_notifications/example/lib/main.dart#L40)) or what other steps were taken?

Did you make sure to read and follow [this](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#release-build-configuration)?

**Comment by srinikande** [comment]
Its working correctly After implementing your recommendation.  It will be nice if we some kind of error instead of  app crashed such situations.

**Comment by MaikuB** [comment]
This has to do with how Android builds work so not something that can be detected by the plugin. An error would be thrown by the Android side already. This is why it's crucial that you follow everything mentioned in the readme. If you used the bug report template that should be used to report issues like this, you should see that this point is emphasised again
