### ISSUE TITLE
Implications of not adding UNUserNotificationCenter.current().delegate code

### ISSUE THREAD

**Issue by ghenry** [MaikuB/flutter_local_notifications#777]
Hi,

At https://pub.dev/packages/flutter_local_notifications#-ios-setup it states:

```
General setup

Add the following lines to the didFinishLaunchingWithOptions method in the AppDelegate.m/AppDelegate.swift file of your iOS project
```

and I understand that when your app is in the foreground, notifications won't show. Now, when I comment out:

```
if #available(iOS 10.0, *) {
  UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate
}
```

notifications do show when my app is in the foreground, which is actually what I want to happen. My question is, will Apple disallow my app if I do it this way and what else do I lose?

Thanks.

**Comment by MaikuB** [comment]
> and I understand that when your app is in the foreground, notifications won't show. 

Note that as covered that on iOS 10+ that you can use presentations options so an alert/notification could still be displayed. The plugin's default settings is to having the alert shown

> notifications do show when my app is in the foreground, which is actually what I want to happen. My question is, will Apple disallow my app if I do it this way and what else do I lose?

if you're still seeing it then I'm guessing your app has a dependency on another notifications plugin like `firebase_messaging`.  I don't think Apple will reject your app but if you don't add this code in then the plugin's callbacks won't work on iOS

**Comment by MaikuB** [comment]
Should add if you need to see the behaviour of notifications then please download/clone the repo and run the example app. I would guess that you haven't done so as if you did then you should see the notifications even if the app is on the foreground and the device/simulator is on iOS 10 or newer.

**Comment by ghenry** [comment]
Thanks. I'm running the examples, but only on Android, I should have checked iOS properly.

Do you have a swift version of:

https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/example/ios/Runner/AppDelegate.m

Thanks.

**Comment by MaikuB** [comment]
No. There's already the other Swift equivalent around cancelling notifications in the readme. The code structure should be close enough to figure where to copy and paste the snippets in
