### ISSUE TITLE
Changing the app name when sending IOS notification

### ISSUE THREAD

**Issue by CeruleanSource** [MaikuB/flutter_local_notifications#778]
I was wondering how you would go about to change the app name which is displayed on the iOS notification. I've gone through all the steps to manually change the name in the app directory, however it doesn't seem to change the name that's displayed when the iOS notification is sent.

I've tried changing the pubspec.yaml name, the info.plist and none of these changes change the name of the app that is displayed when the iOS notification is sent.

**Comment by ghenry** [comment]
Did you uninstall your app after the changes?

**Comment by CeruleanSource** [comment]
@ghenry thank you this worked. Cannot believe I didn't think of this earlier. 👍

**Comment by ghenry** [comment]
Been there :)
