### ISSUE TITLE
AndroidInitializationSettings can't set color

### ISSUE THREAD

**Issue by yourshinsuke** [MaikuB/flutter_local_notifications#779]
**Describe the bug**
It only png path and it can't set color.

```
      final initializationSettingsAndroid =
          AndroidInitializationSettings('app_icon');
```

**To Reproduce**

1. Use Android
2. push notification (HEAD up notification)
3. watch icon

**Expected behavior**

set color option

**Sample code to reproduce the problem**

**Comment by MaikuB** [comment]
Was never stated that you can set the colour that way for this to fall under a bug. See the example app for how you can set the colour
