### ISSUE TITLE
Scheduling multiple notifications on Android

### ISSUE THREAD

**Issue by icavanaugh95** [MaikuB/flutter_local_notifications#78]
I am not sure if this is an issue with the plugin or my implementation.  I am unable to schedule multiple notifications on Android correctly.  I am using time in milliseconds to create new channels for each scheduled notification however they display at the wrong time.  I scheduled 3 notifications at 1 minute, 3 minute, and 5 minutes.  The last two showed up at the same time but showed up at 5 minutes.

**Comment by icavanaugh95** [comment]
Oh okay.  I'm sorry I missed that part of the readme.

**Comment by MaikuB** [comment]
I'll elaborate a bit more in the readme since it mentions that behaviour for recurring notifications but really applies to all scheduled notifications
