### ISSUE TITLE
Android: When the app is closed or killed, the notification didn't show

### ISSUE THREAD

**Issue by rrifafauzikomara** [MaikuB/flutter_local_notifications#784]
**Describe the bug**
I try 3 flow for this:

1. When the app is open (work)
2. When the app is minimized (work)
3. When the app is closed (not work)

```
Future<void> showNotification(
      FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin) async {
    var androidPlatformChannelSpecifics = AndroidNotificationDetails(
        'your channel id', 'your channel name', 'your channel description',
        importance: Importance.Max, priority: Priority.High, ticker: 'ticker');

    var iOSPlatformChannelSpecifics = IOSNotificationDetails();

    var platformChannelSpecifics = NotificationDetails(
        androidPlatformChannelSpecifics, iOSPlatformChannelSpecifics);
    await Future.delayed(Duration(seconds: 5), () async {
      await flutterLocalNotificationsPlugin.show(
          0, 'plain title', 'plain body', platformChannelSpecifics,
          payload: 'plain notification');
    });
  }
```

I add a delay duration for 5 seconds to kill the apps first to check the notification will show or not, after I kill the app, the notification didn't show. So, this notification didn't support when the app is closed?

This is my full code: https://github.com/rrifafauzikomara/simple_notification

**Comment by MaikuB** [comment]
This is an issue with your code not a bug with the plugin. Nothing will run because you killed the app before Flutter can run code.

There are methods to schedule notifications. Not sure why you didn't use them
