### ISSUE TITLE
Sound Not working allways

### ISSUE THREAD

**Issue by srinikande** [MaikuB/flutter_local_notifications#787]
For Schedule notifications , Sound not working always.

final x = UriAndroidNotificationSound('DEFAULT_NOTIFICATION_URI');

    var androidPlatformChannelSpecifics = AndroidNotificationDetails(
        'uri channel id', 'uri channel name', 'uri channel description',
              sound : x,
        playSound: true,

        styleInformation: DefaultStyleInformation(true, true)
       );
    var iOSPlatformChannelSpecifics =
    IOSNotificationDetails(presentSound: false);
    var platformChannelSpecifics = NotificationDetails(
        androidPlatformChannelSpecifics, iOSPlatformChannelSpecifics);
    await flutterLocalNotificationsPlugin.show(
        0, 'uri sound title', 'uri sound body', platformChannelSpecifics); 

=========================================
Added ringtone2 file to res. 

final x = UriAndroidNotificationSound('DEFAULT_NOTIFICATION_URI');

    var androidPlatformChannelSpecifics = AndroidNotificationDetails(
        'uri channel id', 'uri channel name', 'uri channel description',
        sound:  RawResourceAndroidNotificationSound('ringtone2'),
        playSound: true,

        styleInformation: DefaultStyleInformation(true, true)
       );
    var iOSPlatformChannelSpecifics =
    IOSNotificationDetails(presentSound: false);
    var platformChannelSpecifics = NotificationDetails(
        androidPlatformChannelSpecifics, iOSPlatformChannelSpecifics);
    await flutterLocalNotificationsPlugin.show(
        0, 'uri sound title', 'uri sound body', platformChannelSpecifics);

Am i missing anything ?

**Comment by MaikuB** [comment]
> Added ringtone2 file to res

Do you mean you added the file to the res/raw folder? If so then I'm not sure why you're using the `UriAndroidNotificationSound` class when the I've shown in the example app that it's this class that should be use

https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/RawResourceAndroidNotificationSound-class.html

Please take a closer look at the example app in the repository

**Comment by srinikande** [comment]
I have tested with both ways. It worked me for one time. After that stopped working for me.

**Comment by MaikuB** [comment]
You may need to debug your code to see what might be causing the issue then or see if there's an issue with the sound file you have. 

If you download/clone the entire repository, there's an example app that you can use to see if you can reproduce the problem.
