### ISSUE TITLE
onSelectNotification not called when app is closed

### ISSUE THREAD

**Issue by ydotmalik** [MaikuB/flutter_local_notifications#789]
**Describe the bug**

The onSelectNotification handler is not called when the app closed.

**To Reproduce**

1. Download flutter_local_notifications code at https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications/example
2. Add print statement right above line 65 in https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/example/lib/main.dart, inside onSelectNotification handler
2. Run the code
3. Click on 'Repeat notification every minute' button
4. Close application
5. Wait for notification to appear
6. Tap on notification
7. Observe that print statement added at step 2 not printed

**Expected behavior**

onSelectNotification is called when app is opened

**Sample code to reproduce the problem**
https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications/example with modification mentioned above

**Comment by MaikuB** [comment]
What are you using to try to see if a statement is printed? Are you firing up a debugging session?

**Comment by MaikuB** [comment]
Regardless, of the questions I have above, the approach you've taken is strange. That the notification launches the app and goes to a different screen is proof that it works as that is related to this line https://github.com/MaikuB/flutter_local_notifications/blob/8df0fc4ded9af570efe94fd758a7fe0cc366c700/flutter_local_notifications/example/lib/main.dart#L68. In other words, you could've commented out that line to see that doing so would no longer cause a notification to cause the app to open another screen.

If you're going to close your app then your debug/run session gets killed that you won't further print statements

**Comment by MaikuB** [comment]
Did you download the entire repo and then run the example code from the location without further modifications then? Not seeing any of the issues you've described nor has anyone else in the community reported this given how critical the functionality is. To make sure you're running unmodified code, an alternative would be for you to fork this repo and then clone/download your fork and run the example with no changes

**Comment by MaikuB** [comment]
Also curious to know what version of Flutter you have installed (e.g. run `flutter doctor -v`) and what devices/emulators you've tried this on

**Comment by ydotmalik** [comment]
I downloaded the entire code. I took the example code from my pub-cache directory. It is exactly the same code as in the repo, including all other files and folders.

Other people have reported this issue. For example, #547. In #93 multiple people report this issue.

**Comment by ydotmalik** [comment]
I'm using Bluestacks.

$ flutter doctor -v
[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.20.2 at C:\flutter
    • Framework revision bbfbf1770c (3 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\ydotmalik\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • SM G955F (mobile) • localhost:5555 • android-x86 • Android 7.1.2 (API 25)

• No issues found!

**Comment by ydotmalik** [comment]
I don't observe this behavior on my Android device.

Bluestacks is a well known emulator. It is used for games. From my experience it is identical to a real device. It performs much better (both speed and memory wise) than the emulator that comes with Android Studio.

**Comment by MaikuB** [comment]
> I don't observe this behavior on my Android device.

What device was this and do you mean you still have an issue? If you still have an issue then you may need to consider re-installing the Flutter and Android SDKs, or trying to do a build from a CI/CD service since it looks like an environmental issue. 

If it somehow helps, this is the apk I've built from my own dev machine

[app-release.apk.zip](https://github.com/MaikuB/flutter_local_notifications/files/5177549/app-release.apk.zip)

**Comment by ydotmalik** [comment]
Sorry, I meant it works as expected on my Android device.
