### ISSUE TITLE
Not able to create channel from flutter_local_notification

### ISSUE THREAD

**Issue by snd898** [MaikuB/flutter_local_notifications#790]
Always getting this log when app is running in background:
W/FirebaseMessaging(19129): Notification Channel requested (kwanta_insights) has not been created by the app. Manifest configuration, or default, value will be used.
W/FirebaseMessaging(19129): Missing Default Notification Channel metadata in AndroidManifest. Default value will be used.
E/FirebaseMessaging(19129): Adaptive icons cannot be used in notifications. Ignoring icon id: 2131230720

**Comment by MaikuB** [comment]
Take a closer look at your logs, your issue is to do with firebase messaging not to do this with this plugin

**Comment by snd898** [comment]
Ohk, Thank you. I will correct it. Then I will ask If I get any problem.
