### ISSUE TITLE
Android cannot receive notification after app's process is shutdown.

### ISSUE THREAD

**Issue by lanistor** [MaikuB/flutter_local_notifications#796]
First, thanks for created such an amazing library.

**Describe the bug**

Android cannot receive notification after app's process is shutdown. Different manufactor's devices have different behavior: Google' devices is OK, while HUAWEI, XIAOMI cannot.

**To Reproduce**

1. Setting Scheduled notification while opening app, using `flutterLocalNotificationsPlugin.schedule`.
2. Shutdown the app, all the process in XIAOMI (Also in some HUAWEI' devices) will be shundown, then no notification can be received. But if you let app run background, notifications can be received correctly.

**Comment by MaikuB** [comment]
Please read https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#scheduled-android-notifications as it's not a bug with the plugin
