### ISSUE TITLE
Combination of periodicallyShow and schedule

### ISSUE THREAD

**Issue by gleeo** [MaikuB/flutter_local_notifications#799]
First, thank you for this awesome plugin!

Unfortunately it seems not to be possible to create a periodically repeated notification at weekday from 8:00 am to 16:00 pm, e.g. every hour.

Have you plans to add such a feature?

**Comment by MaikuB** [comment]
Not sure what you mean here. Could you please clarify?

**Comment by gleeo** [comment]
A notification should appear every hour. But only on certain days and times of the day. E.g. the notification should always be created every hour but only from Monday to Friday between 8:00 am and 4:00 pm.

**Comment by MaikuB** [comment]
Got it. No plans for this, it's not supported on older versions of iOS and likely require a fair bit of custom code on Android given everyone will use different combinations. You'll need to look into implementing this yourself provided you're ok with limiting your app to iOS 10 or newer
