### ISSUE TITLE
Periodic notifications not showing

### ISSUE THREAD

**Issue by Afonsocraposo** [MaikuB/flutter_local_notifications#801]
**Describe the bug**
The periodic notifications are not working on my application. I tested `showDailyAtTime`, `periodicallyShow`, and `showWeeklyAtDayAndTime` and they also did not work.
The notifications didn't appear even though they appear on `pendingNotificationRequests`.
I then tested with the [example application](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications/example) and it also didn't work. I tested the above methods (and modified the time or date when needed).
I tested on a Xiaomi Redmi Note 9S.

**To Reproduce**
1. Clone the repo.
2. Run the example application.
3. Press "Repeat notification every minute"
4. Nothing happens.

Thank you for your time!

**Comment by MaikuB** [comment]
Please make sure to read the readme https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#scheduled-android-notifications

**Comment by Afonsocraposo** [comment]
I'm sorry for missing that on the README.
The plugin used to work on this same device, but maybe some OS update made it stop working.
Anyway, thank you for your time!
