### ISSUE TITLE
Add a summary

### ISSUE THREAD

**Issue by Ascenio** [MaikuB/flutter_local_notifications#806]
Currently the `README.md` is a little extensive and there's no index which we can refer to when looking for something specific.

**Comment by MaikuB** [comment]
I assume you mean something like a table of content? I'm not familiar with generating these and this is open-source PRs are welcome, preferably to the `time_zone_macos_support` branch first. Note though, that the solution needs to also work on pub.dev as the readme can also be read there.

**Comment by Ascenio** [comment]
That's right, it's a table of contents. I does work on git and pub.dev. I may make a PR soon. Thanks.
