### ISSUE TITLE
Any changes for iOS 14？

### ISSUE THREAD

**Issue by JackZhang1994** [MaikuB/flutter_local_notifications#807]
How does this plugin fit into IOS 14？

**Comment by MaikuB** [comment]
Not sure what you're trying to ask here as the plugin as part of implementing the plugin uses [these APIs](https://developer.apple.com/documentation/usernotifications/unusernotificationcenter) that are documented as being compatible with iOS 10+

**Comment by MaikuB** [comment]
Also that there's an example app included in the repo so if you clone it, you can run it on your device to check the behaviour
