### ISSUE TITLE
Question: Showing Weekly At Day and Time

### ISSUE THREAD

**Issue by GameSquatch** [MaikuB/flutter_local_notifications#813]
When calling the show weekly at date and time method, when does the first notification fire? Say it's Tuesday at 4pm and I loop through each day of the week and set a show weekly notification for each day at 8am. Will the first of these fire the next day at 8am or will it take an entire week (the following Tuesday at 8am) before the first will fire?

**Comment by MaikuB** [comment]
It's should be whatever is the next instance of what you've scheduled. If I'm understanding what you wrote correctly then it would mean Wednesday 8am. You could write the code and run it to confirm
