### ISSUE TITLE
Cannot run after context is used in onSelectNotification

### ISSUE THREAD

**Issue by Linspirit98** [MaikuB/flutter_local_notifications#814]
Hi I tried using flutter_redux to call API, which requires context in onSelectNotification. However, I tried printing context and it never moves to next step and just stop after context is called. Is there a way to use context in onSelectNotification? 
![image](https://user-images.githubusercontent.com/51519489/94088125-a4a38100-fddd-11ea-8aed-cb9254d06cfc.png)

Thanks.

**Comment by MaikuB** [comment]
You need to figure out how you want to structure your app to get hold of a `BuildContext`. The example app shows one approach using RxDart. This relates more to state management than to do with this plugin so if you need more help I'd suggest you engage with the wider [community](https://flutter.dev/community), which may possibly involve asking those who use/maintain flutter_redux
