### ISSUE TITLE
ava.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference

### ISSUE THREAD

**Issue by Sums-shadow** [MaikuB/flutter_local_notifications#816]
can someone help me with this issues? i've specified icon on initialize but does'nt work.
thanks

**Comment by MaikuB** [comment]
You need to check your code and make sure you've configured everything correctly. Please make sure to go through the readme properly and make use of the example app to cross-reference with what you're doing

**Comment by sanjaymajoka** [comment]
> can someone help me with this issues? i've specified icon on initialize but does'nt work.
> thanks

Facing same issue. Do you have any solution?

**Comment by sanjaymajoka** [comment]
Facing same issue. Is there any solution?

**Comment by designDo** [comment]
> can someone help me with this issues? i've specified icon on initialize but does'nt work.
> thanks

    var dateTime = tz.TZDateTime.now(tz.local).add(Duration(seconds: 5));
    var dateTime = tz.TZDateTime.now(tz.UTC).add(Duration(seconds: 5));
    use tz.UTC solove my problem

**Comment by MaikuB** [comment]
@sanjaymajoka I've already replied about this. 

For anyone running into this issue, please check to see how you've configured your app. If you believe you've come across a bug then file a bug report with a link to a repo that reproduces the bug but please make sure you've cross-referenced what you've done with what's in the readme and the example app first. There's an example app in the repo that you can run after cloning/downloading the repo so do not just copy and paste the Dart code
