### ISSUE TITLE
Android: ShowDailyTime Notification were delayed most of the time.

### ISSUE THREAD

**Issue by skc18** [MaikuB/flutter_local_notifications#817]
**Describe the bug**
The notification that are recurring always show delayed notification on Android devices. My iOS was perfectly normal. Somtimes the notifications appear all on same time even though they are different time set to fire.

**Expected behavior**
Notification should appear when time appear, just like iOS.

Not sure is this still relevant:
https://github.com/MaikuB/flutter_local_notifications/issues/160

**Comment by MaikuB** [comment]
This has been covered in the readme https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#recurring-android-notifications

There is a beta version of the plugin where I've added added new a method that allows for more precise timings by scheduling one notification at a time
