### ISSUE TITLE
Custom sound stops when opening notification panel

### ISSUE THREAD

**Issue by obadajasm** [MaikuB/flutter_local_notifications#818]
Why sound stops when opening notification panel?
I have used the additionaFlags property but it doesn't seem to work and the sound stops anyway.

I have used it as follow :
additionalFlags: Int32List.fromList([16]));

**Comment by MaikuB** [comment]
That's because that's the standard behaviour of a notification. You could write your own native Android code or download one of the various Android notification samples on the web to confirm.

**Comment by MaikuB** [comment]
Also, note that if you wanted the sound to keep going, you've specified the wrong flag. Refer to https://developer.android.com/reference/android/app/Notification#FLAG_INSISTENT and note that the value is 4. There was a code snippet for this specific scenario in the example app as well.

**Comment by hugocbpassos** [comment]
@MaikuB How specifying insistent flag prevents the sound from stopping when the user opens the notification window? That flag only makes the sound repeat.

> That's because that's the standard behaviour of a notification.

As far as I could find out, there is no way to override such behavior. None of the flags do so.

**Comment by MaikuB** [comment]
@hugocbpassos that was just meant to be a general comment in case @obadajasm was trying to do  as they may have wanted it to keep going/repeat but looked at the wrong value given 16 is for auto cancel.
