### ISSUE TITLE
[Question] Is there any way to schedule a notification based on the last time the app was opened ?

### ISSUE THREAD

**Issue by itssidhere** [MaikuB/flutter_local_notifications#819]
I want a custom behaviour that if a user has not opened the app for 1 day. The app sends a notification.
So the best way to do this would be to schedule a new notification after x days when a user opens the application and cancel any scheduled notifications with an id . Can we have a dedicated method for that? Like scheduleIfNotOpened that schedules notification based on user interaction with the app?

**Comment by MaikuB** [comment]
This is something you need to implement on your own as it's specific to your app
