### ISSUE TITLE
Notification dissmiss it self when app open

### ISSUE THREAD

**Issue by darkmehmet** [MaikuB/flutter_local_notifications#821]
Notification works when app closed. But don't work when app is working or in background or opened. When app is opened and it is time to display notification, phone vibrates and shows notification icon for a second then notification disappears.

**Comment by MaikuB** [comment]
What device are you using? Have you gone through the readme to read [this](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#scheduled-android-notifications)?

**Comment by MaikuB** [comment]
Closing since no further information has been provided
