### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by himanshu717171** [MaikuB/flutter_local_notifications#823]
[AlarmScreen.txt](https://github.com/MaikuB/flutter_local_notifications/files/5290563/AlarmScreen.txt)

When notifications comes, we click on notification bar, the sound turns off automatically.
How to resolve this issue??
I do not want that sound turned off when touch on notification bar  

I have attached the file which I have created and implemented the local notification

**Comment by MaikuB** [comment]
This is the default behaviour. This sounds like a possible duplicate of https://github.com/MaikuB/flutter_local_notifications/issues/818. Please read there for more details
