### ISSUE TITLE
Dismiss the notification to close the app? 

### ISSUE THREAD

**Issue by NemanjaCvetkovic1993** [MaikuB/flutter_local_notifications#824]
Hey people, I am trying to close the app when a user dismisses the notification.

Until now, my app is still open when I close the notification..

Did any one of you encounter this problem and how did you resolve it?

A question is for both android and ios apps.

**Comment by MaikuB** [comment]
Dismissing a notification isn't suppose to close the app as a default behaviour to begin with. If you need something like that then you need to look into how to handle this natively and isn't something the plugin is going to provide. I don't believe you force an app to close on iOS to begin with
