### ISSUE TITLE
Notifications not working with android 10

### ISSUE THREAD

**Issue by mahmoudsq** [MaikuB/flutter_local_notifications#825]
Hello 
I get error with android 10 but notification working well with android 9. why?
![d3d5f803-1fb0-4797-8f64-b09c6f977338](https://user-images.githubusercontent.com/22487598/94551251-5a932300-0255-11eb-8fb9-9813d7492b13.jpg)

**Comment by andzejsw** [comment]
I have Android 10, but notifications work. I don't think that this is API level related issue.

**Comment by MaikuB** [comment]
Same or at least I had Android 10 until 11 came out. You've most likely haven't configured your app correctly. Please make sure you go through everything in the readme properly and cross-reference what you're doing with the example app included in the repo.

If you want to file a bug then use the bug report template and fork the repo and update the included example app to demonstrate the issue

**Comment by MaikuB** [comment]
Closing due to lack of response and how others include myself have had this working fine on Android 10.
