### ISSUE TITLE
Add support for android setOnlyAlertOnce

### ISSUE THREAD

**Issue by indijanc** [MaikuB/flutter_local_notifications#83]
Would it be possible to add support for setOnlyAlertOnce on Android? I don't know if there's an equivalent for iOS and if it makes sense to diverge the functionality between Android and iOS.

**Comment by MaikuB** [comment]
Yeah, it could go into the `AndroidNotificationDetails` class

**Comment by MaikuB** [comment]
New release adds support for this now so closing this
