### ISSUE TITLE
v1.5 does not appear to be backward compatible with 1.4

### ISSUE THREAD

**Issue by bryantgtx** [MaikuB/flutter_local_notifications#832]
**Describe the bug**
version 1.5 does not appear to be backward compatible with 1.4.  We have a flutter app that uses Alice, which has a dependency on flutter_local_notifications, and as of the 1.5 release, our CI fails (it rebuilds the environment from scratch).

**To Reproduce**
1. Create an app with a dependency on alice, anything from 0.0.23 to 0.1.5 (current)
2. Build the app in an environment with flutter_local_notifications 1.4.4 installed - everything builds
3. Alice has a dependency on ^1.4.4+4, so 1.5 is a "legal" update to be pulled
4. rebuild dependencies with flutter_local_notifications 1.5, the following errors will be seen:

```
alice-0.0.33/lib/core/alice_core.dart:64:56: Error: Too many positional arguments: 0 allowed, but 2 found.
Try removing the extra positional arguments.
    var initializationSettings = InitializationSettings(
                                                       ^
../../../.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-1.5.0/lib/src/initialization_settings.dart:7:9: Context: Found this candidate, but the arguments don't match.
  const InitializationSettings({
        ^^^^^^^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dartlang.org/alice-0.0.33/lib/core/alice_core.dart:169:32: Error: Getter not found: 'Default'.
        importance: Importance.Default,
                               ^^^^^^^
../../../.pub-cache/hosted/pub.dartlang.org/alice-0.0.33/lib/core/alice_core.dart:170:28: Error: Getter not found: 'Default'.
        priority: Priority.Default);
                           ^^^^^^^
../../../.pub-cache/hosted/pub.dartlang.org/alice-0.0.33/lib/core/alice_core.dart:172:59: Error: Too many positional arguments: 0 allowed, but 2 found.
Try removing the extra positional arguments.
    var platformChannelSpecifics = new NotificationDetails(
                                                          ^
../../../.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-1.5.0/lib/src/notification_details.dart:7:9: Context: Found this candidate, but the arguments don't match.
  const NotificationDetails({
        ^^^^^^^^^^^^^^^^^^^
```

**Expected behavior**
I would not expect a minor version change to break the API.  It's entirely possible that Alice is doing something that it should not, in which case this is really a defect on Alice.

**Sample code to reproduce the problem**
Did a "flutter create" and added Alice to the app (dependency and one line in main.dart)
https://github.com/bryantgtx/flutter_local_notifications_repro/tree/master/fln15
download and run "flutter test"
If you add an explicit dependency on flutter_local_notifications: 1.4.4.+4, flutter test will work.

**Comment by MaikuB** [comment]
Apologies, looks like I bumped the wrong number. I'll need to bump to 2.0 but this isn't something that can be retroactively done to 1.5 so you may need to do a dependency override in your app to fix this

**Comment by MaikuB** [comment]
I'll be publishing a 1.5.0+1 that will revert the changes so that I believe that should fix the issue since caret versioning should pull it down. This is how I've seen Google fix wrong versions being incremented in the past

**Comment by MaikuB** [comment]
This is published now. Let me know how it goes.

I'm surprised no one else has brought this up before as I had done a similar thing in the past having misunderstood the caret syntax etc. I'm guessing the package authors were just content to update their pubspec files so thanks for bringing this to my attention

**Comment by bryantgtx** [comment]
Thanks!  I have had to go re-read the docs several times over the years, because my brain reverts to "increment the lowest part of the version number", too.  I'd love to have a way to limit it to micro version numbers only, or better, lowest part of the version specified.

**Comment by MaikuB** [comment]
Since you haven't said anything else, I assume the problem has been fixed so will close this. Feel free to re-open if that isn't the case
