### ISSUE TITLE
Request notification settings for android

### ISSUE THREAD

**Issue by awnigharbia** [MaikuB/flutter_local_notifications#833]
Hey all, I wanna control the notification settings like sound, badges, etc.. I've tried to config my Android channel like this :
```js
 var androidPlatformChannelSpecifics = AndroidNotificationDetails(
      'your channel id',
      'your channel name',
      'your channel description',
      importance: Importance.Max,
      priority: Priority.High,
      ticker: 'ticker',
      channelShowBadge: true,
      playSound: true,
      enableVibration: true,
      visibility: NotificationVisibility.Public,
    );
```
I'm using Xiaomi mobile (MIUI 11.0) when I open the notification settings for my app and enable badges and sound it works well! but when the app is installed it's not auto granted. How can I get it enabled? anything is missing with this cool library ? or should I write a specific native code! if so, Where to start?

**Comment by MaikuB** [comment]
Your issue probably related to Xiaomi's implementation of the Android OS. You can look on pub.dev to see if there are existing plugins to open the settings or write your own native code to do so
