### ISSUE TITLE
Change in flutterLocalNotificationsPlugin.zonedSchedule parameter

### ISSUE THREAD

**Issue by MattheusOliveira** [MaikuB/flutter_local_notifications#834]
[Breaking change]

In `flutterLocalNotificationsPlugin.schedule (....)`, I was passing a scheduleDate parameter of type DateTime to Function Schedule. With the update to `flutterLocalNotificationsPlugin.zonedSchedule (....)`, the scheduleDate parameter of type TZDateTime is requested. How do I convert from DateTime to TZDateTime just passing the DateTime value as I was doing before?

I tried using TZDateTime.from (DateTime datetime, Location location). I don't have the location parameter in my business rule. Would you help me out of this?

old :

`await flutterLocalNotificationsPlugin.schedule(`
        `model.doseScheduleId,`
        `model.medicineName,`
        `body,`
        `model.triggerOn, //DateTime`
        `platformChannelSpecifics,`
        `payload: model.toJson(),`
        `androidAllowWhileIdle: true,`
);`

Where model.triggerOn is not UTC

new :

`await flutterLocalNotificationsPlugin.zonedSchedule(`
        `model.doseScheduleId,`
        `model.medicineName,`
        `body,`
        `tz.TZDateTime.from(model.triggerOn, ?????), //TZDateTime`
        `platformChannelSpecifics,`
        `payload: model.toJson(),`
        `androidAllowWhileIdle: true,`
);`

I am using TZDateTime.from (another DateTime, Location location) because this function allows you to pass a DateTime parameter.

**Comment by MaikuB** [comment]
You need to write your own native code to get the location (the example app does this) or use a plugin e.g. flutter_native_timezone. The readme for the `timezone` package covers how to construct dates https://pub.dev/packages/timezone#timezone-aware-datetime, which would also tell `TZDateTime.from(...)` is actually for converting between timezones

**Comment by tnaseem** [comment]
Just a heads up: I've just upgraded to 2.0.0, and using flutter_native_timezone works fine. Just replace _getLocatalTimeZone() from the example to:
```
  // Retrieve the phone's current time zone.
  Future<void> _getLocalTimeZone() async {
    tz.initializeTimeZones();
    final String timeZoneName = await FlutterNativeTimezone.getLocalTimezone();
    tz.setLocalLocation(tz.getLocation(timeZoneName));
  }
```

I'm wondering though, @MaikuB , is it worth adding that plugin as a dependency, like you've done with the other timezone package? (or, just incorporate the code into your notifications package, perhaps?).

**Comment by MaikuB** [comment]
The plugin uses the `timezone` package so that's why it depends it. `flutter_native_timezone` isn't used at all. Adding it as a dependency would mean this plugin may need to wait for add it support other platforms. It doesn't look like the author isn't trying to keep it updated as well. I submitted a PR to it a while back that they never published. It doesn't support macOS like this plugin does as well.

**Comment by MattheusOliveira** [comment]
@MaikuB I just insert this code snippet after updating the plugin. It's working, but I'm still running tests. I am retrieving a static location, as in `tz.getLocation ('America / Sao_Paulo')`. How can I replace this with something dynamic, that is, through the location of the device. Is there an example of this in the plugin? Could you please indicate me? Thank you!

```
if (canSchedule) {
      tz.initializeTimeZones();
      await flutterLocalNotificationsPlugin.zonedSchedule(
        model.doseScheduleId,
        model.medicineName,
        body,
        tz.TZDateTime.from(model.triggerOn, tz.getLocation('America/Sao_Paulo')),         
        platformChannelSpecifics,
        payload: model.toJson(),
        androidAllowWhileIdle: true,
        uiLocalNotificationDateInterpretation:
            UILocalNotificationDateInterpretation.absoluteTime,
      );
}
```

**Comment by tnaseem** [comment]
You can use the [flutter_native_timezone](https://pub.dev/packages/flutter_native_timezone) package, or write your own, which is what I've done now. The latter is easier, of course:

Then it's just a case of calling:
```
    final String timezoneName = await FlutterNativeTimezone.getLocalTimezone();
    tz.setLocalLocation(tz.getLocation(timezoneName));
```

**Comment by MaikuB** [comment]
@MattheusOliveira see @tnaseem's response. I already mentioned that the example app has it own code so you can refer to that if you want. Closing as original question has been answered.
