### ISSUE TITLE
Notification doesn't create on a created channel 

### ISSUE THREAD

**Issue by sunyeang** [MaikuB/flutter_local_notifications#837]
Been trying to manage the notification with created channel, however notification is always create on Miscellaneous channel.

**Comment by MaikuB** [comment]
Not sure what you mean by miscellaneous channel. I've yet to hear anyone else having this issue or come across with the example app so I would suspect there's an issue with what you're doing but you haven't provided much details to go on. Note that the details of a channel cannot be changed once created so if you keep trying to use the same channel id then perhaps that's your issue

**Comment by sunyeang** [comment]
Here is the case.

I create a notification as the code below. Based on my understanding, the notification should create a channel name 'Chats'. However when I run the code, it create a channel name 'Miscellaneous' instead.

`  Future<void> notification(String title, String body, int id) async {
    AndroidNotificationDetails androidNotificationDetails =
        AndroidNotificationDetails(
            'CHAT_MESSAGES', 'Chats', 'Chat notifications',
            ticker: 'ticker',
            priority: Priority.high,
            importance: Importance.max,
            visibility: NotificationVisibility.public);

    IOSNotificationDetails iosNotificationDetails = IOSNotificationDetails();

    NotificationDetails notificationDetails = NotificationDetails(
      android: androidNotificationDetails,
      iOS: iosNotificationDetails,
    );

    await flutterLocalNotificationsPlugin
        .show(id, title, body, notificationDetails, payload: "aa");
  }`

![Screenshot_20201006-224506_Settings](https://user-images.githubusercontent.com/59597075/95198433-f8bf5400-0826-11eb-80e2-2efbee9a085d.jpg)

**Comment by MaikuB** [comment]
1. Please give more details of the Android device you've run the code on
2. What happens when you clone the repo and run the example app on that device?

**Comment by hawkeye-sama** [comment]
@sunyeang how were you able to resolve this issue?

**Comment by mhlim8157** [comment]
I'm using flutter_local_notification version 19.1.0, and even after executing createNotificationChannel() and declaring the channel id and channel name in AndroidManifest.xml, then building the app and sending push messages, a 'Miscellaneous' channel is automatically created.

Is the solution mentioned in the StackOverflow post ['How to avoid Miscellaneous channel category in android FCM Flutter?'](https://stackoverflow.com/questions/77741635/how-to-avoid-miscellaneous-channel-category-in-android-fcm-flutter) the only way to fix this issue?
