### ISSUE TITLE
If you reboot your phone, the notification appears again.

### ISSUE THREAD

**Issue by minikupa** [MaikuB/flutter_local_notifications#840]
``` 
await flutterLocalNotificationsPlugin.zonedSchedule(
          0,
          'lunch',
          'menu',
          tz.TZDateTime.local(
              dateTime.year, dateTime.month, int.parse(lunch.date), 8, 0),
          NotificationDetails(
              android: AndroidNotificationDetails('gayagok', 'lunch', 'lunch')),
          androidAllowWhileIdle: true,
          uiLocalNotificationDateInterpretation:
              UILocalNotificationDateInterpretation.absoluteTime);
    });
```
The notification appears, but the notification appears even after the reboot.
ex. The notification appears at eight o'clock. If you reboot your phone, the notification appears again.

I am not good at English. sorry

**Comment by MaikuB** [comment]
I can't reproduce this so potentially and haven't heard anyone else report this. Are you sure it's not something wrong with the app you have? If you believe there's an issue with the plugin then provide a link to a GitHub repo with minimal, sample app that can reproduce the problem

**Comment by burhanaksendir** [comment]
Hello @minikupa ,
I'm experiencing the same issue. Have you found a solution for this? I'd appreciate it if you could share.
