### ISSUE TITLE
2.0.0 not working on Xiaomi when app is closed 

### ISSUE THREAD

**Issue by MiroLiebschner** [MaikuB/flutter_local_notifications#843]
Problem: Notification not working when App closed on Xiaomi phone. 

    await flutterLocalNotificationsPlugin.zonedSchedule(
        id,
        headerText,
        reminderText,
        _timePickerForWeeklyReminder(weekday, hours, minutes),
        const NotificationDetails(
          android: AndroidNotificationDetails(
            'daily notification channel id',
            'daily notification channel name',
            'daily notification description&apos',
          ),
        ),
        androidAllowWhileIdle: true,
        uiLocalNotificationDateInterpretation:
            UILocalNotificationDateInterpretation.absoluteTime,
        scheduledNotificationRepeatFrequency:
            ScheduledNotificationRepeatFrequency.weekly);
    print("Weekly Notification was created");
  

This is working fine on OnePlus with Android 9 (App open, closed and in background).
On a Xiaomi RedMiNote7 with Android 10 it is working when the app is open/ in background but not when the app is closed. 

The old method we used (which is deprecated now) worked when the app was closed, so it should not be depending (alone) on the mobile phone settings. 
We already tried: 
`importance: Importance.max,        
priority: Priority.high,`. 

Edit: Formating

**Comment by MaikuB** [comment]
I can't do anything about device-specific issues as some device manufacturers prevent background execution. Xiaomi is one of them so I'm skeptical that it had worked for you before when a lot of others have mentioned on this repo that it doesn't work. It also doesn't make sense that you're seeing different behaviour as the new method calls the exact same Android APIs the old method did to schedule the notification. This is something you can verify given the plugin is open-source.

I'm told some devices (not sure if it includes Xiaomi) allow removing the battery saving restrictions that would allow apps run work even when it's been closed. Is this something you did last time but perhaps forgot to do this time around?

**Comment by MiroLiebschner** [comment]
"I'm told some devices (not sure if it includes Xiaomi) allow removing the battery saving restrictions that would allow apps run work even when it's been closed. Is this something you did last time but perhaps forgot to do this time around?" 
This could be the reason or my memory is wrong. 

Anyway thank you! Issue is closed then.
