### ISSUE TITLE
Trouble using updated Weekly schedule notification

### ISSUE THREAD

**Issue by reshuashish** [MaikuB/flutter_local_notifications#851]
I was using showWeeklyAtDayAndTime but after the update can't understand how to use it using date and time.
I need to schedule notification for specific time on particular weekdays....for example: Monday-10am,5pm;Thursday-3pm,4pm,7pm etc.
I don't have dates for notification schedule, I only got the Days ie. Monday,tues...and time
and once set I need it to repeat every week. It was easy before but now I can't understand how to do it please guide me 
and I think this new method need more documentation.
I know it's not a bug .......

**Comment by MaikuB** [comment]
> I don't have dates for notification schedule, I only got the Days ie. Monday,tues...and time
and once set I need it to repeat every week.

Even if you don't have dates, logically what you can do is schedule it at the next instance of a particularly. If check the example, you should see the code has been updated to demonstrate this. I'll leave a note in the readme about this

**Comment by reshuashish** [comment]
> Even if you don't have dates, logically what you can do is schedule it at the next instance of a particularly. 
What particularly???

**Comment by MaikuB** [comment]
I edited my response as I realised after I wrote it that I forgot to add some words there. Regardless, my point is you can refer to the example app

**Comment by MaikuB** [comment]
Hmm sorry looks like,the example for days isn't there but I've explained the logic to follow

**Comment by reshuashish** [comment]
Thank you for explaining and please update the example asap. 🙏🏽

**Comment by MaikuB** [comment]
The date/time classes should tell you the day of the week that could help you make the calculations (https://api.flutter.dev/flutter/dart-core/DateTime/weekday.html). PRs are welcome if you can assist with adding the example
