### ISSUE TITLE
About 1.5 version changes - was it really necessary?

### ISSUE THREAD

**Issue by chris-rutkowski** [MaikuB/flutter_local_notifications#853]
Hello,
plugins should make things as simple as possible, but with that update, actually, it made it very complicated.
DateTime object can be converted to UTC and later to ISO string. We can send that ISO string to both platforms and they will convert it to their local date object.

Have you explored other possibilities before switching to that "awkward" TZDateTime, which needs to be initialised and additional tasks?

I haven't had any problems with your plugin before. Both iOS and Android notifications were scheduled with the appropriate time. Maybe I haven't pushed it to the limits, maybe I haven't encountered the issues that you have encountered. However with the current version, surprisingly the iOS notifications are scheduled correctly, but Android's do not.

**Comment by MaikuB** [comment]
Yes it was necessary. Your example assumes the user stays within the same location so sounds like either your users never change their location or perhaps they haven't reported an issue. Dart's `DateTime` implementation is only considers local and UTC time, it doesn't know about the timezone/location that is necessary to deal with daylight savings (e.g. see https://api.flutter.dev/flutter/dart-core/DateTime/toIso8601String.html). Dealing with daylight savings has been a longstanding issue (https://github.com/MaikuB/flutter_local_notifications/issues/118) and there were issues on iOS if the user changed location #179). 

If you look at how the native IOS APIs work,  it looks at the IANA timezone of the date. Android also has a [ZonedDateTime](https://developer.android.com/reference/java/time/ZonedDateTime) class. From the purpose of what a plugin should do, these changes are exposing what a native iOS/Android developer would do to schedule a notification that respects daylight savings etc.

Also the changes in 2.0 (which I mistakenly labelled as 1.5) was in beta for many months for feedback/testing. If you an issue with notifications not firing correctly then please provide a minimal app to reproduce the problem. A link to a repo or fork of this repo with an updated example app would be best. If you're not aware of it, there's an example included in the repo already and is what I've been using for testing.

**Comment by chris-rutkowski** [comment]
Thank you for your answer, how about keeping both interfaces - one that simply continues to use DateTime, to schedule notifications in the local timezone, and the new one, for finer control?

**Comment by MaikuB** [comment]
I don't see how your proposal would solve any of the problems I've raised. Using DateTime was what led to issues to begin with and I've already gone through the issues around it. The idea of a local timezone could change as the user goes somewhere else. If you have an idea for this then look at submitting a PR

**Comment by MaikuB** [comment]
Closing due to lack of response. If you have ideas on how to make an API using `DateTime` won't suffer the same issues then feel free to submit a PR. If this is about how the old method worked was sufficient for your scenario then you can maintain a fork or make customisations to your app to make use of platform channels

**Comment by srsudar** [comment]
I'm also somewhat confused about the API changes. It looks like `schedule` and `showDailyAtTime` are both replaced by `zonedSchedule`, is that right?

If so, I have a clarification question about "The idea of a local timezone could change as the user goes somewhere else."

Let's say I run this example code from the docs, but with `hours: 2`.

```
await flutterLocalNotificationsPlugin.zonedSchedule(
    0,
    'scheduled title',
    'scheduled body',
    tz.TZDateTime.now(tz.local).add(const Duration(hours: 2)),
    const NotificationDetails(
        android: AndroidNotificationDetails('your channel id',
            'your channel name', 'your channel description')),
    androidAllowWhileIdle: true,
    uiLocalNotificationDateInterpretation:
        UILocalNotificationDateInterpretation.absoluteTime);
```

Does the change from `schedule` to `zonedSchedule` mean that it will always fire two hours in the future (if we started a stop watch, it would trigger in two hours), but that before it might fire in less or more time if a user changed time zones? In other words, the plugin used to only consider local wall-clock time, and now it is smarter?

Is the same thing true if I try to replicate the old `showDailyAtTime` behavior? Say I schedule something for 8am in Seattle, and then I fly to Rome. Does the new `zonedSchedule` automatically mean that my notifications will fire at 8am in the time zone where my phone is currently located?

**Comment by srsudar** [comment]
Is there a reason something like [this](https://github.com/srsudar/flutter_local_notifications/commit/80be281334f3c49c11b4c644bb488b076291f3a5) wouldn't work? Note that that probably doesn't even build--I had some trouble getting Intellij to work with the project. I also didn't bother optimizing anything and it would have to be cleaned up. It is just a demo.

What I'm trying to do there is keep `schedule()` (and eventually `scheduleDailyAtTime()`), while still fixing the time zone problem by handling time zone complexities for the caller. It seems like those methods could just migrate to calling `zonedSchedule` under the hood.

It seems like that might work...what am I missing?
