### ISSUE TITLE
Get block when app launch

### ISSUE THREAD

**Issue by KhazanGu** [MaikuB/flutter_local_notifications#855]
**Describe the bug**

Get block when app launch Both on iOS and Android.

**To Reproduce**
1. run flutter clean
2. run flutter build
3. Get block when app launch

**Expected behavior**

Get block when app launch

**Sample code to reproduce the problem**

```
FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
    FlutterLocalNotificationsPlugin();

void main() async {

const AndroidInitializationSettings initializationSettingsAndroid =
    AndroidInitializationSettings('app_icon');
final IOSInitializationSettings initializationSettingsIOS =
    IOSInitializationSettings(
        onDidReceiveLocalNotification: onDidReceiveLocalNotification);
final MacOSInitializationSettings initializationSettingsMacOS =
    MacOSInitializationSettings();
final InitializationSettings initializationSettings = InitializationSettings(
    android: initializationSettingsAndroid,
    iOS: initializationSettingsIOS,
    macOS: initializationSettingsMacOS);
await flutterLocalNotificationsPlugin.initialize(initializationSettings,
    onSelectNotification: selectNotification);

  runApp(MyApp());
}
```

**Comment by MaikuB** [comment]
Haven't seen this block on Android, are you sure you got this right? On iOS this is expected and is a bug with your code not a bug with the plugin. In fact you even wrote it is the expected behaviour. If you run the example app then you should see that it isn't blocked by the permissions prompt. Notes about the permissions prompt and ways to handle it were covered in the readme. Please make sure you go over the readme and code in the example app

**Comment by KhazanGu** [comment]
Thanks for your reply. I downloaded the sample codes and ran succeeded on my phone.
But It gets block when the app launch after I created a new flutter project and updated my project step by step reference the README.md file. 
It's very difficult to find out where has a problem. Could you give me some suggestions, please? Thanks a lot. @MaikuB

**Comment by MaikuB** [comment]
If you had gone though the readme then you should've seen that this was covered in the last paragraph of [this section](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#initialisation)

> On iOS and macOS, initialisation may show a prompt to requires users to give the application permission to display notifications (note: permissions don't need to be requested on Android). Depending on when this happens, this may not be the ideal user experience for your application. If so, please refer to the next section on how to work around this.

Please go through it again and make use of the example app to make the necessary adjustments for your own app
