### ISSUE TITLE
Custom system notification sounds

### ISSUE THREAD

**Issue by ebelevics** [MaikuB/flutter_local_notifications#856]
I have tried to find any solution for a while to add custom platform system sound for notification. For iOS it would be http://iphonedevwiki.net/index.php/AudioServices sound list and for Android, if I'm not wrong, then you get from RingtoneManager. And if user doesn't find his preferred system sound, he can choose from file manager app.
I have tried integrating flutter_ringtone_player package, but only thing it does is playing system sounds, not setting sound on notifications.

**Comment by ebelevics** [comment]
Alright I just found in Android case that it should be possible to set Android sound via UriAndroidNotificationSound and RingtoneManager. Still when I tried to insert "media/internal/audio/media/388?title=Acorn&canonical=1" for example as parameter in UriAndroidNotificationSound field, device kept playing same default sound.
IOS case is still unresolved.

**Comment by MaikuB** [comment]
I don't believe what you're after is supported on iOS to begin. You should be doing research to see what the notification APIs support first as opposed to starting with how to get access to the system sounds. If you look at the docs for iOS, the custom sounds that can be played are those that are bundled with the app https://developer.apple.com/documentation/usernotifications/unnotificationsound

**Comment by mustakimpawle** [comment]
@ebelevics do you able to implement it in android?
