### ISSUE TITLE
ScheduleNotification to fix

### ISSUE THREAD

**Issue by Filpin011** [MaikuB/flutter_local_notifications#857]
Hi, I'm looking to make a scheduled notification, but I can only schedule in the moment I start the schedule with various frequency, now I would like to understand if there is a way to set a date of the starting repeated notification, if yes, how, or if there is a way to semi-modify ur code for do this, tnx

**Comment by MaikuB** [comment]
If you look at https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#scheduling-a-notification, the plugin already supports setting the date for a repeatable notification. Are you perhaps looking at the methods that were deprecated in 2.0?

**Comment by reovo** [comment]
Let say our current time is: 2020-10-18 14:00 and our operating system is:  iOS
If we try to schedule notification with:
`ScheduledNotificationRepeatFrequency.daily` and `scheduledDate` set to  2020-10-19 15:00 (next day). 
Then you still receive notification at closest 15:00. ( 2020-10-18 15:00 )

**Comment by MaikuB** [comment]
Hmm yes, looks like there is an issue there for iOS/macOS but not for Android. Though I had tested this but perhaps it was missed. I suspect this also means no one in the community had helped to test whilst the changes were in beta either :(

Having taken another look at this, it looks like this sadly isn't possible for iOS at all so I may need to change the `zonedSchedule` API (which may be a breaking change with how the parameters are exposed) and reconsider how the ability to do daily and weekly notifications are exposed. Apologies for the inconvenience

**Comment by Filpin011** [comment]
tnt

**Comment by Filpin011** [comment]
> Let say our current time is: 2020-10-18 14:00 and our operating system is: iOS
> If we try to schedule notification with:
> `ScheduledNotificationRepeatFrequency.daily` and `scheduledDate` set to 2020-10-19 15:00 (next day).
> Then you still receive notification at closest 15:00. ( 2020-10-18 15:00 )

this is my same issue, and I didn't understand why this was happens, tnx very much for explain what i was looking for say.
there is any possibility to add something like: schedule for every week at Monday, or from Monday to Friday every week? I look that awesome notification can do something like this

**Comment by MaikuB** [comment]
You need to specify a date that matches the same day of the week that you're after. I have a PR to make all platforms behave consistently by matching on the specified date/time components and the parameter is named to better indicate this. This is a breaking change in terms of the API signature. I'll give it a bit of time to test before merging it in though it uses similar mechanisms to what I had implemented before so don't think there'll be issues. If you would like to give it a spin and/or can help test it, then you can reference the branch of code by specifying a [Git dependency](https://dart.dev/tools/pub/dependencies#git-packages) in your pubspec.yaml file

**Comment by Filpin011** [comment]
ok, I saw the changes, but I this it's missing the possibility to make daily notification at a specific hour, like from now at 17:00 to Friday at 17:00, idk if u understand what I mean

**Comment by MaikuB** [comment]
It is there that's what the `DateComponents.Time` enum value is for.

**Comment by Filpin011** [comment]
ok tnt

**Comment by MaikuB** [comment]
released 3.0.0 with the changes in the PR
