### ISSUE TITLE
Default Icon Notification Doesn't Show on Release Mode 

### ISSUE THREAD

**Issue by irufano** [MaikuB/flutter_local_notifications#863]
Step to reproduce :
1.  I've setting default icon with :
```
AndroidInitializationSettings('app_launcher'). 
```

2.  My 'app_launcher' asset I've placed in drawable.

3.  On debug mode icon show perfectly.
4.  But on release mode the default icon doesn't appear only show blank rectangle.

**Comment by MaikuB** [comment]
Please make sure you go through everything in the readme https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#release-build-configuration
