### ISSUE TITLE
change route in fullscreen background msg

### ISSUE THREAD

**Issue by prozaklob** [MaikuB/flutter_local_notifications#864]
hi!
i create fullscreen function with FCM background msg.

when i receive a notification, the home page is brought to the front where this function is declared ( in example go to SecondScreen ).

How to force a switch to another page (homepage2) when triggered?

Future<dynamic> myBackgroundMessageHandler(Map<String, dynamic> message) async {
  // print("myBackgroundMessageHandler message: $message");
  int msgId = int.tryParse(message["data"]["msgId"].toString()) ?? 0;
  // print("msgId $msgId");
  _showFullScreenNotification();
}

```
Future<void> _showFullScreenNotification() async {
  const AndroidNotificationDetails androidPlatformChannelSpecifics =
      AndroidNotificationDetails('your other channel id',
          'your other channel name', 'your other channel description',
          sound: RawResourceAndroidNotificationSound('slow_spring_board'),
          priority: Priority.high,
          importance: Importance.high,
          fullScreenIntent: true);
  const IOSNotificationDetails iOSPlatformChannelSpecifics =
      IOSNotificationDetails(sound: 'slow_spring_board.aiff');
  const MacOSNotificationDetails macOSPlatformChannelSpecifics =
      MacOSNotificationDetails(sound: 'slow_spring_board.aiff');
  const NotificationDetails platformChannelSpecifics = NotificationDetails(
      android: androidPlatformChannelSpecifics,
      iOS: iOSPlatformChannelSpecifics,
      macOS: macOSPlatformChannelSpecifics);
  await flutterLocalNotificationsPlugin.show(
      0,
      'custom sound notification title',
      'custom sound notification body',
      platformChannelSpecifics);
}
```

**Comment by MaikuB** [comment]
If you play around with the example app then you should see that a full-screen intent notification triggers the `onSelectNotification` callback that is then used to display another page.

**Comment by prozaklob** [comment]
> If you play around with the example app then you should see that a full-screen intent notification triggers the `onSelectNotification` callback that is then used to display another page i.e. it's treated the same way as if the user has tapped on the notification

big thx. ;)
