### ISSUE TITLE
How to get payload when notification appear whether normal or scheduled.

### ISSUE THREAD

**Issue by MobileAppDevKtn** [MaikuB/flutter_local_notifications#868]
@MaikuB 

I have seen all issues then I'm adding this one.

Issue: I wanted to add data in the firestore when notification being appeared. As of now what I've seen is you'll get payload when 
notification clicked but I wanted to get payload when the notification appears.

**Comment by MaikuB** [comment]
If you have look at the issues then hopefully you should've seen that this has been asked before in https://github.com/MaikuB/flutter_local_notifications/issues/21 and isn't supported. Given how background execution is still an issue for Flutter, if you only need to handle this in the foreground (sounds that way) then I'd suggest making the changes yourself and I'd happy to look at a PR as maintaining this plugin is done purely in my spare time.

**Comment by MobileAppDevKtn** [comment]
OK, @MaikuB Thanks I guess I missed this one. Thanks for the reply.
