### ISSUE TITLE
I want to execute the code in the onSelectNotification function while in the app

### ISSUE THREAD

**Issue by definev** [MaikuB/flutter_local_notifications#872]
I want to execute the code in the onSelectNotification function while in the app? How can i achieve this, the firebase messenging working like this and i want to do that.

**Comment by MaikuB** [comment]
If you download the repo and run the example app then you should find that it already does this. If it's not happening in your app then there's an issue in your app that you need to fix

**Comment by definev** [comment]
Ok i will check that

**Comment by definev** [comment]
`
await flutterLocalNotificationsPlugin.initialize(initializationSettings,
      onSelectNotification: (String payload) async {
    if (payload != null) {
      debugPrint('notification payload: $payload');
      print("Active Code!");
    }
    selectNotificationSubject.add(payload);
  });
`
i don't see "Active Code!" in console. When notification fire, i'm not mean when i tap to notification tile, i want it excute when it notif.

**Comment by MaikuB** [comment]
This was just asked recently (https://github.com/MaikuB/flutter_local_notifications/issues/868) and isn't supported
