### ISSUE TITLE
Add api to get app current showing notifications

### ISSUE THREAD

**Issue by HrX03** [MaikuB/flutter_local_notifications#873]
We could detect if a notification is already showing and avoid showing it again or dismiss it based on needs.

**Comment by MaikuB** [comment]
Have you come across [this API](https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/AndroidFlutterLocalNotificationsPlugin/getActiveNotifications.html)? It was covered in the example app and the ability to get active notifications on Android was mentioned in the readme

**Comment by HrX03** [comment]
Oh yeah it seems like i missed it. That method 8s just what I needed, thanks
