### ISSUE TITLE
Custom Sound notification is working in simulator but silent in mobile device

### ISSUE THREAD

**Issue by DevDaring** [MaikuB/flutter_local_notifications#878]
I have used custom sound notification in simulator it is working good .
In mobile the notification is coming but not the sound.How I can debug the issue.Any idea?
On the contrary default sound is working.
Here is the code(taken from example)

> Future<void> _showNotificationCustomSound() async {
    const AndroidNotificationDetails androidPlatformChannelSpecifics =
        AndroidNotificationDetails(
      'your other channel id',
      'your other channel name',
      'your other channel description',
      sound: RawResourceAndroidNotificationSound('slow_spring_board'),
    );
    const IOSNotificationDetails iOSPlatformChannelSpecifics =
        IOSNotificationDetails(sound: 'slow_spring_board.aiff');
    const MacOSNotificationDetails macOSPlatformChannelSpecifics =
        MacOSNotificationDetails(sound: 'slow_spring_board.aiff');
    const NotificationDetails platformChannelSpecifics = NotificationDetails(
        android: androidPlatformChannelSpecifics,
        iOS: iOSPlatformChannelSpecifics,
        macOS: macOSPlatformChannelSpecifics);
    await flutterLocalNotificationsPlugin.show(
        0,
        'custom sound notification title',
        'custom sound notification body',
        platformChannelSpecifics);
  }

**Comment by MaikuB** [comment]
If you are running on debug mode for mobile the emulator and device and still have an issue then you need to check the settings of your phone. If you're using a release build on Android then you've most likely haven't done all of the steps around [release build configuration](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#release-build-configuration)
