### ISSUE TITLE
Explicitly list unsupported platforms

### ISSUE THREAD

**Issue by Luckey-Elijah** [MaikuB/flutter_local_notifications#879]
I understand _Flutter Web_ is not supported. 

Could _Flutter Web_ and other unsupported platforms (I think _Windows_ and _Linux_ are the only two left that aren't supported) be explicitly listed in the `README.md`?

**Comment by MaikuB** [comment]
What is the issue with what's mentioned in the readme at moment?

**Comment by Luckey-Elijah** [comment]
There's nothing inherently wrong. The document is solid. I think it would a bit helpful to explicitly note that the package isn't available for Flutter for Web (or other platforms). Just a suggestion! 😀

**Comment by MaikuB** [comment]
Noted though I'm not looking to change this as if anything, I'd say it could add confusion. The plugin already has a [section](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#-supported-platforms) that lists the platforms it does support (so does the description of the repository too) so anything not listed there isn't supported. Given the section itself is titled "Supported platforms", adding it seems counterintuitive and leaves some potential for those who skim to think it is supported
