### ISSUE TITLE
flutter_local_notifications crashes if it's from apk. It works fine in debug mode.

### ISSUE THREAD

**Issue by suztomo** [MaikuB/flutter_local_notifications#882]
My app and flutter_local_notifications work fine when it's in the debug mode (via Android Studio). But when I create apk (`flutter build apk --split-per-abi`) and installs it to my android phone it fails at scheduling notification. Why?

**Comment by suztomo** [comment]
It turned out that I had to add `android/app/proguard-rules.pro` as instructed in https://pub.dev/packages/flutter_local_notifications#release-build-configuration .

I copy-pasted the content of https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/example/android/app/proguard-rules.pro and my app works fine.

**Comment by DanMossa** [comment]
Copy and pasting that did not work for me.

I had to also add

`-keep class com.google.gson.examples.android.model.** { <fields>; }`

**Comment by LAUBENicolas** [comment]
Thank you @DanMossa, this line was missing in my `_proguards-rules.pro_` too
