### ISSUE TITLE
initialize future doesn't complete on iOS if permission is disabled

### ISSUE THREAD

**Issue by avi-mastov** [MaikuB/flutter_local_notifications#885]
**Describe the bug**
When I disable the notification permission on iOS, the future of FlutterLocalNotificationsPlugin.initialize doesn't return.

**To Reproduce**
1. Call FlutterLocalNotificationsPlugin.initialize in the code. Put a breakpoint on that line and on the line after it.
2. Run the app.
3. When in the 1st breakpoint, hit continue in the debugger.
3. Click "Don't Allow" when prompted.
4. Debugger won't stop on the 2nd breakpoint.

**Expected behavior**
Returns false, just as if I would allow, it would return true.

**Sample code to reproduce the problem**

**Comment by vanlooverenkoen** [comment]
How did you fix this?

**Comment by avi-mastov** [comment]
@vanlooverenkoen I think I upgraded the package to the latest release and then it worked.

**Comment by vanlooverenkoen** [comment]
Hmm for me that is not working. I am triggering the notification from a callbackDispatcher function. So in another isolate. but even when I create all the object in the same function it still doesn't work.

**Comment by vanlooverenkoen** [comment]
I forgot to implment `setPluginRegistrantCallback` in iOS

https://github.com/icapps/flutter-background-location-tracker/pull/9
