### ISSUE TITLE
Android: Stop Notification Sound When Pressing Any Button on Device 

### ISSUE THREAD

**Issue by osaidhajjar** [MaikuB/flutter_local_notifications#886]
wondering if there is a way to allow notification sound to stop when a user presses any button of his/her device (power or volume buttons)? Currently the way to stop the notification sound is to swipe down the notifications panel.

**Comment by MaikuB** [comment]
No there isn't

**Comment by faisalmushtaq007** [comment]
@osaidhajjar brother i am having problem with notification sound on android, i am not getting any sound. Could you please help me with this
