### ISSUE TITLE
Providing route when notification selected like firebase does 

### ISSUE THREAD

**Issue by jweidner-mbible** [MaikuB/flutter_local_notifications#887]
Has there been any consideration for having the notification set up so that when it is selected it triggers the app to be opened with an initial route using the same way that a firebase notification does?  I've modified this plugin for Android by adding the two intent extras (route and click_action) as firebase does and that results in my app launching to the desired route.  I'm just curious if this is functionality that has been thought about?

**Comment by MaikuB** [comment]
Where is this feature for the Flutter [`firebase_messaging`](https://pub.dev/packages/firebase_messaging) plugin documented? I did look at the code for the plugin before when I worked on addressing compatibility issues with this plugin and hadn't seen any code where it deals with routes. Furthermore, sounds like you're talking specifically about Android. Intents are specific to Android and not visible to the Flutter side. There's an API that can be used to get the launch notification that could be used by apps to determine what the initial route will be. The upcoming major release to the `firebase_messaging` plugin will be providing a similar API too (see [here](https://pub.dev/documentation/firebase_messaging/8.0.0-dev.2/firebase_messaging/FirebaseMessaging/getInitialMessage.html))

**Comment by MaikuB** [comment]
Closing since no further information has been provided. If you're trying to relate intents with routes then note that they're different and the latter is a responsibility for the Flutter application to handle. Some applications might not even choose to used name routes and there are different approaches to navigation as well such as the Navigator 2.0 changes
