### ISSUE TITLE
notification sound doesnt work when app is in background

### ISSUE THREAD

**Issue by gau187** [MaikuB/flutter_local_notifications#889]
when i open the on android 8 and 8+ and send notification the sound which i added works but when i close the app the default sound plays

**Comment by MaikuB** [comment]
This plugin on its own should work the same way regardless of if the app is closed or not. You can run the example app to confirm. Furthermore, sounds to me that you are dealing with firebase messaging given you said send and I've seen others be confused about this before. If so, then you need to refer to their documentation as the notification you're seeing when the app is closed isn't being handled by this plugin. 

I'm closing this for now but if you're actually running into an issue with this specific plugin, then use the bug report template and include a link to a repo that has a minimal example app using only this plugin

**Comment by faisalmushtaq007** [comment]
@gau187 have you solved this problem, i am having the same issue

**Comment by gau187** [comment]
@faisalmushtaq007 no does not work when app is background but when its open its plays sound i dont think this is dependent on the firebase notifications @MaikuB

**Comment by MaikuB** [comment]
As mentioned before, if you're actually running into an issue with this specific plugin, then use the bug report template and include a link to a repo that has a minimal example app using only this plugin that can reproduce the issue

**Comment by gau187** [comment]
@faisalmushtaq007 i figured it out when i see the documentation we need to fix 2 things
1st --> in the AndroidNotificationDetails which you declaring you need to set  playSound: true
2nd --> check the implementation of you notification trigger you need to pass the android_channel_id in that for smooth functioning
