### ISSUE TITLE
Receiver android

### ISSUE THREAD

**Issue by juanjoserodrigolazaro** [MaikuB/flutter_local_notifications#89]
Is receiver necessary for receiving android scheduled notifications, because for ios you dont need nothing else than the configuration

**Comment by MaikuB** [comment]
Definitely is as Android's notification APIs don't support scheduling on their own and requires an intent to show the notification via the AlarmManager API, the intent to show the notification is handled caught by the receiver. If you search how you would schedule notifications on Android then you'll see that this is how it's normally done

**Comment by PedroNaretto** [comment]
i have the same problem, i have to add the files manually? or just put <receiver....com.package...

**Comment by MaikuB** [comment]
As per the readme, you need to add it the manifest file and there's an example app you can check here on GitHub.
