### ISSUE TITLE
Android notification icon showing in greyscale instead of color

### ISSUE THREAD

**Issue by kbokarius** [MaikuB/flutter_local_notifications#893]
We're seeing our notification icon appear in black and white on Android devices. We added transparency to the .png so the icon itself is showing the correct shape, it's just that the color is missing. Is there a particular setting or other change we have to make to have the icon to appear in color?

**Comment by MaikuB** [comment]
Sounds similar to some of the issues that have been reported e.g. https://github.com/MaikuB/flutter_local_notifications/issues/584. If so, it means you haven't done all of the setup. Please read https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#release-build-configuration

**Comment by kbokarius** [comment]
We actually did follow all of those steps. The icon shows up, it's just in monochrome. Upon further research, it seems like the status bar and small icon shown in the notifications can't have color. The largeIcon that appears to the right of the notification can have color, just not the smaller one. Is that your understanding too, or are we mistaken?

**Comment by MaikuB** [comment]
Ah sorry misunderstood what you meant. Whilst I'm not an expert on the creating the icons etc, what you said is my understanding with the ability to have the notifications API to apply a different colour to the small icon

**Comment by kbokarius** [comment]
> Ah sorry misunderstood what you meant. Whilst I'm not an expert on the creating the icons etc, what you said is my understanding with the ability to have the notifications API to apply a different colour to the small icon

@MaikuB sorry, does that mean you believe that we can change the color of the small icon via the API, or that we can't?

**Comment by MaikuB** [comment]
You cannot change the colour of the actual icon asset but you can via the API. Run the example app to see https://github.com/MaikuB/flutter_local_notifications/blob/4111de48bdbedab632f65ac2892159ba1d22543a/flutter_local_notifications/example/lib/main.dart#L685.

Closing this since this should has been clarified
