### ISSUE TITLE
Android scheduled notification

### ISSUE THREAD

**Issue by mdmota** [MaikuB/flutter_local_notifications#895]
I am doing some tests and I schedule several notifications to be triggered during the month.
Should I close the app completely should the notification appear?

**Comment by serpentdrake** [comment]
I have the same issue in which I am trying to schedule a notification to pop up 5 seconds after I click a button and apparently it does not pop up

**Comment by serpentdrake** [comment]
> I have the same issue in which I am trying to schedule a notification to pop up 5 seconds after I click a button and apparently it does not pop up

nvm solved mine just forgot to add one more receiver on the manifest

**Comment by MaikuB** [comment]
> I am doing some tests and I schedule several notifications to be triggered during the month.
Should I close the app completely should the notification appear?

I assume you meant to ask if the notification will appear if the app is closed. If so and you could run your own to confirm this by scheduling a notification to appear soon after you close the app (e.g. run the example app). Note though there are some devices where it might not happen. This is mentioned in the readme as it's a restriction placed by some manufacturers
