### ISSUE TITLE
on select notification method issue

### ISSUE THREAD

**Issue by muhib349** [MaikuB/flutter_local_notifications#900]
onSelectNotification works well when I tab the notification. If I dismiss the notification then I go to that screen "onSelectNotification()" method gets call again and again.

**Comment by MaikuB** [comment]
Please provide a link to a minimal app that can reproduce the problem

**Comment by muhib349** [comment]
[notification_sample_app](https://github.com/muhib349/notification_app)
[sample video of scenario](https://drive.google.com/file/d/10-ttruN8CZoDpTNXA6a8m2DeURZ4FPCG/view?usp=sharing)

**Comment by MaikuB** [comment]
Looks like this issue has to do with calling `initialize` multiple times. You'll need to look at changing the code so that it's only call once

**Comment by muhib349** [comment]
Well it works when it get calls only one time. May be it will better if callback method work only on notification tap. 
Thanks

**Comment by MaikuB** [comment]
Noted though it would likely need a breaking change to make it a stream instead of a callback as this is similar to what _firebase_messaging_ does as well. IMO a callback seems more natural to use similar to how gestures are handled when it comes to Flutter widgets and I think very few have reported this issue, possibly because it's documented to only call it once

**Comment by fldvlpr** [comment]
> Looks like this issue has to do with calling `initialize` multiple times. You'll need to look at changing the code so that it's only call once

I am also facing similar kind of issue.

@MaikuB  Can you please tell me what is mean by "calling initialize multiple times"? 
I have multiple screens in which i needed to fire local notification. So I am initializing local notification in all the screens using following "initializeNotifications" method in my all the screen's initstate method. Is there anything I am missing?

```
FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin;
initializeNotifications() async {
    if (Platform.isIOS) {
      flutterLocalNotificationsPlugin
          .resolvePlatformSpecificImplementation<
              IOSFlutterLocalNotificationsPlugin>()
          ?.requestPermissions(alert: true, badge: true, sound: true);
    }

    var initializationSettingsAndroid =
        AndroidInitializationSettings('@mipmap/ic_launcher');
    var initializationSettingsIOS = IOSInitializationSettings();
    var initializationSettings = InitializationSettings(
        android: initializationSettingsAndroid, iOS: initializationSettingsIOS);
    await flutterLocalNotificationsPlugin.initialize(initializationSettings,
        onSelectNotification: (String payload) async {
    });
}

```

@muhib349 Can you let me know how did you resolve this issue?

Thank you.

**Comment by MaikuB** [comment]
@fldvlpr what did you need more clarification on? I had highlighted `initialize` to indicate that it refers to code, which is a method from the plugin. This is also called within your code even. Calling `initialize` multiple times means exactly that, where the method is being called multiple times. It has been explained in the readme that initialisation should only be done once (see https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#initialisation).

**Comment by fldvlpr** [comment]
@MaikuB I have kept nw only one initialisation throughout app and still whenever I try to open this screen it triggers the onselect method every time.

**Comment by MaikuB** [comment]
@fldvlpr having only place in the code that does initialisation is not the same as making sure it is only ever called once

**Comment by fldvlpr** [comment]
@MaikuB I have initialised it at one place and the same screen gets called only once in the app.

**Comment by MaikuB** [comment]
If that is indeed what is happening then that would be a bug and you would need to provide a link to a repository containing a minimal app that can reproduce for it to be investigated

**Comment by fldvlpr** [comment]
@MaikuB This is private repo. So I will share you the new repo with same kind of screens but with dummy data and a new project in this weekend.

**Comment by SardorbekR** [comment]
@fldvlpr Have you solved this issue?
