### ISSUE TITLE
When app is closed , notification is not triggered(I checked the example app on android, still nothing)

### ISSUE THREAD

**Issue by faisalmushtaq007** [MaikuB/flutter_local_notifications#901]

**Comment by MaikuB** [comment]
Please provide info on what device you're using

**Comment by MaikuB** [comment]
Also when you're running the example app, did you clone the entire repository? The code will not work if you just copy the Dart code over to your app and is mentioned the code comments for the example app

**Comment by faisalmushtaq007** [comment]
@MaikuB i have cloned the entire repository but i use the example app only. it shows notifications but notification sound doesnt work and when app is closed the notifications are halted until we again open the app

**Comment by faisalmushtaq007** [comment]
i use Xaiomi POCO F1 device

**Comment by MaikuB** [comment]
Please make sure you go through the readme as I had documented [here](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#scheduled-android-notifications) that some Android device manufacturers place restrictions on what can run in the background. There's nothing the plugin can do about that

**Comment by faisalmushtaq007** [comment]
i am having issue with the notification sound on android, i checked your example app. that too doesnt play any sound on notifications. please help @MaikuB

**Comment by MaikuB** [comment]
There aren't any issues on this with the example app so you need to check your device settings. I've had a number of others forget that turned off the notification sound on their device as it's separate from volume settings. I put screenshots of this at https://github.com/MaikuB/flutter_local_notifications/issues/754#issuecomment-673755905

**Comment by faisalmushtaq007** [comment]
@MaikuB yes the issue was in app settings, had to switch on the notifications sound switch. But now the problem is that how will i counter it.  The app users wont know what to do. How will i counter it. like is there some kind of permission for notification sound or something that might help me here

**Comment by MaikuB** [comment]
Standard Android OS implementations don't need permissions on this. Perhaps your device is different and you should look into packages available on pub around permissions to see if they help

**Comment by faisalmushtaq007** [comment]
@MaikuB  solved this issue, actually we had to set IMPORTANCE AND PRIORITY levels to HIGH.

**Comment by efraespada** [comment]
@faisalmushtaq007 could you show us the body request you use for setting these levels?
