### ISSUE TITLE
custom vibration pattern dont work in background message

### ISSUE THREAD

**Issue by ygorrrteles** [MaikuB/flutter_local_notifications#903]
I am implementing background notification to notify the user that a voice call is occurring in the application.
The notification will consist of a custom vibration pattern, however, with the push in the background the custom patten is not performed.
the phone performs the standard device vibration (which is the wrong behavior).

```
  
static Future myBackgroundMessageHandler(Map<String, dynamic> message) async {
    print("background##########################");
    print("background: $message");

     //var vibrationPattern = new Int64List.fromList([1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000]);
    final Int64List customvibrationPattern = Int64List(4);
    customvibrationPattern[0] = 0;
    customvibrationPattern[1] = 1000;
    customvibrationPattern[2] = 5000;
    customvibrationPattern[3] = 2000;
    FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin = FlutterLocalNotificationsPlugin();
    var androidPlatformChannelSpecifics = AndroidNotificationDetails(
      'test',
      'test',
      'test',
      importance: Importance.max,
      priority: Priority.max,
      ticker: 'ticker',
      // vibrationPattern: vibrationPattern,
      vibrationPattern: customvibrationPattern,
      enableVibration: true,
      indeterminate: true,
      timeoutAfter: 30000,
    );
    var iOSPlatformChannelSpecifics = IOSNotificationDetails();
    NotificationDetails platformChannelSpecifics = NotificationDetails(android: androidPlatformChannelSpecifics, iOS: iOSPlatformChannelSpecifics);
    String payload;
    if (Platform.isIOS) {
      payload = message['payload'];
    } else {
      payload = message['data']['payload'];
    }
    await flutterLocalNotificationsPlugin.show(0, message['data']['title'], message['data']['body'], platformChannelSpecifics, payload: payload);
  }
```

what's wrong with my code?
remembering, in the foreground it works, **in the background it doesn't work**

**Comment by MaikuB** [comment]
`firebase_messaging` integration isn't something I can help with but given it works in the foreground and the documented behaviour of  `firebase_messaging`, what you're most likely seeing is actually the push notification not the local notification being shown by your code. If you look at their documentation, it says that when the app is the background or terminated that "Notification is delivered to system tray" so an actual notification will get displayed automatically in those scenarios

**Comment by faisalmushtaq007** [comment]
@ygorrrteles I am having the same problem, and my notification sound also doesnt work. Could you help me with that

**Comment by MaikuB** [comment]
@ygorrrteles what I said should be correct as the new docs that do expand on this. Take a look at https://firebase.flutter.dev/docs/messaging/usage. Whilst it's for the prerelease, the description there should still apply within the context of this problem. Notification messages are displayed by the firebase messaging SDK when the app is in the background automatically. The background handler is called as well. I'm pretty confident that your code actually fails to run as it runs in it's own isolate. This is like another entry point into the app so means that the local notifications plugin would have needed to been initialised as part of the handler. The code within the handler won't know about variables you've defined outside the scope of the method. Closing this in light of this info and explanation
