### ISSUE TITLE
_showFullScreenNotification ios on background

### ISSUE THREAD

**Issue by prozaklob** [MaikuB/flutter_local_notifications#904]
hi!
I apologize in advance if I duplicate the question, but I did not find the information I needed in the answers (or I was looking badly).

At the moment I have adapted the plugin for fcm onback.
On android it works like this:
FCM send json: 
notif: null
data: array

fcm onBack run _showFullScreenNotification
onSelect -> go to page

On android, this launches my application wakes up the screen and launches over the locked screen and goes to the desired page, in any state of the application (closed / minimized / in the foreground, or in the foreground, but the screen is locked).

on ios, if the application is closed or minimized - I could not get the call to _showFullScreenNotification.
I assumed it was my application and tried running example ( schedule ).
example works the same as mine - I only get flutterLocalNotificationsPlugin.show.

Perhaps I am mistaken and, in principle, it cannot work on ios the way I want it?

thx

**Comment by MaikuB** [comment]
With regards to your callback not being called, that's an issue with `firebase_messaging` that should go on their repo. Furthermore, in the latest stable release of firebase_messaging only supports background messaging on Android. If you happen to be using their prerelease version where iOS support was added then you should file an issue on that repo to provide more details for the maintainers to look into it

**Comment by prozaklob** [comment]
The question was not about FCM. :) Yes, they added background work only in the dev branch of fcm. 
I'm wondering if it's possible to call showfullscreen on top of the lock screen on ios (on android it works).

**Comment by MaikuB** [comment]
Ok looks like that wasn't communicated clearly as not getting a call from FCM as described in the post would be a FCM callback issue.

Full-screen intent notifications are only for Android. If you look at the [features](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#-features) section of the readme then you should see the Android "tag" next to that feature to indicate it is specific. This is why it grouped under Android-specific examples in the example app [here](https://github.com/MaikuB/flutter_local_notifications/blob/1fdf1cefba4777a5bedb333db2fa41f11c9e74ee/flutter_local_notifications/example/lib/main.dart#L360). The [property](https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/AndroidNotificationDetails/fullScreenIntent.html) for enabling this belongs to a class for configuring notification details specific to Android.

**Comment by prozaklob** [comment]
Excellent! Thanks for the information. Then it looks like - I'll have to get along with voip push :(
