### ISSUE TITLE
using rrules patterns with local notifications

### ISSUE THREAD

**Issue by vetbabble** [MaikuB/flutter_local_notifications#905]
I currently am trying to create recurring notifications using a similar design as in RRULES patterns (https://dateutil.readthedocs.io/en/stable/rrule.html)

Is there a way to make the rules that require recurrance on certain days of the week, every two weeks, or a certain day of the month?  

It seems like I can set things to calculate the next notification each time the notification is triggered.  However, this won't work for many cases.

Are there other ways to handle recurrance with this library other people have been using?

**Comment by MaikuB** [comment]
There are limitations on what you can do with the APIs, particularly on iOS and macOS around recurring notifications (see https://developer.apple.com/documentation/usernotifications/uncalendarnotificationtrigger). Even on Android, that needed some custom logic to be done. For what you're after, you'll need to look at leveraging the native APIs implementing this logic yourself and even then it'll likely be Android-specific. From what I've seen so far, the native calendar APIs can create events using the RRULES pattern so perhaps the [device_calendar](https://pub.dev/packages/device_calendar) plugin is better suited for what you're after.

As a sidenote, GitHub issues board for libraries like this isn't a place where developers gather to having a discussions so I'll be closing this. At the least, I don't recall anyone going on here for discussions or replying as well. Most people that go here are after things with using this plugin but what you're after requires knowledge of the native APIs that very few that go on here are likely to know. There aren't that many users watching the repo either. I'd suggest you try places like Discord and Slack that is listed at https://flutter.dev/community as you'll have a much better chance of getting an answer there.

**Comment by vetbabble** [comment]
Thanks for the clarification @MaikuB.  I wasn't sure about the specific limitations of this plugin with the new proposed recurrance logic now that the repeat daily/weekly was deprecated.  I was going to make an enhancement request, but wasn't sure if it was already possible and didn't want to reinvent the wheel.
