### ISSUE TITLE
How to dynamically change notification title and body in periodicallyShow() call?

### ISSUE THREAD

**Issue by misici234** [MaikuB/flutter_local_notifications#909]
Here is the code sample from the example project

`    await flutterLocalNotificationsPlugin.periodicallyShow(0, 'repeating title',
        'repeating body', RepeatInterval.everyMinute, platformChannelSpecifics,
        androidAllowWhileIdle: true);`

How can I change 'repeating title' and 'repeating body' every time when new notification is pushed?

**Comment by MaikuB** [comment]
You can't with any of the notification APIs as recurring notifications provided by the native APIs aren't made to work that way. You'll need to come up with your own solution for scheduling a new notification each time
