### ISSUE TITLE
[iOS]Media deleted from app's local folder after media is shown as attachment

### ISSUE THREAD

**Issue by MarsGoatz** [MaikuB/flutter_local_notifications#910]
I am not sure if this is the intended behaviour, if I pass local media path as [attachment in iOS](https://github.com/MaikuB/flutter_local_notifications/blob/1fdf1cefba4777a5bedb333db2fa41f11c9e74ee/flutter_local_notifications/example/lib/main.dart#L546), after the notification is triggered and If I close the app and open it again, the media is gone. **I can reproduce this issue only on real device and not on simulator**. [Apple documentation](https://developer.apple.com/documentation/usernotifications/unnotificationattachment?language=objc) link mentioned in [IOSNotificationAttachment](https://github.com/MaikuB/flutter_local_notifications/blob/1fdf1cefba4777a5bedb333db2fa41f11c9e74ee/flutter_local_notifications/lib/src/platform_specifics/ios/notification_attachment.dart#L11) does state that:

>attached files are moved into the attachment data store so that they can be accessed by all of the appropriate processes. Attachments located inside an app’s bundle are copied instead of moved.

The workaround, if I can call it that, is to copy the media and then pass the copy's path as attachment. 

My question is, isn't the local storage part of the app's bundle? or does the app's bundle consists of just the assets and other things we declare in ```pubspec.yaml```? If the app's storage is not part of the app's bundle then the behaviour makes sense but if its the other way around then its probably a bug?

My worry is, if I keep copying images for notifications and those images are not moved, the app size could keep increasing and that is something I need to worry about.

Anyway, wanted to ask the question here and if everything is working as expected, please close the issue and I apologize for raising the bug. Thank you!

<details>
  <summary>Flutter Doctor</summary>

<p>
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale en-CA)
    • Flutter version 1.22.4 at /Users/sid/Work/Software/Flutter/flutter
    • Framework revision 1aafb3a8b9 (6 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/sid/Work/Software/Flutter/android
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = /Users/sid/Work/Software/Flutter/android
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • iPhone Xs • ios • iOS 14.1

</p>
</details>

**Comment by MaikuB** [comment]
In general, whatever the plugin is doing is working as expected as it's just exposing the available APIs. Your issue here is really more on how storage works so is something you'd need to look up more on and isn't something I can answer. You'd need to look at more about the storage APIs you're using to see where data gets saved and the behaviour(s) specific to the platforms you're targeting. It may be possible you need to store the data elsewhere to ensure it remains there.
