### ISSUE TITLE
Image is not displayed

### ISSUE THREAD

**Issue by evertonfoz** [MaikuB/flutter_local_notifications#913]
Hello, how are you? I follow the implementation of the example, but the icon is not displayed in the notification. I used an existing one (png) and also created one through android studio, but it doesn't appear. Can you help me please? Thankful.

**Comment by gbaranski** [comment]
Same issue here

**Comment by MaikuB** [comment]
If your icon isn't displaying then you're missing something and it's hard to know what it is. Besides following the example, you should make sure you refer to the readme for this plugin. There are links to official Android documentation as it's important to put your images in the right location

**Comment by MaikuB** [comment]
Closing due to lack of response. You'll need to take a closer look at what you're doing and refer to both the docs and example. If you need more help, I suggest going to places like slack or discord listed at https://flutter.dev/community
