### ISSUE TITLE
Notification in foreground opens even if I don't tap the notification

### ISSUE THREAD

**Issue by raffa-12** [MaikuB/flutter_local_notifications#914]
Hi,
when i receive a notification in foreground and I tap anywhere in the screen, the notification function is called. How can i avoid it?
Thank you.

**Comment by MaikuB** [comment]
There haven't been any other reports on this issue and I've never encountered this either. There's an example app in the repo that can be run by cloning/downloading the repository and I haven't been able to reproduce this either. Based on this, I would suspect having something else going on specific to your application. If so, then this something you'd need to look into on you own or seek help from the wider community with helping your specific app.

If you happen to be able to reproduce this with the example, then please provide a video, details of the device and include the output of running `flutter doctor -v`

**Comment by zaeemrbn** [comment]
II have similar onSelectNotification is called continuously once the notification is tapped in while the app is in foregorund

**Comment by MaikuB** [comment]
@zaeemrbn yours is a different issue and sounds more like an issue with how your application is written as there's been no reports of such bugs. If you believe you have run into a bug then please file a separate issue using the bug report template where you need to also include a complete minimal app that can reproduce the problem

**Comment by zaeemrbn** [comment]
> @zaeemrbn yours is a different issue and sounds more like an issue with how your application is written as there's been no reports of such bugs. If you believe you have run into a bug then please file a separate issue using the bug report template where you need to also include a link to a repository that contains complete minimal app that can reproduce the problem

Thank you for the instant response

**Comment by raffa-12** [comment]
I fix the bug and you were correct, it was in my app. Thank
