### ISSUE TITLE
Release mode crashes because of no icon. Icon is grey circle in debug mode [duplicate]

### ISSUE THREAD

**Issue by gbaranski** [MaikuB/flutter_local_notifications#916]
**Describe the bug**
When app is running in release mode it crashes with this exception
```
E/flutter (32266): [ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(43)] java.lang.AssertionError: java.lang.NoSuchFieldException: DrawableResource
E/flutter (32266): 	at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(Unknown Source:87)
E/flutter (32266): 	at com.google.gson.internal.bind.TypeAdapters$30.a(Unknown Source:29)
E/flutter (32266): 	at com.google.gson.Gson.a(Unknown Source:74)
E/flutter (32266): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(Unknown Source:42)
E/flutter (32266): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(Unknown Source:123)
E/flutter (32266): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(Unknown Source:22)
E/flutter (32266): 	at com.google.gson.Gson.a(Unknown Source:74)
E/flutter (32266): 	at com.google.gson.Gson.a(Unknown Source:4)
E/flutter (32266): 	at com.google.gson.Gson.a(Unknown Source:8)
E/flutter (32266): 	at com.google.gson.Gson.a(Unknown Source:5)
E/flutter (32266): 	at com.google.gson.Gson.a(Unknown Source:13)
E/flutter (32266): 	at com.dexterous.flutterlocalnotifications.b.c(Unknown Source:4)
E/flutter (32266): 	at com.dexterous.flutterlocalnotifications.b.j(Unknown Source:29)
E/flutter (32266): 	at com.dexterous.flutterlocalnotifications.b.onMethodCall(Unknown Source:229)
E/flutter (32266): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(Unknown Source:17)
E/flutter (32266): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(Unknown Source:57)
E/flutter (32266): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
E/flutter (32266): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (32266): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/flutter (32266): 	at android.os.Looper.loop(Looper.java:183)
E/flutter (32266): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/flutter (32266): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (32266): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/flutter (32266): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/flutter (32266): Caused by: java.lang.NoSuchFieldException: DrawableResource
E/flutter (32266): 	at java.lang.Class.getField(Class.java:1604)
E/flutter (32266): 	at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(Unknown Source:34)
E/flutter (32266): 	... 23 more
E/flutter (32266):
F/flutter (32266): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(942)] Check failed: CheckException(env).
```
but in debug mode, it doesn't crash but icon is just a grey circle.
And yes, I added `proguard-rules.pro` file, its identical to https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/example/android/app/proguard-rules.pro , also I added 
```
            // Enables code shrinking, obfuscation, and optimization for only
            // your project's release build type.
            minifyEnabled true

            // Enables resource shrinking, which is performed by the
            // Android Gradle plugin.
            shrinkResources true

            // Includes the default ProGuard rules files that are packaged with
            // the Android Gradle plugin. To learn more, go to the section about
            // R8 configuration files.
            proguardFiles getDefaultProguardFile(
                    'proguard-android-optimize.txt')
                'proguard-rules.pro'
```
to `android/app/build.gradle`, I'm not sure about `proguard-android-optimize.txt` because I don't have this file anywhere, but as I can see your example also doesn't have it.
keep.xml is also here, saying to keep all `@drawable/*`. Actually I already saw issues like my one, but most of them endes with "nvm it works" or something I already tried.

Things I'm not sure about is this file
https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/example/android/app/src/main/java/com/dexterous/flutterlocalnotificationsexample/MainActivity.java

Mine MainActivity.kt is almost empty, but there is no information about it in documentation

**Sample code to reproduce the problem**
https://github.com/gbaranski/houseflow/tree/issue_125/app_mobile
Here is where I call all flutter notifications 
https://github.com/gbaranski/houseflow/blob/issue_125/app_mobile/lib/services/notifications.dart

**Comment by MaikuB** [comment]
It looks like you're using 3.0.1+3 whilst the reduced setup was a change in 3.0.1+4, which is the latest version. Can you try using the latest version of the plugin?

**Comment by gbaranski** [comment]
@MaikuB I updated, but still same issue

**Comment by MaikuB** [comment]
You'll need to provide a minimal app then. Your app currently has a few other dependencies (particularly on firebase) that prevents me from being able to run it a release build right away. Earlier I made a lot of changes to strip out all the dependencies and reproduced your issue, bumped the dependency and no longer had the issue.

If you happen to have old notifications scheduled then you'll still see the crash reported as updating can't fix notifications that were previously scheduled for a problem like this.

The icon being grey is because it doesn't meet the requirements Android has around icons so you'll need to check the docs on that e.g. https://developer.android.com/studio/write/image-asset-studio#notification. Looks like yours is in colour so that's why.

**Comment by gbaranski** [comment]
Thanks for help. Solved this by removing background on notification icon :)

**Comment by sewerganger** [comment]
@gbaranski  Can you be more specific

**Comment by gbaranski** [comment]
> @gbaranski  Can you be more specific

Just remove background from logo, export it to png.
