### ISSUE TITLE
> A few questions

### ISSUE THREAD

**Issue by hkndzdr** [MaikuB/flutter_local_notifications#920]
> A few questions
> 
> 1. What phone are you using?
> 2. Have you tried this on an emulator and if so, what happens then?
> 3. When you say it works as expected before restarting, is the app still running in the foreground or has it been killed? If it was from when it was still running, have you tried killing them and not restarting to see if it still appears?

@MaikuB 
I have the same problem. (ver. 3.0.1+4) The result is the same in both the example app and my own app.

1. I tried it on Xiaomi Mi5, Samsung Galaxy S7. (Both release and debug mode)
2. No problem with the emulator. (Running after reboot)
3. I can get notifications when the application is killed on all real devices. The problem only occurs when the device is rebooted.

_Originally posted by @hkndzdr in https://github.com/MaikuB/flutter_local_notifications/issues/767#issuecomment-731183992_

**Comment by MaikuB** [comment]
Then you are running into device-specific issues/restrictions, similar to the same issue with scheduled notifications not working on for certain manufacturers that I pointed out in the readme. I'm curious though on how you got notifications to work on a Xiaomi device even when the app is killed. Don't have one myself (nor a Samsung) but from what I've read, I guess you had to change some settings for that to work. If so, then you may need to look for a setting to solve this issue
