### ISSUE TITLE
Prevent expanded notification view

### ISSUE THREAD

**Issue by Iampato** [MaikuB/flutter_local_notifications#922]
## Feature Request 
In android. in the AndroidInitializationSettings  adding of boolean to allow/disallow expansion

**Comment by MaikuB** [comment]
The title says you want to prevent expansion but the details of your message says you want to be about to expand. Could you please clarify what it is you're after? Expandable notifications are available supported on Android as they're based on the style that is used, which is consistent with how it's done natively as per the official Android docs at https://developer.android.com/training/notify-user/expanded

**Comment by Iampato** [comment]
@MaikuB I have updated

**Comment by MaikuB** [comment]
Then as I covered in my previous post, it's up to you to use the appropriate notification style. This isn't a matter of using a boolean flag or not as that isn't the way they work on Android either. If you haven't already, please make use the example app to see how it works

**Comment by Iampato** [comment]
WTF  !!!!!
