### ISSUE TITLE
Feature: Get scheduled time of PendingNotificationRequest

### ISSUE THREAD

**Issue by RickVM** [MaikuB/flutter_local_notifications#923]
I would like to show all pending notifications to the users in a view.
It is possible to retrieve the pending notifications, these however do not contain the time they are scheduled for or their repeatInterval.

Ofcourse I could implement a store where I match the notification id and store this information myself, but I suspect this information is already available in the library. Therefore it would be convenient if this information was added to the pendingNotificationRequest class

**Comment by MaikuB** [comment]
The info isn't available in the plugin as Android doesn't provide APIs for retrieving it. Even scheduling notifications requires using another API that isn't related to notifications but for scheduling any kind of generic work. You'd need to make some modifications for it to work in your case or use a data store as you mentioned

**Comment by RickVM** [comment]
Alright, seems its harder than I thought, I'll use a data store.
Thanks for the info!

**Comment by MaikuB** [comment]
If you fork the plugin, you could possibly add that as extra info as the pending notification info on Android comes from shared preferences. Notification info is saved there so that the plugin can reschedule notifications after a device is rebooted as as a reboot would normally clear that out

**Comment by RickVM** [comment]
Would this be appreciated? If so, might look into it if I find the time. 
For my use case, in the future I'll also have to save additional information, which sooner or later will require me to implement my own data store.

**Comment by micimize** [comment]
Can't we just put the schedule details in the notification payload?
