### ISSUE TITLE
Xiaomi MIUI don't allow floating notification and sound by default

### ISSUE THREAD

**Issue by mahmoudparandeh** [MaikuB/flutter_local_notifications#928]
**Describe the bug**
when i install my apps which use flutter local notification and firebase messaging, in my app i call show local notification but no sounds play and also no floating notification appears.
![2020-11-25 14 09 06](https://user-images.githubusercontent.com/36625602/100217121-5703db80-2f28-11eb-8d9b-e37d3638d55e.jpg)
is there any permissions needed to add on android manifest?

**Comment by MaikuB** [comment]
Not as far as I know and they're not needed on stock Android. These kind of things tend to happen on non-stock Android devices. It seems like a common thing that users have to change their settings to remove restrictions etc placed by the OS to get things to work. Not sure if floating notifications are the same as a heads-up notification, in which case the only thing available via the Android APIs is to make sure to set the appropriate priority and importance

**Comment by MaikuB** [comment]
Did a bit more of a search and looks like it's common problem and to do with the OS e.g. this messaging product even called this out https://threema.ch/en/faq/notification_channels_xiaomi

You might need to include a guide or look into letting the user in the app that they turn change their settings

**Comment by faisalmushtaq007** [comment]
@MaikuB could you please take a look at this issue. My launch date is in few days, i need to solve this. Please

**Comment by mahmoudparandeh** [comment]
@faisalmushtaq007 you can handle this with two packages, first package is device_info to get device model and brand to detect xiaome phones or other models that disable sounds for default. then, use app_settings to directly navigate user to notification settings. note that the app_settings is worked for android version bigger than 7. hope this help you.
