### ISSUE TITLE
Hot Reload trigger "onSelectNontification"

### ISSUE THREAD

**Issue by anggaaryas** [MaikuB/flutter_local_notifications#931]
is it normal that when i do a hot reload, the nontification trigger "onSelectNontification" automatically.

**Describe the bug**
Hot Reload trigger "onSelectNontification"

**To Reproduce**
1. show nontification
2. click the nontification (move to newScreen)
3. click "hot reload"
4. the app will trigger "onSelectNontification" automatically

**The Question**
Is it normal? or should i handle this behaviour?

**Sample code to reproduce the problem**
example Project

**Comment by iqfareez** [comment]
*notification

**Comment by MaikuB** [comment]
Yes it's normal as initialisation is what triggers the callback and reloading will fire it again. I may see about addressing this at a future update but for now, you'll need to bear this in mind whilst working with the plugin
