### ISSUE TITLE
Android Setup 

### ISSUE THREAD

**Issue by Jayvd** [MaikuB/flutter_local_notifications#933]
Do we still need to use RECEIVE_BOOT_COMPLETE permission in the AndroidManifest file? The current readme doesnt say anything about that.. What changes??

**Comment by wiktoriasobczyk** [comment]
I don't have it in my project configuration :D so I think you can skip it :D but it depends on lib version 👍 if you use the older version this config is required

**Comment by MaikuB** [comment]
Thanks @wiktoriasobczyk for answering this :)

@Jayvd if you looked at the readme then you should see that I had documented that the setup needed has been reduced [here](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#%EF%B8%8F-android-setup). The plugin has a changelog that's on [GitHub](https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/CHANGELOG.md) and [pub](https://pub.dev/packages/flutter_local_notifications/changelog). If you use GitHub's watch feature, you can be notified of new [releases](https://github.com/MaikuB/flutter_local_notifications/releases)where the details are also included there
