### ISSUE TITLE
Unable to Set zonedSchedule's TZDateTime using flutter_native_timezone

### ISSUE THREAD

**Issue by Jayvd** [MaikuB/flutter_local_notifications#934]
MissingPluginException(No implementation found for method getLocalTimezone on channel flutter_native_timezone

Crashes on `iOS Simulator`, any idea how to fix this?  

Thank you

**Comment by eddiesTime** [comment]
>MissingPluginException(No implementation found for method getLocalTimezone on channel flutter_native_timezone

There are multiple closed issue related to this topic. I advice you to check out the closed issue to see if someone ran into the same problem before.

Otherwise, what it means is that you are missing the native implementation of the logic of `getLocalTimezone`. For more information check [this](https://flutter.dev/docs/development/platform-integration/platform-channels) out.

If you created your Flutter project with java & objective-c as native language, you can check out the configuration in the repository's [example](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications/example).

If you use kotlin:

```kotlin
import android.content.ContentResolver
import android.content.Context
import android.media.RingtoneManager
import androidx.annotation.NonNull
import io.flutter.embedding.android.FlutterFragmentActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugin.common.MethodChannel
//import jdk.nashorn.internal.objects.NativeFunction.call
import java.util.TimeZone


class MainActivity: FlutterFragmentActivity() {
    private val CHANNEL = "YOUR_CHANNEL_IDENTIFIER"

    private fun resourceToUriString(context: Context, resId: Int): String? {
        return (ContentResolver.SCHEME_ANDROID_RESOURCE
                + "://"
                + context.resources.getResourcePackageName(resId)
                + "/"
                + context.resources.getResourceTypeName(resId)
                + "/"
                + context.resources.getResourceEntryName(resId))
    }

    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine){
        super.configureFlutterEngine(flutterEngine)
        MethodChannel(flutterEngine.dartExecutor.binaryMessenger, CHANNEL).setMethodCallHandler {
      call, result ->
            if ("drawableToUri" == call.method) {
                val resourceId = this@MainActivity.resources.getIdentifier(call.arguments as String, "drawable", this@MainActivity.packageName)
                result.success(resourceToUriString(this@MainActivity.applicationContext, resourceId))
            }
            if ("getAlarmUri" == call.method) {
                result.success(RingtoneManager.getDefaultUri(RingtoneManager.TYPE_ALARM).toString())
            }
      if("getTimeZoneName".equals(call.method)){
          result.success(TimeZone.getDefault().getID())
      }
    }
    }
}
```

And the swift part:

```swift
import UIKit
import Flutter
import flutter_local_notifications

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    if(!UserDefaults.standard.bool(forKey: "Notification")) {
    UIApplication.shared.cancelAllLocalNotifications()
    UserDefaults.standard.set(true, forKey: "Notification")

    // Required by LocalNotification package
    if #available(iOS 10.0, *) {
  UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate
}
    
    let controller : FlutterViewController = window?.rootViewController as! FlutterViewController
    let timeZoneChannel = FlutterMethodChannel(name: "YOUR_CHANNEL_IDENTIFIER",
                                                  binaryMessenger: controller.binaryMessenger)
    
    timeZoneChannel.setMethodCallHandler({(call: FlutterMethodCall, result: FlutterResult) -> Void in
        guard call.method == "getTimeZoneName" else {
            result(FlutterMethodNotImplemented)
            return
        }
        result(NSTimeZone.local.identifier)
    })
    }
    GeneratedPluginRegistrant.register(with: self)

    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}

```

I hope this answers your question and helps!

**Comment by Jayvd** [comment]
> > MissingPluginException(No implementation found for method getLocalTimezone on channel flutter_native_timezone
> 
> There are multiple closed issue related to this topic. I advice you to check out the closed issues to see if someone ran into the same problem before.
> 
> Otherwise, what it means is that you are missing the native implementation of the logic of `getLocalTimezone`. For more information check [this](https://flutter.dev/docs/development/platform-integration/platform-channels) out.
> 
> If you created your Flutter project with java & objective-c as native language, you can check out the configuration in the repository's [example](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications/example).
> 
> If you use kotlin:
> 
> ```kotlin
> import android.content.ContentResolver
> import android.content.Context
> import android.media.RingtoneManager
> import androidx.annotation.NonNull
> import io.flutter.embedding.android.FlutterFragmentActivity
> import io.flutter.embedding.engine.FlutterEngine
> import io.flutter.plugin.common.MethodChannel
> //import jdk.nashorn.internal.objects.NativeFunction.call
> import java.util.TimeZone
> 
> 
> class MainActivity: FlutterFragmentActivity() {
>     private val CHANNEL = "YOUR_CHANNEL_IDENTIFIER"
> 
>     private fun resourceToUriString(context: Context, resId: Int): String? {
>         return (ContentResolver.SCHEME_ANDROID_RESOURCE
>                 + "://"
>                 + context.resources.getResourcePackageName(resId)
>                 + "/"
>                 + context.resources.getResourceTypeName(resId)
>                 + "/"
>                 + context.resources.getResourceEntryName(resId))
>     }
> 
>     override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine){
>         super.configureFlutterEngine(flutterEngine)
>         MethodChannel(flutterEngine.dartExecutor.binaryMessenger, CHANNEL).setMethodCallHandler {
>       call, result ->
>             if ("drawableToUri" == call.method) {
>                 val resourceId = this@MainActivity.resources.getIdentifier(call.arguments as String, "drawable", this@MainActivity.packageName)
>                 result.success(resourceToUriString(this@MainActivity.applicationContext, resourceId))
>             }
>             if ("getAlarmUri" == call.method) {
>                 result.success(RingtoneManager.getDefaultUri(RingtoneManager.TYPE_ALARM).toString())
>             }
>       if("getTimeZoneName".equals(call.method)){
>           result.success(TimeZone.getDefault().getID())
>       }
>     }
>     }
> }
> ```
> 
> EDIT: Instead of `FlutterFragmentActivity` you can use `FlutterActivity`. I had to adapt it to use an unrelated package to this issue.
> 
> And the swift part:
> 
> ```swift
> import UIKit
> import Flutter
> import flutter_local_notifications
> 
> @UIApplicationMain
> @objc class AppDelegate: FlutterAppDelegate {
>   override func application(
>     _ application: UIApplication,
>     didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
>   ) -> Bool {
>     if(!UserDefaults.standard.bool(forKey: "Notification")) {
>     UIApplication.shared.cancelAllLocalNotifications()
>     UserDefaults.standard.set(true, forKey: "Notification")
> 
>     // Required by LocalNotification package
>     if #available(iOS 10.0, *) {
>   UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate
> }
>     
>     let controller : FlutterViewController = window?.rootViewController as! FlutterViewController
>     let timeZoneChannel = FlutterMethodChannel(name: "YOUR_CHANNEL_IDENTIFIER",
>                                                   binaryMessenger: controller.binaryMessenger)
>     
>     timeZoneChannel.setMethodCallHandler({(call: FlutterMethodCall, result: FlutterResult) -> Void in
>         guard call.method == "getTimeZoneName" else {
>             result(FlutterMethodNotImplemented)
>             return
>         }
>         result(NSTimeZone.local.identifier)
>     })
>     }
>     GeneratedPluginRegistrant.register(with: self)
> 
>     return super.application(application, didFinishLaunchingWithOptions: launchOptions)
>   }
> }
> ```
> 
> I hope this answers your question and helps!

Thank you, on an unrelated note. I am **wondering which part of your Swift code that makes the notification not being triggered when  the app is on foreground** ??  I removed your code and the notification appear even when the app is on foreground..

Sorry for this question, since I am not from a Swift background.. Thank you

**Comment by eddiesTime** [comment]
Glad it helped to overcome the error message.

Regarding you other question - The swift code has been converted from the objective-c example code. If the example code does not handle the notification when the app is in foreground neither will the app with the swift code.

From the package's _Readme_, I am not understanding how to manage this behavior myself, yet. You should check out if someone created an issue regarding this behavior before. Otherwise, [stackoverflow](https://stackoverflow.com/) could provide your desired answers.

If the issue itself is solved, please close it. 

Good luck with your app and happy coding!

**Comment by MaikuB** [comment]
Closing since @eddiesTime has answered the original question.

Thanks @eddiesTime for helping out :)

**Comment by kinex** [comment]
This new requirement that everyone using this plugin must now implement some native code to make things working does not make any sense. I hope you guys find a better solution. Why can't you include that code in this plugin? I think I will revert to 1.5 at least for now.
