### ISSUE TITLE
Retrieving Pending Notification's Schedule

### ISSUE THREAD

**Issue by Jayvd** [MaikuB/flutter_local_notifications#941]
Is it possible to get pending notification's scheduled firing time? The `PendingNotificationRequest` object doesnt seem to provide this. Any other ways to achieve this?

**Comment by MaikuB** [comment]
No, there isn't. There are some old issues with the same question (e.g. https://github.com/MaikuB/flutter_local_notifications/issues/923). Depending on your use cases, it may be possible to for you to get by implementing a fork that is used for your own app or implement all of notification functionality on your own
