### ISSUE TITLE
Notifications are not displayed in release mode.

### ISSUE THREAD

**Issue by rockstar4095** [MaikuB/flutter_local_notifications#945]
I added notifications to my app for reminders and they work fine on my device in debug mode, but after installing the release apk file my notifications no longer work. No crashes, just nothig happens. I followed Android Setup instructions in documentation, but I still have this problem.

I have no idea how to find out the reason for this.

My project on github for more details: https://github.com/rockstar4095/reminder_flutter_app/tree/main_screen

**Comment by MaikuB** [comment]
Which device are you using?

**Comment by rockstar4095** [comment]
Galaxy M21.
model: SM-M215F/DSN,
Android version 10.

**Comment by MaikuB** [comment]
Won't get to try your app yet but one thing that sticks out is you created a Proguard rules as per the official docs that is linked to in the readme but looks like you haven't made reference to it as part of the release build configuration, which would've put it around [here](https://github.com/rockstar4095/reminder_flutter_app/blob/a2f0c5bf7fd47f87d0dbeb39fb638d2e4b7db059/android/app/build.gradle#L53). Please see https://developer.android.com/studio/build/shrink-code#enable for more info. The example app's configuration can be found [here](https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/example/android/app/build.gradle) as well.

Speaking of the example app, have you tried creating a release apk to see what happens on the same device?

**Comment by rockstar4095** [comment]
I changed my release configurations you pointed to, but it looks like something is still missing.

Your example app works great in release mode on my device. I'll check documentation and your example app again.

**Comment by MaikuB** [comment]
One thing that stands out at the moment is your `keep.xml` file is  sitting under the `res` folder when it should be under `res/raw` (see example app https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/example/android/app/src/main/res/raw/keep.xml). So what's likely happening is it can't find the icon and is therefore crashing. For crashes, you can use Logcat in Android Studio and take a look at the output https://developer.android.com/studio/debug/am-logcat

**Comment by rockstar4095** [comment]
Yes, that was the cause of my problem. Thanks for your help and your time.

**Comment by Zony-Zhao** [comment]
@MaikuB. What if your example project doesn't work on my device? In debug mode everything goes well. In release mode nothing shows.

**Comment by MaikuB** [comment]
@Zony-Zhao you need to make sure you've cloned/downloaded everything first. Easiest way is to grab the entire repository. I've seen others saying they had issues with this but they had only copied the code when there's more than this involved. If you still have an issue then you might need to investigate further as I haven't seen any reports on this and haven't encountered this issue myself

**Comment by Zony-Zhao** [comment]
I have them double checked. I git cloned, and open the local_notification/example using android studio. And run ` flutter run --release`. Tried with 2 physical devices, no notifiction shows. Could you offer me something to check. What might the problem would be?
```
[√] Flutter (Channel master, 1.25.0-5.0.pre.91, on Microsoft Windows [Version 10.0.19041.685], locale zh-CN)
    • Flutter version 1.25.0-5.0.pre.91 at E:\_dependency\_environment\flutter_windows_1.20.3-stable\flutter
    • Framework revision 7dade22f25 (8 days ago), 2020-12-06 21:34:04 +0530
    • Engine revision 6491c7518f
    • Dart version 2.12.0 (build 2.12.0-120.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\zony\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: E:\_software\editor\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at E:\_software\editor\AndroidStudio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,127.0.0.1,47.105.188.12,192.168.0.12
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains localhost

[√] Connected device (5 available)
    • vivo X21UD A (mobile)       • 21c1c4e8      • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • sdk gphone x86 arm (mobile) • emulator-5556 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 87.0.4280.88
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 87.0.664.60

• No issues found!
```

> @Zony-Zhao you need to make sure you've cloned/downloaded everything first. Easiest way is to grab the entire repository. I've seen others saying they had issues with this but they had only copied the code when there's more than this involved. If you still have an issue then you might need to investigate further as I haven't seen any reports on this and haven't encountered this issue myself

**Comment by MaikuB** [comment]
You can look at the logs using [logcat](https://developer.android.com/studio/debug/am-logcat)

Some questions I've got

- When you say nothing shows, what exactly does this mean? Like you don't see the app at all or there isn't a notification. If it to do with no notification appearing, does this apply to every example including ones where the notification is meant to show immediately (e.g. tap on the button with the text "Show plain notification with payload")?
- Looks like you're on the master channel, have you tried stable channel as the master one is the least stable
- When you run the app using Android Studio, have any changes been made to the app? If you've cloned the repo then Git should be able to highlight the differences. I'm asking this to make sure you haven't done anything like updated the Gradle plugin used by the app. This is something Android Studio tends to prompt and there's been issues with release builds in general for apps
- Does the sample behaviour occur if you build a release apk and load it on your device?

**Comment by Zony-Zhao** [comment]
> You can look at the logs using [logcat](https://developer.android.com/studio/debug/am-logcat)
> 
> Some questions I've got
> 
> * When you say nothing shows, what exactly does this mean? Like you don't see the app at all or there isn't a notification. If it to do with no notification appearing, does this apply to every example including ones where the notification is meant to show immediately (e.g. tap on the button with the text "Show plain notification with payload")?
> * Looks like you're on the master channel, have you tried stable channel as the master one is the least stable
> * When you run the app using Android Studio, have any changes been made to the app? If you've cloned the repo then Git should be able to highlight the differences. I'm asking this to make sure you haven't done anything like updated the Gradle plugin used by the app. This is something Android Studio tends to prompt and there's been issues with release builds in general for apps
> * Does the sample behaviour occur if you build a release apk and load it on your device?

#### Big Thank for your answer!
I have checked something you said.
1. app shows, but whatever button I tap on  , nothing shows.(including show plain text)
2. I switched to stable, it still exits.
3. I just checkout the repo, and enter `flutter run --release` in the terminal ( I think it auto runs `pub get` etc.). Apparently there are many files changed(mostly added). Can you tell me what is the most important to check? I didn't come from android or ios native programming.
4. Both.
For more information. The status bar( I don't know what the exact name is , the row in the top most of android) there is a very mini icon shows, but the notification didn't.
As for logcat, It seems not to be existing in my version of android studio.
![image](https://user-images.githubusercontent.com/50739849/102692530-e7df8580-424e-11eb-8421-e0c92190e6e6.png)

**Comment by Elle-Q** [comment]
@MaikuB i‘ve got the same issue with Zony-Zhao 
here is what i have done for now :
1.  cloned everything from your repo
2.  modified the files below(/\example\android\gradle\wrapper\gradle-wrapper.properties),  change gradle version to 6.7.1
![image](https://user-images.githubusercontent.com/33471396/102707023-20747300-42d2-11eb-9f02-c183ff1674dc.png)
3.   modified the build.gradle file as well,  i set the andoid gradle from 3.6.3 to 4.0.1
![image](https://user-images.githubusercontent.com/33471396/102707062-8b25ae80-42d2-11eb-96bb-ce38b4ee1c90.png)
4. then run `flutter run --release`,  everything goes fine, the only problem i got is that the notification message didnt show in a popup way

**Comment by MaikuB** [comment]
@Zony-Zhao Could you please file another issue on this? Currently you're commenting on a closed issue, which makes it easier for responses to be missed.

@Elle-Q Flutter has had issues if developers updating the Gradle plugin, there were some fixes but they have not made to stable  so if you're on stable channel then you should avoid updating your Gradle plugin for now
