### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by hborole** [MaikuB/flutter_local_notifications#949]
Hi,

I'm fairly new to this but was wondering whether there is any plan to include a method for showing a notification every hour?
Right now iOS Restriction Limit of only 64 Pending Notifications is making it difficult to set & fire more notifications than that.

Kindly assist.

**Comment by MaikuB** [comment]
This is already supported https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/FlutterLocalNotificationsPlugin/periodicallyShow.html

**Comment by hborole** [comment]
Periodically Show only works from current time. Cannot set it at a future date though. I need to set hourly notifications from a selected DateTime.

**Comment by MaikuB** [comment]
I've no plans to add this one in so if your app needs this functionality, I'd suggest forking, making changes and submit a PR so others could make use of it as well
