### ISSUE TITLE
Initialize notification for *only* Android

### ISSUE THREAD

**Issue by seanmavley** [MaikuB/flutter_local_notifications#95]
In all the examples, I see initializing for both Android and iOS.

The notification initializer even forcefully takes Android and iOS values: `new InitializationSettings( android, ios )`

I want to initialize **only** Android. How would I go about that?

**Comment by MaikuB** [comment]
You could just pass in null. Looks like you only aim to run on an Android device so even if you had passed in iOS specific settings, in the end it wouldn't have made a difference either way. The platform-specific settings just control the behaviour when the code is actually run on the associated platform.
