### ISSUE TITLE
zonedSchedule not working on my phone

### ISSUE THREAD

**Issue by draxex** [MaikuB/flutter_local_notifications#953]
Hi,

I used to zonedSchedule to send notifications at the specific time, it works fine on the emulator but when I try different real devices and  schedule notification at the specific time, there is no notification, crash, or error.

Here is my code:

```
tz.initializeTimeZones();

      var now = DateTime.now();

      var time2 = tz.TZDateTime(
        tz.local,
        now.year,
        now.month,
        now.day,
        _selectedTime.hour,
        _selectedTime.minute,
      );

      int notificationID = widget.newActivity.id;

      _flutterLocalNotificationsPlugin
          .zonedSchedule(
              notificationID, title, body, time2, generalNotificationDetails,
              uiLocalNotificationDateInterpretation:
                  UILocalNotificationDateInterpretation.absoluteTime,
              androidAllowWhileIdle: true)
          .then((value) {
        _setAlarm(widget.newActivity.id, _formattedTime);
        setState(() {
          _hasNotification = true;
        });
        print("notification created!");
      });
```

**Comment by superdima05** [comment]
> Hi,
> 
> 
> 
> I used to zonedSchedule to send notifications at the specific time, it works fine on the emulator but when I try different real devices and  schedule notification at the specific time, there is no notification, crash, or error.
> 
> 
> 
> Here is my code:
> 
> 
> 
> ```
> 
> tz.initializeTimeZones();
> 
> 
> 
>       var now = DateTime.now();
> 
> 
> 
>       var time2 = tz.TZDateTime(
> 
>         tz.local,
> 
>         now.year,
> 
>         now.month,
> 
>         now.day,
> 
>         _selectedTime.hour,
> 
>         _selectedTime.minute,
> 
>       );
> 
> 
> 
>       int notificationID = widget.newActivity.id;
> 
> 
> 
>       _flutterLocalNotificationsPlugin
> 
>           .zonedSchedule(
> 
>               notificationID, title, body, time2, generalNotificationDetails,
> 
>               uiLocalNotificationDateInterpretation:
> 
>                   UILocalNotificationDateInterpretation.absoluteTime,
> 
>               androidAllowWhileIdle: true)
> 
>           .then((value) {
> 
>         _setAlarm(widget.newActivity.id, _formattedTime);
> 
>         setState(() {
> 
>           _hasNotification = true;
> 
>         });
> 
>         print("notification created!");
> 
>       });
> 
> ```

I have no error. On Android notifications works good, but on iOS notification doesn't work

**Comment by draxex** [comment]
On my emulator it's working fine, also other notifications working fine real devices like periodicallyShow. I don't know why zonedSchedule not working in real device. Could be any problem with

tz.initializeTimeZones?

________________________________
Gönderen: Dmitriy <notifications@github.com>
Gönderildi: 20 Aralık 2020 Pazar 16:33
Kime: MaikuB/flutter_local_notifications <flutter_local_notifications@noreply.github.com>
Bilgi: draxex <muhamm3d_@hotmail.com>; Author <author@noreply.github.com>
Konu: Re: [MaikuB/flutter_local_notifications] zonedSchedule not working on my phone (#953)


Hi,

I used to zonedSchedule to send notifications at the specific time, it works fine on the emulator but when I try different real devices and schedule notification at the specific time, there is no notification, crash, or error.

Here is my code:


tz.initializeTimeZones();



      var now = DateTime.now();



      var time2 = tz.TZDateTime(

        tz.local,

        now.year,

        now.month,

        now.day,

        _selectedTime.hour,

        _selectedTime.minute,

      );



      int notificationID = widget.newActivity.id;



      _flutterLocalNotificationsPlugin

          .zonedSchedule(

              notificationID, title, body, time2, generalNotificationDetails,

              uiLocalNotificationDateInterpretation:

                  UILocalNotificationDateInterpretation.absoluteTime,

              androidAllowWhileIdle: true)

          .then((value) {

        _setAlarm(widget.newActivity.id, _formattedTime);

        setState(() {

          _hasNotification = true;

        });

        print("notification created!");

      });



I have no error. On Android notifications works good, but on iOS notification doesn't work

**Comment by MaikuB** [comment]
If it's not working, then either your device has restrictions on it (see https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#scheduled-android-notifications) or you're running a release build but haven't completed all of the [configuration](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#release-build-configuration)

**Comment by draxex** [comment]
The problem is appearing when I set a specific time like this:

```
var time2 = tz.TZDateTime(
      tz.local,
      now.year,
      now.month,
      now.day,
      int.parse(splittedHour[0]),
      int.parse(splittedHour[1]),
    );

_flutterLocalNotificationsPlugin
        .zonedSchedule(
            notificationID, title, body, time2, generalNotificationDetails,
            uiLocalNotificationDateInterpretation:
                UILocalNotificationDateInterpretation.absoluteTime,
            androidAllowWhileIdle: true)
```

The above code line is working on the emulator but it isn't working on real devices (I tested with two).  I try to set a notification adding Duration and it's working fine with all of them.

```
_flutterLocalNotificationsPlugin
          .zonedSchedule(
              notificationID,
              title,
              body,
              tz.TZDateTime.now(tz.local).add(Duration(
                  hours: hourDifInt,
                  minutes: minDifInt,
                  seconds: 0,
                  milliseconds: 0)),
```

I don't know maybe problem with  `tz.TZDateTime`, I couldn't find any solution.

**Comment by MaikuB** [comment]
> I don't know maybe problem with tz.TZDateTime

That's very unlikely, I provided links earlier. Have you read them? What devices are you using and are you running in debug or release mode on the devices? If you are running apps on release build then you need to make sure you complete all of the release build configuration

**Comment by draxex** [comment]
Yes, I have read them. Actually, I am running in debug mode on both devices. There is no error message or something. In my emulator, defining specific time working very well but when I connect my real device to my computer with USB, even in debug mode it doesn't work. By the way, other notifications work without any problem like a show and periodicallyShow.

**Comment by MaikuB** [comment]
If you are going to use `tz.local`, it's important that you set what the local timezone as that is what's needed from the `timezone` package for it to work. The example app already does this so you can clone the repo and run the example app to see if it works on the devices, if it still doesn't then would need to what is being reported as the timezone value at this line https://github.com/MaikuB/flutter_local_notifications/blob/235538f246ac81544ead9b17b6d67f15d4bc34be/flutter_local_notifications/example/lib/main.dart#L101

**Comment by draxex** [comment]
Thank you, I am trying now but what should I write instead of **dexterx.dev/flutter_local_notifications_example** in the MethodChannel?

```
const MethodChannel platform =
    MethodChannel('dexterx.dev/flutter_local_notifications_example');
```

**Comment by MaikuB** [comment]
Anything as long as it's unique to the application. Note that I did write in the [readme](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#scheduling-a-notification) about what I mentioned in my previous response and that there's a plugin available on pub for getting the timezone so you don't need to write code that uses platform channels yourself provided you're only targeting Android and iOS

**Comment by draxex** [comment]
I am sorry I am new about it. I just wonder, how can I get my own device timezone by using the TimeZone package. 

In the example, it's always giving us `tz.getLocation("America/Chicago"),` timezone location as an "America/Chicago". How can I make it specific for all device's timezone dynamically?

**Comment by MaikuB** [comment]
Please read the section I linked to earlier in full as I mentioned there that there's a plugin for doing so. The code in the example will do the same thing and returns the timezone based on the device's timezone

**Comment by draxex** [comment]
Okay I got it but the problem is where Can I get the `timeZoneName `variable. In that example after initializing tz, this code line coming to set localLocation  `tz.setLocalLocation(tz.getLocation(timeZoneName)); ` But my question is, what is the variable timeZoneName? What should I assign to that variable. 

In my excode, I already used `tz.local` but in the description of it "by default it is instantiated with UTC" that's the reason why it doesn't work in my real device. 

So my main question is how can I assign variable to `timeZoneName`. In your example It didn't show I think.

**Comment by vanessabin** [comment]
It is shown  in the description of the flutter package. 
It says that you have to initialize it like this: 
` final String timeZoneName = await platform.invokeMethod('getTimeZoneName');`
But actually I am facing the same problem after adding the line above. I don't know how to solve the unhandled exception it is throwing..

**Comment by draxex** [comment]
The problem is solved with flutter_native_timezone 1.0.4 package. In this package, you can get the local timezone and pass parameters.

`final String currentTimeZone = await FlutterNativeTimezone.getLocalTimezone();`

**Comment by d9media** [comment]
What a hassle guys. Why does it need to be so complicated? We can easily get the timezone offset in Flutter so why the dependency on location?

**Comment by MaikuB** [comment]
Scheduling based on offset isn't going to work for places that have daylight savings as that offset would change and this is based on location. This was an issue that had been reported for a long time (e.g. https://github.com/MaikuB/flutter_local_notifications/issues/118 and https://github.com/MaikuB/flutter_local_notifications/issues/179). Using location is the standard approach for those situations (e.g. building an app for airline carriers) where they a recognised timezone database (https://www.iana.org/time-zones)

**Comment by d9media** [comment]
When I pass           `final String currentTimeZone = await FlutterNativeTimezone.getLocalTimezone();`

I get "Location with the name "GMT" doesn't exist"

The thing is that I'm retrieving the messages from Firebase which includes as Timestamp object that is a Date/Time at the user's location. Maybe I didn't fully understand why these conversion back and forward were necessary in the first place but I had expect to simply specify the scheduled times as time and desired timezone and than let the OS handle things.

**Comment by MaikuB** [comment]
Do you mean that `currentTimeZone` is GMT and you schedule a notification with that timezone ID that it fails?

Don't know what conversions you're referring to but if this is still offset then I've described earlier on why IANA-based timezones are used. Some places might also have the same offset but not all observe daylight savings so causes issues in resolving what is the correct behaviour/location

**Comment by d9media** [comment]
> Do you mean that if `currentTimeZone` is GMT and you schedule a notification with that timezone ID that it fails?

Yes my simulator runs in vanilla mode. Do I need to set a location before using the package?

**Comment by MaikuB** [comment]
Looks like it though I don't recall having to set a location for the simulator myself. I'd need to look into the GMT issue, possible the timezone package/IANA database uses something else for GMT and to make a note on it.

**Comment by d9media** [comment]
Thanks! By the way, this was on Android. Have not yet tested on IOS.

**Comment by MaikuB** [comment]
It looks like the `timezone` package defaults to UTC as the local location already but won't allow searching for UTC as a location. Looks like a design choice/limitation for timezone package as they've manually defined UTC as a location [here](https://github.com/srawlins/timezone/blob/bddb27892e1e23afb541c81f6f8863ae636628ae/lib/src/env.dart#L17)

**Comment by d9media** [comment]
I don't know what to make of this. For me it seems like using FlutterNativeTimezone is not a reliable way of setting a zoned schedule but I can't seem to think of another way to reliably retrieving the device timezone other than using native code like the example repo suggests. For now I think I will simply check for this  case and then hardcoding the location to pass.

**Comment by MaikuB** [comment]
I believe you have mixed the packages i was referring to. This isn't to do with that plugin as it does the same thing as it would make the same native API calls that the example app does. The reason why the example makes the calls itself instead of using the plugin is because i the plugin doesn't have macOS support. The `timezone` package I was referring to in my previous post is the one that supports timezone-based date/time classes.

Your approach to map it sounds good I'm case this occurs though I suspect this may only occur an an emulator. From what I've seen on my Android and iOS devices, you can't pick GMT as a timezone as it's all based on locations. Though can't remember if you could skip that when setting up the device for the first time.
