### ISSUE TITLE
Callback when notification is clicked while app is in foreground

### ISSUE THREAD

**Issue by selvas1998** [MaikuB/flutter_local_notifications#954]
While receiving push notification, when i clicked that notification click action not working, so i need one call back for that.

**Comment by MaikuB** [comment]
Note that this plugin is for local notifications so if you're using push notifications then that's something different. This plugin already has a callback for when the user taps on a local notification via the `onSelectNotification` callback parameter for the [`initialize`](https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/FlutterLocalNotificationsPlugin/initialize.html) method. There's an example app in the repository that you can use to test this out. If you reckon you have found a bug then provide a link to a repository with a minimal app using only this plugin. One way of doing so is to fork the repository and to make use of the example app is already.

Note though that currently there are no known issues around the callback so I suspect you may be confusing push notifications and local notifications.

**Comment by MaikuB** [comment]
Closing as no further info has been provided to indicate that there's a bug with the callback provided by the plugin

**Comment by selvas1998** [comment]
Thank you @MaikuB for your support. Yes, I misunderstood about topics between **push_notification** and **local_notification**. Finally, i have done that **onSelectNotification** callback and successfully used.
