### ISSUE TITLE
android 10

### ISSUE THREAD

**Issue by Harsh4598** [MaikuB/flutter_local_notifications#955]
the notification doesn't occur after android 10 devices when the app is terminated.
Have everyone is facing the same problem??

**Comment by mislavlukach** [comment]
I'm using android 11 and can confirm this is an issue.

**Comment by Harsh4598** [comment]
> I'm using android 11 and can confirm this is an issue.

if you found any solution please help me to solve my problem thank you...

**Comment by MaikuB** [comment]
There are no known bugs on scheduling to do with either Android version and I tested on devices with both versions mentioned in this thread. If you're running into an issue then either you are running into a limitation imposed by certain Android device manufacturers or haven't done all of the release build configuration. Both of these are covered in the readme

**Comment by redbayoub** [comment]
I have the same issue especially in android 10

**Comment by MaikuB** [comment]
Closing this as no sample to reproduce has been provided and the only known limitations on this have been documented. I suspect that's the issue you're running into here

**Comment by Harsh4598** [comment]
> Closing this as no sample to reproduce has been provided and the only known limitations on this have been documented. I suspect that's the issue you're running into here

**Comment by Harsh4598** [comment]
need to give no restriction in battery optimization than its work fine.

**Comment by redbayoub** [comment]
there is one thing that's not mentioned in the docs which is if you scheduled 2 or more notifications and the duration between them is less that 15 min your notifications can be delayed by the system even if you enable `allowWihleIdle` 

> These alarms can significantly impact the power use of the device when idle (and thus cause significant battery blame to the app scheduling them), so they should be used with care. To reduce abuse, there are restrictions on how frequently these alarms will go off for a particular application. Under normal system operation, it will not dispatch these alarms more than about every minute (at which point every such pending alarm is dispatched); when in low-power idle modes this duration may be significantly longer, such as 15 minutes.
> [Android Devloper](https://developer.android.com/reference/android/app/AlarmManager.html#setExactAndAllowWhileIdle(int,%20long,%20android.app.PendingIntent))

**Comment by MaikuB** [comment]
@redbayoub as the plugin itself is a wrapper for native APIs, I generally don't include the info that is in the official docs as it's still vital to know how those work given all the properties etc are meant to coincide with what's available natively

**Comment by redbayoub** [comment]
@MaikuB yeah you're right but I think if you add URLs to the official documentation in the plugin docs  for each method is used that would be really good so we can know what method the plugin is using without looking into its code

**Comment by MaikuB** [comment]
@redbayoub if you have suggestions on how this could be improved then I'm happy to look at PRs on this
