### ISSUE TITLE
How to use image from url in BigPictureStyleInformation

### ISSUE THREAD

**Issue by Lawrene16** [MaikuB/flutter_local_notifications#959]
Hello everyone. I am current using this plugin and so far its been wonderful. However, I am building a chat application where users can send photos. I have received my fcm payload containing the photourl. How can i make make the photourl the image in BigPictureStyleInformation

**Comment by MaikuB** [comment]
One way of handling this has been covered in the example app. You download the image and have the image's location on the device passed to the notification. See https://github.com/MaikuB/flutter_local_notifications/blob/235538f246ac81544ead9b17b6d67f15d4bc34be/flutter_local_notifications/example/lib/main.dart#L794
