### ISSUE TITLE
onSelectNotification not call if show LocalNotification in FCM onBackgroundMessage

### ISSUE THREAD

**Issue by JmyW** [MaikuB/flutter_local_notifications#962]
I can make onSelectNotification work if the notification is initiated and showed in my owned code. But I purpose to implement it in onBackgroundMessage. The onBackgroundMessage is used for processing something when message received and can show my own style notification. I received payload and show local notification fine. But I click the notification, the onSelectNotification is never called. Of course, if I show the notification on somewhere like click button in my app, it works fine that onSelectNotification is called when notification is clicked. However, just cannot perform if in onBackgroundMessage. 

Did you see the same symptom? Could you check it?

**Comment by vuitv** [comment]
I I have the same problem
flutter 1.22.2
firebase_core: 0.5.1
firebase_messaging: 7.0.3
flutter_local_notifications: 3.0.1+2

**Comment by MaikuB** [comment]
I don't have a minimal app with background messaging and local notifications working together so not something I can check. My understanding is the callback is triggered when the app is killed so if you tap on the notification while the app is killed, the app should still startup and determine if the notification launched the app like [here](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#getting-details-on-if-the-app-was-launched-via-a-notification-created-by-this-plugin) and have your do what needs to be done

**Comment by MaikuB** [comment]
Forgot to ask something but my understanding was the `onBackgroundMessage` runs on its own isolate so for it to be able to display a local notification, you would've needed to defined an instance of this plugin that is scoped to that method. As such, `onSelectNotification` not being called is actually expected as the method is run in isolate and the plugin instance would've been disposed of once `onBackgroundMessage` was finished. This is a limitation to do with how Flutter handles background execution. If what I've described matches what you're doing, note that I've already filed an issue on the Flutter repo [here](https://github.com/flutter/flutter/issues/23904). It'd be best if you go there and upvote the issue via a "reaction" on my original post. The Flutter team looks at votes as part of prioritising issues

**Comment by JmyW** [comment]
Thanks, done.

**Comment by MaikuB** [comment]
Thanks. As this isn't anything that the plugin can do/fix, I'll be closing this. I'm already tracking the issue I mentioned since that was opened by me so if the Flutter team makes changes that could be taken advantaged of by this plugin then I should be notified of updates to that thread

**Comment by JmyW** [comment]
@MaikuB Do you know if this issue has been fixed by Flutter team? I'm still seeing this issue on latest version.

**Comment by MaikuB** [comment]
@JmyW no I don't and the issue I mentioned is still open. If you are that impacted by it then something you may need to investigate is if a more native solution will work i.e. one where there is reliant on Flutter packages
