### ISSUE TITLE
Callback payloads not working unless go back to where the notification is trigger 

### ISSUE THREAD

**Issue by Mujhtech** [MaikuB/flutter_local_notifications#965]
Please am having issues, anytime I click on a button notification shows up but if I move to another page then click on that notification nothing work for the callback payload but if I go back to where the notification was trigger the callback payload will now work

**Comment by MaikuB** [comment]
Sounds like an issue in how you defined the scope of the instance of the plugin. By that I mean based on what you've described, you created a variable holding the plugin that is scoped to the lifetime of the page or a method that is part of the page. If that is what you've done then, once the user is away from that page, the page would've been disposed including any objects it had. Therefore, the plugin instance no longer exists to receive callbacks so the behaviour you've described is going to be expected. This is why the example app has the plugin be stored as a global variable.

**Comment by Mujhtech** [comment]
OK, let me try to check that again

**Comment by MaikuB** [comment]
Closing as there's been no further updates. I did also notice one of your repos has code that is doing what I described that would cause the issue so this is a programming issue that you'll need to fix
