### ISSUE TITLE
E/MethodChannel#dexterous.com/flutter/local_notifications( 5321): Failed to handle method call

### ISSUE THREAD

**Issue by AllenZYJ** [MaikuB/flutter_local_notifications#967]
## error info 
E/MethodChannel#dexterous.com/flutter/local_notifications( 5321): Failed to handle method call
E/MethodChannel#dexterous.com/flutter/local_notifications( 5321): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
E/MethodChannel#dexterous.com/flutter/local_notifications( 5321): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.setSmallIcon(FlutterLocalNotificationsPlugin.java:188)
E/MethodChannel#dexterous.com/flutter/local_notifications( 5321): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification(FlutterLocalNotificationsPlugin.java:146)
E/MethodChannel#dexterous.com/flutter/local_notifications( 5321): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification(FlutterLocalNotificationsPlugin.java:688)
E/MethodChannel#dexterous.com/flutter/local_notifications( 5321): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.show(FlutterLocalNotificationsPlugin.java:827)
E/MethodChannel#dexterous.com/flutter/local_notifications( 5321): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(FlutterLocalNotificationsPlugin.java:750)
E/MethodChannel#dexterous.com/flutter/local_notifications( 5321): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#dexterous.com/flutter/local_notifications( 5321): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#dexterous.com/flutter/local_notifications( 5321): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:738)
E/MethodChannel#dexterous.com/flutter/local_notifications( 5321): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#dexterous.com/flutter/local_notifications( 5321): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/MethodChannel#dexterous.com/flutter/local_notifications( 5321): 	at android.os.Looper.loop(Looper.java:183)
E/MethodChannel#dexterous.com/flutter/local_notifications( 5321): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/MethodChannel#dexterous.com/flutter/local_notifications( 5321): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#dexterous.com/flutter/local_notifications( 5321): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/MethodChannel#dexterous.com/flutter/local_notifications( 5321): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
# how cause it?

**Comment by AllenZYJ** [comment]
The problem is in my code or env？

**Comment by MaikuB** [comment]
This is typically an issue in your code where the notification icon hasn't been configured and/or specified correctly. You can cross-reference what you're doing with the docs and example app in the repo that you can also run by downloading the entire repo. In the mean time I'll be closing this as there isn't a known bug on this. If you believe you have run into a bug then feel free to file a new issue but use the bug report template to do so
