### ISSUE TITLE
Scheduled notifications dont work

### ISSUE THREAD

**Issue by saadismail** [MaikuB/flutter_local_notifications#97]
Hi,

I am sure that I am missing something but I don't know why. I have tried scheduling notifications through example app and those are working just fine. But when I schedule those in my own app (following the documentation), it schedules the alarms in AlarmManager (Android v8.1.0) but I am not getting the notifications on the phone.

>     RTC_WAKEUP #1: Alarm{deed396 type 0 when 1535946600875 com.example.timetablenotifier}  >tag=*walarm*:com.example.timetablenotifier/com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver
>      type=0 whenElapsed=+1h0m30s608ms when=2018-09-03 08:50:00
>      window=+5d6h0m0s0ms repeatInterval=604800000 count=0 flags=0x0
>      operation=PendingIntent{f2bfb17: PendingIntentRecord{7051b04 com.example.timetablenotifier broadcastIntent}}

Here is how I am scheduling the notifications:

```
var androidPlatformChannelSpecifics = new AndroidNotificationDetails(
      'channel id', 'channel name', 'channel description',
      importance: Importance.Max,
      priority: Priority.High,
      icon: 'ic_launcher',
      onlyAlertOnce: true);
var iOSPlatformChannelSpecifics = new IOSNotificationDetails();
var platformChannelSpecifics = new NotificationDetails(
      androidPlatformChannelSpecifics, iOSPlatformChannelSpecifics);
await flutterLocalNotificationsPlugin.showWeeklyAtDayAndTime(
          0, notificationTitle, notificationBody, new Day(dayI + 2),
          new Time(startTime - 1, 50, 0), platformChannelSpecifics);
```

Any help would be appreciated.

Thanks

**Comment by MaikuB** [comment]
Double check what you've done and compare with the readme, particularly around the Android integration section

**Comment by saadismail** [comment]
Thank you for the response. I have double checked everything and I have also went through the Android Integration section once again and my manifest have everything necessary added there. One thing that is bugging me is that it is adding alarms but notifications are not being showed. 

As suggested, I have this in my manifest:
```
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <uses-permission android:name="android.permission.VIBRATE" />
...
        <receiver android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver" />
        <receiver android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"></action>
            </intent-filter>
        </receiver>
```

Here is scheduled alarm:
>     RTC_WAKEUP #3: Alarm{cb3a906 type 0 when 1535943000172 com.example.timetablenotifier} tag=*walarm*:com.example.timetablenotifier/com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver
>      type=0 whenElapsed=+35s51ms when=2018-09-03 07:50:00
>      window=+5d6h0m0s0ms repeatInterval=604800000 count=0 flags=0x0
>      operation=PendingIntent{6a2fbc7: PendingIntentRecord{f0605f4 com.example.timetablenotifier broadcastIntent}}

But it doesn't show up for some reason.

**Comment by saadismail** [comment]
I am using Day constructor because I have 0th-indexed days in my JSON. I think I have managed to narrow down the issue.

It seems like if I schedule multiple (_showWeeklyAtDayAndTime) notifications at different times, only one that was scheduled last works. Is this the intended behavior or there is some issue? Can you please check if you can replicate this issue?

Thanks

**Comment by saadismail** [comment]
I have managed to reproduce the same issue (on Android 8.1.0 API 27) in examples app.

```
                        await _showWeeklyAtDayAndTime();
                        await _showWeeklyAtDayAndTime2();
```

```
  Future _showWeeklyAtDayAndTime() async {
    var time = new Time(10, 0, 0);
    var androidPlatformChannelSpecifics = new AndroidNotificationDetails(
        'show weekly channel id',
        'show weekly channel name',
        'show weekly description');
    var iOSPlatformChannelSpecifics = new IOSNotificationDetails();
    var platformChannelSpecifics = new NotificationDetails(
        androidPlatformChannelSpecifics, iOSPlatformChannelSpecifics);
    await flutterLocalNotificationsPlugin.showWeeklyAtDayAndTime(
        0,
        'show weekly title',
        'Weekly notification shown on Monday at approximately ${_toTwoDigitString(time.hour)}:${_toTwoDigitString(time.minute)}:${_toTwoDigitString(time.second)}',
        Day.Monday,
        time,
        platformChannelSpecifics);
  }

  Future _showWeeklyAtDayAndTime2() async {
    var time = new Time(10, 5, 0);
    var androidPlatformChannelSpecifics = new AndroidNotificationDetails(
        'show weekly channel id',
        'show weekly channel name',
        'show weekly description');
    var iOSPlatformChannelSpecifics = new IOSNotificationDetails();
    var platformChannelSpecifics = new NotificationDetails(
        androidPlatformChannelSpecifics, iOSPlatformChannelSpecifics);
    await flutterLocalNotificationsPlugin.showWeeklyAtDayAndTime(
        0,
        'show weekly title',
        'Weekly notification shown on Monday at approximately ${_toTwoDigitString(time.hour)}:${_toTwoDigitString(time.minute)}:${_toTwoDigitString(time.second)}',
        Day.Monday,
        time,
        platformChannelSpecifics);
  }
```

I only get a notification at 10:05 and not at 10:00.

**Comment by MaikuB** [comment]
You need to give each notification a unique ID. Just noticed it's your code always uses zero. The timing of the notifications will not be exact, this is documented in the readme already due to how the Android alarm manager works

**Comment by saadismail** [comment]
Thank you so much Michael. I am too dumb using the same notification ID. I am actually moving a native app to flutter and in native app I didn't have to schedule multiple notifications at once so I never had this issue and I know about AlarmManager and its scheduling :)

Closing this issue.

**Comment by MaikuB** [comment]
No worries :)

**Comment by alexandranb** [comment]
Hi,

I have the same problem, and I have different unique ID's for my scheduled notifications. However they are delayed or not received at all when the app is terminated. This is happening specifically for Android 8.1.0, and on other versions of Android works as it should. 

I am kindly asking for your advice.

Thank you

**Comment by RIddhiIroid** [comment]
Hi,

I have the same problem, Please Help. In android 8.1.1

**Comment by NileshChavan26** [comment]
> Thank you so much Michael. I am too dumb using the same notification ID. I am actually moving a native app to flutter and in native app I didn't have to schedule multiple notifications at once so I never had this issue and I know about AlarmManager and its scheduling :)
> 
> Closing this issue.

Hey

> Thank you so much Michael. I am too dumb using the same notification ID. I am actually moving a native app to flutter and in native app I didn't have to schedule multiple notifications at once so I never had this issue and I know about AlarmManager and its scheduling :)
> 
> Closing this issue.

Hey can you please pass this code to me. I am not getting notification

**Comment by NileshChavan26** [comment]
`import 'package:flutter/material.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin;

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    flutterLocalNotificationsPlugin = new FlutterLocalNotificationsPlugin();
    var android = new AndroidInitializationSettings('@mipmap/ic_launcher');
    var ios = new IOSInitializationSettings();
    var initSettings = new InitializationSettings(android, ios);
    flutterLocalNotificationsPlugin.initialize(initSettings,
        onSelectNotification: selectNoti);

    showNotification1();
  }

  Future<void> showNotification1() async {
    await showNotification();
  }

  Future selectNoti(String payload) async {
    debugPrint("Payload: $payload");
    showDialog(
        context: context,
        builder: (_) => new AlertDialog(
              title: new Text("Hello"),
              content: new Text("$payload"),
            ));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        iconTheme: IconThemeData(color: Colors.black),
        backgroundColor: Colors.transparent,
        elevation: 0,
        title: Text('Create Notification'),
        centerTitle: true,
      ),
      body: new RaisedButton(
        onPressed: () async {
          await showNotification();
        },
        child: new Text(
          "Demo",
        ),
      ),
    );
  }

  Future showNotification() async {
    var time = new Time(16, 31, 20);
    var android = new AndroidNotificationDetails(
        "channelId", "channelName", "channelDescription");
    var iOS = new IOSNotificationDetails();
    var platform = new NotificationDetails(android, iOS);
    await flutterLocalNotificationsPlugin.showDailyAtTime(0, 'show daily title',
        'Daily notification shown at approximately ', time, platform);
  }

`}


My Android manifest 

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.noti_exa">
    
        <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
         
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="noti_exa"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <receiver android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver" />
        <receiver android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver">
    <intent-filter>
        <action android:name="android.intent.action.BOOT_COMPLETED"></action>
    </intent-filter>
</receiver>
    </application>
</manifest>



I am not  getting any notification help me

**Comment by bhavyajeet** [comment]
hey, the issue is somewhat similar, notifications get added to the pending list but are never displayed

**Comment by MaikuB** [comment]
I've not seen any reported bugs on this so any problems is likely due to not having done the appropriate configuration so will be up to developers to ensure they have configured everything

**Comment by bhavyajeet** [comment]
Thanks a lot for the response, but the configuration and setup seems to be complete and the instant notifications are working well, it’s just the scheduled notifications that don’t show up

**Comment by MaikuB** [comment]
That instant notifications appear doesn't say much and I get a lot of reports that setup is complete to find that it actually haven't. Based on your response, doesn't look like you are certain on this since you said "seems".

There is an example app in this repository that is fully configured. Can you reproduce the problem in example app? The other thing is if you are sure everything is configured, are you able to provide a minimal sample app that reproduces the problem?

**Comment by bhavyajeet** [comment]
sure i will try to do so if possible, will revisit all my configurations once and compare them with the example app, thank you

**Comment by rishijohri** [comment]
i am facing the same error. I can show notifications using the .show method but schedule method just won't work. I shows up in the pending notifications and the app doesn't show any error whatsoever on button press. I think it might have something to do with AndroidManifest file so could I wanted to ask that are there any changes we have to make in AndroidManifest file for scheduled notification to work

Thanks

**Comment by MaikuB** [comment]
@rishijohri read the readme
