### ISSUE TITLE
does not work in android 10

### ISSUE THREAD

**Issue by hedraadel1** [MaikuB/flutter_local_notifications#973]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Sample code to reproduce the problem**

**Comment by MaikuB** [comment]
You've not filled in the bug report template properly. Please make sure you do so or this will be closed. Myself and others have had this run on Android 10. You should make sure you go through the readme before filing a bug as there's some info listed in the caveats section that may actually relate to your issue
