### ISSUE TITLE
cancelAll() is also cancelling pending intents

### ISSUE THREAD

**Issue by Manuito83** [MaikuB/flutter_local_notifications#977]
This is probably intended (as it can be seen [here](https://github.com/MaikuB/flutter_local_notifications/blob/9267688d51a3b7548dad59211f105376befd1fa9/flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java#L1123)) but, if I'm not mistaken, it can be misleading since Android's [NotificationsManager.cancelAll()](https://developer.android.com/reference/android/app/NotificationManager#cancelAll()) is only cancelling _shown_ notifications and not scheduled ones (pending intents). 

Would it not make sense to have another method for just calling `notificationManager.cancelAll()` and not cancelling pending intents as well? This would be very helpful, for example, when getting rid of shown notifications that come from the FCM without affecting the scheduled ones, as this now requires to set up a MethodChannel to use either `cancel(tag, id)` (if a TAG has been selected, which is not always the case) or `cancelAll()`... when flutter_local_notifications could be doing the same job.

**Comment by MaikuB** [comment]
This is intended as it's not necessarily meant to mirror Android's APIs. If it were then it scheduling wouldn't even supported as it's not actually part of the notification APIs. IMO, the Android API is quite lacking as well unlike the iOS one but I digress...The other thing is, this plugin is meant to work across multiple platforms as such a request to cancel/remove all notifications (i.e. I'm trying to describe this in English) that ends up cancelling all shown and scheduled notifications makes sense. If we were to change it as you say then this would cause an issue on iOS where the old notification API has a [similar method](https://developer.apple.com/documentation/uikit/uiapplication/1622990-cancelalllocalnotifications) that cancels all notifications as well.

If you're in need of a method to cancel only notifications that haven't been shown yet then I would suggest you submit a PR for this that would add another method. Note that there's another PR that supports showing notifications using tags [here](https://github.com/MaikuB/flutter_local_notifications/pull/983)

**Comment by Manuito83** [comment]
Thanks MaikuB. I was not suggesting that the current behaviour of `cancelAll()` should be altered (does not make sense at this stage), but rather that it would be helpful to have another method that calls `notificationManager.cancelAll()` in Android to remove _shown_ notifications (I'm not sure if iOS has something alike). Something like `cancelShown()`. Or maybe adding a parameter to the current method, such as `cancellAll({bool onlyShown = false})`.

Not that I'm in need of another method, I'm handling this directly with a MethodChannel. I was just offering some ideas that I think could be helpful for the package. But this is not for me to say. If you think this adds unnecessary complexity, then there is not much else to say.

**Comment by MaikuB** [comment]
This could be possible as iOS should also support this but I suggest submitting a PR for it as I only work on the plugin in my spare time. Maintaining it and looking at issues takes good chunk of that time as well. Happy to provide guidance on the iOS and macOS side if needed e.g. as feedback on a draft PR

**Comment by MaikuB** [comment]
As there's been no PRs on this, I'm closing this issue. Happy to look at a PR on this should anyone from the community submit one
