### ISSUE TITLE
Add ability to handle when a user has dismissed a notification (or swiped to dismiss) ?

### ISSUE THREAD

**Issue by LeXuanKhanh** [MaikuB/flutter_local_notifications#98]
Hi MaikuB,
Would be great if you add this feature ? because i working with a small alarm feature on my app which let user uncheck some checkboxs if user dismiss the notification (often no one wouldnt click to the notification)

**Comment by MaikuB** [comment]
Your request seems to be a duplicate of #74. Please see my comments in there. Will close this since this is a duplicate
