### ISSUE TITLE
Schedule Notification not working after conversion from utc to local

### ISSUE THREAD

**Issue by AdnanKazi** [MaikuB/flutter_local_notifications#982]
**I was trying to display Schedule Notification based on some time format which is converted from utc**

**Expected Result**
2021-01-16 18:30:00.000000
**Current Result**
2021-01-16 18:30:00.000

**Conclusion**
What I found this plugin works perfectly on 6 digits attached last of the date and time but not working with 3 digits when I convert to date and time from UTC to local but flutter DateTime parser converts it to last 3 digits is there any way this schedule() function accepts this value or is there any way to pass extra 3 digits.

**Behaviour**
Android: This method works perfectly.
IOS: Notification not getting

**Comment by MaikuB** [comment]
Sorry but I don't understand the issue you're describing here. If you're doing date/time conversions then that's not an issue with this plugin. Another thing to note that I require all bugs to use the bug report template as well. What you've got is close (though I don't understand what you've described) but part of this requires a minimal app that can reproduce the problem, which is currently missing.

If this is about the precision of date/time objects, this is a limitation with the native platforms that has been documented [here](https://github.com/MaikuB/flutter_local_notifications/blob/f15cfd1a677e49884d42c6e785eef3788d6247df/flutter_local_notifications/lib/src/flutter_local_notifications_plugin.dart#L253)

**Comment by AdnanKazi** [comment]
@MaikuB Thanks a lot for the response the reason was not the date format it was same id assigned to the more than 1 notifications that was conflicting i should close this issue as it was not related to date and time apart from that this plugin is awesome 🙌
