### ISSUE TITLE
The ability to send different notification periodically

### ISSUE THREAD

**Issue by Vova104** [MaikuB/flutter_local_notifications#987]
Hey!
Are there ability to send different notifications periodically?
For example I want to show notifications every hour with different information. Function showPerdiodically() only allows to send notifications with the same messages.

**Comment by MaikuB** [comment]
No, as the native APIs don't support this. What you're after requires custom logic that you'd need to implement. From memory, when this question has been asked on here, some members of the community were using the `background_fetch` plugin that may be suitable for your scenario
