### ISSUE TITLE
Custom sound not play on android 10 and floating notification not working 

### ISSUE THREAD

**Issue by xang555** [MaikuB/flutter_local_notifications#988]
## **Describe the bug**
- I custom notification sound by following `readme` and test with android 6. that is working very well  but when i  test with android 10 no sound response. 
- i need to show floating notification but not work on android 10 or 6.

## **To Reproduce**
1. cloud function send fcm message to device
2. receive fcm message using firebase_messages
3. show inbox style notification and set `priority` to `high`, `importance` to `max`

## **Expected behavior**
- play custom sound notification on android 8+
- show head-up notification

#### notification manager class

```dart
.
.
.

static FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
      FlutterLocalNotificationsPlugin();

  static final String channelID = "CHATS";
  static final String channelName = "CHATS";
  static final String channelDescription = "Incomming chat notification";

  // init local notification
  Future<void> initNotification() async {
    // initialise the plugin.
    var initializationSettingsAndroid =
        AndroidInitializationSettings('app_icon');
    var initializationSettingsIOS = IOSInitializationSettings();
    var initializationSettings = InitializationSettings(
        android: initializationSettingsAndroid, iOS: initializationSettingsIOS);
    await flutterLocalNotificationsPlugin.initialize(initializationSettings,
        onSelectNotification: (String payload) async {
      await openNotification(payload);
    });

    // create channel
    await createNotificationChannel();

    //init firebase messaging
    firebaseMessaging.configure(
      onBackgroundMessage: _handleNotificationBackground,
      onMessage: (Map<String, dynamic> message) async {
        String dataId = message['data']['id'];
        String dataRoute = message['data']['route'];
        String payload = dataId + "|" + dataRoute;

        String _chatID = message['data']['chatid'];
        String _title = message['data']['title'];
        String _body = message['data']['body'];
        String _icon = message['data']['icon'];
        print("noti image ----> $_icon");

        // show noti with local notification package
        await showNotification(dataId, _chatID, _title, _body, _icon, payload);
      },
      onResume: (Map<String, dynamic> message) async {
        String dataId = message['data']['id'];
        String dataRoute = message['data']['route'];
        String payload = dataId + "|" + dataRoute;
        await openNotification(payload);
      },
      onLaunch: (Map<String, dynamic> message) async {
        String dataId = message['data']['id'];
        String dataRoute = message['data']['route'];
        String payload = dataId + "|" + dataRoute;
        await openNotification(payload);
      },
    );
  }

  // call for show notification
  static Future<void> showNotification(String notiID, String chatID,
      String title, String body, String largeIcon, String payload) async {
    mt.Random random = new mt.Random();
    var id = random.nextInt(1000 - 1);

    List<String> data = payload.split("|");
    String route = data[1];

    List<String> lines = [];

    if (route != "xxxx") {
      var uuid = await getUserUUID();
      if (uuid != null) {
        id = await getChatID(chatID, uuid);
      }
      if (id == null) {
        id = random.nextInt(1000 - 1);
      }
    }

    if (route == "chat" || route == "ads") {
      lines = await getUnreadChatMessage(notiID);
    } else if (route == "groupchat") {
      lines = await getUnreadGroupChatMessage(notiID);
    }

    var _iconPath = await downloadAndSaveFile(largeIcon, "largeIcon");

    var _contentTitleCounter = lines.length > 1 ? "(${lines.length})" : "";
    var _summaryText = lines.length > 10
        ? "${(lines.length / 2).round()}+ more"
        : "${lines.length}";
    final InboxStyleInformation inboxStyleInformation = InboxStyleInformation(
      lines,
      contentTitle: "$title$_contentTitleCounter",
      summaryText: _summaryText,
    );

    var androidPlatformChannelSpecifics = AndroidNotificationDetails(
        channelID, channelName, channelDescription,
        styleInformation: inboxStyleInformation,
        priority: Priority.high,
        importance: Importance.max,
        largeIcon: FilePathAndroidBitmap(_iconPath),
        sound: RawResourceAndroidNotificationSound("duck_quack_short"),  // duck_quack_short is mp3 file in raw folder
        visibility: NotificationVisibility.public);

    var iOSPlatformChannelSpecifics = IOSNotificationDetails();

    var platformChannelSpecifics = NotificationDetails(
        android: androidPlatformChannelSpecifics,
        iOS: iOSPlatformChannelSpecifics);

    await flutterLocalNotificationsPlugin.show(
        id, "$title$_contentTitleCounter", body, platformChannelSpecifics,
        payload: payload);
  }

  // create notification channel for android
  Future<void> createNotificationChannel() async {
    var androidNotificationChannel = AndroidNotificationChannel(
      channelID,
      channelName,
      channelDescription,
      importance: Importance.max,
    );
    await flutterLocalNotificationsPlugin
        .resolvePlatformSpecificImplementation<
            AndroidFlutterLocalNotificationsPlugin>()
        ?.createNotificationChannel(androidNotificationChannel);
  }

.
.
.
```

####  init flutter local notification

```dart
.
.
.
class MyAppState extends State<MyApp> {
  NotificationManager _notificationManager = NotificationManager();

  // get device locale
  Future getDeviceLocale() async {
    deviceLocale = await Devicelocale.currentLocale;
    log("locale ->" + deviceLocale);
  }

  // init main application
  Future<void> initMainApp() async {
    //init notification
    await _notificationManager.initNotification();
    // get device locale
    await getDeviceLocale();
  }

  @override
  initState() {
    super.initState();
    initMainApp();
  }

  @override
  Widget build(BuildContext context) {
    return DynamicTheme(
      defaultBrightness: Brightness.light,
      data: (brightness) =>
          brightness == Brightness.light ? lightTheme : darkTheme,
      themedWidgetBuilder: (context, theme) => MaterialApp(
          navigatorKey: navigatorKey,
          debugShowCheckedModeBanner: false,
          localizationsDelegates: [
            S.delegate,
            GlobalMaterialLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
            GlobalCupertinoLocalizations.delegate,
          ],
          theme: theme,
          supportedLocales: S.delegate.supportedLocales,
          title: 'XXX',
          home: SplashScreen()),
    );
  }
}
.
.
.

```

#### library version
- `firebase_messaging: ^6.0.16`
- `flutter_local_notifications: ^3.0.3`

#### flutter version 

> Flutter 1.22.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8874f21e79 (3 months ago) • 2020-10-29 14:14:35 -0700
Engine • revision a1440ca392
Tools • Dart 2.10.3

#### flutter doctor
> Doctor summary (to see all details, run flutter doctor -v):
  [✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.7 19H15, locale en)
  [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
  [✓] Xcode - develop for iOS and macOS (Xcode 12.3)
  [!] Android Studio (version 4.1)
      ✗ Flutter plugin not installed; this adds Flutter specific functionality.
      ✗ Dart plugin not installed; this adds Dart specific functionality.
  [✓] VS Code (version 1.52.1)
  [✓] Connected device (1 available)
  ! Doctor found issues in 1 category.

#### Notification app info

- ### **android 6**

![137590946_4002273779812538_1488999493015242995_n](https://user-images.githubusercontent.com/14501918/104612132-731a3280-56b8-11eb-9d74-c8ddacbcd521.jpg)

- ### **android 10**

![138334872_747863362467475_3786838041626966327_n](https://user-images.githubusercontent.com/14501918/104610399-a956b280-56b6-11eb-89b8-0d9af77d03b7.jpg)

![138378605_1703532276501530_6304647868196925196_n](https://user-images.githubusercontent.com/14501918/104610403-a9ef4900-56b6-11eb-9599-9b0280c9431f.jpg)

how to fix this problem?. Thanks for your advance

**Comment by MaikuB** [comment]
Bug reports need a link to minimal app to reproduce the problem. What you've provided is code snippets and also contains references to firebase. Note that when it comes to firebase messaging, depending on the state of the app, you may see a notification be displayed automatically, which wouldn't be a result of trying to display a local notification. A minimal app without any references to firebase would help with isolating the issue. Code snippets don't show how everything else like resources have been configured either

Note that the repo has an example app that you can check when it comes to your issue. You could also fork the repo to modify the example and modify it as a way of providing a minimal app that can reproduce the problem.

**Comment by xang555** [comment]
i think this issue cause by custom android os because i using xiaomi mi 10t pro for testing app but when i test with another phone same android version  is working well. Do you have solution for solve this?

**Comment by MaikuB** [comment]
No, restrictions imposed by those manufacturers are something you'll need to workaround with. This may involve prompting users to update their permissions. I can see in one of the screenshots that floating notifications is disabled so not getting a floating notification is expected then. That's not a standard Android setting either and I assume was from Xiaomi. From what I've seen, this seems to be a common thing that there are tutorials for users on enabling the setting. Perhaps Xiaomi has a process where you can have your app added to a list where this setting is on by default but not something I'm familiar with

**Comment by xang555** [comment]
thank you @MaikuB for quick response 
i wondering why Whatsapp and telegram can handle this

**Comment by MaikuB** [comment]
They get special treatment e.g. see https://threema.ch/en/blog/posts/push-android

**Comment by xang555** [comment]
thank you and closing this issue
