### ISSUE TITLE
[ANDROID] Ability to manually set timestamp, needed for starting chromometer at a non-zero value

### ISSUE THREAD

**Issue by hawkinsjb1** [MaikuB/flutter_local_notifications#989]
I am working on a time tracking app which allows the user to start and stop a time log.

I want to show a stop watch in the navigation tray and originally attempted a Flutter-based solution which manually called .show() on the same channel with updated values.. but I realize that would not be performant and hurt the battery and may even have lifecycle issues.

Then I saw android seems to natively allow for a `chromometer`. AWESOME

It seems like I should be able to implement my use-case using android's chromometer, HOWEVER time logs don't always start at 0, so I would need a way to pass a `timestamp` in the past. Does android offer any custom manipulation of a notification's `timestamp`? I know there is a `showWhen` feature.. but I'm not sure if this works for dates in the past. Any insights?

**Comment by MaikuB** [comment]
Chronometer support was added in recent release thanks to a PR (https://github.com/MaikuB/flutter_local_notifications/pull/939) from another member of the community. I'd suggest you take a look at that. There's an example app in the repo (https://github.com/MaikuB/flutter_local_notifications/blob/9267688d51a3b7548dad59211f105376befd1fa9/flutter_local_notifications/example/lib/main.dart#L495)  that you can run by downloading/cloning the repo

**Comment by hawkinsjb1** [comment]
Hi @MaikuB, the chronometer works great, I'm just wondering if it's possible to update the "when" of my notification item to be in the past, this way my chronometer doesn't always have to start at 0

**Comment by hawkinsjb1** [comment]
I'm pretty sure this is possible as I've seen other time tracking apps such as Harvest show notifications with the chronometer starting at wherever the time log left off. The only way for this to be achieved would be adjusting the notification timestamp once it's been shown

**Comment by hawkinsjb1** [comment]
Ahh! The examples you linked show how to set a custom timestamp, this should be all I need, thanks!
