### ISSUE TITLE
Schedule notification count limitations

### ISSUE THREAD

**Issue by onatcipli** [MaikuB/flutter_local_notifications#991]
**Describe the problem**

I'm trying to schedule notifications daily but it is depending on user entry so that In some cases I will be scheduled notifications like up to 1000 notifications.

But When I try to see the pending notifications with **pendingNotificationRequests()** this method, I'm only seeing 64 of them is the rest is scheduled or not. Does this package have a limitation when scheduling notifications?

**Comment by MaikuB** [comment]
What platform were you running the app on when you observed this behaviour?

**Comment by MaikuB** [comment]
Closing due to lack of further response. I would that this was on iOS and this was something that was documented in the readme
