### ISSUE TITLE
Full Screen Intent Notification

### ISSUE THREAD

**Issue by AbdullahChauhan** [MaikuB/flutter_local_notifications#992]
Hello everyone,
I've a question regarding the scenario I come across. I'm using `fullScreenIntent: true` and by using this, the notification is now opening in full screen when device is locked (my specific alarm screen having dismiss button on it). But is there a possibility to dismiss the notification sound on button click similar like when we tap on or slide default notification (appears on top and the sound goes off).

- I want this behavior because I'm exiting the app on button click but notification custom sound still playing until it completes!

**Comment by MaikuB** [comment]
From what I can see, no. The Android notification APIs (see [here](https://developer.android.com/reference/androidx/core/app/NotificationManagerCompat)) doesn't expose anything to stop the sound that is playing

**Comment by AbdullahChauhan** [comment]
Thanks for clarifying. 

One more question, when we tap on notification, the sound goes off and this `onSelectNotification` executed so is it possible to achieve this functionality somewhere else to make the sound mute/stop?

**Comment by MaikuB** [comment]
The callback being invoked has no correlation to the sound stopping if that is what you mean, in which case the answer is no. It's standard Android behaviour for the sound to stop when a notification is tapped on

**Comment by AbdullahChauhan** [comment]
Got it.
