### ISSUE TITLE
crash after flutter upgrade

### ISSUE THREAD

**Issue by bluvrs** [MaikuB/flutter_local_notifications#993]
my app crashes on android after flutter update when the app intends to show a notification

**Comment by MaikuB** [comment]
This doesn't give me much to go on. For all I know, the issue has been there in your app all along but has only surfaced recently. If it's to do with Flutter versions then I'd expect to see more reports on this as well. I've recently had the example app in the repo run on the latest stable and dev version without issues either.

I'll be closing this given the lack of information. If you have a bug to file, file an issue using the bug report template. This needs to link to a repo including a minimal app that can reproduce the problem e.g. a fork of this repo with modifications done to the example app
