### ISSUE TITLE
Scheduled notifications doesn't shows if app is closed

### ISSUE THREAD

**Issue by VolodymyrHanas** [MaikuB/flutter_local_notifications#995]
Scheduled notifications doesn't works properly. If at scheduled time user was outside of the app and app is closed(not loaded in memory) notification doesn't shows. If app is in foreground or background notifications shows as expected. Found this issue on device running Android 10 with MIUI 12, also reproduced this on other Android devices.

**Steps To Reproduce**
1. Open example app.
2. Tap 'Schedule notification to appear in 5 seconds...' button.
3. Force close app.
4. Notification doesn't show. If in this time i try to open app i receive it immediately.

**Expected behavior**
Notifications shows even if i close the app.

**Demo video**

https://user-images.githubusercontent.com/49440930/104839843-89004100-58cc-11eb-8f9e-5779cc35bde3.mp4

**Comment by MaikuB** [comment]
Not a bug with the plugin. Please read https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#scheduled-android-notifications
