### ISSUE TITLE
Notifications dissapears on xiaomi devices

### ISSUE THREAD

**Issue by kinton** [MaikuB/flutter_local_notifications#996]
**Describe the bug**
Hello everyone!
Notifications dissapears on xiaomi devices.

I don't have the devices, but my friends do.
1) Android 10 QP1A.190711.020, MIUI Global 12.0.5 Stable (QGGMIXM)
2) Android 10 QKQ1 190825.002, MIUI Global 12.0.3 Stable (QFKEUXM)
Video with the bug: https://yadi.sk/i/Th1J4z1jcpK3_w

**To Reproduce**
Use xiaomi device (for example, with id=com.kinton.promemory).

**Expected behavior**
Keeps showing until tapped.

**Sample code to reproduce the problem**
Example code as it is with xiaomi devices.

**Comment by MaikuB** [comment]
Your video doesn't demonstrate the issue with the example app in the repo so for all I know, the issue is with the app that is on those devices. The video quality is also blurry and longer than needed. Are you able to upload a video of the example app running on said devices elsewhere and have it shorter so that it's long enough to just demonstrate the issue?

**Comment by kinton** [comment]
@MaikuB Thanks for your reply! How much time do I have to do this?

**Comment by MaikuB** [comment]
I generally close issues with no further updates on ways to reproduce after a week but if you think it'll take longer then I can keep this open provided you let me know me know there's going to be a delay.

Note I've not heard of any issues on notifications disappearing but scheduled notifications will not appear on Xiaomi devices if the app isn't running as I documented [here](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#scheduled-android-notifications). This is a limitation imposed by the manufacturers. If this is actually what you're referring to then there's nothing the plugin can do about it

**Comment by kinton** [comment]
@MaikuB Thanks again for the answer! We will try to check everything carefully. Also I uploaded the wrong video for the first time, my fault, fixed: https://yadi.sk/i/Th1J4z1jcpK3_w

**Comment by MaikuB** [comment]
I don't know what I'm looking at here. You mention an issue in that it can be reproduced in the example app but this new video doesn't show that. So as I mentioned before, this may well be an issue with the app you're building, especially when there are other developers that have had notifications showing on Xiaomi devices.

**Comment by MaikuB** [comment]
Another thing to add there's no description on how to reproduce the problem. Saying to use a Xiaomi device doesn't indicate much and the example app has a lot of code. A video of the example app would indicate which code is run given each button in the app executes a different method
