### ISSUE TITLE
Incompatible with anothers package that have Background Audio Service

### ISSUE THREAD

**Issue by loicgeek** [MaikuB/flutter_local_notifications#999]
**Describe the bug**
I am creating a music player with [https://pub.dev/packages/assets_audio_player](https://pub.dev/packages/assets_audio_player) . It was working fine with backgroung audio support until I decided to add notification with firebase_messaging+flutter_local_notification.

**To Reproduce**
1. Install https://pub.dev/packages/assets_audio_player , firebase_messaging, flutter_local_notifications
2. Configure FCM ,
3. Play a song with a notification
3. Tap On next/prev action
4. Nothing will happen

**Comment by MaikuB** [comment]
This is likely something you'll need to look into to try to fix. For all I know, the issue could be with the music player plugin given firebase messaging and this plugin can work together. I don't maintain the other plugin and look into this would require spending my limited spare time understanding how the other plugin works and is not one I even use.

**Comment by loicgeek** [comment]
@MaikuB ok, ll try on others repo. Thanks
